\ spawn-emitter-test.f - source-shape regression for Darwin spawn emitters.
\ Run: bin/hb --load lib/errors.f lib/string.f lib/test.f lib/fs.f lib/test/src-shape.f tools/spawn-emitter-test.f

require lib/errors.f
require lib/string.f
require lib/test.f
require lib/fs.f
require lib/test/src-shape.f

: SET-LOAD ( -- )
   s" src/habu/habu1.f" SHAPE:LOAD ;

: SET-TEST-HELPERS ( -- )
   s" : SPAWN-DUP2-ACTION ( reg fd -- )" SHAPE:MUST-HAVE
   s" : SPAWN-CHDIR-ACTION ( reg label -- )" SHAPE:MUST-HAVE
   s" : SPAWN-DARWIN-FRAME3-ENTER ( -- )" SHAPE:MUST-HAVE
   s" : SPAWN-DARWIN-FRAME4-ENTER ( -- )" SHAPE:MUST-HAVE
   s" : SPAWN-DARWIN-ACTIONS-RESET ( count -- )" SHAPE:MUST-HAVE
   s" : SPAWN-DARWIN-STDIO-ACTIONS ( -- )" SHAPE:MUST-HAVE
   s" : SPAWN-DARWIN-ZERO-ADESC ( -- )" SHAPE:MUST-HAVE
   s" : SPAWN-DARWIN-ZERO-ATTR ( -- )" SHAPE:MUST-HAVE
   s" : SPAWN-DARWIN-ATTR-DEFAULTS ( -- )" SHAPE:MUST-HAVE
   s" : SPAWN-DARWIN-FILL-ADESC ( -- )" SHAPE:MUST-HAVE
   s" : SPAWN-DARWIN-USE-ADESC ( -- )" SHAPE:MUST-HAVE
   s" : SPAWN-DARWIN-FINISH ( label label -- )" SHAPE:MUST-HAVE ;

: SET-TEST-HELPER-USES ( -- )
   s" SPAWN-DARWIN-FRAME3-ENTER" 4 SHAPE:COUNT=
   s" SPAWN-DARWIN-FRAME3-LEAVE" 4 SHAPE:COUNT=
   s" SPAWN-DARWIN-FRAME4-ENTER" 2 SHAPE:COUNT=
   s" SPAWN-DARWIN-FRAME4-LEAVE" 2 SHAPE:COUNT=
   s" SPAWN-DARWIN-ACTIONS-RESET" 5 SHAPE:COUNT=
   s" SPAWN-DARWIN-STDIO-ACTIONS" 5 SHAPE:COUNT=
   s" SPAWN-DARWIN-ZERO-ADESC" 5 SHAPE:COUNT=
   s" SPAWN-DARWIN-ZERO-ATTR" 5 SHAPE:COUNT=
   s" SPAWN-DARWIN-ATTR-DEFAULTS" 2 SHAPE:COUNT=
   s" SPAWN-DARWIN-FILL-ADESC" 5 SHAPE:COUNT=
   s" SPAWN-DARWIN-USE-ADESC" 5 SHAPE:COUNT=
   s" SPAWN-DARWIN-FINISH" 5 SHAPE:COUNT= ;

: SET-TEST-DARWIN-WRAPPERS ( -- )
   s" 3 >COUNT SPAWN-DARWIN-ACTIONS-RESET" 3 SHAPE:COUNT=
   s" 4 >COUNT SPAWN-DARWIN-ACTIONS-RESET" 1 SHAPE:COUNT=
   s" 6 >REG BSP-DN @ >LABEL SPAWN-CHDIR-ACTION" SHAPE:MUST-HAVE
   s" SPAWN-DARWIN-USE-DEFAULT-ARGV-ENVP" 2 SHAPE:COUNT=
   s" SPAWN-DARWIN-ARGV-DEFAULT-ENVP" 2 SHAPE:COUNT= ;

: SET-TEST-REMOVED-DUPLICATION ( -- )
   s" SP SP 3584 SUBI," SHAPE:MUST-LACK
   s" SP SP 3584 ADDI," SHAPE:MUST-LACK
   s" 13 SP 176 ADDI," SHAPE:MUST-LACK
   s" 15 1040 MOVZ," SHAPE:MUST-LACK
   s" 14 SP 48 STR,  14 SP 56 STR" SHAPE:MUST-LACK ;

: SET-MAIN ( -- )
   T-RESET
   SET-LOAD
   SET-TEST-HELPERS
   SET-TEST-HELPER-USES
   SET-TEST-DARWIN-WRAPPERS
   SET-TEST-REMOVED-DUPLICATION
   T-REPORT
   s" spawn-emitter-test: ok" type cr ;

SET-MAIN
