\ Deferred DATA columns hold quotation fields across growth and two images.
require lib/test.f

package DEFER-QUOT-TEST

STRUCTURE direct 0 DERIVE addr FIELD handler [ n -- n ] ;STRUCTURE
STRUCTURE nested 0 DERIVE addr FIELD item direct ;STRUCTURE
STRUCTURE hook 0 FIELD handler [ n -- n ] ;STRUCTURE
SUMTYPE choice 0
   VARIANT empty ;VARIANT
   VARIANT scalar n ;VARIANT
   VARIANT present hook ;VARIANT
;SUMTYPE
STRUCTURE envelope 0 FIELD item choice ;STRUCTURE

DEFER-LAYOUT-BUFFER DIRECTS direct
DEFER-LAYOUT-BUFFER NESTEDS nested
DEFER-LAYOUT-BUFFER CHOICES envelope
DYNAMIC-BUFFER MAPPED direct
variable LOOKALIKE

: CHECK-MAPPED ( -- )
   1 MAPPED-RESERVE
   [: 12 + ;] DIRECT-MAKE 0 MAPPED !
   16 MAPPED-RESERVE
   30 0 MAPPED DIRECT-HANDLER @ execute 42 T=
   MAPPED-RELEASE ;

: READ-CHOICE ( envelope -- n )
   ENVELOPE-UNMAKE
   MATCH choice
      empty OF 0 ENDOF
      scalar OF 10 + ENDOF
      present OF HOOK-UNMAKE 35 swap execute ENDOF
   ;MATCH ;

: CHECK-FIRST ( -- )
   35 0 DIRECTS DIRECT-HANDLER @ execute 42 T=
   34 0 NESTEDS NESTED-ITEM DIRECT-HANDLER @ execute 42 T=
   0 CHOICES @ READ-CHOICE 42 T= ;

: CHECK-TAIL ( -- )
   37 1 DIRECTS DIRECT-HANDLER @ execute 46 T=
   38 1 NESTEDS NESTED-ITEM DIRECT-HANDLER @ execute 48 T=
   1 CHOICES @ READ-CHOICE LOOKALIKE @ 10 + T=
   2 CHOICES @ READ-CHOICE 0 T= ;

: INIT ( -- )
   2 DIRECTS-BIND 2 NESTEDS-BIND 3 CHOICES-BIND
   [: 7 + ;] DIRECT-MAKE 0 DIRECTS !
   [: 9 + ;] DIRECT-MAKE 1 DIRECTS !
   [: 8 + ;] DIRECT-MAKE NESTED-MAKE 0 NESTEDS !
   [: 10 + ;] DIRECT-MAKE NESTED-MAKE 1 NESTEDS !
   [: 7 + ;] HOOK-MAKE construct choice present ENVELOPE-MAKE 0 CHOICES !
   cp@ 8 - LOOKALIKE !
   LOOKALIKE @ construct choice scalar ENVELOPE-MAKE 1 CHOICES !
   construct choice empty ENVELOPE-MAKE 2 CHOICES !
   CHECK-MAPPED
   CHECK-FIRST CHECK-TAIL
   1 DIRECTS-BIND 1 NESTEDS-BIND 1 CHOICES-BIND
   CHECK-FIRST ;

: REEXPOSE ( -- )
   2 DIRECTS-BIND 2 NESTEDS-BIND 3 CHOICES-BIND
   CHECK-FIRST CHECK-TAIL ;

: GROW ( -- )
   3 DIRECTS-GROW 3 NESTEDS-GROW 4 CHOICES-GROW
   CHECK-FIRST CHECK-TAIL
   3 CHOICES @ READ-CHOICE 0 T=
   6 DIRECTS-GROW 6 NESTEDS-GROW 7 CHOICES-GROW
   CHECK-FIRST CHECK-TAIL
   [: $200000 DIRECTS-GROW ;] E-LAYOUT-CEIL TTHROWSQ
   CHECK-FIRST CHECK-TAIL
   6 CHOICES @ READ-CHOICE 0 T= ;

: CHECK-SWITCH ( -- )
   35 0 DIRECTS DIRECT-HANDLER @ execute 42 T=
   37 1 DIRECTS DIRECT-HANDLER @ execute 46 T=
   34 0 NESTEDS NESTED-ITEM DIRECT-HANDLER @ execute 42 T=
   38 1 NESTEDS NESTED-ITEM DIRECT-HANDLER @ execute 48 T=
   0 CHOICES @ READ-CHOICE LOOKALIKE @ 10 + T=
   1 CHOICES @ READ-CHOICE 48 T=
   6 CHOICES @ READ-CHOICE 0 T= ;

: SWITCH ( -- )
   LOOKALIKE @ construct choice scalar ENVELOPE-MAKE 0 CHOICES !
   [: 13 + ;] HOOK-MAKE construct choice present ENVELOPE-MAKE 1 CHOICES !
   CHECK-SWITCH ;

public

: SECOND ( -- )
   T-RESET REEXPOSE GROW SWITCH CHECK-MAPPED T-REPORT ;

: FINAL ( -- )
   T-RESET CHECK-SWITCH
   CHECK-MAPPED
   T-REPORT ;

T-RESET INIT T-REPORT
;package
