\ generated-declaration-transaction-suite.f - atomic declaration publication.
\ Run: bin/hb --load test/generated-declaration-transaction-suite.f

require lib/test.f
require test/checker-assert.f
require test/decl-diag-capture.f   \ DECL-DIAG: the check tool's own declaration-packet capture

T-RESET

package GENERATED-DECLARATION-TXN-TEST

-7190 constant E-INJECT
-7191 constant E-CLEANUP
-7192 constant E-BODY
-7193 constant E-DIAGNOSTIC
70 constant E-GENERATED-REJECT
7161 constant E-EVENT-TX
7175 constant E-GENERATED-DICTIONARY-CAP

101 constant PARTICIPANT-A
102 constant PARTICIPANT-B
103 constant PARTICIPANT-C
104 constant PARTICIPANT-D
105 constant PARTICIPANT-CORRUPT
109 constant PARTICIPANT-LATE

200 constant ORDER-A
700 constant ORDER-B
850 constant ORDER-C
400 constant ORDER-D
600 constant ORDER-LATE

4 constant TEST-CAP
DECLARATION-TRANSACTION:ROW-CELLS cells constant TEST-ROW-BYTES
DECLARATION-TRANSACTION:STATE-CELLS cells constant TEST-STATE-BYTES
TEST-CAP TEST-ROW-BYTES * constant TEST-TABLE-BYTES

DECLARATION-TRANSACTION:ROW-CELLS cells constant CAP-TEST-ROW-BYTES
DECLARATION-TRANSACTION:STATE-CELLS cells constant CAP-TEST-STATE-BYTES
$7FFFFFFFFFFFFFFF CAP-TEST-ROW-BYTES / constant CAP-TEST-MAX-ROWS
CAP-TEST-MAX-ROWS 2 / constant CAP-TEST-HALF-ROWS
CAP-TEST-MAX-ROWS CAP-TEST-ROW-BYTES * constant CAP-TEST-MAX-BYTES
$5A5A5A5A5A5A5A5A constant CAP-TEST-STATE-SENTINEL
111 constant CAP-TEST-ID
300 constant CAP-TEST-ORDER

create TEST-TABLE TEST-CAP DECLARATION-TRANSACTION:ROW-CELLS * cells allot
create TEST-STATE DECLARATION-TRANSACTION:STATE-CELLS cells allot
create TEST-TABLE-SAVE TEST-TABLE-BYTES allot
create TEST-STATE-SAVE TEST-STATE-BYTES allot

create CAP-TEST-TABLE CAP-TEST-ROW-BYTES allot
create CAP-TEST-TABLE-SAVE CAP-TEST-ROW-BYTES allot
create CAP-TEST-REJECT-TABLE CAP-TEST-ROW-BYTES allot
create CAP-TEST-STATE CAP-TEST-STATE-BYTES allot
create CAP-TEST-STATE-SAVE CAP-TEST-STATE-BYTES allot

PTR-VARIABLE SOURCE-A
variable SOURCE-U
variable FAMILY-N0
variable VARIANT-N0
variable FIELD-N0
variable SCHEMA-N0
variable SCHEMA-ROOT-N0
variable LAYOUT-N0
variable STRING-N0
variable EVENT-N0
variable PROTECTION-ROOM-N0
variable GENERATED-N
variable GENERATED-NAME-PREFLIGHT-N
variable GENERATED-PLAN-BROKEN
variable GENERATED-XREF-ABSENT
variable GENERATED-CHECKER-ABSENT
variable GENERATED-EVENT-STAGED
variable GENERATED-PROTECTION-UNPUBLISHED
variable GENERATED-DICTIONARY-UNPUBLISHED
PTR-VARIABLE NS-EXPECT-A
variable NS-EXPECT-U
variable NS-EXPECT-VARS
variable NS-HOOK-N
variable NS-HOOK-NAME-OK
variable NS-HOOK-META-CLEAR
variable NS-HOOK-PUBLICATION-CLEAR
$2000 constant NS-PKT-CAP
create NS-PKT NS-PKT-CAP allot
variable NS-PKT-U
variable NC-QUERY-N
variable NATIVE-NDICT-N0
variable NATIVE-CP-N0
PTR-VARIABLE NATIVE-DP-N0

$1000 constant NC-SRC-CAP
$FF constant NC-PKG-U
$400 constant NC-SPEC-CAP
NC-SPEC-CAP NC-PKG-U - 1 - constant NC-FAM-U
96 constant NC-DIAG-U
93 constant NC-DIAG-B-U
0 constant NC-ENUM
1 constant NC-SUM
2 constant NC-PROD
3 constant NC-STRUCT
create NC-SRC NC-SRC-CAP allot
variable NC-U

variable SNAPSHOT-TRACE
variable PREPARE-TRACE
variable COMMIT-TRACE
variable ROLLBACK-TRACE
variable RELEASE-TRACE
variable RELEASE-N
variable TRACE-ON

variable FAIL-PHASE
variable FAIL-PARTICIPANT
variable ROLLBACK-FAIL-PARTICIPANT
variable SNAPSHOT-MUTATE-PARTICIPANT
variable BODY-MUTATE
variable BODY-REGISTER
variable BODY-ERROR

variable VALUE-A
variable VALUE-B
variable VALUE-C
variable SAVED-A
variable SAVED-B
variable SAVED-C
variable TRACK-VALUES

variable ALLOCATOR-CALLS
variable ALLOCATOR-FAIL-AT
variable ALLOCATED-BYTES
variable ALLOCATOR-OLD-BYTES
variable ALLOCATOR-NEW-BYTES

variable CAP-TEST-ALLOC-CALLS
variable CAP-TEST-REJECT-ALLOC-CALLS
variable CAP-TEST-N

variable DIAGNOSTIC-COUNT
variable DIAGNOSTIC-PRIMARY
variable DIAGNOSTIC-CLEANUP
variable DIAGNOSTIC-THROWS

variable NESTING-LEFT
variable NESTING-BODIES
defer NESTED-XT ( -- )

5 constant FIRST-GROWN-DEPTH
variable GROW-NESTING-LEFT
variable GROW-NESTING-BODIES
variable GROW-MAX-DEPTH
defer GROW-NESTED-XT ( -- )

variable CHECKER-DEPTH-N0
variable FIELD-DEPTH-N0
variable EVENT-DEPTH-N0
variable STAGED-N0
variable INNER-EVENT-N
variable INNER-FIELD-N
variable WID-N0
variable WID-N1
PTR-VARIABLE TABLE-N0
variable CAP-N0
variable ALLOCATED-N0
variable CAPACITY-PREFLIGHT-N
variable AFTER-FAIL-FAM
variable AFTER-FAIL-FIELD

public

defer CAP-ROWS>BYTES ( n -- n )
defer CAP-NEXT-CAP ( n -- n )
defer CAP-COUNT! ( ptr a n -- )

private

;package

package DECLARATION-TRANSACTION

: CAP-TEST-COUNT! ( ptr a n -- )
   swap ST.N ! ;

: CAP-TEST-INSTALL ( -- )
   [: ROWS>BYTES ;] is GENERATED-DECLARATION-TXN-TEST:CAP-ROWS>BYTES
   [: NEXT-CAP ;] is GENERATED-DECLARATION-TXN-TEST:CAP-NEXT-CAP
   [: CAP-TEST-COUNT! ;] is GENERATED-DECLARATION-TXN-TEST:CAP-COUNT! ;

CAP-TEST-INSTALL

;package

package GENERATED-DECLARATION-TXN-TEST

: CAP-TEST-ALLOC ( ptr a n n -- ptr a )
   CAP-TEST-ALLOC-CALLS @ 1 + CAP-TEST-ALLOC-CALLS !
   2drop ;

: CAP-TEST-REJECT-ALLOC ( ptr a n n -- ptr a )
   CAP-TEST-REJECT-ALLOC-CALLS @ 1 + CAP-TEST-REJECT-ALLOC-CALLS !
   2drop ;

: CAP-TEST-DIAG ( n n -- ) 2drop ;
: CAP-TEST-REJECT-DIAG ( n n -- ) 2drop ;
: CAP-TEST-INERT ( n -- n ) ;
: CAP-TEST-NO-RELEASE ( -- ) ;

: CAP-TEST-FILL-CELLS ( n ptr a n -- )
   {: value:n a:ptr count:n :}
   count 0 ?do
      value a i cells + !
   loop ;

: CAP-TEST-SAVE-STATE ( -- )
   CAP-TEST-STATE BYTE-VIEW CAP-TEST-STATE-SAVE BYTE-VIEW
      CAP-TEST-STATE-BYTES BYTE-COPY ;

: CAP-TEST-SAVE-ALL ( -- )
   CAP-TEST-SAVE-STATE
   CAP-TEST-TABLE BYTE-VIEW CAP-TEST-TABLE-SAVE BYTE-VIEW
      CAP-TEST-ROW-BYTES BYTE-COPY ;

: CAP-TEST-STATE-SAME ( -- )
   CAP-TEST-STATE BYTE-VIEW CAP-TEST-STATE-BYTES
      CAP-TEST-STATE-SAVE BYTE-VIEW CAP-TEST-STATE-BYTES STR= TTRUE ;

: CAP-TEST-ALL-SAME ( -- )
   CAP-TEST-STATE-SAME
   CAP-TEST-TABLE BYTE-VIEW CAP-TEST-ROW-BYTES
      CAP-TEST-TABLE-SAVE BYTE-VIEW CAP-TEST-ROW-BYTES STR= TTRUE ;

: CAP-TEST-ROWS-RUN ( -- )
   CAP-TEST-N @ CAP-ROWS>BYTES drop ;

: CAP-TEST-NEXT-RUN ( -- )
   CAP-TEST-N @ CAP-NEXT-CAP drop ;

: CAP-TEST-ROWS-CATCH ( n -- n )
   CAP-TEST-N !
   [: CAP-TEST-ROWS-RUN ;] catch ;

: CAP-TEST-NEXT-CATCH ( n -- n )
   CAP-TEST-N !
   [: CAP-TEST-NEXT-RUN ;] catch ;

: CAP-TEST-HELPERS ( -- )
   -1 CAP-TEST-ROWS-CATCH
      DECLARATION-TRANSACTION:E-PARTICIPANT-CAPACITY T=
   CAP-TEST-MAX-ROWS CAP-ROWS>BYTES CAP-TEST-MAX-BYTES T=
   CAP-TEST-MAX-ROWS 1 + CAP-TEST-ROWS-CATCH
      DECLARATION-TRANSACTION:E-PARTICIPANT-CAPACITY T=
   CAP-TEST-HALF-ROWS CAP-NEXT-CAP CAP-TEST-HALF-ROWS 2 * T=
   CAP-TEST-HALF-ROWS 1 + CAP-NEXT-CAP CAP-TEST-MAX-ROWS T=
   CAP-TEST-MAX-ROWS CAP-TEST-NEXT-CATCH
      DECLARATION-TRANSACTION:E-PARTICIPANT-CAPACITY T= ;

: CAP-TEST-INIT-RUN ( -- )
   CAP-TEST-STATE CAP-TEST-TABLE CAP-TEST-N @
   [: CAP-TEST-ALLOC ;] [: CAP-TEST-DIAG ;]
   DECLARATION-TRANSACTION:INIT ;

: CAP-TEST-REJECT-INIT-RUN ( -- )
   CAP-TEST-STATE CAP-TEST-REJECT-TABLE CAP-TEST-N @
   [: CAP-TEST-REJECT-ALLOC ;] [: CAP-TEST-REJECT-DIAG ;]
   DECLARATION-TRANSACTION:INIT ;

: CAP-TEST-INIT-CATCH ( n -- n )
   CAP-TEST-N !
   [: CAP-TEST-INIT-RUN ;] catch ;

: CAP-TEST-REJECT-INIT-CATCH ( n -- n )
   CAP-TEST-N !
   [: CAP-TEST-REJECT-INIT-RUN ;] catch ;

: CAP-TEST-INIT ( -- )
   0 CAP-TEST-ALLOC-CALLS !
   CAP-TEST-MAX-ROWS CAP-TEST-INIT-CATCH 0 T= ;

: CAP-TEST-REGISTER ( -- )
   CAP-TEST-STATE CAP-TEST-ID CAP-TEST-ORDER
   [: CAP-TEST-INERT ;] [: CAP-TEST-INERT ;] [: CAP-TEST-INERT ;]
   [: CAP-TEST-INERT ;] [: CAP-TEST-NO-RELEASE ;]
   DECLARATION-TRANSACTION:REGISTER ;

: CAP-TEST-REGISTER-CATCH ( -- n )
   [: CAP-TEST-REGISTER ;] catch ;

: CAP-TEST-COUNT ( n -- )
   CAP-TEST-STATE swap CAP-COUNT! ;

: CAP-TEST-SEED-DUPLICATE ( -- )
   CAP-TEST-REGISTER
   CAP-TEST-STATE DECLARATION-TRANSACTION:COUNT 1 T= ;

: CAP-TEST-INVALID-INIT ( -- )
   0 CAP-TEST-REJECT-ALLOC-CALLS !
   CAP-TEST-STATE-SENTINEL CAP-TEST-STATE
      DECLARATION-TRANSACTION:STATE-CELLS CAP-TEST-FILL-CELLS
   CAP-TEST-SAVE-STATE
   0 CAP-TEST-REJECT-INIT-CATCH
      DECLARATION-TRANSACTION:E-PARTICIPANT-CAPACITY T=
   CAP-TEST-STATE-SAME
   -1 CAP-TEST-REJECT-INIT-CATCH
      DECLARATION-TRANSACTION:E-PARTICIPANT-CAPACITY T=
   CAP-TEST-STATE-SAME
   CAP-TEST-MAX-ROWS 1 + CAP-TEST-REJECT-INIT-CATCH
      DECLARATION-TRANSACTION:E-PARTICIPANT-CAPACITY T=
   CAP-TEST-STATE-SAME
   CAP-TEST-REJECT-ALLOC-CALLS @ 0 T= ;

: CAP-TEST-ACTIVE-BODY ( -- )
   CAP-TEST-MAX-ROWS CAP-TEST-COUNT
   CAP-TEST-SAVE-ALL
   CAP-TEST-REGISTER-CATCH
      DECLARATION-TRANSACTION:E-REGISTRATION-ACTIVE T=
   CAP-TEST-ALLOC-CALLS @ 0 T=
   CAP-TEST-ALL-SAME
   1 CAP-TEST-COUNT ;

: CAP-TEST-ACTIVE-PRECEDENCE ( -- )
   CAP-TEST-INIT
   CAP-TEST-SEED-DUPLICATE
   CAP-TEST-STATE DECLARATION-TRANSACTION:SEAL
   CAP-TEST-STATE [: CAP-TEST-ACTIVE-BODY ;]
      DECLARATION-TRANSACTION:RUN
   CAP-TEST-STATE DECLARATION-TRANSACTION:COUNT 1 T=
   CAP-TEST-STATE DECLARATION-TRANSACTION:DEPTH 0 T= ;

: CAP-TEST-SEALED-PRECEDENCE ( -- )
   CAP-TEST-INIT
   CAP-TEST-SEED-DUPLICATE
   CAP-TEST-MAX-ROWS CAP-TEST-COUNT
   CAP-TEST-STATE DECLARATION-TRANSACTION:SEAL
   CAP-TEST-SAVE-ALL
   CAP-TEST-REGISTER-CATCH
      DECLARATION-TRANSACTION:E-REGISTRATION-SEALED T=
   CAP-TEST-ALLOC-CALLS @ 0 T=
   CAP-TEST-ALL-SAME ;

: CAP-TEST-CAPACITY-PRECEDENCE ( -- )
   CAP-TEST-INIT
   CAP-TEST-SEED-DUPLICATE
   CAP-TEST-MAX-ROWS CAP-TEST-COUNT
   CAP-TEST-SAVE-ALL
   CAP-TEST-REGISTER-CATCH
      DECLARATION-TRANSACTION:E-PARTICIPANT-CAPACITY T=
   CAP-TEST-ALLOC-CALLS @ 0 T=
   CAP-TEST-ALL-SAME ;

: CAP-TEST-RUN ( -- )
   CAP-TEST-HELPERS
   CAP-TEST-INVALID-INIT
   CAP-TEST-ACTIVE-PRECEDENCE
   CAP-TEST-SEALED-PRECEDENCE
   CAP-TEST-CAPACITY-PRECEDENCE ;

: BREAK-GENERATED-EFFECT ( ptr u8 n -- ) {: a:ptr u:n :}
   0 GENERATED-PLAN-BROKEN !
   a u + 1 + dup c@ 40 <> IF
      drop s" generated declaration test: signature opener moved" 76 die
   THEN
   63 swap c!
   -1 GENERATED-PLAN-BROKEN ! ;

: EVALUATE-GENERATED ( ptr u8 n -- )
   GENERATED-N @ 1 + GENERATED-N !
   INCLUDE-EVALUATE ;

TRUSTED: NS-VAR-NS$ ( n -- ptr u8 n ) SUMV-CTOR-NS$ ;
TRUSTED: NS-VAR-SYM@ ( n -- n ) SUMV-CTOR-SYM@ ;

: RECORD-NS-META ( -- )
   SUMV-N@ VARIANT-N0 @ - NS-EXPECT-VARS @ = NS-HOOK-META-CLEAR !
   VARIANT-N0 @
   BEGIN dup SUMV-N@ < WHILE
      dup NS-VAR-NS$ nip 0 <> IF 0 NS-HOOK-META-CLEAR ! THEN
      NS-VAR-SYM@ 0 <> IF 0 NS-HOOK-META-CLEAR ! THEN
      1 +
   REPEAT drop ;

: RECORD-NS-PUBLICATION ( -- )
   ndict@ NATIVE-NDICT-N0 @ =
   cp@ NATIVE-CP-N0 @ = and
   here NATIVE-DP-N0 @ = and
   prot-wid-room PROTECTION-ROOM-N0 @ = and
   GENERATED-DECL-PROTECTION:STAGED-COUNT STAGED-N0 @ = and
   data-base WIDN-CELL + @ WID-N0 @ = and
   NS-HOOK-PUBLICATION-CLEAR ! ;

: OBSERVE-NS ( ptr u8 n -- bool ) {: a:ptr u:n :}
   NS-HOOK-N @ 1 + NS-HOOK-N !
   a u NS-EXPECT-A @ NS-EXPECT-U @ CORE-STR= NS-HOOK-NAME-OK !
   RECORD-NS-META
   RECORD-NS-PUBLICATION
   0 0= ;

: RECORD-PREFLIGHT-NONPUBLICATION ( -- )
   s" GDTX:RED" XREF-FIND XREF-FOUND? 0= GENERATED-XREF-ABSENT !
   s" GDTX:RED" CHECKER-DEFINED? 0= GENERATED-CHECKER-ABSENT !
   \ The declaration's own event rows ARE on the stream by the time generation
   \ runs, and that is the point: commit runs in ascending participant order, so
   \ DECL-EVENT (800) has already promoted this declaration's rows to the
   \ committed watermark before the constructor participant (820) reads them
   \ through the committed provider. The rows are reversible — ASSERT-UNCHANGED
   \ below proves DECL-EVENT:COUNT is back at the baseline after the reject. This
   \ used to read `= EVENT-N0` because the vehicle was sumtype.f's compact ENUM
   \ definer, which wrote registry rows directly and emitted no events at all; the
   \ global ENUM keyword is the unified front end now, so the honest observable at
   \ this instant is that the events are staged, not that they are absent.
   DECL-EVENT:COUNT EVENT-N0 @ > GENERATED-EVENT-STAGED !
   prot-wid-room PROTECTION-ROOM-N0 @ = GENERATED-PROTECTION-UNPUBLISHED !
   ndict@ NATIVE-NDICT-N0 @ =
   cp@ NATIVE-CP-N0 @ = and
   here NATIVE-DP-N0 @ = and GENERATED-DICTIONARY-UNPUBLISHED ! ;

: PREFLIGHT-GENERATED-NAME ( ptr u8 n -- ) {: a:ptr u:n :}
   GENERATED-NAME-PREFLIGHT-N @ 1 + GENERATED-NAME-PREFLIGHT-N !
   a u GENERATED-DECL-NAME-PREFLIGHT:CHECK
   GENERATED-NAME-PREFLIGHT-N @ 2 = IF
      RECORD-PREFLIGHT-NONPUBLICATION
      a u BREAK-GENERATED-EFFECT
   THEN ;

: INSTALL-SECOND-WORD-FAILURE ( -- )
   0 GENERATED-N !
   0 GENERATED-NAME-PREFLIGHT-N !
   0 GENERATED-PLAN-BROKEN !
   0 GENERATED-XREF-ABSENT !
   0 GENERATED-CHECKER-ABSENT !
   0 GENERATED-EVENT-STAGED !
   0 GENERATED-PROTECTION-UNPUBLISHED !
   0 GENERATED-DICTIONARY-UNPUBLISHED !
   [: EVALUATE-GENERATED ;] is TDECL-EVAL-XT
   [: PREFLIGHT-GENERATED-NAME ;] is TDECL-NAME-PREFLIGHT-XT ;

: REJECT-GENERATED-NAME ( ptr u8 n -- )
   GENERATED-NAME-PREFLIGHT-N @ 1 + GENERATED-NAME-PREFLIGHT-N !
   GENERATED-DECL-NAME-PREFLIGHT:CHECK
   E-INJECT throw ;

: INSTALL-NAME-PREFLIGHT-FAILURE ( -- )
   0 GENERATED-N !
   0 GENERATED-NAME-PREFLIGHT-N !
   [: EVALUATE-GENERATED ;] is TDECL-EVAL-XT
   [: REJECT-GENERATED-NAME ;] is TDECL-NAME-PREFLIGHT-XT ;

: FIRST-GENERATED-WORD-U ( ptr u8 n -- n ) {: a:ptr u:n :}
   0
   BEGIN dup u < WHILE
      a over + c@ 10 = IF 1 + EXIT THEN
      1 +
   REPEAT
   drop u ;

: EVALUATE-FIRST-GENERATED-WORD-THEN-FAIL ( ptr u8 n -- ) {: a:ptr u:n :}
   GENERATED-N @ 1 + GENERATED-N !
   a u FIRST-GENERATED-WORD-U {: first-u:n :}
   a first-u INCLUDE-EVALUATE
   E-INJECT throw ;

: INSTALL-EVALUATOR-FAILURE ( -- )
   0 GENERATED-N !
   0 GENERATED-NAME-PREFLIGHT-N !
   [: EVALUATE-FIRST-GENERATED-WORD-THEN-FAIL ;] is TDECL-EVAL-XT
   [: GENERATED-DECL-NAME-PREFLIGHT:CHECK ;] is TDECL-NAME-PREFLIGHT-XT ;

: RESTORE-GENERATED-EVALUATOR ( -- )
   [: INCLUDE-EVALUATE ;] is TDECL-EVAL-XT
   [: GENERATED-DECL-NAME-PREFLIGHT:CHECK ;] is TDECL-NAME-PREFLIGHT-XT
   [: XREF:NAMESPACE? ;] is TDECL-NS-EXISTS-XT ;

: EVALUATE-SOURCE ( -- )
   SOURCE-A @ SOURCE-U @ INCLUDE-EVALUATE ;

: EVALUATE-CATCH ( ptr u8 n -- n )
   SOURCE-U ! SOURCE-A !
   [: EVALUATE-SOURCE ;] catch ;

: WORD-ABSENT? ( ptr u8 n -- bool )
   0 search-wl 0= ;

: QUALIFIED-ABSENT? ( ptr u8 n -- bool )
   XREF-FIND XREF-FOUND? 0= ;

: ASSERT-NO-STALE-CONSTRUCTOR ( ptr u8 n -- )
   CHECK-QUIET-CANDIDATE! 0 T= ;

: TRY-EVENT-CURRENT ( -- )
   DECL-EVENT:CURRENT drop ;

: RECORD-BASELINE ( -- )
   TFAM-N@ FAMILY-N0 !
   SUMV-N@ VARIANT-N0 !
   TYPE-FIELD:COUNT FIELD-N0 !
   SCHEMA-N@ SCHEMA-N0 !
   SCHEMA-ROOT-N@ SCHEMA-ROOT-N0 !
   LAY-N@ LAYOUT-N0 !
   TF-STR-U@ STRING-N0 !
   DECL-EVENT:COUNT EVENT-N0 !
   prot-wid-room PROTECTION-ROOM-N0 ! ;

: RECORD-OWNER-DEPTHS ( -- )
   CHECKER-SCOPE-DEPTH CHECKER-DEPTH-N0 !
   TYPE-FIELD:TX-DEPTH FIELD-DEPTH-N0 !
   DECL-EVENT:DEPTH EVENT-DEPTH-N0 !
   GENERATED-DECL-PROTECTION:STAGED-COUNT STAGED-N0 ! ;

: RECORD-NATIVE-HIGHWATERS ( -- )
   ndict@ NATIVE-NDICT-N0 !
   cp@ NATIVE-CP-N0 !
   here NATIVE-DP-N0 ! ;

: WID-NEXT ( -- n )
   data-base WIDN-CELL + @ ;

: ASSERT-NATIVE-HIGHWATERS ( -- )
   ndict@ NATIVE-NDICT-N0 @ T=
   cp@ NATIVE-CP-N0 @ T=
   here NATIVE-DP-N0 @ = TTRUE ;

: ASSERT-OWNER-DEPTHS ( -- )
   CHECKER-SCOPE-DEPTH CHECKER-DEPTH-N0 @ T=
   TYPE-FIELD:TX-DEPTH FIELD-DEPTH-N0 @ T=
   DECL-EVENT:DEPTH EVENT-DEPTH-N0 @ T=
   GENERATED-DECL-PROTECTION:STAGED-COUNT STAGED-N0 @ T=
   GENERATED-DECL:DEPTH 0 T=
   GENERATED-DECL:POISONED? 0= TTRUE ;

: ASSERT-UNCHANGED ( -- )
   TFAM-N@ FAMILY-N0 @ T=
   SUMV-N@ VARIANT-N0 @ T=
   TYPE-FIELD:COUNT FIELD-N0 @ T=
   SCHEMA-N@ SCHEMA-N0 @ T=
   SCHEMA-ROOT-N@ SCHEMA-ROOT-N0 @ T=
   LAY-N@ LAYOUT-N0 @ T=
   TF-STR-U@ STRING-N0 @ T=
   DECL-EVENT:COUNT EVENT-N0 @ T=
   prot-wid-room PROTECTION-ROOM-N0 @ T= ;

: APPEND-DIGIT ( n ptr a -- ) {: digit:n trace:ptr :}
   TRACE-ON @ 0= IF EXIT THEN
   trace @ 10 * digit + trace ! ;

: RESET-TRACES ( -- )
   0 SNAPSHOT-TRACE !
   0 PREPARE-TRACE !
   0 COMMIT-TRACE !
   0 ROLLBACK-TRACE !
   0 RELEASE-TRACE !
   0 RELEASE-N ! ;

: RESET-CONTROLS ( -- )
   0 FAIL-PHASE !
   0 FAIL-PARTICIPANT !
   0 ROLLBACK-FAIL-PARTICIPANT !
   0 SNAPSHOT-MUTATE-PARTICIPANT !
   0 BODY-MUTATE !
   0 BODY-REGISTER !
   0 BODY-ERROR !
   0 TRACK-VALUES !
   0 TRACE-ON ! ;

: MAYBE-MUTATE-SNAPSHOT ( ptr a n -- ) {: value:ptr participant:n :}
   SNAPSHOT-MUTATE-PARTICIPANT @ participant = IF 1 value +! THEN ;

: MAYBE-FAIL ( n n -- ) {: phase:n participant:n :}
   FAIL-PHASE @ phase = FAIL-PARTICIPANT @ participant = and
      IF E-INJECT throw THEN ;

: MAYBE-FAIL-ROLLBACK ( n -- ) {: participant:n :}
   ROLLBACK-FAIL-PARTICIPANT @ participant = IF E-CLEANUP throw THEN ;

: SNAPSHOT-A ( n -- n ) {: depth:n :}
   TRACK-VALUES @ IF VALUE-A @ SAVED-A ! THEN
   1 SNAPSHOT-TRACE APPEND-DIGIT
   VALUE-A PARTICIPANT-A MAYBE-MUTATE-SNAPSHOT
   GENERATED-DECL:PHASE-SNAPSHOT PARTICIPANT-A MAYBE-FAIL
   depth ;

: PREPARE-A ( n -- n ) {: depth:n :}
   1 PREPARE-TRACE APPEND-DIGIT
   GENERATED-DECL:PHASE-PREPARE PARTICIPANT-A MAYBE-FAIL
   depth ;

: COMMIT-A ( n -- n ) {: depth:n :}
   1 COMMIT-TRACE APPEND-DIGIT
   GENERATED-DECL:PHASE-COMMIT PARTICIPANT-A MAYBE-FAIL
   depth ;

: ROLLBACK-A ( n -- n ) {: depth:n :}
   TRACK-VALUES @ IF SAVED-A @ VALUE-A ! THEN
   1 ROLLBACK-TRACE APPEND-DIGIT
   PARTICIPANT-A MAYBE-FAIL-ROLLBACK
   depth ;

: RELEASE-A ( -- )
   1 RELEASE-TRACE APPEND-DIGIT
   RELEASE-N @ 1 + RELEASE-N ! ;

: SNAPSHOT-B ( n -- n ) {: depth:n :}
   TRACK-VALUES @ IF VALUE-B @ SAVED-B ! THEN
   2 SNAPSHOT-TRACE APPEND-DIGIT
   VALUE-B PARTICIPANT-B MAYBE-MUTATE-SNAPSHOT
   GENERATED-DECL:PHASE-SNAPSHOT PARTICIPANT-B MAYBE-FAIL
   depth ;

: PREPARE-B ( n -- n ) {: depth:n :}
   2 PREPARE-TRACE APPEND-DIGIT
   GENERATED-DECL:PHASE-PREPARE PARTICIPANT-B MAYBE-FAIL
   depth ;

: COMMIT-B ( n -- n ) {: depth:n :}
   2 COMMIT-TRACE APPEND-DIGIT
   GENERATED-DECL:PHASE-COMMIT PARTICIPANT-B MAYBE-FAIL
   depth ;

: ROLLBACK-B ( n -- n ) {: depth:n :}
   TRACK-VALUES @ IF SAVED-B @ VALUE-B ! THEN
   2 ROLLBACK-TRACE APPEND-DIGIT
   PARTICIPANT-B MAYBE-FAIL-ROLLBACK
   depth ;

: RELEASE-B ( -- )
   2 RELEASE-TRACE APPEND-DIGIT
   RELEASE-N @ 1 + RELEASE-N ! ;

: SNAPSHOT-C ( n -- n ) {: depth:n :}
   TRACK-VALUES @ IF VALUE-C @ SAVED-C ! THEN
   3 SNAPSHOT-TRACE APPEND-DIGIT
   VALUE-C PARTICIPANT-C MAYBE-MUTATE-SNAPSHOT
   GENERATED-DECL:PHASE-SNAPSHOT PARTICIPANT-C MAYBE-FAIL
   depth ;

: PREPARE-C ( n -- n ) {: depth:n :}
   3 PREPARE-TRACE APPEND-DIGIT
   GENERATED-DECL:PHASE-PREPARE PARTICIPANT-C MAYBE-FAIL
   depth ;

: COMMIT-C ( n -- n ) {: depth:n :}
   3 COMMIT-TRACE APPEND-DIGIT
   GENERATED-DECL:PHASE-COMMIT PARTICIPANT-C MAYBE-FAIL
   depth ;

: ROLLBACK-C ( n -- n ) {: depth:n :}
   TRACK-VALUES @ IF SAVED-C @ VALUE-C ! THEN
   3 ROLLBACK-TRACE APPEND-DIGIT
   PARTICIPANT-C MAYBE-FAIL-ROLLBACK
   depth ;

: RELEASE-C ( -- )
   3 RELEASE-TRACE APPEND-DIGIT
   RELEASE-N @ 1 + RELEASE-N ! ;

: REGISTER-A ( -- )
   TEST-STATE PARTICIPANT-A ORDER-A
   [: SNAPSHOT-A ;] [: PREPARE-A ;] [: COMMIT-A ;]
   [: ROLLBACK-A ;] [: RELEASE-A ;]
   DECLARATION-TRANSACTION:REGISTER ;

: REGISTER-B ( -- )
   TEST-STATE PARTICIPANT-B ORDER-B
   [: SNAPSHOT-B ;] [: PREPARE-B ;] [: COMMIT-B ;]
   [: ROLLBACK-B ;] [: RELEASE-B ;]
   DECLARATION-TRANSACTION:REGISTER ;

: REGISTER-C ( -- )
   TEST-STATE PARTICIPANT-C ORDER-C
   [: SNAPSHOT-C ;] [: PREPARE-C ;] [: COMMIT-C ;]
   [: ROLLBACK-C ;] [: RELEASE-C ;]
   DECLARATION-TRANSACTION:REGISTER ;

: INERT ( n -- n ) ;

: NO-RELEASE ( -- ) ;

: CORRUPT-SNAPSHOT ( n -- n ) 1 + ;

: SNAPSHOT-D ( n -- n ) {: depth:n :}
   4 SNAPSHOT-TRACE APPEND-DIGIT
   depth ;

: SNAPSHOT-LATE ( n -- n ) {: depth:n :}
   5 SNAPSHOT-TRACE APPEND-DIGIT
   depth ;

: REGISTER-D ( -- )
   TEST-STATE PARTICIPANT-D ORDER-D
   [: SNAPSHOT-D ;] [: INERT ;] [: INERT ;] [: INERT ;] [: NO-RELEASE ;]
   DECLARATION-TRANSACTION:REGISTER ;

: REGISTER-LATE ( -- )
   TEST-STATE PARTICIPANT-LATE ORDER-LATE
   [: SNAPSHOT-LATE ;] [: INERT ;] [: INERT ;] [: INERT ;] [: NO-RELEASE ;]
   DECLARATION-TRANSACTION:REGISTER ;

: REGISTER-CORRUPT ( -- )
   TEST-STATE PARTICIPANT-CORRUPT ORDER-A
   [: CORRUPT-SNAPSHOT ;]
   [: INERT ;] [: INERT ;] [: INERT ;] [: NO-RELEASE ;]
   DECLARATION-TRANSACTION:REGISTER ;

: SAVE-TEST-BYTES ( -- )
   TEST-STATE BYTE-VIEW TEST-STATE-SAVE BYTE-VIEW TEST-STATE-BYTES BYTE-COPY
   TEST-TABLE BYTE-VIEW TEST-TABLE-SAVE BYTE-VIEW TEST-TABLE-BYTES BYTE-COPY ;

: ASSERT-TEST-BYTES ( -- )
   TEST-STATE BYTE-VIEW TEST-STATE-BYTES
      TEST-STATE-SAVE BYTE-VIEW TEST-STATE-BYTES STR= TTRUE
   TEST-TABLE BYTE-VIEW TEST-TABLE-BYTES
      TEST-TABLE-SAVE BYTE-VIEW TEST-TABLE-BYTES STR= TTRUE ;

: REGISTER-A-CATCH ( -- n )
   [: REGISTER-A ;] catch ;

: REGISTER-B-CATCH ( -- n )
   [: REGISTER-B ;] catch ;

: REGISTER-LATE-CATCH ( -- n )
   [: REGISTER-LATE ;] catch ;

: INJECTING-ALLOCATOR ( ptr a n n -- ptr a )
   {: base:ptr oldbytes:n newbytes:n :}
   ALLOCATOR-CALLS @ 1 + dup ALLOCATOR-CALLS !
   oldbytes ALLOCATOR-OLD-BYTES !
   newbytes ALLOCATOR-NEW-BYTES !
   ALLOCATOR-FAIL-AT @ = IF E-INJECT throw THEN
   base oldbytes newbytes DECLARATION-TRANSACTION:DEFAULT-ALLOCATOR {: grown:ptr :}
   newbytes ALLOCATED-BYTES +!
   grown ;

: INSTALL-ALLOCATOR-FAILURE ( n -- )
   ALLOCATOR-FAIL-AT !
   0 ALLOCATOR-CALLS ! ;

: RECORD-DIAGNOSTIC ( n n -- ) {: primary:n cleanup:n :}
   primary DIAGNOSTIC-PRIMARY !
   cleanup DIAGNOSTIC-CLEANUP !
   DIAGNOSTIC-COUNT @ 1 + DIAGNOSTIC-COUNT !
   DIAGNOSTIC-THROWS @ IF E-DIAGNOSTIC throw THEN ;

: RESET-DIAGNOSTIC ( -- )
   0 DIAGNOSTIC-COUNT !
   0 DIAGNOSTIC-PRIMARY !
   0 DIAGNOSTIC-CLEANUP !
   0 DIAGNOSTIC-THROWS ! ;

: INIT-TEST-COORDINATOR ( -- )
   0 ALLOCATOR-CALLS !
   0 ALLOCATOR-FAIL-AT !
   0 ALLOCATED-BYTES !
   0 ALLOCATOR-OLD-BYTES !
   0 ALLOCATOR-NEW-BYTES !
   RESET-DIAGNOSTIC
   TEST-STATE TEST-TABLE TEST-CAP
   [: INJECTING-ALLOCATOR ;]
   [: RECORD-DIAGNOSTIC ;]
   DECLARATION-TRANSACTION:INIT ;

: REGISTER-TEST-PARTICIPANTS ( -- )
   REGISTER-A REGISTER-B REGISTER-C REGISTER-D REGISTER-LATE
   TEST-STATE DECLARATION-TRANSACTION:SEAL ;

: TRANSACTION-BODY ( -- )
   BODY-MUTATE @ IF
      10 VALUE-A +!
      20 VALUE-B +!
      30 VALUE-C +!
   THEN
   BODY-REGISTER @ IF REGISTER-D THEN
   BODY-ERROR @ dup 0 <> IF throw THEN drop ;

: RUN-BODY ( -- )
   TEST-STATE [: TRANSACTION-BODY ;] DECLARATION-TRANSACTION:RUN ;

: RUN-BODY-CATCH ( -- n )
   [: RUN-BODY ;] catch ;

: NESTED-BODY ( -- )
   NESTING-BODIES @ 1 + NESTING-BODIES !
   NESTING-LEFT @ 0 > IF
      NESTING-LEFT @ 1 - NESTING-LEFT !
      TEST-STATE [: NESTED-XT ;] DECLARATION-TRANSACTION:RUN
   THEN ;

: INSTALL-NESTED ( -- )
   [: NESTED-BODY ;] is NESTED-XT ;
INSTALL-NESTED

: RUN-NESTED ( n -- )
   NESTING-LEFT !
   0 NESTING-BODIES !
   TEST-STATE [: NESTED-BODY ;] DECLARATION-TRANSACTION:RUN ;

: SET-VALUES ( n n n -- )
   VALUE-C ! VALUE-B ! VALUE-A ! ;

: ASSERT-VALUES ( n n n -- )
   {: a:n b:n c:n :}
   VALUE-A @ a T=
   VALUE-B @ b T=
   VALUE-C @ c T= ;

: ASSERT-IDLE ( -- )
   TEST-STATE DECLARATION-TRANSACTION:DEPTH 0 T= ;

: ASSERT-PRODUCTION-IDLE ( -- )
   GENERATED-DECL:DEPTH 0 T= ;

: TEST-REGISTRATION ( -- )
   TEST-STATE DECLARATION-TRANSACTION:COUNT 0 T=
   REGISTER-A
   TEST-STATE DECLARATION-TRANSACTION:COUNT 1 T=
   REGISTER-A-CATCH DECLARATION-TRANSACTION:E-PARTICIPANT-DUP T=
   REGISTER-B REGISTER-C REGISTER-D
   TEST-STATE DECLARATION-TRANSACTION:COUNT 4 T=

   TEST-STATE DECLARATION-TRANSACTION:TABLE TABLE-N0 !
   TEST-STATE DECLARATION-TRANSACTION:CAPACITY CAP-N0 !
   ALLOCATED-BYTES @ ALLOCATED-N0 !
   SAVE-TEST-BYTES
   1 INSTALL-ALLOCATOR-FAILURE
   REGISTER-LATE-CATCH E-INJECT T=
   ALLOCATOR-CALLS @ 1 T=
   TEST-STATE DECLARATION-TRANSACTION:COUNT 4 T=
   TEST-STATE DECLARATION-TRANSACTION:TABLE TABLE-N0 @ = TTRUE
   TEST-STATE DECLARATION-TRANSACTION:CAPACITY CAP-N0 @ T=
   ALLOCATED-BYTES @ ALLOCATED-N0 @ T=
   ASSERT-TEST-BYTES

   0 ALLOCATOR-FAIL-AT !
   REGISTER-LATE
   TEST-STATE DECLARATION-TRANSACTION:COUNT 5 T=
   TEST-STATE DECLARATION-TRANSACTION:CAPACITY TEST-CAP 2 * T=
   ALLOCATOR-OLD-BYTES @ TEST-TABLE-BYTES T=
   ALLOCATOR-NEW-BYTES @ TEST-TABLE-BYTES 2 * T=
   ALLOCATED-BYTES @ ALLOCATED-N0 @ > TTRUE
   TEST-STATE DECLARATION-TRANSACTION:SEAL
   REGISTER-LATE-CATCH DECLARATION-TRANSACTION:E-REGISTRATION-SEALED T=

   \ Five sealed production participants: the checker frame (100), DECL-EVENT
   \ (800), constructor generation (820), the native dictionary (850), and
   \ protection (900), which registers last and seals the set.
   GENERATED-DECL:COUNT 5 T=
   GENERATED-DECL:SEALED? TTRUE
   s" GENERATED-DECL:REGISTER" WORD-ABSENT? TTRUE
   s" GENERATED-DECL:ALLOCATOR!" WORD-ABSENT? TTRUE
   s" GENERATED-DECL:DIAGNOSTIC!" WORD-ABSENT? TTRUE
   s" GENERATED-DECL:RESET" WORD-ABSENT? TTRUE
   s" GENERATED-DECL:SEAL" WORD-ABSENT? TTRUE
   s" CHECKER-DECL-FRAME:INSTALL" QUALIFIED-ABSENT? TTRUE
   s" CHECKER-DECL-FRAME:INSTALL" CHECKER-DEFINED? 0= TTRUE
   \ The four declaration-frame words are closed into the package PRIVATE
   \ wordlist, so no caller outside the checker can reach them and no test can
   \ drive RELEASE directly. That confinement is why "RELEASE must stay
   \ throw-free" cannot be observed behaviourally from here: the only body that
   \ could shift the product-field transaction depth across RELEASE is one that
   \ leaks a declaration-event frame, and src/core/decl-event.f rejects that at
   \ the participant's PREPARE (DEV-PART-PROVE -> DEV-TX-OPEN-REQUIRE, throwing
   \ E-DEV-TX with the depths restored), which test/decl-event-suite.f §19e
   \ already pins including the failing phase. Swapping RELEASE for the ordinary
   \ CHECKER-SCOPE-FINALIZE would therefore survive every behavioural suite in the
   \ repository. test/declaration-release-inventory.f is what makes that swap
   \ fail: it reads the production sources and rejects any throw, catch,
   \ allocation, lookup, validation, or publication reachable from a registered
   \ release callback. The rows below stay as the second guard, because they fail
   \ the moment anyone opens a public seam onto the frame words.
   s" CHECKER-DECL-FRAME:START" QUALIFIED-ABSENT? TTRUE
   s" CHECKER-DECL-FRAME:PREPARE" QUALIFIED-ABSENT? TTRUE
   s" CHECKER-DECL-FRAME:ROLLBACK" QUALIFIED-ABSENT? TTRUE
   s" CHECKER-DECL-FRAME:RELEASE" QUALIFIED-ABSENT? TTRUE
   s" CHECKER-DECL-FRAME:RELEASE" CHECKER-DEFINED? 0= TTRUE
   s" GENERATED-DECL-OWNER:REGISTER" QUALIFIED-ABSENT? TTRUE
   s" GENERATED-DECL-OWNER:REGISTER-LAST" QUALIFIED-ABSENT? TTRUE
   s" GENERATED-DECL-OWNER:RUN" QUALIFIED-ABSENT? TTRUE
   s" GENERATED-DECL-OWNER:DEPTH" QUALIFIED-ABSENT? TTRUE ;

: TEST-PHASE-ORDER ( -- )
   RESET-CONTROLS RESET-TRACES
   -1 TRACE-ON !
   RUN-BODY
   SNAPSHOT-TRACE @ 14523 T=
   PREPARE-TRACE @ 123 T=
   COMMIT-TRACE @ 123 T=
   RELEASE-TRACE @ 321 T=
   ROLLBACK-TRACE @ 0 T=
   ASSERT-IDLE ;

: TEST-ACTIVE-REGISTRATION ( -- )
   RESET-CONTROLS
   -1 BODY-REGISTER !
   RUN-BODY-CATCH DECLARATION-TRANSACTION:E-REGISTRATION-ACTIVE T=
   TEST-STATE DECLARATION-TRANSACTION:COUNT 5 T=
   TEST-STATE DECLARATION-TRANSACTION:LAST-FAILURE-PHASE GENERATED-DECL:PHASE-BODY T=
   TEST-STATE DECLARATION-TRANSACTION:LAST-FAILURE-PARTICIPANT -1 T=
   ASSERT-IDLE ;

: TEST-PARTIAL-SNAPSHOT ( -- )
   RESET-CONTROLS RESET-TRACES RESET-DIAGNOSTIC
   10 20 30 SET-VALUES
   -1 TRACK-VALUES !
   -1 TRACE-ON !
   PARTICIPANT-B SNAPSHOT-MUTATE-PARTICIPANT !
   GENERATED-DECL:PHASE-SNAPSHOT FAIL-PHASE !
   PARTICIPANT-B FAIL-PARTICIPANT !
   RUN-BODY-CATCH E-INJECT T=
   SNAPSHOT-TRACE @ 1452 T=
   ROLLBACK-TRACE @ 21 T=
   10 20 30 ASSERT-VALUES
   TEST-STATE DECLARATION-TRANSACTION:LAST-FAILURE-PHASE GENERATED-DECL:PHASE-SNAPSHOT T=
   TEST-STATE DECLARATION-TRANSACTION:LAST-FAILURE-PARTICIPANT PARTICIPANT-B T=
   DIAGNOSTIC-PRIMARY @ E-INJECT T=
   DIAGNOSTIC-CLEANUP @ 0 T=
   ASSERT-IDLE ;

: TEST-PREPARE-FAILURE ( -- )
   RESET-CONTROLS RESET-TRACES
   10 20 30 SET-VALUES
   -1 TRACK-VALUES !
   -1 TRACE-ON !
   -1 BODY-MUTATE !
   GENERATED-DECL:PHASE-PREPARE FAIL-PHASE !
   PARTICIPANT-B FAIL-PARTICIPANT !
   RUN-BODY-CATCH E-INJECT T=
   SNAPSHOT-TRACE @ 14523 T=
   PREPARE-TRACE @ 12 T=
   COMMIT-TRACE @ 0 T=
   ROLLBACK-TRACE @ 321 T=
   10 20 30 ASSERT-VALUES
   TEST-STATE DECLARATION-TRANSACTION:LAST-FAILURE-PHASE GENERATED-DECL:PHASE-PREPARE T=
   TEST-STATE DECLARATION-TRANSACTION:LAST-FAILURE-PARTICIPANT PARTICIPANT-B T=
   ASSERT-IDLE ;

: TEST-COMMIT-FAILURE ( -- )
   RESET-CONTROLS RESET-TRACES
   10 20 30 SET-VALUES
   -1 TRACK-VALUES !
   -1 TRACE-ON !
   -1 BODY-MUTATE !
   GENERATED-DECL:PHASE-COMMIT FAIL-PHASE !
   PARTICIPANT-B FAIL-PARTICIPANT !
   RUN-BODY-CATCH E-INJECT T=
   SNAPSHOT-TRACE @ 14523 T=
   PREPARE-TRACE @ 123 T=
   COMMIT-TRACE @ 12 T=
   ROLLBACK-TRACE @ 321 T=
   RELEASE-TRACE @ 0 T=
   10 20 30 ASSERT-VALUES
   TEST-STATE DECLARATION-TRANSACTION:LAST-FAILURE-PHASE GENERATED-DECL:PHASE-COMMIT T=
   TEST-STATE DECLARATION-TRANSACTION:LAST-FAILURE-PARTICIPANT PARTICIPANT-B T=
   ASSERT-IDLE ;

: TEST-ROLLBACK-CLEANUP ( -- )
   RESET-CONTROLS RESET-TRACES RESET-DIAGNOSTIC
   10 20 30 SET-VALUES
   -1 TRACK-VALUES !
   -1 TRACE-ON !
   -1 BODY-MUTATE !
   E-BODY BODY-ERROR !
   PARTICIPANT-B ROLLBACK-FAIL-PARTICIPANT !
   -1 DIAGNOSTIC-THROWS !
   RUN-BODY-CATCH E-BODY T=
   ROLLBACK-TRACE @ 321 T=
   10 20 30 ASSERT-VALUES
   DIAGNOSTIC-COUNT @ 1 T=
   DIAGNOSTIC-PRIMARY @ E-BODY T=
   DIAGNOSTIC-CLEANUP @ E-CLEANUP T=
   TEST-STATE DECLARATION-TRANSACTION:LAST-CLEANUP-PARTICIPANT PARTICIPANT-B T=
   TEST-STATE DECLARATION-TRANSACTION:POISONED? TTRUE
   RUN-BODY-CATCH DECLARATION-TRANSACTION:E-TRANSACTION-POISONED T=
   ASSERT-IDLE ;

\ Release is the phase that CANNOT report anything.  This test used to be
\ TEST-FINALIZE-CLEANUP: it injected a failure into the last phase and pinned the
\ old behaviour — the transaction threw, called the diagnostic with a zero
\ primary error, named a cleanup participant, and poisoned the coordinator, all
\ AFTER every reversible commit had already published.  That pin is retired with
\ the injection seam that fed it; a release callback now takes nothing, returns
\ nothing, and has no error channel to inject into.  What the run below proves is
\ the opposite property: once every commit succeeds the transaction is over, so
\ RUN returns normally, the diagnostic is never called, no cleanup participant is
\ recorded, the coordinator stays usable, and every participant is still released
\ in reverse order.
: TEST-RELEASE-AFTER-PUBLICATION ( -- )
   RESET-CONTROLS RESET-TRACES RESET-DIAGNOSTIC
   -1 TRACE-ON !
   RUN-BODY-CATCH 0 T=
   RELEASE-TRACE @ 321 T=
   COMMIT-TRACE @ 123 T=
   DIAGNOSTIC-COUNT @ 0 T=
   TEST-STATE DECLARATION-TRANSACTION:LAST-CLEANUP-PARTICIPANT -1 T=
   TEST-STATE DECLARATION-TRANSACTION:POISONED? 0= TTRUE
   RUN-BODY-CATCH 0 T=
   ASSERT-IDLE ;

: TEST-CALLBACK-DEPTH ( -- )
   INIT-TEST-COORDINATOR
   REGISTER-CORRUPT
   TEST-STATE DECLARATION-TRANSACTION:SEAL
   RUN-BODY-CATCH DECLARATION-TRANSACTION:E-PARTICIPANT-DEPTH T=
   TEST-STATE DECLARATION-TRANSACTION:LAST-FAILURE-PHASE GENERATED-DECL:PHASE-SNAPSHOT T=
   TEST-STATE DECLARATION-TRANSACTION:LAST-FAILURE-PARTICIPANT PARTICIPANT-CORRUPT T=
   TEST-STATE DECLARATION-TRANSACTION:POISONED? TTRUE
   RUN-BODY-CATCH DECLARATION-TRANSACTION:E-TRANSACTION-POISONED T=
   ASSERT-IDLE ;

\ Three of the five registered participants count their own releases, so a run
\ nested 13 deep must record exactly 3 releases per depth: one per active
\ participant at every depth, no depth skipped and none released twice.
: TEST-NESTING-GROWTH ( -- )
   RESET-CONTROLS RESET-TRACES
   12 RUN-NESTED
   NESTING-BODIES @ 13 T=
   RELEASE-N @ 13 3 * T=
   ASSERT-IDLE ;

: GROW-NESTED-BODY ( -- )
   GROW-NESTING-BODIES @ 1 + GROW-NESTING-BODIES !
   GENERATED-DECL:DEPTH GROW-MAX-DEPTH @ max GROW-MAX-DEPTH !
   GROW-NESTING-LEFT @ 0 > IF
      GROW-NESTING-LEFT @ 1 - GROW-NESTING-LEFT !
      [: GROW-NESTED-XT ;] GENERATED-DECL:RUN
   THEN ;

: INSTALL-GROW-NESTED ( -- )
   [: GROW-NESTED-BODY ;] is GROW-NESTED-XT ;
INSTALL-GROW-NESTED

: RUN-TO-GROWN-DEPTH ( -- )
   FIRST-GROWN-DEPTH GENERATED-DECL:DEPTH - 1 - GROW-NESTING-LEFT !
   0 GROW-NESTING-BODIES !
   0 GROW-MAX-DEPTH !
   [: GROW-NESTED-XT ;] GENERATED-DECL:RUN ;

: EVALUATE-INNER-DECLARATION ( -- )
   s" STRUCTURE gdnested 0 FIELD x n ;STRUCTURE" INCLUDE-EVALUATE ;

: EVALUATE-OUTER-WORD ( -- )
   s" package gdrow public : MARK ( -- n ) 1 ; ;package" INCLUDE-EVALUATE ;

: EVALUATE-GROW-WORD ( -- )
   s" package gdgrow public : MARK ( -- n ) 1 ; ;package" INCLUDE-EVALUATE ;

: EVALUATE-DATA-WORD ( -- )
   s" package gddata public variable CELL ;package" INCLUDE-EVALUATE ;

: OUTER-NESTED-BODY ( -- )
   EVALUATE-OUTER-WORD
   EVALUATE-INNER-DECLARATION
   DECL-EVENT:COUNT INNER-EVENT-N !
   TYPE-FIELD:COUNT INNER-FIELD-N ! ;

: OUTER-NESTED-FAIL-BODY ( -- )
   OUTER-NESTED-BODY
   E-BODY throw ;

: RUN-OUTER-NESTED-FAIL-BODY ( -- )
   [: OUTER-NESTED-FAIL-BODY ;] GENERATED-DECL:RUN ;

: RUN-OUTER-NESTED-FAIL ( -- n )
   [: RUN-OUTER-NESTED-FAIL-BODY ;] catch ;

: GROW-OUTER-BODY ( -- )
   EVALUATE-GROW-WORD
   RUN-TO-GROWN-DEPTH
   E-BODY throw ;

: RUN-GROW-OUTER ( -- )
   [: GROW-OUTER-BODY ;] GENERATED-DECL:RUN ;

: RUN-GROW-OUTER-CATCH ( -- n )
   [: RUN-GROW-OUTER ;] catch ;

: DATA-FAIL-BODY ( -- )
   EVALUATE-DATA-WORD
   E-BODY throw ;

: RUN-DATA-FAIL ( -- )
   [: DATA-FAIL-BODY ;] GENERATED-DECL:RUN ;

: RUN-DATA-FAIL-CATCH ( -- n )
   [: RUN-DATA-FAIL ;] catch ;

: TEST-PRODUCTION-FRAME-GROWTH ( -- )
   RECORD-OWNER-DEPTHS RECORD-NATIVE-HIGHWATERS
   RUN-GROW-OUTER-CATCH E-BODY T=
   GROW-MAX-DEPTH @ FIRST-GROWN-DEPTH T=
   GROW-NESTING-BODIES @ FIRST-GROWN-DEPTH 1 - T=
   ASSERT-OWNER-DEPTHS ASSERT-NATIVE-HIGHWATERS
   s" GDGROW:MARK" QUALIFIED-ABSENT? TTRUE ;

\ The same nesting, but succeeding, on the real generated-declaration path.
\ Every production participant's savepoint is a depth counter or a per-depth
\ slot, so "one release per active participant at every nesting depth" is exactly
\ "every owner depth is back at its baseline afterwards": a skipped release
\ leaves a depth high, a doubled release drives it below the baseline, and both
\ fail ASSERT-OWNER-DEPTHS. The declaration inside the outermost body also
\ exercises the event and field owners, not just the dictionary and protection
\ owners, and its word must be visible at the end because release runs after
\ publication, never instead of it.
: EVALUATE-NESTED-OK-DECLARATION ( -- )
   s" STRUCTURE gdnestok 0 FIELD x n ;STRUCTURE" INCLUDE-EVALUATE ;

: PRODUCTION-NESTED-SUCCESS-BODY ( -- )
   EVALUATE-NESTED-OK-DECLARATION
   RUN-TO-GROWN-DEPTH ;

: RUN-PRODUCTION-NESTED-SUCCESS ( -- )
   [: PRODUCTION-NESTED-SUCCESS-BODY ;] GENERATED-DECL:RUN ;

: TEST-PRODUCTION-NESTED-RELEASE ( -- )
   RECORD-BASELINE RECORD-OWNER-DEPTHS
   RUN-PRODUCTION-NESTED-SUCCESS
   GROW-MAX-DEPTH @ FIRST-GROWN-DEPTH T=
   GROW-NESTING-BODIES @ FIRST-GROWN-DEPTH 1 - T=
   ASSERT-OWNER-DEPTHS
   ASSERT-PRODUCTION-IDLE
   DECL-EVENT:COUNT EVENT-N0 @ > TTRUE
   TYPE-FIELD:COUNT FIELD-N0 @ > TTRUE
   s" GDNESTOK:MAKE" QUALIFIED-ABSENT? 0= TTRUE
   s" GDNESTOK-ROUNDTRIP ( n -- n ) GDNESTOK:MAKE GDNESTOK:UNMAKE"
      CHECK-QUIET-CANDIDATE! 0 <> TTRUE ;

: TEST-DATA-ROLLBACK ( -- )
   RECORD-OWNER-DEPTHS RECORD-NATIVE-HIGHWATERS
   RUN-DATA-FAIL-CATCH E-BODY T=
   ASSERT-OWNER-DEPTHS ASSERT-NATIVE-HIGHWATERS
   s" GDDATA:CELL" QUALIFIED-ABSENT? TTRUE ;

: TEST-OUTER-CHECKER-SCOPE ( -- )
   RECORD-OWNER-DEPTHS
   CHECKER-SCOPE-START
   CHECKER-SCOPE-DEPTH CHECKER-DEPTH-N0 @ 1 + T=
   s" STRUCTURE gdouterscope 0 FIELD x n ;STRUCTURE" EVALUATE-CATCH 0 T=
   CHECKER-SCOPE-DEPTH CHECKER-DEPTH-N0 @ 1 + T=
   s" GDOUTERSCOPE-ROUNDTRIP ( n -- n ) GDOUTERSCOPE:MAKE GDOUTERSCOPE:UNMAKE"
      CHECK-QUIET-CANDIDATE! 0 <> TTRUE
   GENERATED-DECL:POISONED? 0= TTRUE
   CHECKER-SCOPE-DONE
   ASSERT-OWNER-DEPTHS ;

: EVALUATE-CHECKER-LEAK-DECLARATION ( -- )
   s" STRUCTURE gdcheckerleak 0 FIELD x n ;STRUCTURE" INCLUDE-EVALUATE ;

: CHECKER-LEAK-BODY ( -- )
   EVALUATE-CHECKER-LEAK-DECLARATION
   CHECKER-SCOPE-START ;

: RUN-CHECKER-LEAK-BODY ( -- )
   [: CHECKER-LEAK-BODY ;] GENERATED-DECL:RUN ;

: RUN-CHECKER-LEAK ( -- n )
   [: RUN-CHECKER-LEAK-BODY ;] catch ;

: TEST-CHECKER-LEAK-PREPARE ( -- )
   RECORD-BASELINE RECORD-OWNER-DEPTHS RECORD-NATIVE-HIGHWATERS
   CHECKER-SCOPE-START
   CHECKER-SCOPE-DEPTH CHECKER-DEPTH-N0 @ 1 + T=
   RUN-CHECKER-LEAK DECLARATION-TRANSACTION:E-PARTICIPANT-DEPTH T=
   GENERATED-DECL:LAST-FAILURE-PHASE GENERATED-DECL:PHASE-PREPARE T=
   GENERATED-DECL:LAST-FAILURE-PARTICIPANT 1 T=
   CHECKER-SCOPE-DEPTH CHECKER-DEPTH-N0 @ 1 + T=
   GENERATED-DECL:POISONED? 0= TTRUE
   ASSERT-UNCHANGED ASSERT-NATIVE-HIGHWATERS
   s" GDCHECKERLEAK:MAKE" QUALIFIED-ABSENT? TTRUE
   CHECKER-SCOPE-DONE
   ASSERT-OWNER-DEPTHS ;

\ Frame records are reused as the rollback stack rises and falls, so the owner
\ mark must be rewritten on every push, not just when a declaration claims the
\ frame. This test seeds one slot with a finished declaration's coordinator depth
\ and then makes an ordinary scope land on that exact slot inside a declaration
\ at the same coordinator depth: two scopes, one successful declaration (its
\ frame takes the third slot and is released), one scope closed, then a
\ declaration whose body leaks a scope onto the seeded slot. A push that failed
\ to reset the mark would leave the stale depth in place and PREPARE would accept
\ the leaked scope as the declaration's own frame.
: EVALUATE-RECYCLE-SEED-WORD ( -- )
   s" package gdrecycleseed public : MARK ( -- n ) 1 ; ;package" INCLUDE-EVALUATE ;

: RUN-RECYCLE-SEED ( -- )
   [: EVALUATE-RECYCLE-SEED-WORD ;] GENERATED-DECL:RUN ;

: EVALUATE-RECYCLE-LEAK-WORD ( -- )
   s" package gdrecycleleak public : MARK ( -- n ) 1 ; ;package" INCLUDE-EVALUATE ;

: RECYCLE-LEAK-BODY ( -- )
   EVALUATE-RECYCLE-LEAK-WORD
   CHECKER-SCOPE-START ;

: RUN-RECYCLE-LEAK-BODY ( -- )
   [: RECYCLE-LEAK-BODY ;] GENERATED-DECL:RUN ;

: RUN-RECYCLE-LEAK ( -- n )
   [: RUN-RECYCLE-LEAK-BODY ;] catch ;

: TEST-RECYCLED-SLOT-LEAK ( -- )
   RECORD-OWNER-DEPTHS RECORD-NATIVE-HIGHWATERS
   CHECKER-SCOPE-START CHECKER-SCOPE-START
   CHECKER-SCOPE-DEPTH CHECKER-DEPTH-N0 @ 2 + T=
   RUN-RECYCLE-SEED
   CHECKER-SCOPE-DEPTH CHECKER-DEPTH-N0 @ 2 + T=
   CHECKER-SCOPE-DONE
   RUN-RECYCLE-LEAK DECLARATION-TRANSACTION:E-PARTICIPANT-DEPTH T=
   GENERATED-DECL:LAST-FAILURE-PHASE GENERATED-DECL:PHASE-PREPARE T=
   GENERATED-DECL:LAST-FAILURE-PARTICIPANT 1 T=
   CHECKER-SCOPE-DEPTH CHECKER-DEPTH-N0 @ 1 + T=
   GENERATED-DECL:POISONED? 0= TTRUE
   s" GDRECYCLELEAK:MARK" QUALIFIED-ABSENT? TTRUE
   s" GDRECYCLESEED:MARK" QUALIFIED-ABSENT? 0= TTRUE
   CHECKER-SCOPE-DONE
   ASSERT-OWNER-DEPTHS ;

: TEST-NESTED-DECLARATION-ROLLBACK ( -- )
   RECORD-BASELINE RECORD-OWNER-DEPTHS RECORD-NATIVE-HIGHWATERS
   WID-NEXT WID-N0 !
   CHECKER-SCOPE-START
   CHECKER-SCOPE-DEPTH CHECKER-DEPTH-N0 @ 1 + T=
   RUN-OUTER-NESTED-FAIL E-BODY T=
   INNER-EVENT-N @ EVENT-N0 @ T=
   INNER-FIELD-N @ FIELD-N0 @ T=
   ASSERT-UNCHANGED
   CHECKER-SCOPE-DEPTH CHECKER-DEPTH-N0 @ 1 + T=
   ASSERT-NATIVE-HIGHWATERS
   WID-NEXT dup WID-N1 ! WID-N0 @ > TTRUE
   s" GDROW:MARK" QUALIFIED-ABSENT? TTRUE
   s" GDNESTED:MAKE" WORD-ABSENT? TTRUE

   [: OUTER-NESTED-BODY ;] GENERATED-DECL:RUN
   INNER-EVENT-N @ EVENT-N0 @ T=
   INNER-FIELD-N @ FIELD-N0 @ T=
   DECL-EVENT:COUNT EVENT-N0 @ > TTRUE
   TYPE-FIELD:COUNT FIELD-N0 @ > TTRUE
   WID-NEXT WID-N1 @ > TTRUE
   s" GDROW:MARK" QUALIFIED-ABSENT? 0= TTRUE
   s" GDNESTED-ROUNDTRIP ( n -- n ) GDNESTED:MAKE GDNESTED:UNMAKE"
      CHECK-QUIET-CANDIDATE! 0 <> TTRUE
   CHECKER-SCOPE-DEPTH CHECKER-DEPTH-N0 @ 1 + T=
   ASSERT-PRODUCTION-IDLE
   CHECKER-SCOPE-DONE
   ASSERT-OWNER-DEPTHS ;

: TEST-NAME-PREFLIGHT-CLEARS-AUTHORITY ( -- )
   RECORD-BASELINE RECORD-OWNER-DEPTHS RECORD-NATIVE-HIGHWATERS
   INSTALL-NAME-PREFLIGHT-FAILURE
   \ The vehicle is the global ENUM keyword, which is the unified front end. Its
   \ rejects are rendered as a declaration packet before they are rethrown, so the
   \ expected diagnostic is captured and asserted rather than left on stderr — the
   \ legacy compact definer printed nothing for a generation-phase failure, since
   \ its constructor step ran outside the body its reporter guarded.
   DECL-DIAG:PROSE
   s" ENUM gdnamefail left right ;ENUM" EVALUATE-CATCH E-INJECT T=
   s" habu: bad enum declaration 'gdnamefail': declaration failed at 'gdnamefail'"
   DECL-DIAG:HAS? TTRUE
   DECL-DIAG:OFF
   RESTORE-GENERATED-EVALUATOR
   GENERATED-N @ 0 T=
   GENERATED-NAME-PREFLIGHT-N @ 1 T=
   s" GDNAMEFAIL:LEFT ( -- ) 0" ASSERT-NO-STALE-CONSTRUCTOR
   s" GDNAMEFAIL:LEFT" QUALIFIED-ABSENT? TTRUE
   ASSERT-UNCHANGED ASSERT-OWNER-DEPTHS ASSERT-NATIVE-HIGHWATERS ;

: TEST-GENERATOR-ROLLBACK ( -- )
   RESET-CONTROLS RESET-TRACES RESET-DIAGNOSTIC
   RECORD-BASELINE RECORD-OWNER-DEPTHS
   RECORD-NATIVE-HIGHWATERS
   INSTALL-SECOND-WORD-FAILURE
   DECL-DIAG:PROSE
   s" ENUM gdtx red blue ;ENUM" EVALUATE-CATCH
      E-GENERATED-REJECT T=
   s" habu: bad enum declaration 'gdtx': declaration failed at 'gdtx'"
   DECL-DIAG:HAS? TTRUE
   DECL-DIAG:OFF
   RESTORE-GENERATED-EVALUATOR
   GENERATED-N @ 0 T=
   GENERATED-NAME-PREFLIGHT-N @ 2 T=
   s" plan broken at the second word" T-LABEL GENERATED-PLAN-BROKEN @ TTRUE
   s" xref absent when generation ran" T-LABEL GENERATED-XREF-ABSENT @ TTRUE
   s" checker row absent when generation ran" T-LABEL GENERATED-CHECKER-ABSENT @ TTRUE
   s" event rows staged when generation ran" T-LABEL GENERATED-EVENT-STAGED @ TTRUE
   s" protection unpublished when generation ran" T-LABEL
   GENERATED-PROTECTION-UNPUBLISHED @ TTRUE
   s" dictionary unpublished when generation ran" T-LABEL
   GENERATED-DICTIONARY-UNPUBLISHED @ TTRUE
   ASSERT-UNCHANGED
   ASSERT-OWNER-DEPTHS
   ASSERT-NATIVE-HIGHWATERS
   s" GDTX:RED" WORD-ABSENT? TTRUE
   s" GDTX:RED" QUALIFIED-ABSENT? TTRUE
   s" GDTX:BLUE" QUALIFIED-ABSENT? TTRUE
   s" GDTX:RED" CHECKER-DEFINED? 0= TTRUE
   s" GDTX:BLUE" CHECKER-DEFINED? 0= TTRUE
   s" GDTX:RED ( -- ) 0" ASSERT-NO-STALE-CONSTRUCTOR
   s" package gdtx ;package" EVALUATE-CATCH 0 T=
   ASSERT-PRODUCTION-IDLE ;

: TEST-EVALUATOR-FAILURE-CLEARS-AUTHORITY ( -- )
   RECORD-BASELINE RECORD-OWNER-DEPTHS RECORD-NATIVE-HIGHWATERS
   INSTALL-EVALUATOR-FAILURE
   s" PRODUCT gdevalfail 0 FIELD value n ;PRODUCT" EVALUATE-CATCH E-INJECT T=
   RESTORE-GENERATED-EVALUATOR
   GENERATED-N @ 1 T=
   s" GDEVALFAIL:MAKE" QUALIFIED-ABSENT? TTRUE
   s" GDEVALFAIL:UNMAKE" QUALIFIED-ABSENT? TTRUE
   s" GDEVALFAIL-MAKE ( n -- gdevalfail ) GDEVALFAIL:MAKE"
      ASSERT-NO-STALE-CONSTRUCTOR
   ASSERT-UNCHANGED ASSERT-OWNER-DEPTHS ASSERT-NATIVE-HIGHWATERS
   [: TRY-EVENT-CURRENT ;] catch E-EVENT-TX T=

   \ The next real declaration must consume the exact rolled-back field/event
   \ ids. Public committed reflection therefore detects provisional leaks
   \ without exposing either owner's private arena.
   s" PRODUCT gdafterfail 0 FIELD clean n ;PRODUCT" EVALUATE-CATCH 0 T=
   DECL-EVENT:COUNT EVENT-N0 @ 3 + T=
   TYPE-FIELD:COUNT FIELD-N0 @ 1 + T=
   EVENT-N0 @ DECL-EVENT:DECL? TTRUE
   EVENT-N0 @ 1 + DECL-EVENT:ARITY? TTRUE
   EVENT-N0 @ 2 + DECL-EVENT:FIELD? TTRUE
   EVENT-N0 @ DECL-EVENT:FAMILY@ AFTER-FAIL-FAM !
   EVENT-N0 @ 1 + DECL-EVENT:FAMILY@ AFTER-FAIL-FAM @ T=
   EVENT-N0 @ 2 + DECL-EVENT:FAMILY@ AFTER-FAIL-FAM @ T=
   EVENT-N0 @ 1 + DECL-EVENT:VAR@ 0 T=
   EVENT-N0 @ 2 + DECL-EVENT:FIELD@ AFTER-FAIL-FIELD !
   AFTER-FAIL-FIELD @ FIELD-N0 @ T=
   AFTER-FAIL-FIELD @ TYPE-FIELD:FAMILY@ AFTER-FAIL-FAM @ T=
   AFTER-FAIL-FIELD @ TYPE-FIELD:VARIANT@ TYPE-FIELD:NO-VARIANT T=
   AFTER-FAIL-FIELD @ TYPE-FIELD:NAME$ s" clean" T$=
   AFTER-FAIL-FIELD @ TYPE-FIELD:SCHEMA@ SCHEMA-ROOT-N0 @ T=
   AFTER-FAIL-FIELD @ TYPE-FIELD:SLOT@ 0 T=
   AFTER-FAIL-FIELD @ TYPE-FIELD:CELLS@ 1 T=
   AFTER-FAIL-FIELD @ TYPE-FIELD:BYTE-OFF@ 0 T=
   AFTER-FAIL-FIELD @ TYPE-FIELD:BYTES@ CELL T=
   AFTER-FAIL-FIELD @ TYPE-FIELD:ALIGN@ CELL T=
   AFTER-FAIL-FIELD @ TYPE-FIELD:FLAGS@ 0 T=
   ASSERT-OWNER-DEPTHS
   ASSERT-PRODUCTION-IDLE ;

: SETUP-NAMESPACE-COLLISIONS ( -- )
   s" package gdpreenum ;package" INCLUDE-EVALUATE
   s" package gdpresum ;package" INCLUDE-EVALUATE
   s" package gdpreprod ;package" INCLUDE-EVALUATE
   s" package gdprestruct ;package" INCLUDE-EVALUATE
   s" package gdpretype ;package package gdpretype:result ;package" INCLUDE-EVALUATE
   s" GDPRETYPE:RESULT" XREF:FINALIZE-NAMESPACE drop
   s" package gdboth public : MAKE ( n -- n ) ; ;package" INCLUDE-EVALUATE ;

: NS-PKT-RESET ( -- )
   0 NS-PKT-U ! ;

: NS-PKT-C, ( n -- )
   NS-PKT-U @ NS-PKT-CAP >= IF
      s" namespace packet oracle too long" 76 die
   THEN
   NS-PKT NS-PKT-U @ + c!
   NS-PKT-U @ 1 + NS-PKT-U ! ;

: NS-PKT-APP ( ptr u8 n -- ) {: a:ptr u:n :}
   0 BEGIN dup u < WHILE
      dup a + c@ NS-PKT-C,
      1 +
   REPEAT drop ;

: NS-PACKET$ ( ptr u8 n ptr u8 n ptr u8 n ptr u8 n -- ptr u8 n )
   {: kind:ptr kindu:n family:ptr familyu:n token:ptr tokenu:n why:ptr whyu:n :}
   NS-PKT-RESET
   s" habu: bad " NS-PKT-APP
   kind kindu NS-PKT-APP
   s"  declaration '" NS-PKT-APP
   family familyu NS-PKT-APP
   s" ': " NS-PKT-APP
   why whyu NS-PKT-APP
   tokenu 0 > IF
      s"  at '" NS-PKT-APP
      token tokenu NS-PKT-APP
      39 NS-PKT-C,
   THEN
   10 NS-PKT-C,
   NS-PKT NS-PKT-U @ ;

: NS-DIAG$ ( ptr u8 n ptr u8 n -- ptr u8 n )
   {: kind:ptr kindu:n family:ptr familyu:n :}
   kind kindu family familyu family familyu
   s" xref: generated namespace already exists" NS-PACKET$ ;

: NS-EVAL ( ptr u8 n ptr u8 n ptr u8 n -- )
   {: src:ptr srcu:n kind:ptr kindu:n family:ptr familyu:n :}
   DECL-DIAG:PROSE
   src srcu EVALUATE-CATCH 76 T=
   DECL-DIAG:TEXT$ kind kindu family familyu NS-DIAG$ DECL-DIAG:SAME? TTRUE
   DECL-DIAG:OFF ;

: NS-ASSERT-ROLLED ( -- )
   ASSERT-UNCHANGED
   ASSERT-OWNER-DEPTHS
   ASSERT-NATIVE-HIGHWATERS
   WID-NEXT WID-N0 @ T= ;

: NS-RECORD ( -- )
   RECORD-BASELINE RECORD-OWNER-DEPTHS RECORD-NATIVE-HIGHWATERS
   WID-NEXT WID-N0 ! ;

: NS-CONTINUE ( ptr u8 n ptr u8 n -- )
   {: src:ptr srcu:n ns:ptr nsu:n :}
   src srcu EVALUATE-CATCH 0 T=
   ns nsu XREF:NAMESPACE? TTRUE
   ASSERT-PRODUCTION-IDLE ;

: NS-TIMING-CASE ( ptr u8 n ptr u8 n ptr u8 n ptr u8 n n ptr u8 n ptr u8 n -- )
   {: srca:ptr srcu:n kind:ptr kindu:n family:ptr familyu:n nsa:ptr nsu:n vars:n
      next:ptr nextu:n nextns:ptr nextnsu:n :}
   NS-RECORD
   nsa NS-EXPECT-A !  nsu NS-EXPECT-U !  vars NS-EXPECT-VARS !
   0 NS-HOOK-N !
   0 NS-HOOK-NAME-OK !
   0 NS-HOOK-META-CLEAR !
   0 NS-HOOK-PUBLICATION-CLEAR !
   [: OBSERVE-NS ;] is TDECL-NS-EXISTS-XT
   srca srcu kind kindu family familyu NS-EVAL
   RESTORE-GENERATED-EVALUATOR
   NS-HOOK-N @ 1 T=
   NS-HOOK-NAME-OK @ TTRUE
   NS-HOOK-META-CLEAR @ TTRUE
   NS-HOOK-PUBLICATION-CLEAR @ TTRUE
   NS-ASSERT-ROLLED
   ASSERT-PRODUCTION-IDLE
   next nextu nextns nextnsu NS-CONTINUE ;

: NS-PRODUCTION-CASE ( ptr u8 n ptr u8 n ptr u8 n ptr u8 n ptr u8 n -- )
   {: src:ptr srcu:n kind:ptr kindu:n family:ptr familyu:n
      next:ptr nextu:n ns:ptr nsu:n :}
   NS-RECORD
   src srcu kind kindu family familyu NS-EVAL
   NS-ASSERT-ROLLED
   ASSERT-PRODUCTION-IDLE
   next nextu ns nsu NS-CONTINUE ;

: TEST-NAMESPACE-COLLISIONS ( -- )
   SETUP-NAMESPACE-COLLISIONS

   \ The observing hook pins each owning seam before constructor metadata,
   \ native dictionary, WID, or protection publication.
   s" ENUM gdpreenum red blue ;ENUM" s" enum" s" gdpreenum"
      s" GDPREENUM" 2
      s" ENUM gdnsh-enum ok ;ENUM GDNSH-ENUM:OK drop" s" GDNSH-ENUM"
      NS-TIMING-CASE
   s" SUMTYPE gdpresum 0 VARIANT one ;VARIANT ;SUMTYPE"
      s" sumtype" s" gdpresum" s" GDPRESUM" 1
      s" SUMTYPE gdnsh-sum 0 VARIANT ok ;VARIANT ;SUMTYPE GDNSH-SUM:OK drop"
      s" GDNSH-SUM" NS-TIMING-CASE
   s" PRODUCT gdpreprod 0 FIELD x n ;PRODUCT"
      s" product" s" gdpreprod" s" GDPREPROD" 0
      s" PRODUCT gdnsh-prod 0 FIELD x n ;PRODUCT 7 GDNSH-PROD:MAKE GDNSH-PROD:UNMAKE 7 T="
      s" GDNSH-PROD" NS-TIMING-CASE
   s" STRUCTURE gdprestruct 0 FIELD x n ;STRUCTURE"
      s" structure" s" gdprestruct" s" GDPRESTRUCT" 0
      s" STRUCTURE gdnsh-struct 0 FIELD x n ;STRUCTURE 8 GDNSH-STRUCT:MAKE GDNSH-STRUCT:UNMAKE 8 T="
      s" GDNSH-STRUCT" NS-TIMING-CASE

   \ The installed xref hook then drives the same four production entry paths.
   s" ENUM gdpreenum red blue ;ENUM" s" enum" s" gdpreenum"
      s" ENUM gdns-enum ok ;ENUM GDNS-ENUM:OK drop" s" GDNS-ENUM"
      NS-PRODUCTION-CASE
   s" SUMTYPE gdpresum 0 VARIANT one ;VARIANT ;SUMTYPE"
      s" sumtype" s" gdpresum"
      s" SUMTYPE gdns-sum 0 VARIANT ok ;VARIANT ;SUMTYPE GDNS-SUM:OK drop"
      s" GDNS-SUM" NS-PRODUCTION-CASE
   s" PRODUCT gdpreprod 0 FIELD x n ;PRODUCT"
      s" product" s" gdpreprod"
      s" PRODUCT gdns-prod 0 FIELD x n ;PRODUCT 11 GDNS-PROD:MAKE GDNS-PROD:UNMAKE 11 T="
      s" GDNS-PROD" NS-PRODUCTION-CASE
   s" STRUCTURE gdprestruct 0 FIELD x n ;STRUCTURE"
      s" structure" s" gdprestruct"
      s" STRUCTURE gdns-struct 0 FIELD x n ;STRUCTURE 12 GDNS-STRUCT:MAKE GDNS-STRUCT:UNMAKE 12 T="
      s" GDNS-STRUCT" NS-PRODUCTION-CASE

   \ A finalized type row is the same exact-child conflict.
   s" package gdpretype public PRODUCT result 0 FIELD x n ;PRODUCT ;package"
      s" product" s" result"
      s" PRODUCT gdns-type 0 FIELD x n ;PRODUCT 13 GDNS-TYPE:MAKE GDNS-TYPE:UNMAKE 13 T="
      s" GDNS-TYPE" NS-PRODUCTION-CASE

   \ Namespace identity wins when the child also contains the would-be word.
   s" PRODUCT gdboth 0 FIELD x n ;PRODUCT"
      s" product" s" gdboth"
      s" PRODUCT gdns-both 0 FIELD x n ;PRODUCT 14 GDNS-BOTH:MAKE GDNS-BOTH:UNMAKE 14 T="
      s" GDNS-BOTH" NS-PRODUCTION-CASE ;

: NC-C, ( n -- )
   NC-U @ NC-SRC-CAP >= IF
      s" generated declaration capacity source too long" 76 die
   THEN
   NC-SRC NC-U @ + c!
   NC-U @ 1 + NC-U ! ;

: NC-APP ( ptr u8 n -- ) {: a:ptr u:n :}
   0 BEGIN dup u < WHILE
      dup a + c@ NC-C,
      1 +
   REPEAT drop ;

: NC-REP ( n n -- ) {: u:n c:n :}
   0 BEGIN dup u < WHILE c NC-C, 1 + REPEAT drop ;

: NC-PKG-C ( n -- n )
   dup NC-ENUM = IF drop [char] E EXIT THEN
   dup NC-SUM = IF drop [char] S EXIT THEN
   dup NC-PROD = IF drop [char] P EXIT THEN
   drop [char] T ;

: NC-PKG ( n n -- ) {: kind:n c:n :}
   NC-PKG-U 1 - c NC-REP
   kind NC-PKG-C NC-C, ;

: NC-FAMILY ( bool -- )
   IF NC-FAM-U 1 + [char] b ELSE NC-FAM-U [char] a THEN NC-REP ;

: NC-KIND$ ( n -- ptr u8 n )
   dup NC-ENUM = IF drop s" enum" EXIT THEN
   dup NC-SUM = IF drop s" sumtype" EXIT THEN
   dup NC-PROD = IF drop s" product" EXIT THEN
   drop s" structure" ;

: NC-LONG-FAMILY$ ( -- ptr u8 n )
   0 NC-U !
   0 0= NC-FAMILY
   NC-SRC NC-U @ ;

: NC-MARKED-FAMILY$ ( -- ptr u8 n )
   0 NC-U !
   NC-DIAG-B-U [char] b NC-REP
   s" ..." NC-APP
   NC-SRC NC-U @ ;

: NC-UNIFIED? ( n -- bool )
   dup NC-ENUM = swap NC-STRUCT = or ;

: NC-ASSERT-UNIFIED-DIAG ( n -- ) {: kind:n :}
   NC-MARKED-FAMILY$ nip NC-DIAG-U T=
   DECL-REJECT:KIND$ kind NC-KIND$ DECL-DIAG:SAME? TTRUE
   DECL-REJECT:FAMILY$ NC-MARKED-FAMILY$ DECL-DIAG:SAME? TTRUE
   DECL-REJECT:TOKEN$ NC-MARKED-FAMILY$ DECL-DIAG:SAME? TTRUE
   E-TFAM-NS-CAP DECL-REJECT:REASON$
      s" tfam: constructor namespace too long" DECL-DIAG:SAME? TTRUE
   DECL-DIAG:TEXT$
   kind NC-KIND$
   NC-MARKED-FAMILY$ 2dup
   s" tfam: constructor namespace too long"
   NS-PACKET$ DECL-DIAG:SAME? TTRUE ;

: NC-ASSERT-CAP-DIAG ( n -- ) {: kind:n :}
   kind NC-UNIFIED? IF
      kind NC-ASSERT-UNIFIED-DIAG
   ELSE
      DECL-DIAG:TEXT$
      kind NC-KIND$
      NC-LONG-FAMILY$ 2dup
      s" tfam: constructor namespace too long"
      NS-PACKET$ DECL-DIAG:SAME? TTRUE
   THEN ;

: NC-DECL$ ( n bool -- ptr u8 n ) {: kind:n long:bool :}
   0 NC-U !
   s" package " NC-APP
   kind [char] p NC-PKG
   s"  public " NC-APP
   kind NC-ENUM = IF
      s" ENUM " NC-APP long NC-FAMILY s"  x y ;ENUM ;package" NC-APP
   ELSE kind NC-SUM = IF
      s" SUMTYPE " NC-APP long NC-FAMILY
      s"  0 VARIANT x ;VARIANT VARIANT y n ;VARIANT ;SUMTYPE ;package" NC-APP
   ELSE kind NC-PROD = IF
      s" PRODUCT " NC-APP long NC-FAMILY
      s"  0 FIELD x n FIELD y n ;PRODUCT ;package" NC-APP
   ELSE
      s" STRUCTURE " NC-APP long NC-FAMILY
      s"  0 FIELD x n FIELD y n ;STRUCTURE ;package" NC-APP
   THEN THEN THEN
   NC-SRC NC-U @ ;

: NC-NS$ ( n -- ptr u8 n ) {: kind:n :}
   0 NC-U !
   kind [char] P NC-PKG
   58 NC-C,
   NC-FAM-U [char] A NC-REP
   NC-SRC NC-U @ ;

: NC-NS-APP ( n -- ) {: kind:n :}
   kind [char] P NC-PKG
   58 NC-C,
   NC-FAM-U [char] A NC-REP ;

: NC-WORD-APP ( n ptr u8 n -- ) {: kind:n a:ptr u:n :}
   kind NC-NS-APP
   58 NC-C,
   a u NC-APP ;

: NC-WORD$ ( n ptr u8 n -- ptr u8 n ) {: kind:n a:ptr u:n :}
   0 NC-U !
   kind a u NC-WORD-APP
   NC-SRC NC-U @ ;

: NC-WID-WORDS ( n -- n ) {: wid:n :}
   0
   ndict@ 0 ?do
      i XREF-REC XREF-WORDLIST wid = IF 1 + THEN
   loop ;

: NC-ASSERT-NS ( n -- ) {: kind:n :}
   kind NC-NS$ XREF-NAMESPACE-WL XREF-FIND-WL
   dup XREF-FOUND? TTRUE
   dup XREF-LEN 0 T=
   dup XREF-FLAGS DNAME-MIN-IN-MASK and 52 rshift NAMESPACE:KIND-TYPE T=
   XREF-START dup prot-wid? TTRUE
   NC-WID-WORDS 2 T= ;

: NC-ASSERT-WORD ( n ptr u8 n -- ) {: kind:n a:ptr u:n :}
   kind a u NC-WORD$ QUALIFIED-ABSENT? 0= TTRUE ;

: NC-CHECK-VARIANT ( n ptr u8 n bool -- ) {: kind:n a:ptr u:n payload:bool :}
   0 NC-U !
   s" NC-CAP-VARIANT-" NC-APP
   kind NC-PKG-C NC-C,
   45 NC-C,
   a u NC-APP
   s"  ( -- " NC-APP
   kind NC-NS-APP
   s"  ) " NC-APP
   payload IF s" 1 " NC-APP THEN
   kind a u NC-WORD-APP
   NC-SRC NC-U @ CHECK-QUIET-CANDIDATE! -1 T= ;

: NC-CHECK-RECORD ( n -- ) {: kind:n :}
   0 NC-U !
   s" NC-CAP-RECORD-" NC-APP
   kind NC-PKG-C NC-C,
   s"  ( -- n n ) 1 2 " NC-APP
   kind s" MAKE" NC-WORD-APP
   32 NC-C,
   kind s" UNMAKE" NC-WORD-APP
   NC-SRC NC-U @ CHECK-QUIET-CANDIDATE! -1 T= ;

: NC-RUN-NAME ( n -- )
   s" NC-CAP-ROUNDTRIP-" NC-APP
   NC-PKG-C NC-C, ;

: NC-RUN-RECORD ( n -- ) {: kind:n :}
   0 NC-U !
   s" : " NC-APP kind NC-RUN-NAME
   s"  ( -- n n ) 1 2 " NC-APP
   kind s" MAKE" NC-WORD-APP
   32 NC-C,
   kind s" UNMAKE" NC-WORD-APP
   s"  ; " NC-APP
   kind NC-RUN-NAME
   s"  2 T= 1 T=" NC-APP
   NC-SRC NC-U @ EVALUATE-CATCH 0 T= ;

: NC-ASSERT-SUM-SURFACE ( n -- ) {: kind:n :}
   kind s" X" NC-ASSERT-WORD
   kind s" Y" NC-ASSERT-WORD
   kind s" X" 0 0= 0= NC-CHECK-VARIANT
   kind s" Y" kind NC-SUM = NC-CHECK-VARIANT ;

: NC-ASSERT-RECORD-SURFACE ( n -- ) {: kind:n :}
   kind s" MAKE" NC-ASSERT-WORD
   kind s" UNMAKE" NC-ASSERT-WORD
   kind NC-CHECK-RECORD
   kind NC-RUN-RECORD ;

: NC-QUERY ( ptr u8 n -- bool )
   2drop
   NC-QUERY-N @ 1 + NC-QUERY-N !
   0 0= 0= ;

: NC-EXACT ( n -- ) {: kind:n :}
   kind 0 0= 0= NC-DECL$ EVALUATE-CATCH 0 T=
   kind NC-ASSERT-NS
   kind NC-ENUM = kind NC-SUM = or IF
      kind NC-ASSERT-SUM-SURFACE
   ELSE
      kind NC-ASSERT-RECORD-SURFACE
   THEN ;

: NC-SHORT ( n -- ) {: kind:n :}
   kind NC-ENUM = IF
      s" ENUM gdcap-enum ok ;ENUM" EVALUATE-CATCH 0 T=
      s" GDCAP-ENUM" XREF:NAMESPACE? TTRUE
      EXIT
   THEN
   kind NC-SUM = IF
      s" SUMTYPE gdcap-sum 0 VARIANT ok ;VARIANT ;SUMTYPE" EVALUATE-CATCH 0 T=
      s" GDCAP-SUM" XREF:NAMESPACE? TTRUE
      EXIT
   THEN
   kind NC-PROD = IF
      s" PRODUCT gdcap-prod 0 FIELD x n ;PRODUCT" EVALUATE-CATCH 0 T=
      s" GDCAP-PROD" XREF:NAMESPACE? TTRUE
      EXIT
   THEN
   s" STRUCTURE gdcap-struct 0 FIELD x n ;STRUCTURE" EVALUATE-CATCH 0 T=
   s" GDCAP-STRUCT" XREF:NAMESPACE? TTRUE ;

: NC-OVER ( n -- ) {: kind:n :}
   RECORD-BASELINE RECORD-OWNER-DEPTHS RECORD-NATIVE-HIGHWATERS
   WID-NEXT WID-N0 !
   0 NC-QUERY-N !
   [: NC-QUERY ;] is TDECL-NS-EXISTS-XT
   DECL-DIAG:PROSE
   kind 0 0= NC-DECL$ EVALUATE-CATCH E-TFAM-NS-CAP T=
   kind NC-ASSERT-CAP-DIAG
   DECL-DIAG:OFF
   RESTORE-GENERATED-EVALUATOR
   NC-QUERY-N @ 0 T=
   NS-ASSERT-ROLLED
   ASSERT-PRODUCTION-IDLE
   kind NC-SHORT ;

: TEST-NAMESPACE-CAPACITY ( -- )
   TF-CTOR-NS-CAP NC-SPEC-CAP T=
   NC-ENUM NC-EXACT   NC-ENUM NC-OVER
   NC-SUM NC-EXACT    NC-SUM NC-OVER
   NC-PROD NC-EXACT   NC-PROD NC-OVER
   NC-STRUCT NC-EXACT NC-STRUCT NC-OVER ;

: RUN-CAPACITY-PREFLIGHT ( -- )
   s" GDCAP-MISSING:MAKE" CAPACITY-PREFLIGHT-N @ TDECL-CAPACITY-PREFLIGHT-XT ;

: CAPACITY-PREFLIGHT-CATCH ( n -- n )
   CAPACITY-PREFLIGHT-N !
   [: RUN-CAPACITY-PREFLIGHT ;] catch ;

: TEST-PLAN-CAPACITY-PREFLIGHT ( -- )
   \ Every public declaration reserves the constructor namespace's WID pair.
   s" GDNESTED:MAKE" 2 GENERATED-DECL-NAME-PREFLIGHT:DICTIONARY-RECORDS 3 T=
   s" GDCAP-MISSING:MAKE" 2 GENERATED-DECL-NAME-PREFLIGHT:DICTIONARY-RECORDS 3 T=
   DICT-CAP ndict@ - {: room:n :}
   RECORD-NATIVE-HIGHWATERS
   room CAPACITY-PREFLIGHT-CATCH 0 T=
   room 1 + CAPACITY-PREFLIGHT-CATCH E-GENERATED-DICTIONARY-CAP T=
   ASSERT-NATIVE-HIGHWATERS
   ASSERT-PRODUCTION-IDLE ;

: TEST-SUCCESS-PUBLICATION ( -- )
   RESET-CONTROLS RESET-TRACES RESET-DIAGNOSTIC
   prot-wid-room PROTECTION-ROOM-N0 !
   s" PRODUCT gdok 0 FIELD x n ;PRODUCT" EVALUATE-CATCH 0 T=
   prot-wid-room PROTECTION-ROOM-N0 @ 1 - T=
   s" GDOK-USE ( n -- gdok ) GDOK:MAKE"
      CHECK-QUIET-CANDIDATE! 0 <> TTRUE
   s" package gdok ;package" EVALUATE-CATCH 7111 T=
   ASSERT-PRODUCTION-IDLE ;

: TEST-DICTIONARY-DEPTH-PRIVATE ( -- )
   s" GENERATED-DECL-DICTIONARY:DEPTH" QUALIFIED-ABSENT? TTRUE ;

public

: RUN ( -- )
   CAP-TEST-RUN
   RESET-CONTROLS
   INIT-TEST-COORDINATOR
   TEST-REGISTRATION
   TEST-PHASE-ORDER
   TEST-ACTIVE-REGISTRATION
   TEST-PARTIAL-SNAPSHOT
   TEST-PREPARE-FAILURE
   TEST-COMMIT-FAILURE
   TEST-NESTING-GROWTH
   TEST-ROLLBACK-CLEANUP
   INIT-TEST-COORDINATOR
   REGISTER-TEST-PARTICIPANTS
   TEST-RELEASE-AFTER-PUBLICATION
   TEST-CALLBACK-DEPTH
   TEST-OUTER-CHECKER-SCOPE
   TEST-CHECKER-LEAK-PREPARE
   TEST-RECYCLED-SLOT-LEAK
   TEST-NESTED-DECLARATION-ROLLBACK
   TEST-PRODUCTION-FRAME-GROWTH
   TEST-PRODUCTION-NESTED-RELEASE
   TEST-DATA-ROLLBACK
   TEST-NAME-PREFLIGHT-CLEARS-AUTHORITY
   TEST-GENERATOR-ROLLBACK
   TEST-EVALUATOR-FAILURE-CLEARS-AUTHORITY
   TEST-NAMESPACE-COLLISIONS
   TEST-NAMESPACE-CAPACITY
   TEST-PLAN-CAPACITY-PREFLIGHT
   TEST-SUCCESS-PUBLICATION
   TEST-DICTIONARY-DEPTH-PRIVATE
   RESTORE-GENERATED-EVALUATOR
   T-REPORT ;

;package

GENERATED-DECLARATION-TXN-TEST:RUN
