\ generated-declaration-transaction-suite.f - atomic declaration publication.
\ Run: bin/hb --load test/generated-declaration-transaction-suite.f

require lib/test.f
require test/checker-assert.f

T-RESET

package GENERATED-DECLARATION-TXN-TEST

-7190 constant E-INJECT
-7191 constant E-CLEANUP
-7192 constant E-BODY
-7193 constant E-DIAGNOSTIC
70 constant E-GENERATED-REJECT
7175 constant E-GENERATED-DICTIONARY-CAP

101 constant PARTICIPANT-A
102 constant PARTICIPANT-B
103 constant PARTICIPANT-C
104 constant PARTICIPANT-D
105 constant PARTICIPANT-CORRUPT
109 constant PARTICIPANT-LATE

200 constant ORDER-A
700 constant ORDER-B
850 constant ORDER-C
400 constant ORDER-D
600 constant ORDER-LATE

4 constant TEST-CAP
DECLARATION-TRANSACTION:ROW-CELLS cells constant TEST-ROW-BYTES
DECLARATION-TRANSACTION:STATE-CELLS cells constant TEST-STATE-BYTES
TEST-CAP TEST-ROW-BYTES * constant TEST-TABLE-BYTES

DECLARATION-TRANSACTION:ROW-CELLS cells constant CAP-TEST-ROW-BYTES
DECLARATION-TRANSACTION:STATE-CELLS cells constant CAP-TEST-STATE-BYTES
$7FFFFFFFFFFFFFFF CAP-TEST-ROW-BYTES / constant CAP-TEST-MAX-ROWS
CAP-TEST-MAX-ROWS 2 / constant CAP-TEST-HALF-ROWS
CAP-TEST-MAX-ROWS CAP-TEST-ROW-BYTES * constant CAP-TEST-MAX-BYTES
$5A5A5A5A5A5A5A5A constant CAP-TEST-STATE-SENTINEL
111 constant CAP-TEST-ID
300 constant CAP-TEST-ORDER

create TEST-TABLE TEST-CAP DECLARATION-TRANSACTION:ROW-CELLS * cells allot
create TEST-STATE DECLARATION-TRANSACTION:STATE-CELLS cells allot
create TEST-TABLE-SAVE TEST-TABLE-BYTES allot
create TEST-STATE-SAVE TEST-STATE-BYTES allot

create CAP-TEST-TABLE CAP-TEST-ROW-BYTES allot
create CAP-TEST-TABLE-SAVE CAP-TEST-ROW-BYTES allot
create CAP-TEST-REJECT-TABLE CAP-TEST-ROW-BYTES allot
create CAP-TEST-STATE CAP-TEST-STATE-BYTES allot
create CAP-TEST-STATE-SAVE CAP-TEST-STATE-BYTES allot

PTR-VARIABLE SOURCE-A
variable SOURCE-U
variable FAMILY-N0
variable VARIANT-N0
variable FIELD-N0
variable SCHEMA-N0
variable SCHEMA-ROOT-N0
variable LAYOUT-N0
variable STRING-N0
variable EVENT-N0
variable PROTECTION-ROOM-N0
variable GENERATED-N
variable GENERATED-NAME-PREFLIGHT-N
variable GENERATED-PLAN-BROKEN
variable GENERATED-XREF-ABSENT
variable GENERATED-CHECKER-ABSENT
variable GENERATED-EVENT-UNPUBLISHED
variable GENERATED-PROTECTION-UNPUBLISHED
variable GENERATED-DICTIONARY-UNPUBLISHED
variable NATIVE-NDICT-N0
variable NATIVE-CP-N0
PTR-VARIABLE NATIVE-DP-N0

variable SNAPSHOT-TRACE
variable PREPARE-TRACE
variable COMMIT-TRACE
variable ROLLBACK-TRACE
variable FINALIZE-TRACE
variable TRACE-ON

variable FAIL-PHASE
variable FAIL-PARTICIPANT
variable ROLLBACK-FAIL-PARTICIPANT
variable SNAPSHOT-MUTATE-PARTICIPANT
variable BODY-MUTATE
variable BODY-REGISTER
variable BODY-ERROR

variable VALUE-A
variable VALUE-B
variable VALUE-C
variable SAVED-A
variable SAVED-B
variable SAVED-C
variable TRACK-VALUES

variable ALLOCATOR-CALLS
variable ALLOCATOR-FAIL-AT
variable ALLOCATED-BYTES
variable ALLOCATOR-OLD-BYTES
variable ALLOCATOR-NEW-BYTES

variable CAP-TEST-ALLOC-CALLS
variable CAP-TEST-REJECT-ALLOC-CALLS
variable CAP-TEST-N

variable DIAGNOSTIC-COUNT
variable DIAGNOSTIC-PRIMARY
variable DIAGNOSTIC-CLEANUP
variable DIAGNOSTIC-THROWS

variable NESTING-LEFT
variable NESTING-BODIES
defer NESTED-XT ( -- )

variable CHECKER-DEPTH-N0
variable FIELD-DEPTH-N0
variable EVENT-DEPTH-N0
variable DICTIONARY-DEPTH-N0
variable STAGED-N0
variable INNER-EVENT-N
variable INNER-FIELD-N
PTR-VARIABLE TABLE-N0
variable CAP-N0
variable ALLOCATED-N0
variable CAPACITY-PREFLIGHT-N

public

defer CAP-ROWS>BYTES ( n -- n )
defer CAP-NEXT-CAP ( n -- n )
defer CAP-COUNT! ( ptr a n -- )

private

;package

package DECLARATION-TRANSACTION

: CAP-TEST-COUNT! ( ptr a n -- )
   swap ST.N ! ;

: CAP-TEST-INSTALL ( -- )
   [: ROWS>BYTES ;] is GENERATED-DECLARATION-TXN-TEST:CAP-ROWS>BYTES
   [: NEXT-CAP ;] is GENERATED-DECLARATION-TXN-TEST:CAP-NEXT-CAP
   [: CAP-TEST-COUNT! ;] is GENERATED-DECLARATION-TXN-TEST:CAP-COUNT! ;

CAP-TEST-INSTALL

;package

package GENERATED-DECLARATION-TXN-TEST

: CAP-TEST-ALLOC ( ptr a n n -- ptr a )
   CAP-TEST-ALLOC-CALLS @ 1 + CAP-TEST-ALLOC-CALLS !
   2drop ;

: CAP-TEST-REJECT-ALLOC ( ptr a n n -- ptr a )
   CAP-TEST-REJECT-ALLOC-CALLS @ 1 + CAP-TEST-REJECT-ALLOC-CALLS !
   2drop ;

: CAP-TEST-DIAG ( n n -- ) 2drop ;
: CAP-TEST-REJECT-DIAG ( n n -- ) 2drop ;
: CAP-TEST-INERT ( n -- n ) ;

: CAP-TEST-FILL-CELLS ( n ptr a n -- )
   {: value:n a:ptr count:n :}
   count 0 ?do
      value a i cells + !
   loop ;

: CAP-TEST-SAVE-STATE ( -- )
   CAP-TEST-STATE BYTE-VIEW CAP-TEST-STATE-SAVE BYTE-VIEW
      CAP-TEST-STATE-BYTES BYTE-COPY ;

: CAP-TEST-SAVE-ALL ( -- )
   CAP-TEST-SAVE-STATE
   CAP-TEST-TABLE BYTE-VIEW CAP-TEST-TABLE-SAVE BYTE-VIEW
      CAP-TEST-ROW-BYTES BYTE-COPY ;

: CAP-TEST-STATE-SAME ( -- )
   CAP-TEST-STATE BYTE-VIEW CAP-TEST-STATE-BYTES
      CAP-TEST-STATE-SAVE BYTE-VIEW CAP-TEST-STATE-BYTES STR= TTRUE ;

: CAP-TEST-ALL-SAME ( -- )
   CAP-TEST-STATE-SAME
   CAP-TEST-TABLE BYTE-VIEW CAP-TEST-ROW-BYTES
      CAP-TEST-TABLE-SAVE BYTE-VIEW CAP-TEST-ROW-BYTES STR= TTRUE ;

: CAP-TEST-ROWS-RUN ( -- )
   CAP-TEST-N @ CAP-ROWS>BYTES drop ;

: CAP-TEST-NEXT-RUN ( -- )
   CAP-TEST-N @ CAP-NEXT-CAP drop ;

: CAP-TEST-ROWS-CATCH ( n -- n )
   CAP-TEST-N !
   [: CAP-TEST-ROWS-RUN ;] catch ;

: CAP-TEST-NEXT-CATCH ( n -- n )
   CAP-TEST-N !
   [: CAP-TEST-NEXT-RUN ;] catch ;

: CAP-TEST-HELPERS ( -- )
   -1 CAP-TEST-ROWS-CATCH
      DECLARATION-TRANSACTION:E-PARTICIPANT-CAPACITY T=
   CAP-TEST-MAX-ROWS CAP-ROWS>BYTES CAP-TEST-MAX-BYTES T=
   CAP-TEST-MAX-ROWS 1 + CAP-TEST-ROWS-CATCH
      DECLARATION-TRANSACTION:E-PARTICIPANT-CAPACITY T=
   CAP-TEST-HALF-ROWS CAP-NEXT-CAP CAP-TEST-HALF-ROWS 2 * T=
   CAP-TEST-HALF-ROWS 1 + CAP-NEXT-CAP CAP-TEST-MAX-ROWS T=
   CAP-TEST-MAX-ROWS CAP-TEST-NEXT-CATCH
      DECLARATION-TRANSACTION:E-PARTICIPANT-CAPACITY T= ;

: CAP-TEST-INIT-RUN ( -- )
   CAP-TEST-STATE CAP-TEST-TABLE CAP-TEST-N @
   [: CAP-TEST-ALLOC ;] [: CAP-TEST-DIAG ;]
   DECLARATION-TRANSACTION:INIT ;

: CAP-TEST-REJECT-INIT-RUN ( -- )
   CAP-TEST-STATE CAP-TEST-REJECT-TABLE CAP-TEST-N @
   [: CAP-TEST-REJECT-ALLOC ;] [: CAP-TEST-REJECT-DIAG ;]
   DECLARATION-TRANSACTION:INIT ;

: CAP-TEST-INIT-CATCH ( n -- n )
   CAP-TEST-N !
   [: CAP-TEST-INIT-RUN ;] catch ;

: CAP-TEST-REJECT-INIT-CATCH ( n -- n )
   CAP-TEST-N !
   [: CAP-TEST-REJECT-INIT-RUN ;] catch ;

: CAP-TEST-INIT ( -- )
   0 CAP-TEST-ALLOC-CALLS !
   CAP-TEST-MAX-ROWS CAP-TEST-INIT-CATCH 0 T= ;

: CAP-TEST-REGISTER ( -- )
   CAP-TEST-STATE CAP-TEST-ID CAP-TEST-ORDER
   [: CAP-TEST-INERT ;] [: CAP-TEST-INERT ;] [: CAP-TEST-INERT ;]
   [: CAP-TEST-INERT ;] [: CAP-TEST-INERT ;]
   DECLARATION-TRANSACTION:REGISTER ;

: CAP-TEST-REGISTER-CATCH ( -- n )
   [: CAP-TEST-REGISTER ;] catch ;

: CAP-TEST-COUNT ( n -- )
   CAP-TEST-STATE swap CAP-COUNT! ;

: CAP-TEST-SEED-DUPLICATE ( -- )
   CAP-TEST-REGISTER
   CAP-TEST-STATE DECLARATION-TRANSACTION:COUNT 1 T= ;

: CAP-TEST-INVALID-INIT ( -- )
   0 CAP-TEST-REJECT-ALLOC-CALLS !
   CAP-TEST-STATE-SENTINEL CAP-TEST-STATE
      DECLARATION-TRANSACTION:STATE-CELLS CAP-TEST-FILL-CELLS
   CAP-TEST-SAVE-STATE
   0 CAP-TEST-REJECT-INIT-CATCH
      DECLARATION-TRANSACTION:E-PARTICIPANT-CAPACITY T=
   CAP-TEST-STATE-SAME
   -1 CAP-TEST-REJECT-INIT-CATCH
      DECLARATION-TRANSACTION:E-PARTICIPANT-CAPACITY T=
   CAP-TEST-STATE-SAME
   CAP-TEST-MAX-ROWS 1 + CAP-TEST-REJECT-INIT-CATCH
      DECLARATION-TRANSACTION:E-PARTICIPANT-CAPACITY T=
   CAP-TEST-STATE-SAME
   CAP-TEST-REJECT-ALLOC-CALLS @ 0 T= ;

: CAP-TEST-ACTIVE-BODY ( -- )
   CAP-TEST-MAX-ROWS CAP-TEST-COUNT
   CAP-TEST-SAVE-ALL
   CAP-TEST-REGISTER-CATCH
      DECLARATION-TRANSACTION:E-REGISTRATION-ACTIVE T=
   CAP-TEST-ALLOC-CALLS @ 0 T=
   CAP-TEST-ALL-SAME
   1 CAP-TEST-COUNT ;

: CAP-TEST-ACTIVE-PRECEDENCE ( -- )
   CAP-TEST-INIT
   CAP-TEST-SEED-DUPLICATE
   CAP-TEST-STATE DECLARATION-TRANSACTION:SEAL
   CAP-TEST-STATE [: CAP-TEST-ACTIVE-BODY ;]
      DECLARATION-TRANSACTION:RUN
   CAP-TEST-STATE DECLARATION-TRANSACTION:COUNT 1 T=
   CAP-TEST-STATE DECLARATION-TRANSACTION:DEPTH 0 T= ;

: CAP-TEST-SEALED-PRECEDENCE ( -- )
   CAP-TEST-INIT
   CAP-TEST-SEED-DUPLICATE
   CAP-TEST-MAX-ROWS CAP-TEST-COUNT
   CAP-TEST-STATE DECLARATION-TRANSACTION:SEAL
   CAP-TEST-SAVE-ALL
   CAP-TEST-REGISTER-CATCH
      DECLARATION-TRANSACTION:E-REGISTRATION-SEALED T=
   CAP-TEST-ALLOC-CALLS @ 0 T=
   CAP-TEST-ALL-SAME ;

: CAP-TEST-CAPACITY-PRECEDENCE ( -- )
   CAP-TEST-INIT
   CAP-TEST-SEED-DUPLICATE
   CAP-TEST-MAX-ROWS CAP-TEST-COUNT
   CAP-TEST-SAVE-ALL
   CAP-TEST-REGISTER-CATCH
      DECLARATION-TRANSACTION:E-PARTICIPANT-CAPACITY T=
   CAP-TEST-ALLOC-CALLS @ 0 T=
   CAP-TEST-ALL-SAME ;

: CAP-TEST-RUN ( -- )
   CAP-TEST-HELPERS
   CAP-TEST-INVALID-INIT
   CAP-TEST-ACTIVE-PRECEDENCE
   CAP-TEST-SEALED-PRECEDENCE
   CAP-TEST-CAPACITY-PRECEDENCE ;

: BREAK-GENERATED-EFFECT ( ptr u8 n -- ) {: a:ptr u:n :}
   0 GENERATED-PLAN-BROKEN !
   a u + 1 + dup c@ 40 <> IF
      drop s" generated declaration test: signature opener moved" 76 die
   THEN
   63 swap c!
   -1 GENERATED-PLAN-BROKEN ! ;

: EVALUATE-GENERATED ( ptr u8 n -- )
   GENERATED-N @ 1 + GENERATED-N !
   INCLUDE-EVALUATE ;

: RECORD-PREFLIGHT-NONPUBLICATION ( -- )
   s" GDTX:RED" XREF-FIND XREF-FOUND? 0= GENERATED-XREF-ABSENT !
   s" GDTX:RED" CHECKER-DEFINED? 0= GENERATED-CHECKER-ABSENT !
   DECL-EVENT:COUNT EVENT-N0 @ = GENERATED-EVENT-UNPUBLISHED !
   prot-wid-room PROTECTION-ROOM-N0 @ = GENERATED-PROTECTION-UNPUBLISHED !
   ndict@ NATIVE-NDICT-N0 @ =
   cp@ NATIVE-CP-N0 @ = and
   here NATIVE-DP-N0 @ = and GENERATED-DICTIONARY-UNPUBLISHED ! ;

: PREFLIGHT-GENERATED-NAME ( ptr u8 n -- ) {: a:ptr u:n :}
   GENERATED-NAME-PREFLIGHT-N @ 1 + GENERATED-NAME-PREFLIGHT-N !
   a u GENERATED-DECL-NAME-PREFLIGHT:CHECK
   GENERATED-NAME-PREFLIGHT-N @ 2 = IF
      RECORD-PREFLIGHT-NONPUBLICATION
      a u BREAK-GENERATED-EFFECT
   THEN ;

: INSTALL-SECOND-WORD-FAILURE ( -- )
   0 GENERATED-N !
   0 GENERATED-NAME-PREFLIGHT-N !
   0 GENERATED-PLAN-BROKEN !
   0 GENERATED-XREF-ABSENT !
   0 GENERATED-CHECKER-ABSENT !
   0 GENERATED-EVENT-UNPUBLISHED !
   0 GENERATED-PROTECTION-UNPUBLISHED !
   0 GENERATED-DICTIONARY-UNPUBLISHED !
   [: EVALUATE-GENERATED ;] is TDECL-EVAL-XT
   [: PREFLIGHT-GENERATED-NAME ;] is TDECL-NAME-PREFLIGHT-XT ;

: REJECT-GENERATED-NAME ( ptr u8 n -- )
   GENERATED-NAME-PREFLIGHT-N @ 1 + GENERATED-NAME-PREFLIGHT-N !
   GENERATED-DECL-NAME-PREFLIGHT:CHECK
   E-INJECT throw ;

: INSTALL-NAME-PREFLIGHT-FAILURE ( -- )
   0 GENERATED-N !
   0 GENERATED-NAME-PREFLIGHT-N !
   [: EVALUATE-GENERATED ;] is TDECL-EVAL-XT
   [: REJECT-GENERATED-NAME ;] is TDECL-NAME-PREFLIGHT-XT ;

: FIRST-GENERATED-WORD-U ( ptr u8 n -- n ) {: a:ptr u:n :}
   0
   BEGIN dup u < WHILE
      a over + c@ 10 = IF 1 + EXIT THEN
      1 +
   REPEAT
   drop u ;

: EVALUATE-FIRST-GENERATED-WORD-THEN-FAIL ( ptr u8 n -- ) {: a:ptr u:n :}
   GENERATED-N @ 1 + GENERATED-N !
   a u FIRST-GENERATED-WORD-U {: first-u:n :}
   a first-u INCLUDE-EVALUATE
   E-INJECT throw ;

: INSTALL-EVALUATOR-FAILURE ( -- )
   0 GENERATED-N !
   0 GENERATED-NAME-PREFLIGHT-N !
   [: EVALUATE-FIRST-GENERATED-WORD-THEN-FAIL ;] is TDECL-EVAL-XT
   [: GENERATED-DECL-NAME-PREFLIGHT:CHECK ;] is TDECL-NAME-PREFLIGHT-XT ;

: RESTORE-GENERATED-EVALUATOR ( -- )
   [: INCLUDE-EVALUATE ;] is TDECL-EVAL-XT
   [: GENERATED-DECL-NAME-PREFLIGHT:CHECK ;] is TDECL-NAME-PREFLIGHT-XT ;

: EVALUATE-SOURCE ( -- )
   SOURCE-A @ SOURCE-U @ INCLUDE-EVALUATE ;

: EVALUATE-CATCH ( ptr u8 n -- n )
   SOURCE-U ! SOURCE-A !
   [: EVALUATE-SOURCE ;] catch ;

: WORD-ABSENT? ( ptr u8 n -- bool )
   0 search-wl 0= ;

: QUALIFIED-ABSENT? ( ptr u8 n -- bool )
   XREF-FIND XREF-FOUND? 0= ;

: ASSERT-NO-STALE-CONSTRUCTOR ( ptr u8 n -- )
   CHECK-QUIET-CANDIDATE! 0 T= ;

: RECORD-BASELINE ( -- )
   TFAM-N@ FAMILY-N0 !
   SUMV-N@ VARIANT-N0 !
   TYPE-FIELD:COUNT FIELD-N0 !
   SCHEMA-N@ SCHEMA-N0 !
   SCHEMA-ROOT-N@ SCHEMA-ROOT-N0 !
   LAY-N@ LAYOUT-N0 !
   TF-STR-U@ STRING-N0 !
   DECL-EVENT:COUNT EVENT-N0 !
   prot-wid-room PROTECTION-ROOM-N0 ! ;

: RECORD-OWNER-DEPTHS ( -- )
   CHECKER-SCOPE-DEPTH CHECKER-DEPTH-N0 !
   TYPE-FIELD:TX-DEPTH FIELD-DEPTH-N0 !
   DECL-EVENT:DEPTH EVENT-DEPTH-N0 !
   GENERATED-DECL-DICTIONARY:DEPTH DICTIONARY-DEPTH-N0 !
   GENERATED-DECL-PROTECTION:STAGED-COUNT STAGED-N0 ! ;

: RECORD-NATIVE-HIGHWATERS ( -- )
   ndict@ NATIVE-NDICT-N0 !
   cp@ NATIVE-CP-N0 !
   here NATIVE-DP-N0 ! ;

: ASSERT-NATIVE-HIGHWATERS ( -- )
   ndict@ NATIVE-NDICT-N0 @ T=
   cp@ NATIVE-CP-N0 @ T=
   here NATIVE-DP-N0 @ = TTRUE ;

: ASSERT-OWNER-DEPTHS ( -- )
   CHECKER-SCOPE-DEPTH CHECKER-DEPTH-N0 @ T=
   TYPE-FIELD:TX-DEPTH FIELD-DEPTH-N0 @ T=
   DECL-EVENT:DEPTH EVENT-DEPTH-N0 @ T=
   GENERATED-DECL-DICTIONARY:DEPTH DICTIONARY-DEPTH-N0 @ T=
   GENERATED-DECL-PROTECTION:STAGED-COUNT STAGED-N0 @ T=
   GENERATED-DECL:DEPTH 0 T=
   GENERATED-DECL:POISONED? 0= TTRUE ;

: ASSERT-UNCHANGED ( -- )
   TFAM-N@ FAMILY-N0 @ T=
   SUMV-N@ VARIANT-N0 @ T=
   TYPE-FIELD:COUNT FIELD-N0 @ T=
   SCHEMA-N@ SCHEMA-N0 @ T=
   SCHEMA-ROOT-N@ SCHEMA-ROOT-N0 @ T=
   LAY-N@ LAYOUT-N0 @ T=
   TF-STR-U@ STRING-N0 @ T=
   DECL-EVENT:COUNT EVENT-N0 @ T=
   prot-wid-room PROTECTION-ROOM-N0 @ T= ;

: APPEND-DIGIT ( n ptr a -- ) {: digit:n trace:ptr :}
   TRACE-ON @ 0= IF EXIT THEN
   trace @ 10 * digit + trace ! ;

: RESET-TRACES ( -- )
   0 SNAPSHOT-TRACE !
   0 PREPARE-TRACE !
   0 COMMIT-TRACE !
   0 ROLLBACK-TRACE !
   0 FINALIZE-TRACE ! ;

: RESET-CONTROLS ( -- )
   0 FAIL-PHASE !
   0 FAIL-PARTICIPANT !
   0 ROLLBACK-FAIL-PARTICIPANT !
   0 SNAPSHOT-MUTATE-PARTICIPANT !
   0 BODY-MUTATE !
   0 BODY-REGISTER !
   0 BODY-ERROR !
   0 TRACK-VALUES !
   0 TRACE-ON ! ;

: MAYBE-MUTATE-SNAPSHOT ( ptr a n -- ) {: value:ptr participant:n :}
   SNAPSHOT-MUTATE-PARTICIPANT @ participant = IF 1 value +! THEN ;

: MAYBE-FAIL ( n n -- ) {: phase:n participant:n :}
   FAIL-PHASE @ phase = FAIL-PARTICIPANT @ participant = and
      IF E-INJECT throw THEN ;

: MAYBE-FAIL-ROLLBACK ( n -- ) {: participant:n :}
   ROLLBACK-FAIL-PARTICIPANT @ participant = IF E-CLEANUP throw THEN ;

: SNAPSHOT-A ( n -- n ) {: depth:n :}
   TRACK-VALUES @ IF VALUE-A @ SAVED-A ! THEN
   1 SNAPSHOT-TRACE APPEND-DIGIT
   VALUE-A PARTICIPANT-A MAYBE-MUTATE-SNAPSHOT
   GENERATED-DECL:PHASE-SNAPSHOT PARTICIPANT-A MAYBE-FAIL
   depth ;

: PREPARE-A ( n -- n ) {: depth:n :}
   1 PREPARE-TRACE APPEND-DIGIT
   GENERATED-DECL:PHASE-PREPARE PARTICIPANT-A MAYBE-FAIL
   depth ;

: COMMIT-A ( n -- n ) {: depth:n :}
   1 COMMIT-TRACE APPEND-DIGIT
   GENERATED-DECL:PHASE-COMMIT PARTICIPANT-A MAYBE-FAIL
   depth ;

: ROLLBACK-A ( n -- n ) {: depth:n :}
   TRACK-VALUES @ IF SAVED-A @ VALUE-A ! THEN
   1 ROLLBACK-TRACE APPEND-DIGIT
   PARTICIPANT-A MAYBE-FAIL-ROLLBACK
   depth ;

: FINALIZE-A ( n -- n ) {: depth:n :}
   1 FINALIZE-TRACE APPEND-DIGIT
   GENERATED-DECL:PHASE-FINALIZE PARTICIPANT-A MAYBE-FAIL
   depth ;

: SNAPSHOT-B ( n -- n ) {: depth:n :}
   TRACK-VALUES @ IF VALUE-B @ SAVED-B ! THEN
   2 SNAPSHOT-TRACE APPEND-DIGIT
   VALUE-B PARTICIPANT-B MAYBE-MUTATE-SNAPSHOT
   GENERATED-DECL:PHASE-SNAPSHOT PARTICIPANT-B MAYBE-FAIL
   depth ;

: PREPARE-B ( n -- n ) {: depth:n :}
   2 PREPARE-TRACE APPEND-DIGIT
   GENERATED-DECL:PHASE-PREPARE PARTICIPANT-B MAYBE-FAIL
   depth ;

: COMMIT-B ( n -- n ) {: depth:n :}
   2 COMMIT-TRACE APPEND-DIGIT
   GENERATED-DECL:PHASE-COMMIT PARTICIPANT-B MAYBE-FAIL
   depth ;

: ROLLBACK-B ( n -- n ) {: depth:n :}
   TRACK-VALUES @ IF SAVED-B @ VALUE-B ! THEN
   2 ROLLBACK-TRACE APPEND-DIGIT
   PARTICIPANT-B MAYBE-FAIL-ROLLBACK
   depth ;

: FINALIZE-B ( n -- n ) {: depth:n :}
   2 FINALIZE-TRACE APPEND-DIGIT
   GENERATED-DECL:PHASE-FINALIZE PARTICIPANT-B MAYBE-FAIL
   depth ;

: SNAPSHOT-C ( n -- n ) {: depth:n :}
   TRACK-VALUES @ IF VALUE-C @ SAVED-C ! THEN
   3 SNAPSHOT-TRACE APPEND-DIGIT
   VALUE-C PARTICIPANT-C MAYBE-MUTATE-SNAPSHOT
   GENERATED-DECL:PHASE-SNAPSHOT PARTICIPANT-C MAYBE-FAIL
   depth ;

: PREPARE-C ( n -- n ) {: depth:n :}
   3 PREPARE-TRACE APPEND-DIGIT
   GENERATED-DECL:PHASE-PREPARE PARTICIPANT-C MAYBE-FAIL
   depth ;

: COMMIT-C ( n -- n ) {: depth:n :}
   3 COMMIT-TRACE APPEND-DIGIT
   GENERATED-DECL:PHASE-COMMIT PARTICIPANT-C MAYBE-FAIL
   depth ;

: ROLLBACK-C ( n -- n ) {: depth:n :}
   TRACK-VALUES @ IF SAVED-C @ VALUE-C ! THEN
   3 ROLLBACK-TRACE APPEND-DIGIT
   PARTICIPANT-C MAYBE-FAIL-ROLLBACK
   depth ;

: FINALIZE-C ( n -- n ) {: depth:n :}
   3 FINALIZE-TRACE APPEND-DIGIT
   GENERATED-DECL:PHASE-FINALIZE PARTICIPANT-C MAYBE-FAIL
   depth ;

: REGISTER-A ( -- )
   TEST-STATE PARTICIPANT-A ORDER-A
   [: SNAPSHOT-A ;] [: PREPARE-A ;] [: COMMIT-A ;]
   [: ROLLBACK-A ;] [: FINALIZE-A ;]
   DECLARATION-TRANSACTION:REGISTER ;

: REGISTER-B ( -- )
   TEST-STATE PARTICIPANT-B ORDER-B
   [: SNAPSHOT-B ;] [: PREPARE-B ;] [: COMMIT-B ;]
   [: ROLLBACK-B ;] [: FINALIZE-B ;]
   DECLARATION-TRANSACTION:REGISTER ;

: REGISTER-C ( -- )
   TEST-STATE PARTICIPANT-C ORDER-C
   [: SNAPSHOT-C ;] [: PREPARE-C ;] [: COMMIT-C ;]
   [: ROLLBACK-C ;] [: FINALIZE-C ;]
   DECLARATION-TRANSACTION:REGISTER ;

: INERT ( n -- n ) ;

: CORRUPT-SNAPSHOT ( n -- n ) 1 + ;

: SNAPSHOT-D ( n -- n ) {: depth:n :}
   4 SNAPSHOT-TRACE APPEND-DIGIT
   depth ;

: SNAPSHOT-LATE ( n -- n ) {: depth:n :}
   5 SNAPSHOT-TRACE APPEND-DIGIT
   depth ;

: REGISTER-D ( -- )
   TEST-STATE PARTICIPANT-D ORDER-D
   [: SNAPSHOT-D ;] [: INERT ;] [: INERT ;] [: INERT ;] [: INERT ;]
   DECLARATION-TRANSACTION:REGISTER ;

: REGISTER-LATE ( -- )
   TEST-STATE PARTICIPANT-LATE ORDER-LATE
   [: SNAPSHOT-LATE ;] [: INERT ;] [: INERT ;] [: INERT ;] [: INERT ;]
   DECLARATION-TRANSACTION:REGISTER ;

: REGISTER-CORRUPT ( -- )
   TEST-STATE PARTICIPANT-CORRUPT ORDER-A
   [: CORRUPT-SNAPSHOT ;]
   [: INERT ;] [: INERT ;] [: INERT ;] [: INERT ;]
   DECLARATION-TRANSACTION:REGISTER ;

: SAVE-TEST-BYTES ( -- )
   TEST-STATE BYTE-VIEW TEST-STATE-SAVE BYTE-VIEW TEST-STATE-BYTES BYTE-COPY
   TEST-TABLE BYTE-VIEW TEST-TABLE-SAVE BYTE-VIEW TEST-TABLE-BYTES BYTE-COPY ;

: ASSERT-TEST-BYTES ( -- )
   TEST-STATE BYTE-VIEW TEST-STATE-BYTES
      TEST-STATE-SAVE BYTE-VIEW TEST-STATE-BYTES STR= TTRUE
   TEST-TABLE BYTE-VIEW TEST-TABLE-BYTES
      TEST-TABLE-SAVE BYTE-VIEW TEST-TABLE-BYTES STR= TTRUE ;

: REGISTER-A-CATCH ( -- n )
   [: REGISTER-A ;] catch ;

: REGISTER-B-CATCH ( -- n )
   [: REGISTER-B ;] catch ;

: REGISTER-LATE-CATCH ( -- n )
   [: REGISTER-LATE ;] catch ;

: INJECTING-ALLOCATOR ( ptr a n n -- ptr a )
   {: base:ptr oldbytes:n newbytes:n :}
   ALLOCATOR-CALLS @ 1 + dup ALLOCATOR-CALLS !
   oldbytes ALLOCATOR-OLD-BYTES !
   newbytes ALLOCATOR-NEW-BYTES !
   ALLOCATOR-FAIL-AT @ = IF E-INJECT throw THEN
   base oldbytes newbytes DECLARATION-TRANSACTION:DEFAULT-ALLOCATOR {: grown:ptr :}
   newbytes ALLOCATED-BYTES +!
   grown ;

: INSTALL-ALLOCATOR-FAILURE ( n -- )
   ALLOCATOR-FAIL-AT !
   0 ALLOCATOR-CALLS ! ;

: RECORD-DIAGNOSTIC ( n n -- ) {: primary:n cleanup:n :}
   primary DIAGNOSTIC-PRIMARY !
   cleanup DIAGNOSTIC-CLEANUP !
   DIAGNOSTIC-COUNT @ 1 + DIAGNOSTIC-COUNT !
   DIAGNOSTIC-THROWS @ IF E-DIAGNOSTIC throw THEN ;

: RESET-DIAGNOSTIC ( -- )
   0 DIAGNOSTIC-COUNT !
   0 DIAGNOSTIC-PRIMARY !
   0 DIAGNOSTIC-CLEANUP !
   0 DIAGNOSTIC-THROWS ! ;

: INIT-TEST-COORDINATOR ( -- )
   0 ALLOCATOR-CALLS !
   0 ALLOCATOR-FAIL-AT !
   0 ALLOCATED-BYTES !
   0 ALLOCATOR-OLD-BYTES !
   0 ALLOCATOR-NEW-BYTES !
   RESET-DIAGNOSTIC
   TEST-STATE TEST-TABLE TEST-CAP
   [: INJECTING-ALLOCATOR ;]
   [: RECORD-DIAGNOSTIC ;]
   DECLARATION-TRANSACTION:INIT ;

: REGISTER-TEST-PARTICIPANTS ( -- )
   REGISTER-A REGISTER-B REGISTER-C REGISTER-D REGISTER-LATE
   TEST-STATE DECLARATION-TRANSACTION:SEAL ;

: TRANSACTION-BODY ( -- )
   BODY-MUTATE @ IF
      10 VALUE-A +!
      20 VALUE-B +!
      30 VALUE-C +!
   THEN
   BODY-REGISTER @ IF REGISTER-D THEN
   BODY-ERROR @ dup 0 <> IF throw THEN drop ;

: RUN-BODY ( -- )
   TEST-STATE [: TRANSACTION-BODY ;] DECLARATION-TRANSACTION:RUN ;

: RUN-BODY-CATCH ( -- n )
   [: RUN-BODY ;] catch ;

: NESTED-BODY ( -- )
   NESTING-BODIES @ 1 + NESTING-BODIES !
   NESTING-LEFT @ 0 > IF
      NESTING-LEFT @ 1 - NESTING-LEFT !
      TEST-STATE [: NESTED-XT ;] DECLARATION-TRANSACTION:RUN
   THEN ;

: INSTALL-NESTED ( -- )
   [: NESTED-BODY ;] is NESTED-XT ;
INSTALL-NESTED

: RUN-NESTED ( n -- )
   NESTING-LEFT !
   0 NESTING-BODIES !
   TEST-STATE [: NESTED-BODY ;] DECLARATION-TRANSACTION:RUN ;

: SET-VALUES ( n n n -- )
   VALUE-C ! VALUE-B ! VALUE-A ! ;

: ASSERT-VALUES ( n n n -- )
   {: a:n b:n c:n :}
   VALUE-A @ a T=
   VALUE-B @ b T=
   VALUE-C @ c T= ;

: ASSERT-IDLE ( -- )
   TEST-STATE DECLARATION-TRANSACTION:DEPTH 0 T= ;

: ASSERT-PRODUCTION-IDLE ( -- )
   GENERATED-DECL:DEPTH 0 T= ;

: TEST-REGISTRATION ( -- )
   TEST-STATE DECLARATION-TRANSACTION:COUNT 0 T=
   REGISTER-A
   TEST-STATE DECLARATION-TRANSACTION:COUNT 1 T=
   REGISTER-A-CATCH DECLARATION-TRANSACTION:E-PARTICIPANT-DUP T=
   REGISTER-B REGISTER-C REGISTER-D
   TEST-STATE DECLARATION-TRANSACTION:COUNT 4 T=

   TEST-STATE DECLARATION-TRANSACTION:TABLE TABLE-N0 !
   TEST-STATE DECLARATION-TRANSACTION:CAPACITY CAP-N0 !
   ALLOCATED-BYTES @ ALLOCATED-N0 !
   SAVE-TEST-BYTES
   1 INSTALL-ALLOCATOR-FAILURE
   REGISTER-LATE-CATCH E-INJECT T=
   ALLOCATOR-CALLS @ 1 T=
   TEST-STATE DECLARATION-TRANSACTION:COUNT 4 T=
   TEST-STATE DECLARATION-TRANSACTION:TABLE TABLE-N0 @ = TTRUE
   TEST-STATE DECLARATION-TRANSACTION:CAPACITY CAP-N0 @ T=
   ALLOCATED-BYTES @ ALLOCATED-N0 @ T=
   ASSERT-TEST-BYTES

   0 ALLOCATOR-FAIL-AT !
   REGISTER-LATE
   TEST-STATE DECLARATION-TRANSACTION:COUNT 5 T=
   TEST-STATE DECLARATION-TRANSACTION:CAPACITY TEST-CAP 2 * T=
   ALLOCATOR-OLD-BYTES @ TEST-TABLE-BYTES T=
   ALLOCATOR-NEW-BYTES @ TEST-TABLE-BYTES 2 * T=
   ALLOCATED-BYTES @ ALLOCATED-N0 @ > TTRUE
   TEST-STATE DECLARATION-TRANSACTION:SEAL
   REGISTER-LATE-CATCH DECLARATION-TRANSACTION:E-REGISTRATION-SEALED T=

   GENERATED-DECL:COUNT 4 T=
   GENERATED-DECL:SEALED? TTRUE
   s" GENERATED-DECL:REGISTER" WORD-ABSENT? TTRUE
   s" GENERATED-DECL:ALLOCATOR!" WORD-ABSENT? TTRUE
   s" GENERATED-DECL:DIAGNOSTIC!" WORD-ABSENT? TTRUE
   s" GENERATED-DECL:RESET" WORD-ABSENT? TTRUE
   s" GENERATED-DECL:SEAL" WORD-ABSENT? TTRUE
   s" GENERATED-DECL-OWNER:REGISTER" QUALIFIED-ABSENT? TTRUE
   s" GENERATED-DECL-OWNER:REGISTER-LAST" QUALIFIED-ABSENT? TTRUE
   s" GENERATED-DECL-OWNER:RUN" QUALIFIED-ABSENT? TTRUE
   s" GENERATED-DECL-OWNER:DEPTH" QUALIFIED-ABSENT? TTRUE
   s" TYPE-FIELD-OWNER:TX-SCHEMA-FOR" QUALIFIED-ABSENT? TTRUE ;

: TEST-PHASE-ORDER ( -- )
   RESET-CONTROLS RESET-TRACES
   -1 TRACE-ON !
   RUN-BODY
   SNAPSHOT-TRACE @ 14523 T=
   PREPARE-TRACE @ 123 T=
   COMMIT-TRACE @ 123 T=
   FINALIZE-TRACE @ 321 T=
   ROLLBACK-TRACE @ 0 T=
   ASSERT-IDLE ;

: TEST-ACTIVE-REGISTRATION ( -- )
   RESET-CONTROLS
   -1 BODY-REGISTER !
   RUN-BODY-CATCH DECLARATION-TRANSACTION:E-REGISTRATION-ACTIVE T=
   TEST-STATE DECLARATION-TRANSACTION:COUNT 5 T=
   TEST-STATE DECLARATION-TRANSACTION:LAST-FAILURE-PHASE GENERATED-DECL:PHASE-BODY T=
   TEST-STATE DECLARATION-TRANSACTION:LAST-FAILURE-PARTICIPANT -1 T=
   ASSERT-IDLE ;

: TEST-PARTIAL-SNAPSHOT ( -- )
   RESET-CONTROLS RESET-TRACES RESET-DIAGNOSTIC
   10 20 30 SET-VALUES
   -1 TRACK-VALUES !
   -1 TRACE-ON !
   PARTICIPANT-B SNAPSHOT-MUTATE-PARTICIPANT !
   GENERATED-DECL:PHASE-SNAPSHOT FAIL-PHASE !
   PARTICIPANT-B FAIL-PARTICIPANT !
   RUN-BODY-CATCH E-INJECT T=
   SNAPSHOT-TRACE @ 1452 T=
   ROLLBACK-TRACE @ 21 T=
   10 20 30 ASSERT-VALUES
   TEST-STATE DECLARATION-TRANSACTION:LAST-FAILURE-PHASE GENERATED-DECL:PHASE-SNAPSHOT T=
   TEST-STATE DECLARATION-TRANSACTION:LAST-FAILURE-PARTICIPANT PARTICIPANT-B T=
   DIAGNOSTIC-PRIMARY @ E-INJECT T=
   DIAGNOSTIC-CLEANUP @ 0 T=
   ASSERT-IDLE ;

: TEST-PREPARE-FAILURE ( -- )
   RESET-CONTROLS RESET-TRACES
   10 20 30 SET-VALUES
   -1 TRACK-VALUES !
   -1 TRACE-ON !
   -1 BODY-MUTATE !
   GENERATED-DECL:PHASE-PREPARE FAIL-PHASE !
   PARTICIPANT-B FAIL-PARTICIPANT !
   RUN-BODY-CATCH E-INJECT T=
   SNAPSHOT-TRACE @ 14523 T=
   PREPARE-TRACE @ 12 T=
   COMMIT-TRACE @ 0 T=
   ROLLBACK-TRACE @ 321 T=
   10 20 30 ASSERT-VALUES
   TEST-STATE DECLARATION-TRANSACTION:LAST-FAILURE-PHASE GENERATED-DECL:PHASE-PREPARE T=
   TEST-STATE DECLARATION-TRANSACTION:LAST-FAILURE-PARTICIPANT PARTICIPANT-B T=
   ASSERT-IDLE ;

: TEST-COMMIT-FAILURE ( -- )
   RESET-CONTROLS RESET-TRACES
   10 20 30 SET-VALUES
   -1 TRACK-VALUES !
   -1 TRACE-ON !
   -1 BODY-MUTATE !
   GENERATED-DECL:PHASE-COMMIT FAIL-PHASE !
   PARTICIPANT-B FAIL-PARTICIPANT !
   RUN-BODY-CATCH E-INJECT T=
   SNAPSHOT-TRACE @ 14523 T=
   PREPARE-TRACE @ 123 T=
   COMMIT-TRACE @ 12 T=
   ROLLBACK-TRACE @ 321 T=
   FINALIZE-TRACE @ 0 T=
   10 20 30 ASSERT-VALUES
   TEST-STATE DECLARATION-TRANSACTION:LAST-FAILURE-PHASE GENERATED-DECL:PHASE-COMMIT T=
   TEST-STATE DECLARATION-TRANSACTION:LAST-FAILURE-PARTICIPANT PARTICIPANT-B T=
   ASSERT-IDLE ;

: TEST-ROLLBACK-CLEANUP ( -- )
   RESET-CONTROLS RESET-TRACES RESET-DIAGNOSTIC
   10 20 30 SET-VALUES
   -1 TRACK-VALUES !
   -1 TRACE-ON !
   -1 BODY-MUTATE !
   E-BODY BODY-ERROR !
   PARTICIPANT-B ROLLBACK-FAIL-PARTICIPANT !
   -1 DIAGNOSTIC-THROWS !
   RUN-BODY-CATCH E-BODY T=
   ROLLBACK-TRACE @ 321 T=
   10 20 30 ASSERT-VALUES
   DIAGNOSTIC-COUNT @ 1 T=
   DIAGNOSTIC-PRIMARY @ E-BODY T=
   DIAGNOSTIC-CLEANUP @ E-CLEANUP T=
   TEST-STATE DECLARATION-TRANSACTION:LAST-CLEANUP-PARTICIPANT PARTICIPANT-B T=
   TEST-STATE DECLARATION-TRANSACTION:POISONED? TTRUE
   RUN-BODY-CATCH DECLARATION-TRANSACTION:E-TRANSACTION-POISONED T=
   ASSERT-IDLE ;

: TEST-FINALIZE-CLEANUP ( -- )
   RESET-CONTROLS RESET-TRACES RESET-DIAGNOSTIC
   -1 TRACE-ON !
   GENERATED-DECL:PHASE-FINALIZE FAIL-PHASE !
   PARTICIPANT-B FAIL-PARTICIPANT !
   RUN-BODY-CATCH E-INJECT T=
   FINALIZE-TRACE @ 321 T=
   DIAGNOSTIC-COUNT @ 1 T=
   DIAGNOSTIC-PRIMARY @ 0 T=
   DIAGNOSTIC-CLEANUP @ E-INJECT T=
   TEST-STATE DECLARATION-TRANSACTION:LAST-CLEANUP-PARTICIPANT PARTICIPANT-B T=
   TEST-STATE DECLARATION-TRANSACTION:POISONED? TTRUE
   RUN-BODY-CATCH DECLARATION-TRANSACTION:E-TRANSACTION-POISONED T=
   ASSERT-IDLE ;

: TEST-CALLBACK-DEPTH ( -- )
   INIT-TEST-COORDINATOR
   REGISTER-CORRUPT
   TEST-STATE DECLARATION-TRANSACTION:SEAL
   RUN-BODY-CATCH DECLARATION-TRANSACTION:E-PARTICIPANT-DEPTH T=
   TEST-STATE DECLARATION-TRANSACTION:LAST-FAILURE-PHASE GENERATED-DECL:PHASE-SNAPSHOT T=
   TEST-STATE DECLARATION-TRANSACTION:LAST-FAILURE-PARTICIPANT PARTICIPANT-CORRUPT T=
   TEST-STATE DECLARATION-TRANSACTION:POISONED? TTRUE
   RUN-BODY-CATCH DECLARATION-TRANSACTION:E-TRANSACTION-POISONED T=
   ASSERT-IDLE ;

: TEST-NESTING-GROWTH ( -- )
   RESET-CONTROLS RESET-TRACES
   12 RUN-NESTED
   NESTING-BODIES @ 13 T=
   ASSERT-IDLE ;

: EVALUATE-INNER-DECLARATION ( -- )
   s" STRUCTURE gdnested 0 FIELD x n ;STRUCTURE" INCLUDE-EVALUATE ;

: OUTER-NESTED-BODY ( -- )
   EVALUATE-INNER-DECLARATION
   DECL-EVENT:COUNT INNER-EVENT-N !
   TYPE-FIELD:COUNT INNER-FIELD-N ! ;

: OUTER-NESTED-FAIL-BODY ( -- )
   OUTER-NESTED-BODY
   E-BODY throw ;

: RUN-OUTER-NESTED-FAIL-BODY ( -- )
   [: OUTER-NESTED-FAIL-BODY ;] GENERATED-DECL:RUN ;

: RUN-OUTER-NESTED-FAIL ( -- n )
   [: RUN-OUTER-NESTED-FAIL-BODY ;] catch ;

: TEST-NESTED-DECLARATION-ROLLBACK ( -- )
   RECORD-BASELINE RECORD-OWNER-DEPTHS
   RUN-OUTER-NESTED-FAIL E-BODY T=
   INNER-EVENT-N @ EVENT-N0 @ T=
   INNER-FIELD-N @ FIELD-N0 @ T=
   ASSERT-UNCHANGED
   ASSERT-OWNER-DEPTHS
   s" GDNESTED:MAKE" WORD-ABSENT? TTRUE

   [: OUTER-NESTED-BODY ;] GENERATED-DECL:RUN
   INNER-EVENT-N @ EVENT-N0 @ T=
   INNER-FIELD-N @ FIELD-N0 @ T=
   DECL-EVENT:COUNT EVENT-N0 @ > TTRUE
   TYPE-FIELD:COUNT FIELD-N0 @ > TTRUE
   s" GDNESTED-ROUNDTRIP ( n -- n ) GDNESTED:MAKE GDNESTED:UNMAKE"
      CHECK-QUIET-CANDIDATE! 0 <> TTRUE
   ASSERT-PRODUCTION-IDLE ;

: TEST-NAME-PREFLIGHT-CLEARS-AUTHORITY ( -- )
   RECORD-BASELINE RECORD-OWNER-DEPTHS RECORD-NATIVE-HIGHWATERS
   INSTALL-NAME-PREFLIGHT-FAILURE
   s" ENUM gdnamefail left right ;ENUM" EVALUATE-CATCH E-INJECT T=
   RESTORE-GENERATED-EVALUATOR
   GENERATED-N @ 0 T=
   GENERATED-NAME-PREFLIGHT-N @ 1 T=
   s" GDNAMEFAIL:LEFT ( -- ) 0" ASSERT-NO-STALE-CONSTRUCTOR
   s" GDNAMEFAIL:LEFT" QUALIFIED-ABSENT? TTRUE
   ASSERT-UNCHANGED ASSERT-OWNER-DEPTHS ASSERT-NATIVE-HIGHWATERS ;

: TEST-GENERATOR-ROLLBACK ( -- )
   RESET-CONTROLS RESET-TRACES RESET-DIAGNOSTIC
   RECORD-BASELINE RECORD-OWNER-DEPTHS
   RECORD-NATIVE-HIGHWATERS
   INSTALL-SECOND-WORD-FAILURE
   s" ENUM gdtx red blue ;ENUM" EVALUATE-CATCH
      E-GENERATED-REJECT T=
   RESTORE-GENERATED-EVALUATOR
   GENERATED-N @ 0 T=
   GENERATED-NAME-PREFLIGHT-N @ 2 T=
   GENERATED-PLAN-BROKEN @ TTRUE
   GENERATED-XREF-ABSENT @ TTRUE
   GENERATED-CHECKER-ABSENT @ TTRUE
   GENERATED-EVENT-UNPUBLISHED @ TTRUE
   GENERATED-PROTECTION-UNPUBLISHED @ TTRUE
   GENERATED-DICTIONARY-UNPUBLISHED @ TTRUE
   ASSERT-UNCHANGED
   ASSERT-OWNER-DEPTHS
   ASSERT-NATIVE-HIGHWATERS
   s" GDTX:RED" WORD-ABSENT? TTRUE
   s" GDTX:RED" QUALIFIED-ABSENT? TTRUE
   s" GDTX:BLUE" QUALIFIED-ABSENT? TTRUE
   s" GDTX:RED" CHECKER-DEFINED? 0= TTRUE
   s" GDTX:BLUE" CHECKER-DEFINED? 0= TTRUE
   s" GDTX:RED ( -- ) 0" ASSERT-NO-STALE-CONSTRUCTOR
   s" package gdtx ;package" EVALUATE-CATCH 0 T=
   ASSERT-PRODUCTION-IDLE ;

: TEST-EVALUATOR-FAILURE-CLEARS-AUTHORITY ( -- )
   RECORD-BASELINE RECORD-OWNER-DEPTHS RECORD-NATIVE-HIGHWATERS
   INSTALL-EVALUATOR-FAILURE
   s" ENUM gdevalfail north south ;ENUM" EVALUATE-CATCH E-INJECT T=
   RESTORE-GENERATED-EVALUATOR
   GENERATED-N @ 1 T=
   s" GDEVALFAIL:NORTH" QUALIFIED-ABSENT? TTRUE
   s" GDEVALFAIL:SOUTH" QUALIFIED-ABSENT? TTRUE
   s" GDEVALFAIL:SOUTH ( -- ) 0" ASSERT-NO-STALE-CONSTRUCTOR
   ASSERT-UNCHANGED ASSERT-OWNER-DEPTHS ASSERT-NATIVE-HIGHWATERS ;

: RUN-CAPACITY-PREFLIGHT ( -- )
   s" GDNESTED:MAKE" CAPACITY-PREFLIGHT-N @ TDECL-CAPACITY-PREFLIGHT-XT ;

: CAPACITY-PREFLIGHT-CATCH ( n -- n )
   CAPACITY-PREFLIGHT-N !
   [: RUN-CAPACITY-PREFLIGHT ;] catch ;

: TEST-PLAN-CAPACITY-PREFLIGHT ( -- )
   s" GDNESTED:MAKE" 2 GENERATED-DECL-NAME-PREFLIGHT:DICTIONARY-RECORDS 2 T=
   s" GDCAP-MISSING:MAKE" 2 GENERATED-DECL-NAME-PREFLIGHT:DICTIONARY-RECORDS 3 T=
   s" GDNESTED:MAKE" GENERATED-DECL-NAME-PREFLIGHT:NEW-WORDLIST? 0= TTRUE
   s" GDCAP-MISSING:MAKE" GENERATED-DECL-NAME-PREFLIGHT:NEW-WORDLIST? TTRUE
   DICT-CAP ndict@ - {: room:n :}
   room CAPACITY-PREFLIGHT-CATCH 0 T=
   room 1 + CAPACITY-PREFLIGHT-CATCH E-GENERATED-DICTIONARY-CAP T=
   ASSERT-PRODUCTION-IDLE ;

: TEST-SUCCESS-PUBLICATION ( -- )
   RESET-CONTROLS RESET-TRACES RESET-DIAGNOSTIC
   prot-wid-room PROTECTION-ROOM-N0 !
   s" PRODUCT gdok 0 FIELD x n ;PRODUCT" EVALUATE-CATCH 0 T=
   prot-wid-room PROTECTION-ROOM-N0 @ 1 - T=
   s" GDOK-USE ( n -- gdok ) GDOK:MAKE"
      CHECK-QUIET-CANDIDATE! 0 <> TTRUE
   s" package gdok ;package" EVALUATE-CATCH 7111 T=
   ASSERT-PRODUCTION-IDLE ;

public

: RUN ( -- )
   CAP-TEST-RUN
   RESET-CONTROLS
   INIT-TEST-COORDINATOR
   TEST-REGISTRATION
   TEST-PHASE-ORDER
   TEST-ACTIVE-REGISTRATION
   TEST-PARTIAL-SNAPSHOT
   TEST-PREPARE-FAILURE
   TEST-COMMIT-FAILURE
   TEST-NESTING-GROWTH
   TEST-ROLLBACK-CLEANUP
   INIT-TEST-COORDINATOR
   REGISTER-TEST-PARTICIPANTS
   TEST-FINALIZE-CLEANUP
   TEST-CALLBACK-DEPTH
   TEST-NESTED-DECLARATION-ROLLBACK
   TEST-NAME-PREFLIGHT-CLEARS-AUTHORITY
   TEST-GENERATOR-ROLLBACK
   TEST-EVALUATOR-FAILURE-CLEARS-AUTHORITY
   TEST-PLAN-CAPACITY-PREFLIGHT
   TEST-SUCCESS-PUBLICATION
   RESTORE-GENERATED-EVALUATOR
   T-REPORT ;

;package

GENERATED-DECLARATION-TXN-TEST:RUN
