\ generated-declaration-transaction-suite.f - atomic declaration publication.
\ Run: bin/hb --load test/generated-declaration-transaction-suite.f

require lib/test.f
require test/checker-assert.f

package GENERATED-DECLARATION-TXN-TEST

-7190 constant E-INJECT
-7191 constant E-CLEANUP
-7192 constant E-BODY
-7193 constant E-DIAGNOSTIC

101 constant PARTICIPANT-A
102 constant PARTICIPANT-B
103 constant PARTICIPANT-C
104 constant PARTICIPANT-D
105 constant PARTICIPANT-CORRUPT
109 constant PARTICIPANT-LATE

200 constant ORDER-A
700 constant ORDER-B
850 constant ORDER-C
400 constant ORDER-D
950 constant ORDER-LATE

4 constant TEST-CAP
create TEST-TABLE TEST-CAP DECLARATION-TRANSACTION:ROW-CELLS * cells allot
create TEST-STATE DECLARATION-TRANSACTION:STATE-CELLS cells allot

PTR-VARIABLE SOURCE-A
variable SOURCE-U
variable FAMILY-N0
variable VARIANT-N0
variable FIELD-N0
variable SCHEMA-N0
variable SCHEMA-ROOT-N0
variable LAYOUT-N0
variable STRING-N0
variable EVENT-N0
variable PROTECTION-ROOM-N0
variable GENERATED-N

variable SNAPSHOT-TRACE
variable PREPARE-TRACE
variable COMMIT-TRACE
variable ROLLBACK-TRACE
variable FINALIZE-TRACE
variable TRACE-ON

variable FAIL-PHASE
variable FAIL-PARTICIPANT
variable ROLLBACK-FAIL-PARTICIPANT
variable SNAPSHOT-MUTATE-PARTICIPANT
variable BODY-MUTATE
variable BODY-REGISTER
variable BODY-ERROR

variable VALUE-A
variable VALUE-B
variable VALUE-C
variable SAVED-A
variable SAVED-B
variable SAVED-C
variable TRACK-VALUES

variable ALLOCATOR-CALLS
variable ALLOCATOR-FAIL-AT
variable ALLOCATED-BYTES

variable DIAGNOSTIC-COUNT
variable DIAGNOSTIC-PRIMARY
variable DIAGNOSTIC-CLEANUP
variable DIAGNOSTIC-THROWS

variable NESTING-LEFT
variable NESTING-BODIES
defer NESTED-XT ( -- )

variable CHECKER-DEPTH-N0
variable FIELD-DEPTH-N0
variable EVENT-DEPTH-N0
variable DICTIONARY-DEPTH-N0
variable STAGED-N0
variable INNER-EVENT-N
variable INNER-FIELD-N
PTR-VARIABLE TABLE-N0
variable CAP-N0
variable ALLOCATED-N0

: EVALUATE-GENERATED ( ptr u8 n -- )
   GENERATED-N @ 1 + dup GENERATED-N !
   2 = IF 2drop E-INJECT throw THEN
   INCLUDE-EVALUATE ;

: INSTALL-SECOND-WORD-FAILURE ( -- )
   0 GENERATED-N !
   [: EVALUATE-GENERATED ;] is TDECL-EVAL-XT ;

: RESTORE-GENERATED-EVALUATOR ( -- )
   [: INCLUDE-EVALUATE ;] is TDECL-EVAL-XT ;

: EVALUATE-SOURCE ( -- )
   SOURCE-A @ SOURCE-U @ INCLUDE-EVALUATE ;

: EVALUATE-CATCH ( ptr u8 n -- n )
   SOURCE-U ! SOURCE-A !
   [: EVALUATE-SOURCE ;] catch ;

: WORD-ABSENT? ( ptr u8 n -- bool )
   0 search-wl 0= ;

: QUALIFIED-ABSENT? ( ptr u8 n -- bool )
   XREF-FIND XREF-FOUND? 0= ;

: RECORD-BASELINE ( -- )
   TFAM-N@ FAMILY-N0 !
   SUMV-N@ VARIANT-N0 !
   TYPE-FIELD:COUNT FIELD-N0 !
   SCHEMA-N@ SCHEMA-N0 !
   SCHEMA-ROOT-N@ SCHEMA-ROOT-N0 !
   LAY-N@ LAYOUT-N0 !
   TF-STR-U@ STRING-N0 !
   DECL-EVENT:COUNT EVENT-N0 !
   prot-wid-room PROTECTION-ROOM-N0 ! ;

: RECORD-OWNER-DEPTHS ( -- )
   CHECKER-SCOPE-DEPTH CHECKER-DEPTH-N0 !
   TYPE-FIELD:TX-DEPTH FIELD-DEPTH-N0 !
   DECL-EVENT:DEPTH EVENT-DEPTH-N0 !
   GENERATED-DECL-DICTIONARY:DEPTH DICTIONARY-DEPTH-N0 !
   GENERATED-DECL-PROTECTION:STAGED-COUNT STAGED-N0 ! ;

: ASSERT-OWNER-DEPTHS ( -- )
   CHECKER-SCOPE-DEPTH CHECKER-DEPTH-N0 @ T=
   TYPE-FIELD:TX-DEPTH FIELD-DEPTH-N0 @ T=
   DECL-EVENT:DEPTH EVENT-DEPTH-N0 @ T=
   GENERATED-DECL-DICTIONARY:DEPTH DICTIONARY-DEPTH-N0 @ T=
   GENERATED-DECL-PROTECTION:STAGED-COUNT STAGED-N0 @ T=
   GENERATED-DECL:DEPTH 0 T=
   GENERATED-DECL:POISONED? 0= TTRUE ;

: ASSERT-UNCHANGED ( -- )
   TFAM-N@ FAMILY-N0 @ T=
   SUMV-N@ VARIANT-N0 @ T=
   TYPE-FIELD:COUNT FIELD-N0 @ T=
   SCHEMA-N@ SCHEMA-N0 @ T=
   SCHEMA-ROOT-N@ SCHEMA-ROOT-N0 @ T=
   LAY-N@ LAYOUT-N0 @ T=
   TF-STR-U@ STRING-N0 @ T=
   DECL-EVENT:COUNT EVENT-N0 @ T=
   prot-wid-room PROTECTION-ROOM-N0 @ T= ;

: APPEND-DIGIT ( n ptr a -- ) {: digit:n trace:ptr :}
   TRACE-ON @ 0= IF EXIT THEN
   trace @ 10 * digit + trace ! ;

: RESET-TRACES ( -- )
   0 SNAPSHOT-TRACE !
   0 PREPARE-TRACE !
   0 COMMIT-TRACE !
   0 ROLLBACK-TRACE !
   0 FINALIZE-TRACE ! ;

: RESET-CONTROLS ( -- )
   0 FAIL-PHASE !
   0 FAIL-PARTICIPANT !
   0 ROLLBACK-FAIL-PARTICIPANT !
   0 SNAPSHOT-MUTATE-PARTICIPANT !
   0 BODY-MUTATE !
   0 BODY-REGISTER !
   0 BODY-ERROR !
   0 TRACK-VALUES !
   0 TRACE-ON ! ;

: MAYBE-MUTATE-SNAPSHOT ( ptr a n -- ) {: value:ptr participant:n :}
   SNAPSHOT-MUTATE-PARTICIPANT @ participant = IF 1 value +! THEN ;

: MAYBE-FAIL ( n n -- ) {: phase:n participant:n :}
   FAIL-PHASE @ phase = FAIL-PARTICIPANT @ participant = and
      IF E-INJECT throw THEN ;

: MAYBE-FAIL-ROLLBACK ( n -- ) {: participant:n :}
   ROLLBACK-FAIL-PARTICIPANT @ participant = IF E-CLEANUP throw THEN ;

: SNAPSHOT-A ( n -- n ) {: depth:n :}
   TRACK-VALUES @ IF VALUE-A @ SAVED-A ! THEN
   1 SNAPSHOT-TRACE APPEND-DIGIT
   VALUE-A PARTICIPANT-A MAYBE-MUTATE-SNAPSHOT
   GENERATED-DECL:PHASE-SNAPSHOT PARTICIPANT-A MAYBE-FAIL
   depth ;

: PREPARE-A ( n -- n ) {: depth:n :}
   1 PREPARE-TRACE APPEND-DIGIT
   GENERATED-DECL:PHASE-PREPARE PARTICIPANT-A MAYBE-FAIL
   depth ;

: COMMIT-A ( n -- n ) {: depth:n :}
   1 COMMIT-TRACE APPEND-DIGIT
   GENERATED-DECL:PHASE-COMMIT PARTICIPANT-A MAYBE-FAIL
   depth ;

: ROLLBACK-A ( n -- n ) {: depth:n :}
   TRACK-VALUES @ IF SAVED-A @ VALUE-A ! THEN
   1 ROLLBACK-TRACE APPEND-DIGIT
   PARTICIPANT-A MAYBE-FAIL-ROLLBACK
   depth ;

: FINALIZE-A ( n -- n ) {: depth:n :}
   1 FINALIZE-TRACE APPEND-DIGIT
   GENERATED-DECL:PHASE-FINALIZE PARTICIPANT-A MAYBE-FAIL
   depth ;

: SNAPSHOT-B ( n -- n ) {: depth:n :}
   TRACK-VALUES @ IF VALUE-B @ SAVED-B ! THEN
   2 SNAPSHOT-TRACE APPEND-DIGIT
   VALUE-B PARTICIPANT-B MAYBE-MUTATE-SNAPSHOT
   GENERATED-DECL:PHASE-SNAPSHOT PARTICIPANT-B MAYBE-FAIL
   depth ;

: PREPARE-B ( n -- n ) {: depth:n :}
   2 PREPARE-TRACE APPEND-DIGIT
   GENERATED-DECL:PHASE-PREPARE PARTICIPANT-B MAYBE-FAIL
   depth ;

: COMMIT-B ( n -- n ) {: depth:n :}
   2 COMMIT-TRACE APPEND-DIGIT
   GENERATED-DECL:PHASE-COMMIT PARTICIPANT-B MAYBE-FAIL
   depth ;

: ROLLBACK-B ( n -- n ) {: depth:n :}
   TRACK-VALUES @ IF SAVED-B @ VALUE-B ! THEN
   2 ROLLBACK-TRACE APPEND-DIGIT
   PARTICIPANT-B MAYBE-FAIL-ROLLBACK
   depth ;

: FINALIZE-B ( n -- n ) {: depth:n :}
   2 FINALIZE-TRACE APPEND-DIGIT
   GENERATED-DECL:PHASE-FINALIZE PARTICIPANT-B MAYBE-FAIL
   depth ;

: SNAPSHOT-C ( n -- n ) {: depth:n :}
   TRACK-VALUES @ IF VALUE-C @ SAVED-C ! THEN
   3 SNAPSHOT-TRACE APPEND-DIGIT
   VALUE-C PARTICIPANT-C MAYBE-MUTATE-SNAPSHOT
   GENERATED-DECL:PHASE-SNAPSHOT PARTICIPANT-C MAYBE-FAIL
   depth ;

: PREPARE-C ( n -- n ) {: depth:n :}
   3 PREPARE-TRACE APPEND-DIGIT
   GENERATED-DECL:PHASE-PREPARE PARTICIPANT-C MAYBE-FAIL
   depth ;

: COMMIT-C ( n -- n ) {: depth:n :}
   3 COMMIT-TRACE APPEND-DIGIT
   GENERATED-DECL:PHASE-COMMIT PARTICIPANT-C MAYBE-FAIL
   depth ;

: ROLLBACK-C ( n -- n ) {: depth:n :}
   TRACK-VALUES @ IF SAVED-C @ VALUE-C ! THEN
   3 ROLLBACK-TRACE APPEND-DIGIT
   PARTICIPANT-C MAYBE-FAIL-ROLLBACK
   depth ;

: FINALIZE-C ( n -- n ) {: depth:n :}
   3 FINALIZE-TRACE APPEND-DIGIT
   GENERATED-DECL:PHASE-FINALIZE PARTICIPANT-C MAYBE-FAIL
   depth ;

: REGISTER-A ( -- )
   TEST-STATE PARTICIPANT-A ORDER-A
   [: SNAPSHOT-A ;] [: PREPARE-A ;] [: COMMIT-A ;]
   [: ROLLBACK-A ;] [: FINALIZE-A ;]
   DECLARATION-TRANSACTION:REGISTER ;

: REGISTER-B ( -- )
   TEST-STATE PARTICIPANT-B ORDER-B
   [: SNAPSHOT-B ;] [: PREPARE-B ;] [: COMMIT-B ;]
   [: ROLLBACK-B ;] [: FINALIZE-B ;]
   DECLARATION-TRANSACTION:REGISTER ;

: REGISTER-C ( -- )
   TEST-STATE PARTICIPANT-C ORDER-C
   [: SNAPSHOT-C ;] [: PREPARE-C ;] [: COMMIT-C ;]
   [: ROLLBACK-C ;] [: FINALIZE-C ;]
   DECLARATION-TRANSACTION:REGISTER ;

: INERT ( n -- n ) ;

: CORRUPT-SNAPSHOT ( n -- n ) 1 + ;

: REGISTER-D ( -- )
   TEST-STATE PARTICIPANT-D ORDER-D
   [: INERT ;] [: INERT ;] [: INERT ;] [: INERT ;] [: INERT ;]
   DECLARATION-TRANSACTION:REGISTER ;

: REGISTER-LATE ( -- )
   TEST-STATE PARTICIPANT-LATE ORDER-LATE
   [: INERT ;] [: INERT ;] [: INERT ;] [: INERT ;] [: INERT ;]
   DECLARATION-TRANSACTION:REGISTER ;

: REGISTER-CORRUPT ( -- )
   TEST-STATE PARTICIPANT-CORRUPT ORDER-A
   [: CORRUPT-SNAPSHOT ;]
   [: INERT ;] [: INERT ;] [: INERT ;] [: INERT ;]
   DECLARATION-TRANSACTION:REGISTER ;

: REGISTER-A-CATCH ( -- n )
   [: REGISTER-A ;] catch ;

: REGISTER-B-CATCH ( -- n )
   [: REGISTER-B ;] catch ;

: REGISTER-LATE-CATCH ( -- n )
   [: REGISTER-LATE ;] catch ;

: INJECTING-ALLOCATOR ( ptr a n n -- ptr a )
   {: base:ptr oldbytes:n newbytes:n :}
   ALLOCATOR-CALLS @ 1 + dup ALLOCATOR-CALLS !
   ALLOCATOR-FAIL-AT @ = IF E-INJECT throw THEN
   base oldbytes newbytes DECLARATION-TRANSACTION:DEFAULT-ALLOCATOR {: grown:ptr :}
   newbytes ALLOCATED-BYTES +!
   grown ;

: INSTALL-ALLOCATOR-FAILURE ( n -- )
   ALLOCATOR-FAIL-AT !
   0 ALLOCATOR-CALLS ! ;

: RECORD-DIAGNOSTIC ( n n -- ) {: primary:n cleanup:n :}
   primary DIAGNOSTIC-PRIMARY !
   cleanup DIAGNOSTIC-CLEANUP !
   DIAGNOSTIC-COUNT @ 1 + DIAGNOSTIC-COUNT !
   DIAGNOSTIC-THROWS @ IF E-DIAGNOSTIC throw THEN ;

: RESET-DIAGNOSTIC ( -- )
   0 DIAGNOSTIC-COUNT !
   0 DIAGNOSTIC-PRIMARY !
   0 DIAGNOSTIC-CLEANUP !
   0 DIAGNOSTIC-THROWS ! ;

: INIT-TEST-COORDINATOR ( -- )
   0 ALLOCATOR-CALLS !
   0 ALLOCATOR-FAIL-AT !
   0 ALLOCATED-BYTES !
   RESET-DIAGNOSTIC
   TEST-STATE TEST-TABLE TEST-CAP
   [: INJECTING-ALLOCATOR ;]
   [: RECORD-DIAGNOSTIC ;]
   DECLARATION-TRANSACTION:INIT ;

: REGISTER-TEST-PARTICIPANTS ( -- )
   REGISTER-A REGISTER-B REGISTER-C REGISTER-D REGISTER-LATE
   TEST-STATE DECLARATION-TRANSACTION:SEAL ;

: TRANSACTION-BODY ( -- )
   BODY-MUTATE @ IF
      10 VALUE-A +!
      20 VALUE-B +!
      30 VALUE-C +!
   THEN
   BODY-REGISTER @ IF REGISTER-D THEN
   BODY-ERROR @ dup 0 <> IF throw THEN drop ;

: RUN-BODY ( -- )
   TEST-STATE [: TRANSACTION-BODY ;] DECLARATION-TRANSACTION:RUN ;

: RUN-BODY-CATCH ( -- n )
   [: RUN-BODY ;] catch ;

: NESTED-BODY ( -- )
   NESTING-BODIES @ 1 + NESTING-BODIES !
   NESTING-LEFT @ 0 > IF
      NESTING-LEFT @ 1 - NESTING-LEFT !
      TEST-STATE [: NESTED-XT ;] DECLARATION-TRANSACTION:RUN
   THEN ;

: INSTALL-NESTED ( -- )
   [: NESTED-BODY ;] is NESTED-XT ;
INSTALL-NESTED

: RUN-NESTED ( n -- )
   NESTING-LEFT !
   0 NESTING-BODIES !
   TEST-STATE [: NESTED-BODY ;] DECLARATION-TRANSACTION:RUN ;

: SET-VALUES ( n n n -- )
   VALUE-C ! VALUE-B ! VALUE-A ! ;

: ASSERT-VALUES ( n n n -- )
   {: a:n b:n c:n :}
   VALUE-A @ a T=
   VALUE-B @ b T=
   VALUE-C @ c T= ;

: ASSERT-IDLE ( -- )
   TEST-STATE DECLARATION-TRANSACTION:DEPTH 0 T= ;

: ASSERT-PRODUCTION-IDLE ( -- )
   GENERATED-DECL:DEPTH 0 T= ;

: TEST-REGISTRATION ( -- )
   TEST-STATE DECLARATION-TRANSACTION:COUNT 0 T=
   REGISTER-A
   TEST-STATE DECLARATION-TRANSACTION:COUNT 1 T=
   REGISTER-A-CATCH DECLARATION-TRANSACTION:E-PARTICIPANT-DUP T=
   REGISTER-B REGISTER-C REGISTER-D
   TEST-STATE DECLARATION-TRANSACTION:COUNT 4 T=

   TEST-STATE DECLARATION-TRANSACTION:TABLE TABLE-N0 !
   TEST-STATE DECLARATION-TRANSACTION:CAPACITY CAP-N0 !
   ALLOCATED-BYTES @ ALLOCATED-N0 !
   1 INSTALL-ALLOCATOR-FAILURE
   REGISTER-LATE-CATCH E-INJECT T=
   ALLOCATOR-CALLS @ 1 T=
   TEST-STATE DECLARATION-TRANSACTION:COUNT 4 T=
   TEST-STATE DECLARATION-TRANSACTION:TABLE TABLE-N0 @ = TTRUE
   TEST-STATE DECLARATION-TRANSACTION:CAPACITY CAP-N0 @ T=
   ALLOCATED-BYTES @ ALLOCATED-N0 @ T=

   0 ALLOCATOR-FAIL-AT !
   REGISTER-LATE
   TEST-STATE DECLARATION-TRANSACTION:COUNT 5 T=
   TEST-STATE DECLARATION-TRANSACTION:CAPACITY TEST-CAP 2 * T=
   ALLOCATED-BYTES @ ALLOCATED-N0 @ > TTRUE
   TEST-STATE DECLARATION-TRANSACTION:SEAL
   REGISTER-LATE-CATCH DECLARATION-TRANSACTION:E-REGISTRATION-SEALED T=

   GENERATED-DECL:COUNT 4 T=
   GENERATED-DECL:SEALED? TTRUE
   s" GENERATED-DECL:REGISTER" WORD-ABSENT? TTRUE
   s" GENERATED-DECL:ALLOCATOR!" WORD-ABSENT? TTRUE
   s" GENERATED-DECL:DIAGNOSTIC!" WORD-ABSENT? TTRUE
   s" GENERATED-DECL:RESET" WORD-ABSENT? TTRUE
   s" GENERATED-DECL:SEAL" WORD-ABSENT? TTRUE
   s" GENERATED-DECL-OWNER:REGISTER" QUALIFIED-ABSENT? TTRUE
   s" GENERATED-DECL-OWNER:REGISTER-LAST" QUALIFIED-ABSENT? TTRUE
   s" GENERATED-DECL-OWNER:RUN" QUALIFIED-ABSENT? TTRUE
   s" GENERATED-DECL-OWNER:DEPTH" QUALIFIED-ABSENT? TTRUE
   s" TYPE-FIELD-OWNER:TX-SCHEMA-FOR" QUALIFIED-ABSENT? TTRUE ;

: TEST-PHASE-ORDER ( -- )
   RESET-CONTROLS RESET-TRACES
   -1 TRACE-ON !
   RUN-BODY
   SNAPSHOT-TRACE @ 123 T=
   PREPARE-TRACE @ 123 T=
   COMMIT-TRACE @ 123 T=
   FINALIZE-TRACE @ 321 T=
   ROLLBACK-TRACE @ 0 T=
   ASSERT-IDLE ;

: TEST-ACTIVE-REGISTRATION ( -- )
   RESET-CONTROLS
   -1 BODY-REGISTER !
   RUN-BODY-CATCH DECLARATION-TRANSACTION:E-REGISTRATION-ACTIVE T=
   TEST-STATE DECLARATION-TRANSACTION:COUNT 5 T=
   TEST-STATE DECLARATION-TRANSACTION:LAST-FAILURE-PHASE GENERATED-DECL:PHASE-BODY T=
   TEST-STATE DECLARATION-TRANSACTION:LAST-FAILURE-PARTICIPANT -1 T=
   ASSERT-IDLE ;

: TEST-PARTIAL-SNAPSHOT ( -- )
   RESET-CONTROLS RESET-TRACES RESET-DIAGNOSTIC
   10 20 30 SET-VALUES
   -1 TRACK-VALUES !
   -1 TRACE-ON !
   PARTICIPANT-B SNAPSHOT-MUTATE-PARTICIPANT !
   GENERATED-DECL:PHASE-SNAPSHOT FAIL-PHASE !
   PARTICIPANT-B FAIL-PARTICIPANT !
   RUN-BODY-CATCH E-INJECT T=
   SNAPSHOT-TRACE @ 12 T=
   ROLLBACK-TRACE @ 21 T=
   10 20 30 ASSERT-VALUES
   TEST-STATE DECLARATION-TRANSACTION:LAST-FAILURE-PHASE GENERATED-DECL:PHASE-SNAPSHOT T=
   TEST-STATE DECLARATION-TRANSACTION:LAST-FAILURE-PARTICIPANT PARTICIPANT-B T=
   DIAGNOSTIC-PRIMARY @ E-INJECT T=
   DIAGNOSTIC-CLEANUP @ 0 T=
   ASSERT-IDLE ;

: TEST-PREPARE-FAILURE ( -- )
   RESET-CONTROLS RESET-TRACES
   10 20 30 SET-VALUES
   -1 TRACK-VALUES !
   -1 TRACE-ON !
   -1 BODY-MUTATE !
   GENERATED-DECL:PHASE-PREPARE FAIL-PHASE !
   PARTICIPANT-B FAIL-PARTICIPANT !
   RUN-BODY-CATCH E-INJECT T=
   SNAPSHOT-TRACE @ 123 T=
   PREPARE-TRACE @ 12 T=
   COMMIT-TRACE @ 0 T=
   ROLLBACK-TRACE @ 321 T=
   10 20 30 ASSERT-VALUES
   TEST-STATE DECLARATION-TRANSACTION:LAST-FAILURE-PHASE GENERATED-DECL:PHASE-PREPARE T=
   TEST-STATE DECLARATION-TRANSACTION:LAST-FAILURE-PARTICIPANT PARTICIPANT-B T=
   ASSERT-IDLE ;

: TEST-COMMIT-FAILURE ( -- )
   RESET-CONTROLS RESET-TRACES
   10 20 30 SET-VALUES
   -1 TRACK-VALUES !
   -1 TRACE-ON !
   -1 BODY-MUTATE !
   GENERATED-DECL:PHASE-COMMIT FAIL-PHASE !
   PARTICIPANT-B FAIL-PARTICIPANT !
   RUN-BODY-CATCH E-INJECT T=
   SNAPSHOT-TRACE @ 123 T=
   PREPARE-TRACE @ 123 T=
   COMMIT-TRACE @ 12 T=
   ROLLBACK-TRACE @ 321 T=
   FINALIZE-TRACE @ 0 T=
   10 20 30 ASSERT-VALUES
   TEST-STATE DECLARATION-TRANSACTION:LAST-FAILURE-PHASE GENERATED-DECL:PHASE-COMMIT T=
   TEST-STATE DECLARATION-TRANSACTION:LAST-FAILURE-PARTICIPANT PARTICIPANT-B T=
   ASSERT-IDLE ;

: TEST-ROLLBACK-CLEANUP ( -- )
   RESET-CONTROLS RESET-TRACES RESET-DIAGNOSTIC
   10 20 30 SET-VALUES
   -1 TRACK-VALUES !
   -1 TRACE-ON !
   -1 BODY-MUTATE !
   E-BODY BODY-ERROR !
   PARTICIPANT-B ROLLBACK-FAIL-PARTICIPANT !
   -1 DIAGNOSTIC-THROWS !
   RUN-BODY-CATCH E-BODY T=
   ROLLBACK-TRACE @ 321 T=
   10 20 30 ASSERT-VALUES
   DIAGNOSTIC-COUNT @ 1 T=
   DIAGNOSTIC-PRIMARY @ E-BODY T=
   DIAGNOSTIC-CLEANUP @ E-CLEANUP T=
   TEST-STATE DECLARATION-TRANSACTION:LAST-CLEANUP-PARTICIPANT PARTICIPANT-B T=
   TEST-STATE DECLARATION-TRANSACTION:POISONED? TTRUE
   RUN-BODY-CATCH DECLARATION-TRANSACTION:E-TRANSACTION-POISONED T=
   ASSERT-IDLE ;

: TEST-FINALIZE-CLEANUP ( -- )
   RESET-CONTROLS RESET-TRACES RESET-DIAGNOSTIC
   -1 TRACE-ON !
   GENERATED-DECL:PHASE-FINALIZE FAIL-PHASE !
   PARTICIPANT-B FAIL-PARTICIPANT !
   RUN-BODY-CATCH E-INJECT T=
   FINALIZE-TRACE @ 321 T=
   DIAGNOSTIC-COUNT @ 1 T=
   DIAGNOSTIC-PRIMARY @ 0 T=
   DIAGNOSTIC-CLEANUP @ E-INJECT T=
   TEST-STATE DECLARATION-TRANSACTION:LAST-CLEANUP-PARTICIPANT PARTICIPANT-B T=
   TEST-STATE DECLARATION-TRANSACTION:POISONED? TTRUE
   RUN-BODY-CATCH DECLARATION-TRANSACTION:E-TRANSACTION-POISONED T=
   ASSERT-IDLE ;

: TEST-CALLBACK-DEPTH ( -- )
   INIT-TEST-COORDINATOR
   REGISTER-CORRUPT
   TEST-STATE DECLARATION-TRANSACTION:SEAL
   RUN-BODY-CATCH DECLARATION-TRANSACTION:E-PARTICIPANT-DEPTH T=
   TEST-STATE DECLARATION-TRANSACTION:LAST-FAILURE-PHASE GENERATED-DECL:PHASE-SNAPSHOT T=
   TEST-STATE DECLARATION-TRANSACTION:LAST-FAILURE-PARTICIPANT PARTICIPANT-CORRUPT T=
   TEST-STATE DECLARATION-TRANSACTION:POISONED? TTRUE
   RUN-BODY-CATCH DECLARATION-TRANSACTION:E-TRANSACTION-POISONED T=
   ASSERT-IDLE ;

: TEST-NESTING-GROWTH ( -- )
   RESET-CONTROLS RESET-TRACES
   12 RUN-NESTED
   NESTING-BODIES @ 13 T=
   ASSERT-IDLE ;

: EVALUATE-INNER-DECLARATION ( -- )
   s" STRUCTURE gdnested 0 FIELD x n ;STRUCTURE" INCLUDE-EVALUATE ;

: OUTER-NESTED-BODY ( -- )
   EVALUATE-INNER-DECLARATION
   DECL-EVENT:COUNT INNER-EVENT-N !
   TYPE-FIELD:COUNT INNER-FIELD-N ! ;

: OUTER-NESTED-FAIL-BODY ( -- )
   OUTER-NESTED-BODY
   E-BODY throw ;

: RUN-OUTER-NESTED-FAIL-BODY ( -- )
   [: OUTER-NESTED-FAIL-BODY ;] GENERATED-DECL:RUN ;

: RUN-OUTER-NESTED-FAIL ( -- n )
   [: RUN-OUTER-NESTED-FAIL-BODY ;] catch ;

: TEST-NESTED-DECLARATION-ROLLBACK ( -- )
   RECORD-BASELINE RECORD-OWNER-DEPTHS
   RUN-OUTER-NESTED-FAIL E-BODY T=
   INNER-EVENT-N @ EVENT-N0 @ T=
   INNER-FIELD-N @ FIELD-N0 @ T=
   ASSERT-UNCHANGED
   ASSERT-OWNER-DEPTHS
   s" GDNESTED:MAKE" WORD-ABSENT? TTRUE

   [: OUTER-NESTED-BODY ;] GENERATED-DECL:RUN
   INNER-EVENT-N @ EVENT-N0 @ T=
   INNER-FIELD-N @ FIELD-N0 @ T=
   DECL-EVENT:COUNT EVENT-N0 @ > TTRUE
   TYPE-FIELD:COUNT FIELD-N0 @ > TTRUE
   s" GDNESTED-ROUNDTRIP ( n -- n ) GDNESTED:MAKE GDNESTED:UNMAKE"
      CHECK-QUIET-CANDIDATE! 0 <> TTRUE
   ASSERT-PRODUCTION-IDLE ;

: TEST-GENERATOR-ROLLBACK ( -- )
   RESET-CONTROLS RESET-TRACES RESET-DIAGNOSTIC
   RECORD-BASELINE RECORD-OWNER-DEPTHS
   INSTALL-SECOND-WORD-FAILURE
   s" PRODUCT gdtx 0 FIELD x n ;PRODUCT" EVALUATE-CATCH
      E-INJECT T=
   RESTORE-GENERATED-EVALUATOR
   GENERATED-N @ 2 T=
   ASSERT-UNCHANGED
   ASSERT-OWNER-DEPTHS
   s" GDTX:MAKE" WORD-ABSENT? TTRUE
   s" GDTX-LEAK ( n -- gdtx ) GDTX:MAKE"
      CHECK-QUIET-CANDIDATE! 0 T=
   s" package gdtx ;package" EVALUATE-CATCH 0 T=
   ASSERT-PRODUCTION-IDLE ;

: TEST-SUCCESS-PUBLICATION ( -- )
   RESET-CONTROLS RESET-TRACES RESET-DIAGNOSTIC
   prot-wid-room PROTECTION-ROOM-N0 !
   s" PRODUCT gdok 0 FIELD x n ;PRODUCT" EVALUATE-CATCH 0 T=
   prot-wid-room PROTECTION-ROOM-N0 @ 1 - T=
   s" GDOK-USE ( n -- gdok ) GDOK:MAKE"
      CHECK-QUIET-CANDIDATE! 0 <> TTRUE
   s" package gdok ;package" EVALUATE-CATCH 7111 T=
   ASSERT-PRODUCTION-IDLE ;

public

: RUN ( -- )
   T-RESET
   RESET-CONTROLS
   INIT-TEST-COORDINATOR
   TEST-REGISTRATION
   TEST-PHASE-ORDER
   TEST-ACTIVE-REGISTRATION
   TEST-PARTIAL-SNAPSHOT
   TEST-PREPARE-FAILURE
   TEST-COMMIT-FAILURE
   TEST-NESTING-GROWTH
   TEST-ROLLBACK-CLEANUP
   INIT-TEST-COORDINATOR
   REGISTER-TEST-PARTICIPANTS
   TEST-FINALIZE-CLEANUP
   TEST-CALLBACK-DEPTH
   TEST-NESTED-DECLARATION-ROLLBACK
   TEST-GENERATOR-ROLLBACK
   TEST-SUCCESS-PUBLICATION
   RESTORE-GENERATED-EVALUATOR
   T-REPORT ;

;package

GENERATED-DECLARATION-TXN-TEST:RUN
