require lib/test.f
require lib/image-lifecycle.f

package IMAGE-LIFECYCLE-TEST
private

variable VALUE
variable ATTEMPTS

: FIRST ( -- ) VALUE @ 10 * 1+ VALUE ! ;
: SECOND ( -- ) VALUE @ 10 * 2 + VALUE ! ;
: BUMP ( -- ) 1 VALUE +! ;


: RETRY ( -- )
   1 ATTEMPTS +!
   ATTEMPTS @ 1 = if 73 throw then
   BUMP ;


: REGISTER-DURING-CLEANUP ( -- )
   [: SECOND ;] IMAGE-LIFECYCLE:REGISTER
   FIRST ;


: REGISTER-ORDER ( -- )
   [: FIRST ;] IMAGE-LIFECYCLE:REGISTER
   [: SECOND ;] IMAGE-LIFECYCLE:REGISTER ;


: REGISTER-MANY ( -- )
   2048 0 ?do [: BUMP ;] IMAGE-LIFECYCLE:REGISTER loop ;


: RUN ( -- )
   T-RESET
   0 VALUE ! REGISTER-ORDER IMAGE-LIFECYCLE:PREPARE
   VALUE @ 21 T=
   IMAGE-LIFECYCLE:PREPARE VALUE @ 21 T=
   0 VALUE ! REGISTER-MANY IMAGE-LIFECYCLE:PREPARE
   VALUE @ 2048 T=
   REGISTER-ORDER IMAGE-LIFECYCLE:PREPARE
   VALUE @ 204821 T=
   0 VALUE ! 0 ATTEMPTS !
   [: RETRY ;] IMAGE-LIFECYCLE:REGISTER
   [: IMAGE-LIFECYCLE:PREPARE ;] catch 73 T=
   ATTEMPTS @ 1 T= VALUE @ 0 T=
   IMAGE-LIFECYCLE:PREPARE
   ATTEMPTS @ 2 T= VALUE @ 1 T=
   0 VALUE !
   [: REGISTER-DURING-CLEANUP ;] IMAGE-LIFECYCLE:REGISTER
   IMAGE-LIFECYCLE:PREPARE VALUE @ 12 T=
   T-REPORT ;

RUN
;package
