require lib/test.f
require lib/image-lifecycle.f

package IMAGE-LIFECYCLE-TEST
private

variable VALUE
variable ATTEMPTS

: FIRST ( -- ) VALUE @ 10 * 1+ VALUE ! ;
: SECOND ( -- ) VALUE @ 10 * 2 + VALUE ! ;
: BUMP ( -- ) 1 VALUE +! ;


: RETRY ( -- )
   1 ATTEMPTS +!
   ATTEMPTS @ 1 = if 73 throw then
   BUMP ;


: REGISTER-DURING-CLEANUP ( -- )
   [: SECOND ;] IMAGE-LIFECYCLE:REGISTER
   FIRST ;


: REGISTER-ORDER ( -- )
   [: FIRST ;] IMAGE-LIFECYCLE:REGISTER
   [: SECOND ;] IMAGE-LIFECYCLE:REGISTER ;


: REGISTER-MANY ( -- )
   2048 0 ?do [: BUMP ;] IMAGE-LIFECYCLE:REGISTER loop ;

: REGISTER-ONE-PERSISTENT ( -- )
   [: BUMP ;] IMAGE-LIFECYCLE:REGISTER-PERSISTENT ;

: PERSISTENT-HOOKS ( -- )
   0 VALUE ! 0 ATTEMPTS !
   [: FIRST ;] IMAGE-LIFECYCLE:REGISTER-PERSISTENT
   [: SECOND ;] IMAGE-LIFECYCLE:REGISTER-PERSISTENT
   IMAGE-LIFECYCLE:COUNT 2 T=
   IMAGE-LIFECYCLE:PREPARE VALUE @ 21 T=
   IMAGE-LIFECYCLE:PREPARE VALUE @ 2121 T=
   IMAGE-LIFECYCLE:COUNT 2 T=
   0 VALUE !
   [: BUMP ;] IMAGE-LIFECYCLE:REGISTER
   IMAGE-LIFECYCLE:PREPARE VALUE @ 121 T=
   IMAGE-LIFECYCLE:COUNT 2 T=
   0 VALUE !
   [: RETRY ;] IMAGE-LIFECYCLE:REGISTER-PERSISTENT
   [: IMAGE-LIFECYCLE:PREPARE ;] catch 73 T=
   IMAGE-LIFECYCLE:COUNT 3 T=
   IMAGE-LIFECYCLE:PREPARE VALUE @ 121 T=
   ATTEMPTS @ 2 T=
   61 0 ?do REGISTER-ONE-PERSISTENT loop
   [: REGISTER-ONE-PERSISTENT ;] E-LAYOUT-BOUNDS TTHROWSQ
   IMAGE-LIFECYCLE:COUNT 64 T= ;


: RUN ( -- )
   T-RESET
   0 VALUE ! REGISTER-ORDER IMAGE-LIFECYCLE:PREPARE
   VALUE @ 21 T=
   IMAGE-LIFECYCLE:PREPARE VALUE @ 21 T=
   0 VALUE ! REGISTER-MANY IMAGE-LIFECYCLE:PREPARE
   VALUE @ 2048 T=
   REGISTER-ORDER IMAGE-LIFECYCLE:PREPARE
   VALUE @ 204821 T=
   0 VALUE ! 0 ATTEMPTS !
   [: RETRY ;] IMAGE-LIFECYCLE:REGISTER
   [: IMAGE-LIFECYCLE:PREPARE ;] catch 73 T=
   ATTEMPTS @ 1 T= VALUE @ 0 T=
   IMAGE-LIFECYCLE:PREPARE
   ATTEMPTS @ 2 T= VALUE @ 1 T=
   0 VALUE !
   [: REGISTER-DURING-CLEANUP ;] IMAGE-LIFECYCLE:REGISTER
   IMAGE-LIFECYCLE:PREPARE VALUE @ 12 T=
   IMAGE-LIFECYCLE:COUNT 0 T=
   0 VALUE ! 0 ATTEMPTS !
   [: FIRST ;] IMAGE-LIFECYCLE:REGISTER
   IMAGE-LIFECYCLE:COUNT 1 T=
   [: SECOND ;] IMAGE-LIFECYCLE:REGISTER
   IMAGE-LIFECYCLE:COUNT 2 T=
   [: RETRY ;] IMAGE-LIFECYCLE:REGISTER
   IMAGE-LIFECYCLE:COUNT 3 T=
   [: IMAGE-LIFECYCLE:PREPARE ;] catch 73 T=
   IMAGE-LIFECYCLE:COUNT 3 T=
   IMAGE-LIFECYCLE:PREPARE
   IMAGE-LIFECYCLE:COUNT 0 T=
   VALUE @ 121 T= ATTEMPTS @ 2 T=
   PERSISTENT-HOOKS
   T-REPORT ;

RUN
;package
