\ run-budget-cal-test.f - focused tests for calibration-derived gate budgets.
\ Run: bin/hb --load lib/test.f test/run-lib.f test/run-budget-cal-test.f

require lib/test.f
require test/run-lib.f

package TRBC

: PROBE-MEASURES ( -- )
   TR-CALIBRATE
   TR-CAL-MEASURED-MS @ 0 > TTRUE ;

: MACOS! ( n -- )
   TR-PROFILE-MACOS-ARM64-10X2 TR-PROFILE-ID !
   TR-CAL-MEASURED-MS ! ;

: NOMINAL-KEEPS-BUDGET ( -- )
   TR-CAL-REF-MACOS-MS MACOS!
   TR-CAL-PCT 100 T=
   40000 TR-CAL-SCALED 40000 T= ;

: SLOW-HOST-SCALES ( -- )
   TR-CAL-REF-MACOS-MS 2 * MACOS!
   TR-CAL-PCT 200 T=
   40000 TR-CAL-SCALED 80000 T=
   45000 TR-CAL-SCALED 90000 T= ;

: FAST-HOST-CLAMPS-LOW ( -- )
   TR-CAL-REF-MACOS-MS 2 / MACOS!
   TR-CAL-PCT 100 T=
   40000 TR-CAL-SCALED 40000 T= ;

: THRASHING-CLAMPS-HIGH ( -- )
   TR-CAL-REF-MACOS-MS 10 * MACOS!
   TR-CAL-PCT 300 T=
   40000 TR-CAL-SCALED 120000 T= ;

: UNCALIBRATED-PROFILE-KEEPS-TABLE ( -- )
   TR-PROFILE-JETSON-ORIN-CLOCKS-4X2 TR-PROFILE-ID !
   TR-CAL-REF-MACOS-MS 10 * TR-CAL-MEASURED-MS !
   TR-CAL-PCT 100 T=
   100000 TR-CAL-SCALED 100000 T= ;

: UNMEASURED-KEEPS-TABLE ( -- )
   0 MACOS!
   TR-CAL-PCT 100 T= ;

: MAIN ( -- )
   T-RESET
   PROBE-MEASURES
   NOMINAL-KEEPS-BUDGET
   SLOW-HOST-SCALES
   FAST-HOST-CLAMPS-LOW
   THRASHING-CLAMPS-HIGH
   UNCALIBRATED-PROFILE-KEEPS-TABLE
   UNMEASURED-KEEPS-TABLE
   T-REPORT ;

MAIN

end-package
