\ run-budget-cal-test.f - focused tests for calibration-derived gate budgets.
\ Run: bin/hb --load lib/test.f test/run-lib.f test/run-budget-cal-test.f

require lib/test.f
require test/run-lib.f

package TRBC

12345 constant USER-BUDGET-MS
23456 constant USER-WALL-MS

: PROBE-MEASURES ( -- )
   TR-CALIBRATE
   TR-CAL-MEASURED-MS @ 0 > TTRUE ;

: MACOS! ( n -- )
   TR-PROFILE-MACOS-ARM64-10X2 TR-PROFILE-ID !
   TR-CAL-MEASURED-MS ! ;

: NOMINAL-KEEPS-BUDGET ( -- )
   TR-CAL-REF-MACOS-MS MACOS!
   TR-CAL-PCT 100 T=
   40000 TR-CAL-SCALED 40000 T= ;

: SLOW-HOST-SCALES ( -- )
   TR-CAL-REF-MACOS-MS 2 * MACOS!
   TR-CAL-PCT 200 T=
   40000 TR-CAL-SCALED 80000 T=
   45000 TR-CAL-SCALED 90000 T= ;

: FAST-HOST-CLAMPS-LOW ( -- )
   TR-CAL-REF-MACOS-MS 2 / MACOS!
   TR-CAL-PCT 100 T=
   40000 TR-CAL-SCALED 40000 T= ;

: THRASHING-CLAMPS-HIGH ( -- )
   TR-CAL-REF-MACOS-MS 10 * MACOS!
   TR-CAL-PCT 300 T=
   40000 TR-CAL-SCALED 120000 T= ;

: UNCALIBRATED-PROFILE-KEEPS-TABLE ( -- )
   TR-PROFILE-JETSON-ORIN-CLOCKS-4X2 TR-PROFILE-ID !
   TR-CAL-REF-MACOS-MS 10 * TR-CAL-MEASURED-MS !
   TR-CAL-PCT 100 T=
   100000 TR-CAL-SCALED 100000 T= ;

: UNMEASURED-KEEPS-TABLE ( -- )
   0 MACOS!
   TR-CAL-PCT 100 T= ;

: MACOS-POLICY ( -- )
   TR-CAL-REF-MACOS-MS MACOS!
   0 TR-BUDGET-USER !
   0 TR-WALL-BUDGET-USER !
   TR-PROFILE-MACOS-ARM64-10X2 TR-PROFILE-APPLY
   TR-BUDGET @ RUN-BUDGET:MACOS-MS T=
   TR-WALL-BUDGET @ RUN-BUDGET:MACOS-WALL-MS T=
   -1 TR-COLD-CACHE !
   TR-COLD-BUDGETS
   TR-BUDGET @ RUN-BUDGET:MACOS-MS T=
   TR-WALL-BUDGET @ RUN-BUDGET:MACOS-WALL-MS T= ;

: MACOS-SLOW-POLICY ( -- )
   TR-CAL-REF-MACOS-MS 2 * MACOS!
   0 TR-BUDGET-USER !
   0 TR-WALL-BUDGET-USER !
   TR-PROFILE-MACOS-ARM64-10X2 TR-PROFILE-APPLY
   TR-BUDGET @ RUN-BUDGET:MACOS-MS 2 * T=
   TR-WALL-BUDGET @ RUN-BUDGET:MACOS-WALL-MS 2 * T=
   -1 TR-COLD-CACHE !
   TR-COLD-BUDGETS
   TR-BUDGET @ RUN-BUDGET:MACOS-MS 2 * T=
   TR-WALL-BUDGET @ RUN-BUDGET:MACOS-WALL-MS 2 * T= ;

: OVERRIDE-BEFORE-PROFILE ( -- )
   TR-CAL-REF-MACOS-MS MACOS!
   USER-BUDGET-MS TR-BUDGET !
   USER-WALL-MS TR-WALL-BUDGET !
   -1 TR-BUDGET-USER !
   -1 TR-WALL-BUDGET-USER !
   TR-PROFILE-MACOS-ARM64-10X2 TR-PROFILE-APPLY
   -1 TR-COLD-CACHE !
   TR-COLD-BUDGETS
   TR-BUDGET @ USER-BUDGET-MS T=
   TR-WALL-BUDGET @ USER-WALL-MS T= ;

: OVERRIDE-AFTER-PROFILE ( -- )
   TR-CAL-REF-MACOS-MS MACOS!
   0 TR-BUDGET-USER !
   0 TR-WALL-BUDGET-USER !
   TR-PROFILE-MACOS-ARM64-10X2 TR-PROFILE-APPLY
   USER-BUDGET-MS TR-BUDGET !
   USER-WALL-MS TR-WALL-BUDGET !
   -1 TR-BUDGET-USER !
   -1 TR-WALL-BUDGET-USER !
   -1 TR-COLD-CACHE !
   TR-COLD-BUDGETS
   TR-BUDGET @ USER-BUDGET-MS T=
   TR-WALL-BUDGET @ USER-WALL-MS T= ;

: SLOW-OVERRIDES-UNSCALED ( -- )
   TR-CAL-REF-MACOS-MS 2 * MACOS!
   USER-BUDGET-MS TR-BUDGET !
   USER-WALL-MS TR-WALL-BUDGET !
   -1 TR-BUDGET-USER !
   -1 TR-WALL-BUDGET-USER !
   TR-PROFILE-MACOS-ARM64-10X2 TR-PROFILE-APPLY
   -1 TR-COLD-CACHE !
   TR-COLD-BUDGETS
   TR-BUDGET @ USER-BUDGET-MS T=
   TR-WALL-BUDGET @ USER-WALL-MS T= ;

\ HB_LOAD_PCT export text: the clamp guarantees 100..300, so the exported env
\ value is always exactly three digits - the worker-side parser relies on it.
: PCT-TEXT-NOMINAL ( -- )
   TR-CAL-REF-MACOS-MS MACOS!
   TR-CAL-PCT TR-PCT$ s" 100" T$= ;

: PCT-TEXT-SCALED ( -- )
   TR-CAL-REF-MACOS-MS 2 * MACOS!
   TR-CAL-PCT TR-PCT$ s" 200" T$= ;

: PCT-TEXT-CLAMPED ( -- )
   TR-CAL-REF-MACOS-MS 10 * MACOS!
   TR-CAL-PCT TR-PCT$ s" 300" T$= ;

\ The export floors the calibration at the gate's pool pressure: any nested
\ pool budgets for the clamp-max worst case (self-contention plus the merge
\ practice of overlapping gates on one box - the 200 floor was measured
\ marginal), while nested=1 keeps the measured cal-factor alone.
: EXPORT-FLOORS-AT-PRESSURE ( -- )
   TR-CAL-REF-MACOS-MS MACOS!
   2 TR-NESTED-POOL !
   TR-LOAD-PCT-EXPORT 300 T= ;

: EXPORT-KEEPS-HEAVY-CAL ( -- )
   TR-CAL-REF-MACOS-MS 2 * MACOS!
   1 TR-NESTED-POOL !
   TR-LOAD-PCT-EXPORT 200 T= ;

: EXPORT-NO-NEST-NO-FLOOR ( -- )
   TR-CAL-REF-MACOS-MS MACOS!
   1 TR-NESTED-POOL !
   TR-LOAD-PCT-EXPORT 100 T= ;

: MAIN ( -- )
   T-RESET
   PROBE-MEASURES
   NOMINAL-KEEPS-BUDGET
   SLOW-HOST-SCALES
   FAST-HOST-CLAMPS-LOW
   THRASHING-CLAMPS-HIGH
   UNCALIBRATED-PROFILE-KEEPS-TABLE
   UNMEASURED-KEEPS-TABLE
   MACOS-POLICY
   MACOS-SLOW-POLICY
   OVERRIDE-BEFORE-PROFILE
   OVERRIDE-AFTER-PROFILE
   SLOW-OVERRIDES-UNSCALED
   PCT-TEXT-NOMINAL
   PCT-TEXT-SCALED
   PCT-TEXT-CLAMPED
   EXPORT-FLOORS-AT-PRESSURE
   EXPORT-KEEPS-HEAVY-CAL
   EXPORT-NO-NEST-NO-FLOOR
   T-REPORT ;

MAIN

;package
