\ type-field-suite.f - shared field arena behavior and type-safety.
\ Run by the native engine gate on both the candidate and bin/hb.

require lib/test/assert.f
require test/checker-assert.f

package TYPE-FIELD-TEST
public

PRODUCT field-parse-owner 0 FIELD legacy n ;PRODUCT
PRODUCT field-owner 0 FIELD legacy n ;PRODUCT
PRODUCT field-bad-owner 0 FIELD legacy n ;PRODUCT
PRODUCT field-reuse-owner 0 FIELD legacy n ;PRODUCT
PRODUCT field-grow-owner 0 FIELD legacy n ;PRODUCT
PRODUCT field-nest-owner 0 FIELD legacy n ;PRODUCT

SUMTYPE field-enum 0
   VARIANT payload n ;VARIANT
;SUMTYPE

ENUM field-color red blue ;ENUM

private

PRODUCT field-private-owner 0 FIELD legacy n ;PRODUCT

variable TFF-BASE
create TFF-NAME 64 allot

TRUSTED: TFF-CHECKER-SNAPSHOT-PREPARE ( -- ) CHECKER-SNAPSHOT-PREPARE ;

: TFF-PARSE-OWNER ( -- TYPE-FIELD:family-id )
   s" field-parse-owner" TYPE-FIELD:FAMILY ;
: TFF-OWNER ( -- TYPE-FIELD:family-id )
   s" field-owner" TYPE-FIELD:FAMILY ;
: TFF-BAD-OWNER ( -- TYPE-FIELD:family-id )
   s" field-bad-owner" TYPE-FIELD:FAMILY ;
: TFF-REUSE-OWNER ( -- TYPE-FIELD:family-id )
   s" field-reuse-owner" TYPE-FIELD:FAMILY ;
: TFF-GROW-OWNER ( -- TYPE-FIELD:family-id )
   s" field-grow-owner" TYPE-FIELD:FAMILY ;
: TFF-NEST-OWNER ( -- TYPE-FIELD:family-id )
   s" field-nest-owner" TYPE-FIELD:FAMILY ;
: TFF-ENUM-OWNER ( -- TYPE-FIELD:family-id )
   s" field-enum" TYPE-FIELD:FAMILY ;
: TFF-PRIVATE-OWNER ( -- TYPE-FIELD:family-id )
   s" field-private-owner" TYPE-FIELD:FAMILY ;
: TFF-COLOR-OWNER ( -- TYPE-FIELD:family-id )
   s" field-color" TYPE-FIELD:FAMILY ;
: TFF-PAYLOAD ( -- TYPE-FIELD:variant-id )
   TFF-ENUM-OWNER s" payload" TYPE-FIELD:VARIANT ;
: TFF-RED ( -- TYPE-FIELD:variant-id )
   TFF-COLOR-OWNER s" red" TYPE-FIELD:VARIANT ;
: TFF-X ( -- TYPE-FIELD:field-id )
   TFF-OWNER s" x" TYPE-FIELD:FIND ;
: TFF-HIDDEN ( -- TYPE-FIELD:field-id )
   TFF-OWNER s" hidden" TYPE-FIELD:FIND ;

: TFF-SCHEMA-PUBLIC
   ( TYPE-FIELD:field-tx TYPE-FIELD:field-draft -- TYPE-FIELD:field-tx TYPE-FIELD:field-draft )
   0 TYPE-FIELD:SCHEMA-ID
   CELL TYPE-FIELD:ALIGNMENT
   TYPE-FIELD:PUBLIC-BYTE-FLAGS
   TYPE-FIELD:SCHEMA ;

: TFF-SCHEMA-PRIVATE
   ( TYPE-FIELD:field-tx TYPE-FIELD:field-draft -- TYPE-FIELD:field-tx TYPE-FIELD:field-draft )
   0 TYPE-FIELD:SCHEMA-ID
   CELL TYPE-FIELD:ALIGNMENT
   TYPE-FIELD:PRIVATE-BYTE-FLAGS
   TYPE-FIELD:SCHEMA ;

: TFF-LAYOUT
   ( TYPE-FIELD:field-tx TYPE-FIELD:field-draft n -- TYPE-FIELD:field-tx TYPE-FIELD:field-draft )
   {: slot:n :}
   slot TYPE-FIELD:SLOT-ID
   1 TYPE-FIELD:CELL-COUNT
   slot CELL * TYPE-FIELD:BYTE-OFF
   CELL TYPE-FIELD:BYTE-SIZE
   TYPE-FIELD:LAYOUT ;

: TFF-SOURCE
   ( TYPE-FIELD:field-tx TYPE-FIELD:field-draft n -- TYPE-FIELD:field-tx TYPE-FIELD:field-draft )
   {: off:n :}
   7 TYPE-FIELD:SOURCE-ID
   off TYPE-FIELD:SOURCE-OFF
   3 TYPE-FIELD:SOURCE-LEN
   TYPE-FIELD:SOURCE ;

: TFF-PUBLIC-ROW
   ( TYPE-FIELD:field-tx ptr u8 n n -- TYPE-FIELD:field-tx )
   {: a:ptr u:n slot:n :}
   a u TYPE-FIELD:START
   TFF-SCHEMA-PUBLIC
   slot TFF-LAYOUT
   slot TFF-SOURCE
   TYPE-FIELD:ADD ;

: TFF-PRIVATE-ROW
   ( TYPE-FIELD:field-tx ptr u8 n n -- TYPE-FIELD:field-tx )
   {: a:ptr u:n slot:n :}
   a u TYPE-FIELD:START
   TFF-SCHEMA-PRIVATE
   slot TFF-LAYOUT
   slot TFF-SOURCE
   TYPE-FIELD:ADD ;

: TFF-PARSE-BUILD ( -- )
   TFF-PARSE-OWNER TYPE-FIELD:OPEN
   TYPE-FIELD:PARSE-START
   TFF-SCHEMA-PUBLIC
   0 TFF-LAYOUT
   0 TFF-SOURCE
   TYPE-FIELD:ADD
   TYPE-FIELD:COMMIT ;

: TFF-BUILD-OWNER ( -- )
   TFF-OWNER TYPE-FIELD:OPEN
   s" x" 0 TFF-PUBLIC-ROW
   s" hidden" 1 TFF-PRIVATE-ROW
   TYPE-FIELD:COMMIT ;

: TFF-BUILD-VARIANT ( -- )
   TFF-ENUM-OWNER TYPE-FIELD:OPEN
   TFF-PAYLOAD s" value" TYPE-FIELD:START-VARIANT
   TFF-SCHEMA-PUBLIC
   2 TFF-LAYOUT
   20 TFF-SOURCE
   TYPE-FIELD:ADD
   TYPE-FIELD:COMMIT ;

: TFF-BUILD-ENUM ( -- )
   TFF-COLOR-OWNER TYPE-FIELD:OPEN
   TFF-RED s" code" TYPE-FIELD:START-VARIANT
   TFF-SCHEMA-PUBLIC
   3 TFF-LAYOUT
   30 TFF-SOURCE
   TYPE-FIELD:ADD
   TYPE-FIELD:COMMIT ;

: TFF-BUILD-PRIVATE-FAMILY ( -- )
   TFF-PRIVATE-OWNER TYPE-FIELD:OPEN
   s" owned" 0 TFF-PUBLIC-ROW
   TYPE-FIELD:COMMIT ;

: TFF-BAD-DUP-STAGE ( -- )
   TFF-BAD-OWNER TYPE-FIELD:OPEN
   s" dup-stage" TYPE-FIELD:START
   TFF-SCHEMA-PUBLIC
   TFF-SCHEMA-PUBLIC
   0 TFF-LAYOUT
   0 TFF-SOURCE
   TYPE-FIELD:ADD
   TYPE-FIELD:ROLLBACK ;

: TFF-BAD-LAYOUT ( -- )
   TFF-BAD-OWNER TYPE-FIELD:OPEN
   s" bad-layout" TYPE-FIELD:START
   0 TYPE-FIELD:SCHEMA-ID
   2 TYPE-FIELD:ALIGNMENT
   TYPE-FIELD:PUBLIC-BYTE-FLAGS
   TYPE-FIELD:SCHEMA
   0 TYPE-FIELD:SLOT-ID
   1 TYPE-FIELD:CELL-COUNT
   1 TYPE-FIELD:BYTE-OFF
   CELL TYPE-FIELD:BYTE-SIZE
   TYPE-FIELD:LAYOUT
   7 TYPE-FIELD:SOURCE-ID
   0 TYPE-FIELD:SOURCE-OFF
   1 TYPE-FIELD:SOURCE-LEN
   TYPE-FIELD:SOURCE
   TYPE-FIELD:ADD
   TYPE-FIELD:ROLLBACK ;

: TFF-BAD-DUP ( -- )
   TFF-OWNER TYPE-FIELD:OPEN
   s" x" 2 TFF-PUBLIC-ROW
   TYPE-FIELD:ROLLBACK ;

: TFF-BAD-RESERVED ( -- )
   TFF-BAD-OWNER TYPE-FIELD:OPEN
   s" make" 0 TFF-PUBLIC-ROW
   TYPE-FIELD:ROLLBACK ;

: TFF-BAD-LIFO ( -- )
   TFF-NEST-OWNER TYPE-FIELD:OPEN
   TFF-NEST-OWNER TYPE-FIELD:OPEN
   swap TYPE-FIELD:COMMIT
   TYPE-FIELD:ROLLBACK ;

: TFF-ROLLBACK-REUSE ( -- )
   TFF-REUSE-OWNER TYPE-FIELD:OPEN
   s" reuse" 0 TFF-PUBLIC-ROW
   TYPE-FIELD:ROLLBACK ;

: TFF-COMMIT-REUSE ( -- )
   TFF-REUSE-OWNER TYPE-FIELD:OPEN
   s" reuse" 0 TFF-PUBLIC-ROW
   TYPE-FIELD:COMMIT ;

: TFF-FINISH
   ( TYPE-FIELD:field-tx TYPE-FIELD:field-draft n -- )
   {: slot:n :}
   TFF-SCHEMA-PUBLIC
   slot TFF-LAYOUT
   slot TFF-SOURCE
   TYPE-FIELD:ADD
   TYPE-FIELD:COMMIT ;

: TFF-GROW ( -- )
   TFF-GROW-OWNER TYPE-FIELD:OPEN
   s" alpha-long" TYPE-FIELD:START
   TFF-GROW-OWNER TYPE-FIELD:OPEN
   s" bravo-long" TYPE-FIELD:START
   TFF-GROW-OWNER TYPE-FIELD:OPEN
   s" charlie-long" TYPE-FIELD:START
   TFF-GROW-OWNER TYPE-FIELD:OPEN
   s" delta-long" TYPE-FIELD:START
   TFF-GROW-OWNER TYPE-FIELD:OPEN
   s" echo-long" TYPE-FIELD:START
   4 TFF-FINISH
   3 TFF-FINISH
   2 TFF-FINISH
   1 TFF-FINISH
   0 TFF-FINISH
   TFF-GROW-OWNER TYPE-FIELD:OPEN
   s" foxtrot-long" 5 TFF-PUBLIC-ROW
   TYPE-FIELD:COMMIT ;

: TFF-RANGE-FAIL ( -- )
   TFF-PARSE-OWNER TYPE-FIELD:OPEN
   s" late" 1 TFF-PUBLIC-ROW
   TYPE-FIELD:ROLLBACK ;

: TFF-NAME-SMALL ( -- )
   TFF-X TFF-NAME 0 TYPE-FIELD:BYTE-SIZE TYPE-FIELD:NAME drop ;

: TFF-FIND-MISSING ( -- )
   TFF-OWNER s" missing" TYPE-FIELD:FIND drop ;

: TFF-FIND-ROLLED-BACK ( -- )
   TFF-REUSE-OWNER s" reuse" TYPE-FIELD:FIND drop ;

: TFF-EACH+ ( n TYPE-FIELD:field-id -- n ) drop 1+ ;

: TFF-ASSERT-X ( -- )
   TFF-X
   dup TYPE-FIELD:FAMILY@ TFF-OWNER TYPE-FIELD:FAMILY= TTRUE
   dup TYPE-FIELD:VARIANT? TFALSE
   dup TYPE-FIELD:SCHEMA@ 0 TYPE-FIELD:SCHEMA-ID TYPE-FIELD:SCHEMA= TTRUE
   dup TYPE-FIELD:SLOT@ 0 TYPE-FIELD:SLOT-ID TYPE-FIELD:SLOT= TTRUE
   dup TYPE-FIELD:CELLS@ 1 TYPE-FIELD:CELL-COUNT TYPE-FIELD:CELL-COUNT= TTRUE
   dup TYPE-FIELD:BYTE-OFF@ 0 TYPE-FIELD:BYTE-OFF TYPE-FIELD:BYTE-OFF= TTRUE
   dup TYPE-FIELD:BYTE-SIZE@ CELL TYPE-FIELD:BYTE-SIZE TYPE-FIELD:BYTE-SIZE= TTRUE
   dup TYPE-FIELD:ALIGN@ CELL TYPE-FIELD:ALIGNMENT TYPE-FIELD:ALIGNMENT= TTRUE
   dup TYPE-FIELD:FLAGS@ TYPE-FIELD:PUBLIC-BYTE-FLAGS TYPE-FIELD:FLAGS= TTRUE
   dup TYPE-FIELD:VIS@ TYPE-FIELD:PUBLIC-VIS TYPE-FIELD:VISIBILITY= TTRUE
   dup TFF-NAME 64 TYPE-FIELD:BYTE-SIZE TYPE-FIELD:NAME
      1 TYPE-FIELD:BYTE-SIZE TYPE-FIELD:BYTE-SIZE= TTRUE
   TFF-NAME 1 s" x" T$=
   TYPE-FIELD:SOURCE@
   3 TYPE-FIELD:SOURCE-LEN TYPE-FIELD:SOURCE-LEN= TTRUE
   0 TYPE-FIELD:SOURCE-OFF TYPE-FIELD:SOURCE-OFF= TTRUE
   7 TYPE-FIELD:SOURCE-ID TYPE-FIELD:SOURCE-ID= TTRUE ;

: TFF-ASSERT-VARIANT ( -- )
   TFF-ENUM-OWNER TFF-PAYLOAD s" value" TYPE-FIELD:FIND-VARIANT
   dup TYPE-FIELD:FAMILY@ TFF-ENUM-OWNER TYPE-FIELD:FAMILY= TTRUE
   dup TYPE-FIELD:VARIANT? TTRUE
   dup TYPE-FIELD:VARIANT@ TFF-PAYLOAD TYPE-FIELD:VARIANT= TTRUE
   TYPE-FIELD:SLOT@ 2 TYPE-FIELD:SLOT-ID TYPE-FIELD:SLOT= TTRUE ;

: TFF-ASSERT-ENUM ( -- )
   TFF-COLOR-OWNER TFF-RED s" code" TYPE-FIELD:FIND-VARIANT
   dup TYPE-FIELD:FAMILY@ TFF-COLOR-OWNER TYPE-FIELD:FAMILY= TTRUE
   dup TYPE-FIELD:VARIANT@ TFF-RED TYPE-FIELD:VARIANT= TTRUE
   TYPE-FIELD:SLOT@ 3 TYPE-FIELD:SLOT-ID TYPE-FIELD:SLOT= TTRUE ;

: TFF-ASSERT-PARSE ( -- )
   TFF-PARSE-OWNER s" parser-token" TYPE-FIELD:FIND
   TFF-NAME 64 TYPE-FIELD:BYTE-SIZE TYPE-FIELD:NAME
      12 TYPE-FIELD:BYTE-SIZE TYPE-FIELD:BYTE-SIZE= TTRUE
   TFF-NAME 12 s" parser-token" T$= ;

: TFF-ASSERT-ROLES ( -- )
   s" TFR-BAD-FAMILY-VARIANT ( TYPE-FIELD:family-id TYPE-FIELD:variant-id -- TYPE-FIELD:family-id TYPE-FIELD:variant-id ) swap"
      CHECK-QUIET-CANDIDATE! 0 T=
   s" TFR-BAD-SCHEMA-SLOT ( TYPE-FIELD:schema-id TYPE-FIELD:slot -- TYPE-FIELD:schema-id TYPE-FIELD:slot ) swap"
      CHECK-QUIET-CANDIDATE! 0 T=
   s" TFR-BAD-SLOT ( TYPE-FIELD:slot TYPE-FIELD:cell-count -- TYPE-FIELD:slot TYPE-FIELD:cell-count ) swap"
      CHECK-QUIET-CANDIDATE! 0 T=
   s" TFR-BAD-BYTE ( TYPE-FIELD:byte-off TYPE-FIELD:byte-size -- TYPE-FIELD:byte-off TYPE-FIELD:byte-size ) swap"
      CHECK-QUIET-CANDIDATE! 0 T=
   s" TFR-BAD-SOURCE-ID ( TYPE-FIELD:source-id TYPE-FIELD:source-off -- TYPE-FIELD:source-id TYPE-FIELD:source-off ) swap"
      CHECK-QUIET-CANDIDATE! 0 T=
   s" TFR-BAD-SOURCE ( TYPE-FIELD:source-off TYPE-FIELD:source-len -- TYPE-FIELD:source-off TYPE-FIELD:source-len ) swap"
      CHECK-QUIET-CANDIDATE! 0 T=
   s" TFR-BAD-ID ( n -- TYPE-FIELD:field-id )"
      CHECK-QUIET-CANDIDATE! 0 T=
   s" TFR-STALE-TX ( TYPE-FIELD:family-id -- ) TYPE-FIELD:OPEN dup TYPE-FIELD:COMMIT TYPE-FIELD:COMMIT"
      CHECK-QUIET-CANDIDATE! 0 T=
   s" TFR-INCOMPLETE ( TYPE-FIELD:family-id ptr u8 n -- ) TYPE-FIELD:OPEN -rot TYPE-FIELD:START swap TYPE-FIELD:COMMIT"
      CHECK-QUIET-CANDIDATE! 0 T=
   s" TFR-PENDING-ID ( TYPE-FIELD:field-tx TYPE-FIELD:field-draft -- TYPE-FIELD:field-tx TYPE-FIELD:field-id ) TYPE-FIELD:ADD"
      CHECK-QUIET-CANDIDATE! 0 T= ;

: TFF-PREPARE ( -- )
   TFF-BUILD-OWNER
   TFF-ASSERT-X
   TFF-HIDDEN drop
   [: TFF-NAME-SMALL ;] TYPE-FIELD:E-CAPACITY TTHROWSQ
   [: TFF-FIND-MISSING ;] TYPE-FIELD:E-ID TTHROWSQ

   [: TFF-BAD-DUP-STAGE ;] TYPE-FIELD:E-DRAFT TTHROWSQ
   [: TFF-BAD-LAYOUT ;] TYPE-FIELD:E-LAYOUT TTHROWSQ
   [: TFF-BAD-DUP ;] TYPE-FIELD:E-DUP TTHROWSQ
   [: TFF-BAD-RESERVED ;] TYPE-FIELD:E-NAME TTHROWSQ
   [: TFF-BAD-LIFO ;] TYPE-FIELD:E-TX TTHROWSQ

   TFF-ROLLBACK-REUSE
   [: TFF-FIND-ROLLED-BACK ;] TYPE-FIELD:E-ID TTHROWSQ
   TFF-COMMIT-REUSE
   TFF-REUSE-OWNER s" reuse" TYPE-FIELD:FIND drop

   TFF-BUILD-VARIANT
   TFF-ASSERT-VARIANT
   TFF-BUILD-ENUM
   TFF-ASSERT-ENUM
   TFF-BUILD-PRIVATE-FAMILY
   TFF-GROW
   [: TFF-RANGE-FAIL ;] TYPE-FIELD:E-RANGE TTHROWSQ

   0 TFF-GROW-OWNER [: TFF-EACH+ ;] TYPE-FIELD:EACH 6 T=
   TFF-COLOR-OWNER s" red" TYPE-FIELD:VARIANT drop ;

public

: HIDDEN-ID ( -- TYPE-FIELD:field-id ) TFF-HIDDEN ;

private

: TFF-SNAPSHOT-ASSERT ( -- )
   TYPE-FIELD:COUNT TYPE-FIELD:FIELD-COUNT>N TFF-BASE @ 13 + T=
   TFF-ASSERT-PARSE
   TFF-ASSERT-X
   TFF-ASSERT-VARIANT
   TFF-GROW-OWNER s" foxtrot-long" TYPE-FIELD:FIND
   TYPE-FIELD:SLOT@ 5 TYPE-FIELD:SLOT-ID TYPE-FIELD:SLOT= TTRUE
   TFF-PRIVATE-OWNER s" owned" TYPE-FIELD:FIND drop ;

T-RESET
TYPE-FIELD:COUNT TYPE-FIELD:FIELD-COUNT>N TFF-BASE !
TFF-PARSE-BUILD parser-token
TFF-PREPARE
TFF-ASSERT-ROLES

;package

package TYPE-FIELD-OUTSIDER

: TFO-OWNER ( -- TYPE-FIELD:family-id )
   s" field-owner" TYPE-FIELD:FAMILY ;

: TFO-HIDDEN ( -- )
   TFO-OWNER s" hidden" TYPE-FIELD:FIND drop ;

: TFO-HIDDEN-REFLECT ( -- )
   TYPE-FIELD-TEST:HIDDEN-ID TYPE-FIELD:FAMILY@ drop ;

: TFO-PRIVATE-FAMILY ( -- )
   s" field-private-owner" TYPE-FIELD:FAMILY drop ;

: TFO-OPEN ( -- )
   TFO-OWNER TYPE-FIELD:OPEN TYPE-FIELD:ROLLBACK ;

: TFO-EACH+ ( n TYPE-FIELD:field-id -- n ) drop 1+ ;

: TFO-ASSERT-EACH ( -- )
   0 TFO-OWNER [: TFO-EACH+ ;] TYPE-FIELD:EACH 1 T= ;

TFO-OWNER s" x" TYPE-FIELD:FIND drop
' TFO-HIDDEN TYPE-FIELD:E-VISIBILITY TTHROWS
' TFO-HIDDEN-REFLECT TYPE-FIELD:E-VISIBILITY TTHROWS
' TFO-PRIVATE-FAMILY TYPE-FIELD:E-FAMILY TTHROWS
' TFO-OPEN TYPE-FIELD:E-VISIBILITY TTHROWS
TFO-ASSERT-EACH

;package

package TYPE-FIELD-TEST
private

TFF-CHECKER-SNAPSHOT-PREPARE
TFF-SNAPSHOT-ASSERT
T-REPORT

;package
