require lib/test.f
require lib/unicode.f

package ALPHABETIC-TEST

T-RESET
$41 UNICODE:ALPHABETIC? TTRUE
$451 UNICODE:ALPHABETIC? TTRUE
$5B0 UNICODE:ALPHABETIC? TTRUE
$345 UNICODE:ALPHABETIC? TTRUE
$345 UNICODE-CLASS:LETTER? TFALSE
$2160 UNICODE:ALPHABETIC? TTRUE
$2160 UNICODE-CLASS:LETTER? TFALSE
$301 UNICODE:ALPHABETIC? TFALSE
\ Not yet assigned in the pinned Unicode16 data.
$88F UNICODE:ALPHABETIC? TFALSE
$10940 UNICODE:ALPHABETIC? TFALSE
$30 UNICODE:ALPHABETIC? TFALSE
$20 UNICODE:ALPHABETIC? TFALSE
$1F600 UNICODE:ALPHABETIC? TFALSE
0 UNICODE:ALPHABETIC? TFALSE
-1 UNICODE:ALPHABETIC? TFALSE
$D800 UNICODE:ALPHABETIC? TFALSE
$DFFF UNICODE:ALPHABETIC? TFALSE
$110000 UNICODE:ALPHABETIC? TFALSE
T-REPORT

;package
