require lib/test.f
require lib/property.f
require lib/codegen.f
require lib/unicode.f
require tools/unicode/class-parse.f

package UPPERCASE-TEST
using PROP
using UNICODE-CLASS-TOOL

1024 CODEGEN:BUFFER CASE-SOURCE

: PARSER-CASE ( n -- )
   {: scalar:n :}
   CASE-SOURCE CODEGEN:RESET
   scalar CASE-SOURCE CODEGEN:APPEND-DECIMAL
   s" ;TEST CAPITAL;Lu;0;L;;;;;N;;;;;" CASE-SOURCE CODEGEN:APPEND-STRING
   CASE-SOURCE CODEGEN:CONTENTS PARSE-UNICODE
   UPPERCASE-LETTER-COUNT 1 T=
   0 UPPERCASE-LETTER-RANGE@ {: first:n last:n :}
   first last T=
   0 LETTER-RANGE@ last T= first T=
   CASE-SOURCE CODEGEN:RESET
   scalar CASE-SOURCE CODEGEN:APPEND-DECIMAL
   s" ; Other_Uppercase" CASE-SOURCE CODEGEN:APPEND-STRING
   CASE-SOURCE CODEGEN:CONTENTS PARSE-PROPERTIES
   OTHER-UPPERCASE-COUNT 1 T=
   0 OTHER-UPPERCASE-RANGE@ last T= first T=
   [: s" D800 ; Other_Uppercase" PARSE-PROPERTIES ;] E-RANGE TTHROWSQ
   OTHER-UPPERCASE-COUNT 1 T=
   0 OTHER-UPPERCASE-RANGE@ last T= first T= ;


: RANDOMIZED ( -- )
   753 2048 RUN-RESET COUNT@ 0 ?do 1000 RND% PARSER-CASE loop ;


: TEST ( -- )
   T-RESET
   $41 UNICODE:UPPERCASE? TTRUE $61 UNICODE:UPPERCASE? TFALSE
   $400 UNICODE:UPPERCASE? TTRUE $450 UNICODE:UPPERCASE? TFALSE
   $2160 UNICODE:UPPERCASE? TTRUE $2170 UNICODE:UPPERCASE? TFALSE
   $24B6 UNICODE:UPPERCASE? TTRUE $24D0 UNICODE:UPPERCASE? TFALSE
   $1F130 UNICODE:UPPERCASE? TTRUE $212A UNICODE:UPPERCASE? TTRUE
   $1C5 UNICODE:UPPERCASE? TFALSE $345 UNICODE:UPPERCASE? TFALSE
   -1 UNICODE:UPPERCASE? TFALSE $D800 UNICODE:UPPERCASE? TFALSE
   $110000 UNICODE:UPPERCASE? TFALSE
   RANDOMIZED T-REPORT ;

TEST
;using
;using
;package
