;;; Bootstrap Habu Executable Delivery
;;; Generates standalone native executables using the bootstrap compiler

(load "bootstrap/compiler.lisp")
(in-package :habu)

(defun nc-bytes-to-c-array (bytes)
  "Convert byte list to C array initializer string"
  (with-output-to-string (s)
    (let ((col 0))
      (dolist (b bytes)
        (format s "0x~2,'0X," b)
        (incf col)
        (when (= col 16)
          (format s "~%    ")
          (setf col 0))))))

(defun nc-generate-embedded-c (bytes output-name)
  "Generate C source with embedded bytecode"
  (format nil "/* Auto-generated by Habu bootstrap deliver - ~A */
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <sys/mman.h>
#include <string.h>
#include \"runtime/habu.h\"

/* Embedded ARM64 bytecode (~A bytes) */
static const unsigned char g_bytecode[] = {
    ~A
};
static const size_t g_bytecode_size = ~A;

/* Runtime function table */
void* g_runtime_table[64];

typedef int64_t (*compiled_fn_t)(void** runtime_table);

int main(int argc, char **argv) {
    (void)argc; (void)argv;

    /* Allocate executable memory */
    void *exec_mem = mmap(NULL, g_bytecode_size,
                          PROT_READ | PROT_WRITE,
                          MAP_PRIVATE | MAP_ANONYMOUS,
                          -1, 0);
    if (exec_mem == MAP_FAILED) {
        perror(\"mmap\");
        return 1;
    }

    /* Copy bytecode to executable memory */
    memcpy(exec_mem, g_bytecode, g_bytecode_size);

    /* Make memory executable */
    if (mprotect(exec_mem, g_bytecode_size, PROT_READ | PROT_EXEC) != 0) {
        perror(\"mprotect\");
        munmap(exec_mem, g_bytecode_size);
        return 1;
    }

    /* Initialize Habu runtime */
    init(1024 * 1024);

    /* Setup runtime function table */
    g_runtime_table[0] = (void*)cons;
    g_runtime_table[1] = (void*)car;
    g_runtime_table[2] = (void*)cdr;
    g_runtime_table[3] = (void*)make_closure;
    g_runtime_table[4] = (void*)closure_code;
    g_runtime_table[5] = (void*)closure_env;
    g_runtime_table[6] = exec_mem;
    g_runtime_table[7] = (void*)make_vector;
    g_runtime_table[8] = (void*)vector_set;
    g_runtime_table[9] = (void*)vector_ref;
    g_runtime_table[10] = (void*)make_string_from_vector;
    g_runtime_table[11] = (void*)make_symbol_from_string;
    g_runtime_table[12] = (void*)string_length_raw;
    g_runtime_table[13] = (void*)symbol_name;
    g_runtime_table[14] = (void*)set_car;
    g_runtime_table[15] = (void*)set_cdr;
    g_runtime_table[16] = (void*)string_ref;
    g_runtime_table[17] = (void*)values_set;
    g_runtime_table[18] = (void*)values_get;
    g_runtime_table[19] = (void*)make_hash_table;
    g_runtime_table[20] = (void*)gethash;
    g_runtime_table[21] = (void*)puthash;
    g_runtime_table[22] = (void*)remhash;
    g_runtime_table[23] = (void*)hash_table_count;
    g_runtime_table[24] = (void*)string_concat;
    g_runtime_table[25] = (void*)string_substring;
    g_runtime_table[26] = (void*)fixnum_to_string;
    g_runtime_table[27] = (void*)values_count_get;
    g_runtime_table[28] = (void*)gensym;
    g_runtime_table[29] = (void*)make_float;
    g_runtime_table[30] = (void*)float_add;
    g_runtime_table[31] = (void*)float_sub;
    g_runtime_table[32] = (void*)float_mul;
    g_runtime_table[33] = (void*)float_div;
    g_runtime_table[34] = (void*)float_lt;
    g_runtime_table[35] = (void*)float_gt;
    g_runtime_table[36] = (void*)float_le;
    g_runtime_table[37] = (void*)float_ge;
    g_runtime_table[38] = (void*)float_eq;
    g_runtime_table[39] = (void*)fixnum_to_float;
    g_runtime_table[40] = (void*)float_to_fixnum;
    g_runtime_table[41] = (void*)float_value;
    g_runtime_table[42] = (void*)open_file;
    g_runtime_table[43] = (void*)close_file;
    g_runtime_table[44] = (void*)read_line;
    g_runtime_table[45] = (void*)write_string;
    g_runtime_table[46] = (void*)read_file;
    g_runtime_table[47] = (void*)write_file;
    g_runtime_table[48] = (void*)print_value;
    g_runtime_table[49] = (void*)println_value;
    g_runtime_table[50] = (void*)get_time_ns;
    g_runtime_table[51] = (void*)system_cmd;
    g_runtime_table[52] = (void*)string_equal;
    g_runtime_table[53] = (void*)write_bytes;

    /* Execute */
    compiled_fn_t fn = (compiled_fn_t)exec_mem;
    int64_t result = fn(g_runtime_table);

    /* Print result */
    printf(\"Result: %lld\\n\", result >> 4);

    /* Clean exit */
    munmap(exec_mem, g_bytecode_size);
    return 0;
}
"
          output-name
          (length bytes)
          (nc-bytes-to-c-array bytes)
          (length bytes)))

(defun nc-deliver (source-string output-path)
  "Deliver Lisp source string as standalone native executable.
   SOURCE-STRING: Lisp source code as a string
   OUTPUT-PATH: path for output executable"
  (let* ((c-source-path (format nil "~A.c" output-path))
         (forms (nc-read-all source-string))
         (bytes (nc-compile-program forms nil)))
    (format t "Compiling...~%")
    (format t "Generated ~A bytes of ARM64 code~%" (length bytes))

    ;; Generate C source
    (let ((c-source (nc-generate-embedded-c bytes (pathname-name (pathname output-path)))))
      (with-open-file (out c-source-path :direction :output
                                         :if-exists :supersede)
        (write-string c-source out)))
    (format t "Generated ~A~%" c-source-path)

    ;; Compile with clang
    (let* ((cmd (format nil "clang -O2 -o ~A ~A runtime/gc.c runtime/io.c runtime/runtime.c runtime/region.c -I. 2>&1"
                        output-path c-source-path))
           (result (with-output-to-string (s)
                     (sb-ext:run-program "/bin/sh" (list "-c" cmd)
                                         :output s :error :output))))
      (format t "Running: ~A~%" cmd)
      (when (> (length result) 0)
        (format t "~A~%" result))

      ;; Check if output exists
      (if (probe-file output-path)
          (progn
            (format t "Created executable: ~A~%" output-path)
            ;; Clean up C source
            (delete-file c-source-path)
            output-path)
          (error "Compilation failed: ~A" result)))))

(defun nc-deliver-file (source-path output-path)
  "Deliver Lisp source file as standalone native executable.
   SOURCE-PATH: path to .lisp source file
   OUTPUT-PATH: path for output executable"
  (let ((source (with-open-file (in source-path :direction :input)
                  (let ((contents (make-string (file-length in))))
                    (read-sequence contents in)
                    contents))))
    (nc-deliver source output-path)))

;; Export
(export '(nc-deliver nc-deliver-file) :habu)
