;;;; Habu Compiler Demo
;;;; Demonstrates all implemented features

(load "compiler.lisp")
(in-package :habu-compiler)

(format t "~%")
(format t "====================================~%")
(format t "  Habu Compiler Feature Demo~%")
(format t "====================================~%")
(format t "~%")

(defun demo-expr (expr)
  "Compile and show an expression for both architectures"
  (format t "Expression: ~S~%" expr)
  (let ((x64-code (compile-expression expr :arch :x86_64))
        (arm-code (compile-expression expr :arch :arm64)))
    (format t "  x86_64: ~D bytes~%" (length x64-code))
    (format t "  ARM64:  ~D bytes~%" (length arm-code))
    (format t "~%")))

(format t "1. LITERALS~%")
(format t "===========~%")
(demo-expr 42)
(demo-expr 1000)

(format t "2. ARITHMETIC~%")
(format t "=============~%")
(demo-expr '(+ 10 20))
(demo-expr '(- 100 50))
(demo-expr '(* 6 7))
(demo-expr '(/ 100 5))
(demo-expr '(mod 17 5))

(format t "3. COMPARISONS~%")
(format t "==============~%")
(demo-expr '(< 5 10))
(demo-expr '(> 20 15))
(demo-expr '(= 42 42))
(demo-expr '(<= 10 10))
(demo-expr '(>= 15 10))

(format t "4. CONDITIONALS~%")
(format t "===============~%")
(demo-expr '(if 1 100 200))
(demo-expr '(if (< 5 10) 42 0))
(demo-expr '(if (> 20 30) 1 (+ 10 20)))

(format t "5. LET BINDINGS~%")
(format t "===============~%")
(demo-expr '(let ((x 42)) x))
(demo-expr '(let ((x 10)) (+ x 20)))
(demo-expr '(let ((x 5) (y 10)) (+ x y)))
(demo-expr '(let ((x 10)) (let ((y 20)) (+ x y))))

(format t "6. LAMBDA EXPRESSIONS~%")
(format t "=====================~%")
(demo-expr '((lambda (x) x) 42))
(demo-expr '((lambda (x) (* x 2)) 21))
(demo-expr '((lambda (x y) (+ x y)) 10 20))
(demo-expr '((lambda (a b) (+ (* a a) (* b b))) 3 4))
(demo-expr '((lambda (x) ((lambda (y) (+ x y)) 20)) 10))

(format t "7. PROGN (SEQUENCES)~%")
(format t "====================~%")
(demo-expr '(progn 1 2 3))
(demo-expr '(progn (+ 1 2) (* 3 4) (- 10 5)))
(demo-expr '((lambda (x) (progn (+ x 1) (* x 2))) 10))

(format t "8. QUOTE (LITERAL DATA)~%")
(format t "=======================~%")
(demo-expr ''42)
(demo-expr ''0)
(demo-expr '(+ '10 '20))
(demo-expr '(let ((x '5)) (+ x '10)))

(format t "9. BOOLEAN OPERATORS~%")
(format t "====================~%")
(demo-expr '(not 0))
(demo-expr '(not 1))
(demo-expr '(and 1 2 3))
(demo-expr '(or 0 0 5))
(demo-expr '(and (< 5 10) (> 20 15)))
(demo-expr '(or (< 10 5) (= 3 3)))

(format t "10. COND (MULTI-WAY CONDITIONALS)~%")
(format t "=================================~%")
(demo-expr '(cond ((< 5 3) 100) ((< 5 7) 200) (t 300)))
(demo-expr '(let ((x 5)) (cond ((< x 3) 1) ((< x 7) 2) (t 3))))
(demo-expr '(cond ((and (> 5 3) (< 5 10)) (* 2 10)) (t (+ 1 1))))

(format t "11. WHEN/UNLESS~%")
(format t "===============~%")
(demo-expr '(when (< 5 10) (* 2 21)))
(demo-expr '(unless (> 5 10) (+ 10 32)))
(demo-expr '(let ((x 5)) (when (< x 10) (+ x 1))))

(format t "12. COMPLEX EXPRESSIONS~%")
(format t "======================~%")
(demo-expr '(+ (* 3 4) (/ 20 2)))
(demo-expr '(if (< (* 2 3) (+ 5 2)) 100 200))
(demo-expr '(let ((a 3) (b 4)) (* (+ a b) 2)))
(demo-expr '(let ((x 10))
              (if (< x 20)
                  (+ x 5)
                  (* x 2))))
(demo-expr '(let ((a 5) (b 3))
              (if (> a b)
                  (- a b)
                  (- b a))))
(demo-expr '((lambda (n)
               (if (< n 2)
                   n
                   (+ n n)))
             10))

(format t "~%")
(format t "====================================~%")
(format t "  Feature Summary~%")
(format t "====================================~%")
(format t "~%")
(format t "Literals:     Fixnum integers~%")
(format t "Arithmetic:   + - * / mod~%")
(format t "Comparison:   < > = <= >=~%")
(format t "Boolean:      and, or, not (short-circuit)~%")
(format t "Control:      if, cond, when, unless, progn~%")
(format t "Variables:    let bindings~%")
(format t "Functions:    lambda expressions~%")
(format t "Quote:        Literal data (fixnums)~%")
(format t "Lists:        car, cdr (cons needs runtime)~%")
(format t "Nesting:      Arbitrary depth~%")
(format t "Targets:      x86_64, ARM64~%")
(format t "~%")
(format t "All expressions compile successfully!~%")
(format t "~%")
