;;;; Habu Compiler Demo
;;;; Demonstrates all implemented features

(load "compiler.lisp")
(in-package :habu-compiler)

(format t "~%")
(format t "====================================~%")
(format t "  Habu Compiler Feature Demo~%")
(format t "====================================~%")
(format t "~%")

(defun demo-expr (expr)
  "Compile and show an expression for both architectures"
  (format t "Expression: ~S~%" expr)
  (let ((x64-code (compile-expression expr :arch :x86_64))
        (arm-code (compile-expression expr :arch :arm64)))
    (format t "  x86_64: ~D bytes~%" (length x64-code))
    (format t "  ARM64:  ~D bytes~%" (length arm-code))
    (format t "~%")))

(format t "1. LITERALS~%")
(format t "===========~%")
(demo-expr 42)
(demo-expr 1000)

(format t "2. ARITHMETIC~%")
(format t "=============~%")
(demo-expr '(+ 10 20))
(demo-expr '(- 100 50))
(demo-expr '(* 6 7))
(demo-expr '(/ 100 5))
(demo-expr '(mod 17 5))

(format t "3. COMPARISONS~%")
(format t "==============~%")
(demo-expr '(< 5 10))
(demo-expr '(> 20 15))
(demo-expr '(= 42 42))
(demo-expr '(<= 10 10))
(demo-expr '(>= 15 10))

(format t "4. CONDITIONALS~%")
(format t "===============~%")
(demo-expr '(if 1 100 200))
(demo-expr '(if (< 5 10) 42 0))
(demo-expr '(if (> 20 30) 1 (+ 10 20)))

(format t "5. LET BINDINGS~%")
(format t "===============~%")
(demo-expr '(let ((x 42)) x))
(demo-expr '(let ((x 10)) (+ x 20)))
(demo-expr '(let ((x 5) (y 10)) (+ x y)))
(demo-expr '(let ((x 10)) (let ((y 20)) (+ x y))))

(format t "6. LAMBDA EXPRESSIONS~%")
(format t "=====================~%")
(demo-expr '((lambda (x) x) 42))
(demo-expr '((lambda (x) (* x 2)) 21))
(demo-expr '((lambda (x y) (+ x y)) 10 20))
(demo-expr '((lambda (a b) (+ (* a a) (* b b))) 3 4))
(demo-expr '((lambda (x) ((lambda (y) (+ x y)) 20)) 10))

(format t "7. PROGN (SEQUENCES)~%")
(format t "====================~%")
(demo-expr '(progn 1 2 3))
(demo-expr '(progn (+ 1 2) (* 3 4) (- 10 5)))
(demo-expr '((lambda (x) (progn (+ x 1) (* x 2))) 10))

(format t "8. QUOTE (LITERAL DATA)~%")
(format t "=======================~%")
(demo-expr ''42)
(demo-expr ''0)
(demo-expr '(+ '10 '20))
(demo-expr '(let ((x '5)) (+ x '10)))

(format t "9. BOOLEAN OPERATORS~%")
(format t "====================~%")
(demo-expr '(not 0))
(demo-expr '(not 1))
(demo-expr '(and 1 2 3))
(demo-expr '(or 0 0 5))
(demo-expr '(and (< 5 10) (> 20 15)))
(demo-expr '(or (< 10 5) (= 3 3)))

(format t "10. COND (MULTI-WAY CONDITIONALS)~%")
(format t "=================================~%")
(demo-expr '(cond ((< 5 3) 100) ((< 5 7) 200) (t 300)))
(demo-expr '(let ((x 5)) (cond ((< x 3) 1) ((< x 7) 2) (t 3))))
(demo-expr '(cond ((and (> 5 3) (< 5 10)) (* 2 10)) (t (+ 1 1))))

(format t "11. WHEN/UNLESS~%")
(format t "===============~%")
(demo-expr '(when (< 5 10) (* 2 21)))
(demo-expr '(unless (> 5 10) (+ 10 32)))
(demo-expr '(let ((x 5)) (when (< x 10) (+ x 1))))

(format t "12. CASE (PATTERN MATCHING)~%")
(format t "===========================~%")
(demo-expr '(case 2 (1 100) (2 200) (3 300)))
(demo-expr '(case 5 (1 100) (2 200) (t 999)))
(demo-expr '(let ((x 2)) (case x (1 100) (2 200) (3 300))))
(demo-expr '(case 3 ((1 2) 100) ((3 4) 200) (t 300)))

(format t "13. BITWISE OPERATORS~%")
(format t "=====================~%")
(demo-expr '(logand 15 7))
(demo-expr '(logior 8 4))
(demo-expr '(logxor 15 9))
(demo-expr '(lognot 0))
(demo-expr '(ash 5 2))
(demo-expr '(ash 20 -2))
(demo-expr '(logand (logior 8 4) 15))

(format t "14. NUMERIC OPERATORS~%")
(format t "=====================~%")
(demo-expr '(min 5 10))
(demo-expr '(max 5 10))
(demo-expr '(abs -10))
(demo-expr '(abs 10))
(demo-expr '(1+ 5))
(demo-expr '(1- 5))
(demo-expr '(max (min 10 20) (abs -15)))

(format t "15. PREDICATES~%")
(format t "==============~%")
(demo-expr '(zerop 0))
(demo-expr '(zerop 5))
(demo-expr '(plusp 5))
(demo-expr '(plusp -5))
(demo-expr '(minusp -5))
(demo-expr '(minusp 5))
(demo-expr '(evenp 4))
(demo-expr '(evenp 5))
(demo-expr '(oddp 5))
(demo-expr '(oddp 4))
(demo-expr '(if (zerop (mod 10 2)) (evenp 10) (oddp 10)))

(format t "16. COMPLEX EXPRESSIONS~%")
(format t "======================~%")
(demo-expr '(+ (* 3 4) (/ 20 2)))
(demo-expr '(if (< (* 2 3) (+ 5 2)) 100 200))
(demo-expr '(let ((a 3) (b 4)) (* (+ a b) 2)))
(demo-expr '(let ((x 10))
              (if (< x 20)
                  (+ x 5)
                  (* x 2))))
(demo-expr '(let ((a 5) (b 3))
              (if (> a b)
                  (- a b)
                  (- b a))))
(demo-expr '((lambda (n)
               (if (< n 2)
                   n
                   (+ n n)))
             10))

(format t "17. DEFUN (GLOBAL FUNCTIONS)~%")
(format t "============================~%")
(demo-expr '(defun square (x) (* x x)))
(demo-expr '(square 5))
(demo-expr '(defun add-numbers (a b) (+ a b)))
(demo-expr '(add-numbers 10 20))
(demo-expr '(defun factorial (n) (if (<= n 1) 1 (* n (factorial (- n 1))))))

(format t "18. LET* (SEQUENTIAL BINDINGS)~%")
(format t "==============================~%")
(demo-expr '(let* ((x 5) (y (+ x 1))) y))
(demo-expr '(let* ((a 1) (b (+ a 1)) (c (+ a b))) c))
(demo-expr '(let* ((x 10) (y (* x 2)) (z (+ x y))) z))

(format t "19. SETQ (VARIABLE MUTATION)~%")
(format t "============================~%")
(demo-expr '(let ((x 5)) (setq x 10) x))
(demo-expr '(let ((x 1)) (setq x (+ x 1)) x))
(demo-expr '(let ((x 0)) (setq x 5) (setq x (* x 2)) x))

(format t "20. INCF/DECF (INCREMENT/DECREMENT)~%")
(format t "====================================~%")
(demo-expr '(let ((x 5)) (incf x) x))
(demo-expr '(let ((x 10)) (incf x 3) x))
(demo-expr '(let ((x 20)) (decf x) x))
(demo-expr '(let ((x 100)) (decf x 25) x))

(format t "21. BEGIN (PROGN ALIAS)~%")
(format t "=======================~%")
(demo-expr '(begin 1 2 3))
(demo-expr '(begin (+ 1 2) (* 3 4)))

(format t "22. ADDITIONAL OPERATORS~%")
(format t "========================~%")
(demo-expr '(/= 5 10))
(demo-expr '(equal 5 5))
(demo-expr '(null 0))
(demo-expr '(identity 42))

(format t "~%")
(format t "====================================~%")
(format t "  Feature Summary~%")
(format t "====================================~%")
(format t "~%")
(format t "Literals:     Fixnum integers~%")
(format t "Arithmetic:   + - * / mod~%")
(format t "Numeric:      min, max, abs, 1+, 1-~%")
(format t "Comparison:   < > = <= >= /= equal~%")
(format t "Bitwise:      logand, logior, logxor, lognot, ash~%")
(format t "Boolean:      and, or, not (short-circuit)~%")
(format t "Predicates:   zerop, plusp, minusp, evenp, oddp, null~%")
(format t "Control:      if, cond, case, when, unless, progn, begin~%")
(format t "Variables:    let, let*, setq, incf, decf~%")
(format t "Functions:    lambda, defun~%")
(format t "Quote:        Literal data (fixnums)~%")
(format t "Lists:        car, cdr (cons needs runtime)~%")
(format t "Utility:      identity~%")
(format t "Nesting:      Arbitrary depth~%")
(format t "Targets:      x86_64, ARM64~%")
(format t "~%")
(format t "Total: 60+ operators and special forms~%")
(format t "All expressions compile successfully!~%")
(format t "~%")
