;;; Mach-O Linker for Habu Self-Hosting
;;;
;;; Buffer-based Mach-O generation - no stream I/O
;;; Pure Habu - uses only features available in bootstrap compiler
;;;
;;; Dependencies: arm64/asm.lisp (loaded via ASDF)

(in-package :habu)

;;; ============================================================
;;; Wrapper Size Constants - SINGLE SOURCE OF TRUTH
;;; ============================================================
;;; This constant MUST match the actual wrapper code generated by
;;; wrap-bytecode-with-heap-for-imports.
;;; If you change the wrapper code, update the constant here.

(defconstant +heap-wrapper-size+ 168
  "Size of heap initialization wrapper in bytes (42 instructions * 4).
   Used by wrap-bytecode-with-heap-for-imports for __DATA segment heap.")

;;; SBCL compatibility: native-write-file
#+sbcl
(defun native-write-file (path content)
  "Write string CONTENT to file PATH (SBCL version)"
  (with-open-file (stream path
                          :direction :output
                          :if-exists :supersede
                          :if-does-not-exist :create
                          :element-type '(unsigned-byte 8))
    (loop for char across content
          do (write-byte (char-code char) stream))))

;;; SBCL compatibility: native-write-executable (write + chmod + codesign)
#+sbcl
(defun native-write-executable (path content)
  "Write executable file, chmod +x, codesign (SBCL version)"
  (with-open-file (stream path
                          :direction :output
                          :if-exists :supersede
                          :if-does-not-exist :create
                          :element-type '(unsigned-byte 8))
    (loop for char across content
          do (write-byte (char-code char) stream)))
  (sb-ext:run-program "/bin/chmod" (list "+x" path)
                      :output nil :error nil :wait t)
  (sb-ext:run-program "/usr/bin/codesign" (list "-s" "-" "-f" path)
                      :output nil :error nil :wait t)
  (length content))

;;; ============================================================
;;; Mach-O Constants
;;; ============================================================

(defconstant +MH-MAGIC-64+ #xFEEDFACF)
(defconstant +CPU-TYPE-ARM64+ #x0100000C)
(defconstant +CPU-SUBTYPE-ARM64-ALL+ #x00000000)
(defconstant +MH-EXECUTE+ 2)

(defconstant +MH-NOUNDEFS+ #x00000001)
(defconstant +MH-DYLDLINK+ #x00000004)
(defconstant +MH-TWOLEVEL+ #x00000080)
(defconstant +MH-PIE+ #x00200000)

(defconstant +LC-SEGMENT-64+ #x19)
(defconstant +LC-SYMTAB+ #x02)
(defconstant +LC-DYSYMTAB+ #x0B)
(defconstant +LC-LOAD-DYLINKER+ #x0E)
(defconstant +LC-UUID+ #x1B)
(defconstant +LC-BUILD-VERSION+ #x32)
(defconstant +LC-MAIN+ #x80000028)
(defconstant +LC-LOAD-DYLIB+ #x0C)
(defconstant +LC-DYLD-CHAINED-FIXUPS+ #x80000034)
(defconstant +LC-DYLD-EXPORTS-TRIE+ #x80000033)

(defconstant +VM-PROT-READ+ #x01)
(defconstant +VM-PROT-WRITE+ #x02)
(defconstant +VM-PROT-EXECUTE+ #x04)

(defconstant +S-ATTR-PURE-INSTRUCTIONS+ #x80000000)
(defconstant +S-ATTR-SOME-INSTRUCTIONS+ #x00000400)
(defconstant +S-NON-LAZY-SYMBOL-POINTERS+ #x06)
(defconstant +S-SYMBOL-STUBS+ #x08)
(defconstant +S-ZEROFILL+ #x01)
(defconstant +S-ATTR-DEBUG+ #x02000000)

(defconstant +DYLD-CHAINED-PTR-64-OFFSET+ 6)
(defconstant +PAGE-SIZE+ #x4000)
(defconstant +VM-BASE+ #x100000000)

;;; ============================================================
;;; Buffer Building Helpers
;;; ============================================================

(defun buf-u8 (val)
  (cons (logand val #xFF) nil))

(defun buf-u16-le (val)
  (cons (logand val #xFF)
        (cons (logand (ash val -8) #xFF)
              nil)))

(defun buf-u32-le (val)
  (cons (logand val #xFF)
        (cons (logand (ash val -8) #xFF)
              (cons (logand (ash val -16) #xFF)
                    (cons (logand (ash val -24) #xFF)
                          nil)))))

(defun buf-u64-le (val)
  (append (buf-u32-le (logand val #xFFFFFFFF))
          (buf-u32-le (logand (ash val -32) #xFFFFFFFF))))

(defun buf-string-padded (str len)
  (let* ((slen (string-length str)))
    (labels ((collect-chars (idx)
               (if (>= idx (if (< slen len) slen len))
                   nil
                   (cons (string-ref str idx)
                         (collect-chars (+ idx 1)))))
             (collect-zeros (count)
               (if (<= count 0)
                   nil
                   (cons 0 (collect-zeros (- count 1))))))
      (append (collect-chars 0)
              (collect-zeros (- len slen))))))

(defun buf-zeros (count)
  "Create a list of COUNT zeros (iterative to avoid stack overflow)"
  (let ((result nil))
    (dotimes (i count result)
      (push 0 result))))

(defun buf-append-all (bufs)
  (if (null bufs)
      nil
      (append (car bufs) (buf-append-all (cdr bufs)))))

(defun buf-to-string (buf)
  (let* ((len (length buf))
         (vec (make-vector len)))
    (labels ((fill-vec (remaining idx)
               (if (null remaining)
                   vec
                   (progn
                     (vector-set vec idx (car remaining))
                     (fill-vec (cdr remaining) (+ idx 1))))))
      (let ((filled (fill-vec buf 0)))
        (make-string-from-vector filled)))))

(defun align-up (val alignment)
  (let ((rem (mod val alignment)))
    (if (= rem 0)
        val
        (+ val (- alignment rem)))))


;;; ============================================================
;;; Mach-O Header (32 bytes)
;;; ============================================================

(defun buf-mach-header-64 (ncmds sizeofcmds flags)
  "Generate Mach-O header as buffer"
  (buf-append-all
   (cons (buf-u32-le +MH-MAGIC-64+)
         (cons (buf-u32-le +CPU-TYPE-ARM64+)
               (cons (buf-u32-le +CPU-SUBTYPE-ARM64-ALL+)
                     (cons (buf-u32-le +MH-EXECUTE+)
                           (cons (buf-u32-le ncmds)
                                 (cons (buf-u32-le sizeofcmds)
                                       (cons (buf-u32-le flags)
                                             (cons (buf-u32-le 0)  ; reserved
                                                   nil))))))))))

;;; ============================================================
;;; Load Commands
;;; ============================================================

(defun buf-segment-command-64 (segname vmaddr vmsize fileoff filesize
                                maxprot initprot nsects flags)
  "Generate LC_SEGMENT_64 load command as buffer"
  (buf-append-all
   (cons (buf-u32-le +LC-SEGMENT-64+)
         (cons (buf-u32-le (+ 72 (* nsects 80)))
               (cons (buf-string-padded segname 16)
                     (cons (buf-u64-le vmaddr)
                           (cons (buf-u64-le vmsize)
                                 (cons (buf-u64-le fileoff)
                                       (cons (buf-u64-le filesize)
                                             (cons (buf-u32-le maxprot)
                                                   (cons (buf-u32-le initprot)
                                                         (cons (buf-u32-le nsects)
                                                               (cons (buf-u32-le flags)
                                                                     nil)))))))))))))

(defun buf-section-64 (sectname segname addr size offset align
                       reloff nreloc flags reserved1 reserved2)
  "Generate section_64 structure as buffer"
  (buf-append-all
   (cons (buf-string-padded sectname 16)
         (cons (buf-string-padded segname 16)
               (cons (buf-u64-le addr)
                     (cons (buf-u64-le size)
                           (cons (buf-u32-le offset)
                                 (cons (buf-u32-le align)
                                       (cons (buf-u32-le reloff)
                                             (cons (buf-u32-le nreloc)
                                                   (cons (buf-u32-le flags)
                                                         (cons (buf-u32-le reserved1)
                                                               (cons (buf-u32-le reserved2)
                                                                     (cons (buf-u32-le 0)  ; reserved3
                                                                           nil))))))))))))))

(defun buf-load-dylinker-command (path)
  "Generate LC_LOAD_DYLINKER command as buffer"
  (let* ((path-len (+ 1 (string-length path)))
         (cmdsize (align-up (+ 12 path-len) 8)))
    (buf-append-all
     (cons (buf-u32-le +LC-LOAD-DYLINKER+)
           (cons (buf-u32-le cmdsize)
                 (cons (buf-u32-le 12)
                       (cons (buf-string-padded path (- cmdsize 12))
                             nil)))))))

(defun buf-uuid-command (uuid-val)
  "Generate LC_UUID command as buffer (uuid-val = list of 4 u32 values)"
  (let* ((uuid0 (car uuid-val))
         (uuid1 (car (cdr uuid-val)))
         (uuid2 (car (cdr (cdr uuid-val))))
         (uuid3 (car (cdr (cdr (cdr uuid-val))))))
    (buf-append-all
     (cons (buf-u32-le +LC-UUID+)
           (cons (buf-u32-le 24)
                 (cons (buf-u32-le uuid0)
                       (cons (buf-u32-le uuid1)
                             (cons (buf-u32-le uuid2)
                                   (cons (buf-u32-le uuid3)
                                         nil)))))))))

(defun buf-build-version-command ()
  "Generate LC_BUILD_VERSION for macOS 14.0 as buffer"
  (buf-append-all
   (cons (buf-u32-le +LC-BUILD-VERSION+)
         (cons (buf-u32-le 24)
               (cons (buf-u32-le 1)           ; platform = macOS
                     (cons (buf-u32-le #x000E0000)  ; minos = 14.0
                           (cons (buf-u32-le #x000E0000)  ; sdk = 14.0
                                 (cons (buf-u32-le 0)  ; ntools
                                       nil))))))))

(defun buf-main-command (entryoff)
  "Generate LC_MAIN command as buffer"
  (buf-append-all
   (cons (buf-u32-le +LC-MAIN+)
         (cons (buf-u32-le 24)
               (cons (buf-u64-le entryoff)
                     (cons (buf-u64-le #x20000000)  ; stacksize = 512MB for deep recursion
                           nil))))))

(defun buf-load-dylib-command (path)
  "Generate LC_LOAD_DYLIB command as buffer"
  (let* ((path-len (+ 1 (string-length path)))
         (cmdsize (align-up (+ 24 path-len) 8)))
    (buf-append-all
     (cons (buf-u32-le +LC-LOAD-DYLIB+)
           (cons (buf-u32-le cmdsize)
                 (cons (buf-u32-le 24)        ; name.offset
                       (cons (buf-u32-le 2)   ; timestamp
                             (cons (buf-u32-le #x054C0000)  ; current_version
                                   (cons (buf-u32-le #x00010000)  ; compat_version
                                         (cons (buf-string-padded path (- cmdsize 24))
                                               nil))))))))))

(defun buf-symtab-command (symoff nsyms stroff strsize)
  "Generate LC_SYMTAB command as buffer"
  (buf-append-all
   (cons (buf-u32-le +LC-SYMTAB+)
         (cons (buf-u32-le 24)
               (cons (buf-u32-le symoff)
                     (cons (buf-u32-le nsyms)
                           (cons (buf-u32-le stroff)
                                 (cons (buf-u32-le strsize)
                                       nil))))))))

(defun buf-dysymtab-command (ilocalsym nlocalsym iextdefsym nextdefsym
                              iundefsym nundefsym)
  "Generate LC_DYSYMTAB command as buffer"
  (buf-append-all
   (cons (buf-u32-le +LC-DYSYMTAB+)
         (cons (buf-u32-le 80)
               (cons (buf-u32-le ilocalsym)
                     (cons (buf-u32-le nlocalsym)
                           (cons (buf-u32-le iextdefsym)
                                 (cons (buf-u32-le nextdefsym)
                                       (cons (buf-u32-le iundefsym)
                                             (cons (buf-u32-le nundefsym)
                                                   (cons (buf-zeros 48)  ; remaining fields
                                                         nil)))))))))))

;;; ============================================================
;;; Chained Fixups for Dynamic Linking
;;; ============================================================

(defun buf-chained-fixups-command (dataoff datasize)
  "Generate LC_DYLD_CHAINED_FIXUPS command as buffer"
  (buf-append-all
   (cons (buf-u32-le +LC-DYLD-CHAINED-FIXUPS+)
         (cons (buf-u32-le 16)
               (cons (buf-u32-le dataoff)
                     (cons (buf-u32-le datasize)
                           nil))))))

(defun string-to-bytes (str)
  "Convert string to list of character codes (bytes)"
  (labels ((collect (idx)
             (if (>= idx (string-length str))
                 nil
                 (cons (string-ref str idx)
                       (collect (+ idx 1))))))
    (collect 0)))

(defun build-symbols-list (imports)
  "Build symbols string: NUL-separated, starts with NUL"
  (labels ((append-name (name rest)
             (append (string-to-bytes name) (cons 0 rest)))
           (build-all (remaining)
             (if (null remaining)
                 nil
                 (append-name (car remaining) (build-all (cdr remaining))))))
    (cons 0 (build-all imports))))

(defun set-u32-le-at (buf offset val)
  "Set 32-bit little-endian value at offset in buffer (returns modified buffer)"
  (let* ((b0 (logand val #xFF))
         (b1 (logand (ash val -8) #xFF))
         (b2 (logand (ash val -16) #xFF))
         (b3 (logand (ash val -24) #xFF)))
    (labels ((set-bytes (lst idx)
               (cond
                 ((null lst) nil)
                 ((= idx offset) (cons b0 (set-bytes (cdr lst) (+ idx 1))))
                 ((= idx (+ offset 1)) (cons b1 (set-bytes (cdr lst) (+ idx 1))))
                 ((= idx (+ offset 2)) (cons b2 (set-bytes (cdr lst) (+ idx 1))))
                 ((= idx (+ offset 3)) (cons b3 (set-bytes (cdr lst) (+ idx 1))))
                 (t (cons (car lst) (set-bytes (cdr lst) (+ idx 1)))))))
      (set-bytes buf 0))))

(defun set-u16-le-at (buf offset val)
  "Set 16-bit little-endian value at offset in buffer"
  (let* ((b0 (logand val #xFF))
         (b1 (logand (ash val -8) #xFF)))
    (labels ((set-bytes (lst idx)
               (cond
                 ((null lst) nil)
                 ((= idx offset) (cons b0 (set-bytes (cdr lst) (+ idx 1))))
                 ((= idx (+ offset 1)) (cons b1 (set-bytes (cdr lst) (+ idx 1))))
                 (t (cons (car lst) (set-bytes (cdr lst) (+ idx 1)))))))
      (set-bytes buf 0))))

(defun set-u64-le-at (buf offset val)
  "Set 64-bit little-endian value at offset in buffer"
  (let* ((lo (logand val #xFFFFFFFF))
         (hi (logand (ash val -32) #xFFFFFFFF)))
    (set-u32-le-at (set-u32-le-at buf offset lo) (+ offset 4) hi)))

(defun set-byte-at (buf offset val)
  "Set single byte at offset in buffer"
  (labels ((set-bytes (lst idx)
             (cond
               ((null lst) nil)
               ((= idx offset) (cons val (set-bytes (cdr lst) (+ idx 1))))
               (t (cons (car lst) (set-bytes (cdr lst) (+ idx 1)))))))
    (set-bytes buf 0)))

(defun build-chained-fixups-data (imports num-segments got-segment-index got-vm-offset)
  "Build chained fixups data for binding external symbols.
   IMPORTS: list of symbol names (strings like \"_write\")
   NUM-SEGMENTS: total number of segments
   GOT-SEGMENT-INDEX: 0-based index of segment containing GOT
   GOT-VM-OFFSET: VM offset from binary base to first fixup
   
   Returns a byte list."
  (let* ((num-imports (length imports))
         (symbols-list (build-symbols-list imports))
         ;; Calculate offsets
         (header-size 32)
         (starts-header-size (+ 4 (* 4 num-segments)))
         (seg-info-size 24)
         (imports-entry-size 4)
         (starts-offset header-size)
         (seg-info-rel-offset (align-up starts-header-size 8))
         (imports-offset (+ starts-offset seg-info-rel-offset seg-info-size))
         (symbols-offset (+ imports-offset (* num-imports imports-entry-size)))
         (total-size (align-up (+ symbols-offset (length symbols-list)) 8)))
    
    ;; Create zero-filled buffer
    (let* ((data (buf-zeros total-size)))
      
      ;; Set dyld_chained_fixups_header fields
      (let* ((d1 (set-u32-le-at data 4 starts-offset))
             (d2 (set-u32-le-at d1 8 imports-offset))
             (d3 (set-u32-le-at d2 12 symbols-offset))
             (d4 (set-u32-le-at d3 16 num-imports))
             (d5 (set-byte-at d4 20 1)))  ; imports_format = 1
        
        ;; Set dyld_chained_starts_in_image
        (let* ((d6 (set-u32-le-at d5 starts-offset num-segments)))
          
          ;; Set seg_info_offset for GOT segment
          (let* ((seg-info-off-pos (+ starts-offset 4 (* got-segment-index 4)))
                 (d7 (set-u32-le-at d6 seg-info-off-pos seg-info-rel-offset)))
            
            ;; Set dyld_chained_starts_in_segment
            (let* ((seg-base (+ starts-offset seg-info-rel-offset))
                   (d8 (set-u32-le-at d7 seg-base 24))  ; size
                   (d9 (set-u16-le-at d8 (+ seg-base 4) #x4000))  ; page_size
                   (d10 (set-u16-le-at d9 (+ seg-base 6) +DYLD-CHAINED-PTR-64-OFFSET+))
                   (d11 (set-u64-le-at d10 (+ seg-base 8) got-vm-offset))
                   (d12 (set-u16-le-at d11 (+ seg-base 20) 1)))  ; page_count
              
              ;; Set import entries
              (labels ((set-imports (remaining idx name-offset buf)
                         (if (null remaining)
                             buf
                             (let* ((name (car remaining))
                                    (entry-off (+ imports-offset (* idx 4)))
                                    (entry (logior 1 (ash (+ 1 name-offset) 9)))
                                    (new-buf (set-u32-le-at buf entry-off entry))
                                    (new-name-offset (+ name-offset 1 (string-length name))))
                               (set-imports (cdr remaining) (+ idx 1) new-name-offset new-buf)))))
                
                (let* ((d13 (set-imports imports 0 0 d12)))
                  
                  ;; Copy symbol strings to buffer
                  (labels ((copy-symbols (src-list dst-idx buf)
                             (if (null src-list)
                                 buf
                                 (copy-symbols (cdr src-list)
                                              (+ dst-idx 1)
                                              (set-byte-at buf (+ symbols-offset dst-idx) (car src-list))))))
                    (copy-symbols symbols-list 0 d13)))))))))))

;;; ============================================================
;;; Top-Level Executable Generation
;;; ============================================================

(defun build-minimal-macho-executable (code-bytes)
  "Build minimal Mach-O executable that runs CODE-BYTES.
   CODE-BYTES should be a list of bytes (ARM64 machine code ending in RET).
   Returns a buffer (byte list) containing complete executable."
  (let* ((code-size (length code-bytes))
         
         ;; Calculate sizes for load commands
         (header-size 32)
         (pagezero-cmd-size 72)
         (text-cmd-size (+ 72 80))  ; segment + 1 section
         (linkedit-cmd-size 72)
         (dylinker-path "/usr/lib/dyld")
         (dylinker-cmd-size (align-up (+ 12 (string-length dylinker-path) 1) 8))
         (uuid-cmd-size 24)
         (build-version-cmd-size 24)
         (main-cmd-size 24)
         (libsystem-path "/usr/lib/libSystem.B.dylib")
         (load-dylib-cmd-size (align-up (+ 24 (string-length libsystem-path) 1) 8))
         (symtab-cmd-size 24)
         (dysymtab-cmd-size 80)
         
         ;; Number of load commands
         (ncmds 10)
         (sizeofcmds (+ pagezero-cmd-size
                       text-cmd-size
                       linkedit-cmd-size
                       dylinker-cmd-size
                       uuid-cmd-size
                       build-version-cmd-size
                       main-cmd-size
                       load-dylib-cmd-size
                       symtab-cmd-size
                       dysymtab-cmd-size))
         
         ;; Code placement
         (code-offset (align-up (+ header-size sizeofcmds 64) 64))
         (text-segment-size +PAGE-SIZE+)
         
         ;; LINKEDIT segment
         (linkedit-fileoff +PAGE-SIZE+)
         (linkedit-vmaddr (+ +VM-BASE+ +PAGE-SIZE+))
         
         ;; String table (just "_main")
         (string-table (cons 0 (cons 95 (cons 109 (cons 97 (cons 105 (cons 110 (cons 0 nil))))))))  ; 0, "_main", 0
         (string-table-size (length string-table))
         
         ;; Symbol table
         (symtab-offset linkedit-fileoff)
         (nsyms 1)
         (nlist-size (* nsyms 16))
         (strtab-offset (+ symtab-offset nlist-size))
         (linkedit-size (align-up (+ nlist-size string-table-size) 8))
         
         ;; Entry point
         (entry-offset code-offset)
         
         ;; Flags
         (flags (logior +MH-NOUNDEFS+ (logior +MH-DYLDLINK+
                                              (logior +MH-TWOLEVEL+ +MH-PIE+))))
         
         ;; UUID (simple: use constants)
         (uuid-vals (cons #xDEADBEEF (cons #xCAFEBABE (cons #x12345678 (cons #x87654321 nil))))))
    
    ;; Build executable by concatenating all parts
    (buf-append-all
     (cons (buf-mach-header-64 ncmds sizeofcmds flags)
           
           ;; Load commands
           (cons (buf-segment-command-64 "__PAGEZERO" 0 +PAGE-SIZE+ 0 0 0 0 0 0)
                 
                 (cons (buf-segment-command-64 "__TEXT" +VM-BASE+ text-segment-size
                                                0 text-segment-size
                                                (logior +VM-PROT-READ+ +VM-PROT-EXECUTE+)
                                                (logior +VM-PROT-READ+ +VM-PROT-EXECUTE+)
                                                1  ; 1 section
                                                0)
                       
                       (cons (buf-section-64 "__text" "__TEXT"
                                             (+ +VM-BASE+ code-offset) code-size
                                             code-offset 2  ; align = 2^2 = 4
                                             0 0  ; reloff, nreloc
                                             (logior +S-ATTR-PURE-INSTRUCTIONS+ +S-ATTR-SOME-INSTRUCTIONS+)
                                             0 0)  ; reserved1, reserved2
                             
                             (cons (buf-segment-command-64 "__LINKEDIT" linkedit-vmaddr linkedit-size
                                                            linkedit-fileoff linkedit-size
                                                            +VM-PROT-READ+ +VM-PROT-READ+
                                                            0 0)  ; nsects, flags
                                   
                                   (cons (buf-load-dylinker-command dylinker-path)
                                         
                                         (cons (buf-uuid-command uuid-vals)
                                               
                                               (cons (buf-build-version-command)
                                                     
                                                     (cons (buf-main-command entry-offset)
                                                           
                                                           (cons (buf-load-dylib-command libsystem-path)
                                                                 
                                                                 (cons (buf-symtab-command symtab-offset nsyms
                                                                                            strtab-offset string-table-size)
                                                                       
                                                                       (cons (buf-dysymtab-command 0 0 0 0 0 1)
                                                                             
                                                                             ;; Padding to code offset
                                                                             (cons (buf-zeros (- code-offset (+ header-size sizeofcmds)))
                                                                                   
                                                                                   ;; Code bytes
                                                                                   (cons code-bytes
                                                                                         
                                                                                         ;; Padding to PAGE_SIZE
                                                                                         (cons (buf-zeros (- linkedit-fileoff (+ code-offset code-size)))
                                                                                               
                                                                                               ;; LINKEDIT: symbol table (nlist_64 entry for _main)
                                                                                               (cons (buf-append-all
                                                                                                      (cons (buf-u32-le 1)  ; strx = 1 ("_main")
                                                                                                            (cons (buf-u8 #x0F)  ; n_type = N_SECT | N_EXT
                                                                                                                  (cons (buf-u8 1)  ; n_sect = 1 (__text)
                                                                                                                        (cons (buf-u16-le 0)  ; n_desc
                                                                                                                              (cons (buf-u64-le (+ +VM-BASE+ code-offset))
                                                                                                                                    nil))))))
                                                                                                     
                                                                                                     ;; String table
                                                                                                     (cons string-table
                                                                                                           
                                                                                                           ;; Final padding
                                                                                                           (cons (buf-zeros (- linkedit-size (+ nlist-size string-table-size)))
                                                                                                                 nil))))))))))))))))))))) ;; 21 parens (fixed: removed extra paren)

(defun write-minimal-macho-executable (output-path code-bytes)
  "Generate minimal Mach-O executable and write to file.
   CODE-BYTES: list of bytes (ARM64 machine code)
   OUTPUT-PATH: string path for output file"
  (let* ((exe-buf (build-minimal-macho-executable code-bytes))
         (exe-str (buf-to-string exe-buf)))
    (native-write-file output-path exe-str)))

;;; ============================================================
;;; ARM64 Instruction Encoding (uses arm64 package)
;;; ============================================================
;;; Note: All instruction encoding functions are in arm64 package (arm64/asm.lisp)
;;; arm64:adrp, arm64:adr, arm64:ldr, arm64:str, arm64:add, arm64:sub,
;;; arm64:mov, arm64:bl, arm64:br, arm64:lsr, arm64:ret

(defun generate-stub-code (got-page-offset got-slot-offset)
  "Generate ARM64 stub code that loads from GOT and branches.
   GOT-PAGE-OFFSET: signed page offset for ADRP (in 4KB pages)
   GOT-SLOT-OFFSET: byte offset within page for LDR
   Returns byte list (12 bytes = 3 instructions)"
  (append (arm64:adrp :x16 got-page-offset)
          (append (arm64:ldr :x16 :x16 :offset got-slot-offset)
                  (arm64:br :x16))))

(defun build-got-entries (num-imports)
  "Build GOT entries with bind markers.
   Each entry is 8 bytes with bit 63 set for chained fixups.
   Returns byte list."
  (labels ((build-entries (remaining idx)
             (if (<= remaining 0)
                 nil
                 (let* ((next-offset (if (= remaining 1) 0 2))  ; stride = 2 (8-byte entries)
                        ;; DYLD_CHAINED_PTR_64_OFFSET format:
                        ;; bit 63: bind (1)
                        ;; bits 62-51: next (stride in 4-byte units, 0 if last)
                        ;; bits 50-32: reserved
                        ;; bits 31-0: ordinal (import index)
                        (entry (logior #x8000000000000000  ; bit 63 = bind
                                      (ash next-offset 51)  ; bits 62-51 = next
                                      idx)))               ; bits 31-0 = ordinal
                   (append (buf-u64-le entry)
                          (build-entries (- remaining 1) (+ idx 1)))))))
    (build-entries num-imports 0)))

(defun build-stubs (imports got-page-offset got-base-offset)
  "Build stub code for all imports.
   IMPORTS: list of symbol names
   GOT-PAGE-OFFSET: page offset from stubs to GOT
   GOT-BASE-OFFSET: byte offset of first GOT entry within GOT page
   Returns byte list."
  (labels ((build-all (remaining idx)
             (if (null remaining)
                 nil
                 (let* ((got-slot-offset (+ got-base-offset (* idx 8)))
                        (stub (generate-stub-code got-page-offset got-slot-offset)))
                   (append stub (build-all (cdr remaining) (+ idx 1)))))))
    (build-all imports 0)))

;;; ============================================================
;;; Helper Functions for Symbol and Indirect Tables
;;; ============================================================

(defun build-string-table-for-imports (imports)
  "Build string table with _main followed by all import names.
   Returns list of bytes."
  (labels ((name-to-bytes (name)
             (append (string-to-bytes name) (cons 0 nil)))
           (build-all (names)
             (if (null names)
                 nil
                 (append (name-to-bytes (car names))
                        (build-all (cdr names))))))
    (cons 0 (build-all (cons "_main" imports)))))

(defun buf-nlist-64 (strx n-type n-sect n-desc n-value)
  "Generate nlist_64 symbol table entry (16 bytes)"
  (buf-append-all
   (cons (buf-u32-le strx)
         (cons (buf-u8 n-type)
               (cons (buf-u8 n-sect)
                     (cons (buf-u16-le n-desc)
                           (cons (buf-u64-le n-value)
                                 nil)))))))

(defun build-symbol-table (imports code-vmaddr)
  "Build symbol table: _main entry followed by import entries.
   Returns byte list."
  (labels ((build-import-syms (names strx)
             (if (null names)
                 nil
                 (let* ((sym (buf-nlist-64 strx #x01 0 #x0100 0))
                        (next-strx (+ strx 1 (string-length (car names)))))
                   (append sym (build-import-syms (cdr names) next-strx))))))
    (let* ((main-sym (buf-nlist-64 1 #x0F 1 #x0010 code-vmaddr))
           (import-syms (build-import-syms imports 7)))  ; "_main\0" = 7 bytes offset
      (append main-sym import-syms))))

;;; ============================================================
;;; Extended Symbol Table Support (with local function symbols)
;;; ============================================================

(defun local-symbol-name (name)
  "Convert function name to symbol name (add _ prefix if needed)"
  (let ((str (if (symbolp name) (symbol-name name) name)))
    (if (char= (char str 0) #\_)
        str
        (concatenate 'string "_" str))))

(defun build-string-table-with-locals (local-fns imports)
  "Build string table with local function names, _main, and imports.
   LOCAL-FNS: list of (name . offset) pairs
   Returns list of bytes."
  (labels ((name-to-bytes (name)
             (append (string-to-bytes name) (cons 0 nil)))
           (build-all (names)
             (if (null names)
                 nil
                 (append (name-to-bytes (car names))
                        (build-all (cdr names))))))
    (let ((local-names (mapcar (lambda (fn) (local-symbol-name (car fn))) local-fns)))
      (cons 0 (append (build-all local-names)
                      (build-all (cons "_main" imports)))))))

(defun compute-string-table-offsets (local-fns)
  "Compute string table offsets for local function names.
   Returns (total-local-size . offset-list)"
  (labels ((compute (fns offset acc)
             (if (null fns)
                 (cons offset (reverse acc))
                 (let* ((name (local-symbol-name (car (car fns))))
                        (size (+ 1 (length name))))  ; +1 for NUL
                   (compute (cdr fns) (+ offset size) (cons offset acc))))))
    (compute local-fns 1 nil)))  ; Start at 1 (after initial NUL)

(defun build-symbol-table-with-locals (local-fns imports code-vmaddr wrapper-size)
  "Build symbol table with local symbols, _main, and imports.
   LOCAL-FNS: list of (name . offset) pairs
   Symbol order: locals, extdef (_main), undefs (imports)
   Returns byte list."
  (let* ((offsets-info (compute-string-table-offsets local-fns))
         (local-strings-size (car offsets-info))
         (local-offsets (cdr offsets-info)))
    (labels ((build-local-syms (fns offsets)
               (if (null fns)
                   nil
                   (let* ((fn (car fns))
                          (offset (cdr fn))
                          (strx (car offsets))
                          ;; N_SECT = #x0E (local, defined in section)
                          (sym (buf-nlist-64 strx #x0E 1 0
                                            (+ code-vmaddr wrapper-size offset))))
                     (append sym (build-local-syms (cdr fns) (cdr offsets))))))
             (build-import-syms (names strx)
               (if (null names)
                   nil
                   (let* ((sym (buf-nlist-64 strx #x01 0 #x0100 0))
                          (next-strx (+ strx 1 (string-length (car names)))))
                     (append sym (build-import-syms (cdr names) next-strx))))))
      (let* ((local-syms (build-local-syms local-fns local-offsets))
             (main-strx (+ local-strings-size))  ; After local names
             (main-sym (buf-nlist-64 main-strx #x0F 1 #x0010 code-vmaddr))
             (import-strx (+ main-strx 7))  ; After "_main\0"
             (import-syms (build-import-syms imports import-strx)))
        (append local-syms main-sym import-syms)))))

(defun build-indirect-symbol-table (num-imports)
  "Build indirect symbol table for stubs and GOT.
   Returns byte list."
  (labels ((build-entries (count idx)
             (if (>= idx count)
                 nil
                 (append (buf-u32-le (+ idx 1))
                        (build-entries count (+ idx 1))))))
    ;; Stubs section entries (indices 1..num-imports)
    (append (build-entries num-imports 0)
            ;; GOT section entries (same indices)
            (build-entries num-imports 0))))

(defun build-indirect-symbol-table-with-offset (num-imports base-index)
  "Build indirect symbol table for stubs and GOT with offset for local symbols.
   BASE-INDEX: index of first undefined symbol (after locals and _main)
   Returns byte list."
  (labels ((build-entries (count idx)
             (if (>= idx count)
                 nil
                 (append (buf-u32-le (+ base-index idx))
                        (build-entries count (+ idx 1))))))
    ;; Stubs section entries
    (append (build-entries num-imports 0)
            ;; GOT section entries (same indices)
            (build-entries num-imports 0))))

(defun buf-exports-trie ()
  "Generate minimal exports trie (empty root node)"
  (cons #x00 (cons #x00 nil)))  ; terminal_size=0, child_count=0

(defun buf-dysymtab-command-full (ilocalsym nlocalsym iextdefsym nextdefsym
                                   iundefsym nundefsym indirectsymoff nindirectsyms)
  "Generate complete LC_DYSYMTAB command with indirect symbol table info"
  (buf-append-all
   (cons (buf-u32-le +LC-DYSYMTAB+)
         (cons (buf-u32-le 80)
               (cons (buf-u32-le ilocalsym)
                     (cons (buf-u32-le nlocalsym)
                           (cons (buf-u32-le iextdefsym)
                                 (cons (buf-u32-le nextdefsym)
                                       (cons (buf-u32-le iundefsym)
                                             (cons (buf-u32-le nundefsym)
                                                   (cons (buf-u32-le 0)  ; tocoff
                                                         (cons (buf-u32-le 0)  ; ntoc
                                                               (cons (buf-u32-le 0)  ; modtaboff
                                                                     (cons (buf-u32-le 0)  ; nmodtab
                                                                           (cons (buf-u32-le 0)  ; extrefsymoff
                                                                                 (cons (buf-u32-le 0)  ; nextrefsyms
                                                                                       (cons (buf-u32-le indirectsymoff)
                                                                                             (cons (buf-u32-le nindirectsyms)
                                                                                                   (cons (buf-u32-le 0)  ; extreloff
                                                                                                         (cons (buf-u32-le 0)  ; nextrel
                                                                                                               (cons (buf-u32-le 0)  ; locreloff
                                                                                                                     (cons (buf-u32-le 0)  ; nlocrel
                                                                                                                           nil))))))))))))))))))))))

(defun buf-exports-trie-command (dataoff datasize)
  "Generate LC_DYLD_EXPORTS_TRIE command"
  (buf-append-all
   (cons (buf-u32-le +LC-DYLD-EXPORTS-TRIE+)
         (cons (buf-u32-le 16)
               (cons (buf-u32-le dataoff)
                     (cons (buf-u32-le datasize)
                           nil))))))

;;; ============================================================
;;; Code Wrapper for Heap Initialization
;;; ============================================================


(defun wrap-bytecode-with-heap-for-imports (code-bytes heap-page-offset
                                            &optional (symtab-offset 0) (symtab-count 0))
  "Wrap bytecode with heap initialization for executables with imports.
   HEAP-PAGE-OFFSET is the page offset from the ADRP instruction to __DATA (in 4KB pages).
   SYMTAB-OFFSET is the offset from user code start (x26) to the symbol table.
   SYMTAB-COUNT is the number of entries in the symbol table.
   Returns +heap-wrapper-size+ bytes (42 instructions) + original code.
   Returns via RET after user code returns.
   Initializes all GC globals at [x27+0..128], heap data starts at x27+128.

   NOTE: If you change this wrapper, update +heap-wrapper-size+ in this file!"
  ;; GC layout at x27 (all fields initialized by wrapper):
  ;;   [x27+0]:   intern_table = nil (0x06)
  ;;   [x27+8]:   lambda_counter = 0
  ;;   [x27+16]:  from_end = x27 + 128 + 32MB
  ;;   [x27+24]:  half_heap_size = 32MB (0x2000000)
  ;;   [x27+32]:  space_flag = 0
  ;;   [x27+40]:  gc_state = 0
  ;;   [x27+48]:  symbol_counter = 0
  ;;   [x27+56]:  symbol_table = nil
  ;;   [x27+64]:  argc = 0
  ;;   [x27+72]:  argv = nil
  ;;   [x27+80]:  packages = nil
  ;;   [x27+88]:  current-package = nil
  ;;   [x27+96]:  stack_base = sp
  ;;   [x27+104]: global_vars = nil
  ;;   [x27+112]: symtab_offset (from x26 to embedded symbol table)
  ;;   [x27+120]: symtab_count (number of symbol table entries)
  ;;   [x27+128]: heap data starts, x28 points here (16-byte aligned)
  ;; Wrapper size: see +heap-wrapper-size+ constant at top of file
  (let* (;; Tag symtab values as fixnums (value << 4) before storing
         (symtab-offset-tagged (ash symtab-offset 4))
         (symtab-count-tagged (ash symtab-count 4))
         ;; Split tagged symtab-offset into 16-bit halves for movz/movk
         (symtab-lo (logand symtab-offset-tagged #xFFFF))
         (symtab-hi (logand (ash symtab-offset-tagged -16) #xFFFF))
         (stub (buf-append-all
                ;; Use nested cons like the original to build list of 4-byte instructions
                (cons (arm64:sub :sp :sp #x30 :imm t)           ; 1: sub sp, sp, #0x30
                (cons (arm64:str :lr :sp :offset 0)              ; 2: str x30, [sp]
                (cons (arm64:str :heap :sp :offset 8)            ; 3: str x28, [sp, 8]
                (cons (arm64:str :code-base :sp :offset 16)      ; 4: str x26, [sp, 16]
                (cons (arm64:str :gc :sp :offset 24)             ; 5: str x27, [sp, 24]
                (cons (arm64:adrp :heap heap-page-offset)        ; 6: adrp x28, heap
                (cons (arm64:mov :gc :heap)                      ; 7: mov x27, x28
                (cons (arm64:movz :x9 6)                         ; 8: movz x9, 6 (nil)
                (cons (arm64:str :x9 :gc :offset 0)              ; 9: str x9, [x27+0] (intern_table)
                (cons (arm64:str :x9 :gc :offset 56)             ; 10: str x9, [x27+56] (symbol_table = nil)
                (cons (arm64:str :x9 :gc :offset 72)             ; 11: str x9, [x27+72] (argv = nil)
                (cons (arm64:str :x9 :gc :offset 80)             ; 12: str x9, [x27+80] (packages = nil)
                (cons (arm64:str :x9 :gc :offset 88)             ; 13: str x9, [x27+88] (current-package = nil)
                (cons (arm64:str :x9 :gc :offset 104)            ; 14: str x9, [x27+104] (global_vars = nil)
                (cons (arm64:movz :x9 0)                         ; 15: movz x9, 0
                (cons (arm64:str :x9 :gc :offset 8)              ; 16: str x9, [x27+8] (lambda_counter = 0)
                (cons (arm64:str :x9 :gc :offset 32)             ; 17: str x9, [x27+32] (space_flag = 0)
                (cons (arm64:str :x9 :gc :offset 40)             ; 18: str x9, [x27+40] (gc_state = 0)
                (cons (arm64:str :x9 :gc :offset 48)             ; 19: str x9, [x27+48] (symbol_counter = 0)
                (cons (arm64:str :x9 :gc :offset 64)             ; 20: str x9, [x27+64] (argc = 0)
                (cons (arm64:movz :x10 0)                        ; 21: movz x10, 0
                (cons (arm64:movk :x10 #x200 :lsl 16)            ; 22: movk x10, #0x200, lsl 16 (=32MB)
                (cons (arm64:str :x10 :gc :offset 24)            ; 23: str x10, [x27+24] (half_heap)
                (cons (arm64:add :x11 :gc 128 :imm t)            ; 24: add x11, x27, #128
                (cons (arm64:add :x11 :x11 :x10)                 ; 25: add x11, x11, x10 (from_end)
                (cons (arm64:str :x11 :gc :offset 16)            ; 26: str x11, [x27+16]
                (cons (arm64:add :heap :gc 128 :imm t)           ; 27: add x28, x27, #128
                (cons (arm64:str :sp :gc :offset 96)             ; 28: str sp, [x27+96] (stack_base)
                ;; Symbol table setup (5 instructions)
                (cons (arm64:movz :x9 symtab-lo)                 ; 29: movz x9, #symtab_lo
                (cons (arm64:movk :x9 symtab-hi :lsl 16)         ; 30: movk x9, #symtab_hi, lsl 16
                (cons (arm64:str :x9 :gc :offset 112)            ; 31: str x9, [x27+112] (symtab_offset)
                (cons (arm64:movz :x9 (logand symtab-count-tagged #xFFFF))  ; 32: movz x9, #symtab_count (tagged)
                (cons (arm64:str :x9 :gc :offset 120)            ; 33: str x9, [x27+120] (symtab_count)
                ;; Call user code - adr at instr 34 (offset 132), bl at 35 (offset 136), MAIN at offset 168
                (cons (arm64:adr :code-base 36)                  ; 34: adr x26, +36 bytes to MAIN
                (cons (arm64:bl 8)                               ; 35: bl +8 instrs to MAIN
                ;; Exit handling - restore and return
                (cons (arm64:lsr :x0 :x0 4 :imm t)               ; 36: lsr x0, x0, #4 (untag)
                (cons (arm64:ldr :gc :sp :offset 24)             ; 37: ldr x27, [sp+24]
                (cons (arm64:ldr :code-base :sp :offset 16)      ; 38: ldr x26, [sp+16]
                (cons (arm64:ldr :heap :sp :offset 8)            ; 39: ldr x28, [sp+8]
                (cons (arm64:ldr :lr :sp :offset 0)              ; 40: ldr x30, [sp]
                (cons (arm64:add :sp :sp #x30 :imm t)            ; 41: add sp, sp, #0x30
                (cons (arm64:ret) nil))))))))))))))))))))))))))))))))))))))))))))) ; 42: ret
    (append stub code-bytes)))

;;; ============================================================
;;; Complete Executable Generator with Imports and Heap
;;; ============================================================

(defun build-macho-executable-with-imports-and-heap (code-bytes imports heap-size
                                                     &optional local-fns symtab-bytes)
  "Build complete Mach-O executable with dynamic imports and heap.
   CODE-BYTES: list of bytes (ARM64 machine code with BL to stubs)
   IMPORTS: list of import names (e.g. (\"_write\" \"_exit\"))
   HEAP-SIZE: size of heap segment
   LOCAL-FNS: optional list of (name . offset) pairs for local function symbols
   SYMTAB-BYTES: optional list of bytes for embedded symbol table (after stubs)

   Returns complete executable as byte list."
  (let* ((num-imports (length imports))
         (num-locals (if local-fns (length local-fns) 0))
         (stub-size 12)
         (stubs-total-size (* num-imports stub-size))
         (got-entry-size 8)
         (got-total-size (if (= num-imports 0) 8 (* num-imports got-entry-size)))
         ;; Embedded symbol table size
         (symtab-size (if symtab-bytes (length symtab-bytes) 0))

         ;; 5 segments
         (num-segments 5)
         (got-segment-index 2)

         ;; Load command sizes
         (header-size 32)
         (pagezero-cmd-size 72)
         (text-cmd-size (+ 72 (* 2 80)))  ; segment + 2 sections (__text, __stubs)
         (data-const-cmd-size (+ 72 80))   ; segment + 1 section (__got)
         (data-cmd-size (+ 72 80))         ; segment + 1 section (__heap)
         (linkedit-cmd-size 72)
         (dylinker-path "/usr/lib/dyld")
         (dylinker-cmd-size (align-up (+ 12 (string-length dylinker-path) 1) 8))
         (uuid-cmd-size 24)
         (build-version-cmd-size 24)
         (main-cmd-size 24)
         (libsystem-path "/usr/lib/libSystem.B.dylib")
         (load-dylib-cmd-size (align-up (+ 24 (string-length libsystem-path) 1) 8))
         (chained-fixups-cmd-size 16)
         (exports-trie-cmd-size 16)
         (symtab-cmd-size 24)
         (dysymtab-cmd-size 80)

         (ncmds 14)
         (sizeofcmds (+ pagezero-cmd-size text-cmd-size data-const-cmd-size data-cmd-size
                       linkedit-cmd-size dylinker-cmd-size uuid-cmd-size build-version-cmd-size
                       main-cmd-size load-dylib-cmd-size chained-fixups-cmd-size
                       exports-trie-cmd-size symtab-cmd-size dysymtab-cmd-size))

         ;; Code placement
         (code-offset (align-up (+ header-size sizeofcmds 16) 64))
         (code-size (length code-bytes))

         ;; Stubs follow code
         (stubs-offset (align-up (+ code-offset code-size) 4))
         (stubs-end (+ stubs-offset stubs-total-size))
         ;; Embedded symtab follows stubs (inside __TEXT but not in a section)
         (symtab-file-offset stubs-end)  ; symtab starts right after stubs
         (text-content-end (+ stubs-end symtab-size))

         ;; __TEXT segment
         (text-vmsize (align-up text-content-end +PAGE-SIZE+))
         (text-filesize text-vmsize)
         
         ;; __DATA_CONST segment (GOT)
         (data-const-fileoff text-filesize)
         (data-const-vmaddr (+ +VM-BASE+ text-vmsize))
         (data-const-vmsize +PAGE-SIZE+)
         (data-const-filesize +PAGE-SIZE+)
         
         ;; __DATA segment (heap) - uses S_ZEROFILL, no file data
         (data-fileoff (+ data-const-fileoff +PAGE-SIZE+))
         (data-vmaddr (+ data-const-vmaddr +PAGE-SIZE+))
         (heap-vmsize (align-up heap-size +PAGE-SIZE+))
         (data-filesize 0)  ; zerofill sections have no file data

         ;; __LINKEDIT segment - comes right after __DATA_CONST (zerofill has no file data)
         (linkedit-fileoff data-fileoff)
         (linkedit-vmaddr (+ data-vmaddr heap-vmsize))
         
         ;; Symbol and string tables
         (nsyms (+ num-locals 1 num-imports))
         (string-table (if local-fns
                          (build-string-table-with-locals local-fns imports)
                          (build-string-table-for-imports imports)))
         (string-table-size (length string-table))
         
         ;; LINKEDIT layout
         (symtab-offset linkedit-fileoff)
         (nlist-size (* nsyms 16))
         (strtab-offset (+ symtab-offset nlist-size))
         (indirect-offset (align-up (+ strtab-offset string-table-size) 4))
         (num-indirect-syms (* 2 num-imports))
         (indirect-size (* num-indirect-syms 4))
         (fixups-offset (align-up (+ indirect-offset indirect-size) 8))
         
         ;; Chained fixups
         (got-vm-offset text-vmsize)
         (fixups-data (build-chained-fixups-data imports num-segments got-segment-index got-vm-offset))
         (fixups-size (length fixups-data))
         (aligned-fixups-size (align-up fixups-size 8))
         
         ;; Exports trie
         (exports-offset (align-up (+ fixups-offset fixups-size) 8))
         (exports-trie-data (buf-exports-trie))
         (exports-trie-size (length exports-trie-data))
         (aligned-exports-size (align-up exports-trie-size 8))
         
         ;; LINKEDIT total size
         (linkedit-size (align-up (+ nlist-size string-table-size
                                    (- indirect-offset strtab-offset string-table-size)
                                    indirect-size
                                    (- fixups-offset indirect-offset indirect-size)
                                    aligned-fixups-size
                                    aligned-exports-size)
                                 +PAGE-SIZE+))
         
         (entry-offset code-offset)
         (flags (logior +MH-NOUNDEFS+ (logior +MH-DYLDLINK+ (logior +MH-TWOLEVEL+ +MH-PIE+))))
         (uuid-vals (cons #xDEADBEEF (cons #xCAFEBABE (cons #x12345678 (cons #x87654321 nil)))))
         
         ;; Calculate stub parameters
         (stub-vmaddr (+ +VM-BASE+ stubs-offset))
         (stub-page (ash stub-vmaddr -12))
         (got-page (ash data-const-vmaddr -12))
         (got-page-diff (- got-page stub-page))
         (got-base-offset 0))
    
    ;; Assemble complete executable
    (buf-append-all
     (cons
      ;; Mach-O header
      (buf-mach-header-64 ncmds sizeofcmds flags)
      
      (cons
       ;; LC #1: __PAGEZERO
       (buf-segment-command-64 "__PAGEZERO" 0 +VM-BASE+ 0 0 0 0 0 0)
       
       (cons
        ;; LC #2: __TEXT with 2 sections
        (buf-segment-command-64 "__TEXT" +VM-BASE+ text-vmsize 0 text-filesize
                                (logior +VM-PROT-READ+ +VM-PROT-EXECUTE+)
                                (logior +VM-PROT-READ+ +VM-PROT-EXECUTE+)
                                2 0)
        
        (cons
         ;; __text section
         (buf-section-64 "__text" "__TEXT"
                        (+ +VM-BASE+ code-offset) code-size code-offset 2 0 0
                        (logior +S-ATTR-PURE-INSTRUCTIONS+ +S-ATTR-SOME-INSTRUCTIONS+)
                        0 0)
         
         (cons
          ;; __stubs section
          (buf-section-64 "__stubs" "__TEXT"
                         (+ +VM-BASE+ stubs-offset) stubs-total-size stubs-offset 2 0 0
                         (logior +S-SYMBOL-STUBS+ +S-ATTR-PURE-INSTRUCTIONS+)
                         0 stub-size)
          
          (cons
           ;; LC #3: __DATA_CONST with __got
           (buf-segment-command-64 "__DATA_CONST" data-const-vmaddr data-const-vmsize
                                   data-const-fileoff data-const-filesize
                                   (logior +VM-PROT-READ+ +VM-PROT-WRITE+)
                                   (logior +VM-PROT-READ+ +VM-PROT-WRITE+)
                                   1 0)
           
           (cons
            ;; __got section
            (buf-section-64 "__got" "__DATA_CONST"
                           data-const-vmaddr got-total-size data-const-fileoff 3 0 0
                           +S-NON-LAZY-SYMBOL-POINTERS+
                           num-imports 0)
            
            (cons
             ;; LC #4: __DATA with __heap
             (buf-segment-command-64 "__DATA" data-vmaddr heap-vmsize
                                     data-fileoff data-filesize
                                     (logior +VM-PROT-READ+ +VM-PROT-WRITE+)
                                     (logior +VM-PROT-READ+ +VM-PROT-WRITE+)
                                     1 0)
             
             (cons
              ;; __heap section - S_ZEROFILL: no file data, zeroed on demand
              (buf-section-64 "__heap" "__DATA"
                             data-vmaddr heap-vmsize 0 3 0 0 +S-ZEROFILL+ 0 0)
              
              (cons
               ;; LC #5: __LINKEDIT
               (buf-segment-command-64 "__LINKEDIT" linkedit-vmaddr +PAGE-SIZE+
                                       linkedit-fileoff linkedit-size
                                       +VM-PROT-READ+ +VM-PROT-READ+
                                       0 0)
               
               (cons
                ;; LC #6: dylinker
                (buf-load-dylinker-command dylinker-path)
                
                (cons
                 ;; LC #7: UUID
                 (buf-uuid-command uuid-vals)
                 
                 (cons
                  ;; LC #8: build version
                  (buf-build-version-command)
                  
                  (cons
                   ;; LC #9: main entry point
                   (buf-main-command entry-offset)
                   
                   (cons
                    ;; LC #10: load dylib
                    (buf-load-dylib-command libsystem-path)
                    
                    (cons
                     ;; LC #11: chained fixups
                     (buf-chained-fixups-command fixups-offset aligned-fixups-size)
                     
                     (cons
                      ;; LC #12: exports trie
                      (buf-exports-trie-command exports-offset aligned-exports-size)
                      
                      (cons
                       ;; LC #13: symtab
                       (buf-symtab-command symtab-offset nsyms strtab-offset string-table-size)
                       
                       (cons
                        ;; LC #14: dysymtab
                        ;; Order: locals, extdef (_main), undefs (imports)
                        (buf-dysymtab-command-full 0 num-locals num-locals 1
                                                   (+ num-locals 1) num-imports
                                                   indirect-offset num-indirect-syms)
                        
                        (cons
                         ;; Padding to code
                         (buf-zeros (- code-offset (+ header-size sizeofcmds)))
                         
                         (cons
                          ;; Code bytes
                          code-bytes
                          
                          (cons
                           ;; Padding to stubs
                           (buf-zeros (- stubs-offset (+ code-offset code-size)))
                           
                           (cons
                            ;; Stubs
                            (build-stubs imports got-page-diff got-base-offset)

                            (cons
                             ;; Embedded symbol table (after stubs)
                             (if symtab-bytes symtab-bytes nil)

                             (cons
                              ;; Padding to DATA_CONST
                              (buf-zeros (- data-const-fileoff text-content-end))

                              (cons
                               ;; GOT entries
                               (build-got-entries num-imports)
                              
                              (cons
                               ;; Padding to DATA
                               (buf-zeros (- data-fileoff (+ data-const-fileoff got-total-size)))
                               
                               (cons
                                ;; Heap (zeros)
                                (buf-zeros data-filesize)
                                
                                (cons
                                 ;; Symbol table
                                 (if local-fns
                                     (build-symbol-table-with-locals local-fns imports (+ +VM-BASE+ code-offset) +heap-wrapper-size+)
                                     (build-symbol-table imports (+ +VM-BASE+ code-offset)))
                                 
                                 (cons
                                  ;; String table
                                  string-table
                                  
                                  (cons
                                   ;; Padding to indirect symbols
                                   (buf-zeros (- indirect-offset (+ strtab-offset string-table-size)))
                                   
                                   (cons
                                    ;; Indirect symbol table
                                    (if local-fns
                                        (build-indirect-symbol-table-with-offset num-imports (1+ num-locals))
                                        (build-indirect-symbol-table num-imports))
                                    
                                    (cons
                                     ;; Padding to fixups
                                     (buf-zeros (- fixups-offset (+ indirect-offset indirect-size)))
                                     
                                     (cons
                                      ;; Chained fixups data
                                      fixups-data
                                      
                                      (cons
                                       ;; Padding to aligned fixups
                                       (buf-zeros (- aligned-fixups-size fixups-size))
                                       
                                       (cons
                                        ;; Exports trie
                                        exports-trie-data
                                        
                                        (cons
                                         ;; Padding to aligned exports
                                         (buf-zeros (- aligned-exports-size exports-trie-size))
                                         
                                         (cons
                                          ;; Final padding to linkedit size
                                          (buf-zeros (- linkedit-size
                                                       (+ nlist-size string-table-size
                                                          (- indirect-offset strtab-offset string-table-size)
                                                          indirect-size
                                                          (- fixups-offset indirect-offset indirect-size)
                                                          aligned-fixups-size
                                                          aligned-exports-size)))
                                          nil))))))))))))))))))))))))))))))))))))))))) ;; 41 parens (added 1 for symtab cons)

(defun write-macho-executable-with-imports-and-heap (output-path code-bytes imports heap-size
                                                     &optional local-fns symtab-bytes)
  "Generate complete Mach-O executable with imports and heap, write to file.
   CODE-BYTES: list of bytes (ARM64 machine code)
   IMPORTS: list of import names (strings like \"_write\")
   HEAP-SIZE: size of heap segment
   OUTPUT-PATH: string path for output file
   LOCAL-FNS: optional list of (name . offset) for function symbols
   SYMTAB-BYTES: optional list of bytes for embedded symbol table"
  (let* ((exe-buf (build-macho-executable-with-imports-and-heap code-bytes imports heap-size
                                                                 local-fns symtab-bytes))
         (exe-str (buf-to-string exe-buf)))
    ;; Use native-write-executable which handles +x and codesign
    (native-write-executable output-path exe-str)))

