require lib/test.f
require test/checker-assert.f
require src/arch/arm32/asm.f

package A32ASM-TEST
private
using A32ASM

: ARM= ( A32ASM:arm-instruction n -- )
   swap ARM-INSTRUCTION>N swap T= ;

: THUMB16= ( A32ASM:thumb16-instruction n -- )
   swap THUMB16-INSTRUCTION>N swap T= ;

: THUMB32= ( A32ASM:thumb32-instruction n -- )
   swap THUMB32-INSTRUCTION>N swap T= ;

: ARM-DATA-CASES ( -- )
   4 >GPR $ABCD ARM-MOVW $E30A4BCD ARM=
   14 >GPR $FFFF ARM-MOVT $E34FEFFF ARM=
   4 >GPR 5 >GPR 6 >GPR ARM-ADD $E0854006 ARM=
   0 >GPR 14 >GPR ARM-CMP $E150000E ARM= ;

: ARM-CONTROL-CASES ( -- )
   14 >GPR 13 >GPR -4095 ARM-LDR $E51DEFFF ARM=
   14 >GPR ARM-BX $E12FFF1E ARM=
   AL 33554428 >BRANCH-OFFSET ARM-B $EA7FFFFF ARM=
   AL -33554432 >BRANCH-OFFSET ARM-BL $EB800000 ARM= ;

: THUMB-SHORT-CASES ( -- )
   7 >GPR 255 THUMB-MOVS $27FF THUMB16=
   0 >GPR 1 >GPR 7 >GPR THUMB-ADDS $19C8 THUMB16=
   7 >GPR 6 >GPR 124 THUMB-LDR $6FF7 THUMB16=
   14 >GPR THUMB-BX $4770 THUMB16= ;

: THUMB-SHORT-BRANCHES ( -- )
   -2048 >BRANCH-OFFSET THUMB-B-SHORT $E400 THUMB16=
   2046 >BRANCH-OFFSET THUMB-B-SHORT $E3FF THUMB16=
   0 >CONDITION -256 >BRANCH-OFFSET THUMB-B-COND $D080 THUMB16=
   13 >CONDITION 254 >BRANCH-OFFSET THUMB-B-COND $DD7F THUMB16= ;

: THUMB-WIDE-CASES ( -- )
   12 >GPR $ABCD THUMB-MOVW $F64A3CCD THUMB32=
   14 >GPR $FFFF THUMB-MOVT $F6CF7EFF THUMB32=
   14 >GPR 13 >GPR 4095 THUMB-LDR-WIDE $F8DDEFFF THUMB32=
   8 >GPR 12 >GPR 0 THUMB-STR-WIDE $F8CC8000 THUMB32= ;

: THUMB-WIDE-BRANCHES ( -- )
   -16777216 >BRANCH-OFFSET THUMB-B-WIDE $F4009000 THUMB32=
   16777214 >BRANCH-OFFSET THUMB-BL $F3FFD7FF THUMB32=
   -2 >BRANCH-OFFSET THUMB-BL $F7FFFFFF THUMB32=
   0 >BRANCH-OFFSET THUMB-B-WIDE $F000B800 THUMB32= ;

: REGISTER-REFUSALS ( -- )
   [: -1 >GPR ARM-BX drop ;] E-OPERAND TTHROWSQ
   [: 15 >GPR 0 ARM-MOV-I8 drop ;] E-OPERAND TTHROWSQ
   [: 8 >GPR 0 THUMB-MOVS drop ;] E-OPERAND TTHROWSQ
   [: 13 >GPR 0 THUMB-MOVW drop ;] E-OPERAND TTHROWSQ
   [: 15 >GPR THUMB-BX drop ;] E-OPERAND TTHROWSQ ;

: CONSTANT-REFUSALS ( -- )
   [: 0 >GPR -1 ARM-MOV-I8 drop ;] E-OPERAND TTHROWSQ
   [: 0 >GPR 256 ARM-MOV-I8 drop ;] E-OPERAND TTHROWSQ
   [: 0 >GPR 65536 ARM-MOVW drop ;] E-OPERAND TTHROWSQ
   [: 0 >GPR -1 THUMB-MOVT drop ;] E-OPERAND TTHROWSQ ;

: MEMORY-REFUSALS ( -- )
   [: 0 >GPR 1 >GPR -4096 ARM-LDR drop ;] E-OPERAND TTHROWSQ
   [: 0 >GPR 1 >GPR 4096 ARM-STR drop ;] E-OPERAND TTHROWSQ
   [: 0 >GPR 1 >GPR 2 THUMB-LDR drop ;] E-OPERAND TTHROWSQ
   [: 0 >GPR 1 >GPR -4 THUMB-STR drop ;] E-OPERAND TTHROWSQ
   [: 0 >GPR 1 >GPR 4096 THUMB-LDR-WIDE drop ;] E-OPERAND TTHROWSQ ;

: ARM-BRANCH-REFUSALS ( -- )
   [: AL 2 >BRANCH-OFFSET ARM-B drop ;] E-OPERAND TTHROWSQ
   [: AL 33554432 >BRANCH-OFFSET ARM-B drop ;] E-OPERAND TTHROWSQ
   [: AL -33554436 >BRANCH-OFFSET ARM-BL drop ;] E-OPERAND TTHROWSQ
   [: 15 >CONDITION 0 >BRANCH-OFFSET ARM-B drop ;] E-OPERAND TTHROWSQ ;

: THUMB-BRANCH-REFUSALS ( -- )
   [: 1 >BRANCH-OFFSET THUMB-B-SHORT drop ;] E-OPERAND TTHROWSQ
   [: 2048 >BRANCH-OFFSET THUMB-B-SHORT drop ;] E-OPERAND TTHROWSQ
   [: 14 >CONDITION 0 >BRANCH-OFFSET THUMB-B-COND drop ;] E-OPERAND TTHROWSQ
   [: 0 >CONDITION 256 >BRANCH-OFFSET THUMB-B-COND drop ;] E-OPERAND TTHROWSQ ;

: THUMB-WIDE-REFUSALS ( -- )
   [: -3 >BRANCH-OFFSET THUMB-BL drop ;] E-OPERAND TTHROWSQ
   [: -16777218 >BRANCH-OFFSET THUMB-B-WIDE drop ;] E-OPERAND TTHROWSQ
   [: 16777216 >BRANCH-OFFSET THUMB-BL drop ;] E-OPERAND TTHROWSQ ;

: NOMINAL-CASES ( -- )
   s" ARM-GOOD ( A32ASM:gpr -- A32ASM:gpr )" CHECK-QUIET-CANDIDATE! -1 T=
   s" ARM-BAD-REG ( n -- A32ASM:gpr )" CHECK-QUIET-CANDIDATE! 0 T=
   s" ARM-BAD-WIDE ( A32ASM:arm-instruction -- A32ASM:thumb32-instruction )"
      CHECK-QUIET-CANDIDATE! 0 T=
   s" ARM-BAD-SHORT ( A32ASM:thumb16-instruction -- A32ASM:thumb32-instruction )"
      CHECK-QUIET-CANDIDATE! 0 T= ;

: RUN ( -- )
   ARM-DATA-CASES ARM-CONTROL-CASES THUMB-SHORT-CASES THUMB-SHORT-BRANCHES
   THUMB-WIDE-CASES THUMB-WIDE-BRANCHES REGISTER-REFUSALS CONSTANT-REFUSALS
   MEMORY-REFUSALS ARM-BRANCH-REFUSALS THUMB-BRANCH-REFUSALS
   THUMB-WIDE-REFUSALS NOMINAL-CASES T-REPORT ;

RUN
;package
