\ Shared HIR keeps the target binding; the native backend owns its limits.
require lib/test.f
require src/compiler/native/hir.f
require src/compiler/native/hir-word.f
require src/compiler/native/abi.f

package BACKEND-BOUNDARY-TEST
using IR-BUILD
using IR-SCHEMA
private

: WRAPPING ( CTARGET:contract -- CBIND:binding )
   CNUM-OVERFLOW:WRAP CNUM-FLOAT--MODEL:IEEE754 CNUM-CONTRACTION:FORBIDDEN
   CNUM-FAST--MATH:BIT-EXACT CNUM-COMPARE:IEEE754-UNORDERED CNUM:POLICY
   CBIND:BIND ;

: ARM-BINDING ( CTARGET:arch -- CBIND:binding )
   CTARGET-ABI:AAPCS32 CTARGET-ENDIAN:LITTLE CTARGET-PTR--WIDTH:BITS32
   CTARGET:F-BASE CTARGET:CONTRACT WRAPPING ;

: C66-BINDING ( -- CBIND:binding )
   CTARGET-ARCH:C66X CTARGET-ABI:C6000-EABI CTARGET-ENDIAN:LITTLE
   CTARGET-PTR--WIDTH:BITS32 CTARGET:F-BASE CTARGET:CONTRACT WRAPPING ;

: BIG-BINDING ( -- CBIND:binding )
   CTARGET-ARCH:AARCH64 CTARGET-ABI:AAPCS64-LINUX CTARGET-ENDIAN:BIG
   CTARGET-PTR--WIDTH:BITS64 CTARGET:F-BASE CTARGET:CONTRACT WRAPPING ;

: BUILD-HIR ( IR-CTX:ctx -- )
   {: c:IR-CTX:ctx :}
   PLAN-BEGIN PLAN-DEFAULT
   c HIR:NEW-BUILDER {: b:IR-BUILD:builder :}
   c b HIR-OPCODE:CONST HIR:ENSURE-OP {: op:IR-ID:ir-symbol-id :}
   c b HIR:CELL-TYPE {: celltype:IR-ID:ir-type-id :}
   c b FREEZE {: m:IR-BUILD:module :}
   m FSCHEMA-ROWS op FARCH@
   c IR-CTX:BINDING@ CBIND:TARGET@ CTARGET:ARCH@ CTARGET-ARCH:EQ TTRUE
   m FSCHEMA-POOL m FSCHEMA-ROWS m FKEY
   op 0 FRESULT@ IR-ID:TYPE-LOCAL celltype IR-ID:TYPE-LOCAL = TTRUE
   m FTYPE-ROWS celltype IR-TYPE:FINT@
   IR--TYPE-SIGN:SIGNED IR--TYPE-SIGN:EQ TTRUE
   IR--TYPE-WIDTH:W64 IR--TYPE-WIDTH:EQ TTRUE
   HIR:CELL-BYTES 8 T= ;

: BUILD-NATIVE ( IR-CTX:ctx -- )
   PLAN-BEGIN PLAN-DEFAULT
   A64IR:NEW-BUILDER drop ;

: ARM-NATIVE ( -- )
   CTARGET-ARCH:A32 ARM-BINDING [: BUILD-NATIVE ;] IR-CTX:WITH-CONTEXT ;

: THUMB-NATIVE ( -- )
   CTARGET-ARCH:THUMB2 ARM-BINDING [: BUILD-NATIVE ;] IR-CTX:WITH-CONTEXT ;

: C66-NATIVE ( -- )
   C66-BINDING [: BUILD-NATIVE ;] IR-CTX:WITH-CONTEXT ;

: BIG-NATIVE ( -- )
   BIG-BINDING [: BUILD-NATIVE ;] IR-CTX:WITH-CONTEXT ;

public

: RUN ( -- )
   T-RESET
   s" shared integer HIR preserves ARM, Thumb2 and C66x bindings" T-LABEL
   CTARGET-ARCH:A32 ARM-BINDING [: BUILD-HIR ;] IR-CTX:WITH-CONTEXT
   CTARGET-ARCH:THUMB2 ARM-BINDING [: BUILD-HIR ;] IR-CTX:WITH-CONTEXT
   C66-BINDING [: BUILD-HIR ;] IR-CTX:WITH-CONTEXT
   s" shared HIR also preserves a coherent big-endian binding" T-LABEL
   BIG-BINDING [: BUILD-HIR ;] IR-CTX:WITH-CONTEXT
   s" the supported native host still creates its machine module" T-LABEL
   NABI:BINDING [: BUILD-HIR ;] IR-CTX:WITH-CONTEXT
   NABI:BINDING [: BUILD-NATIVE ;] IR-CTX:WITH-CONTEXT
   s" unsupported native targets refuse before machine construction" T-LABEL
   [: ARM-NATIVE ;] E-IR-SCHEMA-TARGET TTHROWSQ
   [: THUMB-NATIVE ;] E-IR-SCHEMA-TARGET TTHROWSQ
   [: C66-NATIVE ;] E-IR-SCHEMA-TARGET TTHROWSQ
   [: BIG-NATIVE ;] E-IR-SCHEMA-TARGET TTHROWSQ
   T-REPORT ;

;using
;using
;package

BACKEND-BOUNDARY-TEST:RUN
