\ checker-model-obligations.f - the Rocq obligation text the checker parity gate
\ proves.
\
\ The module lives in `package CHECKER-MODEL-ROCQ`. It writes one Rocq source
\ out of live state: the frozen tables in `package CHECKER-MODEL-PROOF` and the
\ theorem names and statements in the committed manifest. Nothing in it is
\ transcribed.
\
\ Why the obligations are generated rather than written by hand. A hand-written
\ Rocq companion would be a second copy of the vocabulary, the dispatch table
\ and the program vectors, and two copies drift. Here the Habu side and the Rocq
\ side read the one artifact: `test/compiler/checker-model-cases.f` asks the
\ shipped checker about each row, and the very same row is turned into a Rocq
\ obligation about `Habu.Common.Effects` and `Habu.Common.Control`. Delete a
\ row, weaken it, or edit it in place and the two sides are asked different
\ questions, so one refuses.
\
\ What is written out, in order:
\
\   - one obligation per concrete type, binding its code, class, width and sign
\     to the `Effects.con` constructor the frozen row names;
\   - one exhaustive match over `Effects.con`, `Effects.ty`, `Effects.stack` and
\     `Control.tok` naming exactly the constructors the frozen tables name. A
\     constructor ADDED to a model and not to a table leaves the generated match
\     non-exhaustive and Rocq refuses the file; a constructor REMOVED or renamed
\     leaves the generated match naming something that does not resolve, and
\     Rocq refuses the file. That is the both-ways half of the vocabulary
\     question, the other half being the cases file's walk over the checker;
\   - the ceiling `con_max`, which is what a declared linear type's code counts
\     from;
\   - one obligation per control frame kind, running the frozen model token
\     sequence and reading the kind off the top of the model's frame stack;
\   - one obligation per shared program vector, running the frozen model token
\     list through `check_ctl` and demanding the row's one verdict;
\   - one ascribed definition per statement the manifest binds, and one
\     assumption query per statement.
\
\ Statements, not just names. Asking Rocq what a result assumes says nothing
\ about what it says, so every statement the manifest binds is also written out
\ as `Definition pinned_statement_<k> : <manifest type row> := @<name>.` The
\ ascribed type is the manifest's copy of the statement, so a proof rewritten to
\ state something weaker no longer type-checks at the type the committed
\ manifest asks for, and Rocq refuses the generated file.
\
\ Consumer: `test/compiler/checker-model-proof.f`.

require lib/prelude.f
require lib/errors.f
require lib/string.f
require lib/fmt.f
require test/compiler/checker-model-schema.f

package CHECKER-MODEL-ROCQ
using CHECKER-MODEL-PROOF
private

$40000 constant V-CAP
$0A constant LF
$22 constant DQ

create V-BUF V-CAP allot

variable V-U
variable PIN-N
variable ARM-N

\ ---- emit buffer -------------------------------------------------------------

: +$ ( ptr u8 n -- ) {: a:ptr u:n :}
   V-U @ u + V-CAP > if E-STR-CAPACITY throw then
   a V-BUF V-U @ + u BYTE-COPY
   V-U @ u + V-U ! ;

: +C ( n -- ) {: c:n :}
   V-U @ 1+ V-CAP > if E-STR-CAPACITY throw then
   c V-BUF V-U @ + c!
   V-U @ 1+ V-U ! ;

: +NL ( -- )
   LF +C ;

: +N ( n -- )
   SB-RESET FMT:SB-INT SB$ +$ ;

\ ---- preamble ----------------------------------------------------------------
\ The same imports the models themselves open, with the models imported last and
\ in build order, so a name the manifest wrote down resolves here exactly as it
\ did where Rocq printed it.

: EMIT-HEAD ( -- )
   s" (* Generated by test/compiler/checker-model-proof.f from the frozen" +$ +NL
   s"    checker tables and the committed manifest. A build output: never" +$ +NL
   s"    committed. *)" +$ +NL
   s" From Stdlib Require Import Bool List PeanoNat." +$ +NL
   s" Import ListNotations." +$ +NL
   s" From Habu.Common Require Import Effects Control." +$ +NL
   s" Set Printing Width 100000." +$ +NL ;

\ ---- 1. the concrete type vocabulary -----------------------------------------

: +CLASS-CON ( ptr u8 n -- ) {: wa:ptr wu:n :}
   CLASSES 0 ?do
      i CLS-WORD$ wa wu STR= if i CLS-CON$ +$ unloop exit then
   loop
   E-CMP-ROW throw ;

: +SIGN-CON ( ptr u8 n -- ) {: wa:ptr wu:n :}
   SIGNS 0 ?do
      i SGN-WORD$ wa wu STR= if i SGN-CON$ +$ unloop exit then
   loop
   E-CMP-ROW throw ;

: EMIT-VOCAB-ROW ( n -- ) {: k:n :}
   s" Example vocab_" +$ k VOC-NAME$ +$ s"  :" +$ +NL
   s"   con_code " +$ k VOC-CON$ +$ s"  = " +$ k VOC-CODE@ +N
   s"  /\ con_cls " +$ k VOC-CON$ +$ s"  = " +$ k VOC-CLASSW$ +CLASS-CON
   s"  /\ con_width " +$ k VOC-CON$ +$ s"  = " +$ k VOC-WIDTH@ +N
   s"  /\ con_sgn " +$ k VOC-CON$ +$ s"  = " +$ k VOC-SIGNW$ +SIGN-CON
   s" ." +$ +NL
   s" Proof. repeat split; vm_compute; reflexivity. Qed." +$ +NL ;

: EMIT-VOCAB ( -- )
   VOCAB 0 ?do i EMIT-VOCAB-ROW loop
   s" Example vocab_ceiling : con_max = " +$ VOCAB 1+ +N s" ." +$ +NL
   s" Proof. vm_compute; reflexivity. Qed." +$ +NL ;

\ ---- 2. the exhaustive vocabulary matches ------------------------------------
\ Each of these is a total function written over exactly the constructors a
\ frozen table names. Rocq accepts it only if that list IS the constructor set,
\ so the model cannot grow a constructor the tables have never heard of and
\ cannot lose one they name.

: EMIT-CON-COMPLETE ( -- )
   s" Definition con_known (c : con) : bool :=" +$ +NL
   s"   match c with" +$ +NL
   s"   | " +$
   VOCAB 0 ?do
      i 0 > if s"  | " +$ then
      i VOC-CON$ +$
   loop
   s"  | CLinear _ => true" +$ +NL
   s"   end." +$ +NL
   s" Example con_vocabulary_is_exactly_the_frozen_table :" +$ +NL
   s"   forall c : con, con_known c = true." +$ +NL
   s" Proof. destruct c; reflexivity. Qed." +$ +NL ;

\ One arm per tag row whose sort is this one, in table order. A tag the model
\ deliberately does not carry has an empty sort and contributes no arm, which is
\ why the omission has to be written down in the table rather than inferred.
: +TAG-ARMS ( ptr u8 n -- ) {: sa:ptr su:n :}
   0 ARM-N !
   TAGS 0 ?do
      i TAG-SORT$ sa su STR= if
         ARM-N @ 0 > if s"  | " +$ then
         i TAG-PAT$ +$
         ARM-N @ 1+ ARM-N !
      then
   loop
   ARM-N @ 0= if E-CMP-ROW throw then ;

: EMIT-TAG-COMPLETE ( -- )
   s" Definition ty_known (t : ty) : bool :=" +$ +NL
   s"   match t with" +$ +NL
   s"   | " +$ s" ty" +TAG-ARMS s"  => true" +$ +NL
   s"   end." +$ +NL
   s" Definition stack_known (x : stack) : bool :=" +$ +NL
   s"   match x with" +$ +NL
   s"   | " +$ s" stack" +TAG-ARMS s"  => true" +$ +NL
   s"   end." +$ +NL
   s" Example term_tags_are_exactly_the_frozen_table :" +$ +NL
   s"   (forall t : ty, ty_known t = true) /\ (forall x : stack, stack_known x = true)." +$ +NL
   s" Proof. split; [ destruct t | destruct x ]; reflexivity. Qed." +$ +NL ;

\ Two spellings may name one constructor - `do` and `?do` both run `CF-DO` and
\ both are `TDo` - so a constructor already written out is not written again;
\ Rocq refuses a duplicated pattern in one match.
: CON-ALREADY? ( n -- bool ) {: k:n :}
   k 0 ?do
      i CFT-CON$ k CFT-CON$ STR= if true unloop exit then
   loop
   false ;

: EMIT-TOK-COMPLETE ( -- )
   s" Definition tok_known (t : tok) : bool :=" +$ +NL
   s"   match t with" +$ +NL
   s"   | " +$
   0 ARM-N !
   CONTROLS 0 ?do
      i CON-ALREADY? 0= if
         ARM-N @ 0 > if s"  | " +$ then
         i CFT-CON$ +$
         ARM-N @ 1+ ARM-N !
      then
   loop
   OFF-CONS 0 ?do s"  | " +$ i OFF-CON$ +$ loop
   s"  => true" +$ +NL
   s"   end." +$ +NL
   s" Example control_tokens_are_exactly_the_frozen_table :" +$ +NL
   s"   forall t : tok, tok_known t = true." +$ +NL
   s" Proof. destruct t; reflexivity. Qed." +$ +NL ;

\ ---- 3. the control frame kinds ----------------------------------------------

: EMIT-FRAME-HELPER ( -- )
   s" Definition top_kind (s : st) : nat :=" +$ +NL
   s"   match st_cfs s with [] => 0 | f :: _ => fr_knd f end." +$ +NL ;

: EMIT-FRAME-ROW ( n -- ) {: k:n :}
   s" Example frame_kind_" +$ k FRK-KIND@ +N s"  :" +$ +NL
   s"   top_kind (run (" +$ k FRK-CFG$ +$ s" ) (init (" +$ k FRK-CFG$ +$
      s" )) " +$ k FRK-TOKS$ +$ s" ) = " +$ k FRK-KIND@ +N s" ." +$ +NL
   s" Proof. vm_compute; reflexivity. Qed." +$ +NL ;

: EMIT-FRAMES ( -- )
   EMIT-FRAME-HELPER
   FRAMES 0 ?do i EMIT-FRAME-ROW loop ;

\ ---- 4. the shared program vectors -------------------------------------------

: EMIT-VECTOR-ROW ( n -- ) {: k:n :}
   s" Example vector_" +$ k VEC-NAME$ +$ s"  :" +$ +NL
   s"   check_ctl (" +$ k VEC-CFG$ +$ s" ) " +$ k VEC-TOKS$ +$
      s"  = " +$ k VEC-VERD@ VERDICT-NAME$ +$ s" ." +$ +NL
   s" Proof. vm_compute; reflexivity. Qed." +$ +NL ;

: EMIT-VECTORS ( -- )
   VECTORS 0 ?do i EMIT-VECTOR-ROW loop ;

public

: START ( -- )
   0 V-U !
   0 PIN-N !
   EMIT-HEAD
   EMIT-VOCAB
   EMIT-CON-COMPLETE
   EMIT-TAG-COMPLETE
   EMIT-TOK-COMPLETE
   EMIT-FRAMES
   EMIT-VECTORS ;

\ One statement from the committed manifest, pinned to what the manifest says it
\ states. The manifest's `type` row is written out as the ascribed type of a
\ definition whose body is the result itself, so Rocq's own type checker has to
\ accept the proved statement as that type. It accepts up to conversion, which
\ is the honest question to ask: a renamed bound variable is not a change, and a
\ weaker, stronger, or trivial statement is. The type comes from the manifest and
\ never from a model, so editing a model alone cannot also move the target. A
\ definition is silent on success, so this adds nothing to the output the gate
\ reads the assumption set back out of.
: STATEMENT+ ( ptr u8 n ptr u8 n -- )
   {: name:ptr nameu:n type:ptr typeu:n :}
   s" Definition pinned_statement_" +$ PIN-N @ +N s"  : " +$
   type typeu +$
   s"  := @" +$ name nameu +$ s" ." +$ +NL
   PIN-N @ 1+ PIN-N ! ;

\ One statement from the committed manifest: a printed marker so the observed
\ output can be attributed, then the assumption query itself. A name Rocq cannot
\ resolve stops the whole run, so a manifest row for a result that no longer
\ exists fails the gate rather than being skipped.
: ASSUMPTION+ ( ptr u8 n -- ) {: a:ptr u:n :}
   s" Goal True. idtac " +$ DQ +C s" == theorem " +$ a u +$ DQ +C
      s" . Abort." +$ +NL
   s" Print Assumptions " +$ a u +$ s" ." +$ +NL ;

: TEXT$ ( -- ptr u8 n )
   V-BUF V-U @ ;

;using
;package
