require lib/test.f
require src/habu/code-span.f

package CODE-SPAN-TEST

: RUN ( -- )
   T-RESET
   s" legacy final slots and explicit complete spans" T-LABEL
   0 CODE-SPAN:BYTES 4 T=
   12 CODE-SPAN:BYTES 16 T=
   16 CODE-SPAN:EXACT dup CODE-SPAN:BODY 16 T=
   CODE-SPAN:BYTES 16 T=
   s" malformed encoded lengths refuse before code reads" T-LABEL
   -1 CODE-SPAN:VALID? TFALSE
   $100000000 CODE-SPAN:VALID? TFALSE
   CODE-SPAN:FULL CODE-SPAN:VALID? TFALSE
   $80000003 CODE-SPAN:VALID? TFALSE
   $80000004 CODE-SPAN:VALID? TTRUE
   s" exact publication accepts sizes, never an already encoded length" T-LABEL
   -1 CODE-SPAN:SIZE? TFALSE
   0 CODE-SPAN:SIZE? TFALSE
   3 CODE-SPAN:SIZE? TFALSE
   4 CODE-SPAN:SIZE? TTRUE
   CODE-SPAN:MASK 3 - CODE-SPAN:SIZE? TTRUE
   CODE-SPAN:MASK CODE-SPAN:SIZE? TFALSE
   CODE-SPAN:FULL CODE-SPAN:SIZE? TFALSE
   CODE-SPAN:FULL 4 + CODE-SPAN:SIZE? TFALSE
   $100000000 CODE-SPAN:SIZE? TFALSE
   4 CODE-SPAN:EXACT $80000004 T=
   CODE-SPAN:MASK 3 - CODE-SPAN:EXACT $FFFFFFFC T=
   T-REPORT ;

' RUN
;package
execute
