\ insn-obligations.f - the Rocq obligation text the instruction gate proves.
\
\ The module lives in `package COMPILER-INSN-ROCQ`. It writes one Rocq source
\ out of live state: the instruction rows frozen in `package
\ COMPILER-INSN-PROOF` and the theorem names and statements in the committed
\ manifest. Nothing in it is transcribed.
\
\ Why the obligations are generated rather than written by hand. A hand-written
\ Rocq companion would be a second copy of the vectors, and two copies drift.
\ Here the Habu side and the Rocq side read the one artifact:
\ `test/compiler/insn-cases.f` drives each row through the real emitter words
\ and reads the word back out of the code buffer, and the very same row is
\ turned into a Rocq obligation about `Habu.Common.Insn`. Change a row and both
\ sides are asked the new question; delete one and both sides stop asking.
\
\ How a row becomes an obligation:
\
\   - an encoding row asks that the model encodes those operands to that exact
\     word, and that the operands are well formed. The Habu side asks the
\     shipped emitter for the same word, so a disagreement between the model
\     and the assembler shows up as one side refusing;
\   - an out-of-range row asks that the operands are NOT well formed. The Habu
\     side runs the same row through the shipped mnemonic in a child engine and
\     requires it to be refused, so the pair says the two bounds are the same
\     bound: loosen it in the model and this obligation fails, loosen it in the
\     assembler and the child emits instead of dying;
\   - a reserved-register row asks whether the model says that operand slot is
\     checked, against what the shipped code actually did with x18 in it.
\
\ Statements, not just names. Asking Rocq what a theorem assumes says nothing
\ about what it says, so every theorem the manifest binds is also written out as
\ `Definition pinned_statement_<k> : <manifest type row> := @<theorem name>.`
\ The ascribed type is the manifest's copy of the statement, so a proof
\ rewritten to state something weaker no longer type-checks at the type the
\ committed manifest asks for, and Rocq refuses the generated file.
\
\ Consumer: `test/compiler/insn-proof.f`.

require lib/prelude.f
require lib/errors.f
require lib/string.f
require lib/fmt.f
require test/compiler/insn-schema.f

package COMPILER-INSN-ROCQ
using COMPILER-INSN-PROOF
private

$20000 constant V-CAP
$0A constant LF
$22 constant DQ

create V-BUF V-CAP allot

variable V-U
variable PIN-N

\ ---- emit buffer -------------------------------------------------------------

: +$ ( ptr u8 n -- ) {: a:ptr u:n :}
   V-U @ u + V-CAP > if E-STR-CAPACITY throw then
   a V-BUF V-U @ + u BYTE-COPY
   V-U @ u + V-U ! ;

: +C ( n -- ) {: c:n :}
   V-U @ 1+ V-CAP > if E-STR-CAPACITY throw then
   c V-BUF V-U @ + c!
   V-U @ 1+ V-U ! ;

: +NL ( -- )
   LF +C ;

: +N ( n -- )
   SB-RESET FMT:SB-INT SB$ +$ ;

\ A negative operand has to be parenthesised where it is applied, or Rocq reads
\ the minus as the subtraction that separates two arguments.
: +OPERAND ( n -- ) {: v:n :}
   v 0 < if s" (" +$ v +N s" )" +$ exit then
   v +N ;

\ ---- preamble ----------------------------------------------------------------
\ The same imports the model itself opens, with the model imported last and the
\ integer scope opened, so a name and a numeral in a manifest row mean here
\ exactly what they meant where Rocq printed them.

: EMIT-HEAD ( -- )
   s" (* Generated by test/compiler/insn-proof.f from the shared instruction" +$ +NL
   s"    rows and the committed manifest. A build output: never committed. *)" +$ +NL
   s" From Stdlib Require Import ZArith Bool List Lia Btauto." +$ +NL
   s" Import ListNotations." +$ +NL
   s" From Habu.Common Require Import Insn." +$ +NL
   s" Set Printing Width 200." +$ +NL
   s" Local Open Scope Z_scope." +$ +NL ;

\ ---- one instruction ---------------------------------------------------------

: +INSN ( n n n n -- ) {: form:n a:n b:n c:n :}
   s" (" +$ form FORM-NAME$ +$
   form FORM-ARITY {: n:n :}
   n 0 > if s"  " +$ a +OPERAND then
   n 1 > if s"  " +$ b +OPERAND then
   n 2 > if s"  " +$ c +OPERAND then
   s" )" +$ ;

\ ---- the encoding rows -------------------------------------------------------

: EMIT-VECTOR ( n -- ) {: r:n :}
   s" Example enc_" +$ r ROW-FORM@ FORM-NAME$ +$ s" _" +$ r +N s"  :" +$ +NL
   s"   enc " +$ r ROW-FORM@ r ROW-A@ r ROW-B@ r ROW-C@ +INSN
   s"  = " +$ r ROW-WORD@ +N +NL
   s"   /\ wf " +$ r ROW-FORM@ r ROW-A@ r ROW-B@ r ROW-C@ +INSN
   s"  = true." +$ +NL
   s" Proof. split; vm_compute; reflexivity. Qed." +$ +NL ;

\ ---- the out-of-range rows ---------------------------------------------------
\ The shipped code refuses the row; the model has to agree that the operands
\ are not well formed. A bound loosened on either side breaks the pair.

: EMIT-OUT-OF-RANGE ( n -- ) {: r:n :}
   s" Example out_of_range_" +$ r OOR-FORM@ FORM-NAME$ +$ s" _" +$ r +N s"  :" +$ +NL
   s"   wf " +$ r OOR-FORM@ r OOR-A@ r OOR-B@ r OOR-C@ +INSN
   s"  = false." +$ +NL
   s" Proof. vm_compute. reflexivity. Qed." +$ +NL ;

\ ---- the reserved-register rows ----------------------------------------------
\ Exit code 72 is the shipped refusal; anything else is a slot no check reaches.

: EMIT-RESERVED ( n -- ) {: r:n :}
   s" Example reserved_" +$ r RES-FORM@ FORM-NAME$ +$ s" _" +$ r +N s"  :" +$ +NL
   s"   refused " +$ r RES-FORM@ r RES-A@ r RES-B@ r RES-C@ +INSN
   s"  = " +$
   r RES-RC@ RESERVED-RC = if s" true" +$ else s" false" +$ then
   s" ." +$ +NL
   s" Proof. vm_compute. reflexivity. Qed." +$ +NL ;

: EMIT-ROWS ( -- )
   VECTORS 0 ?do i EMIT-VECTOR loop
   OUT-OF-RANGES 0 ?do i EMIT-OUT-OF-RANGE loop
   RESERVEDS 0 ?do i EMIT-RESERVED loop ;

public

: START ( -- )
   0 V-U !
   0 PIN-N !
   EMIT-HEAD
   EMIT-ROWS ;

\ One theorem from the committed manifest, pinned to the statement the manifest
\ says it makes. The manifest's `type` row is written out as the ascribed type
\ of a definition whose body is the theorem itself, so Rocq's own type checker
\ has to accept the proved statement as that type. The type comes from the
\ manifest and never from the proof file, so editing the proof file alone
\ cannot also move the target. A definition is silent on success, so this adds
\ nothing to the output the gate reads the assumption set back out of.
: STATEMENT+ ( ptr u8 n ptr u8 n -- )
   {: name:ptr nameu:n type:ptr typeu:n :}
   s" Definition pinned_statement_" +$ PIN-N @ +N s"  : " +$
   type typeu +$
   s"  := @" +$ name nameu +$ s" ." +$ +NL
   PIN-N @ 1+ PIN-N ! ;

\ One theorem from the committed manifest: a printed marker so the observed
\ output can be attributed, then the assumption query itself. A name Rocq cannot
\ resolve stops the whole run, so a manifest row for a theorem that no longer
\ exists fails the gate rather than being skipped.
: ASSUMPTION+ ( ptr u8 n -- ) {: a:ptr u:n :}
   s" Goal True. idtac " +$ DQ +C s" == theorem " +$ a u +$ DQ +C
      s" . Abort." +$ +NL
   s" Print Assumptions " +$ a u +$ s" ." +$ +NL ;

: TEXT$ ( -- ptr u8 n )
   V-BUF V-U @ ;

;using
;package
