\ ir-id-obligations.f - the Rocq obligation text the parity gate makes Rocq prove.
\
\ The module lives in `package COMPILER-ID-ROCQ`. It writes one Rocq source out
\ of live state: the frozen schema in `package COMPILER-ID-PROOF`, the constants
\ read structurally out of `src/compiler/ir/id.f`, and the theorem names in the
\ committed external-axiom manifest. Nothing in it is transcribed.
\
\ Why the obligations are generated rather than written by hand. A hand-written
\ Rocq companion would be a second copy of the vectors, and two copies drift.
\ Here the Habu side and the Rocq side read the one artifact: Habu runs each row
\ through the public `IR-ID` words, and the very same row is turned into a Rocq
\ obligation about `Habu.Common.Ids`. Delete a row, weaken a row, move a bound,
\ or change a Habu constant and the two sides are asked different questions, so
\ one of them refuses.
\
\ Diagnostic class, not just decision. A rejected row does not merely assert that
\ Rocq says no. It names the predicate that says no - the local domain for an
\ index-range row, the scalar domain for a bound, the owner equality for a
\ foreign owner, the strict bound for an off-by-one - so the Habu error code and
\ the Rocq conjunct that fails are bound to each other row by row.
\
\ Statements, not just names. Asking Rocq what a theorem assumes says nothing
\ about what it says, so every theorem the manifest binds is also written out as
\ `Definition pinned_statement_<k> : <manifest type row> := <theorem name>.` The
\ ascribed type is the manifest's copy of the statement, so a proof file that has
\ been rewritten to state something weaker no longer type-checks at the type the
\ committed manifest asks for, and Rocq refuses the generated file.
\
\ Two places where the two sides are genuinely not the same shape, both stated
\ here rather than smoothed over:
\
\   - Rocq's `owner` is an arithmetic shift and Habu's `OWNER-N` is a logical
\     one. They disagree on negative cells. The frozen discriminator cell is
\     emitted with both readings, the fact that the readings differ, and the
\     fact that both land outside the valid serial domain; two lemmas then
\     confine the disagreement to cells `packed_validb` already rejects, which
\     is the whole domain the projections are ever applied to.
\   - Rocq answers exhaustion with an `Exhausted` value and Habu throws
\     `E-IR-MODULE-EXHAUSTED`. That is a decision-to-diagnostic mapping. The
\     Rocq side pins the guard-before-add and the unchanged cell; the Habu side
\     is pinned structurally, because 2^31-1 serials cannot be spent in a test.
\
\ Consumer: `test/compiler/ir-id-proof.f`.

require lib/prelude.f
require lib/errors.f
require lib/string.f
require lib/fmt.f
require test/compiler/ir-id-schema.f
require test/compiler/ir-id-source.f

package COMPILER-ID-ROCQ
using COMPILER-ID-PROOF
private

$20000 constant V-CAP
$0A constant LF
$22 constant DQ

create V-BUF V-CAP allot

variable V-U
variable PIN-N
variable SRC-SERIAL-MAX
variable SRC-LOCAL-MAX
variable SRC-LOCAL-BITS
variable SRC-INIT

\ ---- emit buffer -------------------------------------------------------------

: +$ ( ptr u8 n -- ) {: a:ptr u:n :}
   V-U @ u + V-CAP > if E-STR-CAPACITY throw then
   a V-BUF V-U @ + u BYTE-COPY
   V-U @ u + V-U ! ;

: +C ( n -- ) {: c:n :}
   V-U @ 1+ V-CAP > if E-STR-CAPACITY throw then
   c V-BUF V-U @ + c!
   V-U @ 1+ V-U ! ;

: +NL ( -- )
   LF +C ;

\ A negative Rocq numeral needs parentheses wherever it stands as an argument,
\ so every emitted number carries them exactly when it is negative.
: +N ( n -- ) {: v:n :}
   v 0 < if s" (" +$ then
   SB-RESET v FMT:SB-INT SB$ +$
   v 0 < if s" )" +$ then ;

: +RAW ( n n -- ) {: serial:n local:n :}
   s" (Ids.pack " +$ serial +N s"  " +$ local +N s" )" +$ ;

: QED ( -- )
   s" Proof. repeat split; vm_compute; reflexivity. Qed." +$ +NL ;

: ROW-LABEL ( ptr u8 n n n -- ) {: a:ptr u:n idx:n w:n :}
   s" Example " +$ a u +$ s" _" +$ idx +N s" _w" +$ w +N s"  :" +$ +NL ;

\ ---- preamble ----------------------------------------------------------------

: EMIT-HEAD ( -- )
   s" (* Generated by test/compiler/ir-id-proof.f from the frozen identity" +$ +NL
   s"    schema and the production source. A build output: never committed. *)" +$ +NL
   s" (* schema digest " +$ DIGEST-HEX$ +$ s"  *)" +$ +NL
   s" From Stdlib Require Import Bool Lia ZArith List Sorting.Sorted." +$ +NL
   s" From Habu.Common Require Import Ids IdAllocator IdLaws IdAllocatorLaws." +$ +NL
   s" Import ListNotations." +$ +NL
   s" Open Scope Z_scope." +$ +NL
   s" Open Scope bool_scope." +$ +NL
   s" Set Printing Width 200." +$ +NL ;

: EMIT-DECIDERS ( -- )
   s" Definition owner_logical (raw : Z) : Z :=" +$ +NL
   s"   Z.shiftr (Z.land raw 18446744073709551615) 32." +$ +NL
   s" Definition pack_decides (serial idx : Z) : bool :=" +$ +NL
   s"   match Ids.try_pack serial idx with Some _ => true | None => false end." +$ +NL
   s" Definition count_decides (value : Z) : bool :=" +$ +NL
   s"   match Ids.make_count value with Some _ => true | None => false end." +$ +NL
   s" Definition pool_decides (value : Z) : bool :=" +$ +NL
   s"   match Ids.make_pool_offset value with Some _ => true | None => false end." +$ +NL ;

\ ---- constants ---------------------------------------------------------------

: WIDTH-ROW ( ptr u8 n ptr u8 n n -- )
   {: label:ptr labelu:n name:ptr nameu:n value:n :}
   s" Example " +$ label labelu +$ s" : Ids." +$ name nameu +$ s"  = " +$
      value +N s" ." +$ +NL
   QED ;

\ Every width and bound the schema froze, asked of the Rocq model. A schema byte
\ that moves one of these changes what Rocq is asked, so the frozen digest and
\ the model cannot drift apart.
: EMIT-SCHEMA-CONSTANTS ( -- )
   s" schema_cell_bits" s" cell_bits" CELL-BITS WIDTH-ROW
   s" schema_cell_value_bits" s" cell_value_bits" CELL-VALUE-BITS WIDTH-ROW
   s" schema_serial_bits" s" serial_bits" SERIAL-BITS WIDTH-ROW
   s" schema_local_bits" s" local_bits" LOCAL-BITS WIDTH-ROW
   s" schema_local_shift" s" local_shift" LOCAL-SHIFT WIDTH-ROW
   s" schema_cell_min" s" cell_min" CELL-MIN WIDTH-ROW
   s" schema_cell_max" s" cell_max" CELL-MAX WIDTH-ROW
   s" schema_serial_min" s" serial_min" SERIAL-MIN WIDTH-ROW
   s" schema_serial_max" s" serial_max" SERIAL-MAX WIDTH-ROW
   s" schema_local_min" s" local_min" LOCAL-MIN WIDTH-ROW
   s" schema_local_max" s" local_max" LOCAL-MAX WIDTH-ROW
   s" schema_local_mask" s" local_mask" LOCAL-MASK WIDTH-ROW
   s" Example schema_scalar_domain :" +$ +NL
   s"   Ids.scalar_validb " +$ SCALAR-MIN +N s"  = true" +$ +NL
   s"   /\ Ids.scalar_validb " +$ SCALAR-MAX +N s"  = true" +$ +NL
   s"   /\ Ids.scalar_validb " +$ SCALAR-MIN 1- +N s"  = false" +$ +NL
   s"   /\ Ids.scalar_validb " +$ SCALAR-MAX 1+ +N s"  = false." +$ +NL
   QED ;

\ The three constants and the initial allocator value the production source
\ actually carries, read structurally out of it. Change `$7FFFFFFF` in
\ `src/compiler/ir/id.f` and Rocq is asked to prove `serial_max` equals the new
\ number, which it will refuse.
: EMIT-SOURCE-CONSTANTS ( -- )
   s" habu_module_max" s" serial_max" SRC-SERIAL-MAX @ WIDTH-ROW
   s" habu_local_max" s" local_max" SRC-LOCAL-MAX @ WIDTH-ROW
   s" habu_local_bits" s" local_shift" SRC-LOCAL-BITS @ WIDTH-ROW
   s" Example habu_next_serial_initial :" +$ +NL
   s"   IdAllocator.cell_ok (IdAllocator.Cell 0 " +$ SRC-INIT @ +N s" ) = true" +$ +NL
   s"   /\ IdAllocator.serial_ok " +$ SRC-INIT @ +N s"  = false" +$ +NL
   s"   /\ IdAllocator.next_serial " +$ SRC-INIT @ +N s"  = Some " +$
      SRC-INIT @ 1+ +N s" ." +$ +NL
   QED ;

\ ---- witnesses ---------------------------------------------------------------

\ Habu mints its module serials from a process-wide counter the test cannot
\ choose, so each row is asked at both ends of the serial domain instead of at
\ one arbitrary point.
: WITNESS-SERIAL ( n -- n ) {: w:n :}
   w 0= if SERIAL-MIN exit then
   SERIAL-MAX ;

: WITNESS-OTHER ( n -- n ) {: w:n :}
   w 0= if SERIAL-MIN 1+ exit then
   SERIAL-MAX 1- ;

\ ---- pack vectors ------------------------------------------------------------

: PACK-ACCEPT ( n n -- ) {: serial:n local:n :}
   s"   Ids.local_validb " +$ local +N s"  = true" +$ +NL
   s"   /\ pack_decides " +$ serial +N s"  " +$ local +N s"  = true" +$ +NL
   s"   /\ Ids.packed_validb " +$ serial local +RAW s"  = true" +$ +NL
   s"   /\ Ids.owner " +$ serial local +RAW s"  = " +$ serial +N +NL
   s"   /\ Ids.local " +$ serial local +RAW s"  = " +$ local +N s" ." +$ +NL ;

: PACK-REJECT ( n n -- ) {: serial:n local:n :}
   s"   Ids.local_validb " +$ local +N s"  = false" +$ +NL
   s"   /\ pack_decides " +$ serial +N s"  " +$ local +N s"  = false." +$ +NL ;

: PACK-ROW ( n n -- ) {: idx:n w:n :}
   w WITNESS-SERIAL {: serial:n :}
   idx PACK-LOCAL {: local:n :}
   s" pack_row" idx w ROW-LABEL
   idx PACK-CLASS 0= if
      serial local PACK-ACCEPT
   else
      idx PACK-CLASS E-IR-INDEX-RANGE <> if E-CID-ROW throw then
      serial local PACK-REJECT
   then
   QED ;

: EMIT-PACK-AT ( n -- ) {: w:n :}
   PACK-ROWS 0 ?do i w PACK-ROW loop ;

: EMIT-PACK-VECTORS ( -- )
   0 EMIT-PACK-AT
   1 EMIT-PACK-AT ;

\ ---- check vectors -----------------------------------------------------------

: CHECK-ACCEPT ( n n n n -- ) {: expect:n packer:n local:n bound:n :}
   s"   Ids.scalar_validb " +$ bound +N s"  = true" +$ +NL
   s"   /\ Ids.packed_validb " +$ packer local +RAW s"  = true" +$ +NL
   s"   /\ Z.eqb (Ids.owner " +$ packer local +RAW s" ) " +$ expect +N
      s"  = true" +$ +NL
   s"   /\ Z.ltb (Ids.local " +$ packer local +RAW s" ) " +$ bound +N
      s"  = true" +$ +NL
   s"   /\ Ids.checkb " +$ expect +N s"  " +$ bound +N s"  " +$
      packer local +RAW s"  = true." +$ +NL ;

: CHECK-BOUND-REJECT ( n n n n -- ) {: expect:n packer:n local:n bound:n :}
   s"   Ids.scalar_validb " +$ bound +N s"  = true" +$ +NL
   s"   /\ Ids.packed_validb " +$ packer local +RAW s"  = true" +$ +NL
   s"   /\ Z.eqb (Ids.owner " +$ packer local +RAW s" ) " +$ expect +N
      s"  = true" +$ +NL
   s"   /\ Z.ltb (Ids.local " +$ packer local +RAW s" ) " +$ bound +N
      s"  = false" +$ +NL
   s"   /\ Ids.checkb " +$ expect +N s"  " +$ bound +N s"  " +$
      packer local +RAW s"  = false." +$ +NL ;

: CHECK-OWNER-REJECT ( n n n n -- ) {: expect:n packer:n local:n bound:n :}
   s"   Ids.scalar_validb " +$ bound +N s"  = true" +$ +NL
   s"   /\ Ids.packed_validb " +$ packer local +RAW s"  = true" +$ +NL
   s"   /\ Z.eqb (Ids.owner " +$ packer local +RAW s" ) " +$ expect +N
      s"  = false" +$ +NL
   s"   /\ Ids.checkb " +$ expect +N s"  " +$ bound +N s"  " +$
      packer local +RAW s"  = false." +$ +NL ;

: CHECK-SCALAR-REJECT ( n n n n -- ) {: expect:n packer:n local:n bound:n :}
   s"   Ids.scalar_validb " +$ bound +N s"  = false" +$ +NL
   s"   /\ Ids.checkb " +$ expect +N s"  " +$ bound +N s"  " +$
      packer local +RAW s"  = false." +$ +NL ;

: CHECK-BODY ( n n n n n -- ) {: expect:n packer:n local:n bound:n class:n :}
   class 0= if expect packer local bound CHECK-ACCEPT exit then
   class E-IR-INDEX-BOUND = if
      expect packer local bound CHECK-BOUND-REJECT exit
   then
   class E-IR-OWNER = if
      expect packer local bound CHECK-OWNER-REJECT exit
   then
   class E-IR-SCALAR-RANGE <> if E-CID-ROW throw then
   expect packer local bound CHECK-SCALAR-REJECT ;

: CHECK-ROW ( n n -- ) {: idx:n w:n :}
   w WITNESS-SERIAL {: expect:n :}
   idx CHECK-OWNER OWNER-OTHER =
   if w WITNESS-OTHER else w WITNESS-SERIAL then {: packer:n :}
   s" check_row" idx w ROW-LABEL
   expect packer idx CHECK-LOCAL idx CHECK-BOUND idx CHECK-CLASS CHECK-BODY
   QED ;

: EMIT-CHECK-AT ( n -- ) {: w:n :}
   CHECK-ROWS 0 ?do i w CHECK-ROW loop ;

: EMIT-CHECK-VECTORS ( -- )
   0 EMIT-CHECK-AT
   1 EMIT-CHECK-AT ;

\ ---- scalar vectors ----------------------------------------------------------

\ An accepted scalar must come back whole. For a value that carries bits above
\ the local field, the two projections are also asked to differ from it, which
\ is what tells a plain number apart from a packed identity.
: SCALAR-ACCEPT ( n -- ) {: value:n :}
   s"   Ids.scalar_validb " +$ value +N s"  = true" +$ +NL
   s"   /\ count_decides " +$ value +N s"  = true" +$ +NL
   s"   /\ pool_decides " +$ value +N s"  = true" +$ +NL
   s"   /\ Ids.count_raw (Ids.MkCount " +$ value +N s" ) = " +$ value +N +NL
   s"   /\ Ids.pool_offset_raw (Ids.MkPoolOffset " +$ value +N s" ) = " +$
      value +N +NL
   value LOCAL-SHIFT rshift 0 <> if
      s"   /\ Z.eqb (Ids.local " +$ value +N s" ) " +$ value +N s"  = false" +$ +NL
      s"   /\ Z.eqb (Ids.owner " +$ value +N s" ) " +$ value +N s"  = false" +$ +NL
   then
   s"   ." +$ +NL ;

: SCALAR-REJECT ( n -- ) {: value:n :}
   s"   Ids.scalar_validb " +$ value +N s"  = false" +$ +NL
   s"   /\ count_decides " +$ value +N s"  = false" +$ +NL
   s"   /\ pool_decides " +$ value +N s"  = false." +$ +NL ;

: SCALAR-ROW ( n -- ) {: idx:n :}
   s" scalar_row" idx 0 ROW-LABEL
   idx SCALAR-CLASS 0= if
      idx SCALAR-VALUE SCALAR-ACCEPT
   else
      idx SCALAR-CLASS E-IR-SCALAR-RANGE <> if E-CID-ROW throw then
      idx SCALAR-VALUE SCALAR-REJECT
   then
   QED ;

: EMIT-SCALAR-VECTORS ( -- )
   SCALAR-ROWS 0 ?do i SCALAR-ROW loop ;

\ ---- the one place the two projections disagree ------------------------------

: EMIT-SHIFT-LEMMAS ( -- )
   s" Lemma reachable_nonneg :" +$ +NL
   s"   forall raw, Ids.packed_validb raw = true -> 0 <= raw <= Ids.cell_max." +$ +NL
   s" Proof." +$ +NL
   s"   intros raw Hvalid." +$ +NL
   s"   rewrite <- (IdLaws.projection_pack_roundtrip raw Hvalid)." +$ +NL
   s"   unfold Ids.packed_validb in Hvalid." +$ +NL
   s"   apply Bool.andb_true_iff in Hvalid as [Hprefix Hlocal]." +$ +NL
   s"   apply Bool.andb_true_iff in Hprefix as [_ Hserial]." +$ +NL
   s"   apply IdLaws.pack_within_signed_cell; assumption." +$ +NL
   s" Qed." +$ +NL
   s" Lemma reachable_owner_readings_agree :" +$ +NL
   s"   forall raw," +$ +NL
   s"     Ids.packed_validb raw = true -> owner_logical raw = Ids.owner raw." +$ +NL
   s" Proof." +$ +NL
   s"   intros raw Hvalid." +$ +NL
   s"   pose proof (reachable_nonneg raw Hvalid) as [Hlo Hhi]." +$ +NL
   s"   change (raw <= 9223372036854775807) in Hhi." +$ +NL
   s"   unfold owner_logical." +$ +NL
   s"   replace 18446744073709551615 with (Z.ones 64) by reflexivity." +$ +NL
   s"   rewrite Z.land_ones by lia." +$ +NL
   s"   rewrite Z.mod_small by lia." +$ +NL
   s"   reflexivity." +$ +NL
   s" Qed." +$ +NL ;

\ The frozen discriminator cell: bit 63 set, so the arithmetic shift the model
\ uses and the logical shift the engine uses read different owners out of it.
\ Both readings leave the valid serial domain, so both sides reject; the reading
\ that differs is recorded rather than hidden, and the lemmas above show the
\ disagreement cannot occur on a cell the packer can produce.
\ The model shifts arithmetically; the engine shifts logically. On a 64-bit
\ two's-complement cell the two readings differ by exactly one whole local field
\ on a negative cell and not at all on a non-negative one, so the model's reading
\ is derived from the engine's rather than restated.
: ARITH-OWNER ( n -- n ) {: v:n :}
   v LOCAL-SHIFT rshift {: hi:n :}
   v 0 < if hi LOCAL-MASK 1+ - exit then
   hi ;

: EMIT-DISCRIMINATOR ( -- )
   LOCAL-MASK LOCAL-SHIFT lshift 5 or {: cell:n :}
   s" Example discriminator_owner_readings :" +$ +NL
   s"   Ids.packed_validb " +$ cell +N s"  = false" +$ +NL
   s"   /\ Ids.owner " +$ cell +N s"  = " +$ cell ARITH-OWNER +N +NL
   s"   /\ owner_logical " +$ cell +N s"  = " +$ cell LOCAL-SHIFT rshift +N +NL
   s"   /\ Z.eqb (Ids.owner " +$ cell +N s" ) (owner_logical " +$ cell +N
      s" ) = false" +$ +NL
   s"   /\ Ids.serial_validb (Ids.owner " +$ cell +N s" ) = false" +$ +NL
   s"   /\ Ids.serial_validb (owner_logical " +$ cell +N s" ) = false" +$ +NL
   s"   /\ Ids.local_validb " +$ cell +N s"  = false" +$ +NL
   s"   /\ Ids.scalar_validb " +$ cell +N s"  = false." +$ +NL
   QED ;

\ ---- the allocator -----------------------------------------------------------

\ Habu answers exhaustion with a throw and Rocq answers with a value. These are
\ the Rocq half of that mapping: the guard runs before the addition, the cell is
\ left alone, a fresh cell issues, and a stale view retries without moving the
\ cell. The Habu half is the frozen `SERIAL-NEXT`, `TRY-SERIAL` and
\ `TAKE-SERIAL` bodies the gate reads out of the production source.
: EMIT-ALLOCATOR ( -- )
   s" Example allocator_guard_precedes_addition :" +$ +NL
   s"   IdAllocator.next_serial 0 = Some 1" +$ +NL
   s"   /\ IdAllocator.next_serial (Ids.serial_max - 1) = Some Ids.serial_max" +$ +NL
   s"   /\ IdAllocator.next_serial Ids.serial_max = None" +$ +NL
   s"   /\ IdAllocator.next_serial (-1) = None" +$ +NL
   s"   /\ IdAllocator.next_serial (Ids.serial_max + 1) = None." +$ +NL
   QED
   s" Example allocator_exhaustion_keeps_state :" +$ +NL
   s"   IdAllocator.pure_attempt (IdAllocator.Cell 3 Ids.serial_max) Ids.serial_max" +$ +NL
   s"     = (IdAllocator.Cell 3 Ids.serial_max, IdAllocator.Exhausted Ids.serial_max)." +$ +NL
   QED
   s" Example allocator_cas_issues :" +$ +NL
   s"   IdAllocator.cas (IdAllocator.Cell 3 0) 0 1" +$ +NL
   s"     = (IdAllocator.Cell 3 1, IdAllocator.CasOk 0 1)" +$ +NL
   s"   /\ IdAllocator.pure_attempt (IdAllocator.Cell 3 0) 0" +$ +NL
   s"     = (IdAllocator.Cell 3 1, IdAllocator.Issued 1)." +$ +NL
   QED
   s" Example allocator_stale_view_retries :" +$ +NL
   s"   IdAllocator.cas (IdAllocator.Cell 3 1) 0 1" +$ +NL
   s"     = (IdAllocator.Cell 3 1, IdAllocator.CasMiss 0 1)" +$ +NL
   s"   /\ IdAllocator.pure_attempt (IdAllocator.Cell 3 1) 0" +$ +NL
   s"     = (IdAllocator.Cell 3 1, IdAllocator.Retry 0 1)." +$ +NL
   QED
   s" Example allocator_cell_is_aligned :" +$ +NL
   s"   IdAllocator.cell_bytes = 8" +$ +NL
   s"   /\ IdAllocator.aligned (IdAllocator.Cell 9 0) = true." +$ +NL
   QED ;

\ ---- the type distinction ----------------------------------------------------

\ One `Fail` per Habu wrong-family candidate. `Fail` is itself the assertion: if
\ the model ever let a family stand in for another, the command would succeed
\ and Rocq would refuse the file.
: EMIT-WRONG-FAMILY ( -- )
   s" Fail Definition wrong_family_pack_source : option Ids.ir_fun_id :=" +$ +NL
   s"   Ids.pack_source (Ids.MkModuleKey 7) 42." +$ +NL
   s" Fail Definition wrong_family_pack_fun : option Ids.ir_source_id :=" +$ +NL
   s"   Ids.pack_fun (Ids.MkModuleKey 7) 42." +$ +NL
   s" Fail Definition wrong_family_owner : Ids.ir_count :=" +$ +NL
   s"   Ids.source_owner (Ids.MkSourceId (Ids.pack 7 42))." +$ +NL
   s" Fail Definition wrong_family_local : Z :=" +$ +NL
   s"   Ids.source_local (Ids.MkFunId (Ids.pack 7 42))." +$ +NL
   s" Fail Definition wrong_family_check : bool :=" +$ +NL
   s"   Ids.source_checkb (Ids.MkModuleKey 7) (Ids.MkCount 43)" +$ +NL
   s"     (Ids.MkFunId (Ids.pack 7 42))." +$ +NL ;

public

\ The three constants and the initial allocator value the gate read out of the
\ production source, in the order the source declares them.
: SOURCE-FACTS! ( n n n n -- )
   {: serial-max:n local-max:n local-bits:n init:n :}
   serial-max SRC-SERIAL-MAX !
   local-max SRC-LOCAL-MAX !
   local-bits SRC-LOCAL-BITS !
   init SRC-INIT ! ;

: START ( -- )
   0 V-U !
   0 PIN-N !
   EMIT-HEAD
   EMIT-DECIDERS
   EMIT-SCHEMA-CONSTANTS
   EMIT-SOURCE-CONSTANTS
   EMIT-PACK-VECTORS
   EMIT-CHECK-VECTORS
   EMIT-SCALAR-VECTORS
   EMIT-SHIFT-LEMMAS
   EMIT-DISCRIMINATOR
   EMIT-ALLOCATOR
   EMIT-WRONG-FAMILY ;

\ One theorem from the committed manifest, pinned to the statement the manifest
\ says it makes. The manifest's `type` row is written out as the ascribed type of
\ a definition whose body is the theorem itself, so Rocq's own type checker has
\ to accept the proved statement as that type. It accepts up to conversion, which
\ is the honest question to ask: a renamed bound variable is not a change, and a
\ weaker, stronger, or trivial statement is. The type comes from the manifest and
\ never from the proof file, so editing a proof file alone cannot also move the
\ target. A definition is silent on success, so this adds nothing to the output
\ the gate reads the assumption set back out of.
: STATEMENT+ ( ptr u8 n ptr u8 n -- )
   {: name:ptr nameu:n type:ptr typeu:n :}
   s" Definition pinned_statement_" +$ PIN-N @ +N s"  : " +$
   type typeu +$
   s"  := " +$ name nameu +$ s" ." +$ +NL
   PIN-N @ 1+ PIN-N ! ;

\ One theorem from the committed manifest: a printed marker so the observed
\ output can be attributed, then the assumption query itself. A name Rocq cannot
\ resolve stops the whole run, so a manifest row for a theorem that no longer
\ exists fails the gate rather than being skipped.
: ASSUMPTION+ ( ptr u8 n -- ) {: a:ptr u:n :}
   s" Goal True. idtac " +$ DQ +C s" == theorem " +$ a u +$ DQ +C
      s" . Abort." +$ +NL
   s" Print Assumptions " +$ a u +$ s" ." +$ +NL ;

: TEXT$ ( -- ptr u8 n )
   V-BUF V-U @ ;

;using
;package
