\ ir-id.f - checked shared compiler IR identity tests.

require src/compiler/ir/id.f
require lib/test.f
require test/checker-assert.f

package IR-RAW
private

: MODULE-RANGE-CASES ( -- )
   1 MINT-MODULE MODULE>N 1 T=
   $7FFFFFFF MINT-MODULE MODULE>N $7FFFFFFF T=
   [: 0 MINT-MODULE drop ;] E-IR-MODULE-ZERO TTHROWSQ
   [: -1 MINT-MODULE drop ;] E-IR-MODULE-RANGE TTHROWSQ
   [: $80000000 MINT-MODULE drop ;] E-IR-MODULE-RANGE TTHROWSQ ;

: SCALAR-CASES ( -- )
   0 MINT-COUNT COUNT>N 0 T=
   $7FFFFFFFFFFFFFFF MINT-COUNT COUNT>N $7FFFFFFFFFFFFFFF T=
   0 MINT-POOL-OFF POOL-OFF>N 0 T=
   $7FFFFFFFFFFFFFFF MINT-POOL-OFF POOL-OFF>N $7FFFFFFFFFFFFFFF T=
   [: $8000000000000000 MINT-COUNT drop ;]
      E-IR-SCALAR-RANGE TTHROWSQ
   [: $8000000000000000 MINT-POOL-OFF drop ;]
      E-IR-SCALAR-RANGE TTHROWSQ
   [: -1 MINT-COUNT drop ;] E-IR-SCALAR-RANGE TTHROWSQ
   [: -1 MINT-POOL-OFF drop ;] E-IR-SCALAR-RANGE TTHROWSQ ;

: SOURCE-CASE ( -- )
   1 MINT-MODULE 7 PACK-SOURCE
   dup SOURCE-LOCAL 7 T=
   dup SOURCE-OWNER MODULE>N 1 T=
   SOURCE>N $100000007 T= ;

: FUN-CASE ( -- )
   2 MINT-MODULE 8 PACK-FUN
   dup FUN-LOCAL 8 T=
   dup FUN-OWNER MODULE>N 2 T=
   FUN>N $200000008 T=
   2 MINT-MODULE 9 MINT-COUNT
      2 MINT-MODULE 8 PACK-FUN
      FUN-CHECK FUN>N $200000008 T= ;

: BLOCK-CASE ( -- )
   3 MINT-MODULE 9 PACK-BLOCK
   dup BLOCK-LOCAL 9 T=
   dup BLOCK-OWNER MODULE>N 3 T=
   BLOCK>N $300000009 T=
   3 MINT-MODULE 10 MINT-COUNT
      3 MINT-MODULE 9 PACK-BLOCK
      BLOCK-CHECK BLOCK>N $300000009 T= ;

: OP-CASE ( -- )
   4 MINT-MODULE 10 PACK-OP
   dup OP-LOCAL 10 T=
   dup OP-OWNER MODULE>N 4 T=
   OP>N $40000000A T=
   4 MINT-MODULE 11 MINT-COUNT
      4 MINT-MODULE 10 PACK-OP
      OP-CHECK OP>N $40000000A T= ;

: VALUE-CASE ( -- )
   5 MINT-MODULE 11 PACK-VALUE
   dup VALUE-LOCAL 11 T=
   dup VALUE-OWNER MODULE>N 5 T=
   VALUE>N $50000000B T=
   5 MINT-MODULE 12 MINT-COUNT
      5 MINT-MODULE 11 PACK-VALUE
      VALUE-CHECK VALUE>N $50000000B T= ;

: TYPE-CASE ( -- )
   6 MINT-MODULE 12 PACK-TYPE
   dup TYPE-LOCAL 12 T=
   dup TYPE-OWNER MODULE>N 6 T=
   TYPE>N $60000000C T=
   6 MINT-MODULE 13 MINT-COUNT
      6 MINT-MODULE 12 PACK-TYPE
      TYPE-CHECK TYPE>N $60000000C T= ;

: ATTR-CASE ( -- )
   7 MINT-MODULE 13 PACK-ATTR
   dup ATTR-LOCAL 13 T=
   dup ATTR-OWNER MODULE>N 7 T=
   ATTR>N $70000000D T=
   7 MINT-MODULE 14 MINT-COUNT
      7 MINT-MODULE 13 PACK-ATTR
      ATTR-CHECK ATTR>N $70000000D T= ;

: SYMBOL-CASE ( -- )
   8 MINT-MODULE 14 PACK-SYMBOL
   dup SYMBOL-LOCAL 14 T=
   dup SYMBOL-OWNER MODULE>N 8 T=
   SYMBOL>N $80000000E T=
   8 MINT-MODULE 15 MINT-COUNT
      8 MINT-MODULE 14 PACK-SYMBOL
      SYMBOL-CHECK SYMBOL>N $80000000E T= ;

: SPAN-CASE ( -- )
   9 MINT-MODULE 15 PACK-SPAN
   dup SPAN-LOCAL 15 T=
   dup SPAN-OWNER MODULE>N 9 T=
   SPAN>N $90000000F T=
   9 MINT-MODULE 16 MINT-COUNT
      9 MINT-MODULE 15 PACK-SPAN
      SPAN-CHECK SPAN>N $90000000F T= ;

: PACK-RANGE-CASES ( -- )
   $7FFFFFFF MINT-MODULE $FFFFFFFF PACK-SOURCE
      {: id:IR-ID:ir-source-id :}
   id SOURCE>N $7FFFFFFFFFFFFFFF T=
   id SOURCE-OWNER MODULE>N $7FFFFFFF T=
   id SOURCE-LOCAL $FFFFFFFF T=
   $7FFFFFFF MINT-MODULE $100000000 MINT-COUNT id
      SOURCE-CHECK SOURCE>N $7FFFFFFFFFFFFFFF T=
   1 MINT-MODULE $FFFFFFFF PACK-SOURCE SOURCE-LOCAL $FFFFFFFF T=
   [: 1 MINT-MODULE -1 PACK-SOURCE drop ;] E-IR-INDEX-RANGE TTHROWSQ
   [: 1 MINT-MODULE $100000000 PACK-SOURCE drop ;]
      E-IR-INDEX-RANGE TTHROWSQ ;

: CHECK-CASES ( -- )
   1 MINT-MODULE 8 MINT-COUNT
      1 MINT-MODULE 7 PACK-SOURCE SOURCE-CHECK SOURCE>N $100000007 T=
   [: 1 MINT-MODULE 7 MINT-COUNT
      1 MINT-MODULE 7 PACK-SOURCE SOURCE-CHECK drop ;]
      E-IR-INDEX-BOUND TTHROWSQ
   [: 2 MINT-MODULE 8 MINT-COUNT
      1 MINT-MODULE 7 PACK-SOURCE SOURCE-CHECK drop ;]
      E-IR-OWNER TTHROWSQ ;

: WRONG-FAMILY-CASES ( -- )
   s" IR-BAD-SRC ( IR-ID:ir-module-id n -- IR-ID:ir-fun-id ) PACK-SOURCE"
      CHECK-QUIET-CANDIDATE! 0 T=
   s" IR-BAD-FN ( IR-ID:ir-module-id n -- IR-ID:ir-source-id ) PACK-FUN"
      CHECK-QUIET-CANDIDATE! 0 T=
   s" IR-BAD-OWNER ( IR-ID:ir-source-id -- IR-ID:ir-count ) SOURCE-OWNER"
      CHECK-QUIET-CANDIDATE! 0 T=
   s" IR-BAD-LOCAL ( IR-ID:ir-fun-id -- n ) SOURCE-LOCAL"
      CHECK-QUIET-CANDIDATE! 0 T=
   s" IR-BAD-CHECK ( IR-ID:ir-module-id IR-ID:ir-count IR-ID:ir-fun-id -- IR-ID:ir-fun-id ) SOURCE-CHECK"
      CHECK-QUIET-CANDIDATE! 0 T=
   s" IR-BAD-BOUND ( IR-ID:ir-module-id IR-ID:ir-pool-offset IR-ID:ir-source-id -- IR-ID:ir-source-id ) SOURCE-CHECK"
      CHECK-QUIET-CANDIDATE! 0 T= ;

: RUN ( -- )
   T-RESET
   MODULE-RANGE-CASES
   SCALAR-CASES
   SOURCE-CASE
   FUN-CASE
   BLOCK-CASE
   OP-CASE
   VALUE-CASE
   TYPE-CASE
   ATTR-CASE
   SYMBOL-CASE
   SPAN-CASE
   PACK-RANGE-CASES
   CHECK-CASES
   WRONG-FAMILY-CASES
   T-REPORT ;

RUN

;package

package IR-ID-TEST
private

: ABSENT? ( ptr u8 n -- bool )
   XREF-FIND XREF-FOUND? 0= ;

: UNRESOLVED ( ptr u8 n -- )
   CHECK-QUIET-CANDIDATE! 1 T= ;

: PUBLIC-ABSENCE ( -- )
   s" IR-ID:MINT-MODULE" ABSENT? TTRUE
   s" IR:MINT-MODULE" ABSENT? TTRUE
   s" HIR:MINT-MODULE" ABSENT? TTRUE
   s" SIR:MINT-MODULE" ABSENT? TTRUE
   s" LIR:MINT-MODULE" ABSENT? TTRUE
   s" A64IR:MINT-MODULE" ABSENT? TTRUE
   s" GPU-RIR:MINT-MODULE" ABSENT? TTRUE
   s" GPU-KIR:MINT-MODULE" ABSENT? TTRUE
   s" GPU-GIR:MINT-MODULE" ABSENT? TTRUE
   s" GPU-PTXIR2:MINT-MODULE" ABSENT? TTRUE
   s" GPU-IR:MINT-MODULE" ABSENT? TTRUE
   s" IR-RAW:MINT-MODULE" ABSENT? TTRUE
   s" IR:PACK-SOURCE" ABSENT? TTRUE
   s" IR:SOURCE-OWNER" ABSENT? TTRUE
   s" IR:SOURCE-LOCAL" ABSENT? TTRUE
   s" IR:SOURCE-CHECK" ABSENT? TTRUE
   s" IR-NO-PUBLIC ( n -- IR-ID:ir-module-id ) IR-ID:MINT-MODULE" UNRESOLVED
   s" IR-NO-PUBLIC ( n -- IR-ID:ir-module-id ) IR:MINT-MODULE" UNRESOLVED
   s" IR-NO-PUBLIC ( n -- IR-ID:ir-module-id ) HIR:MINT-MODULE" UNRESOLVED
   s" IR-NO-PUBLIC ( n -- IR-ID:ir-module-id ) SIR:MINT-MODULE" UNRESOLVED
   s" IR-NO-PUBLIC ( n -- IR-ID:ir-module-id ) LIR:MINT-MODULE" UNRESOLVED
   s" IR-NO-PUBLIC ( n -- IR-ID:ir-module-id ) A64IR:MINT-MODULE" UNRESOLVED
   s" IR-NO-PUBLIC ( n -- IR-ID:ir-module-id ) GPU-RIR:MINT-MODULE" UNRESOLVED
   s" IR-NO-PUBLIC ( n -- IR-ID:ir-module-id ) GPU-KIR:MINT-MODULE" UNRESOLVED
   s" IR-NO-PUBLIC ( n -- IR-ID:ir-module-id ) GPU-GIR:MINT-MODULE" UNRESOLVED
   s" IR-NO-PUBLIC ( n -- IR-ID:ir-module-id ) GPU-PTXIR2:MINT-MODULE" UNRESOLVED
   s" IR-NO-PUBLIC ( n -- IR-ID:ir-module-id ) GPU-IR:MINT-MODULE" UNRESOLVED
   s" IR-NO-PUBLIC ( n -- IR-ID:ir-module-id ) IR-RAW:MINT-MODULE" UNRESOLVED ;

public

: RUN ( -- )
   T-RESET
   PUBLIC-ABSENCE
   T-REPORT ;

;package

IR-ID-TEST:RUN
