\ ir-intern-obligations.f - the Rocq obligation text the interning gate proves.
\
\ The module lives in `package COMPILER-INTERN-ROCQ`. It writes one Rocq source
\ out of live state: the intern sequences frozen in `package
\ COMPILER-INTERN-PROOF` and the theorem names and statements in the committed
\ manifest. Nothing in it is transcribed.
\
\ Why the obligations are generated rather than written by hand. A hand-written
\ Rocq companion would be a second copy of the sequences, and two copies drift.
\ Here the Habu side and the Rocq side read the one artifact:
\ `test/compiler/ir-intern-cases.f` runs each sequence through the real `IR-SYM`,
\ `IR-TYPE` and `IR-ATTR` words, and the very same sequence is turned into a Rocq
\ obligation about `Habu.Common.Interning`. Delete a sequence, weaken a step, or
\ move a ceiling and the two sides are asked different questions, so one refuses.
\
\ How a sequence becomes an obligation. The file defines one runner per key type
\ that folds the model's `intern` over a list of keys and collects what each step
\ answered together with the row count the table ends on. A step the shared row
\ marks accepted must answer `Some <the frozen ordinal>`, and a step it marks
\ rejected must answer `None` - which is the model's whole vocabulary for a
\ refusal, while Habu names a throw code. The row carries the throw code, so the
\ two sides stay bound at the row rather than only agreeing that something failed.
\ On a refusal the runner carries the UNCHANGED table forward, which is the
\ model's `ceiling_fail_closed`, and is what lets one sequence show a full table
\ refusing a new key and still answering a duplicate.
\
\ The forced filter collision gets a second obligation of its own. The Habu side
\ asks the production `IR-SYM:FILTER` whether the two byte strings really collide;
\ the Rocq side asks what a colliding filter would do, using the model's own
\ `Symbols.collide`: the full predicate still separates the two strings and the
\ filter-only mutation merges them.
\
\ Statements, not just names. Asking Rocq what a theorem assumes says nothing
\ about what it says, so every theorem the manifest binds is also written out as
\ `Definition pinned_statement_<k> : <manifest type row> := @<theorem name>.` The
\ ascribed type is the manifest's copy of the statement, so a proof rewritten to
\ state something weaker no longer type-checks at the type the committed manifest
\ asks for, and Rocq refuses the generated file. The `@` makes the implicit key
\ type and comparison of the generic model explicit, because the statements are
\ section-generalized and would otherwise elaborate against holes.
\
\ Consumer: `test/compiler/ir-intern-proof.f`.

require lib/prelude.f
require lib/errors.f
require lib/string.f
require lib/fmt.f
require test/compiler/ir-intern-schema.f

package COMPILER-INTERN-ROCQ
using COMPILER-INTERN-PROOF
private

$20000 constant V-CAP
$0A constant LF
$22 constant DQ

create V-BUF V-CAP allot

variable V-U
variable PIN-N

\ ---- emit buffer -------------------------------------------------------------

: +$ ( ptr u8 n -- ) {: a:ptr u:n :}
   V-U @ u + V-CAP > if E-STR-CAPACITY throw then
   a V-BUF V-U @ + u BYTE-COPY
   V-U @ u + V-U ! ;

: +C ( n -- ) {: c:n :}
   V-U @ 1+ V-CAP > if E-STR-CAPACITY throw then
   c V-BUF V-U @ + c!
   V-U @ 1+ V-U ! ;

: +NL ( -- )
   LF +C ;

: +N ( n -- )
   SB-RESET FMT:SB-INT SB$ +$ ;

\ ---- preamble ----------------------------------------------------------------
\ The same imports the model itself opens, with the model imported last, so a
\ name the manifest wrote down resolves here exactly as it did where Rocq printed
\ it.

: EMIT-HEAD ( -- )
   s" (* Generated by test/compiler/ir-intern-proof.f from the shared intern" +$ +NL
   s"    sequences and the committed manifest. A build output: never committed. *)" +$ +NL
   s" From Stdlib Require Import Bool List Lia Arith Permutation Wf_nat." +$ +NL
   s" Import ListNotations." +$ +NL
   s" From Habu.Common Require Import Interning." +$ +NL
   s" Set Printing Width 200." +$ +NL ;

\ ---- the two runners ---------------------------------------------------------
\ One fold per key type: present the keys left to right, collect what each step
\ answered, and end with the table's row count. A refused step carries the table
\ forward untouched.

: EMIT-RUNNERS ( -- )
   s" Fixpoint sym_run (t : table Symbols.bytes) (ks : list Symbols.bytes)" +$ +NL
   s"   : list (option nat) * nat :=" +$ +NL
   s"   match ks with" +$ +NL
   s"   | [] => ([], count t)" +$ +NL
   s"   | k :: rest =>" +$ +NL
   s"       match Symbols.sym_intern t k with" +$ +NL
   s"       | Some (t', i) => let r := sym_run t' rest in (Some i :: fst r, snd r)" +$ +NL
   s"       | None => let r := sym_run t rest in (None :: fst r, snd r)" +$ +NL
   s"       end" +$ +NL
   s"   end." +$ +NL
   s" Fixpoint ty_run (t : table Types.ty) (ks : list Types.ty)" +$ +NL
   s"   : list (option nat) * nat :=" +$ +NL
   s"   match ks with" +$ +NL
   s"   | [] => ([], count t)" +$ +NL
   s"   | k :: rest =>" +$ +NL
   s"       match Types.ty_intern t k with" +$ +NL
   s"       | Some (t', i) => let r := ty_run t' rest in (Some i :: fst r, snd r)" +$ +NL
   s"       | None => let r := ty_run t rest in (None :: fst r, snd r)" +$ +NL
   s"       end" +$ +NL
   s"   end." +$ +NL ;

\ ---- one key ------------------------------------------------------------------

: +BYTES ( ptr u8 n -- ) {: a:ptr u:n :}
   s" [" +$
   u 0 ?do
      i 0 > if s" ; " +$ then
      a i + c@ +N
   loop
   s" ]" +$ ;

: +TY-KEY ( n -- ) {: ki:n :}
   ki TY-CTOR CTOR-INT = if s" Types.TInt " +$ else s" Types.TPtr " +$ then
   ki TY-ARG-A +N s"  " +$ ki TY-ARG-B +N ;

: +AT-KEY ( n -- ) {: ki:n :}
   s" Types.TInt " +$ ki AT-KEY +N s"  0" +$ ;

: +KEY ( n n -- ) {: kind:n ki:n :}
   kind KIND-SYM = if ki SYM-KEY$ +BYTES exit then
   kind KIND-TYPE = if ki +TY-KEY exit then
   kind KIND-ATTR <> if E-CIN-ROW throw then
   ki +AT-KEY ;

: +ANSWER ( n -- ) {: st:n :}
   st STEP-CLASS@ 0 <> if s" None" +$ exit then
   s" Some " +$ st STEP-ORD@ +N ;

\ ---- one sequence --------------------------------------------------------------

: +LABEL ( n -- ) {: s:n :}
   s" Example seq_" +$ s SCN-ROLE@ ROLE-NAME$ +$ s" _" +$ s +N s"  :" +$ +NL ;

: +RUNNER ( n -- ) {: s:n :}
   s SCN-KIND@ KIND-SYM = if
      s"   sym_run (Symbols.empty " +$
   else
      s"   ty_run (Types.empty " +$
   then
   s SCN-CEIL@ +N s" ) [" +$ ;

: +KEY-LIST ( n -- ) {: s:n :}
   s SCN-LEN@ 0 ?do
      i 0 > if s" ; " +$ then
      s SCN-KIND@ s SCN-BASE@ i + STEP-KEY@ +KEY
   loop
   s" ]" +$ +NL ;

: +ANSWER-LIST ( n -- ) {: s:n :}
   s"     = ([" +$
   s SCN-LEN@ 0 ?do
      i 0 > if s" ; " +$ then
      s SCN-BASE@ i + +ANSWER
   loop
   s" ], " +$ s SCN-FINAL@ +N s" )." +$ +NL ;

: EMIT-SEQUENCE ( n -- ) {: s:n :}
   s +LABEL
   s +RUNNER
   s +KEY-LIST
   s +ANSWER-LIST
   s" Proof. vm_compute. reflexivity. Qed." +$ +NL ;

\ ---- the forced filter collision ----------------------------------------------
\ Under a filter that collides, the predicate the interner actually runs still
\ separates the two byte strings, and the mutation that trusts the filter and
\ skips the byte verify merges them. That is the half of the collision the model
\ owns; that these two strings really do collide is asked of `IR-SYM:FILTER` on
\ the Habu side.

: EMIT-COLLISION ( n -- ) {: s:n :}
   s SCN-ROLE@ ROLE-COLLISION <> if exit then
   s SCN-BASE@ {: b:n :}
   s" Example collision_" +$ s +N s"  :" +$ +NL
   s"   Symbols.row_match Symbols.collide (Symbols.collide " +$
      b STEP-KEY@ SYM-KEY$ +BYTES s" ) " +$
      b STEP-KEY@ SYM-KEY$ +BYTES s"  " +$
      b 1+ STEP-KEY@ SYM-KEY$ +BYTES s"  = false" +$ +NL
   s"   /\ Symbols.filter_only_match Symbols.collide (Symbols.collide " +$
      b STEP-KEY@ SYM-KEY$ +BYTES s" ) " +$
      b 1+ STEP-KEY@ SYM-KEY$ +BYTES s"  = true" +$ +NL
   s"   /\ Symbols.bytes_eqb " +$
      b STEP-KEY@ SYM-KEY$ +BYTES s"  " +$
      b 1+ STEP-KEY@ SYM-KEY$ +BYTES s"  = false." +$ +NL
   s" Proof. repeat split; vm_compute; reflexivity. Qed." +$ +NL ;

: EMIT-SEQUENCES ( -- )
   SCENARIOS 0 ?do
      i EMIT-SEQUENCE
      i EMIT-COLLISION
   loop ;

public

: START ( -- )
   0 V-U !
   0 PIN-N !
   EMIT-HEAD
   EMIT-RUNNERS
   EMIT-SEQUENCES ;

\ One theorem from the committed manifest, pinned to the statement the manifest
\ says it makes. The manifest's `type` row is written out as the ascribed type of
\ a definition whose body is the theorem itself, so Rocq's own type checker has
\ to accept the proved statement as that type. It accepts up to conversion, which
\ is the honest question to ask: a renamed bound variable is not a change, and a
\ weaker, stronger, or trivial statement is. The type comes from the manifest and
\ never from the proof file, so editing the proof file alone cannot also move the
\ target. A definition is silent on success, so this adds nothing to the output
\ the gate reads the assumption set back out of.
: STATEMENT+ ( ptr u8 n ptr u8 n -- )
   {: name:ptr nameu:n type:ptr typeu:n :}
   s" Definition pinned_statement_" +$ PIN-N @ +N s"  : " +$
   type typeu +$
   s"  := @" +$ name nameu +$ s" ." +$ +NL
   PIN-N @ 1+ PIN-N ! ;

\ One theorem from the committed manifest: a printed marker so the observed
\ output can be attributed, then the assumption query itself. A name Rocq cannot
\ resolve stops the whole run, so a manifest row for a theorem that no longer
\ exists fails the gate rather than being skipped.
: ASSUMPTION+ ( ptr u8 n -- ) {: a:ptr u:n :}
   s" Goal True. idtac " +$ DQ +C s" == theorem " +$ a u +$ DQ +C
      s" . Abort." +$ +NL
   s" Print Assumptions " +$ a u +$ s" ." +$ +NL ;

: TEXT$ ( -- ptr u8 n )
   V-BUF V-U @ ;

;using
;package
