\ ir-structure-obligations.f - the Rocq obligation text the structure gate proves.
\
\ The module lives in `package COMPILER-STRUCT-ROCQ`. It writes one Rocq source
\ out of live state: the build sequences frozen in `package
\ COMPILER-STRUCT-PROOF` and the theorem names and statements in the committed
\ manifest. Nothing in it is transcribed.
\
\ Why the obligations are generated rather than written by hand. A hand-written
\ Rocq companion would be a second copy of the sequences, and two copies drift.
\ Here the Habu side and the Rocq side read the one artifact:
\ `test/compiler/ir-structure-cases.f` runs each sequence through the real
\ `IR-OP` and `IR-FUN` words, and the very same sequence is turned into a Rocq
\ obligation about `Habu.Common.Structure`. Delete a sequence, weaken a step, or
\ move a ceiling and the two sides are asked different questions, so one refuses.
\
\ How a sequence becomes an obligation. The file defines one runner per store.
\ `op_run` folds the model's `end_op` over a list of operations and collects what
\ each step answered together with the operation and value counts the store ends
\ on. `blk_run` folds the model's `end_block` and `term_ck` over a list of block
\ steps and collects the same shape. A step the shared row marks accepted must
\ answer `Some <the frozen ordinal>`, and a step it marks rejected must answer
\ `None` - which is the model's whole vocabulary for a refusal, while Habu names
\ a throw code. The row carries the throw code, so the two sides stay bound at
\ the row rather than only agreeing that something failed. On a refusal both
\ runners carry the UNCHANGED table forward, which is the model's
\ `end_op_failure_atomic`; for the block runner the operations of the refused
\ block are still appended, because IR-OP appended them before IR-FUN was asked
\ to close the block, and that is what makes the wedged sequence come out the
\ same on both sides.
\
\ Statements, not just names. Asking Rocq what a theorem assumes says nothing
\ about what it says, so every theorem the manifest binds is also written out as
\ `Definition pinned_statement_<k> : <manifest type row> := @<theorem name>.` The
\ ascribed type is the manifest's copy of the statement, so a proof rewritten to
\ state something weaker no longer type-checks at the type the committed manifest
\ asks for, and Rocq refuses the generated file.
\
\ Consumer: `test/compiler/ir-structure-proof.f`.

require lib/prelude.f
require lib/errors.f
require lib/string.f
require lib/fmt.f
require test/compiler/ir-structure-schema.f

package COMPILER-STRUCT-ROCQ
using COMPILER-STRUCT-PROOF
private

$20000 constant V-CAP
$0A constant LF
$22 constant DQ

create V-BUF V-CAP allot

variable V-U
variable PIN-N

\ ---- emit buffer -------------------------------------------------------------

: +$ ( ptr u8 n -- ) {: a:ptr u:n :}
   V-U @ u + V-CAP > if E-STR-CAPACITY throw then
   a V-BUF V-U @ + u BYTE-COPY
   V-U @ u + V-U ! ;

: +C ( n -- ) {: c:n :}
   V-U @ 1+ V-CAP > if E-STR-CAPACITY throw then
   c V-BUF V-U @ + c!
   V-U @ 1+ V-U ! ;

: +NL ( -- )
   LF +C ;

: +N ( n -- )
   SB-RESET FMT:SB-INT SB$ +$ ;

\ ---- preamble ----------------------------------------------------------------
\ The same imports the model itself opens, with the model imported last, so a
\ name the manifest wrote down resolves here exactly as it did where Rocq printed
\ it.

: EMIT-HEAD ( -- )
   s" (* Generated by test/compiler/ir-structure-proof.f from the shared build" +$ +NL
   s"    sequences and the committed manifest. A build output: never committed. *)" +$ +NL
   s" From Stdlib Require Import Bool List Lia Arith Permutation Wf_nat." +$ +NL
   s" Import ListNotations." +$ +NL
   s" From Habu.Common Require Import Structure." +$ +NL
   s" Set Printing Width 200." +$ +NL ;

\ ---- the two runners ---------------------------------------------------------

: EMIT-OP-RUNNER ( -- )
   s" Fixpoint op_run (c : ocaps) (st : ostate) (os : list op)" +$ +NL
   s"   : list (option nat) * (nat * nat) :=" +$ +NL
   s"   match os with" +$ +NL
   s"   | [] => ([], (length (ops st), nvals st))" +$ +NL
   s"   | o :: rest =>" +$ +NL
   s"       match end_op c st o with" +$ +NL
   s"       | Some st' => let r := op_run c st' rest in (Some (length (ops st)) :: fst r, snd r)" +$ +NL
   s"       | None => let r := op_run c st rest in (None :: fst r, snd r)" +$ +NL
   s"       end" +$ +NL
   s"   end." +$ +NL ;

: EMIT-BLK-RUNNER ( -- )
   s" Definition blk_close (bs : list blk) (opst opn toff : nat) : option blk :=" +$ +NL
   s"   match end_block bs opst opn 0 0 0 with" +$ +NL
   s"   | Some b => if term_ck (fun i => Nat.eqb i (opst + toff)) opst opn then Some b else None" +$ +NL
   s"   | None => None" +$ +NL
   s"   end." +$ +NL
   s" Fixpoint blk_run (bs : list blk) (nops : nat) (steps : list (nat * nat * nat))" +$ +NL
   s"   : list (option nat) * (nat * nat) :=" +$ +NL
   s"   match steps with" +$ +NL
   s"   | [] => ([], (length bs, nops))" +$ +NL
   s"   | (stray, opn, toff) :: rest =>" +$ +NL
   s"       let opst := nops + stray in" +$ +NL
   s"       match blk_close bs opst opn toff with" +$ +NL
   s"       | Some b => let r := blk_run (bs ++ [b]) (opst + opn) rest in (Some (length bs) :: fst r, snd r)" +$ +NL
   s"       | None => let r := blk_run bs (opst + opn) rest in (None :: fst r, snd r)" +$ +NL
   s"       end" +$ +NL
   s"   end." +$ +NL ;

\ ---- one step ----------------------------------------------------------------

: +OPERANDS ( n -- ) {: st:n :}
   s" [" +$
   st SS-OPN@ 0 ?do
      i 0 > if s" ; " +$ then
      st SS-OPB@ i + OPD@ +N
   loop
   s" ]" +$ ;

: +OP ( n -- ) {: st:n :}
   s" MkOp " +$ st +OPERANDS s"  " +$ st SS-RSN@ +N s"  0 0" +$ ;

: +BSTEP ( n -- ) {: st:n :}
   s" (" +$ st BS-STRAY@ +N s" , " +$ st BS-OPN@ +N s" , " +$ st BS-TOFF@ +N s" )" +$ ;

: +ANSWER ( n -- ) {: class:n :}
   class 0 <> if s" None" +$ exit then
   s" Some " +$ ;

: +SSA-ANSWER ( n -- ) {: st:n :}
   st SS-CLASS@ +ANSWER
   st SS-CLASS@ 0 = if st SS-ORD@ +N then ;

: +BLK-ANSWER ( n -- ) {: st:n :}
   st BS-CLASS@ +ANSWER
   st BS-CLASS@ 0 = if st BS-ORD@ +N then ;

\ ---- one sequence ------------------------------------------------------------

: +LABEL ( n -- ) {: s:n :}
   s" Example seq_" +$ s SCN-ROLE@ ROLE-NAME$ +$ s" _" +$ s +N s"  :" +$ +NL ;

: +SSA-CALL ( n -- ) {: s:n :}
   s"   op_run (MkOCaps " +$ s SCN-OCAP@ +N s"  " +$ s SCN-VCAP@ +N s"  " +$
      s SCN-PCAP@ +N s" ) (MkOState [] 0 0)" +$ +NL
   s"     [" +$
   s SCN-LEN@ 0 ?do
      i 0 > if s" ; " +$ then
      s SCN-BASE@ i + +OP
   loop
   s" ]" +$ +NL ;

: +SSA-RESULT ( n -- ) {: s:n :}
   s"     = ([" +$
   s SCN-LEN@ 0 ?do
      i 0 > if s" ; " +$ then
      s SCN-BASE@ i + +SSA-ANSWER
   loop
   s" ], (" +$ s SCN-FINAL-A@ +N s" , " +$ s SCN-FINAL-B@ +N s" ))." +$ +NL ;

: +BLK-CALL ( n -- ) {: s:n :}
   s"   blk_run [] 0" +$ +NL
   s"     [" +$
   s SCN-LEN@ 0 ?do
      i 0 > if s" ; " +$ then
      s SCN-BASE@ i + +BSTEP
   loop
   s" ]" +$ +NL ;

: +BLK-RESULT ( n -- ) {: s:n :}
   s"     = ([" +$
   s SCN-LEN@ 0 ?do
      i 0 > if s" ; " +$ then
      s SCN-BASE@ i + +BLK-ANSWER
   loop
   s" ], (" +$ s SCN-FINAL-A@ +N s" , " +$ s SCN-FINAL-B@ +N s" ))." +$ +NL ;

: EMIT-SEQUENCE ( n -- ) {: s:n :}
   s +LABEL
   s SCN-KIND@ KIND-SSA = if s +SSA-CALL s +SSA-RESULT else s +BLK-CALL s +BLK-RESULT then
   s" Proof. vm_compute. reflexivity. Qed." +$ +NL ;

: EMIT-SEQUENCES ( -- )
   SCENARIOS 0 ?do i EMIT-SEQUENCE loop ;

public

: START ( -- )
   0 V-U !
   0 PIN-N !
   EMIT-HEAD
   EMIT-OP-RUNNER
   EMIT-BLK-RUNNER
   EMIT-SEQUENCES ;

\ One theorem from the committed manifest, pinned to the statement the manifest
\ says it makes. The manifest's `type` row is written out as the ascribed type of
\ a definition whose body is the theorem itself, so Rocq's own type checker has
\ to accept the proved statement as that type. It accepts up to conversion, which
\ is the honest question to ask: a renamed bound variable is not a change, and a
\ weaker, stronger, or trivial statement is. The type comes from the manifest and
\ never from the proof file, so editing the proof file alone cannot also move the
\ target. A definition is silent on success, so this adds nothing to the output
\ the gate reads the assumption set back out of.
: STATEMENT+ ( ptr u8 n ptr u8 n -- )
   {: name:ptr nameu:n type:ptr typeu:n :}
   s" Definition pinned_statement_" +$ PIN-N @ +N s"  : " +$
   type typeu +$
   s"  := @" +$ name nameu +$ s" ." +$ +NL
   PIN-N @ 1+ PIN-N ! ;

\ One theorem from the committed manifest: a printed marker so the observed
\ output can be attributed, then the assumption query itself. A name Rocq cannot
\ resolve stops the whole run, so a manifest row for a theorem that no longer
\ exists fails the gate rather than being skipped.
: ASSUMPTION+ ( ptr u8 n -- ) {: a:ptr u:n :}
   s" Goal True. idtac " +$ DQ +C s" == theorem " +$ a u +$ DQ +C
      s" . Abort." +$ +NL
   s" Print Assumptions " +$ a u +$ s" ." +$ +NL ;

: TEXT$ ( -- ptr u8 n )
   V-BUF V-U @ ;

;using
;package
