\ ir-storage-obligations.f - the Rocq obligation text the storage gate proves.
\
\ The module lives in `package COMPILER-STORE-ROCQ`. It writes one Rocq source
\ out of live state: the pinned capacity constants and the arena and context
\ vector rows frozen in `package COMPILER-STORE-PROOF`, and the theorem names and
\ statements in the committed manifest. Nothing in it is transcribed.
\
\ Why the obligations are generated rather than written by hand. A hand-written
\ Rocq companion would be a second copy of the vector rows, and two copies drift.
\ Here the Habu side and the Rocq side read the one artifact:
\ `test/compiler/ir-storage-cases.f` runs each row through the real `IR-CTX` and
\ `IR-ARENA` words, and the very same row is turned into a Rocq obligation about
\ `Habu.Common.Storage`. Delete a row, weaken a step, or move a ceiling and the
\ two sides are asked different questions, so one refuses.
\
\ How a row becomes an obligation. The file emits a small machine per table. The
\ arena machine holds the two arenas a row addresses, the
\ kept index and the frozen view - the same pieces of state the Habu runner
\ keeps in typed variables - and answers each step with a number or `None`, which
\ is the model's whole vocabulary for a refusal while Habu names a throw code.
\ The row carries the throw code, so the two sides stay bound at the step rather
\ than only agreeing that something failed. A refused step carries the UNCHANGED
\ machine forward, which is the model's `arena_push_failure_atomic`, and is what
\ lets one row show a full arena refusing a cell and still reading its contents.
\
\ The machine starts every handle slot holding a handle of a third, frozen
\ placeholder arena, exactly as the Habu runner does, so the two sides agree even
\ on a row that reads a slot it never set. The table shape check in the cases
\ file makes that unreachable; this makes the two sides agree about it anyway.
\
\ The context machine is the same idea for the scratch cursor and the module
\ budget: a byte cursor that starts just past the header and a spent count
\ against the row's ceiling.
\
\ Statements, not just names. Asking Rocq what a theorem assumes says nothing
\ about what it says, so every theorem the manifest binds is also written out as
\ `Definition pinned_statement_<k> : <manifest type row> := @<theorem name>.` The
\ ascribed type is the manifest's copy of the statement, so a proof rewritten to
\ state something weaker no longer type-checks at the type the committed manifest
\ asks for, and Rocq refuses the generated file. The type comes from the manifest
\ and never from the proof file, so editing the proof file alone cannot also move
\ the target.
\
\ The pinned capacity constants are proved by conversion rather than by
\ `vm_compute`: the generation ceiling is two billion and forcing it into unary
\ form would not finish, while unfolding the definition and comparing the two
\ literals is immediate.
\
\ Consumer: `test/compiler/ir-storage-proof.f`.

require lib/prelude.f
require lib/errors.f
require lib/string.f
require lib/fmt.f
require test/compiler/ir-storage-schema.f

package COMPILER-STORE-ROCQ
using COMPILER-STORE-PROOF
private

$20000 constant V-CAP
$0A constant LF
$22 constant DQ

create V-BUF V-CAP allot

variable V-U
variable PIN-N

\ ---- emit buffer -------------------------------------------------------------

: +$ ( ptr u8 n -- ) {: a:ptr u:n :}
   V-U @ u + V-CAP > if E-STR-CAPACITY throw then
   a V-BUF V-U @ + u BYTE-COPY
   V-U @ u + V-U ! ;

: +C ( n -- ) {: c:n :}
   V-U @ 1+ V-CAP > if E-STR-CAPACITY throw then
   c V-BUF V-U @ + c!
   V-U @ 1+ V-U ! ;

: +NL ( -- )
   LF +C ;

: +N ( n -- )
   SB-RESET FMT:SB-INT SB$ +$ ;

\ ---- preamble ----------------------------------------------------------------
\ The same imports the model itself opens, with the model imported last, so a
\ name the manifest wrote down resolves here exactly as it did where Rocq printed
\ it.

: EMIT-HEAD ( -- )
   s" (* Generated by test/compiler/ir-storage-proof.f from the shared storage" +$ +NL
   s"    vector rows and the committed manifest. A build output: never committed. *)" +$ +NL
   s" From Stdlib Require Import Bool List Lia Arith." +$ +NL
   s" Import ListNotations." +$ +NL
   s" From Habu.Common Require Import Storage." +$ +NL
   s" Set Printing Width 200." +$ +NL ;

\ ---- the pinned capacity constants -------------------------------------------

: EMIT-PIN ( n -- ) {: row:n :}
   s" Example pinned_capacity_" +$ row +N s"  : " +$
   row PIN-MODEL$ +$ s"  = " +$ row PIN-VALUE +N s" ." +$ +NL
   s" Proof. reflexivity. Qed." +$ +NL ;

: EMIT-PINS ( -- )
   PIN-COUNT 0 ?do i EMIT-PIN loop ;

\ ---- the arena machine -------------------------------------------------------
\ Six pieces of state and one owner serial, stepped by the operation codes the
\ shared table uses. A refusal answers `None` and carries the machine forward.

: EMIT-ARENA-MACHINE ( -- )
   s" Record avm : Type := MkAVM {" +$ +NL
   s"   vA : arena; vB : arena;" +$ +NL
   s"   vX : cell_id; vV : arena; vOwner : nat }." +$ +NL
   s" Definition asel (m : avm) (w : nat) : arena :=" +$ +NL
   s"   if Nat.eqb w 0 then vA m else vB m." +$ +NL
   s" Definition aput (m : avm) (w : nat) (a : arena) : avm :=" +$ +NL
   s"   if Nat.eqb w 0" +$ +NL
   s"   then MkAVM a (vB m) (vX m) (vV m) (vOwner m)" +$ +NL
   s"   else MkAVM (vA m) a (vX m) (vV m) (vOwner m)." +$ +NL
   s" Definition aputx (m : avm) (x : cell_id) : avm :=" +$ +NL
   s"   MkAVM (vA m) (vB m) x (vV m) (vOwner m)." +$ +NL
   s" Definition aputv (m : avm) (v : arena) : avm :=" +$ +NL
   s"   MkAVM (vA m) (vB m) (vX m) v (vOwner m)." +$ +NL ;

\ Every step resolves its arena first, exactly as IR-ARENA:RESOLVE does, and a
\ retired slot - generation zero, which is what IR-ARENA:ABORT writes - refuses
\ the step whatever it was. That is the model of the handle going stale, and it
\ is why an abort step in a row makes every later step on that arena refuse
\ rather than only the reads of an index.
: EMIT-ARENA-STEP ( -- )
   s" Definition astep (m : avm) (w op arg : nat) : avm * option nat :=" +$ +NL
   s"   let a := asel m w in" +$ +NL
   s"   if negb (alive a) then (m, None)" +$ +NL
   s"   else if Nat.eqb op 0 then" +$ +NL
   s"     match apush (vOwner m) a arg with" +$ +NL
   s"     | Some (a', i) => (aput m w a', Some i)" +$ +NL
   s"     | None => (m, None) end" +$ +NL
   s"   else if Nat.eqb op 1 then" +$ +NL
   s"     if afrozen a then (m, None)" +$ +NL
   s"     else match amint a arg with" +$ +NL
   s"          | Some x => (m, apeek a x)" +$ +NL
   s"          | None => (m, None) end" +$ +NL
   s"   else if Nat.eqb op 2 then" +$ +NL
   s"     (if afrozen a then (m, None) else (m, Some (acount a)))" +$ +NL
   s"   else if Nat.eqb op 3 then" +$ +NL
   s"     match afreeze a with" +$ +NL
   s"     | Some a' => (aputv (aput m w a') a', Some (acount a'))" +$ +NL
   s"     | None => (m, None) end" +$ +NL
   s"   else if Nat.eqb op 4 then" +$ +NL
   s"     (if afrozen (vV m)" +$ +NL
   s"      then match amint (vV m) arg with" +$ +NL
   s"           | Some x => (m, aat (vV m) x)" +$ +NL
   s"           | None => (m, None) end" +$ +NL
   s"      else (m, None))" +$ +NL
   s"   else if Nat.eqb op 5 then" +$ +NL
   s"     (if afrozen a then (m, None)" +$ +NL
   s"      else match amint a arg with" +$ +NL
   s"           | Some x => (aputx m x, Some (idx_ord x))" +$ +NL
   s"           | None => (m, None) end)" +$ +NL
   s"   else if Nat.eqb op 6 then (m, apeek a (vX m))" +$ +NL
   s"   else" +$ +NL
   s"     match aabort a with" +$ +NL
   s"     | Some a' => (aput m w a', Some 0)" +$ +NL
   s"     | None => (m, None) end." +$ +NL
   s" Fixpoint arun (m : avm) (steps : list (nat * nat * nat))" +$ +NL
   s"   : list (option nat) :=" +$ +NL
   s"   match steps with" +$ +NL
   s"   | [] => []" +$ +NL
   s"   | (w, op, arg) :: rest =>" +$ +NL
   s"       match astep m w op arg with" +$ +NL
   s"       | (m', ans) => ans :: arun m' rest" +$ +NL
   s"       end" +$ +NL
   s"   end." +$ +NL ;

\ The placeholder arena is the third arena the Habu runner creates: one cell
\ pushed, then frozen. Generations 1, 2 and 3 stand for three distinct slots
\ of the one monotone counter.
: EMIT-ARENA-INIT ( -- )
   s" Definition aplaceholder : arena := MkArena 3 1 [0] 1 1 true." +$ +NL
   s" Definition ainit (ceil : nat) : avm :=" +$ +NL
   s"   MkAVM (MkArena 1 1 [] (Nat.min ceil seed_cells) ceil false)" +$ +NL
   s"         (MkArena 2 1 [] (Nat.min ceil seed_cells) ceil false)" +$ +NL
   s"         (MkIdx 3 0) aplaceholder 1." +$ +NL ;

\ ---- the context machine -----------------------------------------------------

: EMIT-CTX-MACHINE ( -- )
   s" Record cvm : Type := MkCVM { cOff : nat; cMinted : nat; cCeil : nat }." +$ +NL
   s" Definition cstep (m : cvm) (op arg : nat) : cvm * option nat :=" +$ +NL
   s"   if Nat.eqb op 0 then" +$ +NL
   s"     match scratch_take (cOff m) arg with" +$ +NL
   s"     | Some (_, off') =>" +$ +NL
   s"         (MkCVM off' (cMinted m) (cCeil m), Some (off' - hdr_bytes))" +$ +NL
   s"     | None => (m, None) end" +$ +NL
   s"   else if Nat.eqb op 1 then" +$ +NL
   s"     match mint_take (cMinted m) (cCeil m) with" +$ +NL
   s"     | Some k => (MkCVM (cOff m) k (cCeil m), Some k)" +$ +NL
   s"     | None => (m, None) end" +$ +NL
   s"   else if Nat.eqb op 2 then (m, Some (cOff m - hdr_bytes))" +$ +NL
   s"   else (m, Some (cMinted m))." +$ +NL
   s" Fixpoint crun (m : cvm) (steps : list (nat * nat))" +$ +NL
   s"   : list (option nat) :=" +$ +NL
   s"   match steps with" +$ +NL
   s"   | [] => []" +$ +NL
   s"   | (op, arg) :: rest =>" +$ +NL
   s"       match cstep m op arg with" +$ +NL
   s"       | (m', ans) => ans :: crun m' rest" +$ +NL
   s"       end" +$ +NL
   s"   end." +$ +NL
   s" Definition cinit (ceil : nat) : cvm := MkCVM hdr_bytes 0 ceil." +$ +NL ;

\ ---- one arena row -----------------------------------------------------------

: +ANSWER ( n -- ) {: st:n :}
   st STEP-CLASS@ 0 <> if s" None" +$ exit then
   s" Some " +$ st STEP-ANS@ +N ;

: +STEP ( n -- ) {: st:n :}
   s" (" +$ st STEP-WHICH@ +N s" , " +$ st STEP-OP@ +N s" , " +$
      st STEP-ARG@ +N s" )" +$ ;

: EMIT-ROW ( n -- ) {: s:n :}
   s" Example arena_" +$ s SCN-ROLE@ ROLE-NAME$ +$ s" _" +$ s +N s"  :" +$ +NL
   s"   arun (ainit " +$ s SCN-CEIL@ +N s" ) [" +$
   s SCN-LEN@ 0 ?do
      i 0 > if s" ; " +$ then
      s SCN-BASE@ i + +STEP
   loop
   s" ]" +$ +NL
   s"     = [" +$
   s SCN-LEN@ 0 ?do
      i 0 > if s" ; " +$ then
      s SCN-BASE@ i + +ANSWER
   loop
   s" ]." +$ +NL
   s" Proof. vm_compute. reflexivity. Qed." +$ +NL ;

: EMIT-ROWS ( -- )
   SCENARIOS 0 ?do i EMIT-ROW loop ;

\ ---- one context row ---------------------------------------------------------

: +CANSWER ( n -- ) {: st:n :}
   st CSTEP-CLASS@ 0 <> if s" None" +$ exit then
   s" Some " +$ st CSTEP-ANS@ +N ;

: +CSTEP ( n -- ) {: st:n :}
   s" (" +$ st CSTEP-OP@ +N s" , " +$ st CSTEP-ARG@ +N s" )" +$ ;

: EMIT-CROW ( n -- ) {: s:n :}
   s" Example context_" +$ s CSCN-ROLE@ ROLE-NAME$ +$ s" _" +$ s +N s"  :" +$ +NL
   s"   crun (cinit " +$ s CSCN-CEIL@ +N s" ) [" +$
   s CSCN-LEN@ 0 ?do
      i 0 > if s" ; " +$ then
      s CSCN-BASE@ i + +CSTEP
   loop
   s" ]" +$ +NL
   s"     = [" +$
   s CSCN-LEN@ 0 ?do
      i 0 > if s" ; " +$ then
      s CSCN-BASE@ i + +CANSWER
   loop
   s" ]." +$ +NL
   s" Proof. vm_compute. reflexivity. Qed." +$ +NL ;

: EMIT-CROWS ( -- )
   CSCENARIOS 0 ?do i EMIT-CROW loop ;

\ ---- one nesting depth row ---------------------------------------------------
\ The nesting itself is `Habu.Common.Storage`'s own `dnest` and `dprobe`, not a
\ machine written here: `dnest` opens the row's number of contexts one inside
\ another and answers nothing at all if any of them is refused, so `dprobe n =
\ Some b` already carries the claim that all n went in, and b is what the entry
\ after them does.
\
\ The row's proof runs through `ctx_nesting_stops_at_depth_max` rather than by
\ computation. That is not a convenience: `nat` is unary and the model's
\ generation ceiling is two billion, so any tactic that forces the ceiling into
\ constructor form takes over a minute per row. The theorem keeps the ceiling
\ symbolic, which is why it also carries `depth_max < gen_max` - stated on the
\ row as well, and recorded as MODEL GAP 11 in the model itself. Both numbers
\ are pinned to the shipped source by the capacity rows above.
\
\ The tactic never decides the answer: it rewrites the row's left side into
\ `Some (Nat.ltb <depth> depth_max)` and then the comparison with what the row
\ recorded is what has to hold. A row that recorded the wrong side of the limit,
\ or a depth past it, fails here.

: EMIT-DROW ( n -- ) {: s:n :}
   s" Example context_depth_" +$ s +N s"  :" +$ +NL
   s"   depth_max < gen_max -> dprobe " +$ s DSCN-DEPTH@ +N s"  = Some " +$
   s DSCN-CLASS@ 0 = if s" true" +$ else s" false" +$ then
   s" ." +$ +NL
   s" Proof." +$ +NL
   s"   intros Hroom." +$ +NL
   s"   rewrite ctx_nesting_stops_at_depth_max" +$ +NL
   s"     by (unfold depth_max in *; lia)." +$ +NL
   s"   reflexivity." +$ +NL
   s" Qed." +$ +NL ;

: EMIT-DROWS ( -- )
   DSCENARIOS 0 ?do i EMIT-DROW loop ;

public

: START ( -- )
   0 V-U !
   0 PIN-N !
   EMIT-HEAD
   EMIT-PINS
   EMIT-ARENA-MACHINE
   EMIT-ARENA-STEP
   EMIT-ARENA-INIT
   EMIT-CTX-MACHINE
   EMIT-ROWS
   EMIT-CROWS
   EMIT-DROWS ;

\ One theorem from the committed manifest, pinned to the statement the manifest
\ says it makes. The manifest's `type` row is written out as the ascribed type of
\ a definition whose body is the theorem itself, so Rocq's own type checker has
\ to accept the proved statement as that type. It accepts up to conversion, which
\ is the honest question to ask: a renamed bound variable is not a change, and a
\ weaker, stronger, or trivial statement is. A definition is silent on success,
\ so this adds nothing to the output the gate reads the assumption set back out
\ of.
: STATEMENT+ ( ptr u8 n ptr u8 n -- )
   {: name:ptr nameu:n type:ptr typeu:n :}
   s" Definition pinned_statement_" +$ PIN-N @ +N s"  : " +$
   type typeu +$
   s"  := @" +$ name nameu +$ s" ." +$ +NL
   PIN-N @ 1+ PIN-N ! ;

\ One theorem from the committed manifest: a printed marker so the observed
\ output can be attributed, then the assumption query itself. A name Rocq cannot
\ resolve stops the whole run, so a manifest row for a theorem that no longer
\ exists fails the gate rather than being skipped.
: ASSUMPTION+ ( ptr u8 n -- ) {: a:ptr u:n :}
   s" Goal True. idtac " +$ DQ +C s" == theorem " +$ a u +$ DQ +C
      s" . Abort." +$ +NL
   s" Print Assumptions " +$ a u +$ s" ." +$ +NL ;

: TEXT$ ( -- ptr u8 n )
   V-BUF V-U @ ;

;using
;package
