\ reloc-obligations.f - the Rocq obligation text the relocation gate proves.
\
\ The module lives in `package RELOC-ROCQ`. It writes one Rocq source out of
\ live state: the pinned band constants and the call and address-cell vector
\ rows frozen in `package RELOC-PROOF`, and the theorem names and statements in
\ the committed manifest. Nothing in it is transcribed.
\
\ Why the obligations are generated rather than written by hand. A hand-written
\ Rocq companion would be a second copy of the vector rows, and two copies
\ drift. Here the Habu side and the Rocq side read the one artifact:
\ `test/compiler/reloc-cases.f` runs each row through the shipped
\ `SNAP-RELOC:EMIT-CALLS` and `SNAP-RELOC:EMIT-XT` instruction sequences, and
\ the very same row is turned into a Rocq obligation about `Habu.Common.Reloc`.
\ Delete a row, weaken an answer, or move a base and the two sides are asked
\ different questions, so one refuses.
\
\ How a row becomes an obligation. A call row is a region written as a list of
\ (recorded, word) pairs, and the model's own `canon_pass` and `rebase_pass` are
\ applied to it - there is no machine written here, because the model already
\ carries the walk. The row's answer is the pair the pass must produce: the
\ rewritten region and either no refusal or the shipped exit status. A refusing
\ row asks only about the writer's leg, because the shipped pass exits there and
\ the loader's leg never runs. An address-cell row is simpler still: the
\ writer's fold and the loader's rebase, applied to the cell the row names.
\
\ An address-literal chain row becomes an `addr_walk` over a list of
\ (recorded, chain) pairs, with the band the pass is moving written out beside
\ it: base, length, target. A slot is `mk_chain <address>` when its four words
\ are the chain the compiler emits, and `break_chain <address> <word> <value>`
\ when one of them is not, so the four instruction words are spelled out by the
\ model rather than transcribed here.
\
\ Statements, not just names. Asking Rocq what a theorem assumes says nothing
\ about what it says, so every theorem the manifest binds is also written out as
\ `Definition pinned_statement_<k> : <manifest type row> := @<theorem name>.`
\ The ascribed type is the manifest's copy of the statement, so a proof
\ rewritten to state something weaker no longer type-checks at the type the
\ committed manifest asks for, and Rocq refuses the generated file. The type
\ comes from the manifest and never from the proof file, so editing the proof
\ file alone cannot also move the target.
\
\ Consumer: `test/compiler/reloc-proof.f`.

require lib/prelude.f
require lib/errors.f
require lib/string.f
require lib/fmt.f
require test/compiler/reloc-schema.f

package RELOC-ROCQ
using RELOC-PROOF
private

$10000 constant V-CAP
$0A constant LF
$22 constant DQ

create V-BUF V-CAP allot

variable V-U
variable PIN-N

\ ---- emit buffer -------------------------------------------------------------

: +$ ( ptr u8 n -- ) {: a:ptr u:n :}
   V-U @ u + V-CAP > if E-STR-CAPACITY throw then
   a V-BUF V-U @ + u BYTE-COPY
   V-U @ u + V-U ! ;

: +C ( n -- ) {: c:n :}
   V-U @ 1+ V-CAP > if E-STR-CAPACITY throw then
   c V-BUF V-U @ + c!
   V-U @ 1+ V-U ! ;

: +NL ( -- )
   LF +C ;

\ A negative integer is parenthesised, because Rocq reads `f -5` as a
\ subtraction and every displacement in these rows is negative.
: +N ( n -- ) {: v:n :}
   v 0< if s" (" +$ then
   SB-RESET v FMT:SB-INT SB$ +$
   v 0< if s" )" +$ then ;

\ ---- preamble ----------------------------------------------------------------
\ The same imports the model itself opens, with the model imported last, so a
\ name the manifest wrote down resolves here exactly as it did where Rocq
\ printed it.

: EMIT-HEAD ( -- )
   s" (* Generated by test/compiler/reloc-proof.f from the shared relocation" +$ +NL
   s"    vector rows and the committed manifest. A build output: never committed. *)" +$ +NL
   s" From Stdlib Require Import ZArith Lia List Bool." +$ +NL
   s" Import ListNotations." +$ +NL
   s" From Habu.Common Require Import Reloc." +$ +NL
   s" Open Scope Z_scope." +$ +NL
   s" Set Printing Width 200." +$ +NL ;

\ ---- the pinned band constants -----------------------------------------------

: EMIT-PIN ( n -- ) {: row:n :}
   s" Example pinned_constant_" +$ row +N s"  : " +$
   row PIN-MODEL$ +$ s"  = " +$ row PIN-VALUE +N s" ." +$ +NL
   s" Proof. reflexivity. Qed." +$ +NL ;

: EMIT-PINS ( -- )
   PIN-COUNT 0 ?do i EMIT-PIN loop ;

\ ---- the emit vocabulary's classification ------------------------------------
\ The same producer rows the cases file holds to src/habu/habu2.f, asked of the
\ model's `classify`. One table, two readers: reclassify a producer on either
\ side and the two sides disagree.

: EMIT-CLASS ( n -- ) {: k:n :}
   s" Example classified_" +$ k +N s"  : classify " +$ k PROD-MODEL$ +$
   s"  = " +$ k PROD-CLASS$ +$ s" ." +$ +NL
   s" Proof. reflexivity. Qed." +$ +NL ;

: EMIT-CLASSES ( -- )
   PROD-COUNT 0 ?do i EMIT-CLASS loop ;

\ ---- one call row ------------------------------------------------------------

: +WORD ( n n -- ) {: s:n v:n :}
   s SITE-KIND@ KIND-BL = if s" bl " +$ v +N exit then
   v +N ;

: +SITE ( n n -- ) {: s:n v:n :}
   s" (" +$
   s SITE-REC@ 0<> if s" true, " +$ else s" false, " +$ then
   s v +WORD s" )" +$ ;

: +LIST ( n n -- ) {: row:n phase:n :}
   s" [" +$
   row ROW-LEN@ 0 ?do
      i 0 > if s" ; " +$ then
      row ROW-BASE@ i + {: s:n :}
      phase 0 = if s s SITE-V0@ +SITE else
      phase 1 = if s s SITE-V1@ +SITE else
                    s s SITE-V2@ +SITE then then
   loop
   s" ]" +$ ;

: +STATUS ( n -- ) {: rc:n :}
   rc 0= if s" None" +$ exit then
   s" Some callmap_rc" +$ ;

: EMIT-CANON ( n -- ) {: row:n :}
   s" Example canon_" +$ row ROW-ROLE@ ROLE-NAME$ +$ s" _" +$ row +N s"  :" +$ +NL
   s"   canon_pass " +$ row 0 +LIST s"  " +$ row ROW-WOFF@ +N +NL
   s"     = (" +$ row 1 +LIST s" , " +$ row ROW-RC@ +STATUS s" )." +$ +NL
   s" Proof. vm_compute. reflexivity. Qed." +$ +NL ;

: EMIT-REBASE ( n -- ) {: row:n :}
   s" Example rebase_" +$ row ROW-ROLE@ ROLE-NAME$ +$ s" _" +$ row +N s"  :" +$ +NL
   s"   rebase_pass " +$ row 1 +LIST s"  " +$ row ROW-LOFF@ +N +NL
   s"     = (" +$ row 2 +LIST s" , None)." +$ +NL
   s" Proof. vm_compute. reflexivity. Qed." +$ +NL ;

\ A refusing row has no loader leg: the shipped pass exits at the bad site, so
\ asking the model to restore an image that was never written would be asking
\ about something that cannot happen.
: EMIT-ROW ( n -- ) {: row:n :}
   row EMIT-CANON
   row ROW-RC@ 0= if row EMIT-REBASE then ;

: EMIT-ROWS ( -- )
   ROWS 0 ?do i EMIT-ROW loop ;

\ ---- one address-cell row ----------------------------------------------------

: EMIT-CELL ( n n -- ) {: row:n j:n :}
   row XROW-BASE@ j + {: c:n :}
   s" Example xt_" +$ row XROW-ROLE@ ROLE-NAME$ +$ s" _" +$ row +N s" _" +$ j +N
      s"  :" +$ +NL
   s"   xt_canon " +$ c CELL-V0@ +N s"  " +$ row XROW-DBW@ +N s"  = " +$
      c CELL-V1@ +N +NL
   s"   /\ xt_rebase " +$ c CELL-V1@ +N s"  " +$ row XROW-DBL@ +N s"  = " +$
      c CELL-V2@ +N s" ." +$ +NL
   s" Proof. split; vm_compute; reflexivity. Qed." +$ +NL ;

: EMIT-XROW ( n -- ) {: row:n :}
   row XROW-LEN@ 0 ?do row i EMIT-CELL loop ;

: EMIT-XROWS ( -- )
   XROWS 0 ?do i EMIT-XROW loop ;

\ ---- one address-literal chain row -------------------------------------------

\ A slot is `mk_chain <address>` when its four words are the chain the engine's
\ own carrier emits, `mk_chain_rd <register> <address>` when they are that chain
\ in the register the compiler's allocator chose, `mix_chain <register> <lane>
\ <address>` when one lane names a different register from the other three, and
\ `break_chain <address> <word> <value>` when one word is not an instruction of
\ the chain at all. Every one of those is the MODEL's constructor, so the four
\ instruction words are spelled out there and not transcribed here.
: +ACHAIN ( n n -- ) {: s:n v:n :}
   s ASITE-BAD@ {: bad:n :}
   s ASITE-ODD@ {: odd:n :}
   bad 0 >= if
      s" break_chain " +$ v +N s"  " +$ bad +N s"  " +$ CHAIN-BAD-WORD +N exit
   then
   odd 0 >= if
      s" mix_chain " +$ s ASITE-RD@ +N s"  " +$ odd +N s"  " +$ v +N exit
   then
   s ASITE-RD@ RD-X9 = if s" mk_chain " +$ v +N exit then
   s" mk_chain_rd " +$ s ASITE-RD@ +N s"  " +$ v +N ;

: +ASITE ( n n -- ) {: s:n v:n :}
   s" (" +$
   s ASITE-REC@ 0<> if s" true, " +$ else s" false, " +$ then
   s v +ACHAIN s" )" +$ ;

: +ALIST ( n n -- ) {: row:n phase:n :}
   s" [" +$
   row AROW-LEN@ 0 ?do
      i 0 > if s" ; " +$ then
      row AROW-BASE@ i + {: s:n :}
      phase 0 = if s s ASITE-V0@ +ASITE else
      phase 1 = if s s ASITE-V1@ +ASITE else
                    s s ASITE-V2@ +ASITE then then
   loop
   s" ]" +$ ;

: +ASTATUS ( n -- ) {: rc:n :}
   rc 0= if s" None" +$ exit then
   s" Some addrmap_rc" +$ ;

: +ABAND ( n n n -- ) {: base:n blen:n tgt:n :}
   s"  " +$ base +N s"  " +$ blen +N s"  " +$ tgt +N ;

: EMIT-ACANON ( n -- ) {: row:n :}
   s" Example addr_canon_" +$ row AROW-ROLE@ ROLE-NAME$ +$ s" _" +$ row +N
      s"  :" +$ +NL
   s"   addr_walk " +$ row 0 +ALIST
      row AROW-WB@ row AROW-BLEN@ row AROW-CB@ +ABAND +NL
   s"     = (" +$ row 1 +ALIST s" , " +$ row AROW-RC@ +ASTATUS s" )." +$ +NL
   s" Proof. vm_compute. reflexivity. Qed." +$ +NL ;

\ A refusing row has no loader leg, for the same reason a refusing call row has
\ none: the shipped pass exits at the bad site and no image is ever written.
: EMIT-AREBASE ( n -- ) {: row:n :}
   s" Example addr_rebase_" +$ row AROW-ROLE@ ROLE-NAME$ +$ s" _" +$ row +N
      s"  :" +$ +NL
   s"   addr_walk " +$ row 1 +ALIST
      row AROW-CB@ row AROW-BLEN@ row AROW-LB@ +ABAND +NL
   s"     = (" +$ row 2 +ALIST s" , None)." +$ +NL
   s" Proof. vm_compute. reflexivity. Qed." +$ +NL ;

: EMIT-AROW ( n -- ) {: row:n :}
   row EMIT-ACANON
   row AROW-RC@ 0= if row EMIT-AREBASE then ;

: EMIT-AROWS ( -- )
   AROWS 0 ?do i EMIT-AROW loop ;

public

: START ( -- )
   0 V-U !
   0 PIN-N !
   EMIT-HEAD
   EMIT-PINS
   EMIT-CLASSES
   EMIT-ROWS
   EMIT-XROWS
   EMIT-AROWS ;

\ One theorem from the committed manifest, pinned to the statement the manifest
\ says it makes. Rocq's own type checker has to accept the proved statement as
\ that type, up to conversion, which is the honest question to ask: a renamed
\ bound variable is not a change, and a weaker, stronger, or trivial statement
\ is. A definition is silent on success, so this adds nothing to the output the
\ gate reads the assumption set back out of.
: STATEMENT+ ( ptr u8 n ptr u8 n -- )
   {: name:ptr nameu:n type:ptr typeu:n :}
   s" Definition pinned_statement_" +$ PIN-N @ +N s"  : " +$
   type typeu +$
   s"  := @" +$ name nameu +$ s" ." +$ +NL
   PIN-N @ 1+ PIN-N ! ;

\ One theorem from the committed manifest: a printed marker so the observed
\ output can be attributed, then the assumption query itself. A name Rocq cannot
\ resolve stops the whole run, so a manifest row for a theorem that no longer
\ exists fails the gate rather than being skipped.
: ASSUMPTION+ ( ptr u8 n -- ) {: a:ptr u:n :}
   s" Goal True. idtac " +$ DQ +C s" == theorem " +$ a u +$ DQ +C
      s" . Abort." +$ +NL
   s" Print Assumptions " +$ a u +$ s" ." +$ +NL ;

: TEXT$ ( -- ptr u8 n )
   V-BUF V-U @ ;

;using
;package
