require lib/test.f
require test/checker-assert.f
require src/arch/tic6x/asm.f

package C6XASM-TEST
private
using C6XASM

: WORD= ( C6XASM:instruction n -- )
   swap INSTRUCTION>N swap T= ;

: MOVE-CASES ( -- )
   0 A-REG -32768 ENC-MVK $00400028 WORD=
   31 B-REG 32767 ENC-MVK $0FBFFFAA WORD=
   4 A-REG 42 ENC-MVK $02001528 WORD=
   31 B-REG $FFFFFFFF ENC-MVKH $0FFFFFEA WORD= ;

: DATA-CASES ( -- )
   31 A-REG 30 A-REG 29 A-REG ENC-ADD-L $0FF7C078 WORD=
   4 A-REG 1 A-REG 6 B-REG ENC-ADD-L $02183078 WORD=
   3 A-REG 1 A-REG 2 B-REG ENC-SUB-L $018830F8 WORD=
   0 A-REG 31 A-REG 31 B-REG ENC-CMPEQ-L $007FFA78 WORD= ;

: MEMORY-CASES ( -- )
   7 A-REG 4 A-REG 124 >BYTE-OFFSET ENC-LDW $0393E264 WORD=
   31 B-REG 0 A-REG -4 >BYTE-OFFSET ENC-LDW $0F802066 WORD=
   31 B-REG 31 A-REG -124 >BYTE-OFFSET ENC-STW $0FFFE076 WORD= ;

: BRANCH-CASES ( -- )
   3 B-REG ENC-B-REG $000C0362 WORD=
   0 >SIDE 4194300 >BRANCH-OFFSET ENC-B-REL $07FFFF90 WORD=
   1 >SIDE -4194304 >BRANCH-OFFSET ENC-B-REL $08000012 WORD=
   3 B-REG ENC-B-REG 0 A-REG WHEN-NONZERO $C00C0362 WORD=
   3 B-REG ENC-B-REG 2 B-REG WHEN-ZERO $700C0362 WORD= ;

: PACKET-CASES ( -- )
   1 ENC-NOP 0 WORD= 5 ENC-NOP $8000 WORD= 9 ENC-NOP $10000 WORD=
   0 A-REG 7 ENC-MVK PARALLEL-NEXT $3A9 WORD= ;

: REGISTER-REFUSALS ( -- )
   [: -1 A-REG drop ;] E-OPERAND TTHROWSQ
   [: 32 B-REG drop ;] E-OPERAND TTHROWSQ
   [: 64 >GPR 0 ENC-MVK drop ;] E-OPERAND TTHROWSQ
   [: 0 A-REG 1 B-REG 2 A-REG ENC-ADD-L drop ;] E-OPERAND TTHROWSQ ;

: CONSTANT-REFUSALS ( -- )
   [: 0 A-REG -32769 ENC-MVK drop ;] E-OPERAND TTHROWSQ
   [: 0 A-REG 32768 ENC-MVK drop ;] E-OPERAND TTHROWSQ
   [: 0 A-REG -1 ENC-MVKL drop ;] E-OPERAND TTHROWSQ
   [: 0 A-REG $100000000 ENC-MVKH drop ;] E-OPERAND TTHROWSQ ;

: SMALL-CONSTANT-REFUSALS ( -- )
   [: 0 A-REG 65536 ENC-MVKLH drop ;] E-OPERAND TTHROWSQ
   [: 0 A-REG 1 A-REG -17 ENC-ADD-I5 drop ;] E-OPERAND TTHROWSQ
   [: 0 A-REG 1 A-REG 16 ENC-ADD-I5 drop ;] E-OPERAND TTHROWSQ ;

: OFFSET-REFUSALS ( -- )
   [: 0 A-REG 1 B-REG 2 >BYTE-OFFSET ENC-LDW drop ;] E-OPERAND TTHROWSQ
   [: 0 A-REG 1 B-REG 128 >BYTE-OFFSET ENC-STW drop ;] E-OPERAND TTHROWSQ
   [: 0 >SIDE 2 >BRANCH-OFFSET ENC-B-REL drop ;] E-OPERAND TTHROWSQ
   [: 0 >SIDE 4194304 >BRANCH-OFFSET ENC-B-REL drop ;] E-OPERAND TTHROWSQ
   [: 0 >SIDE -4194308 >BRANCH-OFFSET ENC-B-REL drop ;] E-OPERAND TTHROWSQ ;

: CONTROL-REFUSALS ( -- )
   [: 2 >SIDE 0 >BRANCH-OFFSET ENC-B-REL drop ;] E-OPERAND TTHROWSQ
   [: 0 ENC-NOP drop ;] E-OPERAND TTHROWSQ
   [: 10 ENC-NOP drop ;] E-OPERAND TTHROWSQ
   [: 3 B-REG ENC-B-REG 3 A-REG WHEN-NONZERO drop ;] E-OPERAND TTHROWSQ
   [: 3 B-REG ENC-B-REG 3 B-REG WHEN-ZERO drop ;] E-OPERAND TTHROWSQ ;

: MODIFIER-REFUSALS ( -- )
   [: 1 ENC-NOP 0 A-REG WHEN-NONZERO drop ;] E-OPERAND TTHROWSQ
   [: $100000000 >INSTRUCTION PARALLEL-NEXT drop ;] E-OPERAND TTHROWSQ ;

: NOMINAL-CASES ( -- )
   s" C6-GOOD ( C6XASM:gpr -- C6XASM:gpr )" CHECK-QUIET-CANDIDATE! -1 T=
   s" C6-BAD-REG ( n -- C6XASM:gpr )" CHECK-QUIET-CANDIDATE! 0 T=
   s" C6-BAD-SIDE ( C6XASM:gpr -- C6XASM:side )" CHECK-QUIET-CANDIDATE! 0 T=
   s" C6-BAD-OFF ( C6XASM:branch-offset -- C6XASM:byte-offset )"
      CHECK-QUIET-CANDIDATE! 0 T= ;

: RUN ( -- )
   MOVE-CASES DATA-CASES MEMORY-CASES BRANCH-CASES PACKET-CASES
   REGISTER-REFUSALS CONSTANT-REFUSALS SMALL-CONSTANT-REFUSALS
   OFFSET-REFUSALS CONTROL-REFUSALS MODIFIER-REFUSALS NOMINAL-CASES
   T-REPORT ;

RUN
;package
