\ x86-64 target-contract smoke.
require lib/test.f
require src/compiler/target.f

package X64TARGET-TEST
private

: X64 ( -- CTARGET:contract )
   CTARGET-ARCH:X86-64 CTARGET-ABI:SYSV-AMD64-LINUX CTARGET-ENDIAN:LITTLE
   CTARGET-PTR--WIDTH:BITS64
   CTARGET:F-BASE CTARGET:F-FP CTARGET:WITH CTARGET:F-SIMD CTARGET:WITH
   CTARGET:F-ATOMIC CTARGET:WITH CTARGET:CONTRACT ;

: RUN ( -- )
   s" x86 target constructs" T-LABEL
   X64 CTARGET:ARCH@ CTARGET-ARCH:X86-64 CTARGET-ARCH:EQ T-TRUE
   X64 CTARGET:ABI@ CTARGET-ABI:SYSV-AMD64-LINUX CTARGET-ABI:EQ T-TRUE
   s" x86 target is 64-bit" T-LABEL
   X64 CTARGET:PTR-BITS 64 T=
   s" x86 rejects big endian" T-LABEL
   [: CTARGET-ARCH:X86-64 CTARGET-ABI:SYSV-AMD64-LINUX CTARGET-ENDIAN:BIG
      CTARGET-PTR--WIDTH:BITS64 CTARGET:F-BASE CTARGET:CONTRACT drop ;]
   E-CTGT-ENDIAN TTHROWSQ ;

RUN
;package
