;;;; Compile functions and generate C test harness for execution
;;;; Phase 3.1: Self-Compile Functions

(load "run-habu.lisp")

(in-package :habu-sbcl-codegen)

(defun dump-c-header ()
  "Output C header includes and typedefs"
  (format t "#include <stdio.h>~%")
  (format t "#include <stdlib.h>~%")
  (format t "#include <stdint.h>~%")
  (format t "#include <sys/mman.h>~%")
  (format t "#include <string.h>~%")
  (format t "~%")
  (format t "#ifndef MAP_JIT~%")
  (format t "#define MAP_JIT 0x0800~%")
  (format t "#endif~%")
  (format t "~%")
  (format t "typedef int64_t (*fn_t)(int64_t);~%")
  (format t "~%"))

(defun dump-bytes-as-c-array (bytes name)
  "Dump byte list as C array"
  (format t "uint8_t ~A[] = {~%" name)
  (format t "    ")
  (loop for b in bytes
        for i from 0
        do (progn
             (when (and (> i 0) (zerop (mod i 12)))
               (format t "~%    "))
             (format t "0x~2,'0X" b)
             (when (< i (1- (length bytes)))
               (format t ", "))))
  (format t "~%};~%")
  (format t "size_t ~A_size = ~D;~%~%" name (length bytes)))

(defun dump-execute-function ()
  "Output execute_code helper function"
  (format t "int64_t execute_code(const uint8_t *code, size_t size, int64_t arg) {~%")
  (format t "    size_t page_size = 4096;~%")
  (format t "    void *mem = mmap(NULL, page_size, PROT_READ | PROT_WRITE,~%")
  (format t "                     MAP_PRIVATE | MAP_ANON | MAP_JIT, -1, 0);~%")
  (format t "    if (mem == MAP_FAILED) {~%")
  (format t "        perror(\"mmap\");~%")
  (format t "        return 0;~%")
  (format t "    }~%")
  (format t "~%")
  (format t "    memcpy(mem, code, size);~%")
  (format t "~%")
  (format t "    if (mprotect(mem, page_size, PROT_READ | PROT_EXEC) != 0) {~%")
  (format t "        perror(\"mprotect\");~%")
  (format t "        munmap(mem, page_size);~%")
  (format t "        return 0;~%")
  (format t "    }~%")
  (format t "~%")
  (format t "    fn_t fn = (fn_t)mem;~%")
  (format t "    int64_t result = fn(arg);~%")
  (format t "~%")
  (format t "    munmap(mem, page_size);~%")
  (format t "    return result;~%")
  (format t "}~%~%"))

(defun dump-test-case (test-name func-name code-var arg expected)
  "Output a test case"
  (format t "    /* Test: ~A */~%" test-name)
  (format t "    printf(\"Test ~A: ~A(~D)\\n\");~%" test-name func-name (/ arg 16))
  (format t "    result = execute_code(~A, ~A_size, ~D);~%" code-var code-var arg)
  (format t "    printf(\"  Result: %lld (expected %lld)\\n\", (long long)(result >> 4), (long long)(~D >> 4));~%" expected)
  (format t "    if (result == ~D) {~%" expected)
  (format t "        printf(\"  ✓ PASS\\n\\n\");~%")
  (format t "        passed++;~%")
  (format t "    } else {~%")
  (format t "        printf(\"  ✗ FAIL\\n\\n\");~%")
  (format t "        failed++;~%")
  (format t "    }~%~%"))

(format t "~%/* ================================================ */~%")
(format t "/* Phase 3.1: Self-Compile Functions Test Harness  */~%")
(format t "/* Generated by compile-and-execute.lisp           */~%")
(format t "/* ================================================ */~%~%")

(dump-c-header)

(format t "/* ================================================ */~%")
(format t "/* Test 1: Simple arithmetic function              */~%")
(format t "/* (defun add-one (x) (+ x 1))                     */~%")
(format t "/* ================================================ */~%~%")

(let ((forms '((defun add-one (x) (+ x 1))
               (add-one 5))))
  (handler-case
      (let ((bytes (compile-program-with-functions-with-runtime forms *runtime-addrs*)))
        (dump-bytes-as-c-array bytes "add_one_code")
        (format t "/* add-one(5) should return 6 (0x~X tagged = ~D) */~%~%"
                (* 6 16) (* 6 16)))
    (error (e)
      (format t "/* ERROR: ~A */~%~%" e))))

(format t "/* ================================================ */~%")
(format t "/* Test 2: Multiplication function                  */~%")
(format t "/* (defun double (x) (* x 2))                      */~%")
(format t "/* ================================================ */~%~%")

(let ((forms '((defun double (x) (* x 2))
               (double 7))))
  (handler-case
      (let ((bytes (compile-program-with-functions-with-runtime forms *runtime-addrs*)))
        (dump-bytes-as-c-array bytes "double_code")
        (format t "/* double(7) should return 14 (0x~X tagged = ~D) */~%~%"
                (* 14 16) (* 14 16)))
    (error (e)
      (format t "/* ERROR: ~A */~%~%" e))))

(format t "/* ================================================ */~%")
(format t "/* Test 3: Conditional function                     */~%")
(format t "/* (defun abs-val (x) (if (< x 0) (- 0 x) x))     */~%")
(format t "/* ================================================ */~%~%")

(let ((forms '((defun abs-val (x) (if (< x 0) (- 0 x) x))
               (abs-val -5))))
  (handler-case
      (let ((bytes (compile-program-with-functions-with-runtime forms *runtime-addrs*)))
        (dump-bytes-as-c-array bytes "abs_val_code")
        (format t "/* abs-val(-5) should return 5 (0x~X tagged = ~D) */~%~%"
                (* 5 16) (* 5 16)))
    (error (e)
      (format t "/* ERROR: ~A */~%~%" e))))

(format t "/* ================================================ */~%")
(format t "/* Test 4: Recursive factorial                      */~%")
(format t "/* (defun factorial (n)                             */~%")
(format t "/*   (if (= n 0) 1 (* n (factorial (- n 1)))))     */~%")
(format t "/* ================================================ */~%~%")

(let ((forms '((defun factorial (n)
                 (if (= n 0) 1 (* n (factorial (- n 1)))))
               (factorial 5))))
  (handler-case
      (let ((bytes (compile-program-with-functions-with-runtime forms *runtime-addrs*)))
        (dump-bytes-as-c-array bytes "factorial_code")
        (format t "/* factorial(5) should return 120 (0x~X tagged = ~D) */~%~%"
                (* 120 16) (* 120 16)))
    (error (e)
      (format t "/* ERROR: ~A */~%~%" e))))

(format t "/* ================================================ */~%")
(format t "/* Test 5: Tail-recursive factorial                 */~%")
(format t "/* (defun fact-tail (n acc)                         */~%")
(format t "/*   (if (= n 0) acc                                */~%")
(format t "/*       (fact-tail (- n 1) (* n acc))))            */~%")
(format t "/* Note: Uses 2 parameters, test with n=5, acc=1   */~%")
(format t "/* ================================================ */~%~%")

(let ((forms '((defun fact-tail (n acc)
                 (if (= n 0) acc (fact-tail (- n 1) (* n acc))))
               (fact-tail 5 1))))
  (handler-case
      (let ((bytes (compile-program-with-functions-with-runtime forms *runtime-addrs*)))
        (dump-bytes-as-c-array bytes "fact_tail_code")
        (format t "/* fact-tail(5, 1) should return 120 (0x~X tagged = ~D) */~%~%"
                (* 120 16) (* 120 16)))
    (error (e)
      (format t "/* ERROR: ~A */~%~%" e))))

(dump-execute-function)

(format t "/* ================================================ */~%")
(format t "/* Main test driver                                 */~%")
(format t "/* ================================================ */~%~%")

(format t "int main(void) {~%")
(format t "    printf(\"\\n=== Phase 3.1: Self-Compiled Function Tests ===\\n\\n\");~%")
(format t "~%")
(format t "    int64_t result;~%")
(format t "    int passed = 0;~%")
(format t "    int failed = 0;~%")
(format t "~%")

(dump-test-case "add-one" "add-one" "add_one_code" (* 5 16) (* 6 16))
(dump-test-case "double" "double" "double_code" (* 7 16) (* 14 16))
(dump-test-case "abs-val(neg)" "abs-val" "abs_val_code" (* -5 16) (* 5 16))
(dump-test-case "factorial" "factorial" "factorial_code" (* 5 16) (* 120 16))
(dump-test-case "fact-tail" "fact-tail" "fact_tail_code" (* 5 16) (* 120 16))

(format t "    printf(\"\\n=== Test Results ===\\n\");~%")
(format t "    printf(\"Passed: %d\\n\", passed);~%")
(format t "    printf(\"Failed: %d\\n\", failed);~%")
(format t "    printf(\"Total:  %d\\n\\n\", passed + failed);~%")
(format t "~%")
(format t "    if (failed == 0) {~%")
(format t "        printf(\"✓ ALL TESTS PASSED!\\n\\n\");~%")
(format t "        return 0;~%")
(format t "    } else {~%")
(format t "        printf(\"✗ SOME TESTS FAILED\\n\\n\");~%")
(format t "        return 1;~%")
(format t "    }~%")
(format t "}~%")

(format t "~%/* End of generated test harness */~%")
