;;;; Habu Self-Hosting Compiler - Extended Version
;;;; Handles special forms: if, let, lambda, defun

(defun compile-expr (expr)
  (if (fixnum? expr)
    (list (quote lit) expr)
    (if (symbol? expr)
      (list (quote var) expr)
      (if (cons? expr)
        (let ((op (car expr)))
          (if (symbol? op)
            (compile-special-or-call op (cdr expr))
            expr))
        expr))))

(defun compile-special-or-call (op args)
  (if (symbol=? op (quote if))
    (compile-if args)
    (if (symbol=? op (quote let))
      (compile-let args)
      (if (symbol=? op (quote lambda))
        (compile-lambda args)
        (if (symbol=? op (quote defun))
          (compile-defun args)
          (compile-call op args))))))

(defun compile-if (args)
  (if (cons? args)
    (let ((test (car args)))
      (let ((rest (cdr args)))
        (if (cons? rest)
          (let ((then-branch (car rest)))
            (let ((rest2 (cdr rest)))
              (if (cons? rest2)
                (list (quote if-expr)
                      (compile-expr test)
                      (compile-expr then-branch)
                      (compile-expr (car rest2)))
                (list (quote if-expr)
                      (compile-expr test)
                      (compile-expr then-branch)
                      (quote nil)))))
          (quote nil))))
    (quote nil)))

(defun compile-let (args)
  (if (cons? args)
    (let ((bindings (car args)))
      (let ((body-list (cdr args)))
        (if (cons? body-list)
          (list (quote let-expr)
                (compile-bindings bindings)
                (compile-expr (car body-list)))
          (quote nil))))
    (quote nil)))

(defun compile-bindings (bindings)
  (if (nil? bindings)
    (quote nil)
    (if (cons? bindings)
      (let ((binding (car bindings)))
        (if (cons? binding)
          (cons (list (car binding) (compile-expr (car (cdr binding))))
                (compile-bindings (cdr bindings)))
          (quote nil)))
      (quote nil))))

(defun compile-lambda (args)
  (if (cons? args)
    (let ((params (car args)))
      (let ((body-list (cdr args)))
        (if (cons? body-list)
          (list (quote lambda-expr) params (compile-expr (car body-list)))
          (quote nil))))
    (quote nil)))

(defun compile-defun (args)
  (if (cons? args)
    (let ((name (car args)))
      (let ((rest (cdr args)))
        (if (cons? rest)
          (let ((params (car rest)))
            (let ((body-list (cdr rest)))
              (if (cons? body-list)
                (list (quote defun-expr) name params (compile-expr (car body-list)))
                (quote nil))))
          (quote nil))))
    (quote nil)))

(defun compile-call (op args)
  (if (cons? args)
    (let ((arg1 (car args)))
      (let ((rest (cdr args)))
        (if (cons? rest)
          (list (quote call) op
                (compile-expr arg1)
                (compile-expr (car rest)))
          (list (quote call) op (compile-expr arg1)))))
    (list (quote call) op)))

;;; Test Suite
(compile-expr 42)
(compile-expr (quote x))
(compile-expr (quote (+ 1 2)))
(compile-expr (quote (if (= x 0) 1 2)))
(compile-expr (quote (let ((y 5)) (+ y 10))))
(compile-expr (quote (lambda (n) (* n n))))
(compile-expr (quote (defun square (n) (* n n))))
