#!/usr/bin/env sbcl --script
;;; decode-bytecode.lisp - Minimal ARM64 bytecode decoder for debugging

(defun read-u32-le (stream)
  (let ((b0 (read-byte stream nil nil))
        (b1 (read-byte stream nil nil))
        (b2 (read-byte stream nil nil))
        (b3 (read-byte stream nil nil)))
    (and b3 (logior b0 (ash b1 8) (ash b2 16) (ash b3 24)))))

(defun sign-extend (value bits)
  (let* ((shift (- 64 bits))
         (extended (ash (ash value shift) (- shift))))
    extended))

(defun decode-stp/ldp (word base)
  (let* ((imm7 (logand (ash word -15) #x7F))
         (rt2 (logand (ash word -10) #x1F))
         (rn (logand (ash word -5) #x1F))
         (rt (logand word #x1F))
         (imm-bytes (* imm7 8))
         (mnemonic (if (= base #xA9000000) "STP" "LDP")))
    (format nil "~A x~A, x~A, [x~A, #x~X]" mnemonic rt rt2 rn imm-bytes)))

(defun decode-movz/movk (word base)
  (let* ((rd (logand word #x1F))
         (imm16 (logand (ash word -5) #xFFFF))
         (hw (logand (ash word -21) #x3))
         (lsls (* hw 16))
         (mnemonic (if (= base #xD2800000) "MOVZ" "MOVK")))
    (format nil "~A x~A, #x~X, LSL #x~X" mnemonic rd imm16 lsls)))

(defun decode-add/sub-imm (word base)
  (let* ((rd (logand word #x1F))
         (rn (logand (ash word -5) #x1F))
         (imm12 (logand (ash word -10) #xFFF))
         (mnemonic (if (= base #x91000000) "ADD" "SUB")))
    (format nil "~A x~A, x~A, #x~X" mnemonic rd rn imm12)))

(defun decode-str/ldr (word base)
  (let* ((rt (logand word #x1F))
         (rn (logand (ash word -5) #x1F))
         (imm12 (logand (ash word -10) #xFFF))
         (imm-bytes (* imm12 8))
         (mnemonic (if (= base #xF9000000) "STR" "LDR")))
    (format nil "~A x~A, [x~A, #x~X]" mnemonic rt rn imm-bytes)))

(defun decode-cmp (word)
  (let ((rm (logand (ash word -16) #x1F))
        (rn (logand (ash word -5) #x1F)))
    (format nil "CMP x~A, x~A" rn rm)))

(defun decode-cset (word)
  (let ((rd (logand word #x1F))
        (cond (logand (ash word -12) #xF)))
    (format nil "CSET x~A, #x~X" rd cond)))

(defun decode-ubfm (word)
  (let ((rd (logand word #x1F))
        (rn (logand (ash word -5) #x1F))
        (immr (logand (ash word -16) #x3F))
        (imms (logand (ash word -10) #x3F)))
    (format nil "UBFM x~A, x~A, #x~X, #x~X" rd rn immr imms)))

(defun decode-bl (word)
  (let* ((imm26 (logand word #x03FFFFFF))
         (offset (sign-extend imm26 26)))
    (format nil "BL #x~X" offset)))

(defun decode-b (word)
  (let* ((imm26 (logand word #x03FFFFFF))
         (offset (sign-extend imm26 26)))
    (format nil "B #x~X" offset)))

(defun decode-b-cond (word)
  (let* ((imm19 (logand (ash word -5) #x7FFFF))
         (cond (logand word #xF))
         (offset (sign-extend imm19 19)))
    (format nil "B.cond #x~X (cond #x~X)" offset cond)))

(defun decode-blr (word)
  (let ((rn (logand (ash word -5) #x1F)))
    (format nil "BLR x~A" rn)))

(defun decode-mov (word)
  (let ((rd (logand word #x1F))
        (rm (logand (ash word -16) #x1F)))
    (format nil "MOV x~A, x~A" rd rm)))

(defun decode-instr (word)
  (cond
    ((= (logand word #xFFC00000) #xA9000000) (decode-stp/ldp word #xA9000000))
    ((= (logand word #xFFC00000) #xA9400000) (decode-stp/ldp word #xA9400000))
    ((= (logand word #xFF800000) #xD2800000) (decode-movz/movk word #xD2800000))
    ((= (logand word #xFF800000) #xF2800000) (decode-movz/movk word #xF2800000))
    ((= (logand word #xFF0003E0) #xAA0003E0) (decode-mov word))
    ((= (logand word #xFF000000) #x94000000) (decode-bl word))
    ((= (logand word #xFF000000) #x14000000) (decode-b word))
    ((= (logand word #xFFFFFC1F) #xD63F0000) (decode-blr word))
    ((= word #xD65F03C0) "RET")
    ((= (logand word #xFF800000) #x91000000) (decode-add/sub-imm word #x91000000))
    ((= (logand word #xFF800000) #xD1000000) (decode-add/sub-imm word #xD1000000))
    ((= (logand word #xFFC00000) #xF9000000) (decode-str/ldr word #xF9000000))
    ((= (logand word #xFFC00000) #xF9400000) (decode-str/ldr word #xF9400000))
    ((= (logand word #xFF00001F) #xEB00001F) (decode-cmp word))
    ((= (logand word #xFF000010) #x54000000) (decode-b-cond word))
    ((= (logand word #xFF0003FF) #x9A9F07E0) (decode-cset word))
    ((= (logand word #xFF800000) #xD3400000) (decode-ubfm word))
    (t (format nil "<unknown #x~8,'0X>" word))))

(let* ((argv (rest sb-ext:*posix-argv*))
       (file (first argv)))
  (unless file
    (format t "Usage: decode-bytecode.lisp <bytecode-file>~%")
    (sb-ext:quit :unix-status 1))
  (with-open-file (in file :element-type '(unsigned-byte 8))
    (let ((words '())
          (count 0))
      (loop for word = (read-u32-le in)
            while word do
            (push word words)
            (incf count))
      (setf words (nreverse words))
      (format t "Bytecode size: ~A bytes~%~%" (* count 4))
      (format t "Offset  Instruction~%")
      (format t "------  -----------~%")
      (loop for word in words
            for idx from 0 do
              (format t "#x~4,'0X  ~A~%"
                      (* idx 4)
                      (decode-instr word))))))
