/* Habu Standalone Executable Template
 *
 * This file is generated by habu deliver.
 * It contains the compiled ARM64 machine code and links with the Habu runtime.
 */

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <sys/mman.h>

/* Include Habu runtime headers */
#include "runtime/habu.h"

/* ============================================================================
 * GENERATED MACHINE CODE
 * ============================================================================
 * This array contains the compiled ARM64 machine code.
 * It will be copied to executable memory at runtime.
 */
static const unsigned char g_code[] = {
/* BEGIN_CODE */
    0x00
/* END_CODE */
};

static const size_t g_code_size = sizeof(g_code);

/* Entry point offset within the code (0 = start of code) */
static const size_t g_entry_offset = /* ENTRY_OFFSET_PLACEHOLDER */ 0;

/* ============================================================================
 * RUNTIME SETUP
 * ============================================================================
 */

/* Runtime function table - matches indices in codegen */
static void* g_runtime_table[64];

static void setup_runtime_table(void *code_base) {
    g_runtime_table[0] = (void*)habu_cons;
    g_runtime_table[1] = (void*)habu_car;
    g_runtime_table[2] = (void*)habu_cdr;
    g_runtime_table[3] = (void*)habu_make_closure;
    g_runtime_table[4] = (void*)habu_closure_code;
    g_runtime_table[5] = (void*)habu_closure_env;
    g_runtime_table[6] = code_base;  /* Code base pointer for closures */
    g_runtime_table[7] = (void*)habu_make_vector;
    g_runtime_table[8] = (void*)habu_vector_set;
    g_runtime_table[9] = (void*)habu_vector_ref;
    g_runtime_table[10] = (void*)habu_make_string_from_vector;
    g_runtime_table[11] = (void*)habu_make_symbol_from_string;
    g_runtime_table[12] = (void*)habu_string_length_raw;
    g_runtime_table[13] = (void*)habu_symbol_name;
    g_runtime_table[14] = (void*)habu_set_car;
    g_runtime_table[15] = (void*)habu_set_cdr;
    g_runtime_table[16] = (void*)habu_string_ref;
    g_runtime_table[17] = (void*)habu_values_set;
    g_runtime_table[18] = (void*)habu_values_get;
    g_runtime_table[19] = (void*)habu_make_hash_table;
    g_runtime_table[20] = (void*)habu_gethash;
    g_runtime_table[21] = (void*)habu_puthash;
    g_runtime_table[22] = (void*)habu_remhash;
    g_runtime_table[23] = (void*)habu_hash_table_count;
    g_runtime_table[24] = (void*)habu_string_concat;
    g_runtime_table[25] = (void*)habu_string_substring;
    g_runtime_table[26] = (void*)habu_fixnum_to_string;
    g_runtime_table[27] = (void*)habu_values_count_get;
    g_runtime_table[28] = (void*)habu_gensym;
    /* Float operations */
    g_runtime_table[29] = (void*)habu_make_float;
    g_runtime_table[30] = (void*)habu_float_add;
    g_runtime_table[31] = (void*)habu_float_sub;
    g_runtime_table[32] = (void*)habu_float_mul;
    g_runtime_table[33] = (void*)habu_float_div;
    g_runtime_table[34] = (void*)habu_float_lt;
    g_runtime_table[35] = (void*)habu_float_gt;
    g_runtime_table[36] = (void*)habu_float_le;
    g_runtime_table[37] = (void*)habu_float_ge;
    g_runtime_table[38] = (void*)habu_float_eq;
    g_runtime_table[39] = (void*)habu_fixnum_to_float;
    g_runtime_table[40] = (void*)habu_float_to_fixnum;
    g_runtime_table[41] = (void*)habu_float_value;
    /* File I/O */
    g_runtime_table[42] = (void*)habu_open_file;
    g_runtime_table[43] = (void*)habu_close_file;
    g_runtime_table[44] = (void*)habu_read_line;
    g_runtime_table[45] = (void*)habu_write_string;
    g_runtime_table[46] = (void*)habu_read_file;
    g_runtime_table[47] = (void*)habu_write_file;
    /* Print */
    g_runtime_table[48] = (void*)habu_print_value;
    g_runtime_table[49] = (void*)habu_println_value;
    /* Profiling */
    g_runtime_table[50] = (void*)habu_get_time_ns;
}

/* ============================================================================
 * MAIN ENTRY POINT
 * ============================================================================
 */

int main(int argc, char **argv) {
    (void)argc;
    (void)argv;

    /* Initialize Habu runtime */
    habu_init(4 * 1024 * 1024);  /* 4MB heap */
    habu_io_init();

    /* Allocate executable memory for code */
    size_t page_size = 4096;
    size_t alloc_size = ((g_code_size + page_size - 1) / page_size) * page_size;

    void *exec_mem = mmap(NULL, alloc_size,
                          PROT_READ | PROT_WRITE,
                          MAP_PRIVATE | MAP_ANONYMOUS,
                          -1, 0);

    if (exec_mem == MAP_FAILED) {
        perror("mmap");
        return 1;
    }

    /* Copy code to executable memory */
    memcpy(exec_mem, g_code, g_code_size);

    /* Make memory executable */
    if (mprotect(exec_mem, alloc_size, PROT_READ | PROT_EXEC) != 0) {
        perror("mprotect");
        munmap(exec_mem, alloc_size);
        return 1;
    }

    /* Setup runtime table with code base */
    setup_runtime_table(exec_mem);

    /* Call entry point */
    typedef int64_t (*entry_fn_t)(void**);
    entry_fn_t entry = (entry_fn_t)((char*)exec_mem + g_entry_offset);
    int64_t result = entry(g_runtime_table);

    /* Cleanup */
    munmap(exec_mem, alloc_size);
    habu_shutdown();

    /* Return exit code based on result */
    if ((result & 0xF) == 0) {
        /* Fixnum - use as exit code */
        return (int)(result >> 4);
    }
    return 0;
}
