;;; ============================================================
;;; Habu Native Compiler - Self-Hosting ARM64 Lisp Compiler
;;; ============================================================
;;;
;;; This file bundles the pure-Habu compiler for delivery as a
;;; standalone native executable. Order matters: helpers before callers.
;;;
;;; Components (in dependency order):
;;; 1. ARM64 instruction encoders
;;; 2. Utility functions
;;; 3. Reader (source code parser)
;;; 4. Code generator (IR to ARM64)
;;; 5. IR generator (source to IR)
;;; 6. Multi-function compiler
;;; 7. Entry point

;;; ============================================================
;;; Part 1: ARM64 Instruction Encoders
;;; ============================================================

(defun encode-word-le (word)
  (list (logand word #xFF)
        (logand (ash word -8) #xFF)
        (logand (ash word -16) #xFF)
        (logand (ash word -24) #xFF)))

(defun movz (rd imm)
  (encode-word-le (logior #xD2800000 (ash (logand imm #xFFFF) 5) rd)))

(defun add-reg (rd rn rm)
  (encode-word-le (logior #x8B000000 (ash rm 16) (ash rn 5) rd)))

(defun sub-reg (rd rn rm)
  (encode-word-le (logior #xCB000000 (ash rm 16) (ash rn 5) rd)))

(defun mul-reg (rd rn rm)
  (encode-word-le (logior #x9B007C00 (ash rm 16) (ash rn 5) rd)))

(defun sdiv-reg (rd rn rm)
  (encode-word-le (logior #x9AC00C00 (ash rm 16) (ash rn 5) rd)))

(defun lsl-imm (rd rn shift)
  (let* ((immr (logand (- #x40 shift) #x3F))
         (imms (- #x3F shift)))
    (encode-word-le (logior #xD3400000 (ash immr 16) (ash imms 10) (ash rn 5) rd))))

(defun lsr-imm (rd rn shift)
  (encode-word-le (logior #xD340FC00 (ash shift 16) (ash rn 5) rd)))

(defun mov-reg (rd rm)
  (encode-word-le (logior #xAA0003E0 (ash rm 16) rd)))

(defun and-reg (rd rn rm)
  (encode-word-le (logior #x8A000000 (ash rm 16) (ash rn 5) rd)))

(defun orr-reg (rd rn rm)
  (encode-word-le (logior #xAA000000 (ash rm 16) (ash rn 5) rd)))

(defun ldr-offset (rt rn offset)
  (encode-word-le (logior #xF9400000 (ash (ash offset -3) 10) (ash rn 5) rt)))

(defun str-offset (rt rn offset)
  (encode-word-le (logior #xF9000000 (ash (ash offset -3) 10) (ash rn 5) rt)))

(defun add-imm (rd rn imm)
  (encode-word-le (logior #x91000000 (ash (logand imm #xFFF) 10) (ash rn 5) rd)))

(defun sub-imm (rd rn imm)
  (encode-word-le (logior #xD1000000 (ash (logand imm #xFFF) 10) (ash rn 5) rd)))

(defun stp-offset (rt1 rt2 rn imm)
  (encode-word-le (logior #xA9000000 (ash (logand (ash imm -3) #x7F) 15) (ash rt2 10) (ash rn 5) rt1)))

(defun ldp-offset (rt1 rt2 rn imm)
  (encode-word-le (logior #xA9400000 (ash (logand (ash imm -3) #x7F) 15) (ash rt2 10) (ash rn 5) rt1)))

(defun cmp-reg (rn rm)
  (encode-word-le (logior #xEB00001F (ash rm 16) (ash rn 5))))

(defun cset (rd cond-code)
  (encode-word-le (logior #x9A9F07E0 (ash (logxor cond-code 1) 12) rd)))

(defun b-offset (offset)
  (encode-word-le (logior #x14000000 (logand (ash offset -2) #x3FFFFFF))))

(defun bl-offset (offset)
  (encode-word-le (logior #x94000000 (logand (ash offset -2) #x3FFFFFF))))

(defun b-cond (cond-code offset)
  (encode-word-le (logior #x54000000 (ash (logand (ash offset -2) #x7FFFF) 5) cond-code)))

(defun ret ()
  (encode-word-le #xD65F03C0))

(defun movk (rd imm shift)
  (encode-word-le (logior #xF2800000 (ash (ash shift -4) 21) (ash (logand imm #xFFFF) 5) rd)))

(defun blr (rn)
  (encode-word-le (logior #xD63F0000 (ash rn 5))))

(defun load-addr (rd addr)
  (let ((lo16 (logand addr #xFFFF))
        (hi16 (logand (ash addr -16) #xFFFF))
        (hi32 (logand (ash addr -32) #xFFFF))
        (hi48 (logand (ash addr -48) #xFFFF)))
    (append (movz rd lo16)
            (if (> hi16 0) (movk rd hi16 16) nil)
            (if (> hi32 0) (movk rd hi32 32) nil)
            (if (> hi48 0) (movk rd hi48 48) nil))))

(defun cond-eq () 0)
(defun cond-ne () 1)
(defun cond-lt () 11)
(defun cond-le () 13)
(defun cond-gt () 12)
(defun cond-ge () 10)

;;; ============================================================
;;; Part 2: Utility Functions
;;; ============================================================

(defun has-tag? (ir tag)
  (and (consp ir) (eq (car ir) tag)))

(defun op= (sym name)
  (and (symbolp sym) (string= (symbol-name sym) name)))

(defun env-lookup (sym env)
  (if (null env)
      nil
      (if (eq (caar env) sym)
          (cdar env)
          (env-lookup sym (cdr env)))))

(defun env-extend (bindings env)
  (labels ((max-offset (e acc)
             (if (null e) acc
                 (max-offset (cdr e) (let ((off (cdar e))) (if (> off acc) off acc)))))
           (add-bindings (bs offset acc)
             (if (null bs) acc
                 (add-bindings (cdr bs) (+ offset 1) (cons (cons (caar bs) offset) acc)))))
    (let ((max-off (if env (max-offset env -1) -1)))
      (append (reverse (add-bindings bindings (+ max-off 1) nil)) env))))

(defun remove-duplicates-simple (lst)
  (labels ((iter (remaining seen)
             (if (null remaining)
                 (reverse seen)
                 (let ((el (car remaining)))
                   (if (member el seen)
                       (iter (cdr remaining) seen)
                       (iter (cdr remaining) (cons el seen)))))))
    (iter lst nil)))

(defun count-instrs (code)
  (if (null code) 0 (ash (length code) -2)))

(setq *gensym-counter* 0)

(defun make-unique-name (base)
  (let ((n *gensym-counter*))
    (setq *gensym-counter* (+ n 1))
    (cons base n)))

;;; ============================================================
;;; Part 3: Reader
;;; ============================================================

(defun whitespace? (ch) (or (= ch #x20) (= ch #x09) (= ch #x0A) (= ch #x0D)))
(defun digit? (ch) (and (>= ch #x30) (<= ch #x39)))
(defun hex-digit? (ch) (or (digit? ch) (and (>= ch #x41) (<= ch #x46)) (and (>= ch #x61) (<= ch #x66))))
(defun alpha? (ch) (or (and (>= ch #x41) (<= ch #x5A)) (and (>= ch #x61) (<= ch #x7A))))
(defun symbol-char? (ch)
  (or (alpha? ch) (digit? ch) (= ch #x2D) (= ch #x5F) (= ch #x2B) (= ch #x2A)
      (= ch #x2F) (= ch #x3D) (= ch #x3C) (= ch #x3E) (= ch #x21) (= ch #x3F)
      (= ch #x26) (= ch #x25) (= ch #x3A)))

(defun char-at (source pos)
  (if (< pos (string-length source)) (string-ref source pos) #x0))

(defun digit-val (ch) (- ch #x30))
(defun hex-val (ch)
  (cond ((digit? ch) (- ch #x30))
        ((and (>= ch #x41) (<= ch #x46)) (+ (- ch #x41) #xA))
        ((and (>= ch #x61) (<= ch #x66)) (+ (- ch #x61) #xA))
        (t #x0)))

(defun skip-line (source pos)
  (let ((ch (char-at source pos)))
    (if (or (= ch #x0A) (= ch #x0)) (+ pos 1) (skip-line source (+ pos 1)))))

(defun skip-ws (source pos)
  (let ((ch (char-at source pos)))
    (cond ((whitespace? ch) (skip-ws source (+ pos 1)))
          ((= ch #x3B) (skip-ws source (skip-line source (+ pos 1))))
          (t pos))))

(defun read-digits (source pos n)
  (let ((ch (char-at source pos)))
    (if (digit? ch)
        (read-digits source (+ pos 1) (+ (* n 10) (digit-val ch)))
        (cons n pos))))

(defun read-int (source pos)
  (let ((neg nil) (start pos))
    (let ((ch (char-at source pos)))
      (cond ((= ch #x2D) (setq neg t) (setq start (+ pos 1)))
            ((= ch #x2B) (setq start (+ pos 1)))))
    (let* ((result (read-digits source start 0))
           (val (car result))
           (end (cdr result)))
      (cons (if neg (- 0 val) val) end))))

(defun read-hex-digits (source pos n)
  (let ((ch (char-at source pos)))
    (if (hex-digit? ch)
        (read-hex-digits source (+ pos 1) (+ (* n 16) (hex-val ch)))
        (cons n pos))))

(defun read-hex (source pos)
  (read-hex-digits source pos 0))

(defun chars-to-string (chars)
  (let* ((len (length chars))
         (vec (make-vector len)))
    (dotimes (i len)
      (vector-set vec i (nth i chars)))
    (make-string-from-vector vec)))

(defun read-sym-chars (source pos chars)
  (let ((ch (char-at source pos)))
    (if (symbol-char? ch)
        (read-sym-chars source (+ pos 1) (cons ch chars))
        (cons chars pos))))

(defun read-sym (source pos)
  (let* ((result (read-sym-chars source pos nil))
         (chars (car result))
         (end (cdr result))
         (name (chars-to-string (reverse chars)))
         (uname (string-upcase name)))
    (cons (cond ((string= uname "NIL") nil)
                ((string= uname "T") t)
                (t (intern uname)))
          end)))

(defun read-str-chars (source pos chars)
  (let ((ch (char-at source pos)))
    (cond
      ((= ch #x22) (cons chars (+ pos 1)))
      ((= ch #x5C)
       (let* ((esc (char-at source (+ pos 1)))
              (esc-char (cond ((= esc #x6E) #x0A) ((= esc #x74) #x09) ((= esc #x72) #x0D) (t esc))))
         (read-str-chars source (+ pos 2) (cons esc-char chars))))
      ((= ch #x0) (cons chars pos))
      (t (read-str-chars source (+ pos 1) (cons ch chars))))))

(defun read-str (source pos)
  (let* ((result (read-str-chars source (+ pos 1) nil))
         (chars (car result))
         (end (cdr result)))
    (cons (chars-to-string (reverse chars)) end)))

(defun habu-read (source pos)
  (labels
      ((read-list-elems (pos)
         (let* ((pos2 (skip-ws source pos))
                (ch (char-at source pos2)))
           (cond
             ((= ch #x29) (cons nil (+ pos2 1)))
             ((= ch #x2E)
              (let* ((result (read-one (+ pos2 1)))
                     (cdr-val (car result))
                     (pos3 (cdr result))
                     (pos4 (skip-ws source pos3)))
                (cons cdr-val (+ pos4 1))))
             ((= ch #x0) (cons nil pos2))
             (t (let* ((elem-result (read-one pos2))
                       (elem (car elem-result))
                       (pos3 (cdr elem-result))
                       (rest-result (read-list-elems pos3)))
                  (cons (cons elem (car rest-result)) (cdr rest-result)))))))
       (read-list (pos) (read-list-elems (+ pos 1)))
       (read-sharp (pos)
         (let ((ch (char-at source (+ pos 1))))
           (cond
             ((or (= ch #x78) (= ch #x58)) (read-hex source (+ pos 2)))
             ((= ch #x27)
              (let ((result (read-one (+ pos 2))))
                (cons (list 'function (car result)) (cdr result))))
             ((= ch #x5C)
              (let ((ch2 (char-at source (+ pos 2))))
                (if (alpha? (char-at source (+ pos 3)))
                    (let* ((result (read-sym-chars source (+ pos 2) nil))
                           (name (chars-to-string (reverse (car result)))))
                      (cons (cond ((string= name "newline") #x0A) ((string= name "space") #x20)
                                  ((string= name "tab") #x09) (t ch2))
                            (cdr result)))
                    (cons ch2 (+ pos 3)))))
             (t (cons nil (+ pos 2))))))
       (read-one (pos)
         (let* ((pos2 (skip-ws source pos))
                (ch (char-at source pos2)))
           (if (>= pos2 (string-length source))
               (cons nil pos2)
               (cond
                 ((= ch #x22) (read-str source pos2))
                 ((= ch #x28) (read-list pos2))
                 ((= ch #x27)
                  (let ((result (read-one (+ pos2 1))))
                    (cons (list 'quote (car result)) (cdr result))))
                 ((= ch #x60)
                  (let ((result (read-one (+ pos2 1))))
                    (cons (list 'quasiquote (car result)) (cdr result))))
                 ((= ch #x2C)
                  (if (= (char-at source (+ pos2 1)) #x40)
                      (let ((result (read-one (+ pos2 2))))
                        (cons (list 'unquote-splicing (car result)) (cdr result)))
                      (let ((result (read-one (+ pos2 1))))
                        (cons (list 'unquote (car result)) (cdr result)))))
                 ((= ch #x23) (read-sharp pos2))
                 ((or (digit? ch)
                      (and (or (= ch #x2D) (= ch #x2B))
                           (digit? (char-at source (+ pos2 1)))))
                  (read-int source pos2))
                 ((symbol-char? ch) (read-sym source pos2))
                 ((= ch #x29) (cons nil (+ pos2 1)))
                 (t (read-one (+ pos2 1))))))))
    (read-one pos)))

(defun read-from-string (source)
  (car (habu-read source 0)))

(defun read-all-from-string (source)
  (let ((len (string-length source)))
    (labels ((read-all (pos acc)
               (let ((pos2 (skip-ws source pos)))
                 (if (>= pos2 len)
                     (reverse acc)
                     (let ((result (habu-read source pos2)))
                       (read-all (cdr result) (cons (car result) acc)))))))
      (read-all 0 nil))))

(defun read-source-file (path)
  (let ((content (read-file path)))
    (if content (read-all-from-string content) nil)))

;;; ============================================================
;;; Part 4: Stack Frame Constants
;;; ============================================================

(setq *stack-frame-size* #xFF0)
(setq *env-base-offset* #x180)
(setq *temp-slot-base* #x40)
(setq *temp-slot-guard* #x180)
(setq *arg-spill-base* #x200)
(setq *arg-spill-stride* 8)

(defun temp-slot-offset (depth)
  (let ((offset (+ *temp-slot-base* (* depth 8))))
    (if (>= offset *temp-slot-guard*)
        (+ *temp-slot-guard* (* (- depth (ash (- *temp-slot-guard* *temp-slot-base*) -3)) 8))
        offset)))

(defun arg-spill-offset (idx)
  (+ *arg-spill-base* (* idx *arg-spill-stride*)))

;;; ============================================================
;;; Part 5: Code Generator Prologue/Epilogue
;;; ============================================================

(defun codegen-prologue ()
  (append
   (stp-offset 29 30 31 (- *stack-frame-size*))
   (sub-imm 31 31 *stack-frame-size*)
   (mov-reg 29 31)
   (stp-offset 19 20 31 16)
   (stp-offset 21 22 31 32)
   (stp-offset 23 24 31 48)
   (mov-reg 20 31)
   (add-imm 20 20 *env-base-offset*)))

(defun codegen-epilogue ()
  (append
   (ldp-offset 23 24 31 48)
   (ldp-offset 21 22 31 32)
   (ldp-offset 19 20 31 16)
   (add-imm 31 31 *stack-frame-size*)
   (ldp-offset 29 30 31 0)
   (ret)))

;;; ============================================================
;;; Part 6: IR Compiler (Source to IR) - Simplified
;;; ============================================================

(defun quote->ir (obj)
  (cond
    ((numberp obj) (list 'lit obj))
    ((null obj) (list 'lit 0))
    ((symbolp obj) (list 'symbol-lit (symbol-name obj)))
    ((consp obj) (list 'cons-call (quote->ir (car obj)) (quote->ir (cdr obj))))
    (t (list 'lit 0))))

(defun compile-expr (expr env fenv)
  (cond
    ((numberp expr) (list 'lit expr))
    ((symbolp expr)
     (let ((off (env-lookup expr env)))
       (if off (list 'var off) (list 'lit 0))))
    ((consp expr)
     (let ((op (car expr)))
       (cond
         ((eq op '+)
          (let ((args (cdr expr)))
            (if (null args) (list 'lit 0)
                (if (null (cdr args)) (compile-expr (car args) env fenv)
                    (if (null (cddr args))
                        (list 'add (compile-expr (car args) env fenv) (compile-expr (cadr args) env fenv))
                        (compile-expr (cons '+ (cons (list '+ (car args) (cadr args)) (cddr args))) env fenv))))))
         ((eq op '-)
          (let ((args (cdr expr)))
            (if (null args) (list 'lit 0)
                (if (null (cdr args)) (list 'sub (list 'lit 0) (compile-expr (car args) env fenv))
                    (if (null (cddr args))
                        (list 'sub (compile-expr (car args) env fenv) (compile-expr (cadr args) env fenv))
                        (compile-expr (cons '- (cons (list '- (car args) (cadr args)) (cddr args))) env fenv))))))
         ((eq op '*)
          (let ((args (cdr expr)))
            (if (null args) (list 'lit 1)
                (if (null (cdr args)) (compile-expr (car args) env fenv)
                    (if (null (cddr args))
                        (list 'mul (compile-expr (car args) env fenv) (compile-expr (cadr args) env fenv))
                        (compile-expr (cons '* (cons (list '* (car args) (cadr args)) (cddr args))) env fenv))))))
         ((eq op '=)
          (list 'cmp-eq (compile-expr (cadr expr) env fenv) (compile-expr (caddr expr) env fenv)))
         ((eq op '<)
          (list 'cmp-lt (compile-expr (cadr expr) env fenv) (compile-expr (caddr expr) env fenv)))
         ((eq op '>)
          (list 'cmp-gt (compile-expr (cadr expr) env fenv) (compile-expr (caddr expr) env fenv)))
         ((eq op '<=)
          (list 'cmp-le (compile-expr (cadr expr) env fenv) (compile-expr (caddr expr) env fenv)))
         ((eq op '>=)
          (list 'cmp-ge (compile-expr (cadr expr) env fenv) (compile-expr (caddr expr) env fenv)))
         ((eq op 'if)
          (list 'if-expr
                (compile-expr (cadr expr) env fenv)
                (compile-expr (caddr expr) env fenv)
                (compile-expr (cadddr expr) env fenv)))
         ((eq op 'let)
          (let* ((bindings (cadr expr))
                 (body (caddr expr)))
            (labels ((process (bs env-acc bind-vals bind-names)
                       (if (null bs)
                           (list env-acc (reverse bind-vals) (reverse bind-names))
                           (let* ((b (car bs))
                                  (name (if (consp b) (car b) b))
                                  (val (if (consp b) (cadr b) 0))
                                  (val-ir (compile-expr val env fenv))
                                  (new-env (env-extend (list (list name)) env-acc)))
                             (process (cdr bs) new-env (cons val-ir bind-vals) (cons name bind-names))))))
              (let* ((r (process bindings env nil nil))
                     (new-env (car r))
                     (bind-vals (cadr r))
                     (bind-names (caddr r))
                     (offs (mapcar (lambda (n) (env-lookup n new-env)) bind-names))
                     (body-ir (compile-expr body new-env fenv)))
                (list 'let-expr bind-vals body-ir (length bindings) offs)))))
         ((eq op 'let*)
          (let ((bindings (cadr expr)) (body (caddr expr)))
            (if (null bindings)
                (compile-expr body env fenv)
                (compile-expr (list 'let (list (car bindings)) (list 'let* (cdr bindings) body)) env fenv))))
         ((eq op 'quote) (quote->ir (cadr expr)))
         ((eq op 'cons) (list 'cons-call (compile-expr (cadr expr) env fenv) (compile-expr (caddr expr) env fenv)))
         ((eq op 'car) (list 'car-call (compile-expr (cadr expr) env fenv)))
         ((eq op 'cdr) (list 'cdr-call (compile-expr (cadr expr) env fenv)))
         ((eq op 'list)
          (labels ((build (args)
                     (if (null args) (list 'lit 0)
                         (list 'cons-call (compile-expr (car args) env fenv) (build (cdr args))))))
            (build (cdr expr))))
         ((eq op 'null)
          (list 'cmp-eq (compile-expr (cadr expr) env fenv) (list 'lit 0)))
         ((eq op 'numberp)
          (list 'cmp-eq (list 'get-tag (compile-expr (cadr expr) env fenv)) (list 'lit 0)))
         ((eq op 'consp)
          (list 'cmp-eq (list 'get-tag (compile-expr (cadr expr) env fenv)) (list 'lit 1)))
         ;; User function call
         (t
          (if (and fenv (assoc op fenv))
              (list 'call-fn op (mapcar (lambda (a) (compile-expr a env fenv)) (cdr expr)))
              (list 'lit 0))))))
    (t (list 'lit 0))))

;;; ============================================================
;;; Part 7: Code Generator (IR to ARM64)
;;; ============================================================

(defun codegen-expr (ir runtime-addrs fn-offsets current-offset temp-depth)
  (cond
    ((has-tag? ir 'lit)
     (let ((tagged (ash (cadr ir) 4)))
       (if (and (>= tagged 0) (< tagged #x10000))
           (movz 0 tagged)
           (load-addr 0 tagged))))
    ((has-tag? ir 'var)
     (append (sub-imm 1 20 (* (cadr ir) 8)) (ldr-offset 0 1 0)))
    ((has-tag? ir 'get-tag)
     (let ((arg-code (codegen-expr (cadr ir) runtime-addrs fn-offsets current-offset temp-depth)))
       (append arg-code (movz 1 #xF) (and-reg 0 0 1) (lsl-imm 0 0 4))))
    ((has-tag? ir 'add)
     (let* ((x24-slot (temp-slot-offset temp-depth))
            (left-slot (temp-slot-offset (+ temp-depth 1)))
            (nested-depth (+ temp-depth 2))
            (left-code (codegen-expr (cadr ir) runtime-addrs fn-offsets nil nested-depth))
            (right-code (codegen-expr (caddr ir) runtime-addrs fn-offsets nil nested-depth)))
       (append (str-offset 24 31 x24-slot)
               left-code (str-offset 0 31 left-slot)
               (ldr-offset 24 31 x24-slot)
               right-code (mov-reg 1 0)
               (ldr-offset 0 31 left-slot)
               (add-reg 0 0 1))))
    ((has-tag? ir 'sub)
     (let* ((x24-slot (temp-slot-offset temp-depth))
            (left-slot (temp-slot-offset (+ temp-depth 1)))
            (nested-depth (+ temp-depth 2))
            (left-code (codegen-expr (cadr ir) runtime-addrs fn-offsets nil nested-depth))
            (right-code (codegen-expr (caddr ir) runtime-addrs fn-offsets nil nested-depth)))
       (append (str-offset 24 31 x24-slot)
               left-code (str-offset 0 31 left-slot)
               (ldr-offset 24 31 x24-slot)
               right-code (mov-reg 1 0)
               (ldr-offset 0 31 left-slot)
               (sub-reg 0 0 1))))
    ((has-tag? ir 'mul)
     (let* ((x24-slot (temp-slot-offset temp-depth))
            (left-slot (temp-slot-offset (+ temp-depth 1)))
            (nested-depth (+ temp-depth 2))
            (left-code (codegen-expr (cadr ir) runtime-addrs fn-offsets nil nested-depth))
            (right-code (codegen-expr (caddr ir) runtime-addrs fn-offsets nil nested-depth)))
       (append (str-offset 24 31 x24-slot)
               left-code (str-offset 0 31 left-slot)
               (ldr-offset 24 31 x24-slot)
               right-code (mov-reg 1 0)
               (ldr-offset 0 31 left-slot)
               (lsr-imm 0 0 4) (lsr-imm 1 1 4) (mul-reg 0 0 1) (lsl-imm 0 0 4))))
    ((has-tag? ir 'cmp-eq)
     (let* ((x24-slot (temp-slot-offset temp-depth))
            (left-slot (temp-slot-offset (+ temp-depth 1)))
            (nested-depth (+ temp-depth 2))
            (left-code (codegen-expr (cadr ir) runtime-addrs fn-offsets nil nested-depth))
            (right-code (codegen-expr (caddr ir) runtime-addrs fn-offsets nil nested-depth)))
       (append (str-offset 24 31 x24-slot)
               left-code (str-offset 0 31 left-slot)
               (ldr-offset 24 31 x24-slot)
               right-code (mov-reg 1 0)
               (ldr-offset 0 31 left-slot)
               (cmp-reg 0 1) (cset 0 (cond-eq)) (lsl-imm 0 0 4))))
    ((has-tag? ir 'cmp-lt)
     (let* ((x24-slot (temp-slot-offset temp-depth))
            (left-slot (temp-slot-offset (+ temp-depth 1)))
            (nested-depth (+ temp-depth 2))
            (left-code (codegen-expr (cadr ir) runtime-addrs fn-offsets nil nested-depth))
            (right-code (codegen-expr (caddr ir) runtime-addrs fn-offsets nil nested-depth)))
       (append (str-offset 24 31 x24-slot)
               left-code (str-offset 0 31 left-slot)
               (ldr-offset 24 31 x24-slot)
               right-code (mov-reg 1 0)
               (ldr-offset 0 31 left-slot)
               (cmp-reg 0 1) (cset 0 (cond-lt)) (lsl-imm 0 0 4))))
    ((has-tag? ir 'cmp-gt)
     (let* ((x24-slot (temp-slot-offset temp-depth))
            (left-slot (temp-slot-offset (+ temp-depth 1)))
            (nested-depth (+ temp-depth 2))
            (left-code (codegen-expr (cadr ir) runtime-addrs fn-offsets nil nested-depth))
            (right-code (codegen-expr (caddr ir) runtime-addrs fn-offsets nil nested-depth)))
       (append (str-offset 24 31 x24-slot)
               left-code (str-offset 0 31 left-slot)
               (ldr-offset 24 31 x24-slot)
               right-code (mov-reg 1 0)
               (ldr-offset 0 31 left-slot)
               (cmp-reg 0 1) (cset 0 (cond-gt)) (lsl-imm 0 0 4))))
    ((has-tag? ir 'cmp-le)
     (let* ((x24-slot (temp-slot-offset temp-depth))
            (left-slot (temp-slot-offset (+ temp-depth 1)))
            (nested-depth (+ temp-depth 2))
            (left-code (codegen-expr (cadr ir) runtime-addrs fn-offsets nil nested-depth))
            (right-code (codegen-expr (caddr ir) runtime-addrs fn-offsets nil nested-depth)))
       (append (str-offset 24 31 x24-slot)
               left-code (str-offset 0 31 left-slot)
               (ldr-offset 24 31 x24-slot)
               right-code (mov-reg 1 0)
               (ldr-offset 0 31 left-slot)
               (cmp-reg 0 1) (cset 0 (cond-le)) (lsl-imm 0 0 4))))
    ((has-tag? ir 'cmp-ge)
     (let* ((x24-slot (temp-slot-offset temp-depth))
            (left-slot (temp-slot-offset (+ temp-depth 1)))
            (nested-depth (+ temp-depth 2))
            (left-code (codegen-expr (cadr ir) runtime-addrs fn-offsets nil nested-depth))
            (right-code (codegen-expr (caddr ir) runtime-addrs fn-offsets nil nested-depth)))
       (append (str-offset 24 31 x24-slot)
               left-code (str-offset 0 31 left-slot)
               (ldr-offset 24 31 x24-slot)
               right-code (mov-reg 1 0)
               (ldr-offset 0 31 left-slot)
               (cmp-reg 0 1) (cset 0 (cond-ge)) (lsl-imm 0 0 4))))
    ((has-tag? ir 'cons-call)
     (let* ((x24-slot (temp-slot-offset temp-depth))
            (car-slot (temp-slot-offset (+ temp-depth 1)))
            (nested-depth (+ temp-depth 2))
            (car-code (codegen-expr (cadr ir) runtime-addrs fn-offsets nil nested-depth))
            (cdr-code (codegen-expr (caddr ir) runtime-addrs fn-offsets nil nested-depth)))
       (append (str-offset 24 31 x24-slot)
               car-code (str-offset 0 31 car-slot)
               (ldr-offset 24 31 x24-slot)
               cdr-code (mov-reg 1 0)
               (ldr-offset 0 31 car-slot)
               (ldr-offset 9 19 0) (blr 9))))
    ((has-tag? ir 'car-call)
     (append (codegen-expr (cadr ir) runtime-addrs fn-offsets current-offset temp-depth)
             (ldr-offset 9 19 8) (blr 9)))
    ((has-tag? ir 'cdr-call)
     (append (codegen-expr (cadr ir) runtime-addrs fn-offsets current-offset temp-depth)
             (ldr-offset 9 19 16) (blr 9)))
    ((has-tag? ir 'if-expr)
     (let* ((test-code (codegen-expr (cadr ir) runtime-addrs fn-offsets nil temp-depth))
            (then-code (codegen-expr (caddr ir) runtime-addrs fn-offsets nil temp-depth))
            (else-code (codegen-expr (cadddr ir) runtime-addrs fn-offsets nil temp-depth))
            (then-len (count-instrs then-code))
            (else-len (count-instrs else-code)))
       (append test-code
               (movz 1 0) (cmp-reg 0 1)
               (b-cond (cond-eq) (* (+ then-len 1) 4))
               then-code
               (b-offset (* else-len 4))
               else-code)))
    ((has-tag? ir 'let-expr)
     (let* ((bind-vals (cadr ir))
            (body-ir (caddr ir))
            (offs (nth 4 (cdr ir)))
            (x24-slot (temp-slot-offset temp-depth))
            (nested-depth (+ temp-depth 1))
            (accum (str-offset 24 31 x24-slot)))
       (labels ((gen-bindings (vals offsets acc)
                  (if (null vals) acc
                      (let* ((val-code (codegen-expr (car vals) runtime-addrs fn-offsets nil nested-depth))
                             (store (append (sub-imm 1 20 (* (car offsets) 8)) (str-offset 0 1 0))))
                        (gen-bindings (cdr vals) (cdr offsets)
                                      (append acc (ldr-offset 24 31 x24-slot) val-code store))))))
         (append accum
                 (gen-bindings bind-vals offs nil)
                 (ldr-offset 24 31 x24-slot)
                 (codegen-expr body-ir runtime-addrs fn-offsets nil nested-depth)))))
    ((has-tag? ir 'call-fn)
     (let* ((fn-name (cadr ir))
            (arg-irs (caddr ir))
            (nargs (length arg-irs))
            (x24-slot (temp-slot-offset temp-depth))
            (nested-depth (+ temp-depth 1))
            (fn-offset (if fn-offsets (cdr (assoc fn-name fn-offsets)) nil)))
       (labels ((gen-args (args idx acc)
                  (if (null args) acc
                      (let* ((restore (if (> idx 0) (ldr-offset 24 31 x24-slot) nil))
                             (arg-code (codegen-expr (car args) runtime-addrs fn-offsets nil nested-depth))
                             (store (str-offset 0 31 (arg-spill-offset idx))))
                        (gen-args (cdr args) (+ idx 1)
                                  (append acc restore arg-code store)))))
                (gen-loads (i acc)
                  (if (>= i nargs) acc
                      (gen-loads (+ i 1) (append acc (ldr-offset i 31 (arg-spill-offset i)))))))
         (append (str-offset 24 31 x24-slot)
                 (gen-args arg-irs 0 nil)
                 (ldr-offset 24 31 x24-slot)
                 (gen-loads 0 nil)
                 (movz 23 nargs)
                 (bl-offset 0)))))  ; BL offset computed later
    (t (movz 0 0))))

;;; ============================================================
;;; Part 8: Multi-Function Compiler
;;; ============================================================

(defun compile-defun (name params body env fenv)
  (let* ((bindings (mapcar (lambda (p) (list p)) params))
         (param-env (env-extend bindings env))
         (param-base (if params (env-lookup (car params) param-env) 0))
         (recursive-fenv (cons (cons name nil) fenv))
         (body-ir (compile-expr body param-env recursive-fenv)))
    (list name params body-ir param-base)))

(defun compile-forms-helper (forms env fenv)
  (if (consp forms)
      (let ((form (car forms)))
        (if (and (consp form) (eq (car form) 'defun))
            (let* ((name (cadr form))
                   (params (caddr form))
                   (body (cadddr form))
                   (compiled-fn (compile-defun name params body env fenv))
                   (new-fenv (cons (cons name compiled-fn) fenv))
                   (rest-result (compile-forms-helper (cdr forms) env new-fenv)))
              (list (cons compiled-fn (car rest-result)) (cadr rest-result)))
            (list nil (compile-expr form env fenv))))
      (list nil (list 'lit 0))))

(defun compile-forms (forms)
  (compile-forms-helper forms nil nil))

(defun gen-param-stores (params base idx acc)
  (if (null params)
      acc
      (let ((store (append (mov-reg 22 idx)
                           (sub-imm 21 20 (* (+ base idx) 8))
                           (str-offset 22 21 0))))
        (gen-param-stores (cdr params) base (+ idx 1) (append acc store)))))

(defun codegen-function (fn runtime-addrs fn-offsets current-offset)
  (let* ((params (cadr fn))
         (body-ir (caddr fn))
         (param-base (cadddr fn))
         (param-code (gen-param-stores params param-base 0 nil))
         (body-code (codegen-expr body-ir runtime-addrs fn-offsets nil 0)))
    (append param-code body-code (ret))))

(defun codegen-main-with-runtime (main-ir runtime-addrs)
  (append (codegen-prologue)
          (codegen-expr main-ir runtime-addrs nil nil 0)
          (codegen-epilogue)))

(defun compile-program (forms runtime-addrs)
  (let* ((result (compile-forms forms))
         (fns (car result))
         (main-ir (cadr result))
         (main-code (codegen-main-with-runtime main-ir runtime-addrs))
         (main-size (count-instrs main-code)))
    ;; For now, just return main (no function calls resolved)
    main-code))

;;; ============================================================
;;; Part 9: Entry Point
;;; ============================================================

;;; Test entry point - parse "42" and return it
(defun main ()
  (let* ((source "42")
         (forms (read-all-from-string source)))
    (if (consp forms)
        (car forms)
        0)))

(main)
