;;; ============================================================
;;; Habu Native Compiler - Self-Hosting ARM64 Lisp Compiler
;;; ============================================================
;;;
;;; All functions prefixed with nc- to avoid shadowing built-ins.
;;; Components: ARM64 asm, utils, reader, codegen, IR compiler

;;; ============================================================
;;; Part 1: ARM64 Instruction Encoders (nc-asm-*)
;;; ============================================================

(defun nc-encode-word (word)
  (list (logand word #xFF)
        (logand (ash word -8) #xFF)
        (logand (ash word -16) #xFF)
        (logand (ash word -24) #xFF)))

(defun nc-movz (rd imm)
  (nc-encode-word (logior #xD2800000 (ash (logand imm #xFFFF) 5) rd)))

(defun nc-add-reg (rd rn rm)
  (nc-encode-word (logior #x8B000000 (ash rm 16) (ash rn 5) rd)))

(defun nc-sub-reg (rd rn rm)
  (nc-encode-word (logior #xCB000000 (ash rm 16) (ash rn 5) rd)))

(defun nc-mul-reg (rd rn rm)
  (nc-encode-word (logior #x9B007C00 (ash rm 16) (ash rn 5) rd)))

(defun nc-lsl-imm (rd rn shift)
  (let* ((immr (logand (- #x40 shift) #x3F))
         (imms (- #x3F shift)))
    (nc-encode-word (logior #xD3400000 (ash immr 16) (ash imms 10) (ash rn 5) rd))))

(defun nc-lsr-imm (rd rn shift)
  (nc-encode-word (logior #xD340FC00 (ash shift 16) (ash rn 5) rd)))

(defun nc-mov-reg (rd rm)
  (nc-encode-word (logior #xAA0003E0 (ash rm 16) rd)))

(defun nc-and-reg (rd rn rm)
  (nc-encode-word (logior #x8A000000 (ash rm 16) (ash rn 5) rd)))

(defun nc-ldr-offset (rt rn offset)
  (nc-encode-word (logior #xF9400000 (ash (ash offset -3) 10) (ash rn 5) rt)))

(defun nc-str-offset (rt rn offset)
  (nc-encode-word (logior #xF9000000 (ash (ash offset -3) 10) (ash rn 5) rt)))

(defun nc-add-imm (rd rn imm)
  (nc-encode-word (logior #x91000000 (ash (logand imm #xFFF) 10) (ash rn 5) rd)))

(defun nc-sub-imm (rd rn imm)
  (nc-encode-word (logior #xD1000000 (ash (logand imm #xFFF) 10) (ash rn 5) rd)))

(defun nc-stp-offset (rt1 rt2 rn imm)
  (nc-encode-word (logior #xA9000000 (ash (logand (ash imm -3) #x7F) 15) (ash rt2 10) (ash rn 5) rt1)))

(defun nc-ldp-offset (rt1 rt2 rn imm)
  (nc-encode-word (logior #xA9400000 (ash (logand (ash imm -3) #x7F) 15) (ash rt2 10) (ash rn 5) rt1)))

(defun nc-cmp-reg (rn rm)
  (nc-encode-word (logior #xEB00001F (ash rm 16) (ash rn 5))))

(defun nc-cset (rd cond-code)
  (nc-encode-word (logior #x9A9F07E0 (ash (logxor cond-code 1) 12) rd)))

(defun nc-b-offset (offset)
  (nc-encode-word (logior #x14000000 (logand (ash offset -2) #x3FFFFFF))))

(defun nc-bl-offset (offset)
  (nc-encode-word (logior #x94000000 (logand (ash offset -2) #x3FFFFFF))))

(defun nc-b-cond (cond-code offset)
  (nc-encode-word (logior #x54000000 (ash (logand (ash offset -2) #x7FFFF) 5) cond-code)))

(defun nc-ret ()
  (nc-encode-word #xD65F03C0))

(defun nc-movk (rd imm shift)
  (nc-encode-word (logior #xF2800000 (ash (ash shift -4) 21) (ash (logand imm #xFFFF) 5) rd)))

(defun nc-blr (rn)
  (nc-encode-word (logior #xD63F0000 (ash rn 5))))

(defun nc-load-addr (rd addr)
  (let ((lo16 (logand addr #xFFFF))
        (hi16 (logand (ash addr -16) #xFFFF))
        (hi32 (logand (ash addr -32) #xFFFF))
        (hi48 (logand (ash addr -48) #xFFFF)))
    (append (nc-movz rd lo16)
            (if (> hi16 0) (nc-movk rd hi16 16) nil)
            (if (> hi32 0) (nc-movk rd hi32 32) nil)
            (if (> hi48 0) (nc-movk rd hi48 48) nil))))

(defun nc-cond-eq () 0)
(defun nc-cond-ne () 1)
(defun nc-cond-lt () 11)
(defun nc-cond-le () 13)
(defun nc-cond-gt () 12)
(defun nc-cond-ge () 10)

;;; ============================================================
;;; Part 2: Utility Functions (nc-util-*)
;;; ============================================================

(defun nc-has-tag (ir tag)
  (and (consp ir) (eq (car ir) tag)))

(defun nc-env-lookup (sym env)
  (if (null env)
      nil
      (if (eq (caar env) sym)
          (cdar env)
          (nc-env-lookup sym (cdr env)))))

(defun nc-env-extend (bindings env)
  (labels ((max-off (e acc)
             (if (null e) acc
                 (max-off (cdr e) (let ((o (cdar e))) (if (> o acc) o acc)))))
           (add-bs (bs off acc)
             (if (null bs) acc
                 (add-bs (cdr bs) (+ off 1) (cons (cons (caar bs) off) acc)))))
    (let ((mx (if env (max-off env -1) -1)))
      (append (reverse (add-bs bindings (+ mx 1) nil)) env))))

(defun nc-count-instrs (code)
  (if (null code) 0 (ash (length code) -2)))

;;; ============================================================
;;; Part 3: Reader (nc-read-*)
;;; ============================================================

(defun nc-whitespace-p (ch) (or (= ch #x20) (= ch #x09) (= ch #x0A) (= ch #x0D)))
(defun nc-digit-p (ch) (and (>= ch #x30) (<= ch #x39)))
(defun nc-hex-digit-p (ch) (or (nc-digit-p ch) (and (>= ch #x41) (<= ch #x46)) (and (>= ch #x61) (<= ch #x66))))
(defun nc-alpha-p (ch) (or (and (>= ch #x41) (<= ch #x5A)) (and (>= ch #x61) (<= ch #x7A))))
(defun nc-symbol-char-p (ch)
  (or (nc-alpha-p ch) (nc-digit-p ch) (= ch #x2D) (= ch #x5F) (= ch #x2B) (= ch #x2A)
      (= ch #x2F) (= ch #x3D) (= ch #x3C) (= ch #x3E) (= ch #x21) (= ch #x3F)
      (= ch #x26) (= ch #x25) (= ch #x3A)))

(defun nc-char-at (s pos)
  (if (< pos (string-length s)) (string-ref s pos) 0))

(defun nc-digit-val (ch) (- ch #x30))
(defun nc-hex-val (ch)
  (cond ((nc-digit-p ch) (- ch #x30))
        ((and (>= ch #x41) (<= ch #x46)) (+ (- ch #x41) 10))
        ((and (>= ch #x61) (<= ch #x66)) (+ (- ch #x61) 10))
        (t 0)))

(defun nc-skip-line (s pos)
  (let ((ch (nc-char-at s pos)))
    (if (or (= ch #x0A) (= ch 0)) (+ pos 1) (nc-skip-line s (+ pos 1)))))

(defun nc-skip-ws (s pos)
  (let ((ch (nc-char-at s pos)))
    (cond ((nc-whitespace-p ch) (nc-skip-ws s (+ pos 1)))
          ((= ch #x3B) (nc-skip-ws s (nc-skip-line s (+ pos 1))))
          (t pos))))

(defun nc-read-digits (s pos n)
  (let ((ch (nc-char-at s pos)))
    (if (nc-digit-p ch)
        (nc-read-digits s (+ pos 1) (+ (* n 10) (nc-digit-val ch)))
        (cons n pos))))

(defun nc-read-int (s pos)
  (let ((neg nil) (start pos))
    (let ((ch (nc-char-at s pos)))
      (cond ((= ch #x2D) (setq neg t) (setq start (+ pos 1)))
            ((= ch #x2B) (setq start (+ pos 1)))))
    (let* ((r (nc-read-digits s start 0))
           (val (car r))
           (end (cdr r)))
      (cons (if neg (- 0 val) val) end))))

(defun nc-read-hex-digits (s pos n)
  (let ((ch (nc-char-at s pos)))
    (if (nc-hex-digit-p ch)
        (nc-read-hex-digits s (+ pos 1) (+ (* n 16) (nc-hex-val ch)))
        (cons n pos))))

(defun nc-read-hex (s pos)
  (nc-read-hex-digits s pos 0))

(defun nc-chars-to-string (chars)
  (let* ((len (length chars))
         (vec (make-vector len)))
    (dotimes (i len)
      (vector-set vec i (nth i chars)))
    (make-string-from-vector vec)))

(defun nc-read-sym-chars (s pos chars)
  (let ((ch (nc-char-at s pos)))
    (if (nc-symbol-char-p ch)
        (nc-read-sym-chars s (+ pos 1) (cons ch chars))
        (cons chars pos))))

(defun nc-read-sym (s pos)
  (let* ((r (nc-read-sym-chars s pos nil))
         (chars (car r))
         (end (cdr r))
         (name (nc-chars-to-string (reverse chars)))
         (uname (string-upcase name)))
    (cons (cond ((string= uname "NIL") nil)
                ((string= uname "T") t)
                (t (intern uname)))
          end)))

(defun nc-read-str-chars (s pos chars)
  (let ((ch (nc-char-at s pos)))
    (cond
      ((= ch #x22) (cons chars (+ pos 1)))
      ((= ch #x5C)
       (let* ((esc (nc-char-at s (+ pos 1)))
              (ec (cond ((= esc #x6E) #x0A) ((= esc #x74) #x09) ((= esc #x72) #x0D) (t esc))))
         (nc-read-str-chars s (+ pos 2) (cons ec chars))))
      ((= ch 0) (cons chars pos))
      (t (nc-read-str-chars s (+ pos 1) (cons ch chars))))))

(defun nc-read-str (s pos)
  (let* ((r (nc-read-str-chars s (+ pos 1) nil))
         (chars (car r))
         (end (cdr r)))
    (cons (nc-chars-to-string (reverse chars)) end)))

(defun nc-read (source pos)
  (labels
      ((read-list-elems (p)
         (let* ((p2 (nc-skip-ws source p))
                (ch (nc-char-at source p2)))
           (cond
             ((= ch #x29) (cons nil (+ p2 1)))
             ((= ch #x2E)
              (let* ((r (read-one (+ p2 1)))
                     (cdr-val (car r))
                     (p3 (cdr r))
                     (p4 (nc-skip-ws source p3)))
                (cons cdr-val (+ p4 1))))
             ((= ch 0) (cons nil p2))
             (t (let* ((er (read-one p2))
                       (el (car er))
                       (p3 (cdr er))
                       (rr (read-list-elems p3)))
                  (cons (cons el (car rr)) (cdr rr)))))))
       (read-list (p) (read-list-elems (+ p 1)))
       (read-sharp (p)
         (let ((ch (nc-char-at source (+ p 1))))
           (cond
             ((or (= ch #x78) (= ch #x58)) (nc-read-hex source (+ p 2)))
             ((= ch #x27)
              (let ((r (read-one (+ p 2))))
                (cons (list 'function (car r)) (cdr r))))
             ((= ch #x5C)
              (let ((ch2 (nc-char-at source (+ p 2))))
                (if (nc-alpha-p (nc-char-at source (+ p 3)))
                    (let* ((r (nc-read-sym-chars source (+ p 2) nil))
                           (nm (nc-chars-to-string (reverse (car r)))))
                      (cons (cond ((string= nm "newline") #x0A) ((string= nm "space") #x20)
                                  ((string= nm "tab") #x09) (t ch2))
                            (cdr r)))
                    (cons ch2 (+ p 3)))))
             (t (cons nil (+ p 2))))))
       (read-one (p)
         (let* ((p2 (nc-skip-ws source p))
                (ch (nc-char-at source p2)))
           (if (>= p2 (string-length source))
               (cons nil p2)
               (cond
                 ((= ch #x22) (nc-read-str source p2))
                 ((= ch #x28) (read-list p2))
                 ((= ch #x27)
                  (let ((r (read-one (+ p2 1))))
                    (cons (list 'quote (car r)) (cdr r))))
                 ((= ch #x60)
                  (let ((r (read-one (+ p2 1))))
                    (cons (list 'quasiquote (car r)) (cdr r))))
                 ((= ch #x2C)
                  (if (= (nc-char-at source (+ p2 1)) #x40)
                      (let ((r (read-one (+ p2 2))))
                        (cons (list 'unquote-splicing (car r)) (cdr r)))
                      (let ((r (read-one (+ p2 1))))
                        (cons (list 'unquote (car r)) (cdr r)))))
                 ((= ch #x23) (read-sharp p2))
                 ((or (nc-digit-p ch)
                      (and (or (= ch #x2D) (= ch #x2B))
                           (nc-digit-p (nc-char-at source (+ p2 1)))))
                  (nc-read-int source p2))
                 ((nc-symbol-char-p ch) (nc-read-sym source p2))
                 ((= ch #x29) (cons nil (+ p2 1)))
                 (t (read-one (+ p2 1))))))))
    (read-one pos)))

(defun nc-read-from-string (source)
  (car (nc-read source 0)))

(defun nc-read-all (source)
  (let ((len (string-length source)))
    (labels ((ra (pos acc)
               (let ((p2 (nc-skip-ws source pos)))
                 (if (>= p2 len)
                     (reverse acc)
                     (let ((r (nc-read source p2)))
                       (ra (cdr r) (cons (car r) acc)))))))
      (ra 0 nil))))

;;; ============================================================
;;; Part 4: Stack Frame Constants
;;; ============================================================

(setq *nc-frame-size* #xFF0)
(setq *nc-env-base* #x180)
(setq *nc-temp-base* #x40)
(setq *nc-temp-guard* #x180)
(setq *nc-spill-base* #x200)

(defun nc-temp-slot (depth)
  (let ((off (+ *nc-temp-base* (* depth 8))))
    (if (>= off *nc-temp-guard*)
        (+ *nc-temp-guard* (* (- depth (ash (- *nc-temp-guard* *nc-temp-base*) -3)) 8))
        off)))

(defun nc-spill-slot (idx)
  (+ *nc-spill-base* (* idx 8)))

;;; ============================================================
;;; Part 5: Prologue/Epilogue
;;; ============================================================

(defun nc-prologue ()
  (append
   (nc-stp-offset 29 30 31 (- *nc-frame-size*))
   (nc-sub-imm 31 31 *nc-frame-size*)
   (nc-mov-reg 29 31)
   (nc-stp-offset 19 20 31 16)
   (nc-stp-offset 21 22 31 32)
   (nc-stp-offset 23 24 31 48)
   (nc-mov-reg 20 31)
   (nc-add-imm 20 20 *nc-env-base*)))

(defun nc-epilogue ()
  (append
   (nc-ldp-offset 23 24 31 48)
   (nc-ldp-offset 21 22 31 32)
   (nc-ldp-offset 19 20 31 16)
   (nc-add-imm 31 31 *nc-frame-size*)
   (nc-ldp-offset 29 30 31 0)
   (nc-ret)))

;;; ============================================================
;;; Part 6: IR Compiler (nc-compile-*)
;;; ============================================================

(defun nc-quote-ir (obj)
  (cond
    ((numberp obj) (list 'lit obj))
    ((null obj) (list 'lit 0))
    ((symbolp obj) (list 'sym-lit (symbol-name obj)))
    ((consp obj) (list 'cons-ir (nc-quote-ir (car obj)) (nc-quote-ir (cdr obj))))
    (t (list 'lit 0))))

(defun nc-compile (expr env fenv)
  (cond
    ((numberp expr) (list 'lit expr))
    ((symbolp expr)
     (let ((off (nc-env-lookup expr env)))
       (if off (list 'var off) (list 'lit 0))))
    ((consp expr)
     (let ((op (car expr)))
       (cond
         ((eq op '+)
          (let ((args (cdr expr)))
            (if (null args) (list 'lit 0)
                (if (null (cdr args)) (nc-compile (car args) env fenv)
                    (if (null (cddr args))
                        (list 'add (nc-compile (car args) env fenv) (nc-compile (cadr args) env fenv))
                        (nc-compile (cons '+ (cons (list '+ (car args) (cadr args)) (cddr args))) env fenv))))))
         ((eq op '-)
          (let ((args (cdr expr)))
            (if (null args) (list 'lit 0)
                (if (null (cdr args)) (list 'sub (list 'lit 0) (nc-compile (car args) env fenv))
                    (if (null (cddr args))
                        (list 'sub (nc-compile (car args) env fenv) (nc-compile (cadr args) env fenv))
                        (nc-compile (cons '- (cons (list '- (car args) (cadr args)) (cddr args))) env fenv))))))
         ((eq op '*)
          (let ((args (cdr expr)))
            (if (null args) (list 'lit 1)
                (if (null (cdr args)) (nc-compile (car args) env fenv)
                    (if (null (cddr args))
                        (list 'mul (nc-compile (car args) env fenv) (nc-compile (cadr args) env fenv))
                        (nc-compile (cons '* (cons (list '* (car args) (cadr args)) (cddr args))) env fenv))))))
         ((eq op '=)
          (list 'cmp-eq (nc-compile (cadr expr) env fenv) (nc-compile (caddr expr) env fenv)))
         ((eq op '<)
          (list 'cmp-lt (nc-compile (cadr expr) env fenv) (nc-compile (caddr expr) env fenv)))
         ((eq op '>)
          (list 'cmp-gt (nc-compile (cadr expr) env fenv) (nc-compile (caddr expr) env fenv)))
         ((eq op '<=)
          (list 'cmp-le (nc-compile (cadr expr) env fenv) (nc-compile (caddr expr) env fenv)))
         ((eq op '>=)
          (list 'cmp-ge (nc-compile (cadr expr) env fenv) (nc-compile (caddr expr) env fenv)))
         ((eq op 'if)
          (list 'if-ir
                (nc-compile (cadr expr) env fenv)
                (nc-compile (caddr expr) env fenv)
                (if (cdddr expr) (nc-compile (cadddr expr) env fenv) (list 'lit 0))))
         ((eq op 'let)
          (let* ((bindings (cadr expr))
                 (body (caddr expr)))
            (labels ((proc (bs eacc vals names)
                       (if (null bs)
                           (list eacc (reverse vals) (reverse names))
                           (let* ((b (car bs))
                                  (nm (if (consp b) (car b) b))
                                  (vl (if (consp b) (cadr b) 0))
                                  (vi (nc-compile vl env fenv))
                                  (ne (nc-env-extend (list (list nm)) eacc)))
                             (proc (cdr bs) ne (cons vi vals) (cons nm names))))))
              (let* ((r (proc bindings env nil nil))
                     (nenv (car r))
                     (vals (cadr r))
                     (names (caddr r))
                     (offs (mapcar (lambda (n) (nc-env-lookup n nenv)) names))
                     (bir (nc-compile body nenv fenv)))
                (list 'let-ir vals bir (length bindings) offs)))))
         ((eq op 'let*)
          (let ((bs (cadr expr)) (body (caddr expr)))
            (if (null bs)
                (nc-compile body env fenv)
                (nc-compile (list 'let (list (car bs)) (list 'let* (cdr bs) body)) env fenv))))
         ((eq op 'quote) (nc-quote-ir (cadr expr)))
         ((eq op 'cons)
          (list 'cons-ir (nc-compile (cadr expr) env fenv) (nc-compile (caddr expr) env fenv)))
         ((eq op 'car) (list 'car-ir (nc-compile (cadr expr) env fenv)))
         ((eq op 'cdr) (list 'cdr-ir (nc-compile (cadr expr) env fenv)))
         ((eq op 'list)
          (labels ((bl (args)
                     (if (null args) (list 'lit 0)
                         (list 'cons-ir (nc-compile (car args) env fenv) (bl (cdr args))))))
            (bl (cdr expr))))
         ((eq op 'null)
          (list 'cmp-eq (nc-compile (cadr expr) env fenv) (list 'lit 0)))
         ((eq op 'numberp)
          (list 'cmp-eq (list 'get-tag (nc-compile (cadr expr) env fenv)) (list 'lit 0)))
         ((eq op 'consp)
          (list 'cmp-eq (list 'get-tag (nc-compile (cadr expr) env fenv)) (list 'lit 1)))
         ;; User function call
         (t
          (if (and fenv (assoc op fenv))
              (list 'call-fn op (mapcar (lambda (a) (nc-compile a env fenv)) (cdr expr)))
              (list 'lit 0))))))
    (t (list 'lit 0))))

;;; ============================================================
;;; Part 7: Code Generator (nc-codegen-*)
;;; ============================================================

(defun nc-codegen (ir rtaddrs fnoffs td)
  (cond
    ((nc-has-tag ir 'lit)
     (let ((tg (ash (cadr ir) 4)))
       (if (and (>= tg 0) (< tg #x10000))
           (nc-movz 0 tg)
           (nc-load-addr 0 tg))))
    ((nc-has-tag ir 'var)
     (append (nc-sub-imm 1 20 (* (cadr ir) 8)) (nc-ldr-offset 0 1 0)))
    ((nc-has-tag ir 'get-tag)
     (let ((ac (nc-codegen (cadr ir) rtaddrs fnoffs td)))
       (append ac (nc-movz 1 #xF) (nc-and-reg 0 0 1) (nc-lsl-imm 0 0 4))))
    ((nc-has-tag ir 'add)
     (let* ((xs (nc-temp-slot td))
            (ls (nc-temp-slot (+ td 1)))
            (nd (+ td 2))
            (lc (nc-codegen (cadr ir) rtaddrs fnoffs nd))
            (rc (nc-codegen (caddr ir) rtaddrs fnoffs nd)))
       (append (nc-str-offset 24 31 xs)
               lc (nc-str-offset 0 31 ls)
               (nc-ldr-offset 24 31 xs)
               rc (nc-mov-reg 1 0)
               (nc-ldr-offset 0 31 ls)
               (nc-add-reg 0 0 1))))
    ((nc-has-tag ir 'sub)
     (let* ((xs (nc-temp-slot td))
            (ls (nc-temp-slot (+ td 1)))
            (nd (+ td 2))
            (lc (nc-codegen (cadr ir) rtaddrs fnoffs nd))
            (rc (nc-codegen (caddr ir) rtaddrs fnoffs nd)))
       (append (nc-str-offset 24 31 xs)
               lc (nc-str-offset 0 31 ls)
               (nc-ldr-offset 24 31 xs)
               rc (nc-mov-reg 1 0)
               (nc-ldr-offset 0 31 ls)
               (nc-sub-reg 0 0 1))))
    ((nc-has-tag ir 'mul)
     (let* ((xs (nc-temp-slot td))
            (ls (nc-temp-slot (+ td 1)))
            (nd (+ td 2))
            (lc (nc-codegen (cadr ir) rtaddrs fnoffs nd))
            (rc (nc-codegen (caddr ir) rtaddrs fnoffs nd)))
       (append (nc-str-offset 24 31 xs)
               lc (nc-str-offset 0 31 ls)
               (nc-ldr-offset 24 31 xs)
               rc (nc-mov-reg 1 0)
               (nc-ldr-offset 0 31 ls)
               (nc-lsr-imm 0 0 4) (nc-lsr-imm 1 1 4) (nc-mul-reg 0 0 1) (nc-lsl-imm 0 0 4))))
    ((nc-has-tag ir 'cmp-eq)
     (let* ((xs (nc-temp-slot td))
            (ls (nc-temp-slot (+ td 1)))
            (nd (+ td 2))
            (lc (nc-codegen (cadr ir) rtaddrs fnoffs nd))
            (rc (nc-codegen (caddr ir) rtaddrs fnoffs nd)))
       (append (nc-str-offset 24 31 xs)
               lc (nc-str-offset 0 31 ls)
               (nc-ldr-offset 24 31 xs)
               rc (nc-mov-reg 1 0)
               (nc-ldr-offset 0 31 ls)
               (nc-cmp-reg 0 1) (nc-cset 0 (nc-cond-eq)) (nc-lsl-imm 0 0 4))))
    ((nc-has-tag ir 'cmp-lt)
     (let* ((xs (nc-temp-slot td))
            (ls (nc-temp-slot (+ td 1)))
            (nd (+ td 2))
            (lc (nc-codegen (cadr ir) rtaddrs fnoffs nd))
            (rc (nc-codegen (caddr ir) rtaddrs fnoffs nd)))
       (append (nc-str-offset 24 31 xs)
               lc (nc-str-offset 0 31 ls)
               (nc-ldr-offset 24 31 xs)
               rc (nc-mov-reg 1 0)
               (nc-ldr-offset 0 31 ls)
               (nc-cmp-reg 0 1) (nc-cset 0 (nc-cond-lt)) (nc-lsl-imm 0 0 4))))
    ((nc-has-tag ir 'cmp-gt)
     (let* ((xs (nc-temp-slot td))
            (ls (nc-temp-slot (+ td 1)))
            (nd (+ td 2))
            (lc (nc-codegen (cadr ir) rtaddrs fnoffs nd))
            (rc (nc-codegen (caddr ir) rtaddrs fnoffs nd)))
       (append (nc-str-offset 24 31 xs)
               lc (nc-str-offset 0 31 ls)
               (nc-ldr-offset 24 31 xs)
               rc (nc-mov-reg 1 0)
               (nc-ldr-offset 0 31 ls)
               (nc-cmp-reg 0 1) (nc-cset 0 (nc-cond-gt)) (nc-lsl-imm 0 0 4))))
    ((nc-has-tag ir 'cmp-le)
     (let* ((xs (nc-temp-slot td))
            (ls (nc-temp-slot (+ td 1)))
            (nd (+ td 2))
            (lc (nc-codegen (cadr ir) rtaddrs fnoffs nd))
            (rc (nc-codegen (caddr ir) rtaddrs fnoffs nd)))
       (append (nc-str-offset 24 31 xs)
               lc (nc-str-offset 0 31 ls)
               (nc-ldr-offset 24 31 xs)
               rc (nc-mov-reg 1 0)
               (nc-ldr-offset 0 31 ls)
               (nc-cmp-reg 0 1) (nc-cset 0 (nc-cond-le)) (nc-lsl-imm 0 0 4))))
    ((nc-has-tag ir 'cmp-ge)
     (let* ((xs (nc-temp-slot td))
            (ls (nc-temp-slot (+ td 1)))
            (nd (+ td 2))
            (lc (nc-codegen (cadr ir) rtaddrs fnoffs nd))
            (rc (nc-codegen (caddr ir) rtaddrs fnoffs nd)))
       (append (nc-str-offset 24 31 xs)
               lc (nc-str-offset 0 31 ls)
               (nc-ldr-offset 24 31 xs)
               rc (nc-mov-reg 1 0)
               (nc-ldr-offset 0 31 ls)
               (nc-cmp-reg 0 1) (nc-cset 0 (nc-cond-ge)) (nc-lsl-imm 0 0 4))))
    ((nc-has-tag ir 'cons-ir)
     (let* ((xs (nc-temp-slot td))
            (cs (nc-temp-slot (+ td 1)))
            (nd (+ td 2))
            (cc (nc-codegen (cadr ir) rtaddrs fnoffs nd))
            (dc (nc-codegen (caddr ir) rtaddrs fnoffs nd)))
       (append (nc-str-offset 24 31 xs)
               cc (nc-str-offset 0 31 cs)
               (nc-ldr-offset 24 31 xs)
               dc (nc-mov-reg 1 0)
               (nc-ldr-offset 0 31 cs)
               (nc-ldr-offset 9 19 0) (nc-blr 9))))
    ((nc-has-tag ir 'car-ir)
     (append (nc-codegen (cadr ir) rtaddrs fnoffs td)
             (nc-ldr-offset 9 19 8) (nc-blr 9)))
    ((nc-has-tag ir 'cdr-ir)
     (append (nc-codegen (cadr ir) rtaddrs fnoffs td)
             (nc-ldr-offset 9 19 16) (nc-blr 9)))
    ((nc-has-tag ir 'if-ir)
     (let* ((tc (nc-codegen (cadr ir) rtaddrs fnoffs td))
            (thc (nc-codegen (caddr ir) rtaddrs fnoffs td))
            (elc (nc-codegen (cadddr ir) rtaddrs fnoffs td))
            (thl (nc-count-instrs thc))
            (ell (nc-count-instrs elc)))
       (append tc
               (nc-movz 1 0) (nc-cmp-reg 0 1)
               (nc-b-cond (nc-cond-eq) (* (+ thl 1) 4))
               thc
               (nc-b-offset (* ell 4))
               elc)))
    ((nc-has-tag ir 'let-ir)
     (let* ((vals (cadr ir))
            (bir (caddr ir))
            (offs (nth 4 (cdr ir)))
            (xs (nc-temp-slot td))
            (nd (+ td 1))
            (acc (nc-str-offset 24 31 xs)))
       (labels ((gb (vs os a)
                  (if (null vs) a
                      (let* ((vc (nc-codegen (car vs) rtaddrs fnoffs nd))
                             (st (append (nc-sub-imm 1 20 (* (car os) 8)) (nc-str-offset 0 1 0))))
                        (gb (cdr vs) (cdr os)
                            (append a (nc-ldr-offset 24 31 xs) vc st))))))
         (append acc
                 (gb vals offs nil)
                 (nc-ldr-offset 24 31 xs)
                 (nc-codegen bir rtaddrs fnoffs nd)))))
    ((nc-has-tag ir 'call-fn)
     (let* ((fnm (cadr ir))
            (airs (caddr ir))
            (na (length airs))
            (xs (nc-temp-slot td))
            (nd (+ td 1)))
       (labels ((ga (as i a)
                  (if (null as) a
                      (let* ((rs (if (> i 0) (nc-ldr-offset 24 31 xs) nil))
                             (ac (nc-codegen (car as) rtaddrs fnoffs nd))
                             (st (nc-str-offset 0 31 (nc-spill-slot i))))
                        (ga (cdr as) (+ i 1) (append a rs ac st)))))
                (gl (i a)
                  (if (>= i na) a
                      (gl (+ i 1) (append a (nc-ldr-offset i 31 (nc-spill-slot i)))))))
         (append (nc-str-offset 24 31 xs)
                 (ga airs 0 nil)
                 (nc-ldr-offset 24 31 xs)
                 (gl 0 nil)
                 (nc-movz 23 na)
                 (nc-bl-offset 0)))))
    (t (nc-movz 0 0))))

;;; ============================================================
;;; Part 8: Multi-Function Compiler
;;; ============================================================

(defun nc-compile-defun (name params body env fenv)
  (let* ((bs (mapcar (lambda (p) (list p)) params))
         (penv (nc-env-extend bs env))
         (pb (if params (nc-env-lookup (car params) penv) 0))
         (rfenv (cons (cons name nil) fenv))
         (bir (nc-compile body penv rfenv)))
    (list name params bir pb)))

(defun nc-compile-forms-h (forms env fenv)
  (if (consp forms)
      (let ((f (car forms)))
        (if (and (consp f) (eq (car f) 'defun))
            (let* ((nm (cadr f))
                   (ps (caddr f))
                   (bd (cadddr f))
                   (cf (nc-compile-defun nm ps bd env fenv))
                   (nfenv (cons (cons nm cf) fenv))
                   (rr (nc-compile-forms-h (cdr forms) env nfenv)))
              (list (cons cf (car rr)) (cadr rr)))
            (list nil (nc-compile f env fenv))))
      (list nil (list 'lit 0))))

(defun nc-compile-forms (forms)
  (nc-compile-forms-h forms nil nil))

(defun nc-gen-param-stores (params base idx acc)
  (if (null params)
      acc
      (let ((st (append (nc-mov-reg 22 idx)
                        (nc-sub-imm 21 20 (* (+ base idx) 8))
                        (nc-str-offset 22 21 0))))
        (nc-gen-param-stores (cdr params) base (+ idx 1) (append acc st)))))

(defun nc-codegen-fn (fn rtaddrs fnoffs)
  (let* ((ps (cadr fn))
         (bir (caddr fn))
         (pb (cadddr fn))
         (pc (nc-gen-param-stores ps pb 0 nil))
         (bc (nc-codegen bir rtaddrs fnoffs 0)))
    (append pc bc (nc-ret))))

(defun nc-codegen-main (mir rtaddrs)
  (append (nc-prologue)
          (nc-codegen mir rtaddrs nil 0)
          (nc-epilogue)))

(defun nc-compile-program (forms rtaddrs)
  (let* ((r (nc-compile-forms forms))
         (fns (car r))
         (mir (cadr r))
         (mc (nc-codegen-main mir rtaddrs)))
    mc))

;;; ============================================================
;;; Part 9: Entry Point
;;; ============================================================

(defun main ()
  ;; Full pipeline: parse -> compile to IR -> generate ARM64 bytecode
  (let* ((src "(+ 10 7)")
         (forms (nc-read-all src)))
    (if (consp forms)
        (let* ((expr (car forms))
               (ir (nc-compile expr nil nil))
               ;; Generate ARM64 bytecode from IR
               (bytecode (nc-codegen ir nil nil 0))
               (byte-count (length bytecode)))
          ;; Return byte count / 4 using arithmetic shift
          (ash byte-count -2))
        0)))

(main)
