;;; Test: recursive labels (n=1), then call concat-string-list

(labels ((outer-rec (n acc)
           (if (= n 0)
               (list acc n)
               (outer-rec (- n 1) (+ acc n)))))
  (let* ((result-list (outer-rec 1 0))
         (acc-val (car result-list))
         (n-val (car (cdr result-list))))
    ;; Now call concat (which has nested recursive labels)
    (let ((chunks (cons "A" (cons "B" nil))))
      (let ((result (concat-string-list chunks 2)))
        (sys-write 1 result (string-length result))
        (sys-write 1 "\n" 1)
        (sys-exit 42)))))
