;;; Test if chunks returned from labels are preserved

(labels ((collect (n acc total)
           (if (= n 0)
               (list acc total)
               (let* ((chunk "X")
                      (next-acc (cons chunk acc))
                      (next-total (+ total 1)))
                 (collect (- n 1) next-acc next-total)))))
  (let* ((result-list (collect 5 nil 0))
         (chunks (car result-list))
         (total (car (cdr result-list))))
    (sys-write 1 "Total: " 7)
    (sys-write 1 (number-to-string total)
               (string-length (number-to-string total)))
    (sys-write 1 "\nFirst chunk addr (as number): " 31)
    (sys-write 1 (number-to-string (if (null chunks) 0 (string-length (car chunks))))
               (string-length (number-to-string (if (null chunks) 0 (string-length (car chunks))))))
    (sys-write 1 "\n" 1)
    (sys-exit (if (= total 5) 42 1))))
