/* ================================================ */
/* Phase 3.1: Self-Compile Functions Test Harness  */
/* Generated by compile-and-execute.lisp           */
/* ================================================ */

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <sys/mman.h>
#include <string.h>

#ifndef MAP_JIT
#define MAP_JIT 0x0800
#endif

typedef int64_t (*fn_t)(int64_t);

/* ================================================ */
/* Test 1: Simple arithmetic function              */
/* (defun add-one (x) (+ x 1))                     */
/* ================================================ */

uint8_t add_one_code[] = {
    0xFD, 0x7B, 0xBF, 0xA9, 0x00, 0x64, 0x95, 0xD2, 0xFD, 0x7B, 0xC1, 0xA8, 
    0xC0, 0x03, 0x5F, 0xD6, 0xFD, 0x7B, 0xBF, 0xA9, 0x00, 0x64, 0x95, 0xD2, 
    0xFD, 0x7B, 0xC1, 0xA8, 0xC0, 0x03, 0x5F, 0xD6, 0xFD, 0x7B, 0xBF, 0xA9, 
    0x00, 0x64, 0x95, 0xD2, 0xFD, 0x7B, 0xC1, 0xA8, 0xC0, 0x03, 0x5F, 0xD6
};
size_t add_one_code_size = 48;

/* add-one(5) should return 6 (0x60 tagged = 96) */

/* ================================================ */
/* Test 2: Multiplication function                  */
/* (defun double (x) (* x 2))                      */
/* ================================================ */

uint8_t double_code[] = {
    0xFD, 0x7B, 0xBF, 0xA9, 0x00, 0x64, 0x95, 0xD2, 0xFD, 0x7B, 0xC1, 0xA8, 
    0xC0, 0x03, 0x5F, 0xD6, 0xFD, 0x7B, 0xBF, 0xA9, 0x00, 0x64, 0x95, 0xD2, 
    0xFD, 0x7B, 0xC1, 0xA8, 0xC0, 0x03, 0x5F, 0xD6, 0xFD, 0x7B, 0xBF, 0xA9, 
    0x00, 0x64, 0x95, 0xD2, 0xFD, 0x7B, 0xC1, 0xA8, 0xC0, 0x03, 0x5F, 0xD6
};
size_t double_code_size = 48;

/* double(7) should return 14 (0xE0 tagged = 224) */

/* ================================================ */
/* Test 3: Conditional function                     */
/* (defun abs-val (x) (if (< x 0) (- 0 x) x))     */
/* ================================================ */

uint8_t abs_val_code[] = {
    0xFD, 0x7B, 0xBF, 0xA9, 0x00, 0x64, 0x95, 0xD2, 0xFD, 0x7B, 0xC1, 0xA8, 
    0xC0, 0x03, 0x5F, 0xD6, 0xFD, 0x7B, 0xBF, 0xA9, 0x00, 0x64, 0x95, 0xD2, 
    0xFD, 0x7B, 0xC1, 0xA8, 0xC0, 0x03, 0x5F, 0xD6, 0xFD, 0x7B, 0xBF, 0xA9, 
    0x00, 0x64, 0x95, 0xD2, 0xFD, 0x7B, 0xC1, 0xA8, 0xC0, 0x03, 0x5F, 0xD6
};
size_t abs_val_code_size = 48;

/* abs-val(-5) should return 5 (0x50 tagged = 80) */

/* ================================================ */
/* Test 4: Recursive factorial                      */
/* (defun factorial (n)                             */
/*   (if (= n 0) 1 (* n (factorial (- n 1)))))     */
/* ================================================ */

uint8_t factorial_code[] = {
    0xFD, 0x7B, 0xBF, 0xA9, 0x00, 0x64, 0x95, 0xD2, 0xFD, 0x7B, 0xC1, 0xA8, 
    0xC0, 0x03, 0x5F, 0xD6, 0xFD, 0x7B, 0xBF, 0xA9, 0x00, 0x64, 0x95, 0xD2, 
    0xFD, 0x7B, 0xC1, 0xA8, 0xC0, 0x03, 0x5F, 0xD6, 0xFD, 0x7B, 0xBF, 0xA9, 
    0x00, 0x64, 0x95, 0xD2, 0xFD, 0x7B, 0xC1, 0xA8, 0xC0, 0x03, 0x5F, 0xD6
};
size_t factorial_code_size = 48;

/* factorial(5) should return 120 (0x780 tagged = 1920) */

/* ================================================ */
/* Test 5: Tail-recursive factorial                 */
/* (defun fact-tail (n acc)                         */
/*   (if (= n 0) acc                                */
/*       (fact-tail (- n 1) (* n acc))))            */
/* Note: Uses 2 parameters, test with n=5, acc=1   */
/* ================================================ */

uint8_t fact_tail_code[] = {
    0xFD, 0x7B, 0xBF, 0xA9, 0x00, 0x64, 0x95, 0xD2, 0xFD, 0x7B, 0xC1, 0xA8, 
    0xC0, 0x03, 0x5F, 0xD6, 0xFD, 0x7B, 0xBF, 0xA9, 0x00, 0x64, 0x95, 0xD2, 
    0xFD, 0x7B, 0xC1, 0xA8, 0xC0, 0x03, 0x5F, 0xD6, 0xFD, 0x7B, 0xBF, 0xA9, 
    0x00, 0x64, 0x95, 0xD2, 0xFD, 0x7B, 0xC1, 0xA8, 0xC0, 0x03, 0x5F, 0xD6
};
size_t fact_tail_code_size = 48;

/* fact-tail(5, 1) should return 120 (0x780 tagged = 1920) */

int64_t execute_code(const uint8_t *code, size_t size, int64_t arg) {
    size_t page_size = 4096;
    void *mem = mmap(NULL, page_size, PROT_READ | PROT_WRITE,
                     MAP_PRIVATE | MAP_ANON | MAP_JIT, -1, 0);
    if (mem == MAP_FAILED) {
        perror("mmap");
        return 0;
    }

    memcpy(mem, code, size);

    if (mprotect(mem, page_size, PROT_READ | PROT_EXEC) != 0) {
        perror("mprotect");
        munmap(mem, page_size);
        return 0;
    }

    fn_t fn = (fn_t)mem;
    int64_t result = fn(arg);

    munmap(mem, page_size);
    return result;
}

/* ================================================ */
/* Main test driver                                 */
/* ================================================ */

int main(void) {
    printf("\n=== Phase 3.1: Self-Compiled Function Tests ===\n\n");

    int64_t result;
    int passed = 0;
    int failed = 0;

    /* Test: add-one */
    printf("Test add-one: add-one(5)\n");
    result = execute_code(add_one_code, add_one_code_size, 80);
    printf("  Result: %lld (expected %lld)\n", (long long)(result >> 4), (long long)(96 >> 4));
    if (result == 96) {
        printf("  ✓ PASS\n\n");
        passed++;
    } else {
        printf("  ✗ FAIL\n\n");
        failed++;
    }

    /* Test: double */
    printf("Test double: double(7)\n");
    result = execute_code(double_code, double_code_size, 112);
    printf("  Result: %lld (expected %lld)\n", (long long)(result >> 4), (long long)(224 >> 4));
    if (result == 224) {
        printf("  ✓ PASS\n\n");
        passed++;
    } else {
        printf("  ✗ FAIL\n\n");
        failed++;
    }

    /* Test: abs-val(neg) */
    printf("Test abs-val(neg): abs-val(-5)\n");
    result = execute_code(abs_val_code, abs_val_code_size, -80);
    printf("  Result: %lld (expected %lld)\n", (long long)(result >> 4), (long long)(80 >> 4));
    if (result == 80) {
        printf("  ✓ PASS\n\n");
        passed++;
    } else {
        printf("  ✗ FAIL\n\n");
        failed++;
    }

    /* Test: factorial */
    printf("Test factorial: factorial(5)\n");
    result = execute_code(factorial_code, factorial_code_size, 80);
    printf("  Result: %lld (expected %lld)\n", (long long)(result >> 4), (long long)(1920 >> 4));
    if (result == 1920) {
        printf("  ✓ PASS\n\n");
        passed++;
    } else {
        printf("  ✗ FAIL\n\n");
        failed++;
    }

    /* Test: fact-tail */
    printf("Test fact-tail: fact-tail(5)\n");
    result = execute_code(fact_tail_code, fact_tail_code_size, 80);
    printf("  Result: %lld (expected %lld)\n", (long long)(result >> 4), (long long)(1920 >> 4));
    if (result == 1920) {
        printf("  ✓ PASS\n\n");
        passed++;
    } else {
        printf("  ✗ FAIL\n\n");
        failed++;
    }

    printf("\n=== Test Results ===\n");
    printf("Passed: %d\n", passed);
    printf("Failed: %d\n", failed);
    printf("Total:  %d\n\n", passed + failed);

    if (failed == 0) {
        printf("✓ ALL TESTS PASSED!\n\n");
        return 0;
    } else {
        printf("✗ SOME TESTS FAILED\n\n");
        return 1;
    }
}

/* End of generated test harness */
