;;; Test: outer-rec, then mapcar (which also expands via transformation)

(labels ((outer-rec (n acc)
           (if (= n 0)
               (list acc n)
               (outer-rec (- n 1) (+ acc n)))))
  (let* ((result-list (outer-rec 3 0))
         (acc-val (car result-list)))
    ;; mapcar also expands to labels recursion
    (let* ((lst (cons 1 (cons 2 (cons 3 nil))))
           (fn (lambda (x) (+ x 10)))
           (result (mapcar fn lst)))
      (let ((sum (+ (car result) (car (cdr result)) (car (cdr (cdr result))))))
        (sys-write 1 (number-to-string sum) 2)
        (sys-write 1 "\n" 1)
        (sys-exit 42)))))
