;;; Minimal test: sys-read + buffer-to-string + concat-string-list

(let* ((fd (sys-open "/tmp/small.txt" #x0 0))
       (buf (make-vector 100)))
  (labels ((read-once ()
             (let* ((n (sys-read fd buf 100))
                    (chunk (buffer-to-string buf n)))
               (list (cons chunk nil) n))))
    (let* ((result-list (read-once))
           (chunks (car result-list))
           (total (car (cdr result-list))))
      (sys-close fd)
      (let ((result (concat-string-list chunks total)))
        (sys-write 1 "Length: " 8)
        (sys-write 1 (number-to-string (string-length result))
                   (string-length (number-to-string (string-length result))))
        (sys-write 1 "\n" 1)
        (sys-exit (if (= (string-length result) 8) 42 1))))))
