;;; Test nested labels (labels calling a function that uses labels internally)

(labels ((outer-fn (x)
           (labels ((inner-fn (y)
                      (+ y 1)))
             (inner-fn x))))
  (let ((result (outer-fn 41)))
    (sys-write 1 (number-to-string result) (string-length (number-to-string result)))
    (sys-write 1 "\n" 1)
    (sys-exit result)))
