/* Test harness for generated machine code */

#include <stdio.h>
#include <stdint.h>
#include <sys/mman.h>
#include <string.h>

typedef int64_t (*habu_fn_t)(void);

int main() {
    /* Machine code generated by Habu compiler
     * Test 1: Simple return (xor eax,eax; ret returns 0)
     */
    unsigned char code[] = {
        0x31, 0xC0,                     /* xor eax, eax (set eax = 0) */
        0xC3                            /* ret */
    };

    size_t code_size = sizeof(code);

    /* Allocate executable memory with all permissions at once (like SBCL) */
    void *mem = mmap(NULL, code_size,
                     PROT_READ | PROT_WRITE | PROT_EXEC,
                     MAP_PRIVATE | MAP_ANON,
                     -1, 0);

    if (mem == MAP_FAILED) {
        perror("mmap");
        return 1;
    }

    /* Copy code to executable memory */
    memcpy(mem, code, code_size);

    /* Cast to function pointer and call */
    habu_fn_t fn = (habu_fn_t)mem;
    int64_t result = fn();

    printf("Generated code returned: %lld\n", result);
    printf("Expected: 0\n");

    /* Clean up */
    munmap(mem, code_size);

    if (result == 0) {
        printf("✓ SUCCESS!\n");
        return 0;
    } else {
        printf("✗ FAILED\n");
        return 1;
    }
}
