;;;; Test ARM64 Intrinsics - Verify byte generation
;;;; Load this file and run tests to ensure all intrinsics generate correct bytes

(load "habu-arm64-codegen.lisp")

(defun print-bytes (name bytes)
  (print name)
  (print " → ")
  (if (cons? bytes)
    (progn
      (print (car bytes))
      (if (cons? (cdr bytes))
        (progn
          (print " ")
          (print-bytes "" (cdr bytes)))
        nil))
    nil)
  (newline))

(defun test-movz ()
  (print "Testing MOVZ intrinsics:")
  (newline)
  (print-bytes "  movz x0, #672" (arm64-movz 0 672))
  (print-bytes "  movz x0, #0" (arm64-movz 0 0))
  (print-bytes "  movz x1, #100" (arm64-movz 1 100))
  (print-bytes "  movz x2, #200" (arm64-movz 2 200))
  (newline))

(defun test-arithmetic ()
  (print "Testing arithmetic intrinsics:")
  (newline)
  (print-bytes "  add x0, x0, x1" (arm64-add 0 0 1))
  (print-bytes "  add x0, x1, x2" (arm64-add 0 1 2))
  (print-bytes "  sub x0, x0, x1" (arm64-sub 0 0 1))
  (print-bytes "  mul x0, x0, x1" (arm64-mul 0 0 1))
  (newline))

(defun test-shifts ()
  (print "Testing shift intrinsics:")
  (newline)
  (print-bytes "  lsr x0, x0, #4" (arm64-lsr 0 0 4))
  (print-bytes "  lsl x0, x0, #4" (arm64-lsl 0 0 4))
  (newline))

(defun test-moves ()
  (print "Testing move intrinsics:")
  (newline)
  (print-bytes "  mov x1, x0" (arm64-mov 1 0))
  (print-bytes "  mov x2, x0" (arm64-mov 2 0))
  (newline))

(defun test-control ()
  (print "Testing control flow:")
  (newline)
  (print-bytes "  ret" (arm64-ret))
  (newline))

(defun run-all-tests ()
  (print "========================================")
  (newline)
  (print "ARM64 Intrinsic Byte Generation Tests")
  (newline)
  (print "========================================")
  (newline)
  (newline)
  (test-movz)
  (test-arithmetic)
  (test-shifts)
  (test-moves)
  (test-control)
  (print "Compare output with ARM64_ENCODINGS.md")
  (newline))

(run-all-tests)
