;;; Test dotimes with string operations (non-recursive)

(let* ((s1 "A")
       (s2 "B")
       (len1 (string-length s1))
       (len2 (string-length s2))
       (total (+ len1 len2))
       (vec (make-vector total)))
  (dotimes (i len1)
    (vector-set vec i (string-ref s1 i)))
  (dotimes (i len2)
    (vector-set vec (+ len1 i) (string-ref s2 i)))
  (let ((result (make-string-from-vector vec)))
    (sys-write 1 result (string-length result))
    (sys-write 1 "\n" 1)
    (sys-exit (if (= (string-length result) 2) 42 1))))
