;;; Test native-read-file-large pattern WITHOUT concat-string-list

(let* ((path "/tmp/small.txt")
       (fd (sys-open path #x0 0))
       (buf (make-vector 65536)))
  (labels ((read-chunks (chunks total)
             (let ((n (sys-read fd buf 65536)))
               (if (= n 0)
                   (list chunks total)
                   (let* ((chunk (buffer-to-string buf n))
                          (next-chunks (cons chunk chunks))
                          (next-total (+ total n)))
                     (read-chunks next-chunks next-total))))))
    (let* ((result-list (read-chunks nil 0))
           (chunks (car result-list))
           (total (car (cdr result-list))))
      (sys-close fd)
      (sys-write 1 "Total: " 7)
      (sys-write 1 (number-to-string total)
                 (string-length (number-to-string total)))
      (sys-write 1 "\n" 1)
      (sys-exit (if (= total 8) 42 1)))))
