(load "habu-arm64-codegen.lisp")
(print "=== Testing simple addition ===")
(print (compile-expr (quote (+ 2 3))))
(print "\n")
(print "=== Testing if expression ===")
(print (compile-expr (quote (if (> 5 3) 10 20))))
(print "\n")
(print "=== Testing cond expression ===")
(print (compile-expr (quote (cond ((> 5 3) 100)))))
(print "\n")
