;;; Test: sys-read + extract + concat (exact failing pattern)

(let* ((fd (sys-open "/tmp/small.txt" #x0 0))
       (buf (make-vector 100)))
  (labels ((read-once (count)
             (if (= count 0)
                 (let ((n (sys-read fd buf 100)))
                   (if (= n 0)
                       (list nil 0)
                       (let ((chunk (buffer-to-string buf n)))
                         (list (cons chunk nil) n))))
                 (read-once (- count 1)))))
    (let* ((result-list (read-once 1))
           (chunks (car result-list))
           (total (car (cdr result-list))))
      (sys-close fd)
      (let ((result (concat-string-list chunks total)))
        (sys-write 1 result (string-length result))
        (sys-write 1 "\n" 1)
        (sys-exit 42)))))
