;;; Test sys-read + buffer-to-string

(let* ((path "/tmp/small.txt")
       (fd (sys-open path #x0 0))
       (buf (make-vector 100)))
  (let* ((n (sys-read fd buf 100))
         (str (buffer-to-string buf n)))
    (sys-close fd)
    (sys-write 1 "Read " 5)
    (sys-write 1 (number-to-string n)
               (string-length (number-to-string n)))
    (sys-write 1 " bytes, string length: " 23)
    (sys-write 1 (number-to-string (string-length str))
               (string-length (number-to-string (string-length str))))
    (sys-write 1 "\n" 1)
    (sys-exit (if (= (string-length str) 8) 42 1))))
