;;; Test if the issue is specific to the FIRST variable or any string variable

(let* ((dummy 42)  ;; First variable is NOT the path
       (path "/tmp/small.txt")
       (fd (sys-open path #x0 0))
       (buf (make-vector 65536)))
  (labels ((read-chunks (chunks total)
             (let ((n (sys-read fd buf 65536)))
               (if (= n 0)
                   (list chunks total)
                   (let* ((chunk (buffer-to-string buf n))
                          (next-chunks (cons chunk chunks))
                          (next-total (+ total n)))
                     (read-chunks next-chunks next-total))))))
    (let* ((result-list (read-chunks nil 0))
           (chunks (car result-list))
           (total (car (cdr result-list))))
      (sys-close fd)
      (let ((result (concat-string-list chunks total)))
        (sys-write 1 "Length: " 8)
        (sys-write 1 (number-to-string (string-length result))
                   (string-length (number-to-string (string-length result))))
        (sys-write 1 "\n" 1)
        (sys-exit (if (= (string-length result) 8) 42 1))))))
