;;; Test native-read-file-large with a small file (just a few bytes)

(let ((result (native-read-file-large "/tmp/small.txt")))
  (sys-write 1 "Result: " 8)
  (sys-write 1 result (string-length result))
  (sys-write 1 "\nLength: " 9)
  (sys-write 1 (number-to-string (string-length result))
             (string-length (number-to-string (string-length result))))
  (sys-write 1 "\n" 1)
  (sys-exit (if (= (string-length result) 8) 42 1)))
