(load "lib/stdlib.habu")
(ignore-errors (load "/private/tmp/habu-ansi/ansi-test/init.lsp"))
(ignore-errors (load "/private/tmp/habu-ansi/ansi-test/compile-and-load.lsp"))
(ignore-errors (load "/private/tmp/habu-ansi/ansi-test/rt-package.lsp"))
(ignore-errors (load "/private/tmp/habu-ansi/ansi-test/rt.lsp"))
(format t "pkg=~A~%" *package*)
(format t "fboundp make-entry RT:: ~A~%" (fboundp 'regression-test::make-entry))
(format t "fboundp copy-entry RT:: ~A~%" (fboundp 'regression-test::copy-entry))
(format t "fboundp copy-entry RT: ~A~%" (fboundp 'regression-test:copy-entry))
(multiple-value-bind (s st) (find-symbol "COPY-ENTRY" "REGRESSION-TEST")
  (format t "find-symbol RT COPY-ENTRY => ~A ~A~%" s st))
(quit)
