\ class-test.f - focused Unicode character-class tests.
\ Run: bin/hb --load lib/unicode/class-test.f

require lib/test.f
require lib/unicode/class.f

package UNICODE-CLASS-TEST

private

: DATA-LOW-FAIL ( -- )
   -1 UNICODE-CLASS-DATA:LETTER-RANGE@ 2drop ;

: DATA-HIGH-FAIL ( -- )
   UNICODE-CLASS-DATA:LETTER-RANGE-COUNT UNICODE-CLASS-DATA:LETTER-RANGE@ 2drop ;

public

: TEST ( -- )
   -1 UNICODE-CLASS:SCALAR? TFALSE
   0 UNICODE-CLASS:SCALAR? TTRUE
   $D7FF UNICODE-CLASS:SCALAR? TTRUE
   $D800 UNICODE-CLASS:SCALAR? TFALSE
   $D900 UNICODE-CLASS:SCALAR? TFALSE
   $DFFF UNICODE-CLASS:SCALAR? TFALSE
   $E000 UNICODE-CLASS:SCALAR? TTRUE
   $10FFFF UNICODE-CLASS:SCALAR? TTRUE
   $110000 UNICODE-CLASS:SCALAR? TFALSE

   64 UNICODE-CLASS:LETTER? TFALSE
   65 UNICODE-CLASS:LETTER? TTRUE
   90 UNICODE-CLASS:LETTER? TTRUE
   91 UNICODE-CLASS:LETTER? TFALSE
   $FF4E UNICODE-CLASS:LETTER? TTRUE
   $0E01 UNICODE-CLASS:LETTER? TTRUE
   $10400 UNICODE-CLASS:LETTER? TTRUE
   $1D7CE UNICODE-CLASS:LETTER? TFALSE
   -1 UNICODE-CLASS:LETTER? TFALSE
   $D800 UNICODE-CLASS:LETTER? TFALSE
   $D900 UNICODE-CLASS:LETTER? TFALSE
   $DFFF UNICODE-CLASS:LETTER? TFALSE
   $110000 UNICODE-CLASS:LETTER? TFALSE

   47 UNICODE-CLASS:NUMBER? TFALSE
   48 UNICODE-CLASS:NUMBER? TTRUE
   57 UNICODE-CLASS:NUMBER? TTRUE
   58 UNICODE-CLASS:NUMBER? TFALSE
   $0E50 UNICODE-CLASS:NUMBER? TTRUE
   $1D7CE UNICODE-CLASS:NUMBER? TTRUE
   $D900 UNICODE-CLASS:NUMBER? TFALSE
   $110000 UNICODE-CLASS:NUMBER? TFALSE

   8 UNICODE-CLASS:WHITE-SPACE? TFALSE
   9 UNICODE-CLASS:WHITE-SPACE? TTRUE
   13 UNICODE-CLASS:WHITE-SPACE? TTRUE
   14 UNICODE-CLASS:WHITE-SPACE? TFALSE
   32 UNICODE-CLASS:WHITE-SPACE? TTRUE
   $200B UNICODE-CLASS:WHITE-SPACE? TFALSE
   $3000 UNICODE-CLASS:WHITE-SPACE? TTRUE
   $D900 UNICODE-CLASS:WHITE-SPACE? TFALSE
   $110000 UNICODE-CLASS:WHITE-SPACE? TFALSE

   UNICODE-CLASS:VERSION$ s" 16.0.0" T$=
   UNICODE-CLASS:UNICODE-DATA-SHA256$
      s" ff58e5823bd095166564a006e47d111130813dcf8bf234ef79fa51a870edb48f" T$=
   UNICODE-CLASS:PROP-LIST-SHA256$
      s" 53d614508e2a0b2305a8aa21cd60d993de9326cdf65993660dfcce4503548583" T$=

   UNICODE-CLASS-DATA:LETTER-RANGE-COUNT 677 T=
   UNICODE-CLASS-DATA:NUMBER-RANGE-COUNT 144 T=
   UNICODE-CLASS-DATA:WHITE-SPACE-RANGE-COUNT 10 T=
   0 UNICODE-CLASS-DATA:LETTER-RANGE@ 90 T= 65 T=
   0 UNICODE-CLASS-DATA:NUMBER-RANGE@ 57 T= 48 T=
   0 UNICODE-CLASS-DATA:WHITE-SPACE-RANGE@ 13 T= 9 T=
   [: DATA-LOW-FAIL ;] UNICODE-CLASS-DATA:E-INDEX TTHROWSQ
   [: DATA-HIGH-FAIL ;] UNICODE-CLASS-DATA:E-INDEX TTHROWSQ ;

;package

UNICODE-CLASS-TEST:TEST
T-REPORT
