\ gpu-buffer-test.f - persistent GPU buffer lifetime.

require maki/gpu-session-test.f
require maki/gpu-buffer.f

package GPU-SPAN-TEST
public

: CALL
   ( GPU:session GPU:buffer CAD-NUM:byte-off CAD-NUM:byte-len -- GPU:session GPU:buffer result<cuda-devptr,n> )
   GPU:SPAN ;

: COPY-CALL
   ( GPU:session GPU:buffer CAD-NUM:byte-off CAD-NUM:byte-off CAD-NUM:byte-len -- GPU:session GPU:buffer result<n,n> )
   GPU:COPY ;

;package

package GPU
private

using CAD-NUM
using MKD

10 constant BT-ALLOC
11 constant BT-UPLOAD
12 constant BT-FREE
13 constant BT-DOWNLOAD
14 constant BT-COPY

variable BT-ALLOC-RC
variable BT-ALLOC-X
variable BT-ALLOC-H
variable BT-UPLOAD-RC
variable BT-UPLOAD-X
variable BT-UPLOAD-DST
variable BT-UPLOAD-LEN
variable BT-UPLOAD-SRC?
variable BT-DOWNLOAD-RC
variable BT-DOWNLOAD-X
variable BT-DOWNLOAD-SRC
variable BT-DOWNLOAD-LEN
variable BT-DOWNLOAD-DST?
variable BT-COPY-RC
variable BT-COPY-X
variable BT-COPY-DST
variable BT-COPY-SRC
variable BT-COPY-N
variable BT-FREE-RC
variable BT-FREE-X
PTR-VARIABLE BT-BUF-P
PTR-VARIABLE BT-OWN-ST
PTR-VARIABLE BT-OWN-BUF

301 constant BT-BUF0
901 constant BT-BUF1
401 constant BT-CTX0
402 constant BT-CTX1
16 constant BT-BUF-LEN
8 constant BT-HALF
$7FFFFFFFFFFFFFFF constant BT-MAX-N

create BT-SRC BT-BUF-LEN allot
create BT-DST BT-BUF-LEN allot

: BT-RESET ( -- )
   FT-RESET
   0 BT-ALLOC-RC !
   0 BT-ALLOC-X !
   BT-BUF0 BT-ALLOC-H !
   0 BT-UPLOAD-RC !
   0 BT-UPLOAD-X !
   0 BT-UPLOAD-DST !
   0 BT-UPLOAD-LEN !
   0 BT-UPLOAD-SRC? !
   0 BT-DOWNLOAD-RC !
   0 BT-DOWNLOAD-X !
   0 BT-DOWNLOAD-SRC !
   0 BT-DOWNLOAD-LEN !
   0 BT-DOWNLOAD-DST? !
   0 BT-COPY-RC !
   0 BT-COPY-X !
   0 BT-COPY-DST !
   0 BT-COPY-SRC !
   0 BT-COPY-N !
   0 BT-FREE-RC !
   0 BT-FREE-X !
   NULL$ drop dup BT-BUF-P ! dup BT-OWN-ST ! BT-OWN-BUF ! ;

: BT-FALLOC ( ptr n len -- rc ) {: out:ptr len:len :}
   BT-ALLOC len LEN>N FT-LOG
   out BT-BUF-P !
   BT-ALLOC-H @ out !
   BT-ALLOC-X @ FT-X
   BT-ALLOC-RC @ >RC ;

: BT-FUPLOAD ( cuda-devptr ptr u8 len -- rc )
   {: dev:cuda-devptr src:ptr len:len :}
   BT-UPLOAD dev CUDA-DEVPTR>N FT-LOG
   dev CUDA-DEVPTR>N BT-UPLOAD-DST !
   len LEN>N BT-UPLOAD-LEN !
   src BT-SRC = BT-UPLOAD-SRC? !
   BT-UPLOAD-X @ FT-X
   BT-UPLOAD-RC @ >RC ;

: BT-FDOWNLOAD ( ptr u8 cuda-devptr len -- rc )
   {: dst:ptr dev:cuda-devptr len:len :}
   BT-DOWNLOAD dev CUDA-DEVPTR>N FT-LOG
   dev CUDA-DEVPTR>N BT-DOWNLOAD-SRC !
   len LEN>N BT-DOWNLOAD-LEN !
   dst BT-DST = BT-DOWNLOAD-DST? !
   BT-DOWNLOAD-X @ FT-X
   BT-DOWNLOAD-RC @ >RC ;

: BT-FCOPY ( cuda-devptr cuda-devptr len -- rc )
   {: dst:cuda-devptr src:cuda-devptr len:len :}
   BT-COPY dst CUDA-DEVPTR>N FT-LOG
   dst CUDA-DEVPTR>N BT-COPY-DST !
   src CUDA-DEVPTR>N BT-COPY-SRC !
   len LEN>N BT-COPY-N !
   BT-COPY-X @ FT-X
   BT-COPY-RC @ >RC ;

: BT-FFREE ( cuda-devptr -- rc ) {: dev:cuda-devptr :}
   BT-FREE dev CUDA-DEVPTR>N FT-LOG
   BT-FREE-X @ FT-X
   BT-FREE-RC @ >RC ;

: BT-ON ( -- )
   FT-ON
   [: BT-FALLOC ;] CUMEMALLOC!
   [: BT-FUPLOAD ;] HTOD!
   [: BT-FDOWNLOAD ;] DTOH!
   [: BT-FCOPY ;] DTOD!
   [: BT-FFREE ;] CUMEMFREE! ;

: BT-OFF ( -- )
   FT-OFF ;

: BT-BYTE-LEN ( n -- CAD-NUM:byte-len )
   BYTE-LEN MATCH CAD-NUM:numeric-result
      ok OF ENDOF
      negative OF E-CADNUM-NEGATIVE throw ENDOF
      zero OF E-CADNUM-ZERO throw ENDOF
      overflow OF E-CADNUM-OVERFLOW throw ENDOF
      underflow OF E-CADNUM-UNDERFLOW throw ENDOF
      bad-alignment OF E-CADNUM-BAD-ALIGNMENT throw ENDOF
      misaligned OF E-CADNUM-MISALIGNED throw ENDOF
   ;MATCH ;

: BT-BYTE-OFF ( n -- CAD-NUM:byte-off )
   BYTE-OFF MATCH CAD-NUM:numeric-result
      ok OF ENDOF
      negative OF E-CADNUM-NEGATIVE throw ENDOF
      zero OF E-CADNUM-ZERO throw ENDOF
      overflow OF E-CADNUM-OVERFLOW throw ENDOF
      underflow OF E-CADNUM-UNDERFLOW throw ENDOF
      bad-alignment OF E-CADNUM-BAD-ALIGNMENT throw ENDOF
      misaligned OF E-CADNUM-MISALIGNED throw ENDOF
   ;MATCH ;

: BT-CODE ( result<n,n> -- n )
   MATCH result
      ok OF drop 0 ENDOF
      err OF ENDOF
   ;MATCH ;

: BT-SAVE-OWNERS ( GPU:session GPU:buffer -- GPU:session GPU:buffer )
   GB-TAKE dup BT-OWN-BUF ! GB-MINT
   swap GS-TAKE dup BT-OWN-ST ! GS-MINT swap ;

: BT-CHECK-OWNERS ( GPU:session GPU:buffer -- GPU:session GPU:buffer )
   GB-TAKE dup BT-OWN-BUF @ = TTRUE GB-MINT
   swap GS-TAKE dup BT-OWN-ST @ = TTRUE GS-MINT swap ;

: BT-MUST-ALLOC ( GPU:session -- GPU:session GPU:buffer )
   BT-BUF-LEN MEM:BYTES-ALLOC-LEN ALLOC MATCH result
      ok OF ENDOF
      err OF throw ENDOF
   ;MATCH ;

: BT-MUST-UPLOAD
   ( GPU:session GPU:buffer CAD-NUM:byte-off ptr u8 CAD-NUM:byte-len -- GPU:session GPU:buffer )
   UPLOAD BT-CODE 0 T= ;

: BT-MUST-DOWNLOAD
   ( GPU:session GPU:buffer CAD-NUM:byte-off ptr u8 CAD-NUM:byte-len -- GPU:session GPU:buffer )
   {: off:CAD-NUM:byte-off dst:ptr len:CAD-NUM:byte-len :}
   BT-SAVE-OWNERS
   off dst len DOWNLOAD BT-CODE {: code:n :}
   BT-CHECK-OWNERS code 0 T= ;

: BT-DOWNLOAD-ERR
   ( GPU:session GPU:buffer CAD-NUM:byte-off ptr u8 CAD-NUM:byte-len n -- GPU:session GPU:buffer )
   {: off:CAD-NUM:byte-off dst:ptr len:CAD-NUM:byte-len want:n :}
   BT-SAVE-OWNERS
   off dst len DOWNLOAD BT-CODE {: code:n :}
   BT-CHECK-OWNERS code want T= ;

: BT-MUST-COPY
   ( GPU:session GPU:buffer CAD-NUM:byte-off CAD-NUM:byte-off CAD-NUM:byte-len -- GPU:session GPU:buffer )
   {: dst:CAD-NUM:byte-off src:CAD-NUM:byte-off len:CAD-NUM:byte-len :}
   BT-SAVE-OWNERS
   dst src len GPU-SPAN-TEST:COPY-CALL BT-CODE {: code:n :}
   BT-CHECK-OWNERS code 0 T= ;

: BT-COPY-ERR
   ( GPU:session GPU:buffer CAD-NUM:byte-off CAD-NUM:byte-off CAD-NUM:byte-len n -- GPU:session GPU:buffer )
   {: dst:CAD-NUM:byte-off src:CAD-NUM:byte-off len:CAD-NUM:byte-len want:n :}
   BT-SAVE-OWNERS
   dst src len GPU-SPAN-TEST:COPY-CALL BT-CODE {: code:n :}
   BT-CHECK-OWNERS code want T= ;

: BT-MUST-SPAN
   ( GPU:session GPU:buffer CAD-NUM:byte-off CAD-NUM:byte-len -- GPU:session GPU:buffer cuda-devptr )
   GPU-SPAN-TEST:CALL MATCH result
      ok OF ENDOF
      err OF throw ENDOF
   ;MATCH ;

: BT-SPAN-WANT
   ( GPU:session GPU:buffer CAD-NUM:byte-off CAD-NUM:byte-len n -- GPU:session GPU:buffer )
   {: want:n :}
   BT-MUST-SPAN CUDA-DEVPTR>N want T= ;

: BT-SPAN-ERR
   ( GPU:session GPU:buffer CAD-NUM:byte-off CAD-NUM:byte-len n -- GPU:session GPU:buffer )
   {: want:n :}
   SPAN MATCH result
      ok OF CUDA-DEVPTR>N drop 0 1 T= ENDOF
      err OF want T= ENDOF
   ;MATCH ;

: BT-UPLOAD-ERR
   ( GPU:session GPU:buffer CAD-NUM:byte-off ptr u8 CAD-NUM:byte-len n -- GPU:session GPU:buffer )
   {: want:n :}
   UPLOAD BT-CODE want T= ;

: BT-MUST-FREE ( GPU:session GPU:buffer -- GPU:session )
   FREE BT-CODE 0 T= ;

: BT-FREE-ERR ( GPU:session GPU:buffer n -- GPU:session )
   {: want:n :}
   FREE BT-CODE want T= ;

: BT-ALLOC-ERR ( GPU:session n -- GPU:session )
   {: want:n :}
   BT-BUF-LEN MEM:BYTES-ALLOC-LEN ALLOC MATCH result
      ok OF BT-MUST-FREE 0 1 T= ENDOF
      err OF want T= ENDOF
   ;MATCH ;

: BT-BUF-CHILD ( -- )
   GPU-SESSION-TEST:CLOSE-STDERR
   BT-BUF-P @ @ drop
   s" " 0 die ;

: BT-WAIT-BUF-FAULT ( -- )
   PROC-FORK:CHECKED {: pid:pid :}
   pid PID>N 0= if BT-BUF-CHILD then
   pid PROC-WAIT-OUTCOME MATCH outcome
      exited OF FT-FAULT T= ENDOF
      signaled OF drop 0 1 T= ENDOF
      timeout OF 0 1 T= ENDOF
   ;MATCH ;

: BT-SAVE-BUF ( GPU:buffer -- GPU:buffer )
   GB-TAKE dup BT-BUF-P ! GB-MINT ;

: BT-ALLOC-REUSE ( GPU:session -- )
   0 BT-ALLOC-RC !
   0 BT-ALLOC-X !
   BT-BUF0 BT-ALLOC-H !
   0 BT-FREE-RC !
   0 BT-FREE-X !
   BT-MUST-ALLOC BT-MUST-FREE FT-MUST-CLOSE ;

: BT-ALLOC-LOG ( -- )
   FT-N @ 3 T=
   0 FT-OP@ FT-SET T=
   1 FT-OP@ BT-ALLOC T=
   1 FT-ARG@ BT-BUF-LEN T=
   2 FT-OP@ BT-FREE T=
   2 FT-ARG@ BT-BUF0 T= ;

: BT-ALLOC-RC-CASE ( -- )
   BT-RESET FT-MUST-OPEN FT-LOG-RESET
   91 BT-ALLOC-RC !
   91 BT-ALLOC-ERR
   BT-ALLOC-LOG
   BT-WAIT-BUF-FAULT
   BT-ALLOC-REUSE ;

: BT-ALLOC-X-CASE ( -- )
   BT-RESET FT-MUST-OPEN FT-LOG-RESET
   92 BT-ALLOC-X !
   93 BT-FREE-X !
   92 BT-ALLOC-ERR
   BT-ALLOC-LOG
   BT-WAIT-BUF-FAULT
   BT-ALLOC-REUSE ;

: BT-ALLOC-ZERO-CASE ( -- )
   BT-RESET FT-MUST-OPEN FT-LOG-RESET
   0 BT-ALLOC-H !
   E-CUDA BT-ALLOC-ERR
   FT-N @ 2 T=
   0 FT-OP@ FT-SET T=
   1 FT-OP@ BT-ALLOC T=
   BT-WAIT-BUF-FAULT
   BT-ALLOC-REUSE ;

: BT-ALLOC-BIND-RC ( -- )
   BT-RESET FT-MUST-OPEN FT-LOG-RESET
   0 FT-SET-N ! 0 FT-SET-I ! 103 FT-SET-RC !
   103 BT-ALLOC-ERR
   FT-N @ 1 T=
   0 FT-OP@ FT-SET T=
   BT-BUF-P @ NULL$ drop = TTRUE
   0 FT-SET-RC ! -1 FT-SET-I !
   BT-ALLOC-REUSE ;

: BT-ALLOC-BIND-X ( -- )
   BT-RESET FT-MUST-OPEN FT-LOG-RESET
   0 FT-SET-N ! 0 FT-SET-I ! 104 FT-SET-X !
   104 BT-ALLOC-ERR
   FT-N @ 1 T=
   0 FT-OP@ FT-SET T=
   BT-BUF-P @ NULL$ drop = TTRUE
   0 FT-SET-X ! -1 FT-SET-I !
   BT-ALLOC-REUSE ;

: BT-BUF-ALLOC-ERRORS ( -- )
   BT-ALLOC-RC-CASE
   BT-ALLOC-X-CASE
   BT-ALLOC-ZERO-CASE
   BT-ALLOC-BIND-RC
   BT-ALLOC-BIND-X ;

: BT-UPLOAD-LOG ( n n -- ) {: off:n len:n :}
   FT-N @ 2 T=
   0 FT-OP@ FT-SET T=
   1 FT-OP@ BT-UPLOAD T=
   BT-UPLOAD-DST @ BT-BUF0 off + T=
   BT-UPLOAD-LEN @ len T=
   BT-UPLOAD-SRC? @ TTRUE ;

: BT-UPLOAD-RC-CASE ( -- )
   BT-RESET FT-MUST-OPEN BT-MUST-ALLOC FT-LOG-RESET
   94 BT-UPLOAD-RC !
   5 BT-BYTE-OFF BT-SRC 7 BT-BYTE-LEN 94 BT-UPLOAD-ERR
   5 7 BT-UPLOAD-LOG
   0 BT-UPLOAD-RC !
   0 BT-BYTE-OFF BT-SRC BT-BUF-LEN BT-BYTE-LEN BT-MUST-UPLOAD
   BT-MUST-FREE FT-MUST-CLOSE ;

: BT-UPLOAD-X-CASE ( -- )
   BT-RESET FT-MUST-OPEN BT-MUST-ALLOC FT-LOG-RESET
   95 BT-UPLOAD-X !
   6 BT-BYTE-OFF BT-SRC 4 BT-BYTE-LEN 95 BT-UPLOAD-ERR
   6 4 BT-UPLOAD-LOG
   0 BT-UPLOAD-X !
   12 BT-BYTE-OFF BT-SRC 4 BT-BYTE-LEN BT-MUST-UPLOAD
   BT-MUST-FREE FT-MUST-CLOSE ;

: BT-UPLOAD-BIND-RC ( -- )
   BT-RESET FT-MUST-OPEN BT-MUST-ALLOC FT-LOG-RESET
   0 FT-SET-N ! 0 FT-SET-I ! 105 FT-SET-RC !
   0 BT-BYTE-OFF BT-SRC 1 BT-BYTE-LEN 105 BT-UPLOAD-ERR
   FT-N @ 1 T=
   0 FT-OP@ FT-SET T=
   0 FT-SET-RC ! -1 FT-SET-I !
   0 BT-BYTE-OFF BT-SRC 1 BT-BYTE-LEN BT-MUST-UPLOAD
   BT-MUST-FREE FT-MUST-CLOSE ;

: BT-UPLOAD-BIND-X ( -- )
   BT-RESET FT-MUST-OPEN BT-MUST-ALLOC FT-LOG-RESET
   0 FT-SET-N ! 0 FT-SET-I ! 106 FT-SET-X !
   0 BT-BYTE-OFF BT-SRC 1 BT-BYTE-LEN 106 BT-UPLOAD-ERR
   FT-N @ 1 T=
   0 FT-OP@ FT-SET T=
   0 FT-SET-X ! -1 FT-SET-I !
   0 BT-BYTE-OFF BT-SRC 1 BT-BYTE-LEN BT-MUST-UPLOAD
   BT-MUST-FREE FT-MUST-CLOSE ;

: BT-BUF-UPLOAD-ERRORS ( -- )
   BT-UPLOAD-RC-CASE
   BT-UPLOAD-X-CASE
   BT-UPLOAD-BIND-RC
   BT-UPLOAD-BIND-X ;

: BT-DOWNLOAD-LOG ( n n -- ) {: off:n len:n :}
   FT-N @ 2 T=
   0 FT-OP@ FT-SET T=
   1 FT-OP@ BT-DOWNLOAD T=
   BT-DOWNLOAD-SRC @ BT-BUF0 off + T=
   BT-DOWNLOAD-LEN @ len T=
   BT-DOWNLOAD-DST? @ TTRUE ;

: BT-DOWNLOAD-RC-CASE ( -- )
   BT-RESET FT-MUST-OPEN BT-MUST-ALLOC FT-LOG-RESET
   107 BT-DOWNLOAD-RC !
   5 BT-BYTE-OFF BT-DST 7 BT-BYTE-LEN 107 BT-DOWNLOAD-ERR
   5 7 BT-DOWNLOAD-LOG
   0 BT-DOWNLOAD-RC !
   0 BT-BYTE-OFF BT-DST BT-BUF-LEN BT-BYTE-LEN BT-MUST-DOWNLOAD
   BT-MUST-FREE FT-MUST-CLOSE ;

: BT-DOWNLOAD-X-CASE ( -- )
   BT-RESET FT-MUST-OPEN BT-MUST-ALLOC FT-LOG-RESET
   108 BT-DOWNLOAD-X !
   6 BT-BYTE-OFF BT-DST 4 BT-BYTE-LEN 108 BT-DOWNLOAD-ERR
   6 4 BT-DOWNLOAD-LOG
   0 BT-DOWNLOAD-X !
   12 BT-BYTE-OFF BT-DST 4 BT-BYTE-LEN BT-MUST-DOWNLOAD
   BT-MUST-FREE FT-MUST-CLOSE ;

: BT-DOWNLOAD-BIND-RC ( -- )
   BT-RESET FT-MUST-OPEN BT-MUST-ALLOC FT-LOG-RESET
   0 FT-SET-N ! 0 FT-SET-I ! 109 FT-SET-RC !
   0 BT-BYTE-OFF BT-DST 1 BT-BYTE-LEN 109 BT-DOWNLOAD-ERR
   FT-N @ 1 T=
   0 FT-OP@ FT-SET T=
   0 FT-SET-RC ! -1 FT-SET-I !
   0 BT-BYTE-OFF BT-DST 1 BT-BYTE-LEN BT-MUST-DOWNLOAD
   BT-MUST-FREE FT-MUST-CLOSE ;

: BT-DOWNLOAD-BIND-X ( -- )
   BT-RESET FT-MUST-OPEN BT-MUST-ALLOC FT-LOG-RESET
   0 FT-SET-N ! 0 FT-SET-I ! 110 FT-SET-X !
   0 BT-BYTE-OFF BT-DST 1 BT-BYTE-LEN 110 BT-DOWNLOAD-ERR
   FT-N @ 1 T=
   0 FT-OP@ FT-SET T=
   0 FT-SET-X ! -1 FT-SET-I !
   0 BT-BYTE-OFF BT-DST 1 BT-BYTE-LEN BT-MUST-DOWNLOAD
   BT-MUST-FREE FT-MUST-CLOSE ;

: BT-BUF-DOWNLOAD-ERRORS ( -- )
   BT-DOWNLOAD-RC-CASE
   BT-DOWNLOAD-X-CASE
   BT-DOWNLOAD-BIND-RC
   BT-DOWNLOAD-BIND-X ;

: BT-COPY-LOG ( n n n -- ) {: dst:n src:n len:n :}
   FT-N @ 2 T=
   0 FT-OP@ FT-SET T=
   1 FT-OP@ BT-COPY T=
   BT-COPY-DST @ dst T=
   BT-COPY-SRC @ src T=
   BT-COPY-N @ len T= ;

: BT-COPY-BOUNDS ( -- )
   BT-RESET FT-MUST-OPEN BT-MUST-ALLOC FT-LOG-RESET
   13 BT-BYTE-OFF 0 BT-BYTE-OFF 4 BT-BYTE-LEN
      E-BUF-BOUNDS BT-COPY-ERR
   FT-N @ 0 T=
   0 BT-BYTE-OFF 13 BT-BYTE-OFF 4 BT-BYTE-LEN
      E-BUF-BOUNDS BT-COPY-ERR
   FT-N @ 0 T=
   BT-MUST-FREE FT-MUST-CLOSE ;

: BT-COPY-OVERLAP ( -- )
   BT-RESET FT-MUST-OPEN BT-MUST-ALLOC FT-LOG-RESET
   4 BT-BYTE-OFF 8 BT-BYTE-OFF 8 BT-BYTE-LEN
      E-BUF-OVERLAP BT-COPY-ERR
   FT-N @ 0 T=
   8 BT-BYTE-OFF 4 BT-BYTE-OFF 8 BT-BYTE-LEN
      E-BUF-OVERLAP BT-COPY-ERR
   FT-N @ 0 T=
   4 BT-BYTE-OFF 4 BT-BYTE-OFF 8 BT-BYTE-LEN
      E-BUF-OVERLAP BT-COPY-ERR
   FT-N @ 0 T=
   BT-MUST-FREE FT-MUST-CLOSE ;

: BT-COPY-DISJOINT ( -- )
   BT-RESET FT-MUST-OPEN BT-MUST-ALLOC FT-LOG-RESET
   8 BT-BYTE-OFF 0 BT-BYTE-OFF 8 BT-BYTE-LEN BT-MUST-COPY
   BT-BUF0 8 + BT-BUF0 8 BT-COPY-LOG
   FT-LOG-RESET
   0 BT-BYTE-OFF 8 BT-BYTE-OFF 8 BT-BYTE-LEN BT-MUST-COPY
   BT-BUF0 BT-BUF0 8 + 8 BT-COPY-LOG
   FT-LOG-RESET
   4 BT-BYTE-OFF 4 BT-BYTE-OFF 0 BT-BYTE-LEN BT-MUST-COPY
   BT-BUF0 4 + BT-BUF0 4 + 0 BT-COPY-LOG
   BT-MUST-FREE FT-MUST-CLOSE ;

: BT-COPY-BIND-RC ( -- )
   BT-RESET FT-MUST-OPEN BT-MUST-ALLOC FT-LOG-RESET
   0 FT-SET-N ! 0 FT-SET-I ! 111 FT-SET-RC !
   8 BT-BYTE-OFF 0 BT-BYTE-OFF 8 BT-BYTE-LEN 111 BT-COPY-ERR
   FT-N @ 1 T= 0 FT-OP@ FT-SET T=
   BT-MUST-FREE FT-MUST-CLOSE ;

: BT-COPY-BIND-X ( -- )
   BT-RESET FT-MUST-OPEN BT-MUST-ALLOC FT-LOG-RESET
   0 FT-SET-N ! 0 FT-SET-I ! 112 FT-SET-X !
   8 BT-BYTE-OFF 0 BT-BYTE-OFF 8 BT-BYTE-LEN 112 BT-COPY-ERR
   FT-N @ 1 T= 0 FT-OP@ FT-SET T=
   BT-MUST-FREE FT-MUST-CLOSE ;

: BT-COPY-RC-CASE ( -- )
   BT-RESET FT-MUST-OPEN BT-MUST-ALLOC FT-LOG-RESET
   113 BT-COPY-RC !
   8 BT-BYTE-OFF 0 BT-BYTE-OFF 8 BT-BYTE-LEN 113 BT-COPY-ERR
   BT-BUF0 8 + BT-BUF0 8 BT-COPY-LOG
   BT-MUST-FREE FT-MUST-CLOSE ;

: BT-COPY-X-CASE ( -- )
   BT-RESET FT-MUST-OPEN BT-MUST-ALLOC FT-LOG-RESET
   114 BT-COPY-X !
   8 BT-BYTE-OFF 0 BT-BYTE-OFF 8 BT-BYTE-LEN 114 BT-COPY-ERR
   BT-BUF0 8 + BT-BUF0 8 BT-COPY-LOG
   BT-MUST-FREE FT-MUST-CLOSE ;

: BT-BUF-COPY ( -- )
   BT-COPY-BOUNDS
   BT-COPY-OVERLAP
   BT-COPY-DISJOINT
   BT-COPY-BIND-RC
   BT-COPY-BIND-X
   BT-COPY-RC-CASE
   BT-COPY-X-CASE ;

: BT-DOWNLOAD-BOUNDS ( -- )
   BT-RESET FT-MUST-OPEN BT-MUST-ALLOC FT-LOG-RESET
   13 BT-BYTE-OFF BT-DST 4 BT-BYTE-LEN E-BUF-BOUNDS BT-DOWNLOAD-ERR
   FT-N @ 0 T=
   BT-MAX-N BT-BYTE-OFF BT-DST 1 BT-BYTE-LEN E-BUF-BOUNDS BT-DOWNLOAD-ERR
   FT-N @ 0 T=
   BT-BUF-LEN 1+ BT-BYTE-OFF BT-DST 0 BT-BYTE-LEN E-BUF-BOUNDS BT-DOWNLOAD-ERR
   FT-N @ 0 T=
   0 BT-BYTE-OFF BT-DST 0 BT-BYTE-LEN BT-MUST-DOWNLOAD
   0 0 BT-DOWNLOAD-LOG
   FT-LOG-RESET
   BT-BUF-LEN BT-BYTE-OFF BT-DST 0 BT-BYTE-LEN BT-MUST-DOWNLOAD
   BT-BUF-LEN 0 BT-DOWNLOAD-LOG
   BT-MUST-FREE FT-MUST-CLOSE ;

: BT-BUF-BOUNDS ( -- )
   BT-RESET FT-MUST-OPEN BT-MUST-ALLOC FT-LOG-RESET
   13 BT-BYTE-OFF BT-SRC 4 BT-BYTE-LEN E-BUF-BOUNDS BT-UPLOAD-ERR
   FT-N @ 0 T=
   BT-MAX-N BT-BYTE-OFF BT-SRC 1 BT-BYTE-LEN E-BUF-BOUNDS BT-UPLOAD-ERR
   FT-N @ 0 T=
   BT-BUF-LEN BT-BYTE-OFF BT-SRC 0 BT-BYTE-LEN BT-MUST-UPLOAD
   BT-BUF-LEN 0 BT-UPLOAD-LOG
   BT-UPLOAD-DST @ BT-BUF0 BT-BUF-LEN + T=
   BT-MUST-FREE FT-MUST-CLOSE ;

: BT-SPAN-RANGES ( -- )
   BT-RESET FT-MUST-OPEN BT-MUST-ALLOC
   0 BT-BYTE-OFF BT-BUF-LEN BT-BYTE-LEN BT-BUF0 BT-SPAN-WANT
   15 BT-BYTE-OFF 1 BT-BYTE-LEN BT-BUF0 15 + BT-SPAN-WANT
   7 BT-BYTE-OFF 0 BT-BYTE-LEN BT-BUF0 7 + BT-SPAN-WANT
   BT-BUF-LEN BT-BYTE-OFF 0 BT-BYTE-LEN
      BT-BUF0 BT-BUF-LEN + BT-SPAN-WANT
   FT-LOG-RESET
   BT-BUF-LEN BT-BYTE-OFF 1 BT-BYTE-LEN E-BUF-BOUNDS BT-SPAN-ERR
   BT-BUF-LEN 1 + BT-BYTE-OFF 0 BT-BYTE-LEN E-BUF-BOUNDS BT-SPAN-ERR
   13 BT-BYTE-OFF 4 BT-BYTE-LEN E-BUF-BOUNDS BT-SPAN-ERR
   BT-MAX-N BT-BYTE-OFF 1 BT-BYTE-LEN E-BUF-BOUNDS BT-SPAN-ERR
   FT-N @ 0 T=
   BT-MUST-FREE FT-MUST-CLOSE ;

: BT-SPAN-BIND ( -- )
   BT-RESET FT-MUST-OPEN BT-MUST-ALLOC FT-LOG-RESET
   0 FT-SET-N ! 0 FT-SET-I ! 107 FT-SET-RC !
   0 BT-BYTE-OFF 1 BT-BYTE-LEN 107 BT-SPAN-ERR
   FT-N @ 1 T=
   0 FT-OP@ FT-SET T=
   0 FT-SET-RC ! -1 FT-SET-I !
   2 BT-BYTE-OFF 1 BT-BYTE-LEN BT-BUF0 2 + BT-SPAN-WANT
   BT-MUST-FREE FT-MUST-CLOSE ;

: BT-SPAN-TWO ( -- )
   BT-RESET
   BT-CTX0 FT-CTX ! BT-BUF0 BT-ALLOC-H ! FT-MUST-OPEN BT-MUST-ALLOC
   BT-CTX1 FT-CTX ! BT-BUF1 BT-ALLOC-H ! FT-MUST-OPEN BT-MUST-ALLOC
   FT-LOG-RESET
   3 BT-BYTE-OFF 1 BT-BYTE-LEN BT-BUF1 3 + BT-SPAN-WANT
   2swap
   4 BT-BYTE-OFF 1 BT-BYTE-LEN BT-BUF0 4 + BT-SPAN-WANT
   2swap
   FT-N @ 2 T=
   0 FT-ARG@ BT-CTX1 T=
   1 FT-ARG@ BT-CTX0 T=
   BT-MUST-FREE FT-MUST-CLOSE
   BT-MUST-FREE FT-MUST-CLOSE ;

: BT-FREE-LOG ( -- )
   FT-N @ 2 T=
   0 FT-OP@ FT-SET T=
   1 FT-OP@ BT-FREE T=
   1 FT-ARG@ BT-BUF0 T= ;

: BT-FREE-FIRST-RC ( -- )
   BT-RESET FT-MUST-OPEN BT-MUST-ALLOC BT-SAVE-BUF FT-LOG-RESET
   0 FT-SET-N ! 0 FT-SET-I !
   96 FT-SET-RC ! 97 BT-FREE-RC !
   96 BT-FREE-ERR
   BT-FREE-LOG
   BT-WAIT-BUF-FAULT
   0 FT-SET-RC ! -1 FT-SET-I !
   BT-ALLOC-REUSE ;

: BT-FREE-FIRST-X ( -- )
   BT-RESET FT-MUST-OPEN BT-MUST-ALLOC BT-SAVE-BUF FT-LOG-RESET
   0 FT-SET-N ! 0 FT-SET-I !
   98 FT-SET-X ! 99 BT-FREE-X !
   98 BT-FREE-ERR
   BT-FREE-LOG
   BT-WAIT-BUF-FAULT
   0 FT-SET-X ! -1 FT-SET-I !
   BT-ALLOC-REUSE ;

: BT-FREE-RC-CASE ( -- )
   BT-RESET FT-MUST-OPEN BT-MUST-ALLOC BT-SAVE-BUF FT-LOG-RESET
   100 BT-FREE-RC !
   100 BT-FREE-ERR
   BT-FREE-LOG
   BT-WAIT-BUF-FAULT
   BT-ALLOC-REUSE ;

: BT-FREE-X-CASE ( -- )
   BT-RESET FT-MUST-OPEN BT-MUST-ALLOC BT-SAVE-BUF FT-LOG-RESET
   102 BT-FREE-X !
   102 BT-FREE-ERR
   BT-FREE-LOG
   BT-WAIT-BUF-FAULT
   BT-ALLOC-REUSE ;

: BT-BUF-FREE-ERRORS ( -- )
   BT-FREE-FIRST-RC
   BT-FREE-FIRST-X
   BT-FREE-RC-CASE
   BT-FREE-X-CASE ;

: BT-REAL-FILL ( -- )
   BT-BUF-LEN 0 ?do
      i 17 * 3 + 255 and BT-SRC i + c!
      0 BT-DST i + c!
   loop ;

: BT-REAL-EQUAL ( -- )
   BT-BUF-LEN 0 ?do
      BT-SRC i + c@ BT-DST i + c@ T=
   loop ;

: BT-REAL-COPY-EQUAL ( -- )
   BT-HALF 0 ?do
      BT-SRC i + c@ BT-DST i + c@ T=
   loop ;

: BT-REAL-BUF ( GPU:session -- GPU:session )
   BT-REAL-FILL
   BT-MUST-ALLOC
   0 BT-BYTE-OFF BT-SRC BT-BUF-LEN BT-BYTE-LEN BT-MUST-UPLOAD
   0 BT-BYTE-OFF BT-DST BT-BUF-LEN BT-BYTE-LEN BT-MUST-DOWNLOAD
   BT-REAL-EQUAL
   BT-MUST-FREE ;

: BT-REAL-SPAN ( GPU:session -- GPU:session )
   BT-MUST-ALLOC
   0 BT-BYTE-OFF 0 BT-BYTE-LEN BT-MUST-SPAN
      CUDA-DEVPTR>N {: base:n :}
   5 BT-BYTE-OFF 1 BT-BYTE-LEN BT-MUST-SPAN
      CUDA-DEVPTR>N base - 5 T=
   BT-MUST-FREE ;

: BT-REAL-COPY ( GPU:session -- GPU:session )
   BT-REAL-FILL
   BT-MUST-ALLOC
   0 BT-BYTE-OFF BT-SRC BT-BUF-LEN BT-BYTE-LEN BT-MUST-UPLOAD
   BT-HALF BT-BYTE-OFF 0 BT-BYTE-OFF BT-HALF BT-BYTE-LEN BT-MUST-COPY
   BT-HALF BT-BYTE-OFF BT-DST BT-HALF BT-BYTE-LEN BT-MUST-DOWNLOAD
   BT-REAL-COPY-EQUAL
   BT-MUST-FREE ;

: BT-REAL-TWO ( -- )
   FT-MUST-OPEN FT-MUST-OPEN
   BT-REAL-COPY swap BT-REAL-BUF swap
   FT-MUST-CLOSE FT-MUST-CLOSE
   FT-MUST-OPEN FT-MUST-OPEN
   BT-REAL-SPAN swap BT-REAL-BUF
   FT-MUST-CLOSE FT-MUST-CLOSE ;

: BT-RUN ( -- )
   T-RESET
   BT-ON
   BT-BUF-ALLOC-ERRORS
   BT-BUF-UPLOAD-ERRORS
   BT-BUF-BOUNDS
   BT-BUF-DOWNLOAD-ERRORS
   BT-DOWNLOAD-BOUNDS
   BT-BUF-COPY
   BT-SPAN-RANGES
   BT-SPAN-BIND
   BT-SPAN-TWO
   BT-BUF-FREE-ERRORS
   BT-OFF
   BT-REAL-TWO
   T-REPORT ;

BT-RUN

;using
;using

;package
s" gpu-buffer-test: ok" type cr
