\ maki/tensor-test.f - nominal tensor metadata tests.

require lib/test.f
require test/checker-assert.f
require maki/tensor.f

package MAKI

T-RESET

DT-F32 DT-SIZE 4 DIM-IS? TTRUE
DT-F16 DT-SIZE 2 DIM-IS? TTRUE
DT-BF16 DT-SIZE 2 DIM-IS? TTRUE
DT-U32 DT-SIZE 4 DIM-IS? TTRUE
DT-I32 DT-SIZE 4 DIM-IS? TTRUE

3 4 SHAPE SHAPE-ELEMS 12 DIM-IS? TTRUE
1 1 SHAPE SHAPE-ELEMS 1 DIM-IS? TTRUE

3 1 SHAPE 3 4 SHAPE SHAPE-BCAST? TTRUE
1 4 SHAPE 3 4 SHAPE SHAPE-BCAST? TTRUE
3 4 SHAPE 3 4 SHAPE SHAPE-BCAST? TTRUE
3 4 SHAPE 2 4 SHAPE SHAPE-BCAST? TFALSE
3 4 SHAPE 3 5 SHAPE SHAPE-BCAST? TFALSE

3 4 SHAPE DT-F32 TENSOR-BYTES 48 DIM-IS? TTRUE
2 8 SHAPE DT-F16 TENSOR-BYTES 32 DIM-IS? TTRUE

3 4 SHAPE 3 4 SHAPE SHAPE-EQUAL? TTRUE
3 4 SHAPE 3 5 SHAPE SHAPE-EQUAL? TFALSE
3 4 SHAPE 3 4 SHAPE-IS? TTRUE

3 1 SHAPE 3 4 SHAPE BCAST-SHAPE 3 4 SHAPE SHAPE-EQUAL? TTRUE
1 1 SHAPE 6 8 SHAPE BCAST-SHAPE 6 8 SHAPE SHAPE-EQUAL? TTRUE
3 4 SHAPE TRANSPOSE-SHAPE 4 3 SHAPE SHAPE-EQUAL? TTRUE

3 1 SHAPE SHAPE-ELEMS 1 1 SHAPE SHAPE-ELEMS DIM-BCAST? TTRUE
3 1 SHAPE SHAPE-ELEMS DT-F32 DT-SIZE DIM-BCAST? TFALSE
3 1 SHAPE SHAPE-ELEMS DT-F32 DT-SIZE DIM-MAX 4 DIM-IS? TTRUE
3 1 SHAPE SHAPE-ELEMS 1 3 SHAPE SHAPE-ELEMS DIM-EQUAL? TTRUE
3 1 SHAPE drop 4 1 SHAPE drop ROWS-EQUAL? TFALSE
1 5 SHAPE nip 2 5 SHAPE nip COLS-EQUAL? TTRUE
2 1 SHAPE drop 3 1 SHAPE drop ROWS+ 5 1 SHAPE drop ROWS-EQUAL? TTRUE
8 1 SHAPE drop 3 1 SHAPE drop ROWS- 5 1 SHAPE drop ROWS-EQUAL? TTRUE
1 2 SHAPE nip 1 3 SHAPE nip COLS+ 1 5 SHAPE nip COLS-EQUAL? TTRUE
1 8 SHAPE nip 1 3 SHAPE nip COLS- 1 5 SHAPE nip COLS-EQUAL? TTRUE
DT-F16 DT-SIZE DT-BF16 DT-SIZE DIM* 4 DIM-IS? TTRUE

0 DTYPE-DECODE DT-F32 DTYPE-EQUAL? TTRUE
1 LAYOUT-DECODE LAY-COL LAYOUT-EQUAL? TTRUE
2 ADDRESS-SPACE-DECODE SPACE-SHARED ADDRESS-SPACE-EQUAL? TTRUE
DT-F32 DT-F16 DTYPE-EQUAL? TFALSE
LAY-ROW LAY-COL LAYOUT-EQUAL? TFALSE
SPACE-HOST SPACE-GLOBAL ADDRESS-SPACE-EQUAL? TFALSE
0 DT-VALID? TTRUE 4 DT-VALID? TTRUE 5 DT-VALID? TFALSE
0 LAYOUT-VALID? TTRUE 2 LAYOUT-VALID? TFALSE
0 ADDRESS-SPACE-VALID? TTRUE 4 ADDRESS-SPACE-VALID? TFALSE
1 2 SHAPE nip 2 1 SHAPE drop INNER-EQUAL? TTRUE

: TN-BAD-DT ( -- )
   99 DTYPE-DECODE drop ;

: TN-BAD-DIM ( -- )
   -1 1 SHAPE 2drop ;

: TN-BAD-LAYOUT ( -- )
   99 LAYOUT-DECODE drop ;

: TN-BAD-SPACE ( -- )
   99 ADDRESS-SPACE-DECODE drop ;

: TN-BAD-BCAST ( -- )
   2 3 SHAPE 4 5 SHAPE BCAST-SHAPE 2drop ;

' TN-BAD-DT E-MK-DTYPE TTHROWS
' TN-BAD-DIM E-MK-DIM TTHROWS
' TN-BAD-LAYOUT E-MK-LAYOUT TTHROWS
' TN-BAD-SPACE E-MK-SPACE TTHROWS
' TN-BAD-BCAST E-MK-DIM TTHROWS

\ Same-cell semantic swaps reject before runtime.
s" TENSOR-NEG-DIM-DTYPE ( CAD-KIND:dim CAD-KIND:dtype -- CAD-KIND:dim ) MAKI:DIM*" CHECK-QUIET-CANDIDATE! 0 T=
s" TENSOR-NEG-DTYPE-LAYOUT ( CAD-KIND:rows CAD-KIND:cols CAD-KIND:layout -- CAD-KIND:dim ) MAKI:TENSOR-BYTES" CHECK-QUIET-CANDIDATE! 0 T=
s" TENSOR-NEG-ROWS-COLS ( CAD-KIND:cols CAD-KIND:rows -- CAD-KIND:dim ) MAKI:SHAPE-ELEMS" CHECK-QUIET-CANDIDATE! 0 T=

T-REPORT

end-package
