\ maki/tensor-value-test.f - nominal tensor descriptor and storage tests.

require lib/test.f
require test/checker-assert.f
require maki/tensor-value.f

package MAKI

T-RESET

create TVT-BX 4 cells allot
1.0 TVT-BX 0 T-SET
2.0 TVT-BX 1 T-SET
3.0 TVT-BX 2 T-SET
4.0 TVT-BX 3 T-SET

: TVT-A16 ( -- ptr a )
   TVT-BX TVT-BX P>N 15 and 16 swap - 15 and + ;

: TVT-SHAPE? ( tensor n n -- bool )
   {: t:tensor rows:n cols:n :}
   t TENSOR:TV-ROWS@ t TENSOR:TV-COLS@ rows cols SHAPE-IS? ;

\ Default construction records typed host facts.
TVT-BX 2 2 SHAPE TENSOR:TV-NEW
dup 2 2 TVT-SHAPE? TTRUE
dup TENSOR:TV-DTYPE@ DT-F32 DTYPE-EQUAL? TTRUE
dup TENSOR:TV-LAYOUT@ LAY-ROW LAYOUT-EQUAL? TTRUE
dup TENSOR:TV-SPACE@ SPACE-HOST ADDRESS-SPACE-EQUAL? TTRUE
dup TENSOR:TV-ELEMS 4 DIM-IS? TTRUE
dup TENSOR:TV-HAS-DATA? TTRUE
dup TENSOR:TV-DATA@ TVT-BX = TTRUE
drop

\ Materialized host storage records explicit dtype/layout without false space provenance.
TVT-BX 3 5 SHAPE DT-BF16 LAY-COL TENSOR:TV-NEW-HOST
dup 3 5 TVT-SHAPE? TTRUE
dup TENSOR:TV-DTYPE@ DT-BF16 DTYPE-EQUAL? TTRUE
dup TENSOR:TV-LAYOUT@ LAY-COL LAYOUT-EQUAL? TTRUE
dup TENSOR:TV-SPACE@ SPACE-HOST ADDRESS-SPACE-EQUAL? TTRUE
drop

TVT-A16 1 1 SHAPE TENSOR:TV-NEW dup TENSOR:TV-ALIGN@ AL-16 T= drop
TVT-A16 8 + 1 1 SHAPE TENSOR:TV-NEW dup TENSOR:TV-ALIGN@ AL-8 T= drop
TVT-A16 4 + 1 1 SHAPE TENSOR:TV-NEW dup TENSOR:TV-ALIGN@ AL-4 T= drop
TVT-A16 2 + 1 1 SHAPE TENSOR:TV-NEW dup TENSOR:TV-ALIGN@ AL-BYTE T= drop
TVT-A16 1 + 1 1 SHAPE TENSOR:TV-NEW dup TENSOR:TV-ALIGN@ AL-BYTE T= drop

2 3 SHAPE DT-F32 LAY-ROW SPACE-GLOBAL TENSOR:TV-DESC
dup 2 3 TVT-SHAPE? TTRUE
dup TENSOR:TV-DTYPE@ DT-F32 DTYPE-EQUAL? TTRUE
dup TENSOR:TV-LAYOUT@ LAY-ROW LAYOUT-EQUAL? TTRUE
dup TENSOR:TV-SPACE@ SPACE-GLOBAL ADDRESS-SPACE-EQUAL? TTRUE
dup TENSOR:TV-ALIGN@ AL-UNKNOWN T=
dup TENSOR:TV-HAS-DATA? TFALSE
drop

\ Bufferless descriptors may represent target spaces because they claim no pointer provenance.
1 1 SHAPE DT-F16 LAY-ROW SPACE-SHARED TENSOR:TV-DESC
dup TENSOR:TV-SPACE@ SPACE-SHARED ADDRESS-SPACE-EQUAL? TTRUE
drop

\ Eager interop remains byte-for-byte equivalent to the legacy array kernel.
create TVT-IX 4 cells allot
create TVT-IW 4 cells allot
create TVT-IB 2 cells allot
create TVT-IY 4 cells allot
create TVT-IYE 4 cells allot
1.0 TVT-IX 0 T-SET 2.0 TVT-IX 1 T-SET 3.0 TVT-IX 2 T-SET 4.0 TVT-IX 3 T-SET
5.0 TVT-IW 0 T-SET 6.0 TVT-IW 1 T-SET 7.0 TVT-IW 2 T-SET 8.0 TVT-IW 3 T-SET
100.0 TVT-IB 0 T-SET 200.0 TVT-IB 1 T-SET

TVT-IX TVT-IW TVT-IB TVT-IYE 2 2 2 LINEAR
TVT-IX 2 2 SHAPE TENSOR:TV-NEW
TVT-IW 2 2 SHAPE TENSOR:TV-NEW
TVT-IB 1 2 SHAPE TENSOR:TV-NEW
TVT-IY 2 2 SHAPE TENSOR:TV-NEW
TENSOR:TV-LINEAR drop

TVT-IY 0 T-GET TVT-IYE 0 T-GET f- f>s 0 T=
TVT-IY 1 T-GET TVT-IYE 1 T-GET f- f>s 0 T=
TVT-IY 2 T-GET TVT-IYE 2 T-GET f- f>s 0 T=
TVT-IY 3 T-GET TVT-IYE 3 T-GET f- f>s 0 T=
TVT-IY 0 T-GET 0.5 f+ f>s 119 T=
TVT-IY 1 T-GET 0.5 f+ f>s 222 T=
TVT-IY 3 T-GET 0.5 f+ f>s 250 T=

variable TVT-BLDX
TENSOR:PLAN-RESET
2 3 SHAPE DT-F32 LAY-ROW SPACE-GLOBAL TENSOR:TV-DESC TVT-BLDX !
OP-GELU TENSOR:PLAN-OP-BEGIN
TVT-BLDX @ TENSOR:PLAN-IN+
2 3 SHAPE DT-F32 LAY-ROW SPACE-GLOBAL TENSOR:TV-DESC TENSOR:PLAN-OP+
TENSOR:PLAN-N@ 1 T=
0 TENSOR:PLAN-OP@ OP-GELU T=
0 TENSOR:PLAN-IN-COUNT@ 1 T=
0 0 TENSOR:PLAN-IN@ TVT-BLDX @ TENSOR:TV-EQUAL? TTRUE

variable TVT-X
variable TVT-W1
variable TVT-B1
variable TVT-W2
variable TVT-B2
TENSOR:PLAN-RESET
2 3 SHAPE DT-F32 LAY-ROW SPACE-GLOBAL TENSOR:TV-DESC TVT-X !
3 4 SHAPE DT-F32 LAY-ROW SPACE-GLOBAL TENSOR:TV-DESC TVT-W1 !
1 4 SHAPE DT-F32 LAY-ROW SPACE-GLOBAL TENSOR:TV-DESC TVT-B1 !
4 5 SHAPE DT-F32 LAY-ROW SPACE-GLOBAL TENSOR:TV-DESC TVT-W2 !
1 5 SHAPE DT-F32 LAY-ROW SPACE-GLOBAL TENSOR:TV-DESC TVT-B2 !
TVT-X @ TVT-W1 @ TVT-B1 @ TENSOR:PLINEAR
TENSOR:PGELU
TVT-W2 @ TVT-B2 @ TENSOR:PLINEAR drop

TENSOR:PLAN-N@ 3 T=
0 TENSOR:PLAN-OP@ OP-LINEAR T=
1 TENSOR:PLAN-OP@ OP-GELU T=
2 TENSOR:PLAN-OP@ OP-LINEAR T=
0 TENSOR:PLAN-IN-COUNT@ 3 T=
1 TENSOR:PLAN-IN-COUNT@ 1 T=
2 TENSOR:PLAN-IN-COUNT@ 3 T=
0 0 TENSOR:PLAN-IN@ TVT-X @ TENSOR:TV-EQUAL? TTRUE
0 1 TENSOR:PLAN-IN@ TVT-W1 @ TENSOR:TV-EQUAL? TTRUE
0 2 TENSOR:PLAN-IN@ TVT-B1 @ TENSOR:TV-EQUAL? TTRUE
1 0 TENSOR:PLAN-IN@ 0 TENSOR:PLAN-OUT@ TENSOR:TV-EQUAL? TTRUE
2 0 TENSOR:PLAN-IN@ 1 TENSOR:PLAN-OUT@ TENSOR:TV-EQUAL? TTRUE
2 1 TENSOR:PLAN-IN@ TVT-W2 @ TENSOR:TV-EQUAL? TTRUE
0 TENSOR:PLAN-OUT@ 2 4 TVT-SHAPE? TTRUE
1 TENSOR:PLAN-OUT@ 2 4 TVT-SHAPE? TTRUE
2 TENSOR:PLAN-OUT@ 2 5 TVT-SHAPE? TTRUE

: TVT-BAD-DT ( -- )
   99 DTYPE-DECODE drop ;

: TVT-BAD-LAY ( -- )
   99 LAYOUT-DECODE drop ;

: TVT-BAD-SPACE ( -- )
   99 ADDRESS-SPACE-DECODE drop ;

: TVT-NODATA ( -- )
   2 2 SHAPE DT-F32 LAY-ROW SPACE-GLOBAL TENSOR:TV-DESC
   TENSOR:TV-DATA@ drop ;

: TVT-BAD-SHAPE ( -- )
   TVT-BX 2 3 SHAPE TENSOR:TV-NEW
   TVT-BX 2 2 SHAPE TENSOR:TV-NEW
   TVT-BX 1 2 SHAPE TENSOR:TV-NEW
   TVT-BX 2 2 SHAPE TENSOR:TV-NEW
   TENSOR:TV-LINEAR drop ;

: TVT-PLAN-IDX ( -- )
   TENSOR:PLAN-RESET 0 TENSOR:PLAN-OP@ drop ;

: TVT-OPKIND ( -- )
   TENSOR:PLAN-RESET 99 TENSOR:PLAN-OP-BEGIN ;

: TVT-PLAN-DBL ( -- )
   TENSOR:PLAN-RESET
   OP-GELU TENSOR:PLAN-OP-BEGIN
   OP-GELU TENSOR:PLAN-OP-BEGIN ;

: TVT-IN-NB ( -- )
   TENSOR:PLAN-RESET
   2 2 SHAPE DT-F32 LAY-ROW SPACE-GLOBAL TENSOR:TV-DESC TENSOR:PLAN-IN+ ;

: TVT-OP-NB ( -- )
   TENSOR:PLAN-RESET
   2 2 SHAPE DT-F32 LAY-ROW SPACE-GLOBAL TENSOR:TV-DESC TENSOR:PLAN-OP+ ;

: TVT-FULL-TV ( -- )
   TENSOR:TV-RESET
   TENSOR:TV-CAP 1+ 0 ?do
      2 2 SHAPE DT-F32 LAY-ROW SPACE-GLOBAL TENSOR:TV-DESC drop
   loop ;

: TVT-FULL-PLAN ( -- )
   TENSOR:TV-RESET
   TENSOR:PLAN-RESET
   TENSOR:PLAN-CAP 1+ 0 ?do
      OP-GELU TENSOR:PLAN-OP-BEGIN
      2 2 SHAPE DT-F32 LAY-ROW SPACE-GLOBAL TENSOR:TV-DESC TENSOR:PLAN-OP+
   loop ;

: TVT-STALE ( -- )
   TENSOR:TV-RESET
   2 2 SHAPE DT-F32 LAY-ROW SPACE-GLOBAL TENSOR:TV-DESC {: old:tensor :}
   TENSOR:TV-RESET
   2 2 SHAPE DT-F32 LAY-ROW SPACE-GLOBAL TENSOR:TV-DESC drop
   old TENSOR:TV-ROWS@ drop ;

: TVT-STALE-PLAN ( -- )
   TENSOR:TV-RESET TENSOR:PLAN-RESET
   2 2 SHAPE DT-F32 LAY-ROW SPACE-GLOBAL TENSOR:TV-DESC {: x:tensor :}
   OP-GELU TENSOR:PLAN-OP-BEGIN x TENSOR:PLAN-IN+
   2 2 SHAPE DT-F32 LAY-ROW SPACE-GLOBAL TENSOR:TV-DESC TENSOR:PLAN-OP+
   TENSOR:TV-RESET
   2 2 SHAPE DT-F32 LAY-ROW SPACE-GLOBAL TENSOR:TV-DESC drop
   0 0 TENSOR:PLAN-IN@ drop ;

' TVT-BAD-DT E-MK-DTYPE TTHROWS
' TVT-BAD-LAY E-MK-LAYOUT TTHROWS
' TVT-BAD-SPACE E-MK-SPACE TTHROWS
' TVT-NODATA E-TV-NODATA TTHROWS
' TVT-BAD-SHAPE E-TV-SHAPE TTHROWS
' TVT-PLAN-IDX E-TV-PLAN-IDX TTHROWS
' TVT-OPKIND E-TV-OPKIND TTHROWS
' TVT-PLAN-DBL E-TV-PLAN-STATE TTHROWS
' TVT-IN-NB E-TV-PLAN-STATE TTHROWS
' TVT-OP-NB E-TV-PLAN-STATE TTHROWS
' TVT-STALE E-TV-HANDLE TTHROWS
' TVT-STALE-PLAN E-TV-HANDLE TTHROWS
' TVT-FULL-TV E-TV-FULL TTHROWS
' TVT-FULL-PLAN E-TV-PLAN-FULL TTHROWS

\ Public descriptor argument roles are statically non-interchangeable.
s" TVT-NEG-ROWS-COLS ( CAD-KIND:cols CAD-KIND:rows CAD-KIND:dtype CAD-KIND:layout CAD-KIND:address-space -- tensor ) TENSOR:TV-DESC" CHECK-QUIET-CANDIDATE! 0 T=
s" TVT-NEG-DTYPE-LAYOUT ( CAD-KIND:rows CAD-KIND:cols CAD-KIND:layout CAD-KIND:dtype CAD-KIND:address-space -- tensor ) TENSOR:TV-DESC" CHECK-QUIET-CANDIDATE! 0 T=
s" TVT-NEG-LAYOUT-SPACE ( CAD-KIND:rows CAD-KIND:cols CAD-KIND:dtype CAD-KIND:address-space CAD-KIND:layout -- tensor ) TENSOR:TV-DESC" CHECK-QUIET-CANDIDATE! 0 T=
s" TVT-NEG-HOST-SPACE ( ptr a CAD-KIND:rows CAD-KIND:cols CAD-KIND:dtype CAD-KIND:layout CAD-KIND:address-space -- tensor ) TENSOR:TV-NEW-HOST" CHECK-QUIET-CANDIDATE! 0 T=
s" TVT-NEG-RAW-HANDLE ( n -- tensor )" CHECK-QUIET-CANDIDATE! 0 T=

;package

package TENSOR
private

: TVT-FORGED-IDX ( -- )
   TV-RESET
   1 1 MAKI:SHAPE MAKI:DT-F32 MAKI:LAY-ROW MAKI:SPACE-GLOBAL TV-DESC drop
   TV-GEN @ TV-CAP * TV-U @ + RAW>TENSOR TV-ROWS@ drop ;

: TVT-FORGED-GEN ( -- )
   TV-RESET
   1 1 MAKI:SHAPE MAKI:DT-F32 MAKI:LAY-ROW MAKI:SPACE-GLOBAL TV-DESC drop
   TV-GEN @ 1+ TV-CAP * RAW>TENSOR TV-ROWS@ drop ;

' TVT-FORGED-IDX E-TV-HANDLE TTHROWS
' TVT-FORGED-GEN E-TV-HANDLE TTHROWS
TV-GEN-MAX TV-GEN !
' TV-RESET E-TV-GEN TTHROWS
0 TV-GEN ! 0 TV-U !

;package

package MAKI

T-REPORT

;package
