#!/usr/bin/env sbcl --script
;;; Test 10-arg calls using stack-passed extras with rest and optional
(load "sbcl-habu-shim.lisp")
(load "arm64/codegen-sbcl.lisp")

(defun write-bytecode-to-file (code-list filename)
  (with-open-file (out filename :direction :output :if-exists :supersede :if-does-not-exist :create :element-type '(unsigned-byte 8))
    (dolist (byte code-list)
      (write-byte byte out))))

(defun parse-result (output)
  (let* ((lines (loop for i = 0 then (1+ j)
                      as j = (position #\Newline output :start i)
                      collect (subseq output i j)
                      while j))
         (line (find "Untagged fixnum:" lines :test (lambda (x y) (search x y)))))
    (when line
      (parse-integer line :start (+ 17 (search "Untagged fixnum:" line)) :junk-allowed t))))

(defun run-case (forms expected)
  (let* ((code (habu-sbcl-codegen:compile-program-with-functions forms))
         (file "/tmp/test-10-args.bin"))
    (write-bytecode-to-file code file)
    (let* ((output (with-output-to-string (s)
                     (sb-ext:run-program "./run-bytecode" (list file) :output s :search t)))
           (result (parse-result output)))
      (format t "Forms: ~S~%" forms)
      (format t "Output: ~A~%" output)
      (and result (= result expected)))))

(let* ((cases '(((defun sum10 (a b c d e f g h i j)
                   (+ (+ (+ a b) (+ c d)) (+ (+ e f) (+ g (+ h (+ i j))))))
                 (sum10 1 2 3 4 5 6 7 8 9 10))
                ((defun pick10 (a b c d e f g h i j) j)
                 (pick10 0 0 0 0 0 0 0 0 0 42))
                ((defun rest10 (a b c d e f g h i j &rest r)
                   (if (= r 0) 0 (cdr r)))
                 (rest10 1 2 3 4 5 6 7 8 9 10))
                ((defun opt10 (a b c d e f g h i &optional (j 99 supplied)) (if supplied j 0))
                 (opt10 1 2 3 4 5 6 7 8 9))
                ((defun opt10 (a b c d e f g h i &optional (j 99 supplied)) (if supplied j 0))
                 (opt10 1 2 3 4 5 6 7 8 9 55))
                ((defun pick12 (a b c d e f g h i j k l) (+ k l))
                 (pick12 1 2 3 4 5 6 7 8 9 10 11 12))
                ((defun rest-many (a b c &rest r) (car (cdr (cdr r))))
                 (rest-many 1 2 3 4 5 6 7 8 9 10 11 12))
                ((defun opt12 (a b c d e f g h i j k &optional (l 99 supplied)) (if supplied l k))
                 (opt12 1 2 3 4 5 6 7 8 9 10 11))
                ((defun opt12 (a b c d e f g h i j k &optional (l 99 supplied)) (if supplied l k))
                 (opt12 1 2 3 4 5 6 7 8 9 10 11 123))))
      (expecteds '(55 42 0 0 55 23 6 11 123))
      (passed 0)
      (total 0))
  (loop for forms in cases
        for expected in expecteds do
          (incf total)
          (when (run-case forms expected)
            (incf passed)))
  (format t "Passed ~A/~A~%" passed total)
  (sb-ext:quit :unix-status (if (= passed total) 0 1)))
