#!/usr/bin/env sbcl --script
;;; Stage 1 Bootstrap Test - Part B
;;;
;;; Test more complex compiler patterns from habu-arm64-codegen-clean.lisp

(load "run-habu.lisp")

(format t "~%=== STAGE 1 BOOTSTRAP TEST - Part B ===~%")
(format t "Testing more complex compiler patterns...~%~%")

;; Test 1: Deeply nested let with ARM64 encoding
(format t "Test 1: Nested let pattern (arm64-sub)~%")
(let ((result (habu-sbcl:compile-and-run-forms
               '((defun my-mod (n d)
                   (- n (* d (/ n d))))
                 (defun word-to-bytes (w)
                   (list (my-mod w #x100)
                         (my-mod (/ w #x100) #x100)
                         (my-mod (/ w #x10000) #x100)
                         (my-mod (/ w #x1000000) #x100)))
                 (defun encode-word (w)
                   (word-to-bytes w))
                 (defun arm64-sub (rd rn rm)
                   (let ((base #xCB000000))
                     (let ((shifted-rm (* rm #x10000)))
                       (let ((shifted-rn (* rn #x20)))
                         (let ((encoded (+ base (+ shifted-rm (+ shifted-rn rd)))))
                           (encode-word encoded))))))
                 (length (arm64-sub #x0 #x1 #x2))))))
  (format t "  Result: ~A (expected 4)~%" result)
  (unless (= result #x4)
    (format t "  *** FAILED~%")
    (sb-ext:quit :unix-status 1)))

;; Test 2: load-address-to-reg pattern (multiple instructions)
(format t "~%Test 2: load-address-to-reg pattern~%")
(let ((result (habu-sbcl:compile-and-run-forms
               '((defun my-mod (n d)
                   (- n (* d (/ n d))))
                 (defun word-to-bytes (w)
                   (list (my-mod w #x100)
                         (my-mod (/ w #x100) #x100)
                         (my-mod (/ w #x10000) #x100)
                         (my-mod (/ w #x1000000) #x100)))
                 (defun encode-word (w)
                   (word-to-bytes w))
                 (defun arm64-movz (rd imm)
                   (let ((base #xD2800000))
                     (let ((shifted-imm (* imm #x20)))
                       (let ((encoded (+ base (+ shifted-imm rd))))
                         (encode-word encoded)))))
                 (defun arm64-movk (rd imm shift)
                   (let ((base #xF2800000))
                     (let ((shifted-shift (* shift #x200000)))
                       (let ((shifted-imm (* imm #x20)))
                         (let ((encoded (+ base (+ shifted-shift (+ shifted-imm rd)))))
                           (encode-word encoded))))))
                 (defun load-address-to-reg (rd addr)
                   (let ((low (my-mod addr #x10000)))
                     (let ((high (/ addr #x10000)))
                       (append (arm64-movz rd low)
                               (arm64-movk rd high #x1)))))
                 (length (load-address-to-reg #x0 #x12345678))))))
  (format t "  Result: ~A (expected 8)~%" result)  ; 2 instructions * 4 bytes
  (unless (= result #x8)
    (format t "  *** FAILED~%")
    (sb-ext:quit :unix-status 1)))

;; Test 3: Recursive codegen pattern (simplified)
(format t "~%Test 3: Recursive codegen pattern~%")
(let ((result (habu-sbcl:compile-and-run-forms
               '((defun has-tag? (ir tag)
                   (and (consp ir) (eq (car ir) tag)))
                 (defun my-mod (n d)
                   (- n (* d (/ n d))))
                 (defun word-to-bytes (w)
                   (list (my-mod w #x100)
                         (my-mod (/ w #x100) #x100)
                         (my-mod (/ w #x10000) #x100)
                         (my-mod (/ w #x1000000) #x100)))
                 (defun encode-word (w)
                   (word-to-bytes w))
                 (defun arm64-movz (rd imm)
                   (let ((base #xD2800000))
                     (let ((shifted-imm (* imm #x20)))
                       (let ((encoded (+ base (+ shifted-imm rd))))
                         (encode-word encoded)))))
                 (defun arm64-add (rd rn rm)
                   (let ((base #x8B000000))
                     (let ((shifted-rm (* rm #x10000)))
                       (let ((shifted-rn (* rn #x20)))
                         (let ((encoded (+ base (+ shifted-rm (+ shifted-rn rd)))))
                           (encode-word encoded))))))
                 ;; Mini codegen for literals and add operations
                 (defun mini-codegen (ir)
                   (cond
                     ((has-tag? ir 'lit)
                      (let ((value (cadr ir)))
                        (let ((tagged (* value #x10)))
                          (arm64-movz #x0 tagged))))
                     ((has-tag? ir 'add)
                      (let ((left (cadr ir))
                            (right (caddr ir)))
                        (append (mini-codegen left)
                                (list #xE1 #x03 #x00 #xAA)  ; mov x1, x0
                                (mini-codegen right)
                                (arm64-add #x0 #x1 #x0))))
                     (t (list))))
                 ;; Generate code for (add (lit 5) (lit 3))
                 (length (mini-codegen (list 'add
                                             (list 'lit #x5)
                                             (list 'lit #x3))))))))
  (format t "  Result: ~A (expected 16)~%" result)  ; 4 instructions * 4 bytes
  (unless (= result #x10)
    (format t "  *** FAILED~%")
    (sb-ext:quit :unix-status 1)))

;; Test 4: Multiple function composition
(format t "~%Test 4: Multiple function composition~%")
(let ((result (habu-sbcl:compile-and-run-forms
               '((defun has-tag? (ir tag)
                   (and (consp ir) (eq (car ir) tag)))
                 (defun count-instrs (code)
                   (/ (length code) #x4))
                 (defun append-code (c1 c2)
                   (append c1 c2))
                 (defun my-mod (n d)
                   (- n (* d (/ n d))))
                 (defun word-to-bytes (w)
                   (list (my-mod w #x100)
                         (my-mod (/ w #x100) #x100)
                         (my-mod (/ w #x10000) #x100)
                         (my-mod (/ w #x1000000) #x100)))
                 (defun encode-word (w)
                   (word-to-bytes w))
                 (defun arm64-movz (rd imm)
                   (let ((base #xD2800000))
                     (let ((shifted-imm (* imm #x20)))
                       (let ((encoded (+ base (+ shifted-imm rd))))
                         (encode-word encoded)))))
                 ;; Generate code and count instructions
                 (let ((code1 (arm64-movz #x0 #x10))
                       (code2 (arm64-movz #x1 #x20)))
                   (count-instrs (append-code code1 code2)))))))
  (format t "  Result: ~A (expected 2)~%" result)
  (unless (= result #x2)
    (format t "  *** FAILED~%")
    (sb-ext:quit :unix-status 1)))

;; Test 5: Offset calculation pattern (like codegen-expr)
(format t "~%Test 5: Offset calculation pattern~%")
(let ((result (habu-sbcl:compile-and-run-forms
               '((defun count-instrs (code)
                   (/ (length code) #x4))
                 (defun my-mod (n d)
                   (- n (* d (/ n d))))
                 (defun word-to-bytes (w)
                   (list (my-mod w #x100)
                         (my-mod (/ w #x100) #x100)
                         (my-mod (/ w #x10000) #x100)
                         (my-mod (/ w #x1000000) #x100)))
                 (defun encode-word (w)
                   (word-to-bytes w))
                 (defun arm64-movz (rd imm)
                   (let ((base #xD2800000))
                     (let ((shifted-imm (* imm #x20)))
                       (let ((encoded (+ base (+ shifted-imm rd))))
                         (encode-word encoded)))))
                 ;; Simulate offset tracking during codegen
                 (defun gen-with-offset (current-offset)
                   (let ((code1 (arm64-movz #x0 #x10)))
                     (let ((new-offset (+ current-offset (count-instrs code1))))
                       (let ((code2 (arm64-movz #x1 new-offset)))
                         (+ (count-instrs code1) (count-instrs code2))))))
                 (gen-with-offset #x100)))))
  (format t "  Result: ~A (expected 2)~%" result)
  (unless (= result #x2)
    (format t "  *** FAILED~%")
    (sb-ext:quit :unix-status 1)))

;; Test 6: fn-offset-lookup pattern
(format t "~%Test 6: fn-offset-lookup pattern~%")
(let ((result (habu-sbcl:compile-and-run-forms
               '((defun fn-offset-lookup (fname fn-offsets)
                   (if (nil? fn-offsets)
                       nil
                       (if (eq (car (car fn-offsets)) fname)
                           (cdr (car fn-offsets))
                           (fn-offset-lookup fname (cdr fn-offsets)))))
                 (let ((offsets (list (cons 'foo #x100)
                                      (cons 'bar #x200)
                                      (cons 'baz #x300))))
                   (+ (fn-offset-lookup 'foo offsets)
                      (fn-offset-lookup 'bar offsets)
                      (fn-offset-lookup 'baz offsets)))))))
  (format t "  Result: ~A (expected 1536 = 0x600)~%" result)
  (unless (= result #x600)
    (format t "  *** FAILED~%")
    (sb-ext:quit :unix-status 1)))

;; Test 7: Complex cond with codegen
(format t "~%Test 7: Complex cond with codegen~%")
(let ((result (habu-sbcl:compile-and-run-forms
               '((defun has-tag? (ir tag)
                   (and (consp ir) (eq (car ir) tag)))
                 (defun my-mod (n d)
                   (- n (* d (/ n d))))
                 (defun word-to-bytes (w)
                   (list (my-mod w #x100)
                         (my-mod (/ w #x100) #x100)
                         (my-mod (/ w #x10000) #x100)
                         (my-mod (/ w #x1000000) #x100)))
                 (defun encode-word (w)
                   (word-to-bytes w))
                 (defun arm64-movz (rd imm)
                   (let ((base #xD2800000))
                     (let ((shifted-imm (* imm #x20)))
                       (let ((encoded (+ base (+ shifted-imm rd))))
                         (encode-word encoded)))))
                 (defun arm64-ldr (rt rn offset)
                   (let ((base #xF9400000))
                     (let ((shifted-offset (* (/ offset #x8) #x400)))
                       (let ((shifted-rn (* rn #x20)))
                         (let ((encoded (+ base (+ shifted-offset (+ shifted-rn rt)))))
                           (encode-word encoded))))))
                 ;; Codegen with multiple cases
                 (defun codegen-simple (ir)
                   (cond
                     ((has-tag? ir 'lit)
                      (arm64-movz #x0 (* (cadr ir) #x10)))
                     ((has-tag? ir 'var)
                      (arm64-ldr #x0 #x1f (* (cadr ir) #x10)))
                     (t (list))))
                 (+ (length (codegen-simple (list 'lit #x5)))
                    (length (codegen-simple (list 'var #x2))))))))
  (format t "  Result: ~A (expected 8)~%" result)
  (unless (= result #x8)
    (format t "  *** FAILED~%")
    (sb-ext:quit :unix-status 1)))

(format t "~%=== ALL STAGE 1B BOOTSTRAP TESTS PASSED ===~%")
(format t "~%Successfully tested:~%")
(format t "  - Deeply nested let expressions~%")
(format t "  - Multi-instruction generation~%")
(format t "  - Recursive codegen patterns~%")
(format t "  - Function composition~%")
(format t "  - Offset calculation~%")
(format t "  - Environment lookup~%")
(format t "  - Complex cond expressions~%")

(sb-ext:quit :unix-status 0)
