#!/usr/bin/env sbcl --script
;;; Test &rest parameter handling for functions, lambdas, and closures
(load "sbcl-habu-shim.lisp")
(load "arm64/codegen-sbcl.lisp")

(defun write-bytecode-to-file (code-list filename)
  (with-open-file (out filename :direction :output :if-exists :supersede :if-does-not-exist :create :element-type '(unsigned-byte 8))
    (dolist (byte code-list)
      (write-byte byte out))))

(defun parse-result (output)
  (let* ((lines (loop for i = 0 then (1+ j)
                      as j = (position #\Newline output :start i)
                      collect (subseq output i j)
                      while j))
         (line (find "Untagged fixnum:" lines :test (lambda (x y) (search x y)))))
    (when line
      (parse-integer line :start (+ 17 (search "Untagged fixnum:" line)) :junk-allowed t))))

(defun run-case (forms expected)
  (let* ((code (habu-sbcl-codegen:compile-program-with-functions forms))
         (file "/tmp/test-rest.bin"))
    (write-bytecode-to-file code file)
    (let* ((output (with-output-to-string (s)
                     (sb-ext:run-program "./run-bytecode" (list file) :output s :search t)))
           (result (parse-result output)))
      (format t "Forms: ~S~%" forms)
      (format t "Output: ~A~%" output)
      (and result (= result expected)))))

(let* ((cases '(((defun list-length (lst)
                   (if (= lst 0)
                       0
                       (+ 1 (list-length (cdr lst)))))
                 (defun count-all (&rest args)
                   (list-length args))
                 (count-all 5 6 7))
                ((defun list-length (lst)
                   (if (= lst 0)
                       0
                       (+ 1 (list-length (cdr lst)))))
                 (defun drop-first (x &rest rest)
                   (+ x (list-length rest)))
                 (drop-first 10 20 30))
                ((defun make-rest-closure (&rest xs)
                   (lambda () (car xs)))
                 (funcall (make-rest-closure 9 10)))
                (((lambda (&rest xs) (car xs)) 4 5))
                ((defun list-length (lst)
                   (if (= lst 0)
                       0
                       (+ 1 (list-length (cdr lst)))))
                 (defun empty-rest (&rest xs)
                   (list-length xs))
                 (empty-rest))))
       (expecteds '(3 12 9 4 0))
       (passed 0)
       (total 0))
  (loop for forms in cases
        for expected in expecteds do
          (incf total)
          (when (run-case forms expected)
            (incf passed)))
  (format t "Passed ~A/~A~%" passed total)
  (sb-ext:quit :unix-status (if (= passed total) 0 1)))
