#!/usr/bin/env sbcl --script
;;; Test &optional parameter defaults, supplied args, and interaction with &rest
(load "sbcl-habu-shim.lisp")
(load "arm64/codegen-sbcl.lisp")

(defun write-bytecode-to-file (code-list filename)
  (with-open-file (out filename :direction :output :if-exists :supersede :if-does-not-exist :create :element-type '(unsigned-byte 8))
    (dolist (byte code-list)
      (write-byte byte out))))

(defun parse-result (output)
  (let* ((lines (loop for i = 0 then (1+ j)
                      as j = (position #\Newline output :start i)
                      collect (subseq output i j)
                      while j))
         (line (find "Untagged fixnum:" lines :test (lambda (x y) (search x y)))))
    (when line
      (parse-integer line :start (+ 17 (search "Untagged fixnum:" line)) :junk-allowed t))))

(defun run-case (forms expected)
  (let* ((code (habu-sbcl-codegen:compile-program-with-functions forms))
         (file "/tmp/test-optional.bin"))
    (write-bytecode-to-file code file)
    (let* ((output (with-output-to-string (s)
                     (sb-ext:run-program "./run-bytecode" (list file) :output s :search t)))
           (result (parse-result output)))
      (format t "Forms: ~S~%" forms)
      (format t "Output: ~A~%" output)
      (and result (= result expected)))))

(let* ((cases '(((defun opt-default (&optional x) x)
                 (opt-default))
                ((defun opt-supplied (&optional x) x)
                 (opt-supplied 7))
                ((defun opt-flag (&optional (x 5 supplied)) (if supplied x 0))
                 (opt-flag))
                ((defun opt-flag (&optional (x 5 supplied)) (if supplied x 0))
                 (opt-flag 9))
                ((defun opt-with-default (a &optional (b (+ a 1))) (+ a b))
                 (opt-with-default 5))
                ((defun opt-with-default (a &optional (b (+ a 1))) (+ a b))
                 (opt-with-default 5 20))
                ((defun list-length (lst)
                   (if (= lst 0)
                       0
                       (+ 1 (list-length (cdr lst)))))
                 (defun opt-rest (a &optional b &rest r)
                   (+ a (+ (if b b 0) (list-length r))))
                 (opt-rest 10 20 30))))
       (expecteds '(0 7 0 9 11 25 31))
       (passed 0)
       (total 0))
  (loop for forms in cases
        for expected in expecteds do
          (incf total)
          (when (run-case forms expected)
            (incf passed)))
  (format t "Passed ~A/~A~%" passed total)
  (sb-ext:quit :unix-status (if (= passed total) 0 1)))
