#!/usr/bin/env sbcl --script
;;; test_closure_integration.lisp - closure integration smoke
(load "sbcl-habu-shim.lisp")
(load "arm64/codegen-sbcl.lisp")

(defun write-bytecode-to-file (code-list filename)
  (with-open-file (out filename :direction :output :if-exists :supersede :if-does-not-exist :create :element-type '(unsigned-byte 8))
    (dolist (byte code-list)
      (write-byte byte out))))

(defun parse-result (output)
  (let* ((lines (loop for i = 0 then (1+ j)
                      as j = (position #\Newline output :start i)
                      collect (subseq output i j)
                      while j))
         (line (find "Untagged fixnum:" lines :test (lambda (x y) (search x y)))))
    (when line
      (parse-integer line :start (+ 17 (search "Untagged fixnum:" line)) :junk-allowed t))))

(defun run-case (forms expected)
  (let* ((code (habu-sbcl-codegen:compile-program-with-functions forms))
         (file "/tmp/test-closure.bin"))
    (write-bytecode-to-file code file)
    (let* ((output (with-output-to-string (s)
                     (sb-ext:run-program "./run-bytecode" (list file) :output s :search t)))
           (result (parse-result output)))
      (format t "Forms: ~S~%" forms)
      (format t "Output: ~A~%" output)
      (and result (= result expected)))))

(let* ((cases '(((defun make-adder (n) (lambda (y) (+ n y)))
                 (funcall (make-adder 7) 8))
                ((defun outer (x) (lambda (y) (lambda (z) (+ x (+ y z)))))
                 (funcall (funcall (outer 1) 2) 3))
                ((defun make-counter (n)
                   (lambda (k)
                     (if (= k 0) n (funcall (make-counter (+ n 1)) (- k 1)))))
                 (funcall (make-counter 5) 3))
                ((defun make-sum (a b c)
                   (lambda (x y) (+ a (+ b (+ c (+ x y))))))
                 (funcall (make-sum 1 2 3) 4 5))
                ((defun make-counter (n)
                   (lambda (k)
                     (if (= k 0) n (funcall (make-counter (+ n 1)) (- k 1)))))
                 (funcall (make-counter 5) 10))))
       (expecteds '(15 6 8 15 15))
       (passed 0)
       (total 0))
  (loop for forms in cases
        for expected in expecteds do
          (incf total)
          (when (run-case forms expected)
            (incf passed)))
  (format t "Passed ~A/~A~%" passed total)
  (sb-ext:quit :unix-status (if (= passed total) 0 1)))
