\ aot-chain-bake.f - bake ONE named chain artifact into an engine.
\
\ The production build captures its own artifact and bakes it (tools/build-fixpoint.f
\ BF-BUILD-STDIN-FROM-STAGE), so this tool is not how bin/hb is made. It exists for
\ the case the build cannot serve: baking an artifact somebody else captured, keyed
\ to the engine that captured it, without a capture of its own. That is what the
\ acceptance suite needs - it captures in bin/hb, edits the bytes, and asks what the
\ real bake does with them.
\
\ Everything below the argument handling is the production path: the driver is
\ generated by BUILD-FIXPOINT (which owns the build's path construction) and the
\ engine is emitted by the same BF-EMIT-ENGINE the build calls twice.
\
\ Run:  bin/hb --load tools/aot-chain-bake.f -- <artifact> <producer-engine>
\ Leaves <HB_TMP>/hb-chain and prints `aot-chain-bake: hb-chain ready`.

require lib/errors.f
require lib/string.f
require lib/memory.f
require lib/fs.f
require lib/fs-mutate.f
require lib/vector.f
require lib/fmt.f
require lib/process.f
require lib/process-argv.f
require lib/process-env.f
require lib/process-fork.f
require lib/source.f
require lib/build.f
require lib/codesign.f
require lib/content-key.f
require lib/date.f
require tools/build-fixpoint.f

package CHAIN-BAKE
using BUILD-FIXPOINT

create ART-BUF FS-PATH-CAP allot   variable ART-U
create ENG-BUF FS-PATH-CAP allot   variable ENG-U

: ?ARGS ( -- )
   SCRIPT-ARGC 2 >= if exit then
   s" aot-chain-bake: usage: --load tools/aot-chain-bake.f -- <artifact> <producer-engine>"
   BF-BUILD-RC die ;

: PATH-COPY ( ptr u8 n ptr u8 -- ) {: a:ptr u:n d:ptr :}
   u FS-PATH-CAP > if s" aot-chain-bake: path exceeds the buffer" BF-BUILD-RC die then
   a d u BYTE-COPY ;

: ARGS! ( -- )
   ?ARGS
   0 SCRIPT-ARGV$ dup ART-U !  ART-BUF PATH-COPY
   1 SCRIPT-ARGV$ dup ENG-U !  ENG-BUF PATH-COPY ;

: ART$ ( -- ptr u8 n ) ART-BUF ART-U @ ;
: ENG$ ( -- ptr u8 n ) ENG-BUF ENG-U @ ;

\ Keep the engine under a name of its own: the build's own product is hb-stdin and
\ an install would take it, which is not what a one-artifact bake is for.
: KEEP ( -- )
   s" hb-stdin" s" hb-chain" BF-RENAME-TMP
   s" hb-chain" BF-CHMOD-X-TMP
   s" hb-chain" BF-CODESIGN-VERIFY-TMP ;

: RUN ( -- )
   ARGS!
   BF-STAGE-FIXPOINT
   ART$ ENG$ BF-CHAIN-DRIVER-FROM
   BF-CHAIN-DRIVER$ BF-EMIT-ENGINE
   KEEP
   s" aot-chain-bake: hb-chain ready" type cr ;

\ Fail-closed CLI boundary, the same one BUILD-FIXPOINT's own entry has: an escaped
\ throw exits with the raw code masked to 8 bits and NO diagnostic, so a code that
\ is a multiple of 256 exits 0 and a failed bake reads as a successful one. Name it
\ and die with the build rc instead.
: FAIL ( n -- ) {: rc:n :}
   s" aot-chain-bake: failed: uncaught throw code " type rc . cr
   s" aot-chain-bake: no engine was written" BF-BUILD-RC die ;

public

: BUILD ( -- )
   [: RUN ;] catch {: rc:n :}
   rc 0 <> if rc FAIL then ;

;using
;package

CHAIN-BAKE:BUILD
