\ class-generate.f - deterministic Unicode character-class source generator.

require lib/prelude.f
require lib/memory.f
require lib/fs.f
require lib/fs-mutate.f
require lib/codegen.f
require tools/unicode/class-parse.f

package UNICODE-CLASS-TOOL

private

131072 CODEGEN:BUFFER OUTPUT
10 constant OUTPUT-LINE-FEED
64 constant SHA256-HEX-LENGTH
create INPUT-DIGEST SHA256-HEX-LENGTH allot
create OUTPUT-LOCK SHA256-HEX-LENGTH 1+ allot

: UNICODE-PATH$ ( -- ptr u8 n )
   s" data/unicode/16.0.0/UnicodeData.txt" ;

: PROPERTIES-PATH$ ( -- ptr u8 n )
   s" data/unicode/16.0.0/PropList.txt" ;

: OUTPUT-PATH$ ( -- ptr u8 n )
   s" lib/unicode/class-data.f" ;

: OUTPUT-LOCK-PATH$ ( -- ptr u8 n )
   s" data/unicode/16.0.0/class-data.sha256" ;

: EXPECTED-UNICODE-DIGEST$ ( -- ptr u8 n )
   s" ff58e5823bd095166564a006e47d111130813dcf8bf234ef79fa51a870edb48f" ;

: EXPECTED-PROPERTIES-DIGEST$ ( -- ptr u8 n )
   s" 53d614508e2a0b2305a8aa21cd60d993de9326cdf65993660dfcce4503548583" ;

: VERIFY-FILE-DIGEST ( ptr u8 n ptr u8 n -- ) {: path:ptr pathu:n want:ptr wantu:n :}
   wantu SHA256-HEX-LENGTH <> if E-DIGEST throw then
   path pathu INPUT-DIGEST SHA256-FILE-HEX 0 <> if E-DIGEST throw then
   INPUT-DIGEST SHA256-HEX-LENGTH want wantu STR= 0= if E-DIGEST throw then ;

: CHECK-INPUT-DIGESTS ( -- )
   UNICODE-PATH$ EXPECTED-UNICODE-DIGEST$ VERIFY-FILE-DIGEST
   PROPERTIES-PATH$ EXPECTED-PROPERTIES-DIGEST$ VERIFY-FILE-DIGEST ;

: LOAD-UNICODE-FILE ( -- )
   UNICODE-PATH$ 2dup FILE-SIZE 1+ MEM-ALLOC-64K-SPAN {: path:ptr pathu:n buf:ptr cap:n :}
   path pathu buf cap READ-ALL {: got:n :}
   buf got PARSE-UNICODE ;

: LOAD-PROPERTIES-FILE ( -- )
   PROPERTIES-PATH$ 2dup FILE-SIZE 1+ MEM-ALLOC-64K-SPAN {: path:ptr pathu:n buf:ptr cap:n :}
   path pathu buf cap READ-ALL {: got:n :}
   buf got PARSE-PROPERTIES ;

: OUT$ ( ptr u8 n -- )
   OUTPUT CODEGEN:APPEND-STRING ;

: OUT-N ( n -- )
   OUTPUT CODEGEN:APPEND-DECIMAL ;

: OUT-LINE ( ptr u8 n -- )
   OUT$
   OUTPUT-LINE-FEED OUTPUT CODEGEN:APPEND-BYTE ;

: OUT-RANGE ( n n -- ) {: lo:n hi:n :}
   s"    " OUT$
   lo OUT-N
   s"  , " OUT$
   hi OUT-N
   s"  ," OUT-LINE ;

\ typed-local-lint: allow-bare-local - getter preserves the range-accessor quotation effect.
: OUT-RANGES ( n [ n -- n n ] -- ) {: count:n getter :}
   0 begin dup count < while
      dup getter execute OUT-RANGE
      1+
   repeat drop ;

\ typed-local-lint: allow-bare-local - getter preserves the range-accessor quotation effect.
: OUT-TABLE ( ptr u8 n n [ n -- n n ] -- )
   {: name:ptr nameu:n count:n getter :}
   s" create " OUT$ name nameu OUT$ s" -RANGES" OUT-LINE
   count getter OUT-RANGES
   count OUT-N s"  constant " OUT$ name nameu OUT$ s" -TABLE-COUNT" OUT-LINE
   s" " OUT-LINE ;

: OUT-PREAMBLE ( -- )
   s" \ class-data.f - generated complete Unicode 16.0.0 class ranges." OUT-LINE
   s" \ Generated by tools/unicode/class-generate.f; do not edit." OUT-LINE
   s" " OUT-LINE
   s" require lib/prelude.f" OUT-LINE
   s" " OUT-LINE
   s" package UNICODE-CLASS-DATA" OUT-LINE
   s" " OUT-LINE
   s" public" OUT-LINE
   s" " OUT-LINE
   s" -7804 constant E-INDEX" OUT-LINE
   s" " OUT-LINE
   s" private" OUT-LINE
   s" " OUT-LINE ;

: OUT-METADATA ( -- )
   s" public" OUT-LINE
   s" " OUT-LINE
   s" : VERSION$ ( -- ptr u8 n )" OUT-LINE
   s"    s" OUT$ 34 OUTPUT CODEGEN:APPEND-BYTE s"  16.0.0" OUT$ 34 OUTPUT CODEGEN:APPEND-BYTE s"  ;" OUT-LINE
   s" " OUT-LINE
   s" : UNICODE-DATA-SHA256$ ( -- ptr u8 n )" OUT-LINE
   s"    s" OUT$ 34 OUTPUT CODEGEN:APPEND-BYTE s"  ff58e5823bd095166564a006e47d111130813dcf8bf234ef79fa51a870edb48f" OUT$ 34 OUTPUT CODEGEN:APPEND-BYTE s"  ;" OUT-LINE
   s" " OUT-LINE
   s" : PROP-LIST-SHA256$ ( -- ptr u8 n )" OUT-LINE
   s"    s" OUT$ 34 OUTPUT CODEGEN:APPEND-BYTE s"  53d614508e2a0b2305a8aa21cd60d993de9326cdf65993660dfcce4503548583" OUT$ 34 OUTPUT CODEGEN:APPEND-BYTE s"  ;" OUT-LINE
   s" " OUT-LINE ;

: OUT-ACCESSOR ( ptr u8 n -- ) {: name:ptr nameu:n :}
   s" : " OUT$ name nameu OUT$ s" -RANGE-COUNT ( -- n )" OUT-LINE
   s"    " OUT$ name nameu OUT$ s" -TABLE-COUNT ;" OUT-LINE
   s" " OUT-LINE
   s" : " OUT$ name nameu OUT$ s" -RANGE@ ( n -- n n )" OUT-LINE
   s"    dup 0 < over " OUT$ name nameu OUT$ s" -TABLE-COUNT >= or if E-INDEX throw then" OUT-LINE
   s"    2 * cells " OUT$ name nameu OUT$ s" -RANGES + dup @ swap cell+ @ ;" OUT-LINE
   s" " OUT-LINE ;

: OUT-ACCESSORS ( -- )
   s" LETTER" OUT-ACCESSOR
   s" NUMBER" OUT-ACCESSOR
   s" WHITE-SPACE" OUT-ACCESSOR
   s" ;package" OUT-LINE ;

: WRITE-OUTPUT-LOCK ( -- )
   OUTPUT-PATH$ OUTPUT-LOCK SHA256-FILE-HEX 0 <> if E-DIGEST throw then
   OUTPUT-LINE-FEED OUTPUT-LOCK SHA256-HEX-LENGTH + c!
   OUTPUT-LOCK-PATH$ OUTPUT-LOCK SHA256-HEX-LENGTH 1+ ATOMIC-WRITE-FILE ;

public

: CHECK-FILE-DIGEST ( ptr u8 n ptr u8 n -- )
   VERIFY-FILE-DIGEST ;

: LOAD-PINNED ( -- )
   CHECK-INPUT-DIGESTS
   RESET
   LOAD-UNICODE-FILE
   LOAD-PROPERTIES-FILE
   READY? 0= if E-STATE throw then ;

: RENDER ( -- ptr u8 n )
   READY? 0= if E-STATE throw then
   OUTPUT CODEGEN:RESET
   OUT-PREAMBLE
   s" LETTER" LETTER-COUNT [: LETTER-RANGE@ ;] OUT-TABLE
   s" NUMBER" NUMBER-COUNT [: NUMBER-RANGE@ ;] OUT-TABLE
   s" WHITE-SPACE" SPACE-COUNT [: SPACE-RANGE@ ;] OUT-TABLE
   OUT-METADATA
   OUT-ACCESSORS
   OUTPUT CODEGEN:CONTENTS ;

: WRITE-PINNED ( -- )
   LOAD-PINNED
   OUTPUT-PATH$ RENDER ATOMIC-WRITE-FILE
   WRITE-OUTPUT-LOCK ;

;package
