\ class-tool-test.f - parser transaction and generator tests.
\ Run: bin/hb --load tools/unicode/class-tool-test.f

require lib/test.f
require lib/codegen.f
require tools/unicode/class-generate.f

package UNICODE-CLASS-TOOL-TEST

private

65536 CODEGEN:BUFFER CAPACITY-SOURCE
10 constant LINE-FEED

: ORDERED-UNICODE$ ( -- ptr u8 n )
   S\" 0030;DIGIT ZERO;Nd;0;EN;;;;;N;;;;;\n0041;LATIN CAPITAL LETTER A;Lu;0;L;;;;;N;;;;;\n0042;LATIN CAPITAL LETTER B;Lu;0;L;;;;;N;;;;;" ;

: GOOD-PROPS$ ( -- ptr u8 n )
   S\" 0009..000D ; White_Space # controls\n0020 ; White_Space # space\n002D ; Dash" ;

: BAD-LAST$ ( -- ptr u8 n )
   S\" 3400;<CJK Ideograph Extension A, First>;Lo;0;L;;;;;N;;;;;\n4DBF;<wrong, Last>;Lo;0;L;;;;;N;;;;;" ;

: MISSING-LAST$ ( -- ptr u8 n )
   s" 3400;<CJK Ideograph Extension A, First>;Lo;0;L;;;;;N;;;;;" ;

: BAD-FIELDS$ ( -- ptr u8 n )
   s" 0041;X;Lu;" ;

: BAD-HEX$ ( -- ptr u8 n )
   s" 00G1;X;Lu;0;L;;;;;N;;;;;" ;

: HIGH-SCALAR$ ( -- ptr u8 n )
   s" 110000;X;Lu;0;L;;;;;N;;;;;" ;

: SURROGATE-FIRST$ ( -- ptr u8 n )
   s" D800;X;Lo;0;L;;;;;N;;;;;" ;

: SURROGATE-MIDDLE$ ( -- ptr u8 n )
   s" D900;X;Lo;0;L;;;;;N;;;;;" ;

: SURROGATE-LAST$ ( -- ptr u8 n )
   s" DFFF;X;Lo;0;L;;;;;N;;;;;" ;

: ORPHAN-LAST$ ( -- ptr u8 n )
   s" 4DBF;<CJK Ideograph Extension A, Last>;Lo;0;L;;;;;N;;;;;" ;

: CATEGORY-MISMATCH$ ( -- ptr u8 n )
   S\" 3400;<CJK Ideograph Extension A, First>;Lo;0;L;;;;;N;;;;;\n4DBF;<CJK Ideograph Extension A, Last>;Nd;0;L;;;;;N;;;;;" ;

: BAD-CATEGORY$ ( -- ptr u8 n )
   s" 0041;X;Xx;0;L;;;;;N;;;;;" ;

: BAD-ORDER$ ( -- ptr u8 n )
   S\" 0042;B;Lu;0;L;;;;;N;;;;;\n0041;A;Lu;0;L;;;;;N;;;;;" ;

: OVERLAP$ ( -- ptr u8 n )
   S\" 3400;<CJK Ideograph Extension A, First>;Lo;0;L;;;;;N;;;;;\n4DBF;<CJK Ideograph Extension A, Last>;Lo;0;L;;;;;N;;;;;\n4DBF;DUPLICATE;Lo;0;L;;;;;N;;;;;" ;

: BAD-PROP-RANGE$ ( -- ptr u8 n )
   s" 0020..0010 ; White_Space" ;

: BAD-PROP-DOTS$ ( -- ptr u8 n )
   s" 0020.0021 ; White_Space" ;

: SURROGATE-PROP$ ( -- ptr u8 n )
   s" D800..DFFF ; White_Space" ;

: BAD-OTHER-PROP$ ( -- ptr u8 n )
   s" GGGG ; Dash" ;

: ADJACENT-PROPS$ ( -- ptr u8 n )
   S\" 0009..000D ; White_Space\n000E ; White_Space" ;

: OVERLAP-PROPS$ ( -- ptr u8 n )
   S\" 0009..000D ; White_Space\n000D ; White_Space" ;

: UNSORTED-PROPS$ ( -- ptr u8 n )
   S\" 0020 ; White_Space\n0009 ; White_Space" ;

: BAD-LAST ( -- )
   BAD-LAST$ UNICODE-CLASS-TOOL:PARSE-UNICODE ;

: MISSING-LAST ( -- )
   MISSING-LAST$ UNICODE-CLASS-TOOL:PARSE-UNICODE ;

: BAD-FIELDS ( -- )
   BAD-FIELDS$ UNICODE-CLASS-TOOL:PARSE-UNICODE ;

: BAD-HEX ( -- )
   BAD-HEX$ UNICODE-CLASS-TOOL:PARSE-UNICODE ;

: HIGH-SCALAR ( -- )
   HIGH-SCALAR$ UNICODE-CLASS-TOOL:PARSE-UNICODE ;

: SURROGATE-FIRST ( -- )
   SURROGATE-FIRST$ UNICODE-CLASS-TOOL:PARSE-UNICODE ;

: SURROGATE-MIDDLE ( -- )
   SURROGATE-MIDDLE$ UNICODE-CLASS-TOOL:PARSE-UNICODE ;

: SURROGATE-LAST ( -- )
   SURROGATE-LAST$ UNICODE-CLASS-TOOL:PARSE-UNICODE ;

: ORPHAN-LAST ( -- )
   ORPHAN-LAST$ UNICODE-CLASS-TOOL:PARSE-UNICODE ;

: CATEGORY-MISMATCH ( -- )
   CATEGORY-MISMATCH$ UNICODE-CLASS-TOOL:PARSE-UNICODE ;

: BAD-CATEGORY ( -- )
   BAD-CATEGORY$ UNICODE-CLASS-TOOL:PARSE-UNICODE ;

: BAD-ORDER ( -- )
   BAD-ORDER$ UNICODE-CLASS-TOOL:PARSE-UNICODE ;

: OVERLAP ( -- )
   OVERLAP$ UNICODE-CLASS-TOOL:PARSE-UNICODE ;

: BAD-PROP-RANGE ( -- )
   BAD-PROP-RANGE$ UNICODE-CLASS-TOOL:PARSE-PROPERTIES ;

: BAD-PROP-DOTS ( -- )
   BAD-PROP-DOTS$ UNICODE-CLASS-TOOL:PARSE-PROPERTIES ;

: SURROGATE-PROP ( -- )
   SURROGATE-PROP$ UNICODE-CLASS-TOOL:PARSE-PROPERTIES ;

: BAD-OTHER-PROP ( -- )
   BAD-OTHER-PROP$ UNICODE-CLASS-TOOL:PARSE-PROPERTIES ;

: OVERLAP-PROPS ( -- )
   OVERLAP-PROPS$ UNICODE-CLASS-TOOL:PARSE-PROPERTIES ;

: UNSORTED-PROPS ( -- )
   UNSORTED-PROPS$ UNICODE-CLASS-TOOL:PARSE-PROPERTIES ;

: APPEND-CAPACITY-ROW ( n ptr u8 n -- ) {: cp:n category:ptr categoryu:n :}
   cp CAPACITY-SOURCE CODEGEN:APPEND-DECIMAL
   s" ;X;" CAPACITY-SOURCE CODEGEN:APPEND-STRING
   category categoryu CAPACITY-SOURCE CODEGEN:APPEND-STRING
   s" ;0;L;;;;;N;;;;;" CAPACITY-SOURCE CODEGEN:APPEND-STRING
   LINE-FEED CAPACITY-SOURCE CODEGEN:APPEND-BYTE ;

: BUILD-CAPACITY-SOURCE ( n -- ptr u8 n ) {: rows:n :}
   CAPACITY-SOURCE CODEGEN:RESET
   0 begin dup rows < while
      dup 2 * s" Lu" APPEND-CAPACITY-ROW
      dup 2 * 1+ s" Mn" APPEND-CAPACITY-ROW
      1+
   repeat drop
   CAPACITY-SOURCE CODEGEN:CONTENTS ;

: OVER-CAPACITY ( -- )
   1025 BUILD-CAPACITY-SOURCE UNICODE-CLASS-TOOL:PARSE-UNICODE ;

: AT-CAPACITY ( -- )
   1024 BUILD-CAPACITY-SOURCE UNICODE-CLASS-TOOL:PARSE-UNICODE ;

: PARSER-RANGE-LOW ( -- )
   -1 UNICODE-CLASS-TOOL:LETTER-RANGE@ 2drop ;

: PARSER-RANGE-HIGH ( -- )
   UNICODE-CLASS-TOOL:LETTER-COUNT UNICODE-CLASS-TOOL:LETTER-RANGE@ 2drop ;

: BAD-DIGEST ( -- )
   s" data/unicode/16.0.0/UnicodeData.txt"
   s" 0000000000000000000000000000000000000000000000000000000000000000"
   UNICODE-CLASS-TOOL:CHECK-FILE-DIGEST ;

: RENDER-WITHOUT-INPUT ( -- )
   UNICODE-CLASS-TOOL:RESET
   UNICODE-CLASS-TOOL:RENDER 2drop ;

: SEED ( -- )
   ORDERED-UNICODE$ UNICODE-CLASS-TOOL:PARSE-UNICODE
   GOOD-PROPS$ UNICODE-CLASS-TOOL:PARSE-PROPERTIES ;

: ASSERT-UNICODE-SEED ( -- )
   UNICODE-CLASS-TOOL:LETTER-COUNT 1 T=
   UNICODE-CLASS-TOOL:NUMBER-COUNT 1 T=
   0 UNICODE-CLASS-TOOL:LETTER-RANGE@ 66 T= 65 T=
   0 UNICODE-CLASS-TOOL:NUMBER-RANGE@ 48 T= 48 T= ;

: ASSERT-SPACE-SEED ( -- )
   UNICODE-CLASS-TOOL:SPACE-COUNT 2 T=
   0 UNICODE-CLASS-TOOL:SPACE-RANGE@ 13 T= 9 T=
   1 UNICODE-CLASS-TOOL:SPACE-RANGE@ 32 T= 32 T= ;

: CHECK-UNICODE-ROLLBACK ( [ -- ] n -- )
   TTHROWSQ
   ASSERT-UNICODE-SEED ;

: CHECK-SPACE-ROLLBACK ( [ -- ] n -- )
   TTHROWSQ
   ASSERT-SPACE-SEED ;

: TEST-TRANSACTION ( -- )
   UNICODE-CLASS-TOOL:RESET
   UNICODE-CLASS-TOOL:READY? TFALSE
   SEED
   UNICODE-CLASS-TOOL:READY? TTRUE
   ASSERT-UNICODE-SEED
   ASSERT-SPACE-SEED

   [: BAD-FIELDS ;] UNICODE-CLASS-TOOL:E-SYNTAX CHECK-UNICODE-ROLLBACK
   [: BAD-HEX ;] UNICODE-CLASS-TOOL:E-SYNTAX CHECK-UNICODE-ROLLBACK
   [: BAD-CATEGORY ;] UNICODE-CLASS-TOOL:E-SYNTAX CHECK-UNICODE-ROLLBACK
   [: BAD-LAST ;] UNICODE-CLASS-TOOL:E-SYNTAX CHECK-UNICODE-ROLLBACK
   [: MISSING-LAST ;] UNICODE-CLASS-TOOL:E-SYNTAX CHECK-UNICODE-ROLLBACK
   [: ORPHAN-LAST ;] UNICODE-CLASS-TOOL:E-SYNTAX CHECK-UNICODE-ROLLBACK
   [: CATEGORY-MISMATCH ;] UNICODE-CLASS-TOOL:E-SYNTAX CHECK-UNICODE-ROLLBACK
   [: HIGH-SCALAR ;] UNICODE-CLASS-TOOL:E-RANGE CHECK-UNICODE-ROLLBACK
   [: SURROGATE-FIRST ;] UNICODE-CLASS-TOOL:E-RANGE CHECK-UNICODE-ROLLBACK
   [: SURROGATE-MIDDLE ;] UNICODE-CLASS-TOOL:E-RANGE CHECK-UNICODE-ROLLBACK
   [: SURROGATE-LAST ;] UNICODE-CLASS-TOOL:E-RANGE CHECK-UNICODE-ROLLBACK
   [: BAD-ORDER ;] UNICODE-CLASS-TOOL:E-RANGE CHECK-UNICODE-ROLLBACK
   [: OVERLAP ;] UNICODE-CLASS-TOOL:E-RANGE CHECK-UNICODE-ROLLBACK
   [: BAD-PROP-RANGE ;] UNICODE-CLASS-TOOL:E-RANGE CHECK-SPACE-ROLLBACK
   [: BAD-PROP-DOTS ;] UNICODE-CLASS-TOOL:E-SYNTAX CHECK-SPACE-ROLLBACK
   [: SURROGATE-PROP ;] UNICODE-CLASS-TOOL:E-RANGE CHECK-SPACE-ROLLBACK
   [: BAD-OTHER-PROP ;] UNICODE-CLASS-TOOL:E-SYNTAX CHECK-SPACE-ROLLBACK
   [: OVERLAP-PROPS ;] UNICODE-CLASS-TOOL:E-RANGE CHECK-SPACE-ROLLBACK
   [: UNSORTED-PROPS ;] UNICODE-CLASS-TOOL:E-RANGE CHECK-SPACE-ROLLBACK
   [: PARSER-RANGE-LOW ;] UNICODE-CLASS-TOOL:E-RANGE TTHROWSQ
   [: PARSER-RANGE-HIGH ;] UNICODE-CLASS-TOOL:E-RANGE TTHROWSQ
   [: BAD-DIGEST ;] UNICODE-CLASS-TOOL:E-DIGEST TTHROWSQ

   ADJACENT-PROPS$ UNICODE-CLASS-TOOL:PARSE-PROPERTIES
   UNICODE-CLASS-TOOL:SPACE-COUNT 1 T=
   0 UNICODE-CLASS-TOOL:SPACE-RANGE@ 14 T= 9 T=
   GOOD-PROPS$ UNICODE-CLASS-TOOL:PARSE-PROPERTIES

   AT-CAPACITY
   UNICODE-CLASS-TOOL:LETTER-COUNT 1024 T=
   1023 UNICODE-CLASS-TOOL:LETTER-RANGE@ nip 8180 > TTRUE
   SEED
   [: OVER-CAPACITY ;] UNICODE-CLASS-TOOL:E-CAPACITY CHECK-UNICODE-ROLLBACK ;

: TEST-PINNED ( -- )
   UNICODE-CLASS-TOOL:LOAD-PINNED
   UNICODE-CLASS-TOOL:READY? TTRUE
   UNICODE-CLASS-TOOL:LETTER-COUNT 677 T=
   UNICODE-CLASS-TOOL:NUMBER-COUNT 144 T=
   UNICODE-CLASS-TOOL:SPACE-COUNT 10 T=
   UNICODE-CLASS-TOOL:RENDER nip 16615 T= ;

public

: TEST ( -- )
   [: RENDER-WITHOUT-INPUT ;] UNICODE-CLASS-TOOL:E-STATE TTHROWSQ
   TEST-TRANSACTION
   TEST-PINNED ;

;package

UNICODE-CLASS-TOOL-TEST:TEST
T-REPORT
