// build.zig - external consumer build for a habu-exported kernel artifact pair.
//
// Descriptive example (Zig 0.16): shows how a Zig project depends on
// checked-Habu kernel output. It does not build inside the habu repo (no CUDA
// here); the wiring is the contract.
//
// Artifact provenance: the pair is produced as a build step by the habu tree:
//
//     bin/hb --load tools/ptx/kernel-export.f -- SAXPY examples/kernel-consumer
//
// which writes SAXPY.ptx and SAXPY.manifest.json (habu-kernel-manifest v1,
// contract in docs/ptx-sketch.md "Kernel ABI contract"). The export is
// deterministic - the same habu source tree writes byte-identical artifacts -
// so the pair can either be committed next to this file or regenerated by the
// system-command step below; @embedFile then bakes both into the executable.

const std = @import("std");

pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});

    // Regenerate the artifact pair from the habu tree when HABU_ROOT is set;
    // otherwise the committed SAXPY.ptx / SAXPY.manifest.json are used as-is.
    const maybe_habu_root = b.graph.environ_map.get("HABU_ROOT");

    const exe = b.addExecutable(.{
        .name = "kernel-consumer",
        .root_module = b.createModule(.{
            // main.zig @embedFile's SAXPY.ptx and SAXPY.manifest.json from
            // this module's directory.
            .root_source_file = b.path("main.zig"),
            .target = target,
            .optimize = optimize,
        }),
    });

    // The CUDA Driver API (cuInit/cuModuleLoadData/cuLaunchKernel/...) lives
    // in libcuda, shipped by the DRIVER, not the toolkit. On Jetson/Tegra the
    // real library is /usr/lib/aarch64-linux-gnu/tegra/libcuda.so - add that
    // directory with addLibraryPath when the linker only finds the toolkit
    // stub.
    exe.linkSystemLibrary("cuda");
    exe.linkLibC();

    if (maybe_habu_root) |habu_root| {
        const export_step = b.addSystemCommand(&.{ "bin/hb", "--load", "tools/ptx/kernel-export.f", "--", "SAXPY" });
        export_step.addArg(b.path(".").getPath(b));
        export_step.setCwd(.{ .cwd_relative = habu_root });
        exe.step.dependOn(&export_step.step);
    }

    b.installArtifact(exe);

    const run = b.addRunArtifact(exe);
    b.step("run", "launch the embedded habu kernel").dependOn(&run.step);
}
