\ build-test.f - focused tests for checked build helpers.
\ Run: bin/hb --load lib/errors.f lib/string.f lib/test.f lib/fs.f lib/fs-mutate.f lib/process.f lib/build.f lib/build-test.f

require lib/errors.f
require lib/string.f
require lib/test.f
require lib/fs.f
require lib/fs-mutate.f
require lib/process.f
require lib/build.f

\ Reopen the module for BUILD-EXPECT and the package-local public builders.
package BUILD

create BUILD-TEST-PATH FS-PATH-CAP allot
TYPED-VARIABLE BUILD-TEST-STEP step
1 TYPED-BUFFER BUILD-TEST-BOUNDED step
STRUCTURE guarded-step 0 DERIVE addr
   FIELD before n FIELD value step FIELD after n
;STRUCTURE
TYPED-VARIABLE BT-GUARDED guarded-step

variable BT-ROOT-U
variable BT-SRC-U
variable BT-MISSING-U
variable BT-CMD-OK-U
variable BT-CMD-NOART-U
variable BT-CMD-FAIL-U
variable BT-BAD-SRC-U
variable BT-UNCHECKABLE-SRC-U
variable BT-TOP-DIE-SRC-U

create BT-ROOT-BUF FS-PATH-CAP allot
create BT-SRC-BUF FS-PATH-CAP allot
create BT-MISSING-BUF FS-PATH-CAP allot
create BT-CMD-OK-BUF FS-PATH-CAP allot
create BT-CMD-NOART-BUF FS-PATH-CAP allot
create BT-CMD-FAIL-BUF FS-PATH-CAP allot
create BT-BAD-SRC-BUF FS-PATH-CAP allot
create BT-UNCHECKABLE-SRC-BUF FS-PATH-CAP allot
create BT-TOP-DIE-SRC-BUF FS-PATH-CAP allot

: BT-COPY! ( ptr u8 n ptr u8 ptr n -- ) {: a:ptr u dst:ptr lenp:ptr :}
   a dst u BYTE-COPY
   u lenp ! ;

: BT-PATH! ( ptr u8 n ptr u8 n ptr u8 ptr n -- ) {: pa:ptr pu na:ptr nu dst:ptr lenp:ptr :}
   pa pu na nu dst JOIN-PATH lenp ! ;

: BT-ROOT ( -- ptr u8 n )
   BT-ROOT-BUF BT-ROOT-U @ ;

: BT-SRC ( -- ptr u8 n )
   BT-SRC-BUF BT-SRC-U @ ;

: BT-MISSING ( -- ptr u8 n )
   BT-MISSING-BUF BT-MISSING-U @ ;

: BT-CMD-OK ( -- ptr u8 n )
   BT-CMD-OK-BUF BT-CMD-OK-U @ ;

: BT-CMD-NOART ( -- ptr u8 n )
   BT-CMD-NOART-BUF BT-CMD-NOART-U @ ;

: BT-CMD-FAIL ( -- ptr u8 n )
   BT-CMD-FAIL-BUF BT-CMD-FAIL-U @ ;

: BT-BAD-SRC ( -- ptr u8 n )
   BT-BAD-SRC-BUF BT-BAD-SRC-U @ ;

: BT-UNCHECKABLE-SRC ( -- ptr u8 n )
   BT-UNCHECKABLE-SRC-BUF BT-UNCHECKABLE-SRC-U @ ;

: BT-TOP-DIE-SRC ( -- ptr u8 n )
   BT-TOP-DIE-SRC-BUF BT-TOP-DIE-SRC-U @ ;

: BT-ROOT! ( -- )
   s" habu-build" HB-TMP-MKDIR {: a:ptr u :}
   a u BT-ROOT-BUF BT-ROOT-U BT-COPY! ;

: BT-PATHS! ( -- )
   BT-ROOT s" source.f" BT-SRC-BUF BT-SRC-U BT-PATH!
   BT-ROOT s" missing.f" BT-MISSING-BUF BT-MISSING-U BT-PATH!
   BT-ROOT s" cmd-ok.f" BT-CMD-OK-BUF BT-CMD-OK-U BT-PATH!
   BT-ROOT s" cmd-noart.f" BT-CMD-NOART-BUF BT-CMD-NOART-U BT-PATH!
   BT-ROOT s" cmd-fail.f" BT-CMD-FAIL-BUF BT-CMD-FAIL-U BT-PATH!
   BT-ROOT s" bad.f" BT-BAD-SRC-BUF BT-BAD-SRC-U BT-PATH!
   BT-ROOT s" uncheckable.f" BT-UNCHECKABLE-SRC-BUF BT-UNCHECKABLE-SRC-U BT-PATH!
   BT-ROOT s" top-die.f" BT-TOP-DIE-SRC-BUF BT-TOP-DIE-SRC-U BT-PATH! ;

: BT-ART ( -- ptr u8 n )
   BT-ROOT s" artifact.bin" ARTIFACT ;

: BT-NOART ( -- ptr u8 n )
   BT-ROOT s" noart.bin" ARTIFACT ;

: BT-SHEBANG ( -- )
   s" #!/usr/bin/env bin/hb" SB-APPEND
   10 SB-APPEND-C ;

: BT-SB-C, ( n -- )
   FS-MUT-SB-U
   s"  c, " SB-APPEND ;

: BT-SB-BYTES ( ptr u8 n -- ) {: a:ptr u :}
   0 begin dup u < while
      dup a + c@ BT-SB-C,
      1+
   repeat drop ;

: BT-SB-PATH ( ptr u8 n -- )
   s" create P " SB-APPEND
   BT-SB-BYTES
   0 BT-SB-C, ;

: BT-SB-ARTIFACT-DATA ( -- )
   s" create BT-ART-BUF 97 c, 114 c, 116 c, 105 c, 102 c, 97 c, 99 c, 116 c, " SB-APPEND ;

: BT-SCRIPT$ ( ptr u8 n -- ptr u8 n ) {: a:ptr u :}
   SB-RESET
   BT-SHEBANG
   a u SB-APPEND
   SB$ ;

: BT-OK-SCRIPT$ ( -- ptr u8 n )
   SB-RESET
   BT-SHEBANG
   BT-ART BT-SB-PATH
   BT-SB-ARTIFACT-DATA
   s" P 1537 420 open dup BT-ART-BUF 8 write drop close" SB-APPEND
   SB$ ;

: BT-WRITE-FILE ( ptr u8 n ptr u8 n -- ) {: path:ptr pathu src:ptr srcu :}
   path pathu src srcu WRITE-ALL
   path pathu CLEANUP+ ;

: BT-WRITE-CMD ( ptr u8 n ptr u8 n -- ) {: path:ptr pathu src:ptr srcu :}
   src srcu BT-SCRIPT$ {: code:ptr codeu :}
   path pathu code codeu WRITE-ALL
   path pathu CHMOD-X
   path pathu CLEANUP+ ;

: BT-WRITE-CMD-OK ( -- )
   BT-CMD-OK BT-OK-SCRIPT$ WRITE-ALL
   BT-CMD-OK CHMOD-X
   BT-CMD-OK CLEANUP+ ;

: BT-WRITE-FIXTURES ( -- )
   BT-SRC s" : MAIN ( -- ) ; : INC ( i64 -- i64 ) 1 + ;" BT-WRITE-FILE
   BT-BAD-SRC s" : BAD ( i64 -- i64 ) 0= ;" BT-WRITE-FILE
   BT-UNCHECKABLE-SRC s" : UNCHECKABLE ( i64 -- i64 ) evaluate ;" BT-WRITE-FILE
   BT-TOP-DIE-SRC s" 0 0 1 die : SAFE ( i64 -- i64 ) 1 + ;" BT-WRITE-FILE
   BT-WRITE-CMD-OK
   BT-CMD-NOART s" : NOART ( -- ) ; NOART" BT-WRITE-CMD
   BT-CMD-FAIL s" 0 0 7 die" BT-WRITE-CMD
   BT-ART CLEANUP+
   BT-NOART CLEANUP+ ;

: BT-PREPARE ( -- )
   CLEANUP-RESET
   BT-ROOT!
   BT-ROOT CLEANUP-DIR+
   BT-PATHS!
   BT-WRITE-FIXTURES ;

: BT-CLEANUP ( -- )
   CLEANUP-RUN
   BT-ROOT EXISTS? TFALSE ;

: BT-CHECK-ARTIFACT-PATH ( -- )
   BT-ROOT s" artifact.bin" ARTIFACT {: got:ptr gotu:n :}
   BT-ROOT s" artifact.bin" BUILD-TEST-PATH JOIN-PATH {: wantu :}
   got gotu BUILD-TEST-PATH wantu T$= ;

: BT-FILL-STEP ( -- )
   BUILD-TEST-STEP STEP-CLEAR
   s" make-artifact" BUILD-TEST-STEP STEP-NAME!
   BT-CMD-OK BUILD-TEST-STEP STEP-COMMAND!
   s" --emit-artifact" BUILD-TEST-STEP STEP-ARGV!
   BT-ROOT BUILD-TEST-STEP STEP-TMP!
   BT-ART BUILD-TEST-STEP STEP-ARTIFACT! ;

: BT-FILL-STEP-NOART ( -- )
   BUILD-TEST-STEP STEP-CLEAR
   s" no-artifact" BUILD-TEST-STEP STEP-NAME!
   BT-CMD-NOART BUILD-TEST-STEP STEP-COMMAND!
   s" --missing-artifact" BUILD-TEST-STEP STEP-ARGV!
   BT-ROOT BUILD-TEST-STEP STEP-TMP!
   BT-NOART BUILD-TEST-STEP STEP-ARTIFACT! ;

: BT-OK-STEP ( -- n )
   0 ;

: BT-BAD-STEP ( -- n )
   7 ;

: BT-MISSING-SOURCE ( -- )
   BT-MISSING CHECK ;

: BT-BAD-SOURCE ( -- )
   BT-BAD-SRC CHECK ;

: BT-UNCHECKABLE-SOURCE ( -- )
   BT-UNCHECKABLE-SRC CHECK ;

: BT-MISSING-EXPECT ( -- )
   BT-NOART BUILD-EXPECT ;

: BT-EMPTY-ARTIFACT ( -- )
   BT-ROOT s" " ARTIFACT 2drop ;

: BT-BAD-STEP-RUN ( -- )
   s" bad-step" [: BT-BAD-STEP ;] STEP ;

: BT-EMPTY-STEP ( -- )
   s" " [: BT-OK-STEP ;] STEP ;

: BT-MISSING-COMMAND ( -- )
   BT-MISSING BT-ART RUN drop ;

: BT-NO-ARTIFACT ( -- )
   BT-CMD-NOART BT-NOART RUN drop ;

: BT-FAIL-COMMAND ( -- )
   BT-CMD-FAIL BT-ART RUN drop ;

: BT-BAD-STEP-FIELD ( -- )
   1 BUILD-TEST-BOUNDED drop ;

: BT-MISSING-STEP-COMMAND ( -- )
   BUILD-TEST-STEP STEP-CLEAR
   s" bad" BUILD-TEST-STEP STEP-NAME!
   s" --none" BUILD-TEST-STEP STEP-ARGV!
   BT-ROOT BUILD-TEST-STEP STEP-TMP!
   BT-ART BUILD-TEST-STEP STEP-ARTIFACT!
   BUILD-TEST-STEP STEP-RUN drop ;

: BT-EMPTY-STEP-TMP ( -- )
   s" " BUILD-TEST-STEP STEP-TMP! ;

: BT-NOART-STEP-RUN ( -- )
   BT-FILL-STEP-NOART
   BUILD-TEST-STEP STEP-RUN drop ;

: BT-PENDING? ( ptr step -- bool )
   STEP-STATE@ MATCH state
      pending OF true ENDOF
      completed OF drop false ENDOF
   ;MATCH ;

: BT-NEGATIVE-ARGV ( -- )
   s" unused" drop -1 BUILD-TEST-STEP STEP-ARGV! ;
: BT-ZERO-COMMAND ( -- )
   s" " BUILD-TEST-STEP STEP-COMMAND! ;
: BT-RUN-RECORD ( -- ) BUILD-TEST-STEP STEP-RUN drop ;

: BUILD-TEST-TYPES ( -- )
   s" BTP ( BUILD:text ptr BUILD:step -- ) BUILD-STEP:COMMAND !"
   CHECK-QUIET-CANDIDATE! -1 T=
   s" BTC ( BUILD:state ptr BUILD:step -- ) BUILD-STEP:COMMAND !"
   CHECK-QUIET-CANDIDATE! 0 T=
   s" BTF ( BUILD:text ptr BUILD:step -- ) BUILD-STEP:STATE !"
   CHECK-QUIET-CANDIDATE! 0 T=
   s" BTR ( n ptr BUILD:step -- ) BUILD-STEP:STATE !"
   CHECK-QUIET-CANDIDATE! 0 T=
   s" BTL ( len ptr u8 -- BUILD:text ) BUILD-TEXT:MAKE"
   CHECK-QUIET-CANDIDATE! 0 T=
   s" BTRAW ( ptr n -- ) BUILD:STEP-CLEAR"
   CHECK-QUIET-CANDIDATE! 0 T= ;

: BUILD-TEST-STATE ( -- )
   0 BUILD-TEST-BOUNDED BT-PENDING? TTRUE
   BUILD-TEST-STEP STEP-CLEAR
   BUILD-TEST-STEP BT-PENDING? TTRUE
   BUILD-TEST-STEP STEP-RC@ -1 T=
   BT-FILL-STEP
   BUILD-TEST-STEP STEP-RUN 0 T=
   BUILD-TEST-STEP BT-PENDING? TFALSE
   BUILD-TEST-STEP STEP-RUN 0 T=  \ reruns remain legal
   -2 BUILD-TEST-STEP STEP-RC!
   BUILD-TEST-STEP STEP-RC@ -2 T=
   -1 BUILD-TEST-STEP STEP-RC!
   BUILD-TEST-STEP BT-PENDING? TTRUE
   \ Every successful input edit invalidates the old completed result.
   7 BUILD-TEST-STEP STEP-RC!
   s" renamed" BUILD-TEST-STEP STEP-NAME! BUILD-TEST-STEP BT-PENDING? TTRUE
   7 BUILD-TEST-STEP STEP-RC!
   BT-CMD-OK BUILD-TEST-STEP STEP-COMMAND! BUILD-TEST-STEP BT-PENDING? TTRUE
   7 BUILD-TEST-STEP STEP-RC!
   s" " BUILD-TEST-STEP STEP-ARGV! BUILD-TEST-STEP BT-PENDING? TTRUE
   7 BUILD-TEST-STEP STEP-RC!
   BT-ROOT BUILD-TEST-STEP STEP-TMP! BUILD-TEST-STEP BT-PENDING? TTRUE
   7 BUILD-TEST-STEP STEP-RC!
   BT-ART BUILD-TEST-STEP STEP-ARTIFACT! BUILD-TEST-STEP BT-PENDING? TTRUE
   \ Refused edits preserve both the old input and its completed result.
   7 BUILD-TEST-STEP STEP-RC!
   [: BT-NEGATIVE-ARGV ;] E-BUILD-PATH TTHROWSQ
   BUILD-TEST-STEP STEP-ARGV$ nip 0 T=
   [: BT-ZERO-COMMAND ;] E-BUILD-COMMAND TTHROWSQ
   BUILD-TEST-STEP STEP-COMMAND$ BT-CMD-OK T$=
   [: BT-EMPTY-STEP-TMP ;] E-BUILD-PATH TTHROWSQ
   BUILD-TEST-STEP STEP-TMP$ BT-ROOT T$=
   BUILD-TEST-STEP STEP-RC@ 7 T=
   \ Validation refusal leaves the entire record unchanged.
   BT-MISSING BUILD-TEST-STEP STEP-COMMAND!
   7 BUILD-TEST-STEP STEP-RC!
   [: BT-RUN-RECORD ;] E-BUILD-COMMAND TTHROWSQ
   BUILD-TEST-STEP STEP-COMMAND$ BT-MISSING T$=
   BUILD-TEST-STEP STEP-RC@ 7 T=
   BT-CMD-OK BUILD-TEST-STEP STEP-COMMAND!
   BT-MISSING BUILD-TEST-STEP STEP-TMP!
   7 BUILD-TEST-STEP STEP-RC!
   [: BT-RUN-RECORD ;] E-BUILD-PATH TTHROWSQ
   BUILD-TEST-STEP STEP-TMP$ BT-MISSING T$=
   BUILD-TEST-STEP STEP-RC@ 7 T=
   \ A started run that throws cannot retain a preceding success.
   BT-FILL-STEP-NOART 0 BUILD-TEST-STEP STEP-RC!
   [: BT-RUN-RECORD ;] E-BUILD-PATH TTHROWSQ
   BUILD-TEST-STEP BT-PENDING? TTRUE
   BT-FILL-STEP BT-CMD-FAIL BUILD-TEST-STEP STEP-COMMAND!
   0 BUILD-TEST-STEP STEP-RC!
   [: BT-RUN-RECORD ;] E-BUILD-STATUS TTHROWSQ
   BUILD-TEST-STEP BT-PENDING? TTRUE
   BUILD-TEST-STEP STEP-CLEAR BUILD-TEST-STEP BT-PENDING? TTRUE ;

: BUILD-TEST-CANARIES ( -- )
   123 BT-GUARDED GUARDED-STEP-BEFORE !
   456 BT-GUARDED GUARDED-STEP-AFTER !
   BT-GUARDED GUARDED-STEP-VALUE {: rec:ptr :}
   rec STEP-CLEAR
   s" name" rec STEP-NAME!
   s" command" rec STEP-COMMAND!
   s" arguments" rec STEP-ARGV!
   s" temporary" rec STEP-TMP!
   s" artifact" rec STEP-ARTIFACT!
   7 rec STEP-RC!
   rec STEP-CLEAR
   rec STEP-NAME$ nip 0 T=
   rec STEP-COMMAND$ nip 0 T=
   rec STEP-ARGV$ nip 0 T=
   rec STEP-TMP$ nip 0 T=
   rec STEP-ARTIFACT$ nip 0 T=
   BT-GUARDED GUARDED-STEP-BEFORE @ 123 T=
   BT-GUARDED GUARDED-STEP-AFTER @ 456 T=
   0 BUILD-TEST-BOUNDED STEP-CLEAR
   [: BT-BAD-STEP-FIELD ;] E-LAYOUT-BOUNDS TTHROWSQ
   0 BUILD-TEST-BOUNDED BT-PENDING? TTRUE ;

: BUILD-TEST-PATHS ( -- )
   BT-SRC CHECK
   BT-TOP-DIE-SRC CHECK
   [: BT-MISSING-SOURCE ;] E-BUILD-SOURCE TTHROWSQ
   [: BT-BAD-SOURCE ;] E-BUILD-SOURCE TTHROWSQ
   [: BT-UNCHECKABLE-SOURCE ;] E-BUILD-SOURCE TTHROWSQ
   BT-CHECK-ARTIFACT-PATH
   [: BT-MISSING-EXPECT ;] E-BUILD-PATH TTHROWSQ
   [: BT-EMPTY-ARTIFACT ;] E-BUILD-PATH TTHROWSQ ;

: BUILD-TEST-STEPS ( -- )
   s" ok-step" [: BT-OK-STEP ;] STEP
   [: BT-BAD-STEP-RUN ;] E-BUILD-STATUS TTHROWSQ
   [: BT-EMPTY-STEP ;] E-BUILD-COMMAND TTHROWSQ ;

: BUILD-TEST-RUNS ( -- )
   BT-CMD-OK BT-ART RUN 0 T=
   BT-ART FILE? TTRUE
   [: BT-MISSING-COMMAND ;] E-BUILD-COMMAND TTHROWSQ
   [: BT-NO-ARTIFACT ;] E-BUILD-PATH TTHROWSQ
   [: BT-FAIL-COMMAND ;] E-BUILD-STATUS TTHROWSQ ;

: BUILD-TEST-RECORDS ( -- )
   BT-FILL-STEP
   BUILD-TEST-STEP STEP-NAME$ s" make-artifact" T$=
   BUILD-TEST-STEP STEP-COMMAND$ BT-CMD-OK T$=
   BUILD-TEST-STEP STEP-ARGV$ s" --emit-artifact" T$=
   BUILD-TEST-STEP STEP-TMP$ BT-ROOT T$=
   BUILD-TEST-STEP STEP-ARTIFACT$ BT-ART T$=
   BUILD-TEST-STEP STEP-VALIDATE
   BUILD-TEST-STEP STEP-RUN 0 T=
   BUILD-TEST-STEP STEP-RC@ 0 T=
   BT-ART FILE? TTRUE
   [: BT-BAD-STEP-FIELD ;] E-LAYOUT-BOUNDS TTHROWSQ
   [: BT-MISSING-STEP-COMMAND ;] E-BUILD-COMMAND TTHROWSQ
   [: BT-EMPTY-STEP-TMP ;] E-BUILD-PATH TTHROWSQ
   [: BT-NOART-STEP-RUN ;] E-BUILD-PATH TTHROWSQ ;

: BUILD-TEST-MAIN ( -- )
   T-RESET
   BT-PREPARE
   BUILD-TEST-PATHS
   BUILD-TEST-STEPS
   BUILD-TEST-RUNS
   BUILD-TEST-RECORDS
   BUILD-TEST-TYPES
   BUILD-TEST-STATE
   BUILD-TEST-CANARIES
   BT-CLEANUP
   T-REPORT
   s" build-test: ok" type cr ;

BUILD-TEST-MAIN

;package
