\ fs-mutate-test.f - focused tests for lib/fs-mutate.f.
\ Run: lib/fs-mutate-test.sh

: FMT-REMOVE-PATH ( -- ptr u8 n )
   0 SCRIPT-ARGV$ ;

: FMT-RENAME-SRC ( -- ptr u8 n )
   1 SCRIPT-ARGV$ ;

: FMT-RENAME-DST ( -- ptr u8 n )
   2 SCRIPT-ARGV$ ;

: FMT-CHMOD-PATH ( -- ptr u8 n )
   3 SCRIPT-ARGV$ ;

: FMT-COPY-SRC ( -- ptr u8 n )
   4 SCRIPT-ARGV$ ;

: FMT-COPY-DST ( -- ptr u8 n )
   5 SCRIPT-ARGV$ ;

: FMT-ATOMIC-PATH ( -- ptr u8 n )
   6 SCRIPT-ARGV$ ;

: FMT-MKDIR-PATH ( -- ptr u8 n )
   7 SCRIPT-ARGV$ ;

: FMT-NEST-A ( -- ptr u8 n )
   8 SCRIPT-ARGV$ ;

: FMT-NEST-B ( -- ptr u8 n )
   9 SCRIPT-ARGV$ ;

: FMT-NEST-C ( -- ptr u8 n )
   10 SCRIPT-ARGV$ ;

: FMT-TEMP-BASE ( -- ptr u8 n )
   11 SCRIPT-ARGV$ ;

: FMT-REMOVE-MISSING ( -- )
   s" no-such-habu-fs-remove-file" REMOVE-FILE ;

: FMT-RENAME-MISSING ( -- )
   s" no-such-habu-fs-rename-file" FMT-RENAME-DST RENAME-FILE ;

: FMT-CHMOD-MISSING ( -- )
   s" no-such-habu-fs-chmod-file" CHMOD-X ;

: FMT-RMDIR-MISSING ( -- )
   s" no-such-habu-fs-rmdir" REMOVE-DIR ;

: FMT-MKDIR-EXISTS ( -- )
   FMT-MKDIR-PATH MAKE-DIR ;

: FMT-COPY-TOO-SMALL ( -- )
   FMT-COPY-SRC FMT-COPY-DST 3 COPY-FILE ;

create FMT-READ-BUF 64 allot

: FMT-TEST-COPY ( -- )
   FMT-COPY-SRC FMT-COPY-DST 64 COPY-FILE
   FMT-COPY-DST FILE? TTRUE
   FMT-COPY-DST FMT-READ-BUF 64 READ-ALL 8 T=
   FMT-READ-BUF 8 s" copy-src" T$= ;

: FMT-TEST-ATOMIC-WRITE ( -- )
   FMT-ATOMIC-PATH s" old" WRITE-ALL
   FMT-ATOMIC-PATH s" new-data" ATOMIC-WRITE-FILE
   FMT-ATOMIC-PATH FMT-READ-BUF 64 READ-ALL 8 T=
   FMT-READ-BUF 8 s" new-data" T$= ;

: FMT-TEST-DIRS ( -- )
   FMT-MKDIR-PATH MAKE-DIR
   FMT-MKDIR-PATH DIR? TTRUE
   FMT-NEST-C MAKE-DIRS
   FMT-NEST-A DIR? TTRUE
   FMT-NEST-B DIR? TTRUE
   FMT-NEST-C DIR? TTRUE ;

: FMT-TEST-TEMPS ( -- )
   FMT-TEMP-BASE s" one" MAKE-TEMP-DIR 2dup DIR? TTRUE CLEANUP-DIR+
   FMT-TEMP-BASE s" two" MAKE-TEMP-DIR 2dup DIR? TTRUE CLEANUP-DIR+
   s" habu-fs-mut" TMPDIR-MKDIR 2dup DIR? TTRUE CLEANUP-DIR+ ;

: FMT-TEST-CLEANUP ( -- )
   CLEANUP-RESET
   FMT-COPY-DST CLEANUP+
   FMT-ATOMIC-PATH CLEANUP+
   FMT-MKDIR-PATH CLEANUP-DIR+
   FMT-NEST-A CLEANUP-DIR+
   FMT-NEST-B CLEANUP-DIR+
   FMT-NEST-C CLEANUP-DIR+
   CLEANUP-RUN
   FMT-COPY-DST EXISTS? TFALSE
   FMT-ATOMIC-PATH EXISTS? TFALSE
   FMT-MKDIR-PATH EXISTS? TFALSE
   FMT-NEST-A EXISTS? TFALSE
   CLEANUP-RUN ;

: FS-MUTATE-TEST-MAIN ( -- )
   T-RESET
   SCRIPT-ARGC 12 < if s" fs-mutate-test: missing fixture args" T-EX-FAIL die then
   FMT-REMOVE-PATH FILE? TTRUE
   FMT-REMOVE-PATH REMOVE-FILE
   FMT-REMOVE-PATH EXISTS? TFALSE
   FMT-RENAME-SRC FILE? TTRUE
   FMT-RENAME-DST EXISTS? TFALSE
   FMT-RENAME-SRC FMT-RENAME-DST RENAME-FILE
   FMT-RENAME-SRC EXISTS? TFALSE
   FMT-RENAME-DST FILE? TTRUE
   FMT-CHMOD-PATH CHMOD-X
   FMT-CHMOD-PATH STAT-MODE FS-MUT-MODE-EXEC and FS-MUT-MODE-EXEC = TTRUE
   FMT-TEST-COPY
   FMT-TEST-ATOMIC-WRITE
   FMT-TEST-DIRS
   FMT-TEST-TEMPS
   ['] FMT-REMOVE-MISSING E-FS-IO TTHROWS
   ['] FMT-RENAME-MISSING E-FS-IO TTHROWS
   ['] FMT-CHMOD-MISSING E-FS-STAT TTHROWS
   ['] FMT-RMDIR-MISSING E-FS-IO TTHROWS
   ['] FMT-MKDIR-EXISTS E-FS-IO TTHROWS
   ['] FMT-COPY-TOO-SMALL E-FS-CAPACITY TTHROWS
   FMT-TEST-CLEANUP
   T-REPORT
   s" fs-mutate-test: ok" type cr ;

FS-MUTATE-TEST-MAIN
