\ fs-mutate-test.f - focused tests for lib/fs-mutate.f.
\ Run: bin/hb --load lib/errors.f lib/string.f lib/test.f lib/fs.f lib/fs-mutate.f lib/fs-mutate-test.f

variable FMT-ROOT-U
variable FMT-REMOVE-U
variable FMT-RENAME-SRC-U
variable FMT-RENAME-DST-U
variable FMT-CHMOD-U
variable FMT-COPY-SRC-U
variable FMT-COPY-DST-U
variable FMT-ATOMIC-U
variable FMT-MKDIR-U
variable FMT-NEST-A-U
variable FMT-NEST-B-U
variable FMT-NEST-C-U
variable FMT-TREE-U
variable FMT-TREE-CHILD-U
variable FMT-TREE-GRAND-U
variable FMT-TREE-DOTS-U
variable FMT-TREE-ROOT-FILE-U
variable FMT-TREE-LEAF-U
variable FMT-TREE-DOTS-FILE-U
variable FMT-LINK-TARGET-U
variable FMT-LINK-U
variable FMT-BROKEN-TARGET-U
variable FMT-BROKEN-LINK-U
variable FMT-LINK-DIR-U
variable FMT-LINK-DIR-FILE-U
variable FMT-TREE-DIR-LINK-U

create FMT-ROOT-BUF FS-PATH-CAP allot
create FMT-REMOVE-BUF FS-PATH-CAP allot
create FMT-RENAME-SRC-BUF FS-PATH-CAP allot
create FMT-RENAME-DST-BUF FS-PATH-CAP allot
create FMT-CHMOD-BUF FS-PATH-CAP allot
create FMT-COPY-SRC-BUF FS-PATH-CAP allot
create FMT-COPY-DST-BUF FS-PATH-CAP allot
create FMT-ATOMIC-BUF FS-PATH-CAP allot
create FMT-MKDIR-BUF FS-PATH-CAP allot
create FMT-NEST-A-BUF FS-PATH-CAP allot
create FMT-NEST-B-BUF FS-PATH-CAP allot
create FMT-NEST-C-BUF FS-PATH-CAP allot
create FMT-TREE-BUF FS-PATH-CAP allot
create FMT-TREE-CHILD-BUF FS-PATH-CAP allot
create FMT-TREE-GRAND-BUF FS-PATH-CAP allot
create FMT-TREE-DOTS-BUF FS-PATH-CAP allot
create FMT-TREE-ROOT-FILE-BUF FS-PATH-CAP allot
create FMT-TREE-LEAF-BUF FS-PATH-CAP allot
create FMT-TREE-DOTS-FILE-BUF FS-PATH-CAP allot
create FMT-LINK-TARGET-BUF FS-PATH-CAP allot
create FMT-LINK-BUF FS-PATH-CAP allot
create FMT-BROKEN-TARGET-BUF FS-PATH-CAP allot
create FMT-BROKEN-LINK-BUF FS-PATH-CAP allot
create FMT-LINK-DIR-BUF FS-PATH-CAP allot
create FMT-LINK-DIR-FILE-BUF FS-PATH-CAP allot
create FMT-TREE-DIR-LINK-BUF FS-PATH-CAP allot

: FMT-ROOT$ ( -- ptr u8 n )
   FMT-ROOT-BUF FMT-ROOT-U @ ;

: FMT-REMOVE-PATH ( -- ptr u8 n )
   FMT-REMOVE-BUF FMT-REMOVE-U @ ;

: FMT-RENAME-SRC ( -- ptr u8 n )
   FMT-RENAME-SRC-BUF FMT-RENAME-SRC-U @ ;

: FMT-RENAME-DST ( -- ptr u8 n )
   FMT-RENAME-DST-BUF FMT-RENAME-DST-U @ ;

: FMT-CHMOD-PATH ( -- ptr u8 n )
   FMT-CHMOD-BUF FMT-CHMOD-U @ ;

: FMT-COPY-SRC ( -- ptr u8 n )
   FMT-COPY-SRC-BUF FMT-COPY-SRC-U @ ;

: FMT-COPY-DST ( -- ptr u8 n )
   FMT-COPY-DST-BUF FMT-COPY-DST-U @ ;

: FMT-ATOMIC-PATH ( -- ptr u8 n )
   FMT-ATOMIC-BUF FMT-ATOMIC-U @ ;

: FMT-MKDIR-PATH ( -- ptr u8 n )
   FMT-MKDIR-BUF FMT-MKDIR-U @ ;

: FMT-NEST-A ( -- ptr u8 n )
   FMT-NEST-A-BUF FMT-NEST-A-U @ ;

: FMT-NEST-B ( -- ptr u8 n )
   FMT-NEST-B-BUF FMT-NEST-B-U @ ;

: FMT-NEST-C ( -- ptr u8 n )
   FMT-NEST-C-BUF FMT-NEST-C-U @ ;

: FMT-TREE ( -- ptr u8 n )
   FMT-TREE-BUF FMT-TREE-U @ ;

: FMT-TREE-CHILD ( -- ptr u8 n )
   FMT-TREE-CHILD-BUF FMT-TREE-CHILD-U @ ;

: FMT-TREE-GRAND ( -- ptr u8 n )
   FMT-TREE-GRAND-BUF FMT-TREE-GRAND-U @ ;

: FMT-TREE-DOTS ( -- ptr u8 n )
   FMT-TREE-DOTS-BUF FMT-TREE-DOTS-U @ ;

: FMT-TREE-ROOT-FILE ( -- ptr u8 n )
   FMT-TREE-ROOT-FILE-BUF FMT-TREE-ROOT-FILE-U @ ;

: FMT-TREE-LEAF ( -- ptr u8 n )
   FMT-TREE-LEAF-BUF FMT-TREE-LEAF-U @ ;

: FMT-TREE-DOTS-FILE ( -- ptr u8 n )
   FMT-TREE-DOTS-FILE-BUF FMT-TREE-DOTS-FILE-U @ ;

: FMT-LINK-TARGET ( -- ptr u8 n )
   FMT-LINK-TARGET-BUF FMT-LINK-TARGET-U @ ;

: FMT-LINK ( -- ptr u8 n )
   FMT-LINK-BUF FMT-LINK-U @ ;

: FMT-BROKEN-TARGET ( -- ptr u8 n )
   FMT-BROKEN-TARGET-BUF FMT-BROKEN-TARGET-U @ ;

: FMT-BROKEN-LINK ( -- ptr u8 n )
   FMT-BROKEN-LINK-BUF FMT-BROKEN-LINK-U @ ;

: FMT-LINK-DIR ( -- ptr u8 n )
   FMT-LINK-DIR-BUF FMT-LINK-DIR-U @ ;

: FMT-LINK-DIR-FILE ( -- ptr u8 n )
   FMT-LINK-DIR-FILE-BUF FMT-LINK-DIR-FILE-U @ ;

: FMT-TREE-DIR-LINK ( -- ptr u8 n )
   FMT-TREE-DIR-LINK-BUF FMT-TREE-DIR-LINK-U @ ;

: FMT-TEMP-BASE ( -- ptr u8 n )
   FMT-ROOT$ ;

: FMT-ROOT! ( -- )
   s" habu-fs-mutate" TMPDIR-MKDIR {: a:ptr u :}
   a FMT-ROOT-BUF u BYTE-COPY
   u FMT-ROOT-U ! ;

: FMT-REMOVE! ( -- )
   FMT-ROOT$ s" remove.txt" FMT-REMOVE-BUF JOIN-PATH FMT-REMOVE-U ! ;

: FMT-RENAME-SRC! ( -- )
   FMT-ROOT$ s" rename-src.txt" FMT-RENAME-SRC-BUF JOIN-PATH FMT-RENAME-SRC-U ! ;

: FMT-RENAME-DST! ( -- )
   FMT-ROOT$ s" rename-dst.txt" FMT-RENAME-DST-BUF JOIN-PATH FMT-RENAME-DST-U ! ;

: FMT-CHMOD! ( -- )
   FMT-ROOT$ s" chmod.txt" FMT-CHMOD-BUF JOIN-PATH FMT-CHMOD-U ! ;

: FMT-COPY-SRC! ( -- )
   FMT-ROOT$ s" copy-src.txt" FMT-COPY-SRC-BUF JOIN-PATH FMT-COPY-SRC-U ! ;

: FMT-COPY-DST! ( -- )
   FMT-ROOT$ s" copy-dst.txt" FMT-COPY-DST-BUF JOIN-PATH FMT-COPY-DST-U ! ;

: FMT-ATOMIC! ( -- )
   FMT-ROOT$ s" atomic.txt" FMT-ATOMIC-BUF JOIN-PATH FMT-ATOMIC-U ! ;

: FMT-MKDIR! ( -- )
   FMT-ROOT$ s" mkdir-one" FMT-MKDIR-BUF JOIN-PATH FMT-MKDIR-U ! ;

: FMT-NEST-A! ( -- )
   FMT-ROOT$ s" nested" FMT-NEST-A-BUF JOIN-PATH FMT-NEST-A-U ! ;

: FMT-NEST-B! ( -- )
   FMT-NEST-A s" child" FMT-NEST-B-BUF JOIN-PATH FMT-NEST-B-U ! ;

: FMT-NEST-C! ( -- )
   FMT-NEST-B s" grand" FMT-NEST-C-BUF JOIN-PATH FMT-NEST-C-U ! ;

: FMT-TREE! ( -- )
   FMT-ROOT$ s" remove-tree" FMT-TREE-BUF JOIN-PATH FMT-TREE-U ! ;

: FMT-TREE-CHILD! ( -- )
   FMT-TREE s" child" FMT-TREE-CHILD-BUF JOIN-PATH FMT-TREE-CHILD-U ! ;

: FMT-TREE-GRAND! ( -- )
   FMT-TREE-CHILD s" grand" FMT-TREE-GRAND-BUF JOIN-PATH FMT-TREE-GRAND-U ! ;

: FMT-TREE-DOTS! ( -- )
   FMT-TREE s" .dots" FMT-TREE-DOTS-BUF JOIN-PATH FMT-TREE-DOTS-U ! ;

: FMT-TREE-ROOT-FILE! ( -- )
   FMT-TREE s" root.txt" FMT-TREE-ROOT-FILE-BUF JOIN-PATH FMT-TREE-ROOT-FILE-U ! ;

: FMT-TREE-LEAF! ( -- )
   FMT-TREE-GRAND s" leaf.txt" FMT-TREE-LEAF-BUF JOIN-PATH FMT-TREE-LEAF-U ! ;

: FMT-TREE-DOTS-FILE! ( -- )
   FMT-TREE-DOTS s" kept-by-walk.txt" FMT-TREE-DOTS-FILE-BUF JOIN-PATH FMT-TREE-DOTS-FILE-U ! ;

: FMT-LINK-TARGET! ( -- )
   FMT-ROOT$ s" link-target.txt" FMT-LINK-TARGET-BUF JOIN-PATH FMT-LINK-TARGET-U ! ;

: FMT-LINK! ( -- )
   FMT-ROOT$ s" link.txt" FMT-LINK-BUF JOIN-PATH FMT-LINK-U ! ;

: FMT-BROKEN-TARGET! ( -- )
   FMT-ROOT$ s" no-such-link-target.txt" FMT-BROKEN-TARGET-BUF JOIN-PATH FMT-BROKEN-TARGET-U ! ;

: FMT-BROKEN-LINK! ( -- )
   FMT-ROOT$ s" broken-link.txt" FMT-BROKEN-LINK-BUF JOIN-PATH FMT-BROKEN-LINK-U ! ;

: FMT-LINK-DIR! ( -- )
   FMT-ROOT$ s" link-dir-target" FMT-LINK-DIR-BUF JOIN-PATH FMT-LINK-DIR-U ! ;

: FMT-LINK-DIR-FILE! ( -- )
   FMT-LINK-DIR s" kept.txt" FMT-LINK-DIR-FILE-BUF JOIN-PATH FMT-LINK-DIR-FILE-U ! ;

: FMT-TREE-DIR-LINK! ( -- )
   FMT-TREE s" dir-link" FMT-TREE-DIR-LINK-BUF JOIN-PATH FMT-TREE-DIR-LINK-U ! ;

: FMT-PATHS! ( -- )
   FMT-ROOT!
   FMT-REMOVE!
   FMT-RENAME-SRC!
   FMT-RENAME-DST!
   FMT-CHMOD!
   FMT-COPY-SRC!
   FMT-COPY-DST!
   FMT-ATOMIC!
   FMT-MKDIR!
   FMT-NEST-A!
   FMT-NEST-B!
   FMT-NEST-C!
   FMT-TREE!
   FMT-TREE-CHILD!
   FMT-TREE-GRAND!
   FMT-TREE-DOTS!
   FMT-TREE-ROOT-FILE!
   FMT-TREE-LEAF!
   FMT-TREE-DOTS-FILE!
   FMT-LINK-TARGET!
   FMT-LINK!
   FMT-BROKEN-TARGET!
   FMT-BROKEN-LINK!
   FMT-LINK-DIR!
   FMT-LINK-DIR-FILE!
   FMT-TREE-DIR-LINK! ;

: FMT-WRITE-FIXTURES ( -- )
   FMT-REMOVE-PATH s" delete-me" WRITE-ALL
   FMT-RENAME-SRC s" rename-me" WRITE-ALL
   FMT-CHMOD-PATH s" #!/bin/sh\nexit 0\n" WRITE-ALL
   FMT-COPY-SRC s" copy-src" WRITE-ALL ;

: FMT-WRITE-TREE ( -- )
   FMT-TREE-GRAND MAKE-DIRS
   FMT-TREE-DOTS MAKE-DIRS
   FMT-TREE-ROOT-FILE s" root" WRITE-ALL
   FMT-TREE-LEAF s" leaf" WRITE-ALL
   FMT-TREE-DOTS-FILE s" dot" WRITE-ALL ;

: FMT-PREPARE ( -- )
   CLEANUP-RESET
   FMT-PATHS!
   FMT-ROOT$ CLEANUP-DIR+
   FMT-WRITE-FIXTURES ;

: FMT-REMOVE-MISSING ( -- )
   s" no-such-habu-fs-remove-file" REMOVE-FILE ;

: FMT-RENAME-MISSING ( -- )
   s" no-such-habu-fs-rename-file" FMT-RENAME-DST RENAME-FILE ;

: FMT-CHMOD-MISSING ( -- )
   s" no-such-habu-fs-chmod-file" CHMOD-X ;

: FMT-RMDIR-MISSING ( -- )
   s" no-such-habu-fs-rmdir" REMOVE-DIR ;

: FMT-MKDIR-EXISTS ( -- )
   FMT-MKDIR-PATH MAKE-DIR ;

: FMT-COPY-TOO-SMALL ( -- )
   FMT-COPY-SRC FMT-COPY-DST 3 COPY-FILE ;

: FMT-REMOVE-TREE-EMPTY ( -- )
   s" " REMOVE-TREE ;

create FMT-READ-BUF 64 allot
create FMT-LINK-READ-BUF FS-PATH-CAP allot

: FMT-MAKE-SYMLINK-EXISTS ( -- )
   FMT-LINK-TARGET FMT-LINK MAKE-SYMLINK ;

: FMT-LINK-READ-TOO-SMALL ( -- )
   FMT-LINK FMT-LINK-READ-BUF 3 READ-LINK drop ;

: FMT-READ-LINK-NONLINK ( -- )
   FMT-LINK-TARGET FMT-LINK-READ-BUF FS-PATH-CAP READ-LINK drop ;

: FMT-TEST-COPY ( -- )
   FMT-COPY-SRC FMT-COPY-DST 64 COPY-FILE
   FMT-COPY-DST FILE? TTRUE
   FMT-COPY-DST FMT-READ-BUF 64 READ-ALL 8 T=
   FMT-READ-BUF 8 s" copy-src" T$= ;

: FMT-TEST-ATOMIC-WRITE ( -- )
   FMT-ATOMIC-PATH s" old" WRITE-ALL
   FMT-ATOMIC-PATH s" new-data" ATOMIC-WRITE-FILE
   FMT-ATOMIC-PATH FMT-READ-BUF 64 READ-ALL 8 T=
   FMT-READ-BUF 8 s" new-data" T$= ;

: FMT-TEST-DIRS ( -- )
   FMT-MKDIR-PATH MAKE-DIR
   FMT-MKDIR-PATH DIR? TTRUE
   FMT-NEST-C MAKE-DIRS
   FMT-NEST-A DIR? TTRUE
   FMT-NEST-B DIR? TTRUE
   FMT-NEST-C DIR? TTRUE ;

: FMT-TEST-TEMPS ( -- )
   FMT-TEMP-BASE s" one" MAKE-TEMP-DIR 2dup DIR? TTRUE CLEANUP-DIR+
   FMT-TEMP-BASE s" two" MAKE-TEMP-DIR 2dup DIR? TTRUE CLEANUP-DIR+
   s" habu-fs-mut" TMPDIR-MKDIR 2dup DIR? TTRUE CLEANUP-DIR+ ;

: FMT-TEST-SYMLINK ( -- )
   FMT-LINK-TARGET s" link-target" WRITE-ALL
   FMT-LINK-TARGET FMT-LINK MAKE-SYMLINK
   FMT-LINK SYMLINK? TTRUE
   FMT-LINK FILE? TTRUE
   FMT-LINK FMT-LINK-READ-BUF FS-PATH-CAP READ-LINK FMT-LINK-TARGET-U @ T=
   FMT-LINK-READ-BUF FMT-LINK-TARGET-U @ FMT-LINK-TARGET T$=
   ['] FMT-MAKE-SYMLINK-EXISTS E-FS-IO TTHROWS
   ['] FMT-LINK-READ-TOO-SMALL E-FS-CAPACITY TTHROWS
   ['] FMT-READ-LINK-NONLINK E-FS-STAT TTHROWS
   FMT-LINK REMOVE-FILE
   FMT-LINK SYMLINK? TFALSE
   FMT-LINK-TARGET FILE? TTRUE
   FMT-LINK-TARGET REMOVE-FILE
   FMT-LINK-TARGET EXISTS? TFALSE ;

: FMT-TEST-BROKEN-SYMLINK ( -- )
   FMT-BROKEN-TARGET FMT-BROKEN-LINK MAKE-SYMLINK
   FMT-BROKEN-LINK EXISTS? TFALSE
   FMT-BROKEN-LINK SYMLINK? TTRUE
   FMT-BROKEN-LINK FMT-LINK-READ-BUF FS-PATH-CAP READ-LINK FMT-BROKEN-TARGET-U @ T=
   FMT-LINK-READ-BUF FMT-BROKEN-TARGET-U @ FMT-BROKEN-TARGET T$=
   FMT-BROKEN-LINK REMOVE-FILE
   FMT-BROKEN-LINK SYMLINK? TFALSE ;

: FMT-TEST-REMOVE-TREE ( -- )
   FMT-WRITE-TREE
   FMT-TREE-ROOT-FILE FILE? TTRUE
   FMT-TREE-LEAF FILE? TTRUE
   FMT-TREE-DOTS-FILE FILE? TTRUE
   FMT-TREE REMOVE-TREE
   FMT-TREE EXISTS? TFALSE
   FMT-TREE REMOVE-TREE
   s" no-such-habu-fs-remove-tree" REMOVE-TREE ;

: FMT-TEST-REMOVE-TREE-SYMLINK-DIR ( -- )
   FMT-LINK-DIR MAKE-DIR
   FMT-LINK-DIR-FILE s" kept" WRITE-ALL
   FMT-TREE MAKE-DIR
   FMT-LINK-DIR FMT-TREE-DIR-LINK MAKE-SYMLINK
   FMT-TREE-DIR-LINK SYMLINK? TTRUE
   FMT-TREE REMOVE-TREE
   FMT-TREE EXISTS? TFALSE
   FMT-LINK-DIR DIR? TTRUE
   FMT-LINK-DIR-FILE FILE? TTRUE ;

: FMT-TEST-CLEANUP ( -- )
   FMT-WRITE-TREE
   FMT-TREE CLEANUP-TREE+
   FMT-RENAME-DST CLEANUP+
   FMT-CHMOD-PATH CLEANUP+
   FMT-COPY-SRC CLEANUP+
   FMT-COPY-DST CLEANUP+
   FMT-ATOMIC-PATH CLEANUP+
   FMT-MKDIR-PATH CLEANUP-DIR+
   FMT-NEST-A CLEANUP-TREE+
   FMT-LINK-DIR CLEANUP-TREE+
   CLEANUP-RUN
   FMT-COPY-DST EXISTS? TFALSE
   FMT-ATOMIC-PATH EXISTS? TFALSE
   FMT-MKDIR-PATH EXISTS? TFALSE
   FMT-NEST-A EXISTS? TFALSE
   FMT-LINK-DIR EXISTS? TFALSE
   FMT-TREE EXISTS? TFALSE
   FMT-ROOT$ EXISTS? TFALSE
   CLEANUP-RUN ;

: FS-MUTATE-TEST-MAIN ( -- )
   T-RESET
   FMT-PREPARE
   FMT-REMOVE-PATH FILE? TTRUE
   FMT-REMOVE-PATH REMOVE-FILE
   FMT-REMOVE-PATH EXISTS? TFALSE
   FMT-RENAME-SRC FILE? TTRUE
   FMT-RENAME-DST EXISTS? TFALSE
   FMT-RENAME-SRC FMT-RENAME-DST RENAME-FILE
   FMT-RENAME-SRC EXISTS? TFALSE
   FMT-RENAME-DST FILE? TTRUE
   FMT-CHMOD-PATH CHMOD-X
   FMT-CHMOD-PATH STAT-MODE FS-MUT-MODE-EXEC and FS-MUT-MODE-EXEC = TTRUE
   FMT-TEST-COPY
   FMT-TEST-ATOMIC-WRITE
   FMT-TEST-DIRS
   FMT-TEST-TEMPS
   FMT-TEST-SYMLINK
   FMT-TEST-BROKEN-SYMLINK
   ['] FMT-REMOVE-MISSING E-FS-IO TTHROWS
   ['] FMT-RENAME-MISSING E-FS-IO TTHROWS
   ['] FMT-CHMOD-MISSING E-FS-STAT TTHROWS
   ['] FMT-RMDIR-MISSING E-FS-IO TTHROWS
   ['] FMT-MKDIR-EXISTS E-FS-IO TTHROWS
   ['] FMT-COPY-TOO-SMALL E-FS-CAPACITY TTHROWS
   ['] FMT-REMOVE-TREE-EMPTY E-FS-PATH TTHROWS
   FMT-TEST-REMOVE-TREE
   FMT-TEST-REMOVE-TREE-SYMLINK-DIR
   FMT-TEST-CLEANUP
   T-REPORT
   s" fs-mutate-test: ok" type cr ;

FS-MUTATE-TEST-MAIN
