\ fs-mutate-test.f - focused tests for lib/fs-mutate.f.
\ Run: bin/hb --load lib/errors.f lib/string.f lib/test.f lib/fs.f lib/fs-mutate.f lib/fs-mutate-test.f

variable FMT-ROOT-U
variable FMT-REMOVE-U
variable FMT-RENAME-SRC-U
variable FMT-RENAME-DST-U
variable FMT-CHMOD-U
variable FMT-COPY-SRC-U
variable FMT-COPY-DST-U
variable FMT-ATOMIC-U
variable FMT-MKDIR-U
variable FMT-NEST-A-U
variable FMT-NEST-B-U
variable FMT-NEST-C-U

create FMT-ROOT-BUF FS-PATH-CAP allot
create FMT-REMOVE-BUF FS-PATH-CAP allot
create FMT-RENAME-SRC-BUF FS-PATH-CAP allot
create FMT-RENAME-DST-BUF FS-PATH-CAP allot
create FMT-CHMOD-BUF FS-PATH-CAP allot
create FMT-COPY-SRC-BUF FS-PATH-CAP allot
create FMT-COPY-DST-BUF FS-PATH-CAP allot
create FMT-ATOMIC-BUF FS-PATH-CAP allot
create FMT-MKDIR-BUF FS-PATH-CAP allot
create FMT-NEST-A-BUF FS-PATH-CAP allot
create FMT-NEST-B-BUF FS-PATH-CAP allot
create FMT-NEST-C-BUF FS-PATH-CAP allot

: FMT-ROOT$ ( -- ptr u8 n )
   FMT-ROOT-BUF FMT-ROOT-U @ ;

: FMT-REMOVE-PATH ( -- ptr u8 n )
   FMT-REMOVE-BUF FMT-REMOVE-U @ ;

: FMT-RENAME-SRC ( -- ptr u8 n )
   FMT-RENAME-SRC-BUF FMT-RENAME-SRC-U @ ;

: FMT-RENAME-DST ( -- ptr u8 n )
   FMT-RENAME-DST-BUF FMT-RENAME-DST-U @ ;

: FMT-CHMOD-PATH ( -- ptr u8 n )
   FMT-CHMOD-BUF FMT-CHMOD-U @ ;

: FMT-COPY-SRC ( -- ptr u8 n )
   FMT-COPY-SRC-BUF FMT-COPY-SRC-U @ ;

: FMT-COPY-DST ( -- ptr u8 n )
   FMT-COPY-DST-BUF FMT-COPY-DST-U @ ;

: FMT-ATOMIC-PATH ( -- ptr u8 n )
   FMT-ATOMIC-BUF FMT-ATOMIC-U @ ;

: FMT-MKDIR-PATH ( -- ptr u8 n )
   FMT-MKDIR-BUF FMT-MKDIR-U @ ;

: FMT-NEST-A ( -- ptr u8 n )
   FMT-NEST-A-BUF FMT-NEST-A-U @ ;

: FMT-NEST-B ( -- ptr u8 n )
   FMT-NEST-B-BUF FMT-NEST-B-U @ ;

: FMT-NEST-C ( -- ptr u8 n )
   FMT-NEST-C-BUF FMT-NEST-C-U @ ;

: FMT-TEMP-BASE ( -- ptr u8 n )
   FMT-ROOT$ ;

: FMT-ROOT! ( -- )
   s" habu-fs-mutate" TMPDIR-MKDIR {: a:ptr u :}
   a FMT-ROOT-BUF u BYTE-COPY
   u FMT-ROOT-U ! ;

: FMT-REMOVE! ( -- )
   FMT-ROOT$ s" remove.txt" FMT-REMOVE-BUF JOIN-PATH FMT-REMOVE-U ! ;

: FMT-RENAME-SRC! ( -- )
   FMT-ROOT$ s" rename-src.txt" FMT-RENAME-SRC-BUF JOIN-PATH FMT-RENAME-SRC-U ! ;

: FMT-RENAME-DST! ( -- )
   FMT-ROOT$ s" rename-dst.txt" FMT-RENAME-DST-BUF JOIN-PATH FMT-RENAME-DST-U ! ;

: FMT-CHMOD! ( -- )
   FMT-ROOT$ s" chmod.txt" FMT-CHMOD-BUF JOIN-PATH FMT-CHMOD-U ! ;

: FMT-COPY-SRC! ( -- )
   FMT-ROOT$ s" copy-src.txt" FMT-COPY-SRC-BUF JOIN-PATH FMT-COPY-SRC-U ! ;

: FMT-COPY-DST! ( -- )
   FMT-ROOT$ s" copy-dst.txt" FMT-COPY-DST-BUF JOIN-PATH FMT-COPY-DST-U ! ;

: FMT-ATOMIC! ( -- )
   FMT-ROOT$ s" atomic.txt" FMT-ATOMIC-BUF JOIN-PATH FMT-ATOMIC-U ! ;

: FMT-MKDIR! ( -- )
   FMT-ROOT$ s" mkdir-one" FMT-MKDIR-BUF JOIN-PATH FMT-MKDIR-U ! ;

: FMT-NEST-A! ( -- )
   FMT-ROOT$ s" nested" FMT-NEST-A-BUF JOIN-PATH FMT-NEST-A-U ! ;

: FMT-NEST-B! ( -- )
   FMT-NEST-A s" child" FMT-NEST-B-BUF JOIN-PATH FMT-NEST-B-U ! ;

: FMT-NEST-C! ( -- )
   FMT-NEST-B s" grand" FMT-NEST-C-BUF JOIN-PATH FMT-NEST-C-U ! ;

: FMT-PATHS! ( -- )
   FMT-ROOT!
   FMT-REMOVE!
   FMT-RENAME-SRC!
   FMT-RENAME-DST!
   FMT-CHMOD!
   FMT-COPY-SRC!
   FMT-COPY-DST!
   FMT-ATOMIC!
   FMT-MKDIR!
   FMT-NEST-A!
   FMT-NEST-B!
   FMT-NEST-C! ;

: FMT-WRITE-FIXTURES ( -- )
   FMT-REMOVE-PATH s" delete-me" WRITE-ALL
   FMT-RENAME-SRC s" rename-me" WRITE-ALL
   FMT-CHMOD-PATH s" #!/bin/sh\nexit 0\n" WRITE-ALL
   FMT-COPY-SRC s" copy-src" WRITE-ALL ;

: FMT-PREPARE ( -- )
   CLEANUP-RESET
   FMT-PATHS!
   FMT-ROOT$ CLEANUP-DIR+
   FMT-WRITE-FIXTURES ;

: FMT-REMOVE-MISSING ( -- )
   s" no-such-habu-fs-remove-file" REMOVE-FILE ;

: FMT-RENAME-MISSING ( -- )
   s" no-such-habu-fs-rename-file" FMT-RENAME-DST RENAME-FILE ;

: FMT-CHMOD-MISSING ( -- )
   s" no-such-habu-fs-chmod-file" CHMOD-X ;

: FMT-RMDIR-MISSING ( -- )
   s" no-such-habu-fs-rmdir" REMOVE-DIR ;

: FMT-MKDIR-EXISTS ( -- )
   FMT-MKDIR-PATH MAKE-DIR ;

: FMT-COPY-TOO-SMALL ( -- )
   FMT-COPY-SRC FMT-COPY-DST 3 COPY-FILE ;

create FMT-READ-BUF 64 allot

: FMT-TEST-COPY ( -- )
   FMT-COPY-SRC FMT-COPY-DST 64 COPY-FILE
   FMT-COPY-DST FILE? TTRUE
   FMT-COPY-DST FMT-READ-BUF 64 READ-ALL 8 T=
   FMT-READ-BUF 8 s" copy-src" T$= ;

: FMT-TEST-ATOMIC-WRITE ( -- )
   FMT-ATOMIC-PATH s" old" WRITE-ALL
   FMT-ATOMIC-PATH s" new-data" ATOMIC-WRITE-FILE
   FMT-ATOMIC-PATH FMT-READ-BUF 64 READ-ALL 8 T=
   FMT-READ-BUF 8 s" new-data" T$= ;

: FMT-TEST-DIRS ( -- )
   FMT-MKDIR-PATH MAKE-DIR
   FMT-MKDIR-PATH DIR? TTRUE
   FMT-NEST-C MAKE-DIRS
   FMT-NEST-A DIR? TTRUE
   FMT-NEST-B DIR? TTRUE
   FMT-NEST-C DIR? TTRUE ;

: FMT-TEST-TEMPS ( -- )
   FMT-TEMP-BASE s" one" MAKE-TEMP-DIR 2dup DIR? TTRUE CLEANUP-DIR+
   FMT-TEMP-BASE s" two" MAKE-TEMP-DIR 2dup DIR? TTRUE CLEANUP-DIR+
   s" habu-fs-mut" TMPDIR-MKDIR 2dup DIR? TTRUE CLEANUP-DIR+ ;

: FMT-TEST-CLEANUP ( -- )
   FMT-RENAME-DST CLEANUP+
   FMT-CHMOD-PATH CLEANUP+
   FMT-COPY-SRC CLEANUP+
   FMT-COPY-DST CLEANUP+
   FMT-ATOMIC-PATH CLEANUP+
   FMT-MKDIR-PATH CLEANUP-DIR+
   FMT-NEST-A CLEANUP-DIR+
   FMT-NEST-B CLEANUP-DIR+
   FMT-NEST-C CLEANUP-DIR+
   CLEANUP-RUN
   FMT-COPY-DST EXISTS? TFALSE
   FMT-ATOMIC-PATH EXISTS? TFALSE
   FMT-MKDIR-PATH EXISTS? TFALSE
   FMT-NEST-A EXISTS? TFALSE
   FMT-ROOT$ EXISTS? TFALSE
   CLEANUP-RUN ;

: FS-MUTATE-TEST-MAIN ( -- )
   T-RESET
   FMT-PREPARE
   FMT-REMOVE-PATH FILE? TTRUE
   FMT-REMOVE-PATH REMOVE-FILE
   FMT-REMOVE-PATH EXISTS? TFALSE
   FMT-RENAME-SRC FILE? TTRUE
   FMT-RENAME-DST EXISTS? TFALSE
   FMT-RENAME-SRC FMT-RENAME-DST RENAME-FILE
   FMT-RENAME-SRC EXISTS? TFALSE
   FMT-RENAME-DST FILE? TTRUE
   FMT-CHMOD-PATH CHMOD-X
   FMT-CHMOD-PATH STAT-MODE FS-MUT-MODE-EXEC and FS-MUT-MODE-EXEC = TTRUE
   FMT-TEST-COPY
   FMT-TEST-ATOMIC-WRITE
   FMT-TEST-DIRS
   FMT-TEST-TEMPS
   ['] FMT-REMOVE-MISSING E-FS-IO TTHROWS
   ['] FMT-RENAME-MISSING E-FS-IO TTHROWS
   ['] FMT-CHMOD-MISSING E-FS-STAT TTHROWS
   ['] FMT-RMDIR-MISSING E-FS-IO TTHROWS
   ['] FMT-MKDIR-EXISTS E-FS-IO TTHROWS
   ['] FMT-COPY-TOO-SMALL E-FS-CAPACITY TTHROWS
   FMT-TEST-CLEANUP
   T-REPORT
   s" fs-mutate-test: ok" type cr ;

FS-MUTATE-TEST-MAIN
