\ map-test.f - focused tests for fixed-capacity map layout helpers.
\ Run: cat lib/errors.f lib/map.f lib/map-test.f | bin/hb

1 constant MT-EX-FAIL
8 constant MT-CAP

variable MT-CASE
variable MT-FAIL

create MT-MAP MT-CAP MAP-CELLS cells allot
create MT-KEY 97 c, 98 c, 99 c,

: MT-ASSERT ( bool -- )
   MT-CASE @ 1 + MT-CASE !
   0= if
      s" map-test: assertion " type MT-CASE @ . s" failed" type cr
      MT-FAIL @ 1 + MT-FAIL !
   then ;

: MT= ( n n -- )
   = MT-ASSERT ;

: MT-RANGE ( n n -- ) {: ix cap :}
   ix 0 >= ix cap < and MT-ASSERT ;

: MT-FILL-STORAGE ( -- )
   MT-CAP MAP-CELLS 0 ?do
      777 MT-MAP i cells + !
   loop ;

: MT-ASSERT-CLEAR-SLOT ( n -- ) {: ix :}
   MT-MAP ix MAP-SLOT-STATE@ MAP-EMPTY MT=
   MT-MAP ix MAP-SLOT-HASH@ 0 MT=
   MT-MAP ix MAP-SLOT-KEY-A@ NULL$ drop = MT-ASSERT
   MT-MAP ix MAP-SLOT-KEY-U@ 0 MT=
   MT-MAP ix MAP-SLOT-VALUE@ 0 MT= ;

: MT-BAD-CAP-ZERO ( -- )
   0 MAP-CHECK-CAP ;

: MT-BAD-CAP-NEG ( -- )
   -1 MAP-CHECK-CAP ;

: MT-GOOD-CAP ( -- )
   1 MAP-CHECK-CAP ;

: MT-BAD-COUNT-NEG ( -- )
   MT-MAP MT-CAP MAP-INIT
   -1 MT-MAP MAP-COUNT! ;

: MT-BAD-COUNT-HIGH ( -- )
   MT-MAP MT-CAP MAP-INIT
   MT-CAP 1 + MT-MAP MAP-COUNT! ;

: MT-BAD-COUNT-SUM ( -- )
   MT-MAP MT-CAP MAP-INIT
   MT-CAP 1 - MT-MAP MAP-DELETED!
   2 MT-MAP MAP-COUNT! ;

: MT-BAD-DELETED-NEG ( -- )
   MT-MAP MT-CAP MAP-INIT
   -1 MT-MAP MAP-DELETED! ;

: MT-BAD-DELETED-HIGH ( -- )
   MT-MAP MT-CAP MAP-INIT
   MT-CAP 1 + MT-MAP MAP-DELETED! ;

: MT-BAD-DELETED-SUM ( -- )
   MT-MAP MT-CAP MAP-INIT
   MT-CAP 1 - MT-MAP MAP-COUNT!
   2 MT-MAP MAP-DELETED! ;

: MT-BAD-INDEX-NEG ( -- )
   MT-MAP -1 MAP-CHECK-INDEX ;

: MT-BAD-INDEX-HIGH ( -- )
   MT-MAP MT-CAP MAP-CHECK-INDEX ;

: MT-BAD-FIELD-HIGH ( -- )
   MT-MAP 0 MAP-SLOT-CELLS MAP-SLOT-FIELD drop ;

: MT-BAD-STATE ( -- )
   99 MT-MAP 0 MAP-SLOT-STATE! ;

: MT-BAD-HASH ( -- )
   -1 MT-MAP 0 MAP-SLOT-HASH! ;

: MT-BAD-KEY-U ( -- )
   -1 MT-MAP 0 MAP-SLOT-KEY-U! ;

: MT-TEST-CONSTANTS ( -- )
   MAP-CAP-OFF 0 MT=
   MAP-COUNT-OFF 1 MT=
   MAP-DELETED-OFF 2 MT=
   MAP-HEADER-CELLS 3 MT=
   MAP-SLOT-STATE-OFF 0 MT=
   MAP-SLOT-HASH-OFF 1 MT=
   MAP-SLOT-KEY-A-OFF 2 MT=
   MAP-SLOT-KEY-U-OFF 3 MT=
   MAP-SLOT-VALUE-OFF 4 MT=
   MAP-SLOT-CELLS 5 MT=
   MAP-EMPTY MAP-EMPTY? MT-ASSERT
   MAP-DELETED MAP-DELETED? MT-ASSERT
   MAP-OCCUPIED MAP-OCCUPIED? MT-ASSERT
   MAP-EMPTY MAP-DELETED? 0= MT-ASSERT
   MAP-DELETED MAP-OCCUPIED? 0= MT-ASSERT ;

: MT-TEST-CHECKS ( -- )
   ['] MT-GOOD-CAP catch 0 MT=
   ['] MT-BAD-CAP-ZERO catch E-MAP-BAD-CAP MT=
   ['] MT-BAD-CAP-NEG catch E-MAP-BAD-CAP MT=
   MT-MAP MT-CAP MAP-INIT
   MT-CAP MT-MAP MAP-COUNT!  MT-MAP MAP-COUNT@ MT-CAP MT=
   0 MT-MAP MAP-COUNT!
   MT-CAP MT-MAP MAP-DELETED!  MT-MAP MAP-DELETED@ MT-CAP MT=
   ['] MT-BAD-COUNT-NEG catch E-MAP-BAD-CAP MT=
   ['] MT-BAD-COUNT-HIGH catch E-MAP-FULL MT=
   ['] MT-BAD-COUNT-SUM catch E-MAP-FULL MT=
   ['] MT-BAD-DELETED-NEG catch E-MAP-BAD-CAP MT=
   ['] MT-BAD-DELETED-HIGH catch E-MAP-FULL MT=
   ['] MT-BAD-DELETED-SUM catch E-MAP-FULL MT=
   MT-MAP 0 MAP-CHECK-INDEX
   MT-MAP MT-CAP 1 - MAP-CHECK-INDEX
   ['] MT-BAD-INDEX-NEG catch E-MAP-BAD-CAP MT=
   ['] MT-BAD-INDEX-HIGH catch E-MAP-BAD-CAP MT=
   ['] MT-BAD-FIELD-HIGH catch E-MAP-BAD-CAP MT=
   ['] MT-BAD-STATE catch E-MAP-BAD-CAP MT=
   ['] MT-BAD-HASH catch E-MAP-BAD-CAP MT=
   ['] MT-BAD-KEY-U catch E-MAP-BAD-CAP MT= ;

: MT-TEST-LAYOUT ( -- )
   MT-CAP MAP-CELLS MAP-HEADER-CELLS MT-CAP MAP-SLOT-CELLS * + MT=
   MT-MAP MT-CAP MAP-INIT
   MT-MAP MAP-CAP@ MT-CAP MT=
   MT-MAP MAP-COUNT@ 0 MT=
   MT-MAP MAP-DELETED@ 0 MT=
   MT-MAP MAP-SLOTS MT-MAP MAP-HEADER-CELLS cells + = MT-ASSERT
   MT-MAP 0 MAP-SLOT MT-MAP MAP-SLOTS = MT-ASSERT
   MT-MAP 1 MAP-SLOT MT-MAP MAP-SLOTS MAP-SLOT-CELLS cells + = MT-ASSERT
   MT-MAP 2 MAP-SLOT-STATE-OFF MAP-SLOT-FIELD MT-MAP 2 MAP-SLOT = MT-ASSERT
   MT-MAP 2 MAP-SLOT-VALUE-OFF MAP-SLOT-FIELD
      MT-MAP 2 MAP-SLOT 4 cells + = MT-ASSERT ;

: MT-TEST-SLOT-FIELDS ( -- )
   MT-MAP MT-CAP MAP-INIT
   MAP-DELETED MT-MAP 2 MAP-SLOT-STATE!
   12345 MT-MAP 2 MAP-SLOT-HASH!
   MT-KEY MT-MAP 2 MAP-SLOT-KEY-A!
   3 MT-MAP 2 MAP-SLOT-KEY-U!
   99 MT-MAP 2 MAP-SLOT-VALUE!
   MT-MAP 2 MAP-SLOT-STATE@ MAP-DELETED MT=
   MT-MAP 2 MAP-SLOT-HASH@ 12345 MT=
   MT-MAP 2 MAP-SLOT-KEY-A@ MT-KEY = MT-ASSERT
   MT-MAP 2 MAP-SLOT-KEY-U@ 3 MT=
   MT-MAP 2 MAP-SLOT-VALUE@ 99 MT=
   MT-MAP 2 MAP-SLOT-CLEAR
   2 MT-ASSERT-CLEAR-SLOT ;

: MT-TEST-INIT-CLEAR ( -- )
   MT-FILL-STORAGE
   MT-MAP MT-CAP MAP-INIT
   MT-MAP MAP-CAP@ MT-CAP MT=
   MT-MAP MAP-COUNT@ 0 MT=
   MT-MAP MAP-DELETED@ 0 MT=
   MT-CAP 0 ?do i MT-ASSERT-CLEAR-SLOT loop
   MAP-OCCUPIED MT-MAP 3 MAP-SLOT-STATE!
   88 MT-MAP 3 MAP-SLOT-VALUE!
   4 MT-MAP MAP-COUNT!
   2 MT-MAP MAP-DELETED!
   MT-MAP MAP-CLEAR
   MT-MAP MAP-COUNT@ 0 MT=
   MT-MAP MAP-DELETED@ 0 MT=
   MT-CAP 0 ?do i MT-ASSERT-CLEAR-SLOT loop ;

: MT-PROBE-RANGE ( ptr u8 n n n -- ) {: a:ptr u step cap :}
   a u MAP-HASH step cap MAP-PROBE cap MT-RANGE ;

: MT-TEST-HASH-PROBE ( -- )
   s" " MAP-HASH MAP-HASH-SEED MT=
   s" alpha" MAP-HASH s" alpha" MAP-HASH MT=
   s" alpha" MAP-HASH 0 >= MT-ASSERT
   s" beta" MAP-HASH MT-CAP MAP-INDEX MT-CAP MT-RANGE
   -1 MT-CAP MAP-INDEX MT-CAP 1 - MT=
   s" alpha" 0 MT-CAP MT-PROBE-RANGE
   s" alpha" 1 MT-CAP MT-PROBE-RANGE
   s" alpha" MT-CAP MT-CAP MT-PROBE-RANGE
   s" alpha" -1 MT-CAP MT-PROBE-RANGE ;

: MT-REPORT ( -- )
   MT-FAIL @ 0= if s" map-test: ok" type cr exit then
   MT-FAIL @ . s" map-test: failures" type cr
   s" map-test: failures" MT-EX-FAIL die ;

: MT-MAIN ( -- )
   MT-TEST-CONSTANTS
   MT-TEST-CHECKS
   MT-TEST-LAYOUT
   MT-TEST-SLOT-FIELDS
   MT-TEST-INIT-CLEAR
   MT-TEST-HASH-PROBE
   MT-REPORT ;

MT-MAIN
