\ memory-test.f - focused tests for OS-backed memory buffers.

64 constant MEMT-BUFS
16 constant MEMT-SPAN-BUFS
32 constant MEMT-SPANS
65 constant MEMT-MARK-A
90 constant MEMT-MARK-Z

variable MEMT-HERE

: MEMT-TOTAL ( -- n )
   MEMT-BUFS MEM-64K * ;

: MEMT-SPAN-TOTAL ( -- n )
   MEMT-SPAN-BUFS MEM-64K * ;

: MEMT-ZERO-BYTES ( -- )
   0 MEM-ALLOC-BYTES 2drop ;

: MEMT-NEG-BYTES ( -- )
   -1 MEM-ALLOC-BYTES 2drop ;

: MEMT-ZERO-64K ( -- )
   0 MEM-ALLOC-64K-BUFFERS 2drop ;

: MEMT-TOO-MANY-64K ( -- )
   MEM-MAX-64K-BUFFERS 1 + MEM-64K-BYTES drop ;

: MEMT-TOO-LARGE-SPAN ( -- )
   MEM-MAX-N MEM-ALLOC-64K-SPAN 2drop ;

: MEMT-ZERO-CELLS ( -- )
   0 >COUNT MEM-ALLOC-CELLS drop ;

: MEMT-TOO-MANY-CELLS ( -- )
   MEM-MAX-CELLS 1 + >COUNT MEM-CELLS>BYTES drop ;

: MEMT-END ( ptr u8 n -- ptr u8 ) {: a:ptr u :}
   a u 1 - + ;

: MEMT-TOUCH-ENDS ( ptr u8 n -- ) {: a:ptr u :}
   MEMT-MARK-A a c!
   MEMT-MARK-Z a u MEMT-END c!
   a c@ MEMT-MARK-A T=
   a u MEMT-END c@ MEMT-MARK-Z T= ;

: MEMT-TOUCH-SLOTS ( ptr u8 n n -- ) {: a:ptr u count :}
   count MEM-64K * u T=
   count 0 ?do
      MEMT-MARK-A i + a i MEM-64K * + c!
      a i MEM-64K * + c@ MEMT-MARK-A i + T=
   loop ;

: MEMT-TOUCH-64K-SLOTS ( ptr u8 n -- )
   MEMT-BUFS MEMT-TOUCH-SLOTS ;

: MEMT-TOUCH-SPAN-SLOTS ( ptr u8 n -- )
   MEMT-SPAN-BUFS MEMT-TOUCH-SLOTS ;

: MEMT-CELL-SPAN ( -- )
   4 >COUNT MEM-ALLOC-CELLS {: a:ptr :}
   111 a !
   222 a 1 cells + !
   a @ 111 T=
   a 1 cells + @ 222 T= ;

: MEMT-SINGLE-64K ( -- )
   MEM-ALLOC-64K
   dup MEM-64K T=
   MEMT-TOUCH-ENDS ;

: MEMT-MANY-64K ( -- )
   MEMT-BUFS MEM-ALLOC-64K-BUFFERS
   MEMT-TOUCH-64K-SLOTS ;

: MEMT-DATA-UNCHANGED ( -- )
   here data-base - MEMT-HERE !
   MEM-ALLOC-64K 2drop
   here data-base - MEMT-HERE @ T= ;

: MEMT-LIVE-SPAN-FRAME ( ptr u8 n n -- ) {: a:ptr u remaining :}
   u MEMT-SPAN-TOTAL T=
   a u MEMT-TOUCH-SPAN-SLOTS
   remaining 0 > if
      MEMT-SPAN-BUFS MEM-ALLOC-64K-BUFFERS
      remaining 1 - recurse
   then
   a u MEMT-TOUCH-SPAN-SLOTS ;

: MEMT-MANY-LIVE-SPANS ( -- )
   here data-base - MEMT-HERE !
   MEMT-SPAN-BUFS MEM-ALLOC-64K-BUFFERS
   MEMT-SPANS 1 - MEMT-LIVE-SPAN-FRAME
   here data-base - MEMT-HERE @ T= ;

T-RESET
MEM-64K $10000 T=
1 MEM-64K-BYTES MEM-64K T=
1 MEM-64K-COUNT-FOR 1 T=
MEM-64K MEM-64K-COUNT-FOR 1 T=
MEM-64K 1 + MEM-64K-COUNT-FOR 2 T=
MEM-CELL-BYTES 1 cells T=
1 >COUNT MEM-CELLS>BYTES MEM-CELL-BYTES T=
1 MEM-64K-SPAN-BYTES MEM-64K T=
MEM-64K 1 + MEM-64K-SPAN-BYTES MEM-64K 2 * T=
MEMT-CELL-SPAN
MEMT-SINGLE-64K
MEMT-MANY-64K
MEMT-DATA-UNCHANGED
MEMT-MANY-LIVE-SPANS
' MEMT-ZERO-BYTES E-MEM-SIZE TTHROWS
' MEMT-NEG-BYTES E-MEM-SIZE TTHROWS
' MEMT-ZERO-64K E-MEM-SIZE TTHROWS
' MEMT-TOO-MANY-64K E-MEM-SIZE TTHROWS
' MEMT-TOO-LARGE-SPAN E-MEM-SIZE TTHROWS
' MEMT-ZERO-CELLS E-MEM-SIZE TTHROWS
' MEMT-TOO-MANY-CELLS E-MEM-SIZE TTHROWS
T-REPORT
s" memory-test: ok" type cr
