\ property-test.f - focused tests for property helper library.
\ Run: cat lib/errors.f lib/test.f lib/property.f lib/property-test.f | bin/hb

: PT-BAD-SEED ( -- )
   -1 1 PROP-RUN-RESET ;

: PT-BAD-COUNT ( -- )
   1 PROP-MAX-COUNT 1+ PROP-RUN-RESET ;

: PT-ZERO-MOD ( -- )
   0 PROP-RND% drop ;

: PT-BAD-ROOM ( -- )
   PROP-BUF-CAP 1+ PROP-BUF-CHECK-ROOM ;

: PT-BAD-DIGIT ( -- )
   10 PROP-DIGIT+ ;

: PT-BAD-STEP ( -- )
   0 PROP-GEN-START
   s" drop " 1 -1 PROP-GEN-STEP ;

: PT-SHRINK-KEEP? ( -- bool )
   PROP-BUF$ nip 4 >= ;

: PT-SHRINK-FALSE? ( -- bool )
   0 0= 0= ;

: PT-BAD-SHRINK ( -- )
   PROP-BUF-RESET
   s" x " PROP-BUF+
   [: PT-SHRINK-FALSE? ;] PROP-SHRINK ;

: PT-EXAMPLE-PROP ( -- )
   7 16 PROP-RUN-RESET
   0 begin dup PROP-COUNT@ < while
      100 PROP-RND% dup * 0 >= TTRUE
      1+
   repeat drop ;

T-RESET

PROP-DEFAULTS PROP-DEFAULT-COUNT T= PROP-DEFAULT-SEED T=
1 5 PROP-RUN-RESET
PROP-SEED@ 1 T=
PROP-COUNT@ 5 T=
PROP-RND 1103527590 T=
PROP-SEED@ 1103527590 T=

1 PROP-SEED!
10 PROP-RND% 0 T=
8 PROP-RND% 7 T=

PROP-BUF-RESET
65 PROP-BUF-C+
7 PROP-DIGIT+
PROP-BUF$ s" A7" T$=

PROP-BUF-RESET
s" abc   " PROP-BUF+
PROP-TRIM-TRAIL
PROP-BUF$ s" abc" T$=

PROP-BUF-RESET
s" abc def " PROP-BUF+
PROP-DROP-LAST TTRUE
PROP-BUF$ s" abc " T$=

0 PROP-GEN-START
s" 7 " 0 1 PROP-GEN-STEP
s" drop " 1 -1 PROP-GEN-STEP
PROP-GEN-DEPTH@ 0 T=
PROP-BUF$ s" 7 drop " T$=

PROP-BUF-RESET
s" dup drop 1+ " PROP-BUF+
' PT-SHRINK-KEEP? PROP-SHRINK
PROP-BUF$ s" dup " T$=

' PT-BAD-SEED E-PROP-SEED TTHROWS
' PT-BAD-COUNT E-PROP-SEED TTHROWS
' PT-ZERO-MOD E-PROP-GENERATOR TTHROWS
' PT-BAD-ROOM E-PROP-CAPACITY TTHROWS
' PT-BAD-DIGIT E-PROP-GENERATOR TTHROWS
' PT-BAD-STEP E-PROP-GENERATOR TTHROWS
' PT-BAD-SHRINK E-PROP-SHRINK TTHROWS

PT-EXAMPLE-PROP

T-REPORT
