\ task-test.f - CPU tasking smoke, isolation, and exit fixtures.

require lib/errors.f
require lib/string.f
require lib/test.f
require lib/process.f
require lib/process-argv.f
require lib/task.f

package TASK-TEST

: TASK-TEST-ALIGN8 ( -- )
   here P>N 7 and 8 swap - 7 and allot ;

TASK-TEST-ALIGN8
variable TASK-COUNT
variable TASK-READY-CELL
variable TASK-SELF-A
variable TASK-SELF-B

TASK:#USER
CELL TASK:+USER TASK-USER-CELL
CELL TASK:+USER TASK-LOCAL-ID
CELL TASK:+USER TASK-LOCAL-FFI
drop

TASK:MIN-STACK TASK:TASK WORKER-A
TASK:MIN-STACK TASK:TASK WORKER-B
TASK:MIN-STACK TASK:TASK ODIN-ACQ0
TASK:MIN-STACK TASK:TASK ODIN-ACQ1
TASK:MIN-STACK TASK:TASK ODIN-ACQ2
TASK:MIN-STACK TASK:TASK ODIN-ACQ3
TASK:MIN-STACK TASK:TASK ODIN-DET
TASK:FACILITY TASK-LOCK
TASK:FACILITY ODIN-LOCK

$4000 constant TASK-CAP
$1388 constant TASK-CAPTURE-MS
$4F constant TASK-LIVE-RC
$62 constant TASK-DIE-RC
E-TASK-STATE $FF and constant TASK-THROW-RC
8 constant ODIN-CYCLES
16 constant ODIN-ITERS
4 constant ODIN-ACQ-WANT
ODIN-ITERS 10 * 5 + constant ODIN-FFI-WANT
ODIN-ITERS 10 * 100 + constant ODIN-SHARED-WANT

create TASK-OUT TASK-CAP allot
create TASK-ERR TASK-CAP allot
create TASK-SYM-STRLEN $73 c, $74 c, $72 c, $6C c, $65 c, $6E c, 0 c,
create TASK-LIBC $6C c, $69 c, $62 c, $63 c, $2E c, $73 c, $6F c, $2E c, $36 c, 0 c,
create TASK-LIBSYSTEM
   $2F c, $75 c, $73 c, $72 c, $2F c, $6C c, $69 c, $62 c, $2F c,
   $6C c, $69 c, $62 c, $53 c, $79 c, $73 c, $74 c, $65 c, $6D c,
   $2E c, $42 c, $2E c, $64 c, $79 c, $6C c, $69 c, $62 c, 0 c,
create ODIN-CSTR1 $61 c, 0 c,
create ODIN-CSTR2 $61 c, $62 c, 0 c,
create ODIN-CSTR3 $61 c, $62 c, $63 c, 0 c,
create ODIN-CSTR4 $61 c, $62 c, $63 c, $64 c, 0 c,
create ODIN-CSTR5 $61 c, $62 c, $63 c, $64 c, $65 c, 0 c,

variable TASK-STRLEN-XT
variable ODIN-ACQ-DONE
variable ODIN-DET-DONE
variable ODIN-SHARED
variable ODIN-FFI-TOTAL
variable ODIN-BAD

: TASK-WAIT-READY ( n -- ) {: want:n :}
   begin TASK-READY-CELL atomic@ want < while TASK:PAUSE repeat ;

: TASK-INC-LOCKED ( -- )
   TASK-LOCK TASK:GET
   1 TASK-COUNT atomic-add drop
   TASK-LOCK TASK:RELEASE ;

: TASK-TEST-FACILITY-SWIFT ( -- )
   TASK-LOCK TASK:RELEASE
   TASK-LOCK TASK:GET
   TASK-LOCK TASK:GET
   TASK-LOCK TASK:RELEASE
   TASK-LOCK TASK:RELEASE ;

: TASK-WORK-A ( -- )
   11 TASK-USER-CELL !
   TASK:SELF-N TASK-SELF-A !
   TASK-INC-LOCKED
   1 TASK-READY-CELL atomic-add drop ;

: TASK-WORK-B ( -- )
   22 TASK-USER-CELL !
   TASK:SELF-N TASK-SELF-B !
   TASK-INC-LOCKED
   1 TASK-READY-CELL atomic-add drop ;

: TASK-PAUSER ( -- )
   begin TASK:PAUSE again ;

: TASK-LF ( -- )
   $0A SB-APPEND-C ;

: TASK-DQ ( -- )
   $22 SB-APPEND-C ;

: TASK-LIB-PATH ( -- ptr u8 )
   HB-TARGET-MACOS? if TASK-LIBSYSTEM exit then
   TASK-LIBC ;

: TASK-STRLEN-READY ( -- )
   TASK-STRLEN-XT @ 0= 0= if exit then
   TASK-LIB-PATH RTLD-NOW DLOPEN dup 0= if E-TASK-DLOPEN throw then
   TASK-SYM-STRLEN DLSYM dup 0= if E-TASK-DLSYM throw then
   TASK-STRLEN-XT ! ;

: TASK-CSTRLEN ( ptr u8 -- n ) {: cstr:ptr :}
   cstr P>N 0 FFI-ARG!
   TASK:PAUSE
   1 TASK-STRLEN-XT @ FFI-CALLN ;

: ODIN-BAD+ ( -- )
   1 ODIN-BAD atomic-add drop ;

: ODIN-WAIT-CELL ( ptr a n -- ) {: cell:ptr want:n :}
   begin cell atomic@ want < while TASK:PAUSE repeat ;

: ODIN-WAIT-DONE ( ptr a -- ) {: tcb:ptr :}
   begin tcb TASK:DONE? 0= while TASK:PAUSE repeat ;

: ODIN-SHARED+ ( n -- ) {: v:n :}
   ODIN-LOCK TASK:GET
   ODIN-SHARED @ v + ODIN-SHARED !
   ODIN-LOCK TASK:RELEASE ;

: ODIN-ACQ-WORK ( n ptr u8 n -- ) {: id:n cstr:ptr want:n :}
   id TASK-LOCAL-ID !
   0 TASK-LOCAL-FFI !
   ODIN-ITERS 0 ?do
      id TASK-LOCAL-ID !
      cstr TASK-CSTRLEN dup TASK-LOCAL-FFI !
      dup want <> if ODIN-BAD+ then
      ODIN-FFI-TOTAL atomic-add drop
      TASK-LOCAL-ID @ id <> if ODIN-BAD+ then
      id 1 + ODIN-SHARED+
   loop
   1 ODIN-ACQ-DONE atomic-add drop ;

: ODIN-ACQ0-WORK ( -- )
   0 ODIN-CSTR1 1 ODIN-ACQ-WORK ;

: ODIN-ACQ1-WORK ( -- )
   1 ODIN-CSTR2 2 ODIN-ACQ-WORK ;

: ODIN-ACQ2-WORK ( -- )
   2 ODIN-CSTR3 3 ODIN-ACQ-WORK ;

: ODIN-ACQ3-WORK ( -- )
   3 ODIN-CSTR4 4 ODIN-ACQ-WORK ;

: ODIN-DET-WORK ( -- )
   $63 TASK-LOCAL-ID !
   ODIN-ACQ-DONE ODIN-ACQ-WANT ODIN-WAIT-CELL
   ODIN-CSTR5 TASK-CSTRLEN dup TASK-LOCAL-FFI !
   dup 5 <> if ODIN-BAD+ then
   ODIN-FFI-TOTAL atomic-add drop
   TASK-LOCAL-ID @ $63 <> if ODIN-BAD+ then
   100 ODIN-SHARED+
   1 ODIN-DET-DONE atomic-add drop ;

: ODIN-RESET ( -- )
   0 ODIN-ACQ-DONE !
   0 ODIN-DET-DONE !
   0 ODIN-SHARED !
   0 ODIN-FFI-TOTAL !
   0 ODIN-BAD ! ;

: ODIN-START ( -- )
   ['] ODIN-ACQ0-WORK ODIN-ACQ0 TASK:ACTIVATE
   ['] ODIN-ACQ1-WORK ODIN-ACQ1 TASK:ACTIVATE
   ['] ODIN-ACQ2-WORK ODIN-ACQ2 TASK:ACTIVATE
   ['] ODIN-ACQ3-WORK ODIN-ACQ3 TASK:ACTIVATE
   ['] ODIN-DET-WORK ODIN-DET TASK:ACTIVATE ;

: ODIN-WAIT ( -- )
   ODIN-ACQ-DONE ODIN-ACQ-WANT ODIN-WAIT-CELL
   ODIN-DET-DONE 1 ODIN-WAIT-CELL
   ODIN-ACQ0 ODIN-WAIT-DONE
   ODIN-ACQ1 ODIN-WAIT-DONE
   ODIN-ACQ2 ODIN-WAIT-DONE
   ODIN-ACQ3 ODIN-WAIT-DONE
   ODIN-DET ODIN-WAIT-DONE ;

: ODIN-CHECK-USERS ( -- )
   ODIN-ACQ0 TASK-LOCAL-ID TASK:HIS @ 0 T=
   ODIN-ACQ1 TASK-LOCAL-ID TASK:HIS @ 1 T=
   ODIN-ACQ2 TASK-LOCAL-ID TASK:HIS @ 2 T=
   ODIN-ACQ3 TASK-LOCAL-ID TASK:HIS @ 3 T=
   ODIN-DET TASK-LOCAL-ID TASK:HIS @ $63 T=
   ODIN-ACQ0 TASK-LOCAL-FFI TASK:HIS @ 1 T=
   ODIN-ACQ1 TASK-LOCAL-FFI TASK:HIS @ 2 T=
   ODIN-ACQ2 TASK-LOCAL-FFI TASK:HIS @ 3 T=
   ODIN-ACQ3 TASK-LOCAL-FFI TASK:HIS @ 4 T=
   ODIN-DET TASK-LOCAL-FFI TASK:HIS @ 5 T= ;

: ODIN-CHECK ( -- )
   ODIN-BAD @ 0 T=
   ODIN-ACQ-DONE @ ODIN-ACQ-WANT T=
   ODIN-DET-DONE @ 1 T=
   ODIN-FFI-TOTAL @ ODIN-FFI-WANT T=
   ODIN-SHARED @ ODIN-SHARED-WANT T=
   ODIN-CHECK-USERS ;

: ODIN-KILL ( -- )
   ODIN-ACQ0 TASK:KILL
   ODIN-ACQ1 TASK:KILL
   ODIN-ACQ2 TASK:KILL
   ODIN-ACQ3 TASK:KILL
   ODIN-DET TASK:KILL ;

: TASK-TEST-ODIN-SOAK ( -- )
   TASK-STRLEN-READY
   ODIN-LOCK TASK:FACILITY-INIT
   ODIN-CYCLES 0 ?do
      ODIN-RESET
      ODIN-START
      ODIN-WAIT
      ODIN-CHECK
      ODIN-KILL
   loop ;

: TASK-LIVE-COMPILE$ ( -- ptr u8 n )
   SB-RESET
   s" require lib/task.f" SB-APPEND TASK-LF
   s" : TASK-GUARD-LOOP ( -- ) begin TASK:PAUSE again ;" SB-APPEND TASK-LF
   s" TASK:MIN-STACK TASK:TASK TASK-GUARD-WORKER" SB-APPEND TASK-LF
   s" ' TASK-GUARD-LOOP TASK-GUARD-WORKER TASK:ACTIVATE" SB-APPEND TASK-LF
   s" variable TASK-GUARD-BAD" SB-APPEND TASK-LF
   SB$ ;

: TASK-DIE$ ( -- ptr u8 n )
   SB-RESET
   s" require lib/task.f" SB-APPEND TASK-LF
   s" : TASK-DIE-WORK ( -- ) s" SB-APPEND TASK-DQ
   $20 SB-APPEND-C
   s" task died" SB-APPEND TASK-DQ
   s"  $62 die ;" SB-APPEND TASK-LF
   s" TASK:MIN-STACK TASK:TASK TASK-DIE-WORKER" SB-APPEND TASK-LF
   s" : TASK-DIE-WAIT ( -- ) begin TASK:PAUSE again ;" SB-APPEND TASK-LF
   s" ' TASK-DIE-WORK TASK-DIE-WORKER TASK:ACTIVATE" SB-APPEND TASK-LF
   s" TASK-DIE-WAIT" SB-APPEND TASK-LF
   SB$ ;

: TASK-THROW$ ( -- ptr u8 n )
   SB-RESET
   s" require lib/task.f" SB-APPEND TASK-LF
   s" : TASK-THROW-WORK ( -- ) E-TASK-STATE throw ;" SB-APPEND TASK-LF
   s" TASK:MIN-STACK TASK:TASK TASK-THROW-WORKER" SB-APPEND TASK-LF
   s" : TASK-THROW-WAIT ( -- ) begin TASK:PAUSE again ;" SB-APPEND TASK-LF
   s" ' TASK-THROW-WORK TASK-THROW-WORKER TASK:ACTIVATE" SB-APPEND TASK-LF
   s" TASK-THROW-WAIT" SB-APPEND TASK-LF
   SB$ ;

: TASK-RUN-STDIN ( ptr u8 n -- len len n n ) {: src:ptr srcu:n :}
   PROC-ARGV-RESET
   s" bin/hb" >LEN src srcu >LEN
   TASK-OUT TASK-CAP >LEN TASK-ERR TASK-CAP >LEN
   TASK-CAPTURE-MS >MS RUN-ARGV-STDIN-CAPTURE-OUTCOME ;

: TASK-TEST-LIVE-COMPILE-GUARD ( -- )
   TASK-LIVE-COMPILE$ TASK-RUN-STDIN {: outu:len erru:len kind:n code:n :}
   outu LEN>N 0 T=
   TASK-ERR erru LEN>N s" variable" T$=
   kind PROC-OUTCOME-EXIT T=
   code TASK-LIVE-RC T= ;

: TASK-EXPECT-FAIL ( ptr u8 n n ptr u8 n -- ) {: src:ptr srcu:n want:n needle:ptr needleu:n :}
   src srcu TASK-RUN-STDIN {: outu:len erru:len kind:n code:n :}
   outu LEN>N 0 T=
   kind PROC-OUTCOME-EXIT T=
   code want T=
   TASK-ERR erru LEN>N needle needleu CONTAINS? TTRUE ;

: TASK-TEST-WORKER-DIE ( -- )
   TASK-DIE$ TASK-DIE-RC s" task died" TASK-EXPECT-FAIL ;

: TASK-TEST-WORKER-THROW ( -- )
   TASK-THROW$ TASK-THROW-RC s" task: unhandled throw" TASK-EXPECT-FAIL ;

: TASK-TEST-RUN ( -- )
   T-RESET
   0 TASK-COUNT !
   0 TASK-READY-CELL !
   0 TASK-SELF-A !
   0 TASK-SELF-B !
   99 TASK-USER-CELL !
   TASK-LOCK TASK:FACILITY-INIT
   TASK-TEST-FACILITY-SWIFT
   ['] TASK-WORK-A WORKER-A TASK:ACTIVATE
   ['] TASK-WORK-B WORKER-B TASK:ACTIVATE
   2 TASK-WAIT-READY
   TASK-USER-CELL @ 99 T=
   WORKER-A TASK-USER-CELL TASK:HIS @ 11 T=
   WORKER-B TASK-USER-CELL TASK:HIS @ 22 T=
   TASK-SELF-A @ WORKER-A P>N T=
   TASK-SELF-B @ WORKER-B P>N T=
   WORKER-A TASK:KILL
   WORKER-B TASK:KILL
   TASK-COUNT @ 2 T=
   TASK-READY-CELL @ 2 T=
   ['] TASK-PAUSER WORKER-A TASK:ACTIVATE
   WORKER-A TASK:HALT
   WORKER-A TASK:KILL
   WORKER-A TASK:DONE? TFALSE
   TASK-TEST-LIVE-COMPILE-GUARD
   TASK-TEST-ODIN-SOAK
   TASK-TEST-WORKER-DIE
   TASK-TEST-WORKER-THROW
   T-REPORT ;

TASK-TEST-RUN

end-package
