\ task-test.f - CPU tasking smoke, isolation, and exit fixtures.

require lib/errors.f
require lib/string.f
require lib/test.f
require lib/process.f
require lib/process-argv.f
require lib/task.f
require lib/test/outcome.f

package TASK-TEST

: TASK-TEST-ALIGN8 ( -- )
   here P>N 7 and 8 swap - 7 and allot ;

TASK-TEST-ALIGN8
variable TASK-COUNT
variable TASK-READY-CELL
variable TASK-SELF-A
variable TASK-SELF-B

TASK:#USER
CELL TASK:+USER TASK-USER-CELL
CELL TASK:+USER TASK-LOCAL-ID
CELL TASK:+USER TASK-LOCAL-FFI
drop

TASK:MIN-STACK TASK:TASK WORKER-A
TASK:MIN-STACK TASK:TASK WORKER-B
TASK:MIN-STACK TASK:TASK APP-ACQ0
TASK:MIN-STACK TASK:TASK APP-ACQ1
TASK:MIN-STACK TASK:TASK APP-ACQ2
TASK:MIN-STACK TASK:TASK APP-ACQ3
TASK:MIN-STACK TASK:TASK APP-DET
TASK:FACILITY TASK-LOCK
TASK:FACILITY APP-LOCK

$4000 constant TASK-CAP
$1388 constant TASK-CAPTURE-MS
$4F constant TASK-LIVE-RC
$62 constant TASK-DIE-RC
E-TASK-STATE $FF and constant TASK-THROW-RC
8 constant APP-CYCLES
16 constant APP-ITERS
4 constant APP-ACQ-WANT
APP-ITERS 10 * 5 + constant APP-FFI-WANT
APP-ITERS 10 * 100 + constant APP-SHARED-WANT

create TASK-OUT TASK-CAP allot
create TASK-ERR TASK-CAP allot
create TASK-SYM-STRLEN $73 c, $74 c, $72 c, $6C c, $65 c, $6E c, 0 c,
create TASK-LIBC $6C c, $69 c, $62 c, $63 c, $2E c, $73 c, $6F c, $2E c, $36 c, 0 c,
create TASK-LIBSYSTEM
   $2F c, $75 c, $73 c, $72 c, $2F c, $6C c, $69 c, $62 c, $2F c,
   $6C c, $69 c, $62 c, $53 c, $79 c, $73 c, $74 c, $65 c, $6D c,
   $2E c, $42 c, $2E c, $64 c, $79 c, $6C c, $69 c, $62 c, 0 c,
create APP-CSTR1 $61 c, 0 c,
create APP-CSTR2 $61 c, $62 c, 0 c,
create APP-CSTR3 $61 c, $62 c, $63 c, 0 c,
create APP-CSTR4 $61 c, $62 c, $63 c, $64 c, 0 c,
create APP-CSTR5 $61 c, $62 c, $63 c, $64 c, $65 c, 0 c,

variable APP-ACQ-DONE
variable APP-DET-DONE
variable APP-SHARED
variable APP-FFI-TOTAL
variable APP-BAD

: TASK-WAIT-READY ( n -- ) {: want:n :}
   begin TASK-READY-CELL atomic@ want < while TASK:PAUSE repeat ;

: TASK-INC-LOCKED ( -- )
   TASK-LOCK TASK:GET
   1 TASK-COUNT atomic-add drop
   TASK-LOCK TASK:RELEASE ;

: TASK-TEST-FACILITY-SWIFT ( -- )
   TASK-LOCK TASK:RELEASE
   TASK-LOCK TASK:GET
   TASK-LOCK TASK:GET
   TASK-LOCK TASK:RELEASE
   TASK-LOCK TASK:RELEASE ;

: TASK-WORK-A ( -- )
   11 TASK-USER-CELL !
   TASK:SELF-N TASK-SELF-A !
   TASK-INC-LOCKED
   1 TASK-READY-CELL atomic-add drop ;

: TASK-WORK-B ( -- )
   22 TASK-USER-CELL !
   TASK:SELF-N TASK-SELF-B !
   TASK-INC-LOCKED
   1 TASK-READY-CELL atomic-add drop ;

: TASK-PAUSER ( -- )
   begin TASK:PAUSE again ;

: TASK-LF ( -- )
   $0A SB-APPEND-C ;

: TASK-DQ ( -- )
   $22 SB-APPEND-C ;

: TASK-LIB-PATH ( -- ptr u8 )
   HB-TARGET-MACOS? if TASK-LIBSYSTEM exit then
   TASK-LIBC ;

: TASK-STRLEN-LOAD ( -- n )
   TASK-LIB-PATH FFI:NOW FFI:DLOPEN dup 0= if E-TASK-DLOPEN throw then
   TASK-SYM-STRLEN FFI:DLSYM dup 0= if E-TASK-DLSYM throw then ;

TASK-STRLEN-LOAD constant TASK-STRLEN-XT

TRUSTED: TASK-CSTRLEN ( ptr u8 -- n ) {: cstr:ptr :}
   FFI:RESET
   cstr 0 FFI:READABLE!
   TASK:PAUSE
   FFI:ARGS FFI:REG-LENS 1 TASK-STRLEN-XT ffi-call-bounded ;

: APP-BAD+ ( -- )
   1 APP-BAD atomic-add drop ;

: APP-WAIT-CELL ( ptr a n -- ) {: cell:ptr want:n :}
   begin cell atomic@ want < while TASK:PAUSE repeat ;

: APP-WAIT-DONE ( ptr a -- ) {: tcb:ptr :}
   begin tcb TASK:DONE? 0= while TASK:PAUSE repeat ;

: APP-SHARED+ ( n -- ) {: v:n :}
   APP-LOCK TASK:GET
   APP-SHARED @ v + APP-SHARED !
   APP-LOCK TASK:RELEASE ;

: APP-ACQ-WORK ( n ptr u8 n -- ) {: id:n cstr:ptr want:n :}
   id TASK-LOCAL-ID !
   0 TASK-LOCAL-FFI !
   APP-ITERS 0 ?do
      id TASK-LOCAL-ID !
      cstr TASK-CSTRLEN dup TASK-LOCAL-FFI !
      dup want <> if APP-BAD+ then
      APP-FFI-TOTAL atomic-add drop
      TASK-LOCAL-ID @ id <> if APP-BAD+ then
      id 1 + APP-SHARED+
   loop
   1 APP-ACQ-DONE atomic-add drop ;

: APP-ACQ0-WORK ( -- )
   0 APP-CSTR1 1 APP-ACQ-WORK ;

: APP-ACQ1-WORK ( -- )
   1 APP-CSTR2 2 APP-ACQ-WORK ;

: APP-ACQ2-WORK ( -- )
   2 APP-CSTR3 3 APP-ACQ-WORK ;

: APP-ACQ3-WORK ( -- )
   3 APP-CSTR4 4 APP-ACQ-WORK ;

: APP-DET-WORK ( -- )
   $63 TASK-LOCAL-ID !
   APP-ACQ-DONE APP-ACQ-WANT APP-WAIT-CELL
   APP-CSTR5 TASK-CSTRLEN dup TASK-LOCAL-FFI !
   dup 5 <> if APP-BAD+ then
   APP-FFI-TOTAL atomic-add drop
   TASK-LOCAL-ID @ $63 <> if APP-BAD+ then
   100 APP-SHARED+
   1 APP-DET-DONE atomic-add drop ;

: APP-RESET ( -- )
   0 APP-ACQ-DONE !
   0 APP-DET-DONE !
   0 APP-SHARED !
   0 APP-FFI-TOTAL !
   0 APP-BAD ! ;

: APP-START ( -- )
   ['] APP-ACQ0-WORK APP-ACQ0 TASK:ACTIVATE
   ['] APP-ACQ1-WORK APP-ACQ1 TASK:ACTIVATE
   ['] APP-ACQ2-WORK APP-ACQ2 TASK:ACTIVATE
   ['] APP-ACQ3-WORK APP-ACQ3 TASK:ACTIVATE
   ['] APP-DET-WORK APP-DET TASK:ACTIVATE ;

: APP-WAIT ( -- )
   APP-ACQ-DONE APP-ACQ-WANT APP-WAIT-CELL
   APP-DET-DONE 1 APP-WAIT-CELL
   APP-ACQ0 APP-WAIT-DONE
   APP-ACQ1 APP-WAIT-DONE
   APP-ACQ2 APP-WAIT-DONE
   APP-ACQ3 APP-WAIT-DONE
   APP-DET APP-WAIT-DONE ;

: APP-CHECK-USERS ( -- )
   APP-ACQ0 TASK-LOCAL-ID TASK:HIS @ 0 T=
   APP-ACQ1 TASK-LOCAL-ID TASK:HIS @ 1 T=
   APP-ACQ2 TASK-LOCAL-ID TASK:HIS @ 2 T=
   APP-ACQ3 TASK-LOCAL-ID TASK:HIS @ 3 T=
   APP-DET TASK-LOCAL-ID TASK:HIS @ $63 T=
   APP-ACQ0 TASK-LOCAL-FFI TASK:HIS @ 1 T=
   APP-ACQ1 TASK-LOCAL-FFI TASK:HIS @ 2 T=
   APP-ACQ2 TASK-LOCAL-FFI TASK:HIS @ 3 T=
   APP-ACQ3 TASK-LOCAL-FFI TASK:HIS @ 4 T=
   APP-DET TASK-LOCAL-FFI TASK:HIS @ 5 T= ;

: APP-CHECK ( -- )
   APP-BAD @ 0 T=
   APP-ACQ-DONE @ APP-ACQ-WANT T=
   APP-DET-DONE @ 1 T=
   APP-FFI-TOTAL @ APP-FFI-WANT T=
   APP-SHARED @ APP-SHARED-WANT T=
   APP-CHECK-USERS ;

: APP-KILL ( -- )
   APP-ACQ0 TASK:KILL
   APP-ACQ1 TASK:KILL
   APP-ACQ2 TASK:KILL
   APP-ACQ3 TASK:KILL
   APP-DET TASK:KILL ;

: TASK-TEST-APP-SOAK ( -- )
   APP-LOCK TASK:FACILITY-INIT
   APP-CYCLES 0 ?do
      APP-RESET
      APP-START
      APP-WAIT
      APP-CHECK
      APP-KILL
   loop ;

: TASK-LIVE-COMPILE$ ( -- ptr u8 n )
   SB-RESET
   s" require lib/task.f" SB-APPEND TASK-LF
   s" : TASK-GUARD-LOOP ( -- ) begin TASK:PAUSE again ;" SB-APPEND TASK-LF
   s" TASK:MIN-STACK TASK:TASK TASK-GUARD-WORKER" SB-APPEND TASK-LF
   s" ' TASK-GUARD-LOOP TASK-GUARD-WORKER TASK:ACTIVATE" SB-APPEND TASK-LF
   s" variable TASK-GUARD-BAD" SB-APPEND TASK-LF
   SB$ ;

: TASK-DIE$ ( -- ptr u8 n )
   SB-RESET
   s" require lib/task.f" SB-APPEND TASK-LF
   s" : TASK-DIE-WORK ( -- ) s" SB-APPEND TASK-DQ
   $20 SB-APPEND-C
   s" task died" SB-APPEND TASK-DQ
   s"  $62 die ;" SB-APPEND TASK-LF
   s" TASK:MIN-STACK TASK:TASK TASK-DIE-WORKER" SB-APPEND TASK-LF
   s" : TASK-DIE-WAIT ( -- ) begin TASK:PAUSE again ;" SB-APPEND TASK-LF
   s" ' TASK-DIE-WORK TASK-DIE-WORKER TASK:ACTIVATE" SB-APPEND TASK-LF
   s" TASK-DIE-WAIT" SB-APPEND TASK-LF
   SB$ ;

: TASK-THROW$ ( -- ptr u8 n )
   SB-RESET
   s" require lib/task.f" SB-APPEND TASK-LF
   s" : TASK-THROW-WORK ( -- ) E-TASK-STATE throw ;" SB-APPEND TASK-LF
   s" TASK:MIN-STACK TASK:TASK TASK-THROW-WORKER" SB-APPEND TASK-LF
   s" : TASK-THROW-WAIT ( -- ) begin TASK:PAUSE again ;" SB-APPEND TASK-LF
   s" ' TASK-THROW-WORK TASK-THROW-WORKER TASK:ACTIVATE" SB-APPEND TASK-LF
   s" TASK-THROW-WAIT" SB-APPEND TASK-LF
   SB$ ;

: TASK-RUN-STDIN ( ptr u8 n -- len len outcome ) {: src:ptr srcu:n :}
   PROC-ARGV-RESET
   s" bin/hb" >LEN src srcu >LEN
   TASK-OUT TASK-CAP >LEN TASK-ERR TASK-CAP >LEN
   TASK-CAPTURE-MS >MS RUN-ARGV-STDIN-CAPTURE-OUTCOME ;

: TASK-TEST-LIVE-COMPILE-GUARD ( -- )
   TASK-LIVE-COMPILE$ TASK-RUN-STDIN TASK-LIVE-RC T-OUTCOME-EXITED= {: outu:len erru:len :}
   outu LEN>N 0 T=
   TASK-ERR erru LEN>N s" variable" T$= ;

: TASK-EXPECT-FAIL ( ptr u8 n n ptr u8 n -- ) {: src:ptr srcu:n want:n needle:ptr needleu:n :}
   src srcu TASK-RUN-STDIN want T-OUTCOME-EXITED= {: outu:len erru:len :}
   outu LEN>N 0 T=
   TASK-ERR erru LEN>N needle needleu CONTAINS? TTRUE ;

: TASK-TEST-WORKER-DIE ( -- )
   TASK-DIE$ TASK-DIE-RC s" task died" TASK-EXPECT-FAIL ;

: TASK-TEST-WORKER-THROW ( -- )
   TASK-THROW$ TASK-THROW-RC s" task: unhandled throw" TASK-EXPECT-FAIL ;

: TASK-TEST-RUN ( -- )
   T-RESET
   0 TASK-COUNT !
   0 TASK-READY-CELL !
   0 TASK-SELF-A !
   0 TASK-SELF-B !
   99 TASK-USER-CELL !
   TASK-LOCK TASK:FACILITY-INIT
   TASK-TEST-FACILITY-SWIFT
   ['] TASK-WORK-A WORKER-A TASK:ACTIVATE
   ['] TASK-WORK-B WORKER-B TASK:ACTIVATE
   2 TASK-WAIT-READY
   TASK-USER-CELL @ 99 T=
   WORKER-A TASK-USER-CELL TASK:HIS @ 11 T=
   WORKER-B TASK-USER-CELL TASK:HIS @ 22 T=
   TASK-SELF-A @ WORKER-A P>N T=
   TASK-SELF-B @ WORKER-B P>N T=
   WORKER-A TASK:KILL
   WORKER-B TASK:KILL
   TASK-COUNT @ 2 T=
   TASK-READY-CELL @ 2 T=
   ['] TASK-PAUSER WORKER-A TASK:ACTIVATE
   WORKER-A TASK:HALT
   WORKER-A TASK:KILL
   WORKER-A TASK:DONE? TFALSE
   TASK-TEST-LIVE-COMPILE-GUARD
   TASK-TEST-APP-SOAK
   TASK-TEST-WORKER-DIE
   TASK-TEST-WORKER-THROW
   T-REPORT ;

TASK-TEST-RUN

;package
