\ vector-test.f - focused tests for checked growable cell vectors.
\ Run: bin/hb --load lib/errors.f lib/string.f lib/test.f lib/memory.f lib/vector.f lib/vector-test.f

create VECT-VEC VEC-HEADER-CELLS cells allot
create VECT-PTR-VEC VEC-HEADER-CELLS cells allot

variable VECT-SUM
variable VECT-IDX-SUM

: VECT-RESET ( -- )
   VECT-VEC 2 VEC-CAP-COUNT VEC-INIT
   VECT-PTR-VEC 1 VEC-CAP-COUNT VEC-INIT
   0 VECT-SUM !
   0 VECT-IDX-SUM ! ;

TRUSTED: VECT-CHECK-REJECTS ( ptr u8 n -- )
   DIAGXT @ >r
   0 DIAGXT !
   CHECK! 0 T=
   r> DIAGXT ! ;

: VECT-GROW ( -- )
   VECT-RESET
   0 VEC-COUNT VEC-CHECK-NEED
   1 VEC-CAP-COUNT VEC-CELLS>BYTES 1 cells T=
   1 VEC-LEN VEC-CHECK-LEN
   VECT-VEC 1 VEC-CELL-FIELD VECT-VEC cell+ = TTRUE
   VECT-VEC VEC-CAP@ VEC-CHECK-CAP
   VECT-VEC 2 VEC-COUNT VEC-ENSURE
   VECT-VEC VEC-CAP@ COUNT>N 2 T=
   11 VECT-VEC VEC-PUSH-N IDX>N 0 T=
   22 VECT-VEC VEC-PUSH-N IDX>N 1 T=
   33 VECT-VEC VEC-PUSH-N IDX>N 2 T=
   VECT-VEC VEC-LEN@ LEN>N 3 T=
   VECT-VEC VEC-CAP@ COUNT>N 4 T=
   VECT-VEC 0 VEC-IDX VEC-N@ 11 T=
   VECT-VEC 1 VEC-IDX VEC-N@ 22 T=
   VECT-VEC 2 VEC-IDX VEC-N@ 33 T= ;

: VECT-SET ( -- )
   VECT-RESET
   99 VECT-VEC VEC-PUSH-N drop
   123 VECT-VEC 0 VEC-IDX VEC-N!
   VECT-VEC 0 VEC-IDX VEC-N@ 123 T= ;

: VECT-RESIZE ( -- )
   VECT-RESET
   41 VECT-VEC VEC-PUSH-N drop
   42 VECT-VEC VEC-PUSH-N drop
   VECT-VEC 5 VEC-CAP-COUNT VEC-RESIZE
   VECT-VEC VEC-LEN@ LEN>N 2 T=
   VECT-VEC VEC-CAP@ COUNT>N 5 T=
   VECT-VEC 0 VEC-IDX VEC-N@ 41 T=
   VECT-VEC 1 VEC-IDX VEC-N@ 42 T= ;

: VECT-RESIZE-SHRINK-BAD ( -- )
   VECT-RESET
   41 VECT-VEC VEC-PUSH-N drop
   42 VECT-VEC VEC-PUSH-N drop
   VECT-VEC 1 VEC-CAP-COUNT VEC-RESIZE ;

: VECT-CLEAR ( -- )
   VECT-RESET
   7 VECT-VEC VEC-PUSH-N drop
   8 VECT-VEC VEC-PUSH-N drop
   VECT-VEC VEC-CLEAR
   VECT-VEC VEC-LEN@ LEN>N 0 T=
   VECT-VEC VEC-CAP@ COUNT>N 2 T=
   9 VECT-VEC VEC-PUSH-N IDX>N 0 T=
   VECT-VEC 0 VEC-IDX VEC-N@ 9 T= ;

: VECT-POINTER ( -- )
   VECT-RESET
   s" alpha" drop VECT-PTR-VEC VEC-PUSH-A IDX>N 0 T=
   VECT-PTR-VEC 0 VEC-IDX VEC-A@ 5 s" alpha" T$=
   s" beta" drop VECT-PTR-VEC 0 VEC-IDX VEC-A!
   VECT-PTR-VEC 0 VEC-IDX VEC-A@ 4 s" beta" T$= ;

: VECT-EACH-ACC ( idx n -- ) {: ix value :}
   VECT-SUM @ value + VECT-SUM !
   VECT-IDX-SUM @ ix IDX>N + VECT-IDX-SUM ! ;

: VECT-EACH-TEST ( -- )
   VECT-RESET
   5 VECT-VEC VEC-PUSH-N drop
   6 VECT-VEC VEC-PUSH-N drop
   7 VECT-VEC VEC-PUSH-N drop
   VECT-VEC [: VECT-EACH-ACC ;] VEC-EACH
   VECT-SUM @ 18 T=
   VECT-IDX-SUM @ 3 T= ;

: VECT-BAD-CAP-ZERO ( -- )
   0 VEC-CAP-COUNT drop ;

: VECT-BAD-CAP-NEG ( -- )
   -1 VEC-CAP-COUNT drop ;

: VECT-BAD-NEED-HIGH ( -- )
   VEC-MAX-CELLS 1 + VEC-COUNT drop ;

: VECT-BAD-LEN-NEG ( -- )
   -1 VEC-LEN drop ;

: VECT-BAD-LEN-HIGH ( -- )
   VECT-RESET
   3 VEC-LEN VECT-VEC VEC-LEN! ;

: VECT-GET-HIGH ( -- )
   VECT-RESET
   1 VECT-VEC VEC-PUSH-N drop
   VECT-VEC 1 VEC-IDX VEC-N@ drop ;

: VECT-GET-NEG ( -- )
   VECT-RESET
   1 VECT-VEC VEC-PUSH-N drop
   VECT-VEC -1 VEC-IDX VEC-N@ drop ;

: VECT-SET-HIGH ( -- )
   VECT-RESET
   1 VECT-VEC VEC-PUSH-N drop
   2 VECT-VEC 1 VEC-IDX VEC-N! ;

: VECT-RUN ( -- )
   T-RESET
   VECT-GROW
   VECT-SET
   VECT-RESIZE
   VECT-CLEAR
   VECT-POINTER
   VECT-EACH-TEST
   [: VECT-RESIZE-SHRINK-BAD ;] E-VEC-BOUNDS TTHROWSQ
   [: VECT-BAD-CAP-ZERO ;] E-VEC-CAPACITY TTHROWSQ
   [: VECT-BAD-CAP-NEG ;] E-VEC-CAPACITY TTHROWSQ
   [: VECT-BAD-NEED-HIGH ;] E-VEC-CAPACITY TTHROWSQ
   [: VECT-BAD-LEN-NEG ;] E-VEC-BOUNDS TTHROWSQ
   [: VECT-BAD-LEN-HIGH ;] E-VEC-BOUNDS TTHROWSQ
   [: VECT-GET-HIGH ;] E-VEC-BOUNDS TTHROWSQ
   [: VECT-GET-NEG ;] E-VEC-BOUNDS TTHROWSQ
   [: VECT-SET-HIGH ;] E-VEC-BOUNDS TTHROWSQ
   s" BAD-VEC-FETCH ( ptr a len -- a ) VEC@" VECT-CHECK-REJECTS
   s" BAD-VEC-LEN! ( count ptr a -- ) VEC-LEN!" VECT-CHECK-REJECTS
   T-REPORT ;

VECT-RUN
