\ gpt2-reference-data-test.f - pinned GPT-2 reference contract tests.

require lib/test.f
require lib/ieee754.f
require maki/infer/gpt2-reference-data.f

package GPT2-REFERENCE-TEST
private

: RT= ( r r -- ) {: actual:r expected:r :}
   actual IEEE754:F64>BITS expected IEEE754:F64>BITS T= ;

: MISSING-ARTIFACT ( -- )
   s" /.habu-gpt2-reference-artifact-missing" GPT2-REFERENCE:VERIFY-ARTIFACT ;

: WRONG-ARTIFACT ( -- )
   s" maki/infer/gpt2-reference-data.f" GPT2-REFERENCE:VERIFY-ARTIFACT ;

: BAD-TINY-ID ( -- )  -1 GPT2-REFERENCE:TINY-ID drop ;
: BAD-TINY-PROBE ( -- )  4 0 GPT2-REFERENCE:TINY-PROBE drop ;
: BAD-REAL-PROBE ( -- )  0 3 GPT2-REFERENCE:REAL-PROBE drop ;
: BAD-REAL-LOGIT ( -- )  8 GPT2-REFERENCE:REAL-LOGIT drop ;

: COUNTS ( -- )
   GPT2-REFERENCE:TINY-ID-COUNT 8 T=
   GPT2-REFERENCE:REAL-ID-COUNT 64 T=
   GPT2-REFERENCE:TINY-BOUNDARY-COUNT 4 T=
   GPT2-REFERENCE:REAL-BOUNDARY-COUNT 14 T=
   GPT2-REFERENCE:PROBE-COMPONENT-COUNT 3 T=
   GPT2-REFERENCE:TINY-LOGIT-COUNT 16 T=
   GPT2-REFERENCE:REAL-LOGIT-COUNT 8 T= ;

: SAMPLES ( -- )
   0 GPT2-REFERENCE:TINY-ID 3 T=
   7 GPT2-REFERENCE:TINY-ID 6 T=
   3 0 GPT2-REFERENCE:TINY-PROBE 1.471802421230333557 RT=
   3 GPT2-REFERENCE:TINY-LOGIT 0.3550359957174532 RT=
   0 GPT2-REFERENCE:REAL-ID 11 T=
   63 GPT2-REFERENCE:REAL-ID 407 T=
   13 2 GPT2-REFERENCE:REAL-PROBE 5745.297091220824768243 RT=
   5 GPT2-REFERENCE:REAL-LOGIT-ID 15496 T=
   7 GPT2-REFERENCE:REAL-LOGIT -36.457968475880193 RT=
   GPT2-REFERENCE:REAL-SUM -2159609.0490200613 RT=
   GPT2-REFERENCE:REAL-SUMSQ 92900785.768102676 RT= ;

public

: RUN ( -- )
   T-RESET
   COUNTS
   SAMPLES
   [: BAD-TINY-ID ;] GPT2-REFERENCE:E-BOUNDS TTHROWSQ
   [: BAD-TINY-PROBE ;] GPT2-REFERENCE:E-BOUNDS TTHROWSQ
   [: BAD-REAL-PROBE ;] GPT2-REFERENCE:E-BOUNDS TTHROWSQ
   [: BAD-REAL-LOGIT ;] GPT2-REFERENCE:E-BOUNDS TTHROWSQ
   [: MISSING-ARTIFACT ;] GPT2-REFERENCE:E-ARTIFACT TTHROWSQ
   [: WRONG-ARTIFACT ;] GPT2-REFERENCE:E-DIGEST TTHROWSQ
   T-REPORT ;

;package

GPT2-REFERENCE-TEST:RUN
