\ Parsed as emitter text by clobber-lint-test; not loaded as a Habu program.
: STACK-GUARDED-LEAF ( -- )
   LSTACKLEAF LABEL@ LBL,
   9 11 MOVZ,  16 12 MOVZ,  17 13 MOVZ,
   0 64 STACK-GUARD:CHECK-DATA
   0 2 STACK-GUARD:CHECK-RETURN
   2 0 STACK-GUARD:CHECK-LOOP
   0 16 JIT-STACK:CHECK-DATA
   9 16 JIT-STACK:DATA-REGS
   0 2 JIT-STACK:CHECK-RETURN
   9 16 JIT-STACK:RETURN-REGS
   2 0 JIT-STACK:CHECK-LOOP
   9 16 JIT-STACK:LITERAL-REG
   17 9 JIT-STACK:CELL-BYTES
   9 DATA 0 STR,  16 DATA 8 STR,  17 DATA 16 STR,
   RET, ;
