\ clobber-sys-x8-fixture.f - negative fixture for syscall scratch liveness.

variable LBAD
variable LCALL
variable LEXITGROUP
variable LRET
variable LX13-CALLEE
variable LX13-CALLER
variable LX13-CLEAN
variable LP2CWAT
variable LCEMIT
variable LHIDXADD
variable LRETURN-USE
variable LPRESERVE-X13
variable LPRESERVE-X17
variable LHEADER-RELOAD
variable LHEADER-STALE
variable LROWS-RELOAD
variable LROWS-STALE
variable LINDEX-RELOAD
variable LINDEX-STALE

: EMIT-ROWS-RELOAD-OK ( -- )
   LROWS-RELOAD LABEL@ LBL,
   MARK-HEADER
   NR-MMAP SYS,
   MARK-HEADER MARK-ROWS
   RET, ;

: EMIT-ROWS-RELOAD-BAD ( -- )
   LROWS-STALE LABEL@ LBL,
   MARK-HEADER
   NR-MMAP SYS,
   MARK-ROWS
   RET, ;

: EMIT-INDEX-RELOAD-OK ( -- )
   LINDEX-RELOAD LABEL@ LBL,
   8 9 0 ADDI,
   NR-MMAP SYS,
   8 0 0 ADDI,
   bad INDEX-SHAPE
   RET, ;

: EMIT-INDEX-RELOAD-BAD ( -- )
   LINDEX-STALE LABEL@ LBL,
   8 9 0 ADDI,
   NR-MMAP SYS,
   bad INDEX-SHAPE
   RET, ;

: EMIT-HEADER-RELOAD-OK ( -- )
   LHEADER-RELOAD LABEL@ LBL,
   16 9 0 ADDI,
   NR-MMAP SYS,
   MARK-HEADER
   5 16 0 LDR,
   6 4 0 LDR,
   RET, ;

: EMIT-HEADER-RELOAD-BAD ( -- )
   LHEADER-STALE LABEL@ LBL,
   16 9 0 ADDI,
   NR-MMAP SYS,
   5 16 0 LDR,
   RET, ;

: EMIT-SYS-X8-BAD ( -- )
   LBAD LABEL@ LBL,
   8 9 0 ADDI,
   NR-CLOSE SYS,
   4 8 0 LDRB,
   RET, ;

: EMIT-LR-BAD ( -- )
   LCALL LABEL@ LBL,
   LRET LABEL@ BL,
   RET,
   LRET LABEL@ LBL,
   RET, ;

: EMIT-EXIT-GROUP-OK ( -- )
   LEXITGROUP LABEL@ LBL,
   16 9 0 ADDI,
   NR-EXIT-GROUP SYS,
   4 16 0 LDRB,
   RET, ;

: EMIT-X13-CALLEE ( -- )
   LX13-CALLEE LABEL@ LBL,
   13 0 MOVZ,
   RET, ;

: EMIT-X13-CALLER-BAD ( -- )
   LX13-CALLER LABEL@ LBL,
   SP SP 16 SUBI,
   30 SP 0 STR,
   13 9 0 ADDI,
   LX13-CALLEE LABEL@ BL,
   4 13 0 LDRB,
   30 SP 0 LDR,
   SP SP 16 ADDI,
   RET, ;

: EMIT-X13-CALLER-OK ( -- )
   LX13-CLEAN LABEL@ LBL,
   SP SP 16 SUBI,
   30 SP 0 STR,
   13 9 0 ADDI,
   LX13-CALLEE LABEL@ BL,
   13 9 0 ADDI,
   4 13 0 LDRB,
   30 SP 0 LDR,
   SP SP 16 ADDI,
   RET, ;

: EMIT-RETURNS-X10 ( -- )
   LP2CWAT LABEL@ LBL,
   10 1 MOVZ,
   RET, ;

: EMIT-USES-RETURNED-X10 ( -- )
   LRETURN-USE LABEL@ LBL,
   SP SP 16 SUBI,
   30 SP 0 STR,
   LP2CWAT LABEL@ BL,
   4 10 0 LDRB,
   30 SP 0 LDR,
   SP SP 16 ADDI,
   RET, ;

: EMIT-PRESERVES-X13 ( -- )
   LCEMIT LABEL@ LBL,
   SP SP 16 SUBI,
   13 SP 0 STR,
   13 0 MOVZ,
   13 SP 0 LDR,
   SP SP 16 ADDI,
   RET, ;

: EMIT-KEEPS-X13 ( -- )
   LPRESERVE-X13 LABEL@ LBL,
   SP SP 16 SUBI,
   30 SP 0 STR,
   13 9 0 ADDI,
   LCEMIT LABEL@ BL,
   4 13 0 LDRB,
   30 SP 0 LDR,
   SP SP 16 ADDI,
   RET, ;

: EMIT-PRESERVES-X17 ( -- )
   LHIDXADD LABEL@ LBL,
   SP SP 16 SUBI,
   17 SP 0 STR,
   17 0 MOVZ,
   17 SP 0 LDR,
   SP SP 16 ADDI,
   RET, ;

: EMIT-KEEPS-X17 ( -- )
   LPRESERVE-X17 LABEL@ LBL,
   SP SP 16 SUBI,
   30 SP 0 STR,
   17 9 0 ADDI,
   LHIDXADD LABEL@ BL,
   4 17 0 LDRB,
   30 SP 0 LDR,
   SP SP 16 ADDI,
   RET, ;

package CLOBBER-FIX
public
variable LQUAL

: EMIT-QUALIFIED-CALLEE ( -- )
   LQUAL LABEL@ LBL,
   13 0 MOVZ,
   RET, ;
;package

package CLOBBER-FIXTURE
variable LQUAL-CALLER

: EMIT-QUALIFIED-CALLER-BAD ( -- )
   LQUAL-CALLER LABEL@ LBL,
   SP SP 16 SUBI,
   30 SP 0 STR,
   13 9 0 ADDI,
   CLOBBER-FIX:LQUAL LABEL@ BL,
   4 13 0 LDRB,
   30 SP 0 LDR,
   SP SP 16 ADDI,
   RET, ;
;package

package CLOBBER-FIXTURE
variable LSEPARATE-CLOBBER
variable LSEPARATE-READ
variable LFALL-CLOBBER
variable LFALL-READ
variable LJUMP-CLOBBER
variable LJUMP-READ
variable LUNUSED
variable LCOND-CLOBBER
variable LCOND-READ
variable LLOCAL-CLOBBER
variable LLOCAL-SKIP

\ A read in the next independent routine does not use the prior routine's
\ poisoned value. The same read reached by fall-through must still be caught.
: EMIT-SEPARATE-ENTRIES-OK ( -- )
   LSEPARATE-CLOBBER LABEL@ LBL,
   SP SP 16 SUBI,  30 SP 0 STR,
   13 9 0 ADDI,
   LX13-CALLEE LABEL@ BL,
   30 SP 0 LDR,  SP SP 16 ADDI,  RET,
   LSEPARATE-READ LABEL@ LBL,
   4 13 0 LDRB,  RET, ;

: EMIT-FALL-THROUGH-BAD ( -- )
   LFALL-CLOBBER LABEL@ LBL,
   SP SP 16 SUBI,  30 SP 0 STR,
   13 9 0 ADDI,
   LX13-CALLEE LABEL@ BL,
   LFALL-READ LABEL@ LBL,
   4 13 0 LDRB,
   30 SP 0 LDR,  SP SP 16 ADDI,  RET, ;

: EMIT-JUMP-TO-NEXT-BAD ( -- )
   LJUMP-CLOBBER LABEL@ LBL,
   SP SP 16 SUBI,  30 SP 0 STR,
   13 9 0 ADDI,
   LX13-CALLEE LABEL@ BL,
   30 SP 0 LDR,
   LJUMP-READ LABEL@ B,
   LUNUSED LABEL@ LBL, RET,
   LJUMP-READ LABEL@ LBL,
   4 13 0 LDRB,
   30 SP 0 LDR,  SP SP 16 ADDI,  RET, ;

: EMIT-JUMP-PAST-RETURN-BAD ( -- )
   LCOND-CLOBBER LABEL@ LBL,
   SP SP 16 SUBI,  30 SP 0 STR,
   13 9 0 ADDI,
   LX13-CALLEE LABEL@ BL,
   C-EQ LCOND-READ LABEL@ BCOND,
   30 SP 0 LDR,  SP SP 16 ADDI,  RET,
   LCOND-READ LABEL@ LBL,
   4 13 0 LDRB,
   30 SP 0 LDR,  SP SP 16 ADDI,  RET, ;

: EMIT-LOCAL-JUMP-PAST-ENTRY-BAD ( -- )
   LBL {: shared:label :}
   LLOCAL-CLOBBER LABEL@ LBL,
   SP SP 16 SUBI,  30 SP 0 STR,
   13 9 0 ADDI,
   LX13-CALLEE LABEL@ BL,
   30 SP 0 LDR,
   shared B,
   LLOCAL-SKIP LABEL@ LBL, RET,
   shared LBL,
   4 13 0 LDRB,
   30 SP 0 LDR,  SP SP 16 ADDI,  RET, ;
;package
