\ def-test.f - focused structural defining-role classifier fixtures.

require lib/test.f
require tools/lint/def.f

package LINT-DEF-TEST
private

: SOME= ( option<n> n -- ) {: want:n :}
   MATCH option
      none OF -1 want T= ENDOF
      some OF want T= ENDOF
   ;MATCH ;

: NONE? ( option<n> -- )
   MATCH option
      none OF LINT-TRUE TTRUE ENDOF
      some OF drop LINT-FALSE TTRUE ENDOF
   ;MATCH ;

: MIXED-AND-LEGACY ( -- )
   s" cHeCkEd: Name ;" LINT-LEX:SOURCE
   0 LINT-DEF:DIRECT-KIND LINT-DEF:COLON T=
   s" newtype T 0" LINT-LEX:SOURCE
   0 LINT-DEF:DIRECT-KIND LINT-DEF:DATA T=
   s" enum E ;enum" LINT-LEX:SOURCE
   0 LINT-DEF:DIRECT-KIND LINT-DEF:ENUM T=
   2 LINT-DEF:ENUM LINT-DEF:CLOSE? TTRUE
   s" structure S ;structure" LINT-LEX:SOURCE
   0 LINT-DEF:DIRECT-KIND LINT-DEF:STRUCTURE T=
   2 LINT-DEF:STRUCTURE LINT-DEF:CLOSE? TTRUE
   s" sumtype S ;sumtype" LINT-LEX:SOURCE
   0 LINT-DEF:DIRECT-KIND LINT-DEF:SUMTYPE T=
   s" product P ;product" LINT-LEX:SOURCE
   0 LINT-DEF:DIRECT-KIND LINT-DEF:PRODUCT T=
   s" deftype T" LINT-LEX:SOURCE
   0 LINT-DEF:DIRECT-KIND LINT-DEF:DATA T= ;

: EXPORT-CASES ( -- )
   s" EXPORT GLOBAL:COUNT>N" LINT-LEX:SOURCE
   0 LINT-DEF:DIRECT-KIND LINT-DEF:NONE T=
   0 LINT-DEF:EXPORT? TTRUE
   0 LINT-DEF:EXPORT-I 1 SOME=
   1 LINT-DEF:EXPORT? TFALSE
   s" EXPORT" LINT-LEX:SOURCE
   0 LINT-DEF:EXPORT-I NONE?
   s" EXPORT-X NAME" LINT-LEX:SOURCE
   0 LINT-DEF:EXPORT? TFALSE
   0 LINT-DEF:EXPORT-I NONE? ;

: ALL-INERT ( -- )
   0 begin dup LINT-LEX:COUNT < while
      dup LINT-DEF:DIRECT-KIND LINT-DEF:NONE T=
      dup LINT-DEF:EXPORT? TFALSE
      1+
   repeat drop ;

: STRING$ ( -- ptr u8 n )
   SB-RESET
   s" s" SB-APPEND 34 SB-APPEND-C
   s"  : HIDDEN EXPORT HIDDEN" SB-APPEND
   34 SB-APPEND-C
   SB$ ;

: OPAQUE-AND-MISSING ( -- )
   s" ( : HIDDEN EXPORT HIDDEN )" LINT-LEX:SOURCE ALL-INERT
   STRING$ LINT-LEX:SOURCE ALL-INERT
   s" PRIM: HIDDEN PE-N PE-IN PRIM;" LINT-LEX:SOURCE ALL-INERT
   s" :" LINT-LEX:SOURCE
   0 LINT-DEF:NAME-I NONE?
   \ A standalone `(` after the definer is a comment, so the name is missing;
   \ a word merely NAMED with a leading paren (habu1.f's `(CMP)`) is the name.
   s" : ( n -- ) ;" LINT-LEX:SOURCE
   0 LINT-DEF:NAME-I NONE?
   s" : (PAREN-NAME) ;" LINT-LEX:SOURCE
   0 LINT-DEF:NAME-I 1 SOME=
   s" : NEAR ;" LINT-LEX:SOURCE
   0 LINT-DEF:DIRECT-KIND LINT-DEF:COLON T=
   2 LINT-DEF:SUMTYPE LINT-DEF:CLOSE? TFALSE
   2 LINT-DEF:NONE LINT-DEF:CLOSE? TFALSE
   2 LINT-DEF:DATA LINT-DEF:CLOSE? TFALSE
   s" COLON: NAME" LINT-LEX:SOURCE
   0 LINT-DEF:DIRECT-KIND LINT-DEF:NONE T=
   s" NEWTYPE-X NAME" LINT-LEX:SOURCE
   0 LINT-DEF:DIRECT-KIND LINT-DEF:NONE T= ;

public

: RUN ( -- )
   T-RESET
   MIXED-AND-LEGACY
   EXPORT-CASES
   OPAQUE-AND-MISSING
   T-REPORT ;

RUN

;package
