\ text-foundation-test.f — focused tests for tools/lint/lib.f text helpers.
\ Run: cat tools/lint/lib.f tools/lint/source-lex.f tools/lint/text-foundation-test.f | bin/hb

variable TEST-N
: ASSERT  ( f -- )
   0= IF s" text-foundation-test failed at assertion " type TEST-N @ . cr 1 die THEN
   TEST-N @ 1+ TEST-N ! ;
: ASSERT=  ( got want -- )  = ASSERT ;
: ASSERT$  ( a u b v -- )  STR= ASSERT ;

$100 constant FIX-CAP
create STR-FIX FIX-CAP allot     variable STR-LEN
create TRUST-FIX FIX-CAP allot   variable TRUST-LEN
create SRC-FIX FIX-CAP allot     variable SRC-LEN
create BT-FIX FIX-CAP allot      variable BT-LEN
create LEX-FIX FIX-CAP allot     variable LEX-LEN

: INIT-STR-FIX  ( -- )
   0 STR-LEN !
   32 STR-FIX FIX-CAP STR-LEN BUF-APPEND-C
   32 STR-FIX FIX-CAP STR-LEN BUF-APPEND-C
   s" Alpha beta" STR-FIX FIX-CAP STR-LEN BUF-APPEND
   10 STR-FIX FIX-CAP STR-LEN BUF-APPEND-C
   s" Gamma" STR-FIX FIX-CAP STR-LEN BUF-APPEND
   32 STR-FIX FIX-CAP STR-LEN BUF-APPEND-C
   32 STR-FIX FIX-CAP STR-LEN BUF-APPEND-C
   10 STR-FIX FIX-CAP STR-LEN BUF-APPEND-C ;
: STR-FIX$  ( -- a u )  STR-FIX STR-LEN @ ;

: INIT-TRUST-FIX  ( -- )
   0 TRUST-LEN !
   s" prefix s" TRUST-FIX FIX-CAP TRUST-LEN BUF-APPEND
   DQUOTE TRUST-FIX FIX-CAP TRUST-LEN BUF-APPEND-C
   32 TRUST-FIX FIX-CAP TRUST-LEN BUF-APPEND-C
   s" SQ" TRUST-FIX FIX-CAP TRUST-LEN BUF-APPEND
   DQUOTE TRUST-FIX FIX-CAP TRUST-LEN BUF-APPEND-C
   32 TRUST-FIX FIX-CAP TRUST-LEN BUF-APPEND-C
   115 TRUST-FIX FIX-CAP TRUST-LEN BUF-APPEND-C
   DQUOTE TRUST-FIX FIX-CAP TRUST-LEN BUF-APPEND-C
   32 TRUST-FIX FIX-CAP TRUST-LEN BUF-APPEND-C
   s" ( n -- n )" TRUST-FIX FIX-CAP TRUST-LEN BUF-APPEND
   DQUOTE TRUST-FIX FIX-CAP TRUST-LEN BUF-APPEND-C
   s"  TRUST \\ comment" TRUST-FIX FIX-CAP TRUST-LEN BUF-APPEND
   10 TRUST-FIX FIX-CAP TRUST-LEN BUF-APPEND-C ;
: TRUST-FIX$  ( -- a u )  TRUST-FIX TRUST-LEN @ ;

: INIT-SRC-FIX  ( -- )
   0 SRC-LEN !
   s" : REPL-SRC s" SRC-FIX FIX-CAP SRC-LEN BUF-APPEND
   DQUOTE SRC-FIX FIX-CAP SRC-LEN BUF-APPEND-C
   32 SRC-FIX FIX-CAP SRC-LEN BUF-APPEND-C
   s" src/habu/repl.f" SRC-FIX FIX-CAP SRC-LEN BUF-APPEND
   DQUOTE SRC-FIX FIX-CAP SRC-LEN BUF-APPEND-C
   s"  ;" SRC-FIX FIX-CAP SRC-LEN BUF-APPEND
   10 SRC-FIX FIX-CAP SRC-LEN BUF-APPEND-C ;
: SRC-FIX$  ( -- a u )  SRC-FIX SRC-LEN @ ;

: INIT-BT-FIX  ( -- )
   0 BT-LEN !
   s" See `tools/lint/source-lex.f` and `plain`." BT-FIX FIX-CAP BT-LEN BUF-APPEND
   10 BT-FIX FIX-CAP BT-LEN BUF-APPEND-C ;
: BT-FIX$  ( -- a u )  BT-FIX BT-LEN @ ;

: INIT-LEX-FIX  ( -- )
   0 LEX-LEN !
   s" : SQ ( n -- n ) s" LEX-FIX FIX-CAP LEX-LEN BUF-APPEND
   DQUOTE LEX-FIX FIX-CAP LEX-LEN BUF-APPEND-C
   s"  hi : ; ( x )" LEX-FIX FIX-CAP LEX-LEN BUF-APPEND
   DQUOTE LEX-FIX FIX-CAP LEX-LEN BUF-APPEND-C
   s"  dup " LEX-FIX FIX-CAP LEX-LEN BUF-APPEND
   92 LEX-FIX FIX-CAP LEX-LEN BUF-APPEND-C
   s"  skip die" LEX-FIX FIX-CAP LEX-LEN BUF-APPEND
   10 LEX-FIX FIX-CAP LEX-LEN BUF-APPEND-C
   99 LEX-FIX FIX-CAP LEX-LEN BUF-APPEND-C
   DQUOTE LEX-FIX FIX-CAP LEX-LEN BUF-APPEND-C
   s"  z" LEX-FIX FIX-CAP LEX-LEN BUF-APPEND
   DQUOTE LEX-FIX FIX-CAP LEX-LEN BUF-APPEND-C
   s"  ;" LEX-FIX FIX-CAP LEX-LEN BUF-APPEND
   10 LEX-FIX FIX-CAP LEX-LEN BUF-APPEND-C ;
: LEX-FIX$  ( -- a u )  LEX-FIX LEX-LEN @ ;

: INIT-FIXTURES  ( -- )
   INIT-STR-FIX
   INIT-TRUST-FIX
   INIT-SRC-FIX
   INIT-BT-FIX
   INIT-LEX-FIX ;

: TEST-STRINGS  ( -- )
   STR-FIX$ SPLIT-LINES  SN# @ 2 ASSERT=
   0 S@ TRIM s" Alpha beta" ASSERT$
   1 S@ TRIM s" Gamma" ASSERT$
   STR-FIX$ SPLIT-WHITESPACE  SN# @ 3 ASSERT=
   0 S@ s" Alpha" ASSERT$  1 S@ s" beta" ASSERT$  2 S@ s" Gamma" ASSERT$
   s" hello.f" s" .f" HAS-EXT? ASSERT
   s" hello.fs" s" .py" HAS-EXT? 0= ASSERT
   s" Habu" s" Ha" STARTS-WITH? ASSERT
   s" Habu" s" bu" ENDS-WITH? ASSERT
   s" banana" 97 COUNT-CHAR 3 ASSERT=
   s" banana" 110 INDEX-OF 2 ASSERT= ;

: TEST-SCANNERS  ( -- )
   TRUST-FIX$ TRUST-SITE? ASSERT
   P1A @ P1U @ s" SQ" ASSERT$
   P2A @ P2U @ s" ( n -- n )" ASSERT$
   SRC-FIX$ SRC-PATH-REF? ASSERT
   P1A @ P1U @ s" src/habu/repl.f" ASSERT$
   BT-FIX$ BACKTICK-PATH? ASSERT
   P1A @ P1U @ s" tools/lint/source-lex.f" ASSERT$
   s" `plain`" BACKTICK-PATH? 0= ASSERT ;

: TEST-SIGS  ( -- )
   s"  n -- n  " SIG-KIND SIG-TYPED ASSERT=
   s" private infer" SIG-KIND SIG-OPTOUT ASSERT=
   s" i64 )" SIG-KIND SIG-MISSING ASSERT=
   s" : BAD ( i64 ) dup ;" LEX-SOURCE
   2 LCONTENT SIG-KIND SIG-MISSING ASSERT= ;

: TEST-LEXER  ( -- )
   LEX-FIX$ LEX-SOURCE
   L# @ 7 ASSERT=
   0 LK@ L-WORD ASSERT=    0 LTOK s" :" ASSERT$
   0 LB@ 0 ASSERT=  0 LL@ 1 ASSERT=  0 LC@ 1 ASSERT=
   1 LK@ L-WORD ASSERT=    1 LTOK s" SQ" ASSERT$
   1 LB@ 2 ASSERT=  1 LL@ 1 ASSERT=  1 LC@ 3 ASSERT=
   2 LK@ L-COMMENT ASSERT= 2 LCONTENT s"  n -- n " ASSERT$
   2 LB@ 5 ASSERT=  2 LL@ 1 ASSERT=  2 LC@ 6 ASSERT=
   3 LTOK nip 2 ASSERT=  3 LTOK drop c@ 115 ASSERT=  3 LTOK drop 1+ c@ DQUOTE ASSERT=
   3 LB@ 16 ASSERT=  3 LL@ 1 ASSERT=  3 LC@ 17 ASSERT=
   4 LTOK s" dup" ASSERT$
   4 LB@ 33 ASSERT=  4 LL@ 1 ASSERT=  4 LC@ 34 ASSERT=
   5 LTOK nip 2 ASSERT=  5 LTOK drop c@ 99 ASSERT=  5 LTOK drop 1+ c@ DQUOTE ASSERT=
   5 LB@ 48 ASSERT=  5 LL@ 2 ASSERT=  5 LC@ 1 ASSERT=
   6 LTOK s" ;" ASSERT$
   6 LB@ 54 ASSERT=  6 LL@ 2 ASSERT=  6 LC@ 7 ASSERT= ;

: TEXT-FOUNDATION-TEST  ( -- )
   1 TEST-N !
   INIT-FIXTURES
   TEST-STRINGS
   TEST-SCANNERS
   TEST-SIGS
   TEST-LEXER
   s" text-foundation-test: ok (" type TEST-N @ 1- . s"  assertions)" type cr ;

TEXT-FOUNDATION-TEST
