\ ptx-launch-test.f - checked fixtures for PTX launch contracts.

require lib/ptx/test-prelude.f

T-RESET

1 4 256 PTX-ROW-LAUNCH-CHECK
2 256 256 PTX-ROW-LAUNCH-CHECK
2 1024 1024 PTX-ROW-LAUNCH-CHECK

: PTX-BAD-LAUNCH-ROWS ( -- )
   0 4 256 PTX-ROW-LAUNCH-CHECK ;
: PTX-BAD-LAUNCH-COLS ( -- )
   1 0 256 PTX-ROW-LAUNCH-CHECK ;
: PTX-BAD-LAUNCH-BLOCK ( -- )
   1 4 33 PTX-ROW-LAUNCH-CHECK ;
: PTX-BAD-LAUNCH-WHERE ( -- )
   1 257 256 PTX-ROW-LAUNCH-CHECK ;

' PTX-BAD-LAUNCH-ROWS E-PTX-BLOCK TTHROWS
' PTX-BAD-LAUNCH-COLS E-PTX-BLOCK TTHROWS
' PTX-BAD-LAUNCH-BLOCK E-PTX-BLOCK TTHROWS
' PTX-BAD-LAUNCH-WHERE E-PTX-BLOCK TTHROWS

T-REPORT
