\ generated-declaration.f - production generated-declaration transaction.
\
\ This file owns one sealed DECLARATION-TRANSACTION instance.  The checker is
\ the first participant; DECL-EVENT enrolls later in the checked declaration
\ layer; the native dictionary and protection owners enroll after xref; and the
\ protection owner seals the participant set last. RUN refuses to start before
\ that final seal.

package GENERATED-DECL-OWNER

4 constant PARTICIPANT-CAP-INIT

create PARTICIPANT-BOOT
   PARTICIPANT-CAP-INIT DECLARATION-TRANSACTION:ROW-CELLS * cells allot
create STATE DECLARATION-TRANSACTION:STATE-CELLS cells allot

: INIT ( -- )
   STATE PARTICIPANT-BOOT PARTICIPANT-CAP-INIT
   [: DECLARATION-TRANSACTION:DEFAULT-ALLOCATOR ;]
   [: DECLARATION-TRANSACTION:DEFAULT-DIAGNOSTIC ;]
   DECLARATION-TRANSACTION:INIT ;

1 constant CHECKER-PARTICIPANT
100 constant CHECKER-ORDER

: CHECKER-SNAPSHOT ( n -- n )
   CHECKER-SCOPE-START ;

: CHECKER-PREPARE ( n -- n ) ;
: CHECKER-COMMIT ( n -- n ) ;

: CHECKER-ROLLBACK ( n -- n )
   CHECKER-SCOPE-DONE ;

: CHECKER-FINALIZE ( n -- n )
   CHECKER-SCOPE-FINALIZE ;

: INSTALL-CHECKER ( -- )
   STATE CHECKER-PARTICIPANT CHECKER-ORDER
   [: CHECKER-SNAPSHOT ;]
   [: CHECKER-PREPARE ;]
   [: CHECKER-COMMIT ;]
   [: CHECKER-ROLLBACK ;]
   [: CHECKER-FINALIZE ;]
   DECLARATION-TRANSACTION:REGISTER ;

public

: REGISTER
   ( n n [ n -- n ] [ n -- n ] [ n -- n ] [ n -- n ] [ n -- n ] -- )
   {: id:n order:n snapshot prepare commit rollback finalize :} \ typed-local-lint: allow-bare-local
   STATE id order snapshot prepare commit rollback finalize
   DECLARATION-TRANSACTION:REGISTER ;

: REGISTER-LAST
   ( n n [ n -- n ] [ n -- n ] [ n -- n ] [ n -- n ] [ n -- n ] -- )
   REGISTER
   STATE DECLARATION-TRANSACTION:SEAL ;

: RUN ( [ -- ] -- )
   STATE DECLARATION-TRANSACTION:SEALED? 0=
      IF DECLARATION-TRANSACTION:E-REGISTRATION-SEALED throw THEN
   STATE swap DECLARATION-TRANSACTION:RUN ;

: COUNT ( -- n ) STATE DECLARATION-TRANSACTION:COUNT ;
: DEPTH ( -- n ) STATE DECLARATION-TRANSACTION:DEPTH ;
: SEALED? ( -- bool ) STATE DECLARATION-TRANSACTION:SEALED? ;
: POISONED? ( -- bool ) STATE DECLARATION-TRANSACTION:POISONED? ;
: LAST-FAILURE-PHASE ( -- n ) STATE DECLARATION-TRANSACTION:LAST-FAILURE-PHASE ;
: LAST-FAILURE-PARTICIPANT ( -- n ) STATE DECLARATION-TRANSACTION:LAST-FAILURE-PARTICIPANT ;
: LAST-CLEANUP-PARTICIPANT ( -- n ) STATE DECLARATION-TRANSACTION:LAST-CLEANUP-PARTICIPANT ;

private

INIT
INSTALL-CHECKER
get-current prot-wid-add

;package

package GENERATED-DECL

public

DECLARATION-TRANSACTION:E-PARTICIPANT-DUP constant E-PARTICIPANT-DUP
DECLARATION-TRANSACTION:E-REGISTRATION-ACTIVE constant E-REGISTRATION-ACTIVE
DECLARATION-TRANSACTION:E-TRANSACTION-POISONED constant E-TRANSACTION-POISONED
DECLARATION-TRANSACTION:E-REGISTRATION-SEALED constant E-REGISTRATION-SEALED

100 constant ORDER-CHECKER
800 constant ORDER-EVENT
850 constant ORDER-DICTIONARY
900 constant ORDER-PROTECTION

DECLARATION-TRANSACTION:PHASE-SNAPSHOT constant PHASE-SNAPSHOT
DECLARATION-TRANSACTION:PHASE-BODY constant PHASE-BODY
DECLARATION-TRANSACTION:PHASE-PREPARE constant PHASE-PREPARE
DECLARATION-TRANSACTION:PHASE-COMMIT constant PHASE-COMMIT
DECLARATION-TRANSACTION:PHASE-ROLLBACK constant PHASE-ROLLBACK
DECLARATION-TRANSACTION:PHASE-FINALIZE constant PHASE-FINALIZE

: RUN ( [ -- ] -- ) GENERATED-DECL-OWNER:RUN ;
: COUNT ( -- n ) GENERATED-DECL-OWNER:COUNT ;
: DEPTH ( -- n ) GENERATED-DECL-OWNER:DEPTH ;
: SEALED? ( -- bool ) GENERATED-DECL-OWNER:SEALED? ;
: POISONED? ( -- bool ) GENERATED-DECL-OWNER:POISONED? ;
: LAST-FAILURE-PHASE ( -- n ) GENERATED-DECL-OWNER:LAST-FAILURE-PHASE ;
: LAST-FAILURE-PARTICIPANT ( -- n ) GENERATED-DECL-OWNER:LAST-FAILURE-PARTICIPANT ;
: LAST-CLEANUP-PARTICIPANT ( -- n ) GENERATED-DECL-OWNER:LAST-CLEANUP-PARTICIPANT ;

private

TRUSTED: INSTALL-DECLARATION-RUNNER ( -- )
   [: GENERATED-DECL-OWNER:RUN ;] is TDECL-TXN-XT
   -1 TDECL-TXN-ARMED ! ;

INSTALL-DECLARATION-RUNNER
get-current prot-wid-add

;package
