\ roles.f — nominal scalar role conversions baked into hb.
\
\ The checker treats roles such as idx/len/fd as distinct nominal cell types.
\ Runtime representation is still one cell, so these conversion bodies are no-op
\ casts. Their effects are pinned by TRUST rows and covered by the engine gate.

\ `deftype NAME` registers a fresh nominal cell type (distinct from n and from
\ every other nominal, no widening) and auto-derives its explicit converter pair
\ >NAME ( n -- NAME ) and NAME>N ( NAME -- n ) as no-op casts, matching the
\ built-in role pattern (>IDX / IDX>N). The converters are the only way across the
\ boundary; the checker never collapses a nominal to n. Each pair is generated by
\ evaluating a TRUSTED: shape (the text lives in string literals, so no static
\ trust site is added per declaration — it is one runtime cast per direction,
\ audited exactly like the built-in role casts).
$200 constant DTC-CAP
create DTC-BUF DTC-CAP allot
variable DTC-U
variable DTC-NAME-OFF
variable DTC-NAME-U
variable DTC-SIG-OFF
variable DTC-SIG-U

: DTC-CLEAR ( -- ) 0 DTC-U ! ;

: DTC+ ( ptr u8 n -- ) {: a:ptr u:n :}
   DTC-U @ u + DTC-CAP > IF s" deftype: converter text too long" 70 die THEN
   0 BEGIN dup u < WHILE
      dup a + c@  DTC-BUF DTC-U @ + c!
      DTC-U @ 1 + DTC-U !  1+
   REPEAT drop ;

\ The one metaprogramming boundary: `evaluate` cannot be checker-typed, so the
\ audited TRUSTED wrapper compiles the constructed TRUSTED: converter shape. Each
\ generated converter is a proven no-op identity cast (n<->NAME), correct by
\ construction, so this single boundary covers every deftype-derived pair.
TRUSTED: DTC-EVAL ( -- ) DTC-BUF DTC-U @ evaluate ;

: DTC-NAME$ ( -- ptr u8 n )
   DTC-BUF DTC-NAME-OFF @ + DTC-NAME-U @ ;

: DTC-SIG$ ( -- ptr u8 n )
   DTC-BUF DTC-SIG-OFF @ + DTC-SIG-U @ ;

: DTC-BEGIN ( -- )
   DTC-CLEAR
   s" TRUSTED: " DTC+
   DTC-U @ DTC-NAME-OFF ! ;

: DTC-NAME-END ( -- )
   DTC-U @ DTC-NAME-OFF @ - DTC-NAME-U !
   s"  ( " DTC+
   DTC-U @ DTC-SIG-OFF ! ;

: DTC-SIG-END ( -- )
   DTC-U @ DTC-SIG-OFF @ - DTC-SIG-U !
   s"  ) ;" DTC+ ;

: DTC-BUILD-IN ( ptr u8 n -- ) {: name:ptr nameu:n :}
   DTC-BEGIN
   s" >" DTC+ name nameu DTC+ DTC-NAME-END
   s" n -- " DTC+ name nameu DTC+ DTC-SIG-END ;

: DTC-BUILD-OUT ( ptr u8 n -- ) {: name:ptr nameu:n :}
   DTC-BEGIN
   name nameu DTC+ s" >N" DTC+ DTC-NAME-END
   name nameu DTC+ s"  -- n" DTC+ DTC-SIG-END ;

: DEFTYPE-CAST-IN ( ptr u8 n -- )   \ TRUSTED: >NAME ( n -- NAME ) ;
   DTC-BUILD-IN
   DTC-EVAL ;

: DEFTYPE-CAST-OUT ( ptr u8 n -- )   \ TRUSTED: NAME>N ( NAME -- n ) ;
   DTC-BUILD-OUT
   DTC-EVAL ;

: DEFTYPE ( -- )
   parse-name dup 0= IF s" deftype: missing name" 70 die THEN
   2dup CHECKER-DEFTYPE
   2dup DEFTYPE-CAST-IN
   DEFTYPE-CAST-OUT ;

TRUSTED: >IDX ( n -- idx ) ;
TRUSTED: IDX>N ( idx -- n ) ;

TRUSTED: >LEN ( n -- len ) ;
TRUSTED: LEN>N ( len -- n ) ;

TRUSTED: >COUNT ( n -- count ) ;
TRUSTED: COUNT>N ( count -- n ) ;

TRUSTED: >OFF ( n -- off ) ;
TRUSTED: OFF>N ( off -- n ) ;

TRUSTED: >FD ( n -- fd ) ;
TRUSTED: FD>N ( fd -- n ) ;

TRUSTED: >RC ( n -- rc ) ;
TRUSTED: RC>N ( rc -- n ) ;

TRUSTED: >PID ( n -- pid ) ;
TRUSTED: PID>N ( pid -- n ) ;

TRUSTED: >MS ( n -- ms ) ;
TRUSTED: MS>N ( ms -- n ) ;

TRUSTED: >NS ( n -- ns ) ;
TRUSTED: NS>N ( ns -- n ) ;

TRUSTED: >TOK ( n -- tok ) ;
TRUSTED: TOK>N ( tok -- n ) ;

TRUSTED: >REG ( n -- reg ) ;
TRUSTED: REG>N ( reg -- n ) ;

TRUSTED: >LABEL ( n -- label ) ;
TRUSTED: LABEL>N ( label -- n ) ;

TRUSTED: >VA ( n -- va ) ;
TRUSTED: VA>N ( va -- n ) ;

TRUSTED: >SYMIDX ( n -- symidx ) ;
TRUSTED: SYMIDX>N ( symidx -- n ) ;

TRUSTED: >ASM ( n -- asm ) ;
TRUSTED: ASM>N ( asm -- n ) ;

TRUSTED: >IMG ( n -- img ) ;
TRUSTED: IMG>N ( img -- n ) ;

TRUSTED: >SNAP ( n -- snap ) ;
TRUSTED: SNAP>N ( snap -- n ) ;

: ASM-PHASE ( -- asm )
   0 >ASM ;

: ASM-DROP ( asm -- )
   ASM>N drop ;

: IMG-PHASE ( -- img )
   0 >IMG ;

: IMG-DROP ( img -- )
   IMG>N drop ;

: SNAP-PHASE ( -- snap )
   0 >SNAP ;

: SNAP-DROP ( snap -- )
   SNAP>N drop ;

: DEFLINEAR ( -- )
   parse-name dup 0= IF s" deflinear: missing name" 70 die THEN
   CHECKER-DEFLINEAR ;

$1000 constant VRDEF-CAP
create VRDEF-BUF VRDEF-CAP allot
variable VRDEF-U
variable VRDEF-I

: VRDEF-CLEAR ( -- )
   0 VRDEF-U ! ;

: VRDEF-ROOM ( n -- )
   VRDEF-U @ + VRDEF-CAP > IF
      s" value-record: field list too long" 70 die
   THEN ;

: VRDEF-C, ( n -- )
   1 VRDEF-ROOM
   VRDEF-BUF VRDEF-U @ + c!
   VRDEF-U @ 1 + VRDEF-U ! ;

: VRDEF-SPACE ( -- )
   VRDEF-U @ 0 > IF 32 VRDEF-C, THEN ;

: VRDEF-APP ( ptr u8 n -- ) {: a:ptr u:n :}
   u VRDEF-ROOM
   0 VRDEF-I !
   BEGIN VRDEF-I @ u < WHILE
      a VRDEF-I @ + c@ VRDEF-C,
      VRDEF-I @ 1 + VRDEF-I !
   REPEAT ;

: VRDEF-TOKEN+ ( ptr u8 n -- )
   VRDEF-SPACE
   VRDEF-APP ;

: VRDEF-FOLD-C ( n -- n )
   dup $41 < IF EXIT THEN
   dup $5A > IF EXIT THEN
   $20 or ;

: VRDEF-STR=CI ( ptr u8 n ptr u8 n -- bool ) {: a:ptr u:n b:ptr v:n :}
   u v <> IF 0 0= 0= EXIT THEN
   0 BEGIN dup u < WHILE
      dup a + c@ VRDEF-FOLD-C
      over b + c@ VRDEF-FOLD-C <> IF drop 0 0= 0= EXIT THEN
      1+
   REPEAT drop 0 0= ;

: VRDEF-END? ( ptr u8 n -- bool )
   s" END-VALUE-RECORD" VRDEF-STR=CI ;

: VALUE-RECORD ( -- )
   parse-name dup 0= IF
      s" value-record: missing name" 70 die
   THEN
   {: name:ptr nameu:n :}
   VRDEF-CLEAR
   BEGIN
      parse-name dup 0= IF
         s" value-record: missing END-VALUE-RECORD" 70 die
      THEN
      2dup VRDEF-END? IF
         2drop
         name nameu VRDEF-BUF VRDEF-U @ CHECKER-DEFRECORD
         EXIT
      THEN
      VRDEF-TOKEN+
   AGAIN ;
