\ gpt2-attention-launch-test.f - host checks for GPT-2 attention launch sizing.

require lib/test.f
require maki/infer/gpt2-attention-cg.f

package GPT2-ATTN-LAUNCH-TEST

$FFFFFFFF constant U32-MAX
$7FFFFFFFFFFFFFFF constant CELL-MAX
$7FFFFFFF constant GRID-X-MAX
128 constant BLOCK
U32-MAX BLOCK 1- - constant STRIDE-MAX
U32-MAX 4 / 1- constant SHARED-CAP-MAX
CELL-MAX 4 / STRIDE-MAX / constant ROW-HEAD-MAX
CELL-MAX 2 / 4 / STRIDE-MAX / constant CACHE-HEAD-MAX

: CHECK ( n n n n -- )
   GPT2-ATTN:LAUNCH-CHECK drop drop drop ;

: GRID-OVER ( -- ) 0 GRID-X-MAX 1+ 1 1 CHECK ;
: WIDTH-OVER ( -- ) 0 1 $FFFFFF81 1 CHECK ;
: CAP-STRIDE-OVER ( -- ) 0 1 1 STRIDE-MAX 1+ CHECK ;
: ROW-OVER ( -- ) 0 ROW-HEAD-MAX 1+ STRIDE-MAX 1 CHECK ;
: CACHE-OVER ( -- ) 0 CACHE-HEAD-MAX 1+ STRIDE-MAX 2 CHECK ;
: SHARED-OVER ( -- ) 0 1 1 SHARED-CAP-MAX 1+ CHECK ;

: NEG-POS ( -- ) -1 12 64 17 CHECK ;
: END-POS ( -- ) 17 12 64 17 CHECK ;
: ZERO-HEADS ( -- ) 0 0 64 17 CHECK ;
: ZERO-WIDTH ( -- ) 0 12 0 17 CHECK ;
: ZERO-CAP ( -- ) 0 12 64 0 CHECK ;

: RUN ( -- )
   T-RESET

   0 12 64 17 GPT2-ATTN:LAUNCH-CHECK
   72 T= 52224 T= 3072 T=

   0 GRID-X-MAX 1 1 CHECK
   0 1 STRIDE-MAX 1 CHECK
   0 ROW-HEAD-MAX STRIDE-MAX 1 CHECK
   0 CACHE-HEAD-MAX STRIDE-MAX 2 CHECK
   0 1 1 SHARED-CAP-MAX CHECK

   [: GRID-OVER ;] E-PTX-BLOCK TTHROWSQ
   [: WIDTH-OVER ;] E-PTX-BLOCK TTHROWSQ
   [: CAP-STRIDE-OVER ;] E-PTX-BLOCK TTHROWSQ
   [: ROW-OVER ;] E-PTX-BLOCK TTHROWSQ
   [: CACHE-OVER ;] E-PTX-BLOCK TTHROWSQ
   [: SHARED-OVER ;] E-PTX-BLOCK TTHROWSQ

   [: NEG-POS ;] E-PTX-BLOCK TTHROWSQ
   [: END-POS ;] E-PTX-BLOCK TTHROWSQ
   [: ZERO-HEADS ;] E-PTX-BLOCK TTHROWSQ
   [: ZERO-WIDTH ;] E-PTX-BLOCK TTHROWSQ
   [: ZERO-CAP ;] E-PTX-BLOCK TTHROWSQ

   T-REPORT ;

RUN

;package
