#!/bin/sh
set -eu

cd "$(dirname "$0")/.."

usage() {
  echo "usage: tools/bundle-lib.sh [-o out.f] module... -- script.f" >&2
  exit 64
}

fail() {
  echo "bundle-lib.sh: $1" >&2
  exit "${2:-1}"
}

valid_module() {
  case "$1" in
    [abcdefghijklmnopqrstuvwxyz]*) ;;
    *) return 1 ;;
  esac
  case "$1" in
    *[!abcdefghijklmnopqrstuvwxyz0123456789-]*) return 1 ;;
    *) return 0 ;;
  esac
}

OUT=
MODULES=

while [ "$#" -gt 0 ]; do
  case "$1" in
    -o)
      shift
      [ "$#" -gt 0 ] || usage
      OUT=$1
      shift
      ;;
    --)
      shift
      break
      ;;
    -*)
      usage
      ;;
    *)
      valid_module "$1" || fail "invalid module: $1" 64
      MODULES="${MODULES}${MODULES:+ }$1"
      shift
      ;;
  esac
done

[ -n "$MODULES" ] || usage
[ "$#" -eq 1 ] || usage

SCRIPT=$1
[ -f "$SCRIPT" ] || fail "missing script: $SCRIPT" 66

for module in $MODULES; do
  path="lib/$module.f"
  [ -f "$path" ] || fail "missing module: $module ($path)" 66
done

emit_bundle() {
  printf '\\ generated by tools/bundle-lib.sh\n'
  for module in $MODULES; do
    path="lib/$module.f"
    printf '\\ BEGIN %s\n' "$path"
    cat "$path"
    printf '\n\\ END %s\n' "$path"
  done
  printf '\\ BEGIN %s\n' "$SCRIPT"
  cat "$SCRIPT"
  printf '\n\\ END %s\n' "$SCRIPT"
}

if [ -n "$OUT" ]; then
  OUT_DIR=$(dirname "$OUT")
  [ -d "$OUT_DIR" ] || fail "missing output directory: $OUT_DIR" 66
  TMP=$(mktemp "$OUT_DIR/.bundle-lib.XXXXXX")
  cleanup() {
    rm -f "$TMP"
  }
  trap cleanup EXIT HUP INT TERM
  emit_bundle > "$TMP"
  mv "$TMP" "$OUT"
  trap - EXIT HUP INT TERM
else
  emit_bundle
fi
