\ codegen-compare-c4.f - the clang reference column of the FOURTH comparison.
\ One concern: which C twin stands for which of the pinned twelve, and on which
\ inputs.
\
\ THIS IS THE CORPUS THAT WAS CHOSEN TO BE HARD, so it is the one whose
\ reference column is worth the most: every row here was picked because somebody
\ believed the chain handles it badly, and the third column says whether the
\ shape is hard for a code generator or only for this one. The two rows with
\ nine arguments cross the register boundary the AAPCS64 call has - eight in
\ registers and the ninth on the stack - which is a cost the reference pays and
\ the two habu columns, whose arguments arrive in data-stack slots, do not; the
\ per-row floor takes it off both sides, because the floor is the same nine
\ arguments marshalled into the same places with an empty callee.

require lib/errors.f
require lib/prelude.f
require lib/string.f
require tools/codegen-compare-core.f
require tools/codegen-compare-cabi.f
require tools/codegen-compare-clang.f

package CODEGEN-C4

private

variable REC
variable STEP

8 constant LOOP-LEN
0 constant NO-LEN

: PREPARE ( -- )
   s" hc4_rec_ptr" CODEGEN-CABI:FN CODEGEN-CABI:I0 REC !
   s" hc4_step_ptr" CODEGEN-CABI:FN CODEGEN-CABI:I0 STEP ! ;

: S-RESET ( -- )
   s" hc4_step_reset" CODEGEN-CABI:FN CODEGEN-CABI:I0 drop ;

: STEP-CELL@ ( n -- n )
   s" hc4_step_get" CODEGEN-CABI:FN CODEGEN-CABI:I1 ;

: CALL-FAN-CASE ( -- )
   s" CODEGEN-CORPUS4:CALL-FAN" s" hc4_call_fan" s" hf_i1"
   [: 7 CODEGEN-CLANG:FN@ CODEGEN-CABI:I1 drop ;]
   [: 7 CODEGEN-CLANG:FN@ CODEGEN-CABI:I1 CODEGEN-COMPARE:VECTOR
      0 CODEGEN-CLANG:FN@ CODEGEN-CABI:I1 CODEGEN-COMPARE:VECTOR
      -1 CODEGEN-CLANG:FN@ CODEGEN-CABI:I1 CODEGEN-COMPARE:VECTOR
      255 CODEGEN-CLANG:FN@ CODEGEN-CABI:I1 CODEGEN-COMPARE:VECTOR ;]
   CODEGEN-CLANG:MEASURE ;

: CALL-FAN-BIG-CASE ( -- )
   s" CODEGEN-CORPUS4:CALL-FAN-BIG" s" hc4_call_fan_big" s" hf_i1"
   [: 7 CODEGEN-CLANG:FN@ CODEGEN-CABI:I1 drop ;]
   [: 7 CODEGEN-CLANG:FN@ CODEGEN-CABI:I1 CODEGEN-COMPARE:VECTOR
      0 CODEGEN-CLANG:FN@ CODEGEN-CABI:I1 CODEGEN-COMPARE:VECTOR
      -1 CODEGEN-CLANG:FN@ CODEGEN-CABI:I1 CODEGEN-COMPARE:VECTOR
      255 CODEGEN-CLANG:FN@ CODEGEN-CABI:I1 CODEGEN-COMPARE:VECTOR ;]
   CODEGEN-CLANG:MEASURE ;

: CALL-LOOP-3-CASE ( -- )
   s" CODEGEN-CORPUS4:CALL-LOOP-3" s" hc4_call_loop_3" s" hf_i5"
   [: 1 2 3 7 LOOP-LEN CODEGEN-CLANG:FN@ CODEGEN-CABI:I5 drop ;]
   [: 1 2 3 7 LOOP-LEN CODEGEN-CLANG:FN@ CODEGEN-CABI:I5
      CODEGEN-COMPARE:VECTOR
      1 2 3 7 NO-LEN CODEGEN-CLANG:FN@ CODEGEN-CABI:I5
      CODEGEN-COMPARE:VECTOR
      -1 -2 -3 -7 LOOP-LEN CODEGEN-CLANG:FN@ CODEGEN-CABI:I5
      CODEGEN-COMPARE:VECTOR ;]
   CODEGEN-CLANG:MEASURE ;

: CALL-PRESSURE-CASE ( -- )
   s" CODEGEN-CORPUS4:CALL-PRESSURE" s" hc4_call_pressure" s" hf_i9"
   [: 1 2 3 4 5 6 7 9 LOOP-LEN CODEGEN-CLANG:FN@ CODEGEN-CABI:I9 drop ;]
   [: 1 2 3 4 5 6 7 9 LOOP-LEN CODEGEN-CLANG:FN@ CODEGEN-CABI:I9
      CODEGEN-COMPARE:VECTOR
      1 2 3 4 5 6 7 9 NO-LEN CODEGEN-CLANG:FN@ CODEGEN-CABI:I9
      CODEGEN-COMPARE:VECTOR
      -1 -2 -3 -4 -5 -6 -7 -9 LOOP-LEN CODEGEN-CLANG:FN@ CODEGEN-CABI:I9
      CODEGEN-COMPARE:VECTOR ;]
   CODEGEN-CLANG:MEASURE ;

: TINY-CALLEE-CASE ( -- )
   s" CODEGEN-CORPUS4:TINY-CALLEE" s" hc4_tiny_callee" s" hf_i2"
   [: 0 LOOP-LEN CODEGEN-CLANG:FN@ CODEGEN-CABI:I2 drop ;]
   [: 0 LOOP-LEN CODEGEN-CLANG:FN@ CODEGEN-CABI:I2 CODEGEN-COMPARE:VECTOR
      5 NO-LEN CODEGEN-CLANG:FN@ CODEGEN-CABI:I2 CODEGEN-COMPARE:VECTOR
      -3 LOOP-LEN CODEGEN-CLANG:FN@ CODEGEN-CABI:I2 CODEGEN-COMPARE:VECTOR ;]
   CODEGEN-CLANG:MEASURE ;

: WIDE-ARITY-CASE ( -- )
   s" CODEGEN-CORPUS4:WIDE-ARITY" s" hc4_wide_arity" s" hf_i6"
   [: 1 2 3 4 5 6 CODEGEN-CLANG:FN@ CODEGEN-CABI:I6 drop ;]
   [: 1 2 3 4 5 6 CODEGEN-CLANG:FN@ CODEGEN-CABI:I6 CODEGEN-COMPARE:VECTOR
      6 5 4 3 2 1 CODEGEN-CLANG:FN@ CODEGEN-CABI:I6 CODEGEN-COMPARE:VECTOR
      0 0 0 0 0 0 CODEGEN-CLANG:FN@ CODEGEN-CABI:I6 CODEGEN-COMPARE:VECTOR
      -1 -2 -3 -4 -5 -6 CODEGEN-CLANG:FN@ CODEGEN-CABI:I6
      CODEGEN-COMPARE:VECTOR ;]
   CODEGEN-CLANG:MEASURE ;

: LADDER-CASE ( -- )
   s" CODEGEN-CORPUS4:LADDER" s" hc4_ladder" s" hf_i1"
   [: 1000 CODEGEN-CLANG:FN@ CODEGEN-CABI:I1 drop ;]
   [: -5 CODEGEN-CLANG:FN@ CODEGEN-CABI:I1 CODEGEN-COMPARE:VECTOR
      0 CODEGEN-CLANG:FN@ CODEGEN-CABI:I1 CODEGEN-COMPARE:VECTOR
      1 CODEGEN-CLANG:FN@ CODEGEN-CABI:I1 CODEGEN-COMPARE:VECTOR
      3 CODEGEN-CLANG:FN@ CODEGEN-CABI:I1 CODEGEN-COMPARE:VECTOR
      20 CODEGEN-CLANG:FN@ CODEGEN-CABI:I1 CODEGEN-COMPARE:VECTOR
      100 CODEGEN-CLANG:FN@ CODEGEN-CABI:I1 CODEGEN-COMPARE:VECTOR
      127 CODEGEN-CLANG:FN@ CODEGEN-CABI:I1 CODEGEN-COMPARE:VECTOR
      1000 CODEGEN-CLANG:FN@ CODEGEN-CABI:I1 CODEGEN-COMPARE:VECTOR ;]
   CODEGEN-CLANG:MEASURE ;

: PRESSURE-LOOP-CASE ( -- )
   s" CODEGEN-CORPUS4:PRESSURE-LOOP" s" hc4_pressure_loop" s" hf_i2"
   [: REC @ LOOP-LEN CODEGEN-CLANG:FN@ CODEGEN-CABI:I2 drop ;]
   [: REC @ LOOP-LEN CODEGEN-CLANG:FN@ CODEGEN-CABI:I2 CODEGEN-COMPARE:VECTOR
      REC @ NO-LEN CODEGEN-CLANG:FN@ CODEGEN-CABI:I2 CODEGEN-COMPARE:VECTOR ;]
   CODEGEN-CLANG:MEASURE ;

: BIG-CONSTS-CASE ( -- )
   s" CODEGEN-CORPUS4:BIG-CONSTS" s" hc4_big_consts" s" hf_i1"
   [: LOOP-LEN CODEGEN-CLANG:FN@ CODEGEN-CABI:I1 drop ;]
   [: LOOP-LEN CODEGEN-CLANG:FN@ CODEGEN-CABI:I1 CODEGEN-COMPARE:VECTOR
      0 CODEGEN-CLANG:FN@ CODEGEN-CABI:I1 CODEGEN-COMPARE:VECTOR
      1 CODEGEN-CLANG:FN@ CODEGEN-CABI:I1 CODEGEN-COMPARE:VECTOR ;]
   CODEGEN-CLANG:MEASURE ;

: MANY-LOCALS-CASE ( -- )
   s" CODEGEN-CORPUS4:MANY-LOCALS" s" hc4_many_locals" s" hf_i9"
   [: 1 2 3 4 5 6 7 8 LOOP-LEN CODEGEN-CLANG:FN@ CODEGEN-CABI:I9 drop ;]
   [: 1 2 3 4 5 6 7 8 LOOP-LEN CODEGEN-CLANG:FN@ CODEGEN-CABI:I9
      CODEGEN-COMPARE:VECTOR
      1 2 3 4 5 6 7 8 NO-LEN CODEGEN-CLANG:FN@ CODEGEN-CABI:I9
      CODEGEN-COMPARE:VECTOR
      -1 2 -3 4 -5 6 -7 8 LOOP-LEN CODEGEN-CLANG:FN@ CODEGEN-CABI:I9
      CODEGEN-COMPARE:VECTOR ;]
   CODEGEN-CLANG:MEASURE ;

: FLOAT-MIX-CASE ( -- )
   s" CODEGEN-CORPUS4:FLOAT-MIX" s" hc4_float_mix" s" hf_i2"
   [: 0 LOOP-LEN CODEGEN-CLANG:FN@ CODEGEN-CABI:I2 drop ;]
   [: 0 LOOP-LEN CODEGEN-CLANG:FN@ CODEGEN-CABI:I2 CODEGEN-COMPARE:VECTOR
      0 NO-LEN CODEGEN-CLANG:FN@ CODEGEN-CABI:I2 CODEGEN-COMPARE:VECTOR
      -100 3 CODEGEN-CLANG:FN@ CODEGEN-CABI:I2 CODEGEN-COMPARE:VECTOR ;]
   CODEGEN-CLANG:MEASURE ;

\ The row whose point is a side effect: the cell the run stepped and the cell
\ after it, which it must not have, then a run of no turns from the refilled
\ cell.
: STORE-LOAD-CASE ( -- )
   s" CODEGEN-CORPUS4:STORE-LOAD" s" hc4_store_load" s" hf_i2"
   [: STEP @ LOOP-LEN CODEGEN-CLANG:FN@ CODEGEN-CABI:I2 drop ;]
   [: S-RESET
      STEP @ LOOP-LEN CODEGEN-CLANG:FN@ CODEGEN-CABI:I2 CODEGEN-COMPARE:VECTOR
      0 STEP-CELL@ CODEGEN-COMPARE:VECTOR
      1 STEP-CELL@ CODEGEN-COMPARE:VECTOR
      S-RESET
      STEP @ NO-LEN CODEGEN-CLANG:FN@ CODEGEN-CABI:I2 CODEGEN-COMPARE:VECTOR ;]
   CODEGEN-CLANG:MEASURE ;

public

: RUN ( -- )
   CODEGEN-CLANG:PRESENT? 0= if exit then
   PREPARE
   CODEGEN-CLANG:CALIBRATE
   CALL-FAN-CASE
   CALL-FAN-BIG-CASE
   CALL-LOOP-3-CASE
   CALL-PRESSURE-CASE
   TINY-CALLEE-CASE
   WIDE-ARITY-CASE
   LADDER-CASE
   PRESSURE-LOOP-CASE
   BIG-CONSTS-CASE
   MANY-LOCALS-CASE
   FLOAT-MIX-CASE
   STORE-LOAD-CASE ;

;package
