\ codegen-compare-c3.f - the clang reference column of the THIRD comparison.
\ One concern: which C twin stands for which of the pinned ten float rows, and
\ on which inputs.
\
\ THE ANSWERS ARE COMPARED BIT FOR BIT, which is why the build passes no
\ fast-math flag: every recorded double goes through VECTOR-REAL, which records
\ the whole cell, so a reference that reassociated a sum or flushed a subnormal
\ would disagree with the engine and be reported as a wrong answer rather than
\ as a faster number. The pinned inputs include both zeros, a NaN in each
\ argument position and an infinity for the same reason the corpus states at its
\ own head: those are where two float programs that look alike stop agreeing.
\
\ THE STEP RESETS AND THE TIMED BODY DOES NOT, exactly as the engine's row does:
\ the twin's weight buffer is refilled before the recorded call, so the row
\ records one step from the pinned weights however many timing runs came first,
\ and the timed body calls the step alone so that what is timed is a step and not
\ a fill.

require lib/errors.f
require lib/prelude.f
require lib/string.f
require tools/codegen-compare-core.f
require tools/codegen-compare-cabi.f
require tools/codegen-compare-clang.f

package CODEGEN-C3

private

variable A-VEC
variable B-VEC
variable Z-VEC
variable S-VEC
variable W-VEC
variable G-VEC

4 constant VEC-LEN
3 constant SUM-LEN
0 constant NO-LEN
9007199254740993 constant WIDE-INT   \ 2^53+1, the smallest integer a double cannot hold

: NAN ( -- r )
   0.0 0.0 f/ ;

: INF ( -- r )
   1.0 0.0 f/ ;

: PREPARE ( -- )
   s" hc3_a_ptr" CODEGEN-CABI:FN CODEGEN-CABI:I0 A-VEC !
   s" hc3_b_ptr" CODEGEN-CABI:FN CODEGEN-CABI:I0 B-VEC !
   s" hc3_z_ptr" CODEGEN-CABI:FN CODEGEN-CABI:I0 Z-VEC !
   s" hc3_s_ptr" CODEGEN-CABI:FN CODEGEN-CABI:I0 S-VEC !
   s" hc3_w_ptr" CODEGEN-CABI:FN CODEGEN-CABI:I0 W-VEC !
   s" hc3_g_ptr" CODEGEN-CABI:FN CODEGEN-CABI:I0 G-VEC ! ;

: W-RESET ( -- )
   s" hc3_w_reset" CODEGEN-CABI:FN CODEGEN-CABI:I0 drop ;

: W-CELL ( n -- r )
   s" hc3_w_get" CODEGEN-CABI:FN CODEGEN-CABI:ID ;

: T-SUM-CASE ( -- )
   s" CODEGEN-CORPUS3:T-SUM" s" hc3_t_sum" s" hf_iid"
   [: A-VEC @ VEC-LEN CODEGEN-CLANG:FN@ CODEGEN-CABI:IID drop ;]
   [: A-VEC @ VEC-LEN CODEGEN-CLANG:FN@ CODEGEN-CABI:IID
      CODEGEN-COMPARE:VECTOR-REAL
      S-VEC @ SUM-LEN CODEGEN-CLANG:FN@ CODEGEN-CABI:IID
      CODEGEN-COMPARE:VECTOR-REAL
      A-VEC @ NO-LEN CODEGEN-CLANG:FN@ CODEGEN-CABI:IID
      CODEGEN-COMPARE:VECTOR-REAL ;]
   CODEGEN-CLANG:MEASURE ;

: T-DIST2-CASE ( -- )
   s" CODEGEN-CORPUS3:T-DIST2" s" hc3_t_dist2" s" hf_iiid"
   [: A-VEC @ B-VEC @ VEC-LEN CODEGEN-CLANG:FN@ CODEGEN-CABI:IIID drop ;]
   [: A-VEC @ B-VEC @ VEC-LEN CODEGEN-CLANG:FN@ CODEGEN-CABI:IIID
      CODEGEN-COMPARE:VECTOR-REAL
      B-VEC @ B-VEC @ VEC-LEN CODEGEN-CLANG:FN@ CODEGEN-CABI:IIID
      CODEGEN-COMPARE:VECTOR-REAL
      A-VEC @ B-VEC @ NO-LEN CODEGEN-CLANG:FN@ CODEGEN-CABI:IIID
      CODEGEN-COMPARE:VECTOR-REAL ;]
   CODEGEN-CLANG:MEASURE ;

: T-NORM2-CASE ( -- )
   s" CODEGEN-CORPUS3:T-NORM2" s" hc3_t_norm2" s" hf_iid"
   [: A-VEC @ VEC-LEN CODEGEN-CLANG:FN@ CODEGEN-CABI:IID drop ;]
   [: A-VEC @ VEC-LEN CODEGEN-CLANG:FN@ CODEGEN-CABI:IID
      CODEGEN-COMPARE:VECTOR-REAL
      Z-VEC @ VEC-LEN CODEGEN-CLANG:FN@ CODEGEN-CABI:IID
      CODEGEN-COMPARE:VECTOR-REAL
      A-VEC @ NO-LEN CODEGEN-CLANG:FN@ CODEGEN-CABI:IID
      CODEGEN-COMPARE:VECTOR-REAL ;]
   CODEGEN-CLANG:MEASURE ;

: T-SGD-CASE ( -- )
   s" CODEGEN-CORPUS3:T-SGD!" s" hc3_t_sgd" s" hf_diii"
   [: 0.25 W-VEC @ G-VEC @ VEC-LEN CODEGEN-CLANG:FN@ CODEGEN-CABI:DIII drop ;]
   [: W-RESET
      0.25 W-VEC @ G-VEC @ VEC-LEN CODEGEN-CLANG:FN@ CODEGEN-CABI:DIII drop
      0 W-CELL CODEGEN-COMPARE:VECTOR-REAL
      1 W-CELL CODEGEN-COMPARE:VECTOR-REAL
      2 W-CELL CODEGEN-COMPARE:VECTOR-REAL
      3 W-CELL CODEGEN-COMPARE:VECTOR-REAL
      4 W-CELL CODEGEN-COMPARE:VECTOR-REAL ;]
   CODEGEN-CLANG:MEASURE ;

: T-REL-L2-CASE ( -- )
   s" CODEGEN-CORPUS3:T-REL-L2" s" hc3_t_rel_l2" s" hf_iiid"
   [: A-VEC @ B-VEC @ VEC-LEN CODEGEN-CLANG:FN@ CODEGEN-CABI:IIID drop ;]
   [: A-VEC @ B-VEC @ VEC-LEN CODEGEN-CLANG:FN@ CODEGEN-CABI:IIID
      CODEGEN-COMPARE:VECTOR-REAL
      B-VEC @ B-VEC @ VEC-LEN CODEGEN-CLANG:FN@ CODEGEN-CABI:IIID
      CODEGEN-COMPARE:VECTOR-REAL
      A-VEC @ Z-VEC @ VEC-LEN CODEGEN-CLANG:FN@ CODEGEN-CABI:IIID
      CODEGEN-COMPARE:VECTOR-REAL
      Z-VEC @ Z-VEC @ VEC-LEN CODEGEN-CLANG:FN@ CODEGEN-CABI:IIID
      CODEGEN-COMPARE:VECTOR-REAL ;]
   CODEGEN-CLANG:MEASURE ;

: RELU-CASE ( -- )
   s" CODEGEN-CORPUS3:RELU-F" s" hc3_relu_f" s" hf_dd"
   [: -2.5 CODEGEN-CLANG:FN@ CODEGEN-CABI:DD drop ;]
   [: -2.5 CODEGEN-CLANG:FN@ CODEGEN-CABI:DD CODEGEN-COMPARE:VECTOR-REAL
      0.0 CODEGEN-CLANG:FN@ CODEGEN-CABI:DD CODEGEN-COMPARE:VECTOR-REAL
      -0.0 CODEGEN-CLANG:FN@ CODEGEN-CABI:DD CODEGEN-COMPARE:VECTOR-REAL
      1.5 CODEGEN-CLANG:FN@ CODEGEN-CABI:DD CODEGEN-COMPARE:VECTOR-REAL
      NAN CODEGEN-CLANG:FN@ CODEGEN-CABI:DD CODEGEN-COMPARE:VECTOR-REAL ;]
   CODEGEN-CLANG:MEASURE ;

: MAX-F-CASE ( -- )
   s" CODEGEN-CORPUS3:MAX-F" s" hc3_max_f" s" hf_ddd"
   [: 1.5 -2.5 CODEGEN-CLANG:FN@ CODEGEN-CABI:DDD drop ;]
   [: 1.5 -2.5 CODEGEN-CLANG:FN@ CODEGEN-CABI:DDD CODEGEN-COMPARE:VECTOR-REAL
      -2.5 1.5 CODEGEN-CLANG:FN@ CODEGEN-CABI:DDD CODEGEN-COMPARE:VECTOR-REAL
      0.0 -0.0 CODEGEN-CLANG:FN@ CODEGEN-CABI:DDD CODEGEN-COMPARE:VECTOR-REAL
      -0.0 0.0 CODEGEN-CLANG:FN@ CODEGEN-CABI:DDD CODEGEN-COMPARE:VECTOR-REAL
      NAN 1.5 CODEGEN-CLANG:FN@ CODEGEN-CABI:DDD CODEGEN-COMPARE:VECTOR-REAL
      1.5 NAN CODEGEN-CLANG:FN@ CODEGEN-CABI:DDD CODEGEN-COMPARE:VECTOR-REAL ;]
   CODEGEN-CLANG:MEASURE ;

: SGD-CASE ( -- )
   s" CODEGEN-CORPUS3:SGD" s" hc3_sgd" s" hf_dddd"
   [: 1.0 0.5 0.25 CODEGEN-CLANG:FN@ CODEGEN-CABI:DDDD drop ;]
   [: 1.0 0.5 0.25 CODEGEN-CLANG:FN@ CODEGEN-CABI:DDDD
      CODEGEN-COMPARE:VECTOR-REAL
      -2.0 -0.5 0.25 CODEGEN-CLANG:FN@ CODEGEN-CABI:DDDD
      CODEGEN-COMPARE:VECTOR-REAL
      0.0 0.0 1.0 CODEGEN-CLANG:FN@ CODEGEN-CABI:DDDD
      CODEGEN-COMPARE:VECTOR-REAL
      -0.0 0.0 1.0 CODEGEN-CLANG:FN@ CODEGEN-CABI:DDDD
      CODEGEN-COMPARE:VECTOR-REAL ;]
   CODEGEN-CLANG:MEASURE ;

: SEG-CASE ( -- )
   s" CODEGEN-CORPUS3:SEG-1/SQRT" s" hc3_seg_rsqrt" s" hf_id"
   [: 4 CODEGEN-CLANG:FN@ CODEGEN-CABI:ID drop ;]
   [: 4 CODEGEN-CLANG:FN@ CODEGEN-CABI:ID CODEGEN-COMPARE:VECTOR-REAL
      1 CODEGEN-CLANG:FN@ CODEGEN-CABI:ID CODEGEN-COMPARE:VECTOR-REAL
      2 CODEGEN-CLANG:FN@ CODEGEN-CABI:ID CODEGEN-COMPARE:VECTOR-REAL
      0 CODEGEN-CLANG:FN@ CODEGEN-CABI:ID CODEGEN-COMPARE:VECTOR-REAL
      -4 CODEGEN-CLANG:FN@ CODEGEN-CABI:ID CODEGEN-COMPARE:VECTOR-REAL
      WIDE-INT CODEGEN-CLANG:FN@ CODEGEN-CABI:ID CODEGEN-COMPARE:VECTOR-REAL ;]
   CODEGEN-CLANG:MEASURE ;

\ The one row whose answers are already numbers: the rounding is the way OUT of
\ the float domain, so its outputs go to VECTOR unchanged.
: FROUND-CASE ( -- )
   s" CODEGEN-CORPUS3:FROUND" s" hc3_fround" s" hf_di"
   [: 2.5 CODEGEN-CLANG:FN@ CODEGEN-CABI:DI drop ;]
   [: 2.5 CODEGEN-CLANG:FN@ CODEGEN-CABI:DI CODEGEN-COMPARE:VECTOR
      -2.5 CODEGEN-CLANG:FN@ CODEGEN-CABI:DI CODEGEN-COMPARE:VECTOR
      -0.0 CODEGEN-CLANG:FN@ CODEGEN-CABI:DI CODEGEN-COMPARE:VECTOR
      1.5 CODEGEN-CLANG:FN@ CODEGEN-CABI:DI CODEGEN-COMPARE:VECTOR
      INF CODEGEN-CLANG:FN@ CODEGEN-CABI:DI CODEGEN-COMPARE:VECTOR
      NAN CODEGEN-CLANG:FN@ CODEGEN-CABI:DI CODEGEN-COMPARE:VECTOR ;]
   CODEGEN-CLANG:MEASURE ;

public

: RUN ( -- )
   CODEGEN-CLANG:PRESENT? 0= if exit then
   PREPARE
   CODEGEN-CLANG:CALIBRATE
   T-SUM-CASE
   T-DIST2-CASE
   T-NORM2-CASE
   T-SGD-CASE
   T-REL-L2-CASE
   RELU-CASE
   MAX-F-CASE
   SGD-CASE
   SEG-CASE
   FROUND-CASE ;

;package
