\ compiler-dispatch-test.f - source-shape regression for compiler dispatch factoring.
\ Run: bin/hb --load lib/errors.f lib/string.f lib/test.f lib/fs.f lib/test/src-shape.f tools/compiler-dispatch-test.f

require lib/errors.f
require lib/string.f
require lib/test.f
require lib/fs.f
require lib/test/src-shape.f

: CDT-TEST-NATIVE-INTERPRET ( -- )
   s" : EM-INTERPRET-DEFINE-KEYWORDS ( -- )" SHAPE:MUST-HAVE
   s" : EM-INTERPRET-STRING-KEYWORDS ( -- )" SHAPE:MUST-HAVE
   s" : EM-INTERPRET-NUMBER ( label -- )" SHAPE:MUST-HAVE
   s" : EM-INTERPRET-FIND ( -- )" SHAPE:MUST-HAVE
   s" EM-INTERPRET-DEFINE-KEYWORDS" 2 SHAPE:COUNT=
   s" EM-INTERPRET-STRING-KEYWORDS" 2 SHAPE:COUNT=
   s" EM-INTERPRET-NUMBER" 2 SHAPE:COUNT=
   s" EM-INTERPRET-FIND" 2 SHAPE:COUNT= ;

: CDT-TEST-NATIVE-COMPILE ( -- )
   s" : EM-COMPILE-CONTROL-KEYWORDS ( -- )" SHAPE:MUST-HAVE
   s" : EM-COMPILE-STRING-KEYWORDS ( -- )" SHAPE:MUST-HAVE
   s" : EM-COMPILE-META-KEYWORDS ( -- )" SHAPE:MUST-HAVE
   s" : EM-COMPILE-LOOP-KEYWORDS ( -- )" SHAPE:MUST-HAVE
   s" : EM-COMPILE-ARITH-OPS ( -- )" SHAPE:MUST-HAVE
   s" : EM-COMPILE-SHUFFLE-OPS ( -- )" SHAPE:MUST-HAVE
   s" : EM-COMPILE-COMPARE-OPS ( -- )" SHAPE:MUST-HAVE
   s" : EM-COMPILE-UNARY-OPS ( -- )" SHAPE:MUST-HAVE
   s" : EM-COMPILE-FLOAT-OPS ( -- )" SHAPE:MUST-HAVE
   s" : J-CASE ( -- )" SHAPE:MUST-HAVE
   s" : J-OF ( -- )" SHAPE:MUST-HAVE
   s" : J-ENDOF ( -- )" SHAPE:MUST-HAVE
   s" : J-ENDCASE ( -- )" SHAPE:MUST-HAVE
   s" LKWCASE 4 ['] J-CASE CFN-ENTRY" SHAPE:MUST-HAVE
   s" LKWOF 2 ['] J-OF CF-ENTRY" SHAPE:MUST-HAVE
   s" LKWENDOF 5 ['] J-ENDOF CF-ENTRY" SHAPE:MUST-HAVE
   s" LKWENDCASE 7 ['] J-ENDCASE CF-ENTRY" SHAPE:MUST-HAVE
   \ item 10: MATCH keyword lowered; CASE shape above is unchanged
   s" : J-MATCH ( -- )" SHAPE:MUST-HAVE
   s" : EM-ADT-MATCH-FAM ( -- )" SHAPE:MUST-HAVE
   s" : EM-MATCH-SEMI ( -- )" SHAPE:MUST-HAVE
   s" : C-DIE-BAD-TAG ( -- )" SHAPE:MUST-HAVE
   s" LKWMATCH 5 ['] J-MATCH CF-ENTRY" SHAPE:MUST-HAVE
   s" EM-COMPILE-CONTROL-KEYWORDS" 2 SHAPE:COUNT=
   s" EM-COMPILE-STRING-KEYWORDS" 2 SHAPE:COUNT=
   s" EM-COMPILE-META-KEYWORDS" 2 SHAPE:COUNT=
   s" EM-COMPILE-LOOP-KEYWORDS" 2 SHAPE:COUNT=
   s" EM-COMPILE-ARITH-OPS" 2 SHAPE:COUNT=
   s" EM-COMPILE-SHUFFLE-OPS" 2 SHAPE:COUNT=
   s" EM-COMPILE-COMPARE-OPS" 2 SHAPE:COUNT=
   s" EM-COMPILE-UNARY-OPS" 2 SHAPE:COUNT=
   s" EM-COMPILE-FLOAT-OPS" 2 SHAPE:COUNT= ;

: CDT-TEST-NATIVE-LOCAL ( -- )
   s" variable CLOC-MAIN  variable CLOC-NOT" SHAPE:MUST-HAVE
   s" variable CLOC-MEM   variable CLOC-QOK" SHAPE:MUST-HAVE
   s" : C-LOCAL-REF-ARGS ( label label -- )" SHAPE:MUST-HAVE
   s" : C-LOCAL-REF-LABELS ( -- )" SHAPE:MUST-HAVE
   s" : EMIT-RESET-BUILDER ( ptr u8 n -- )" SHAPE:MUST-HAVE
   s" C-LOCAL-REF-ARGS" 2 SHAPE:COUNT=
   s" C-LOCAL-REF-LABELS" 2 SHAPE:COUNT=
   s" {: lmainlbl notloc :}" SHAPE:MUST-LACK
   s" LBL LBL {: lmem qlrefok :}" SHAPE:MUST-LACK
   s" {: a:ptr u :}" SHAPE:MUST-LACK
   \ 3 = register path + memory path + the pass-2 width-aware reference
   \ (EM-P2-LOCREF branch, item 12 slice 3b)
   s" CLOC-MAIN LABEL@ B," 3 SHAPE:COUNT=
   s" CLOC-MAIN @ B ;" SHAPE:MUST-LACK
   s" CLOC-QOK LABEL@ LBL," SHAPE:MUST-HAVE
   s" CLOC-MEM LABEL@ LBL," SHAPE:MUST-HAVE ;

: CDT-TEST-SECTIONS ( -- )
   s" : EMIT-PRIMITIVE-SECTIONS ( -- )" SHAPE:MUST-HAVE
   s" : EMIT-DICTIONARY-SECTIONS ( -- )" SHAPE:MUST-HAVE
   s" : EMIT-RUNTIME-SECTIONS ( -- )" SHAPE:MUST-HAVE
   s" EMIT-PRIMITIVE-SECTIONS" 2 SHAPE:COUNT=
   s" EMIT-DICTIONARY-SECTIONS" 2 SHAPE:COUNT=
   s" EMIT-RUNTIME-SECTIONS" 2 SHAPE:COUNT=
   s" EMIT-PRIMS  EMIT-PROF-PRIMS  EMIT-FP-PRIMS" SHAPE:MUST-LACK
   s" EMIT-CF-HELPERS  EMIT-LOC-FIND  EMIT-KWDATA" SHAPE:MUST-LACK ;

: CDT-TEST-NATIVE ( -- )
   s" src/habu/habu2.f" SHAPE:LOAD
   CDT-TEST-NATIVE-INTERPRET
   CDT-TEST-NATIVE-COMPILE
   CDT-TEST-NATIVE-LOCAL
   CDT-TEST-SECTIONS ;

: CDT-TEST-HABU1 ( -- )
   s" src/habu/habu1.f" SHAPE:LOAD
   s" variable PR-A  variable PR-U  variable PR-L  variable PR-E" SHAPE:MUST-HAVE
   s" variable FP-A  variable FP-U  variable FP-XT" SHAPE:MUST-HAVE
   s" variable SDA-FD  variable SDA-NEW  variable SDA-SKIP" SHAPE:MUST-HAVE
   s" variable BSP-OK  variable BSP-DN  variable BSP-SAD" SHAPE:MUST-HAVE
   s" variable SZA-I" SHAPE:MUST-HAVE
   s" : REG-PRIM ( ptr u8 n n n -- )" SHAPE:MUST-HAVE
   s" : FPRIM ( ptr u8 n n -- )" SHAPE:MUST-HAVE
   s" : FPRIM-L ( ptr u8 n n -- )" SHAPE:MUST-HAVE
   s" : PR-COPY-NAME ( -- )" SHAPE:MUST-HAVE
   s" : BSP-LABELS3 ( -- )" SHAPE:MUST-HAVE
   s" : FPRIM {: na:ptr nu xt :}" SHAPE:MUST-LACK
   s" : FPRIM-L {: na:ptr nu xt :}" SHAPE:MUST-LACK
   s" : REG-PRIM {: na:ptr nu lbl elbl :}" SHAPE:MUST-LACK
   s" : ?PRIM-SPACE {: na:ptr nu :}" SHAPE:MUST-LACK
   s" : SPAWN-DUP2-ACTION ( reg fd -- )" SHAPE:MUST-HAVE
   s" : SPAWN-CHDIR-ACTION ( reg label -- )" SHAPE:MUST-HAVE
   s" : SPAWN-DUP2-ACTION ( n n -- ) {: fdreg newfd :}" SHAPE:MUST-LACK
   s" : SPAWN-CHDIR-ACTION ( n n -- ) {: cwdreg fail :}" SHAPE:MUST-LACK
   s" : BSPAWNIO" SHAPE:MUST-HAVE
   s" 14 SP SPAWN-ADESC-OFF SZA-I @ + STR," SHAPE:MUST-HAVE
   s" 14 SP SPAWN-ADESC-OFF + over + STR," SHAPE:MUST-LACK
   s" LBL LBL LBL {: spok spdn sad :}" SHAPE:MUST-LACK
   s" LBL LBL {: spok spdn :}" SHAPE:MUST-LACK ;

: CDT-TEST-ICODE ( -- )
   s" src/arch/arm64/icode.f" SHAPE:LOAD
   s" variable BYA" SHAPE:MUST-HAVE
   s" variable BYU" SHAPE:MUST-HAVE
   s" : BYA@ ( -- ptr u8 )" SHAPE:MUST-HAVE
   s" : BYTES-ARGS ( ptr u8 n -- )" SHAPE:MUST-HAVE
   s" : BYTES-CAP ( -- )" SHAPE:MUST-HAVE
   s" : BYTES-COPY ( -- )" SHAPE:MUST-HAVE
   s" : BYTES-PAD ( -- )" SHAPE:MUST-HAVE
   s" : BYTES, ( ptr u8 n -- )" SHAPE:MUST-HAVE
   s" {: a:ptr u :}" SHAPE:MUST-LACK ;

: CDT-TEST-BOOTSTRAP-COMPILE ( -- )
   s" : EMIT-COMPILE-CONTROL-KEYWORDS ( n -- )" SHAPE:MUST-HAVE
   s" : EMIT-COMPILE-STRING-KEYWORDS ( n -- )" SHAPE:MUST-HAVE
   s" : EMIT-COMPILE-META-KEYWORDS ( n -- )" SHAPE:MUST-HAVE
   s" : EMIT-COMPILE-LOOP-KEYWORDS ( n -- )" SHAPE:MUST-HAVE
   s" : EMIT-COMPILE-ARITH-OPS ( n -- )" SHAPE:MUST-HAVE
   s" : EMIT-COMPILE-SHUFFLE-OPS ( n -- )" SHAPE:MUST-HAVE
   s" : EMIT-COMPILE-COMPARE-OPS ( n -- )" SHAPE:MUST-HAVE
   s" : EMIT-COMPILE-UNARY-OPS ( n -- )" SHAPE:MUST-HAVE
   s" : EMIT-COMPILE-FLOAT-OPS ( n -- )" SHAPE:MUST-HAVE
   s" : J-CASE ( -- )" SHAPE:MUST-HAVE
   s" : J-OF ( -- )" SHAPE:MUST-HAVE
   s" : J-ENDOF ( -- )" SHAPE:MUST-HAVE
   s" : J-ENDCASE ( -- )" SHAPE:MUST-HAVE
   s" LKWCASE   4 ['] J-CASE   CFN-ENTRY" SHAPE:MUST-HAVE
   s" LKWOF     2 ['] J-OF     CF-ENTRY" SHAPE:MUST-HAVE
   s" LKWENDOF  5 ['] J-ENDOF  CF-ENTRY" SHAPE:MUST-HAVE
   s" LKWENDCASE 7 ['] J-ENDCASE CF-ENTRY" SHAPE:MUST-HAVE
   s" EMIT-COMPILE-CONTROL-KEYWORDS" 2 SHAPE:COUNT=
   s" EMIT-COMPILE-STRING-KEYWORDS" 2 SHAPE:COUNT=
   s" EMIT-COMPILE-META-KEYWORDS" 2 SHAPE:COUNT=
   s" EMIT-COMPILE-LOOP-KEYWORDS" 2 SHAPE:COUNT=
   s" EMIT-COMPILE-ARITH-OPS" 2 SHAPE:COUNT=
   s" EMIT-COMPILE-SHUFFLE-OPS" 2 SHAPE:COUNT=
   s" EMIT-COMPILE-COMPARE-OPS" 2 SHAPE:COUNT=
   s" EMIT-COMPILE-UNARY-OPS" 2 SHAPE:COUNT=
   s" EMIT-COMPILE-FLOAT-OPS" 2 SHAPE:COUNT= ;

: CDT-TEST-BOOTSTRAP ( -- )
   s" bootstrap/cg/forth.fs" SHAPE:LOAD
   CDT-TEST-BOOTSTRAP-COMPILE
   CDT-TEST-SECTIONS ;

: CDT-MAIN ( -- )
   T-RESET
   CDT-TEST-NATIVE
   CDT-TEST-HABU1
   CDT-TEST-ICODE
   CDT-TEST-BOOTSTRAP
   T-REPORT
   s" compiler-dispatch-test: ok" type cr ;

CDT-MAIN
