\ diff-side-content-test.f - side-content codec and reader regressions.
\ Run: bin/hb --load tools/diff-side-content-test.f

require lib/errors.f
require lib/prelude.f
require lib/string.f
require lib/test.f
require lib/fs.f
require src/core/sha256.f
require tools/diff-side-content.f
require tools/diff-side-content-read.f

package DIFF-CONTENT-TEST

1024 constant ART-CAP
8001 constant PROBE-U
168 constant EMPTY-ROW-U
176 constant ART-FIXED-U
1024 constant LARGE-N
LARGE-N EMPTY-ROW-U * ART-FIXED-U + constant LARGE-CAP

64 constant TEST-TRAILER-U
112 constant ROW0-OFF
152 constant ROW0-OLD-OFF
333 constant ROW1-OLD-OFF
504 constant ROW2-OLD-OFF

create ART ART-CAP allot
create WORK ART-CAP allot
create LARGE LARGE-CAP allot
create PATH-BUF 64 allot
create DIGEST $20 allot
create EXPECT-DIGEST $20 allot
create ZERO-DIGEST $20 allot
create PROBE-A PROBE-U allot
create PROBE-B PROBE-U allot
create NUL-PATH $61 c, 0 c, $62 c,
create ADV-PATH $61 c, $20 c, $09 c, $22 c, $5C c, $0A c, $0D c, $7A c,

variable ART-U

: META$ ( -- ptr u8 n )
   s" metadata binding\n" ;

: KIND-N ( content-kind -- n )
   MATCH content-kind
      absent  OF 0 ENDOF
      file    OF 1 ENDOF
      symlink OF 2 ENDOF
      gitlink OF 3 ENDOF
   ;MATCH ;

: FILL-PROBES ( -- )
   0 begin dup PROBE-U < while
      dup PROBE-A + $78 swap c!
      dup PROBE-B + $78 swap c!
      1+
   repeat drop
   0 PROBE-A 7999 + c!
   0 PROBE-B 8000 + c! ;

: FILL-ART ( -- )
   0 begin dup ART-CAP < while
      dup ART + $AA swap c!
      1+
   repeat drop ;

: ROW0-SIZES ( -- n n )
   5 DIFF-CONTENT:SIDE-SIZE 8 DIFF-CONTENT:SIDE-SIZE ;

: ROW1-SIZES ( -- n n )
   0 DIFF-CONTENT:SIDE-SIZE 3 DIFF-CONTENT:SIDE-SIZE ;

: ROW2-SIZES ( -- n n )
   3 DIFF-CONTENT:SIDE-SIZE 1 DIFF-CONTENT:SIDE-SIZE ;

: PAYLOAD-SIZE ( -- n )
   ROW0-SIZES DIFF-CONTENT:ROW-SIZE
   ROW1-SIZES DIFF-CONTENT:ROW-SIZE +
   ROW2-SIZES DIFF-CONTENT:ROW-SIZE + ;

: BUILD-ROW0 ( -- )
   ROW0-SIZES 0 -rot DIFF-CONTENT:ROW-BEGIN
   true DIFF-CONTENT:FILE-KIND s" empty" 0 DIFF-CONTENT:SIDE-BEGIN
   DIFF-CONTENT:SIDE-END
   true DIFF-CONTENT:FILE-KIND ADV-PATH 8 PROBE-U DIFF-CONTENT:SIDE-BEGIN
   PROBE-A PROBE-U DIFF-CONTENT:SIDE-CHUNK
   DIFF-CONTENT:SIDE-END
   DIFF-CONTENT:ROW-END ;

: BUILD-ROW1 ( -- )
   ROW1-SIZES 1 -rot DIFF-CONTENT:ROW-BEGIN
   false DIFF-CONTENT:ABSENT-KIND false s" " s" " DIFF-CONTENT:SIDE
   true DIFF-CONTENT:SYMLINK-KIND false s" sym" s" target" DIFF-CONTENT:SIDE
   DIFF-CONTENT:ROW-END ;

: BUILD-ROW2 ( -- )
   ROW2-SIZES 2 -rot DIFF-CONTENT:ROW-BEGIN
   true DIFF-CONTENT:GITLINK-KIND s" sub" 0 DIFF-CONTENT:SIDE-BEGIN
   DIFF-CONTENT:SIDE-END
   true DIFF-CONTENT:FILE-KIND s" n" PROBE-U DIFF-CONTENT:SIDE-BEGIN
   PROBE-B PROBE-U DIFF-CONTENT:SIDE-CHUNK
   DIFF-CONTENT:SIDE-END
   DIFF-CONTENT:ROW-END ;

: BUILD-ART ( -- )
   FILL-ART
   FILL-PROBES
   ART ART-CAP 3 META$ DIFF-CONTENT:START
   BUILD-ROW0 BUILD-ROW1 BUILD-ROW2
   DIFF-CONTENT:FINISH ART-U ! drop ;

: COPY-WORK ( -- )
   ART WORK ART-U @ BYTE-COPY ;

: TEST-U64! ( n ptr u8 -- ) {: value:n dst:ptr :}
   value 0 < if DIFF-CONTENT:E-SYNTAX throw then
   0 begin dup 8 < while
      dup 8 * value swap rshift $FF and
      over dst + c!
      1+
   repeat drop ;

: REHASH-WORK ( -- )
   SHA256-RESET
   WORK 32 SHA256-UPDATE
   ZERO-DIGEST $20 SHA256-UPDATE
   WORK 64 + ART-U @ TEST-TRAILER-U 2 * - SHA256-UPDATE
   DIGEST SHA256-FINAL
   DIGEST WORK 32 + $20 BYTE-COPY
   DIGEST WORK ART-U @ TEST-TRAILER-U - 32 + + $20 BYTE-COPY ;

: VALID-WORK ( -- n )
   WORK ART-U @ DIFF-CONTENT:VALIDATE ;

: EXPECT-PATH ( ptr u8 n bool -- ) {: want:ptr wantu:n old?:bool :}
   old? if
      PATH-BUF 64 DIFF-CONTENT:OLD-PATH
   else
      PATH-BUF 64 DIFF-CONTENT:NEW-PATH
   then {: gotu:n :}
   PATH-BUF gotu want wantu T$= ;

: EXPECT-HASH ( ptr u8 n bool -- ) {: body:ptr bodyu:n old?:bool :}
   body bodyu EXPECT-DIGEST SHA256
   old? if
      DIGEST DIFF-CONTENT:OLD-DIGEST
   else
      DIGEST DIFF-CONTENT:NEW-DIGEST
   then
   DIGEST $20 EXPECT-DIGEST $20 T$= ;

: ACCESS-BEFORE-SELECT ( -- )
   DIFF-CONTENT:OLD-PRESENT? drop ;

: TEST-ERROR-SCOPE ( -- )
   DIFF-CONTENT:E-SYNTAX -7500 T=
   DIFF-CONTENT:E-CAPACITY -7501 T=
   DIFF-CONTENT:E-DIGEST -7502 T= ;

: TEST-ROUNDTRIP ( -- )
   COPY-WORK
   WORK ART-U @ META$ DIFF-CONTENT:VALIDATE-BINDING 3 T=
   DIFF-CONTENT:COUNT 3 T=
   DIFF-CONTENT:METADATA-SIZE META$ nip T=
   META$ EXPECT-DIGEST SHA256
   DIGEST DIFF-CONTENT:METADATA-DIGEST
   DIGEST $20 EXPECT-DIGEST $20 T$=
   [: ACCESS-BEFORE-SELECT ;] DIFF-CONTENT:E-SYNTAX TTHROWSQ

   0 DIFF-CONTENT:ROW-SELECT
   DIFF-CONTENT:OLD-PRESENT? TTRUE
   DIFF-CONTENT:OLD-KIND KIND-N 1 T=
   DIFF-CONTENT:OLD-BINARY? TFALSE
   DIFF-CONTENT:OLD-CONTENT-SIZE 0 T=
   s" empty" true EXPECT-PATH
   s" " true EXPECT-HASH
   DIFF-CONTENT:NEW-PRESENT? TTRUE
   DIFF-CONTENT:NEW-KIND KIND-N 1 T=
   DIFF-CONTENT:NEW-BINARY? TTRUE
   DIFF-CONTENT:NEW-CONTENT-SIZE PROBE-U T=
   ADV-PATH 8 false EXPECT-PATH
   PROBE-A PROBE-U false EXPECT-HASH

   1 DIFF-CONTENT:ROW-SELECT
   DIFF-CONTENT:OLD-PRESENT? TFALSE
   DIFF-CONTENT:OLD-KIND KIND-N 0 T=
   DIFF-CONTENT:NEW-KIND KIND-N 2 T=
   DIFF-CONTENT:NEW-BINARY? TFALSE
   DIFF-CONTENT:NEW-CONTENT-SIZE 6 T=
   s" sym" false EXPECT-PATH
   s" target" false EXPECT-HASH

   2 DIFF-CONTENT:ROW-SELECT
   DIFF-CONTENT:OLD-KIND KIND-N 3 T=
   DIFF-CONTENT:OLD-CONTENT-SIZE 0 T=
   DIGEST DIFF-CONTENT:OLD-DIGEST
   DIGEST $20 ZERO-DIGEST $20 T$=
   DIFF-CONTENT:NEW-KIND KIND-N 1 T=
   DIFF-CONTENT:NEW-BINARY? TFALSE
   DIFF-CONTENT:NEW-CONTENT-SIZE PROBE-U T=
   PROBE-B PROBE-U false EXPECT-HASH ;

: TEST-OWNERSHIP ( -- )
   COPY-WORK
   VALID-WORK drop
   $78 WORK ROW0-OLD-OFF 64 + + c!
   0 DIFF-CONTENT:ROW-SELECT
   s" empty" true EXPECT-PATH
   $7A PATH-BUF c!
   s" empty" true EXPECT-PATH ;

: BAD-BINDING ( -- )
   WORK ART-U @ s" wrong" DIFF-CONTENT:VALIDATE-BINDING drop ;

: BAD-TRUNC ( -- )
   WORK ART-U @ 1- DIFF-CONTENT:VALIDATE drop ;

: BAD-MAGIC ( -- )
   $58 WORK c!
   VALID-WORK drop ;

: BAD-DIGEST ( -- )
   WORK ROW0-OLD-OFF 32 + + dup c@ 1 xor swap c!
   VALID-WORK drop ;

: BAD-TOP-U64 ( -- )
   WORK 31 + dup c@ $80 or swap c!
   VALID-WORK drop ;

: BAD-ORDER ( -- )
   1 WORK ROW0-OFF 8 + + TEST-U64!
   REHASH-WORK
   VALID-WORK drop ;

: BAD-COUNT ( -- )
   4 WORK 16 + TEST-U64!
   4 WORK ART-U @ TEST-TRAILER-U - 16 + + TEST-U64!
   REHASH-WORK
   VALID-WORK drop ;

: BAD-ABSENT-DIGEST ( -- )
   1 WORK ROW1-OLD-OFF 32 + + c!
   REHASH-WORK
   VALID-WORK drop ;

: BAD-GITLINK-DIGEST ( -- )
   1 WORK ROW2-OLD-OFF 32 + + c!
   REHASH-WORK
   VALID-WORK drop ;

: BAD-EMPTY-DIGEST ( -- )
   WORK ROW0-OLD-OFF 32 + + dup c@ 1 xor swap c!
   REHASH-WORK
   VALID-WORK drop ;

: BAD-EMPTY-BINARY ( -- )
   1 WORK ROW0-OLD-OFF 3 + + c!
   REHASH-WORK
   VALID-WORK drop ;

: BAD-ABSOLUTE-PATH ( -- )
   $2F WORK ROW0-OLD-OFF 64 + + c!
   REHASH-WORK
   VALID-WORK drop ;

: INVALID-COUNT ( -- )
   DIFF-CONTENT:COUNT drop ;

: TEST-REJECTIONS ( -- )
   COPY-WORK [: BAD-BINDING ;] DIFF-CONTENT:E-DIGEST TTHROWSQ
   COPY-WORK [: BAD-TRUNC ;] DIFF-CONTENT:E-CAPACITY TTHROWSQ
   COPY-WORK [: BAD-MAGIC ;] DIFF-CONTENT:E-SYNTAX TTHROWSQ
   [: INVALID-COUNT ;] DIFF-CONTENT:E-SYNTAX TTHROWSQ
   COPY-WORK [: BAD-DIGEST ;] DIFF-CONTENT:E-DIGEST TTHROWSQ
   COPY-WORK [: BAD-TOP-U64 ;] DIFF-CONTENT:E-CAPACITY TTHROWSQ
   COPY-WORK [: BAD-ORDER ;] DIFF-CONTENT:E-SYNTAX TTHROWSQ
   COPY-WORK [: BAD-COUNT ;] DIFF-CONTENT:E-SYNTAX TTHROWSQ
   COPY-WORK [: BAD-ABSENT-DIGEST ;] DIFF-CONTENT:E-DIGEST TTHROWSQ
   COPY-WORK [: BAD-GITLINK-DIGEST ;] DIFF-CONTENT:E-DIGEST TTHROWSQ
   COPY-WORK [: BAD-EMPTY-DIGEST ;] DIFF-CONTENT:E-DIGEST TTHROWSQ
   COPY-WORK [: BAD-EMPTY-BINARY ;] DIFF-CONTENT:E-SYNTAX TTHROWSQ
   COPY-WORK [: BAD-ABSOLUTE-PATH ;] DIFF-CONTENT:E-SYNTAX TTHROWSQ ;

: TEST-PATHS ( -- )
   s" safe" DIFF-CONTENT:SAFE-PATH? TTRUE
   ADV-PATH 8 DIFF-CONTENT:SAFE-PATH? TTRUE
   s" /abs" DIFF-CONTENT:SAFE-PATH? TFALSE
   NUL-PATH 3 DIFF-CONTENT:SAFE-PATH? TFALSE
   s" a//b" DIFF-CONTENT:SAFE-PATH? TFALSE
   s" a/" DIFF-CONTENT:SAFE-PATH? TFALSE
   s" ." DIFF-CONTENT:SAFE-PATH? TFALSE
   s" .." DIFF-CONTENT:SAFE-PATH? TFALSE
   s" a/./b" DIFF-CONTENT:SAFE-PATH? TFALSE
   s" a/../b" DIFF-CONTENT:SAFE-PATH? TFALSE ;

: BAD-START-CAP ( -- )
   ART 100 0 s" " DIFF-CONTENT:START ;

: BAD-SIDE-STATE ( -- )
   ART ART-CAP 0 s" " DIFF-CONTENT:START
   false DIFF-CONTENT:ABSENT-KIND s" " 0 DIFF-CONTENT:SIDE-BEGIN ;

: BAD-CHUNK-STATE ( -- )
   ART ART-CAP 0 s" " DIFF-CONTENT:START
   s" x" DIFF-CONTENT:SIDE-CHUNK ;

: BAD-ROW-STATE ( -- )
   ART ART-CAP 0 s" " DIFF-CONTENT:START
   DIFF-CONTENT:ROW-END ;

: BAD-ONE-SIDE ( -- )
   ART ART-CAP 1 s" " DIFF-CONTENT:START
   0 64 64 DIFF-CONTENT:ROW-BEGIN
   false DIFF-CONTENT:ABSENT-KIND s" " 0 DIFF-CONTENT:SIDE-BEGIN
   DIFF-CONTENT:SIDE-END
   DIFF-CONTENT:ROW-END ;

: BAD-BODY-SIZE ( -- )
   ART ART-CAP 1 s" " DIFF-CONTENT:START
   0 65 64 DIFF-CONTENT:ROW-BEGIN
   true DIFF-CONTENT:FILE-KIND s" x" 1 DIFF-CONTENT:SIDE-BEGIN
   DIFF-CONTENT:SIDE-END ;

: TEST-WRITER-STATE ( -- )
   [: BAD-START-CAP ;] DIFF-CONTENT:E-CAPACITY TTHROWSQ
   [: BAD-SIDE-STATE ;] DIFF-CONTENT:E-SYNTAX TTHROWSQ
   [: BAD-CHUNK-STATE ;] DIFF-CONTENT:E-SYNTAX TTHROWSQ
   [: BAD-ROW-STATE ;] DIFF-CONTENT:E-SYNTAX TTHROWSQ
   [: BAD-ONE-SIDE ;] DIFF-CONTENT:E-SYNTAX TTHROWSQ
   [: BAD-BODY-SIZE ;] DIFF-CONTENT:E-SYNTAX TTHROWSQ ;

: BEGIN-SIDE-REJECT ( -- )
   ART ART-CAP 1 s" " DIFF-CONTENT:START
   0 64 65 DIFF-CONTENT:ROW-BEGIN
   false DIFF-CONTENT:ABSENT-KIND s" " 0 DIFF-CONTENT:SIDE-BEGIN
   DIFF-CONTENT:SIDE-END ;

: BAD-SIDE-BINARY ( -- )
   true DIFF-CONTENT:FILE-KIND true s" x" s" x" DIFF-CONTENT:SIDE ;

: BAD-FINISH-AFTER-SIDE ( -- )
   DIFF-CONTENT:FINISH 2drop ;

: TEST-SIDE-ATOMIC ( -- )
   BEGIN-SIDE-REJECT
   [: BAD-SIDE-BINARY ;] DIFF-CONTENT:E-SYNTAX TTHROWSQ
   [: DIFF-CONTENT:ROW-END ;] DIFF-CONTENT:E-SYNTAX TTHROWSQ
   [: BAD-FINISH-AFTER-SIDE ;] DIFF-CONTENT:E-SYNTAX TTHROWSQ ;

: INTERFERENCE-SIZES ( -- n n )
   0 DIFF-CONTENT:SIDE-SIZE 1 DIFF-CONTENT:SIDE-SIZE ;

: BUILD-INTERFERENCE ( -- )
   ART ART-CAP 1 s" " DIFF-CONTENT:START
   INTERFERENCE-SIZES 0 -rot DIFF-CONTENT:ROW-BEGIN
   false DIFF-CONTENT:ABSENT-KIND s" " 0 DIFF-CONTENT:SIDE-BEGIN
   DIFF-CONTENT:SIDE-END
   true DIFF-CONTENT:FILE-KIND s" x" 3 DIFF-CONTENT:SIDE-BEGIN
   s" a" DIFF-CONTENT:SIDE-CHUNK
   s" unrelated" EXPECT-DIGEST SHA256
   s" bc" DIFF-CONTENT:SIDE-CHUNK
   DIFF-CONTENT:SIDE-END
   DIFF-CONTENT:ROW-END
   DIFF-CONTENT:FINISH ART-U ! drop ;

: TEST-SHA-INTERFERENCE ( -- )
   BUILD-INTERFERENCE
   ART ART-U @ DIFF-CONTENT:VALIDATE 1 T=
   0 DIFF-CONTENT:ROW-SELECT
   s" abc" false EXPECT-HASH ;

: BUILD-LARGE ( -- )
   LARGE LARGE-CAP LARGE-N s" " DIFF-CONTENT:START
   0 begin dup LARGE-N < while
      dup 64 64 DIFF-CONTENT:ROW-BEGIN
      false DIFF-CONTENT:ABSENT-KIND s" " 0 DIFF-CONTENT:SIDE-BEGIN
      DIFF-CONTENT:SIDE-END
      false DIFF-CONTENT:ABSENT-KIND s" " 0 DIFF-CONTENT:SIDE-BEGIN
      DIFF-CONTENT:SIDE-END
      DIFF-CONTENT:ROW-END
      1+
   repeat drop
   DIFF-CONTENT:FINISH ART-U ! drop ;

: TEST-LINEAR ( -- )
   BUILD-LARGE
   ART-U @ LARGE-CAP T=
   ART-U @ MEM-64K 2 * > TTRUE
   LARGE ART-U @ DIFF-CONTENT:VALIDATE LARGE-N T=
   DIFF-CONTENT:TRAVERSAL-STEPS 0 T=
   0 begin dup LARGE-N < while
      DIFF-CONTENT:ROW-NEXT? TTRUE
      DIFF-CONTENT:OLD-PRESENT? TFALSE
      1+
   repeat drop
   DIFF-CONTENT:ROW-NEXT? TFALSE
   DIFF-CONTENT:TRAVERSAL-STEPS LARGE-N T=
   0 DIFF-CONTENT:ROW-SELECT
   DIFF-CONTENT:TRAVERSAL-STEPS 1 T= ;

public

: RUN ( -- )
   T-RESET
   TEST-ERROR-SCOPE
   BUILD-ART
   ART-U @ PAYLOAD-SIZE DIFF-CONTENT:ARTIFACT-SIZE T=
   TEST-ROUNDTRIP
   TEST-OWNERSHIP
   TEST-REJECTIONS
   TEST-PATHS
   TEST-WRITER-STATE
   TEST-SIDE-ATOMIC
   TEST-SHA-INTERFERENCE
   TEST-LINEAR
   T-REPORT ;

;package

DIFF-CONTENT-TEST:RUN
