\ diff-capture-content-test.f - bulk-provider contract fixtures.

require lib/errors.f
require lib/test.f
require lib/memory.f
require src/core/sha256.f
require tools/diff-capture-content.f

package DIFF-META
public

: CONTENT-RECORD ( n n n -- )
   {: old-kind:n new-kind:n status:n :}
   1 REC-N !
   REC-CELLS >COUNT MEM-ALLOC-CELLS REC-A !
   0 begin dup REC-CELLS < while
      0 0 over REC!
      1+
   repeat drop
   status 0 R-STATUS REC!
   old-kind 0 R-OLD-KIND REC!
   new-kind 0 R-NEW-KIND REC! ;

: CONTENT-ABSENT-KIND ( -- n )
   KIND-ABSENT ;

: CONTENT-FILE-KIND ( -- n )
   KIND-FILE ;

: CONTENT-SYMLINK-KIND ( -- n )
   KIND-SYMLINK ;

: CONTENT-GITLINK-KIND ( -- n )
   KIND-GITLINK ;

;package

package DIFF-CONTENT-TEST
private

$20 constant DIGEST-U
create OLD-DIGEST DIGEST-U allot
create NEW-DIGEST DIGEST-U allot
create META 1 allot
create PATH 1 allot
variable OLD-SIZE
variable NEW-SIZE
variable OLD-BINARY
variable NEW-BINARY
variable OLD-DIGEST-U
variable NEW-DIGEST-U

: FACTS ( -- )
   s" old" OLD-DIGEST SHA256
   s" new" NEW-DIGEST SHA256
   1 OLD-SIZE !
   1 NEW-SIZE !
   false OLD-BINARY !
   false NEW-BINARY !
   DIGEST-U OLD-DIGEST-U !
   DIGEST-U NEW-DIGEST-U ! ;

: RECORD ( n n n -- )
   DIFF-META:CONTENT-RECORD
   FACTS ;

: ROW ( n -- )
   OLD-SIZE @ OLD-BINARY @ OLD-DIGEST OLD-DIGEST-U @
   NEW-SIZE @ NEW-BINARY @ NEW-DIGEST NEW-DIGEST-U @
   DIFF-CONTENT:CONTENT-ROW! ;

: PROVIDER ( -- )
   0 ROW ;

: DUPLICATE-PROVIDER ( -- )
   0 ROW
   0 ROW ;

: RANGE-PROVIDER ( -- )
   1 ROW ;

: NEGATIVE-PROVIDER ( -- )
   -1 ROW ;

: INCOMPLETE-PROVIDER ( -- )
   DIFF-CONTENT:CONTENT-METADATA$ 2drop
   DIFF-CONTENT:CONTENT-METADATA-PATH$ 2drop
   DIFF-CONTENT:CONTENT-ROW-COUNT drop ;

: PROVIDER-RUN ( -- )
   [: PROVIDER ;] DIFF-CONTENT:CONTENT-PROVIDER!
   DIFF-CONTENT:PROVIDE ;

: DUPLICATE-RUN ( -- )
   [: DUPLICATE-PROVIDER ;] DIFF-CONTENT:CONTENT-PROVIDER!
   DIFF-CONTENT:PROVIDE ;

: RANGE-RUN ( -- )
   [: RANGE-PROVIDER ;] DIFF-CONTENT:CONTENT-PROVIDER!
   DIFF-CONTENT:PROVIDE ;

: NEGATIVE-RUN ( -- )
   [: NEGATIVE-PROVIDER ;] DIFF-CONTENT:CONTENT-PROVIDER!
   DIFF-CONTENT:PROVIDE ;

: INCOMPLETE-RUN ( -- )
   [: INCOMPLETE-PROVIDER ;] DIFF-CONTENT:CONTENT-PROVIDER!
   DIFF-CONTENT:PROVIDE ;

: EXPECT-FAIL ( -- )
   [: PROVIDER-RUN ;] E-DIFF-CAPTURE TTHROWSQ
   DIFF-CONTENT:RESET ;

: OUTSIDE-METADATA ( -- )
   DIFF-CONTENT:CONTENT-METADATA$ 2drop ;

: OUTSIDE-PATH ( -- )
   DIFF-CONTENT:CONTENT-METADATA-PATH$ 2drop ;

: OUTSIDE-COUNT ( -- )
   DIFF-CONTENT:CONTENT-ROW-COUNT drop ;

: OUTSIDE-ROW ( -- )
   0 0 false OLD-DIGEST DIGEST-U
   0 false NEW-DIGEST DIGEST-U
   DIFF-CONTENT:CONTENT-ROW! ;

: DUPLICATE ( -- )
   DIFF-META:CONTENT-FILE-KIND DIFF-META:CONTENT-FILE-KIND 0 RECORD
   [: DUPLICATE-RUN ;] E-DIFF-CAPTURE TTHROWSQ
   DIFF-CONTENT:RESET ;

: RANGE ( -- )
   DIFF-META:CONTENT-FILE-KIND DIFF-META:CONTENT-FILE-KIND 0 RECORD
   [: RANGE-RUN ;] E-DIFF-CAPTURE TTHROWSQ
   DIFF-CONTENT:RESET ;

: NEGATIVE ( -- )
   DIFF-META:CONTENT-FILE-KIND DIFF-META:CONTENT-FILE-KIND 0 RECORD
   [: NEGATIVE-RUN ;] E-DIFF-CAPTURE TTHROWSQ
   DIFF-CONTENT:RESET ;

: OLD-DIGEST-LENGTH ( -- )
   DIFF-META:CONTENT-FILE-KIND DIFF-META:CONTENT-FILE-KIND 0 RECORD
   DIGEST-U 1- OLD-DIGEST-U !
   EXPECT-FAIL ;

: NEW-DIGEST-LENGTH ( -- )
   DIFF-META:CONTENT-FILE-KIND DIFF-META:CONTENT-FILE-KIND 0 RECORD
   DIGEST-U 1- NEW-DIGEST-U !
   EXPECT-FAIL ;

: OLD-NEGATIVE-SIZE ( -- )
   DIFF-META:CONTENT-FILE-KIND DIFF-META:CONTENT-FILE-KIND 0 RECORD
   -1 OLD-SIZE !
   EXPECT-FAIL ;

: NEW-NEGATIVE-SIZE ( -- )
   DIFF-META:CONTENT-FILE-KIND DIFF-META:CONTENT-FILE-KIND 0 RECORD
   -1 NEW-SIZE !
   EXPECT-FAIL ;

: OLD-ABSENT-SIZE ( -- )
   DIFF-META:CONTENT-ABSENT-KIND DIFF-META:CONTENT-FILE-KIND 1 RECORD
   1 OLD-SIZE !
   EXPECT-FAIL ;

: NEW-ABSENT-SIZE ( -- )
   DIFF-META:CONTENT-FILE-KIND DIFF-META:CONTENT-ABSENT-KIND 2 RECORD
   1 NEW-SIZE !
   EXPECT-FAIL ;

: OLD-ABSENT-BINARY ( -- )
   DIFF-META:CONTENT-ABSENT-KIND DIFF-META:CONTENT-FILE-KIND 1 RECORD
   0 OLD-SIZE ! true OLD-BINARY !
   EXPECT-FAIL ;

: NEW-ABSENT-BINARY ( -- )
   DIFF-META:CONTENT-FILE-KIND DIFF-META:CONTENT-ABSENT-KIND 2 RECORD
   0 NEW-SIZE ! true NEW-BINARY !
   EXPECT-FAIL ;

: OLD-GITLINK-SIZE ( -- )
   DIFF-META:CONTENT-GITLINK-KIND DIFF-META:CONTENT-GITLINK-KIND 0 RECORD
   1 OLD-SIZE ! 0 NEW-SIZE !
   EXPECT-FAIL ;

: NEW-GITLINK-SIZE ( -- )
   DIFF-META:CONTENT-GITLINK-KIND DIFF-META:CONTENT-GITLINK-KIND 0 RECORD
   0 OLD-SIZE ! 1 NEW-SIZE !
   EXPECT-FAIL ;

: OLD-GITLINK-BINARY ( -- )
   DIFF-META:CONTENT-GITLINK-KIND DIFF-META:CONTENT-GITLINK-KIND 0 RECORD
   0 OLD-SIZE ! 0 NEW-SIZE ! true OLD-BINARY !
   EXPECT-FAIL ;

: NEW-GITLINK-BINARY ( -- )
   DIFF-META:CONTENT-GITLINK-KIND DIFF-META:CONTENT-GITLINK-KIND 0 RECORD
   0 OLD-SIZE ! 0 NEW-SIZE ! true NEW-BINARY !
   EXPECT-FAIL ;

: OLD-SYMLINK-BINARY ( -- )
   DIFF-META:CONTENT-SYMLINK-KIND DIFF-META:CONTENT-SYMLINK-KIND 0 RECORD
   true OLD-BINARY !
   EXPECT-FAIL ;

: NEW-SYMLINK-BINARY ( -- )
   DIFF-META:CONTENT-SYMLINK-KIND DIFF-META:CONTENT-SYMLINK-KIND 0 RECORD
   true NEW-BINARY !
   EXPECT-FAIL ;

: MAIN ( -- )
   T-RESET
   META 0 PATH 0 DIFF-CONTENT:CONFIGURE
   DIFF-CONTENT:RESET
   [: OUTSIDE-METADATA ;] E-DIFF-CAPTURE TTHROWSQ
   [: OUTSIDE-PATH ;] E-DIFF-CAPTURE TTHROWSQ
   [: OUTSIDE-COUNT ;] E-DIFF-CAPTURE TTHROWSQ
   [: OUTSIDE-ROW ;] E-DIFF-CAPTURE TTHROWSQ
   [: DIFF-CONTENT:PROVIDE ;] E-DIFF-CAPTURE TTHROWSQ
   DIFF-META:CONTENT-FILE-KIND DIFF-META:CONTENT-FILE-KIND 0 RECORD
   [: INCOMPLETE-RUN ;] E-DIFF-CAPTURE TTHROWSQ
   DIFF-CONTENT:RESET
   DUPLICATE
   RANGE
   NEGATIVE
   OLD-DIGEST-LENGTH
   NEW-DIGEST-LENGTH
   OLD-NEGATIVE-SIZE
   NEW-NEGATIVE-SIZE
   OLD-ABSENT-SIZE
   NEW-ABSENT-SIZE
   OLD-ABSENT-BINARY
   NEW-ABSENT-BINARY
   OLD-GITLINK-SIZE
   NEW-GITLINK-SIZE
   OLD-GITLINK-BINARY
   NEW-GITLINK-BINARY
   OLD-SYMLINK-BINARY
   NEW-SYMLINK-BINARY
   T-REPORT
   s" diff-capture-content-test: ok" type cr ;

MAIN

;package
