\ ptx-ad-test.f - runnable tests for the reverse-mode AD pass v0.

require lib/ptx/test-prelude.f

package PTX-AD-TEST

using PTX-AD

: VJP-MEMORY ( -- )
   s" LOAD" VJP-EXPAND s" SCATTER-ADD" STR= TTRUE
   s" STORE" VJP-EXPAND s" LOAD" STR= TTRUE
   s" LOAD-ONCE" VJP-EXPAND s" STORE-ONCE" STR= TTRUE
   s" STORE-ONCE" VJP-EXPAND s" LOAD-ONCE" STR= TTRUE ;

: VJP-STACK ( -- )
   s" DUP" VJP-EXPAND s" +." STR= TTRUE
   s" +." VJP-EXPAND s" DUP" STR= TTRUE
   s" NEG" VJP-EXPAND s" NEG" STR= TTRUE ;

: VJP-COLLECTIVE ( -- )
   s" BLOCK-SUM" VJP-EXPAND s" BROADCAST" STR= TTRUE
   s" BROADCAST" VJP-EXPAND s" BLOCK-SUM" STR= TTRUE ;

: VJP-ROW ( -- )
   s" ROW-LOAD" VJP-EXPAND s" ROW-SCATTER-ADD" STR= TTRUE
   s" ROW-LOAD-ONCE" VJP-EXPAND s" ROW-STORE-ONCE" STR= TTRUE
   s" ROW-STORE-ONCE" VJP-EXPAND s" ROW-LOAD-ONCE" STR= TTRUE ;

: REVERSE-LINEAR ( -- )
   s" LOAD DUP BLOCK-SUM" AD-REVERSE
      s" BROADCAST +. SCATTER-ADD" STR= TTRUE
   s" +." AD-REVERSE s" DUP" STR= TTRUE
   s" LOAD LOAD +. STORE" AD-REVERSE
      s" LOAD DUP SCATTER-ADD SCATTER-ADD" STR= TTRUE ;

: REVERSE-ROW ( -- )
   s" ROW-LOAD BLOCK-SUM BROADCAST ROW-STORE" AD-REVERSE
      s" ROW-LOAD BLOCK-SUM BROADCAST ROW-SCATTER-ADD" STR= TTRUE
   s" LOAD-ONCE DUP STORE-ONCE" AD-REVERSE
      s" LOAD-ONCE +. STORE-ONCE" STR= TTRUE
   s" ROW-LOAD-ONCE ROW-STORE-ONCE" AD-REVERSE
      s" ROW-LOAD-ONCE ROW-STORE-ONCE" STR= TTRUE ;

: BAD-VJP ( -- )
   s" NO-SUCH-OP" VJP-EXPAND 2drop ;

: BAD-AD-CONTROL ( -- )
   s" LOAD if STORE then" AD-REVERSE 2drop ;

: FAILS-CLOSED ( -- )
   [: BAD-VJP ;] E-PTX-NOVJP TTHROWSQ
   [: BAD-AD-CONTROL ;] E-PTX-AD-CONTROL TTHROWSQ ;

: VJP-NONLINEAR ( -- )
   s" SCALE" VJP-EXPAND
      s" DUP SAVED-A SCALE SWAP SAVED-X *. BLOCK-SUM" STR= TTRUE
   s" -." VJP-EXPAND s" DUP NEG" STR= TTRUE ;

: SAVE-COUNTS ( -- )
   s" EXP." VJP-SAVES 1 T=
   s" *." VJP-SAVES 2 T=
   s" BLOCK-MAX" VJP-SAVES 2 T=
   s" +." VJP-SAVES 0 T=
   s" LOAD" VJP-SAVES 0 T= ;

: NONLINEAR? ( -- )
   s" EXP." VJP-NONLINEAR? TTRUE
   s" +." VJP-NONLINEAR? TFALSE ;

: RECOMPUTE? ( -- )
   10 3 AD-RECOMPUTE? TTRUE
   3 10 AD-RECOMPUTE? TFALSE ;

: SLICE-COSTS ( -- )
   s" ROW-LOAD EXP. ROW-STORE" AD-SLICE-COST 9 T=
   s" ROW-LOAD DUP BLOCK-MAX PTX:B- EXP. DUP BLOCK-SUM PTX:B/ ROW-STORE"
      AD-SLICE-COST 75 T=
   0 0= AD-SAVE-COST 8 T=
   0 0= 0= AD-SAVE-COST 16 T= ;

: SAVE-CHOICES ( -- )
   s" ROW-LOAD DUP BLOCK-MAX PTX:B- EXP. DUP BLOCK-SUM PTX:B/ ROW-STORE"
      0 0= AD-SAVE? TTRUE
   s" ROW-LOAD EXP. ROW-STORE" 0 0= 0= AD-SAVE? TFALSE ;

: BAD-COST ( -- )
   s" ROW-LOAD FROB ROW-STORE" AD-SLICE-COST drop ;

: BAD-POLICY ( -- )
   3 AD-POLICY! ;

: COST-FAILS-CLOSED ( -- )
   [: BAD-COST ;] E-PTX-AD-UNKNOWN TTHROWSQ
   [: BAD-POLICY ;] E-PTX-SYNTAX TTHROWSQ ;

: FORCE-SAVE ( -- )
   AD-POLICY-SAVE AD-POLICY!
   s" ROW-LOAD EXP. ROW-STORE" 0 0= 0= AD-SAVE? TTRUE ;

: FORCE-RECOMPUTE ( -- )
   AD-POLICY-RECOMPUTE AD-POLICY!
   s" ROW-LOAD DUP BLOCK-MAX PTX:B- EXP. DUP BLOCK-SUM PTX:B/ ROW-STORE"
      0 0= AD-SAVE? TFALSE ;

: POLICY-OVERRIDES ( -- )
   FORCE-SAVE FORCE-RECOMPUTE
   AD-POLICY-AUTO AD-POLICY!
   s" ROW-LOAD EXP. ROW-STORE" 0 0= 0= AD-SAVE? TFALSE ;

: REVERSE-NONLINEAR-UNARY ( -- )
   s" LOAD EXP. STORE" AD-REVERSE
      s" LOAD SAVED-Y *. SCATTER-ADD" STR= TTRUE
   s" ROW-LOAD BLOCK-MAX ROW-STORE" AD-REVERSE
      s" ROW-LOAD SAVED-X SAVED-MX BLOCK-MAX-SELECT ROW-SCATTER-ADD" STR= TTRUE ;

: REVERSE-NONLINEAR-BINARY ( -- )
   s" LOAD *. STORE" AD-REVERSE
      s" LOAD DUP SAVED-Y *. SWAP SAVED-X *. SCATTER-ADD" STR= TTRUE
   s" LOAD PTX:B- STORE" AD-REVERSE
      s" LOAD DUP BLOCK-SUM NEG SCATTER-ADD" STR= TTRUE ;

: REVERSE-DIV ( -- )
   s" LOAD PTX:B/ STORE" AD-REVERSE
      s" LOAD DUP SAVED-S PTX:B/ SWAP SAVED-Z *. BLOCK-SUM NEG SAVED-S PTX:U/ SCATTER-ADD"
      STR= TTRUE
   s" LOAD DUP BLOCK-MAX PTX:B- EXP. DUP BLOCK-SUM PTX:B/"
      AD-REVERSE nip 0 > TTRUE ;

: SIMPLIFIES ( -- )
   s" NEG NEG" AD-SIMPLIFY s" " STR= TTRUE
   s" DUP NEG NEG +." AD-SIMPLIFY s" DUP +." STR= TTRUE
   s" NEG" AD-SIMPLIFY s" NEG" STR= TTRUE
   s" +. STORE" AD-SIMPLIFY s" +. STORE" STR= TTRUE ;

: VJP-TESTS ( -- )
   VJP-MEMORY VJP-STACK VJP-COLLECTIVE VJP-ROW
   VJP-NONLINEAR SAVE-COUNTS NONLINEAR? ;

: REVERSE-TESTS ( -- )
   REVERSE-LINEAR REVERSE-ROW FAILS-CLOSED
   REVERSE-NONLINEAR-UNARY REVERSE-NONLINEAR-BINARY REVERSE-DIV ;

: COST-TESTS ( -- )
   RECOMPUTE? SLICE-COSTS SAVE-CHOICES
   COST-FAILS-CLOSED POLICY-OVERRIDES ;

public

: RUN ( -- )
   T-RESET
   VJP-TESTS REVERSE-TESTS COST-TESTS
   SIMPLIFIES
   T-REPORT ;

;using

;package

PTX-AD-TEST:RUN
