\ ptx-ir-test.f - static value fixtures for the PTX IR optimizer seed.

T-RESET

: PTXIRT-FOLD ( -- )
   PTXIR-RESET
   2 PTXIR-CONST 3 PTXIR-CONST PTXIR-ADD {: sum:n :}
   sum PTXIR-CONST? TTRUE
   sum PTXIR-CONST-VAL 5 T=
   4 PTXIR-CONST 3 PTXIR-CONST PTXIR-MUL {: prod:n :}
   prod PTXIR-CONST-VAL 12 T= ;

: PTXIRT-PEEPHOLE ( -- )
   PTXIR-RESET
   PTXIR-INPUT {: x:n :}
   x PTXIR-NEG PTXIR-NEG x T=
   x 0 PTXIR-CONST PTXIR-ADD x T=
   x 1 PTXIR-CONST PTXIR-MUL x T=
   x PTXIR-RENDER s" y" STR= TTRUE ;

: PTXIRT-CSE ( -- )
   PTXIR-RESET
   PTXIR-INPUT {: x:n :}
   1 PTXIR-CONST {: one:n :}
   x one PTXIR-ADD {: a:n :}
   one x PTXIR-ADD {: b:n :}
   a b T=
   PTXIR-COUNT 3 T= ;

: PTXIRT-INPUT-SYMS ( -- )
   PTXIR-RESET
   0 PTXIR-INPUT# {: x:n :}
   1 PTXIR-INPUT# {: y:n :}
   0 PTXIR-INPUT# x T=
   x y <> TTRUE
   PTXIR-COUNT 2 T= ;

: PTXIRT-DCE ( -- )
   PTXIR-RESET
   PTXIR-INPUT {: x:n :}
   x 2 PTXIR-CONST PTXIR-ADD {: root:n :}
   x 3 PTXIR-CONST PTXIR-MUL {: dead:n :}
   root PTXIR-LIVE-COUNT 3 T=
   root PTXIR-LIVE@ TTRUE
   dead PTXIR-LIVE@ TFALSE ;

: PTXIRT-SOFTMAX-BWD ( -- )
   PTXIR-RESET
   0 PTXIR-INPUT# {: y:n :}
   1 PTXIR-INPUT# {: dy:n :}
   dy y PTXIR-MUL PTXIR-BSUM {: s:n :}
   dy s PTXIR-BSUB y PTXIR-MUL {: dx:n :}
   dx PTXIR-OP@ PTXIR-K-MUL T=
   dx PTXIR-A@ y T=
   dx PTXIR-B@ PTXIR-OP@ PTXIR-K-BSUB T=
   dx PTXIR-LIVE-COUNT 6 T=
   dx PTXIR-RENDER s" y dy y dy *. BLOCK-SUM PTX:B- *." STR= TTRUE ;

: PTXIRT-RENDER ( -- )
   PTXIR-RESET
   2 PTXIR-CONST 3 PTXIR-CONST PTXIR-ADD {: folded:n :}
   folded PTXIR-RENDER s" 5" STR= TTRUE
   2 PTXIR-INPUT# 1 PTXIR-CONST PTXIR-ADD
   PTXIR-RENDER s" i2 1 +." STR= TTRUE ;

: PTXIRT-OVERFLOW ( -- )
   PTXIR-RESET
   PTXIR-MAX 0 ?do i PTXIR-CONST drop loop
   PTXIR-MAX PTXIR-CONST drop ;

PTXIRT-FOLD
PTXIRT-PEEPHOLE
PTXIRT-CSE
PTXIRT-INPUT-SYMS
PTXIRT-DCE
PTXIRT-SOFTMAX-BWD
PTXIRT-RENDER
' PTXIRT-OVERFLOW E-PTX-IR-OVERFLOW TTHROWS

T-REPORT
